### ISSUE TITLE
Invalid Schema for fbaInventory Model

### ISSUE THREAD

**Issue by BilalHasanKhan** [amzn/selling-partner-api-models#1]
I was trying to generate typescript client and encountered this in fbaInventory, I was using swaxios package for this. Interestingly with some other packages it works but I also tried to validate schema [here](https://apitools.dev/swagger-parser/online/) but it still shows the same issues
stack: 'SyntaxError: Swagger schema validation failed. \n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/503\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/503/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/503\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/500\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/500/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/500\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/429\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/429/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/429\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/404\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/404/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/404\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/403\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/403/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/403\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/400\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/400/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/400\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/200\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/200/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/200\n' +
    ' \n' +
    'JSON_OBJECT_VALIDATION_FAILED\n' +
    '    at validateSchema (C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\swaxios\\node_modules\\swagger-parser\\lib\\validators\\schema.js:27:15)\n' +
    '    at SwaggerParser.validate (C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\swaxios\\node_modules\\swagger-parser\\lib\\index.js:155:7)\n' +
    '\n' +
    'z-schema validation error: JSON_OBJECT_VALIDATION_FAILED\n' +
    '    at ZSchema.getLastError (C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\swaxios\\node_modules\\z-schema\\src\\ZSchema.js:260:13)\n' +
    '    at validateSchema (C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\swaxios\\node_modules\\swagger-parser\\lib\\validators\\schema.js:25:23)\n' +
    '    at SwaggerParser.validate (C:\\Users\\bilal\\AppData\\Roaming\\npm\\node_modules\\swaxios\\node_modules\\swagger-parser\\lib\\index.js:155:7)',
  message: 'Swagger schema validation failed. \n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/503\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/503/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/503\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/500\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/500/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/500\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/429\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/429/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/429\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/404\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/404/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/404\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/403\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/403/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/403\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/400\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/400/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/400\n' +
    "  Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/200\n" +
    "    Data does not match any schemas from 'oneOf' at #/paths//fba/inventory/v1/summaries/get/responses/200/schema\n" +
    '      Expected type object but found type array at #/schema/properties/payload/properties/granularity/properties/x-docgen-enum-table-extension\n' +
    '      Additional properties not allowed: properties at #/schema\n' +
    '    Missing required property: $ref at #/paths//fba/inventory/v1/summaries/get/responses/200\n' +
    ' \n' +
    'JSON_OBJECT_VALIDATION_FAILED',
  details: [
    {
      code: 'ONE_OF_MISSING',
      params: [],
      message: "Data does not match any schemas from 'oneOf'",
      path: [Array],
      schemaId: undefined,
      inner: [Array],
      [Symbol(z-schema/schema)]: [Object],
      [Symbol(z-schema/json)]: [Object]
    },
    {
      code: 'ONE_OF_MISSING',
      params: [],
      message: "Data does not match any schemas from 'oneOf'",
      path: [Array],
      schemaId: undefined,
      inner: [Array],
      [Symbol(z-schema/schema)]: [Object],
      [Symbol(z-schema/json)]: [Object]
    },
    {
      code: 'ONE_OF_MISSING',
      params: [],
      message: "Data does not match any schemas from 'oneOf'",
      path: [Array],
      schemaId: undefined,
      inner: [Array],
      [Symbol(z-schema/schema)]: [Object],
      [Symbol(z-schema/json)]: [Object]
    },
    {
      code: 'ONE_OF_MISSING',
      params: [],
      message: "Data does not match any schemas from 'oneOf'",
      path: [Array],
      schemaId: undefined,
      inner: [Array],
      [Symbol(z-schema/schema)]: [Object],
      [Symbol(z-schema/json)]: [Object]
    },
    {
      code: 'ONE_OF_MISSING',
      params: [],
      message: "Data does not match any schemas from 'oneOf'",
      path: [Array],
      schemaId: undefined,
      inner: [Array],
      [Symbol(z-schema/schema)]: [Object],
      [Symbol(z-schema/json)]: [Object]
    },
    {
      code: 'ONE_OF_MISSING',
      params: [],
      message: "Data does not match any schemas from 'oneOf'",
      path: [Array],
      schemaId: undefined,
      inner: [Array],
      [Symbol(z-schema/schema)]: [Object],
      [Symbol(z-schema/json)]: [Object]
    },
    {
      code: 'ONE_OF_MISSING',
      params: [],
      message: "Data does not match any schemas from 'oneOf'",
      path: [Array],
      schemaId: undefined,
      inner: [Array],
      [Symbol(z-schema/schema)]: [Object],
      [Symbol(z-schema/json)]: [Object]
    }
  ],
  toJSON: [Function: toJSON],
  name: 'SyntaxError',
  toString: [Function: toString]
}

**Comment by BilalHasanKhan** [comment]
The error goes away if I remove ;

 "enum": [
          "Marketplace"
        ],
        "x-docgen-enum-table-extension": [
          {
            "value": "Marketplace",
            "description": "Marketplace"
          }
from Granularity.

Thoughts?

**Comment by evdeg** [comment]
@BilalHasanKhan Thanks for bringing this issue to our attention! We are investigating it and will update you with our findings as soon as they are available.

**Comment by weitzhandler** [comment]
Pasting the info FBA Inventory API into [editor.swagger.io](https://editor.swagger.io) generates the following error ([credit](https://github.com/unchase/Unchase.OpenAPI.Connectedservice/issues/29#issuecomment-694178958)):

![image](https://user-images.githubusercontent.com/2716316/93473278-7ebe3e00-f8fe-11ea-9697-5d55473b741f.png)

**Comment by evdeg** [comment]
Our team has reviewed this issue and corrected the model. The fix was pushed today in [ec9973c](https://github.com/amzn/selling-partner-api-models/commit/ec9973c291069979dbb3f44be6102608d667452c). Thanks again for bringing this to our attention!
