### ISSUE TITLE
[Auth] The authorization grant type is not supported by the authorization server

### ISSUE THREAD

**Issue by twanlee** [amzn/selling-partner-api-models#1012]
Hello you guys, i'm recenly got Error getting LWA Access Token while using SDK to connect to SP API. Then i test it on Postman like instruction here: https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-request-a-login-with-amazon-access-token
then i've got response: {
    "error_description": "The authorization grant type is not supported by the authorization server",
    "error": "unsupported_grant_type"
},
I read a document again and again, try with LWA Credentials in my app. Seems like nothing wrong. If anyone has got this issued, please share your experience!!!!

**Comment by yehia-salah** [comment]
Starting from Laravel Passport v12, Laravel no longer enables the password grant by default for security reasons. Instead, you need to explicitly enable it in your application.

To enable the password grant, call the "enablePasswordGrant" method in the boot method of your application's

App\Providers\AppServiceProvider class:

```
/**
 * Bootstrap any application services.
 */

public function boot(): void
{
    Passport::enablePasswordGrant();
}
```
