### ISSUE TITLE
Unauthorized when trying to get /catalog/v0/items while getting /orders/v0/orders works fine

### ISSUE THREAD

**Issue by kwimbeep** [amzn/selling-partner-api-models#1035]
Greetings, /catalog/v0/items returns "Access to requested resource is denied" error.
Getting orders and /products/pricing/v0/price works ok.

At first getting orders did not work as well, but after AssumeRole it works now.
For item listing I'm using the same tokens, same marketplace etc, but still getting the error.

App is using self authorization with role as IAM ARN. In App Settings page I have checked these roles: Finance and Accounting, Pricing, Inventory and Order Tracking, Amazon Fulfillment and Product Listing.

What could be the problem? Does anyone have any idea?

**Comment by QasimMughal05** [comment]
Check out permission in your seller center. Then you will be able to get it

**Comment by AntonioPereiraTetris** [comment]
HI guys, 2025 and the bug continues happened, unfortunately.

**Comment by Jonjago** [comment]
Hello, i have the same Problem when i try to use:

https://sellingpartnerapi-eu.amazon.com//catalog/2022-04-01/items/B0DWDWK591?marketplaceIds=A1PA6795UKMFR9&includedData=summaries&locale=de_DE


{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}

my roles: 

<img width="898" height="831" alt="Image" src="https://github.com/user-attachments/assets/6b80be80-c39f-49b1-b8b8-a85c020fcd00" />

**Comment by Sleepy-Git-User** [comment]
Im getting the same issue too, but with a Vendor account. That has Brand Analytics, Product Listings and Amazon Warehousing and Distribution permissions selected. 

https://sellingpartnerapi-eu.amazon.com/catalog/2022-04-01/items/B0783PTCZD?marketplaceIds=A1F83G8C2ARO7P&includedData=summaries

{
"errors": [
{
"code": "Unauthorized",
"message": "Access to requested resource is denied.",
"details": ""
}
]
}

**Comment by Sleepy-Git-User** [comment]
> Hello, i have the same Problem when i try to use:
> 
> https://sellingpartnerapi-eu.amazon.com//catalog/2022-04-01/items/B0DWDWK591?marketplaceIds=A1PA6795UKMFR9&includedData=summaries&locale=de_DE
> 
> { "errors": [ { "code": "Unauthorized", "message": "Access to requested resource is denied.", "details": "" } ] }
> 
> my roles:
> <img alt="Image" width="898" height="831" src="https://private-user-images.githubusercontent.com/68513428/502925255-6b80be80-c39f-49b1-b8b8-a85c020fcd00.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExNzMzMjUsIm5iZiI6MTc2MTE3MzAyNSwicGF0aCI6Ii82ODUxMzQyOC81MDI5MjUyNTUtNmI4MGJlODAtYzM5Zi00OWIxLWI4YjgtYTg1YzAyMGZjZDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIyVDIyNDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NzljZDA4OWFlMDJlZjg4YzEyNzZmMThmNzJhZDEwMmNkZjcwNDJmOWQ1OGYwZWNmZDYwMTAyMWEzNGY2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.etYfH90yNL5XzclHSkBXFmvJpwYOw4dvsrcdNv2U1Ek">

Could the // inbetween ".com" and "/catalog" be the issue for you?
