### ISSUE TITLE
Inventory API "Access to requested resource is denied"

### ISSUE THREAD

**Issue by mo86** [amzn/selling-partner-api-models#1039]
Hi, my request to https://sellingpartnerapi-eu.amazon.com/fba/inventory/v1/summaries results in "Access to requested resource is denied". All other Endpoints are working fine so it's nothing avout HOW I do the requests. In the app options I activated all endpoints.

I read somewhere else that the inventory API is not enabled in the European Marketplace. Can somebody confirm this? Thank you

**Comment by Henokagb** [comment]
Good Morning! Have that issue been resolved ?
Thank you.
