### ISSUE TITLE
createReport  GET_FBA_MYI_ALL_INVENTORY_DATA  , return _CANCELLED_

### ISSUE THREAD

**Issue by salegoodluck** [amzn/selling-partner-api-models#104]
i createReport   GET_FBA_MYI_ALL_INVENTORY_DATA,why  response   report _CANCELLED_ status 

<ReportRequestInfo>
      <ReportProcessingStatus>_CANCELLED_</ReportProcessingStatus>
      <EndDate>2021-05-06T06:32:16+00:00</EndDate>
      <Scheduled>false</Scheduled>
      <ReportRequestId>136461018753</ReportRequestId>
      <SubmittedDate>2021-05-06T06:32:16+00:00</SubmittedDate>
      <CompletedDate>2021-05-06T06:34:53+00:00</CompletedDate>
      <ReportType>_GET_FBA_MYI_ALL_INVENTORY_DATA_</ReportType>
      <StartedProcessingDate>2021-05-06T06:34:17+00:00</StartedProcessingDate>
      <StartDate>2021-04-21T20:11:24+00:00</StartDate>
    </ReportRequestInfo>

**Comment by DawidWawrzyniak** [comment]
One of the reasons can be that report does not contain any data.
