### ISSUE TITLE
[BUG] getPricing missing pricing data

### ISSUE THREAD

**Issue by darek292** [amzn/selling-partner-api-models#1059]
I've signed up and subscribed to the pricing role recently and I'm testing the API, the following call works as expected:

**GET /products/pricing/v0/competitivePrice** (it uses the same input as getPricing below) - it returns the competitive price with no issues.

Unfortunately this call is not working as expected:

**GET /products/pricing/v0/price**

```
let response = await sellingPartner.callAPI({
  operation:'getPricing',
  query:{
    MarketplaceId:'A1F83G8C2ARO7P',
    Asins: ['B00NH13S44'],
    ItemType: 'Asin'
  }
});
```

Returns

```
[{
  "status": "Success",
  "ASIN": "B00NH13S44",
  "Product": {
    "Identifiers": {
      "MarketplaceASIN": {
        "MarketplaceId": "A1F83G8C2ARO7P",
        "ASIN": "B00NH13S44"
      }
    }
  }
}]
```

This looks like it's missing pricing information? Initially I thought it would only be for my products, but I can call **GET /products/pricing/v0/items/{Asin}/offers** which then return all the offers and their pricing just fine, so that doesn't make sense to me. The sandbox also shows more data than what is actually coming back.

Am I missing something crucial here? I'm also seeing some things from the MWS API not available here, one such example is:

**GetLowestOfferListingsForSKU** which allows for 20 requests (10 items every sec restored) - In contrast, getListingOffers is somewhat close but only applies to one listing (you can only specify one ASIN and you need to specify ItemCondition).

Are there some undocumented APIs still in the work? I need to be able to return the lowest offer for multiple ASINs but it's proving to be difficult, I would love to have access to the MWS API in the interim but unfortunately as I'm a new dev it does not give me the option anywhere to sign up for it. 

@ShivikaK / @parvathm  could you provide some insight on this if possible please? I've been trying a lot of things with no success.

**Comment by yashlaharia16** [comment]
anybody got solution to this case. Please help
