### ISSUE TITLE
Is there a method to get all amazon listings for our store?

### ISSUE THREAD

**Issue by tecorraltd** [amzn/selling-partner-api-models#108]
I'm struggling to find any way to get a full list of all the listings on our store. The closest I've found is the GetPricing method but that requires you to pass either the ASIN or SKU list (which is also limited to 20). 

Thanks

**Comment by ericblade** [comment]
I believe you can generate reports that will provide enough info to be able to drill down to that.

**Comment by vikingcodes** [comment]
@tecorraltd You can use Report API and report type can be Inventory Reports

check following links

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#inventory-reports

**Comment by tecorraltd** [comment]
I found that too eventually. I sign all amazon requests the same, but it seems the getReport in C# isn't working.

```
            // this works and passes back a report ID in createReportResult.Payload.ReportId
            var createReportResult = reportsAPI.CreateReport(new CreateReportSpecification(
                reportOptions: new ReportOptions(),
                reportType: "GET_FLAT_FILE_OPEN_LISTINGS_DATA",
                marketplaceIds: new List<string> { MARKETPLACE_ID }
            ));

            // this errors
            var report = reportsAPI.GetReport(createReportResult.Payload.ReportId);
```

Error message: 

> 
> An unhandled exception of type 'IO.Swagger.Client.ApiException' occurred in tecorra-service-manager.dll: 'Error calling GetReport: {
>   "errors": [
>     {
>       "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
> 
> The Canonical String for this request should have been
> 'GET
> /reports/2020-09-04/reports/50010018756
> 
> accept:application/json
> host:sellingpartnerapi-eu.amazon.com

I've had this before when the parameters of a request were incorrect or I didn't submit everything required. For getReport though there is only one parameter and I've triple checked it's passing the report ID returned from the first step. Any advice?

**Comment by tecorraltd** [comment]
Ok bug found - the line below was missing $.

`var localVarPath = $"/reports/2020-09-04/reports/{reportId}";`

**Comment by vikingcodes** [comment]
Great
