### ISSUE TITLE
Where do you get the warehouse id from?

### ISSUE THREAD

**Issue by tecorraltd** [amzn/selling-partner-api-models#110]
All products we sell are fulfilled by merchant, not amazon. We need to sync the inventory across amazon and our web store, the only method I've found is: UpdateInventoryApi.SubmitInventoryUpdate(). I would have thought a method would be in the merchant fulfillment api? For this method it requires the following information I can't find anywhere:

- PartyId
-  WarehouseId

I'm not sure if this is the right API for my task or where I can obtain these two ids. It would be great to provide this information in the docs.

**Comment by kratoskat** [comment]
I'd like to reopen this - we are having the same issue and there is zero record in github or the docs about what warehouseId is

**Comment by coder771** [comment]
@kratoskat did you find out about warehouseId?

**Comment by kratoskat** [comment]
i think so but I've not managed to test yet cz we're still in development and using the sanbox! 
You can get it by navigating to the Warehouse menu as described in "Adding a Warehouse" from here https://infiplex.com/Amazon-Vendor-Central-Set-up.

If you have one, you can click Edit and get the code from there (ours was 4 letter uppercase word) or create a new one and get it from there!

**Comment by coder771** [comment]
@kratoskat thanks. Do you know what this error is about. Would it be something customer not setup correctly in their Amazon vendor account?
Ensure that your product ID (SKU/UPC/EAN) is correctly mapped to an Amazon ASIN.

**Comment by kratoskat** [comment]
@coder771  **i think** .. when selling products in AVC you have to map them to an ASIN which is Amazon's unique identifier - if they don't have one they cant be fulfilled by Amazon. You can find details about the products in these reports ( i think under Inventory or Catalog)
![image](https://user-images.githubusercontent.com/46923294/224304107-1c7fdaae-71ec-42b8-a1ff-95c5d50d1f61.png)
