### ISSUE TITLE
The Product Pricing endpoint fails for SKUs containing forward slashes

### ISSUE THREAD

**Issue by ellis** [amzn/selling-partner-api-models#1100]
How can the product pricing endpoint be used to fetch data on SKUs that contain forward slashes?  Let's say the SKU is: EXAMPLE/SLASH. Here's are several examples of URLs I tested for this issue:

1. https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLE%2FSLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New
2. https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLE/SLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New
3. https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLESLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New

I would expect URL 1 to work, where the slash is URL-encoded.  But it returns a 404 error ("The requested URL was not found on this server.").

Obviously, the URL 2 can't work because of the extra slash.  Here's the error:

```json
{
    "message": "Access to requested resource is denied.",
    "code": "Unauthorized",
    "details": ""
}
```

URL 3 also won't work, because its the wrong SKU, but it produces the appropriate error message:

```json
{
	"code": "InvalidInput",
	"message": "SOMESTRANGE is an invalid SKU for marketplace A1PA6795UKMFR9",
	"details": ""
}
```

Can you add support for SKUs with slashes, like in URL 1?

**Comment by diegocvazquez** [comment]
@LoneRegister 

Hello there, did you get this to work? I am facing the same issue; some of our clients are using forward slashes in the SKUs. Thanks in advance

**Comment by sreecodeslayer** [comment]
~Why is this issue closed, it is very much a bug even now, and impacts a lot of SKUs which are not URL safe @ellis~

~Both `getListingsItem` and `patchListingsItem` is affected and fails~

eg.: 

Original SKU: `3351/53-25+25`

URL Without encoding: `https://sellingpartnerapi-na.amazon.com/listings/2021-08-01/items/xxxxx/3351/53-25+25` -> 403 (`"x-amzn-RequestId", "a62ebe87-b58d-4fd4-b365-e8e7ce6eddaf"`)

~URL With encoding: `https://sellingpartnerapi-na.amazon.com/listings/2021-08-01/items/xxxxx/3351%252F53-25%252B25%2522` -> 404 (`"x-amzn-RequestId", "2a96b267-31cc-4d77-ba1a-d355f64fe8ee"`)~

**Comment by ellis** [comment]
@sreecodeslayer I haven't encountered the error in a long time, so I can't say much about it.  But just a quick idea: the URL encoding that you pasted in looks wrong to me, so maybe that is part of the issue?

```
3351%252F53-25%252B25%2522 # WRONG (I think)
3351%2F53-25%2B25 # CORRECT (I think)
```
