### ISSUE TITLE
where is io.swagger.client

### ISSUE THREAD

**Issue by q657198385** [amzn/selling-partner-api-models#111]
I want to run the sample-code, but it show me that package io.swagger.client not exist.

**Comment by parvathm** [comment]
Hi @q657198385 ,

Can you please give us more details about your issue. Have you generated the client library using swagger code gen and in that client library are you not able to find the package io.swagger.client. Please provide more details so we can help you better.

Thanks,
Parvathm
Selling Partner API Developer Support.
