### ISSUE TITLE
The Canonical String for this request

### ISSUE THREAD

**Issue by jmawebtech** [amzn/selling-partner-api-models#113]
Hi,

I am trying to use the Swagger library and C#. I receive an error that my canonical string is wrong. 

Here is my string:

GET
/sellers/v1/marketplaceParticipations
host=sellingpartnerapi-na.amazon.com&x-amz-access-token=x&X-Amz-Date=20210518T154816Z
host:sellingpartnerapi-na.amazon.com
x-amz-access-token:Atza|
X-Amz-Date:20210518T154816Z

Here is my request and response:

GET https://sellingpartnerapi-na.amazon.com/sellers/v1/marketplaceParticipations HTTP/1.1
Accept: application/json
x-amz-access-token: Atza|
X-Amz-Date: 20210518T154816Z
Authorization: AWS4-HMAC-SHA256 Credential=HIDDEN/20210518/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-date, Signature=1d8e3288297cabaaed70ff307288587be11d5dc61b4497fdeb8c6b04f2745ad7
Host: sellingpartnerapi-na.amazon.com

HTTP/1.1 403 Forbidden
Date: Tue, 18 May 2021 15:48:57 GMT
Content-Type: application/json
Content-Length: 1087
Connection: keep-alive
x-amzn-RequestId: 491cbe4b-06e2-4095-9b64-f14a0970bbfb
x-amzn-ErrorType: InvalidSignatureException
x-amz-apigw-id: fiA8hFkVIAMFosg=

{
  "errors": [
    {
      "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'GET
/sellers/v1/marketplaceParticipations

host:sellingpartnerapi-na.amazon.com
x-amz-access-token:Atza|
x-amz-date:20210518T154816Z

host;x-amz-access-token;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20210518T154816Z
20210518/us-east-1/execute-api/aws4_request
a086ed92b2ce4198501237f6abbdb1f3e6dda1eb727e2ef2b899b44a48a2e1eb'
",
     "code": "InvalidSignature"
    }
  ]
}

**Comment by Mike-the-one** [comment]
@jmawebtech hi, have you solved this issue? I am facing the same issue with TokensAPI call to get RDT, also I am using java.
