### ISSUE TITLE
OrdersV0Api: java sdk, i use right params but always get null order

### ISSUE THREAD

**Issue by lkx1993** [amzn/selling-partner-api-models#115]
OrdersV0Api: java sdk, i use right params but always get null order,the order is exist
![image](https://user-images.githubusercontent.com/34115582/119223138-555b4f00-bb2a-11eb-91a5-0538b622a98d.png)

this is a response headers

Date: Sat, 22 May 2021 10:17:17 GMT
Content-Type: application/json
Content-Length: 28
Connection: keep-alive
x-amzn-RequestId: 6912f6d3-c9f2-42da-ac4e-2bc461235981
x-amzn-RateLimit-Limit: 0.0055
x-amz-apigw-id: fucHHGNdoAMF8uw=
X-Amzn-Trace-Id: Root=1-60a8da2d-35bae70609aea78d15b699d1
OkHttp-Sent-Millis: 1621678634925
OkHttp-Received-Millis: 1621678635263

**Comment by fillumina** [comment]
I have the same issue, how did you solve that? Thank you

**Comment by AleemFeng** [comment]
Hi,I have the sample problem now ,did you resolve it?

**Comment by AlexandruCiobanu** [comment]
@lkx6 Can you please share with us the solution you found? Since you closed the ticket I take it you found a resolution.

Thank you
