### ISSUE TITLE
Create shipments - Invalid input

### ISSUE THREAD

**Issue by rusanpas** [amzn/selling-partner-api-models#1152]
I am trying to make a call to Merchanfullfillment - create shipment (POST /mfn/v0/shipments ), but it returns the error
```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}
```
I have tried in the sandbox and the call is successful. You can tell me that it may be wrong ...I think the json is correct.

This is what is being sent without personal data :
```
{
   "ShipmentRequestDetails":{
      "AmazonOrderId":"...",
      "ItemList":[
         {
            "OrderItemId":"3183...459",
            "Quantity":1
         }
      ],
      "ShipFromAddress":{
         "Name":"...",
         "AddressLine1":"..",
         "Email":"...",
         "City":"...",
         "PostalCode":"...",
         "CountryCode":"ES",
         "Phone":"..."
      },
      "PackageDimensions":{
         "Length":17.6,
         "Width":13.7,
         "Height":11.2,
         "Unit":"inches"
      },
      "Weight":{
         "Value":202.1,
         "Unit":"oz"
      },
      "ShippingServiceOptions":{
         "DeliveryExperience":"DeliveryConfirmationWithoutSignature",
         "CarrierWillPickup":false
      }
   },
   "ShippingServiceId":"SEUR_ES_MFN_24",
   "ShippingServiceOfferId":"....."
}
````

Case Id : #6880732102

Thanks

**Comment by dennisb87** [comment]
I also get an invalid input error, eligibleShippingServices is ok, there I am given 3 shipping types to choose from, no matter which one I choose, invalid input always comes up when I call the Create Shipment api. But not always, for example if I am only offered one shipping service, everything works fine and I get a label back.

response for /mfn/v0/shipments call:

{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}
