### ISSUE TITLE
orderAddress api: couldn't get shipping address detail

### ISSUE THREAD

**Issue by lyndon2333** [amzn/selling-partner-api-models#117]
Tax Invoicing role has been added, this api returned  a few information of ShippingAddress
only  StateOrRegion,PostalCode,CountryCode and Name were included in ShippingAddress,
and the Name was blank, 
detail address information  such as AddressLine1,City couldn't be returned
RDT was also tried , same response, and the request status was true
fulfillment channel of the order was AFN

**Comment by greenxolutions** [comment]
I have the same issue. Could someone help us?

**Comment by marconline** [comment]
Same here. @ShivikaK can you please help us? We are getting incomplete responses from Order APIs, even passing RDT.

**Comment by fillumina** [comment]
I have the same issue as well.

**Comment by DawidWawrzyniak** [comment]
Please try to use the scheduled report API with RDT. I am using "GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING" and I have a shipping address. If data is still not present you should open an Issue with Amazon via Seller Center.

**Comment by marconline** [comment]
@Daniel-Rutkowski I have an issue opened since months, but nothing changes. Thanks anyway
