### ISSUE TITLE
How to solve Too Many Requests Error

### ISSUE THREAD

**Issue by lijinghui** [amzn/selling-partner-api-models#120]
I get api **/orders/v0/orders/{orderId}/address** with **RDT**, but always throw You exceeded your quota for the requested resource.
I got a header x-amzn-RateLimit-Limit is 0.0055 and documentation said the Burst is 20.
how should I sleep the thread ? Rate (requests per second) 0.0055 means 180 second added one token to the token bucket?
But there is a lot of data on the order address，It doesn't seem reasonable .

**Comment by DawidWawrzyniak** [comment]
It is better to use reports API to download orders data, ex: GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING or GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING.
