### ISSUE TITLE
GetOrderAddressResponse Does not include Buyers Name and Address !

### ISSUE THREAD

**Issue by mashhood1995** [amzn/selling-partner-api-models#1219]
I am trying to import orders from amazon to oracle Netsuite ERP using Orders API. When I request order shipping address, the response does not include  name and street address . After searching for answers i found out that it requires PII access . How can i get PII access for our seller account. We are using API for our own business only.
![Capture](https://user-images.githubusercontent.com/52625077/114557346-04328280-9c83-11eb-84ce-2bf613f9e0b4.PNG)

**Comment by Eflores89** [comment]
hi, how was this resolved?
