### ISSUE TITLE
Vendor-Direct-Fulfillment APIs return "Too Many Active Keys" error message

### ISSUE THREAD

**Issue by jdliangli** [amzn/selling-partner-api-models#122]
I'm testing the APIs for Vendor-Direct-Fulfillment. Yesterday every testing requests on Sandbox worked fine. But today when I went through the requests again, they all returned the same error:

"errors": [
"message": "Too Many Active Keys",
"code": "Invalid Input"] 

I'm just wondering what causes this error and how to resolve it.

Thanks.

**Comment by jdliangli** [comment]
Right now things back to normal again. So basically I had the issue on 6/2/2021 before 2:00pm EDT.

Wondering if I will have this issue in the future.

**Comment by ShivikaK** [comment]
Hello @jdliangli 

The error "Too Many Active Keys" was an APIG error and has been resolved fully. 
You should not be impacted by this issue again.

Thanks,
Shivika Khare
Selling Partner API Developer Support
