### ISSUE TITLE
Getting Page Sales and Traffic reports using Reports API

### ISSUE THREAD

**Issue by yiweixia** [amzn/selling-partner-api-models#1230]
If I go to Seller Central, under Reports I can go:

Reports -> Business Reports -> By ASIN ->  Detail Page Sales and Traffic

which takes me to a page where I can download a CSV which details page views by ASIN. I can't seem to find a similar report using the SP API. Please correct me if I'm mistaken, but it seems like the reports offered by the Reports API don't line up with the reports shown on the Seller Central dashboard. 

I've checked a few of the inventory reports/performance reports, but those don't contain the info I'm looking for.

If these reports are currently available via the API, could we document the mapping of SC reports <-> API call better? 
 
If it's not, could you make them available?

**Comment by koradiyayash26** [comment]
> > kenyonduan
> > Does this mean that my application needs to be re-approved? and will I be able to access the Sp-API during the approval period?
> 
> [@kenyonduan](https://github.com/kenyonduan) Have you found an answer to this?
> 
> Were you able to use SP-API after adding this role before it was re approved?

I have successfully implemented a workaround for the Sales and Traffic report quota limits. If anyone is still struggling with 429 errors or needs a guide on how to structure these requests for SP-API or Amazon Ads, feel free to mention me here. Happy to share my findings and help guide the implementation!
