### ISSUE TITLE
Remove dependency of RESTSharp from  AWSSigV4Signer

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-models#124]
The use case of a private developer requires that the AWS Credentials be stored off the Client/Seller's infrastructure.  This means private developers generally create APIs to sign requests.   Because you cannot serialize IRestRequest or IRestClient, the dependency on the signing code on these libraries should be removed, and  they should allow you to pass in the host, parms, and body for singing.

**Comment by unleashed-jamest** [comment]
I second this. We want to use this with Refit instead of RestSharp, and hence baking the signer (which is a complex algorithm in its own right) to implementation details of RestSharp isn't ideal here.

**Comment by kpconnell** [comment]
why would the bot mark this as completed?
