### ISSUE TITLE
Using the same SP API developer on different Seller accounts

### ISSUE THREAD

**Issue by bm-lucas** [amzn/selling-partner-api-models#1267]
I currently manage the integrations with different Seller accounts using the old MWS Api. These integrations share the same developer account, so I use the same pair of access-secret and a different mwsAuthToken for each Seller. 

I've managed to successfully configure, on one of the Sellers (SELLER_1), the new SPApi integration. 
I followed the [Self Authorization](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization) workflow and I am now able to correctly authenticate and perform Api calls on SELLER_1. Note that I left the app in draft, since the [doc](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#self-authorization) clearly states that "You can self authorize your application in draft state; there is no reason to publish your self-authorized application to the Marketplace Appstore.".

I am now trying to use the same developer account and the same app to perform SPApi calls on a different SELLER_2, using the [Authorization Api](https://github.com/amzn/selling-partner-api-docs/blob/main/references/authorization-api/authorization.md).

To do this, I call the https://api.amazon.com/auth/o2/token endpoint with the following payload:

```
{    
     "grant_type": "client_credentials",
     "client_id": ** LWA clientId from the app on the working SELLER_1 account ** ,
     "client_secret": "***",
     "scope": "sellingpartnerapi::migration"
}
```

And this gives me a LWA access_token, that I am then using to call the Authorization Api, passing it the SELLER_2 id and the MwsAuthToken that I am already using to call MWS. I get the following error:

`
{ "code": "InvalidInput", "message": "A published application with the provided app-id not found", "details": "" }
`

So it seems to me that the SELLER_2 cannot find the app I created, since I have not published it. I have no reason to publish the app on the Marketplace Appstore, so I'd prefer to leave it in draft.

Am I missing something here? Is there a way that I can keep using the same developer on different Seller accounts without having to publish my app on the Marketplace Appstore?

**Comment by domeglic** [comment]
I tried to follow the steps here but I can't access the other account.

I have a private app in seller1 and want to access seller2. I create a new app in seller1 then sign in to seller2 and authorize to obtain the refresh token. 

If I use client_id and secret from seller1 and refresh token from seller2, I get wrong credentials error. If I also use client_id and secret from seller2 app + refresh token from seller2, I just get access to seller1 data.
