### ISSUE TITLE
C# Client Signatures not properly working for POST requests, HASH is not calculated correctly

### ISSUE THREAD

**Issue by shkedy** [amzn/selling-partner-api-models#129]
When using the C# SDK to make API requests the client is not properly signing POST requests.
When you submit the request to Amazon you will get "code": "InvalidSignature" in the response.
The issues seems like it is with the string to Sign:
The error specifies the String-to-Sign should have been:
AWS4-HMAC-SHA256
20210611T141704Z
20210611/us-east-1/execute-api/aws4_request
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Where XXXXXXXXXXXXXXXXXXXXXX..... is the HASH(digest) of the payload body 
Amazon is calculating a different HASH(digest) of the payload body.

**Comment by shkedy** [comment]
I was able to resolve the issue. It seems like the RestClient object needs to be set in a very specific order with very specific headers.
When adding POST body the only thing that seemed to work for me was:

restRequest.AddHeader("Content-Type", "application/json");
restRequest.AddParameter("application/json", Newtonsoft.Json.JsonConvert.SerializeObject(requestBody), ParameterType.RequestBody);

Other methods like: restRequest.AddJsonBody(....) would result in signature error.

**Comment by markbeazley** [comment]
Just ran into this issue myself, this is because when using AddJsonBody() the body isn't serialised until the request is sent so when the AWSSigV4Signer tries to read the Request Body the body.Value contains the data to be serialised.
