### ISSUE TITLE
Nodejs Client

### ISSUE THREAD

**Issue by beastmike1** [amzn/selling-partner-api-models#13]
Hi, I'm super excited with this new API and it will be super useful in our company. In our company we use Node.Js with Typescript for the development and it would be super useful for us to have a client for Node. There is any plan to develop other clients besides Java and C#? 

Thanks.

**Comment by charliecode** [comment]
@beastmike1 [Current answer.](https://github.com/amzn/selling-partner-api-docs/issues/32)
