### ISSUE TITLE
Seller API returns 403 for Resource Not Found?

### ISSUE THREAD

**Issue by kvm** [amzn/selling-partner-api-models#131]
Sellers API documentation mentions that getMarketplaceParticipations API returns 403 error when the resource is not found
https://github.com/amzn/selling-partner-api-models/blob/cd00b56aebb5822686b45cc27730465c868dcab9/models/sellers-api-model/sellers.json#L226

Is that a typo in the documentation or does the API really return 403 which doesn't make sense as per REST standards, it should be 404 not 403.

**Comment by AleemFeng** [comment]
403 means you don't have access to require,did you have authorization token?
