### ISSUE TITLE
Unauthorized on subscriptions/ANY_OFFER_CHANGE

### ISSUE THREAD

**Issue by akymos** [amzn/selling-partner-api-models#132]
Hi,

we are migrating our C# code from MWS to SP-API, but there is strange behaviour with notification subscribe.
When calling **notifications/v1/subscriptions/ANY_OFFER_CHANGED** with the destinationId returned by **notifications/v1/destinations** it return 
```
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
```

The user seem configured correctly, because if we do the same call, with same config, with this go library "amzapi/selling-partner-api-sdk" there is no problem.

What can be the problem?

**Comment by ShivikaK** [comment]
Hello @akymos 

Did you manage to get past this error? 

Please feel free to open a support case with us if you'd like deeper assistance with this issue.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by akymos** [comment]
Thank you so much for the quick reply!
Given the date of passage (scheduled for September) and the no response to our problem (blocker for us), we decided to stop working with Amazon and switch to Alibaba (which has greater support) because our customers are present on both stores.

**Comment by xbaha** [comment]
I believe the date was shifted one more year.
