### ISSUE TITLE
Required parameter IdType not found   at (/catalog/v0/items)

### ISSUE THREAD

**Issue by gtzhong** [amzn/selling-partner-api-models#134]
Exception when calling CatalogApi->listCatalogItems: [400] Client error: `GET https://sellingpartnerapi-na.amazon.com/catalog/v0/items?MarketplaceId=ATVPDKIKX0DER` resulted in a `400 Bad Request` respons
e:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Required parameter IdType not found",
      "detai (truncated...)

/models/catalog-items-api-model/catalogItemsV0.json

path:/catalog/v0/items

why?Required parameter IdType not found?????

**Comment by gtzhong** [comment]
https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json


"paths": {
      
      
            "/catalog/v0/items": {
      
      
              "get": {
      
      
                "tags": [
      
      
                  "catalog"
      
      
                ],
      
      
                "description": "Returns a list of items and their attributes, based on a search query or item identifiers that you specify. When based on a search query, provide the Query parameter and optionally, the QueryContextId parameter. When based on item identifiers, provide a single appropriate parameter based on the identifier type, and specify the associated item value. MarketplaceId is always required.\n\nThis operation returns a maximum of ten products and does not return non-buyable products.\n\n**Usage Plans:**\n\n| Plan type | Rate (requests per second) | Burst |\n| ---- | ---- | ---- |\n|Default| 6 | 40 |\n|Selling partner specific| Variable | Variable |\n\nThe x-amzn-RateLimit-Limit response header returns the usage plan rate limits that were applied to the requested operation. Rate limits for some selling partners will vary from the default rate and burst shown in the table above. For more information, see \"Usage Plans and Rate Limits\" in the Selling Partner API documentation.",
      
      
                "operationId": "listCatalogItems",
      
      
                "parameters": [
      
      
                  {
      
      
                    "name": "MarketplaceId",
      
      
                    "in": "query",
      
      
                    "description": "A marketplace identifier. Specifies the marketplace for which items are returned.",
      
      
                    "required": true,
      
      
                    "type": "string"
      
      
                  },
      
      
                  {
      
      
                    "name": "Query",
      
      
                    "in": "query",
      
      
                    "description": "Keyword(s) to use to search for items in the catalog. Example: 'harry potter books'.",
      
      
                    "required": false,
      
      
                    "type": "string"
      
      
                  },
      
      
                  {
      
      
                    "name": "QueryContextId",
      
      
                    "in": "query",
      
      
                    "description": "An identifier for the context within which the given search will be performed. A marketplace might provide mechanisms for constraining a search to a subset of potential items. For example, the retail marketplace allows queries to be constrained to a specific category. The QueryContextId parameter specifies such a subset. If it is omitted, the search will be performed using the default context for the marketplace, which will typically contain the largest set of items.",
      
      
                    "required": false,
      
      
                    "type": "string"
      
      
                  },
      
      
                  {
      
      
                    "name": "SellerSKU",
      
      
                    "in": "query",
      
      
                    "description": "Used to identify an item in the given marketplace. SellerSKU is qualified by the seller's SellerId, which is included with every operation that you submit.",
      
      
                    "required": false,
      
      
                    "type": "string"
      
      
                  },
      
      
                  {
      
      
                    "name": "UPC",
      
      
                    "in": "query",
      
      
                    "description": "A 12-digit bar code used for retail packaging.",
      
      
                    "required": false,
      
      
                    "type": "string"
      
      
                  },
      
      
                  {
      
      
                    "name": "EAN",
      
      
                    "in": "query",
      
      
                    "description": "A European article number that uniquely identifies the catalog item, manufacturer, and its attributes.",
      
      
                    "required": false,
      
      
                    "type": "string"
      
      
                  },
      
      
                  {
      
      
                    "name": "ISBN",
      
      
                    "in": "query",
      
      
                    "description": "The unique commercial book identifier used to identify books internationally.",
      
      
                    "required": false,
      
      
                    "type": "string"
      
      
                  },
      
      
                  {
      
      
                    "name": "JAN",
      
      
                    "in": "query",
      
      
                    "description": "A Japanese article number that uniquely identifies the product, manufacturer, and its attributes.",
      
      
                    "required": false,
      
      
                    "type": "string"
      
      
                  }
      
      
                ],

**Comment by JosueExsim** [comment]
Did you find the solution?

> Exception when calling CatalogApi->listCatalogItems: [400] Client error: `GET https://sellingpartnerapi-na.amazon.com/catalog/v0/items?MarketplaceId=ATVPDKIKX0DER` resulted in a `400 Bad Request` respons
> e:
> {
> "errors": [
> {
> "code": "InvalidInput",
> "message": "Required parameter IdType not found",
> "detai (truncated...)
> 
> /models/catalog-items-api-model/catalogItemsV0.json
> 
> path:/catalog/v0/items
> 
> why?Required parameter IdType not found?????

**Comment by danielecr** [comment]
I had the same error using https://github.com/amz-tools/amazon-sp-api version 0.5.1, then I switched to 0.5.2 and to the 2020-12-01 api version, and the error is gone. I can not find anything about `IdType` in that code, maybe the only option is to use version 2020-12-01

**Comment by JosueExsim** [comment]
> I had the same error using https://github.com/amz-tools/amazon-sp-api version 0.5.1, then I switched to 0.5.2 and to the 2020-12-01 api version, and the error is gone. I can not find anything about `IdType` in that code, maybe the only option is to use version 2020-12-01

Sorry I'm new to this, how do you change the version?
