### ISSUE TITLE
Some Orders appears to have no data when calling financial events by order id

### ISSUE THREAD

**Issue by ianrussel** [amzn/selling-partner-api-models#1365]
This seem another bug for this sellingpartner api. My goal is to get Financial events. Bu I noticed some of them return empty objects.

         finances/v0/orders/303-3828883-7xxxxxxxx/financialEvents

         {
            "payload": {
              "FinancialEvents": {
                "ShipmentEventList": [],
                "RefundEventList": [],
                "GuaranteeClaimEventList": [],
                "ChargebackEventList": [],
                "PayWithAmazonEventList": [],
                "ServiceProviderCreditEventList": [],
                "RetrochargeEventList": [],
                "RentalTransactionEventList": [],
                "ProductAdsPaymentEventList": [],
                "ServiceFeeEventList": [],
                "SellerDealPaymentEventList": [],
                "DebtRecoveryEventList": [],
                "LoanServicingEventList": [],
                "AdjustmentEventList": [],
                "SAFETReimbursementEventList": [],
                "SellerReviewEnrollmentPaymentEventList": [],
                "FBALiquidationEventList": [],
                "CouponPaymentEventList": [],
                "ImagingServicesFeeEventList": [],
                "NetworkComminglingTransactionEventList": [],
                "AffordabilityExpenseEventList": [],
                "AffordabilityExpenseReversalEventList": []
              }
            }
         }

calling same api with different orderid returns data

            {
        "payload": {
          "FinancialEvents": {
            "ShipmentEventList": [
              {
                "AmazonOrderId": "302-xxx3690-xxxxxx",
                "SellerOrderId": "302-xxx3690-xxxx",
                "MarketplaceName": "Amazon.de",
                "PostedDate": "2021-05-14T22:39:14+00:00",
                "ShipmentItemList": [
                  {
                    "SellerSKU": "4Z-xxxxx",
                    "OrderItemId": "2xxxx7168403",
                    "QuantityShipped": 2,
                    "ItemChargeList": [
                      {
                        "ChargeType": "Principal",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 33.9
                        }
                      },
                      {
                        "ChargeType": "Tax",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 0
                        }
                      },
                      {
                        "ChargeType": "GiftWrap",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 0
                        }
                      },
                      {
                        "ChargeType": "GiftWrapTax",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 0
                        }
                      },
                      {
                        "ChargeType": "ShippingCharge",
                        "ChargeAmount": {
                          "CurrencyCode": "EUR",
                          "CurrencyAmount": 3.99
                        }
                      },

And there are 5 more orderids that returns empty object, which I cant get enough information example charges(shpping etc)

And they are in same date range and marketplace. Any help @ShivikaK ?
And is there any other apis that can be used to get this information like the financial events api ?

**Comment by dsokolowski** [comment]
I just spotted this info in the seller api doc: 'It may take up to 48 hours for orders to appear in your financial events'. Looks like this the cause of this issue.
