### ISSUE TITLE
How to tell which permissions are required for a model

### ISSUE THREAD

**Issue by yuri-lonesomelabs** [amzn/selling-partner-api-models#140]
Where can I find info about which permission should be requested by the app to consume each model?

**Comment by ShivikaK** [comment]
Hello @yuri-lonesomelabs 

Thank you for raising this issue.

You can refer to our Roles documentation which has details on which roles are required for access to the API sections.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md

Thanks,
Shivika Khare
Selling Partner API Developer Support
