### ISSUE TITLE
[BUG] 400 Bad Request when using NextToken on GetOrders

### ISSUE THREAD

**Issue by BasilAlhakami-SonaEnterprises** [amzn/selling-partner-api-models#1411]
I receive a 400 Bad Request response, when calling the /orders/v0/orders endpoint.
when I have the NextToken in the request I submitted a case# 8390283141

this thread: https://github.com/amzn/selling-partner-api-models/issues/384 
 
is discussing the same issue but with https://github.com/amzn/selling-partner-api-models/issues/384

the bug was resolved by @parvathm for the financialEventGroups API

I wonder if the same fix should apply to Orders

Thanks

**Comment by ImportFence** [comment]
> ![sp-api](https://private-user-images.githubusercontent.com/81614378/294500274-6a4e3e40-19bd-4b19-a8bf-ffa987a2fa3e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjIzMTYsIm5iZiI6MTcyNjQyMjAxNiwicGF0aCI6Ii84MTYxNDM3OC8yOTQ1MDAyNzQtNmE0ZTNlNDAtMTliZC00YjE5LWE4YmYtZmZhOTg3YTJmYTNlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE3NDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwY2M5YzQxNmE1MjA1NmU1ZGI0MThhYjI1ZDRhNDE3MjFiN2ZlMjgwMjIxZGNlYjBiOTM2MTcxNjE2NjU3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JZJwEZV-o9CcBWbupz74sRDN5CayY7n3686XR-cnRyY) the problem is still here, why is this closed?

Did you try to only use the nextToken parameter and keep the other three parameters be unchecked while you are trying to fetch 2+ pages data?
