### ISSUE TITLE
Malformed JSON response.

### ISSUE THREAD

**Issue by DeLaGuardo** [amzn/selling-partner-api-models#148]
I'm getting wrongly escaped JSON result out from `finances-api/listFinancialEventsByGroupId`. ProductDescription in AdjusmentItem object might have an invalid escape sequence (In my case - `\-`) which leads to an inability to parse the data on the client side.

**Comment by DeLaGuardo** [comment]
There is a reference to exactly the same problem - https://github.com/amz-tools/amazon-sp-api#known-issues

**Comment by sPaCeMoNk3yIam** [comment]
Having the same issue here, it's very unfortunate to have to deal with this kind of malformed JSON payload. Data quality is key! As this might regard the data itself, I wonder if a code change (to treat every known bad char) on the data before sending the response or a one shot on the DB is more suitable to solve that on SP API side.
