### ISSUE TITLE
Unauthorized: Forbidden Access to resource

### ISSUE THREAD

**Issue by marcovolpedev** [amzn/selling-partner-api-models#15]
Hi

I'm using Selling partner API models to develop application for reading orders.
I'm trying to access to my marketplace even if there are no orders using a Java Client. But for each request I make, I have ad response "Forbidden" with this content

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
}

I'm using this code

`

	try {
			
			AWSAuthenticationCredentials awsAuthenticationCredentials = AWSAuthenticationCredentials.builder()
					.accessKeyId(accessKeyId)
					.secretKey(accessKeySecret)
					.region(region)
					.build();
					;
					
	
			AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider=
					AWSAuthenticationCredentialsProvider.builder()
							  .roleArn(arnRole)
							  .roleSessionName(generateSessionId())
							  .build();	
		
		
			LWAAuthorizationCredentials lwaAuthorizationCredentials = LWAAuthorizationCredentials.builder()
					  .clientId(clientId)
					  .clientSecret(clientSecret)
					  .refreshToken(refreshToken)
					  .endpoint("https://api.amazon.com/auth/o2/token")
					  .build();
			
			OrdersV0Api orderApi = new OrdersV0Api.Builder()
					.awsAuthenticationCredentials(awsAuthenticationCredentials)
					.awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
					.lwaAuthorizationCredentials(lwaAuthorizationCredentials)
					.endpoint("https://sellingpartnerapi-eu.amazon.com")
					.build();
			
			
			List<String> marketplaceIds = new ArrayList<String>();
			marketplaceIds.add(AmazonConstants.MarketplaceItalyID);
			GetOrdersResponse response = orderApi.getOrders(marketplaceIds, null, null, null, null, 
null, null, null, null, null, null, null, null, null);
			
...
			
		} catch (Exception e) {
			e.printStackTrace();
		}

`

Could you help me?

Thanks 
Marco

**Comment by ykl1993** [comment]
me too;
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}

**Comment by israelproscai** [comment]
The same problem

**resource**:  https://sandbox.sellingpartnerapi-na.amazon.com/orders/v0/orders

**responsebody**
`{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}`

**response headers**
x-amzn-ErrorType = AccessDeniedException

**Comment by charliecode** [comment]
@israelproscai @ykl1993. [Check out this issue.](https://github.com/amzn/selling-partner-api-docs/issues/38)

**Comment by seanevan** [comment]
I am closing this issue in favor of the one linked by @charliecode.
