### ISSUE TITLE
ReportsApi 403

### ISSUE THREAD

**Issue by AleemFeng** [amzn/selling-partner-api-models#150]
The account has been authorized all apis ,but the ReportsApi result is **Forbidden** ,others api is success.How to deal it?

**Comment by DawidWawrzyniak** [comment]
You can try to generate a new authorization token.

**Comment by AleemFeng** [comment]
> You can try to generate a new authorization token.

I had try it use four refresh_token,all same result.

paramtetrs is :
``` java 
input.put("startTime", "2021-07-01 04:04:27");
input.put("endTime", "2021-07-27 04:04:27");
input.put("reportType", "GET_ORDER_REPORT_DATA_TAX");
```

**Comment by DawidWawrzyniak** [comment]
Have you tried with another report like SC_VAT_TAX_REPORT or GET_MERCHANT_LISTINGS_DATA?
My request body: 
{"reportType":"GET_ORDER_REPORT_DATA_TAX","dataStartTime":"2021-07-19T11:14:09.2060618+02:00","marketplaceIds":["A1C3SOZRARQ6R3"]}

PS: I have tried to generate this report on my account (I have access to PII data) and I also have an unauthorized message.

**Comment by AleemFeng** [comment]
> Have you tried with another report like SC_VAT_TAX_REPORT or GET_MERCHANT_LISTINGS_DATA?
> My request body:
> {"reportType":"GET_ORDER_REPORT_DATA_TAX","dataStartTime":"2021-07-19T11:14:09.2060618+02:00","marketplaceIds":["A1C3SOZRARQ6R3"]}
> 
> PS: I have tried to generate this report on my account (I have access to PII data) and I also have an unauthorized message.

I find the reason,My app doesn't have the access to require some report type which contains PII. My app have access to require **GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL** datas. 
Finally, thanks my bro.
