### ISSUE TITLE
reports content Incorrect characters

### ISSUE THREAD

**Issue by yuql** [amzn/selling-partner-api-models#1517]
I downloaded a report（TYPE：GET_MERCHANT_LISTINGS_ALL_DATA）use sp-api，the api response header tell me the document charset is  cp1252，I try to convert it to UTF-8 and save to my database（mysql） ，but the document content always show me the  Incorrect characters 。
example：℃ will be show ?

My used function is ：mb_convert_encoding($string, 'UTF-8','cp1252');
How Can I correct convert it to UTF-8 ？

**Comment by ansgarbecker** [comment]
This happened to me today as well. Same report: `GET_MERCHANT_LISTINGS_DATA`. I suppose this was not yet solved?

**Comment by ansgarbecker** [comment]
Ok, the http response contains a "content-type" header, which I can make use of with PHP:

```php
$mbCharsetMap = ['Cp1252' => 'Windows-1252'];

// $contentType is "text/plain; charset=Cp1252"
$charset = preg_replace('#^.*;\s*charset=#', '', $contentType);
$charset = $mbCharsetMap[$charset] ?? $charset;
if(!empty($charset) && $charset != 'UTF-8') {
    $documentContent = mb_convert_encoding($documentContent, 'UTF-8', $charset);
}
```
