### ISSUE TITLE
Report GET_REFERRAL_FEE_PREVIEW_REPORT gets cancelled

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-models#1521]
Please explain the algorithm for obtaining this report (`GET_REFERRAL_FEE_PREVIEW_REPORT`).

When I manually request it, it always gets `CANCELLED`.

This is what the docs say:

> Tab-delimited flat file that contains the seller's open listings as well as the price and estimated referral fees for each SKU.
> 
> Note: The information in this report may be up to 24 hours old. Please do not request a report more than once per 24 hour period.
> 
> Can be requested.

**Comment by tarunod** [comment]
yes, I'm still having the same issue. can anyone help me please.

**Comment by hexrw** [comment]
For anyone encountering similar issues.

**There are undisclosed internal limits to Reports.**

As far as I can tell, the Reports API is just a wrapper and the actual data-retrieval logic is completely separate. Most of the reports are best-effort exports from their internal reporting layers.

According to the [official documentation](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits), even the regular rate limits are dynamic and differ from seller to seller and from application to application. It is reasonable to assume such is the case for the Reports API and the underlying supporting infrastructure.

Your best option is monitor closely and implement back-off and retry strategies.
