### ISSUE TITLE
Swagger generated clients have incorrect casing and missing enums

### ISSUE THREAD

**Issue by athena9** [amzn/selling-partner-api-models#153]
Using swagger codgen to build csharp client.

I've had a number of API methods fail with cryptic errors such as this one seen on PutTransportDetails
```

"errors": [
    {
      "code": "InvalidInput",
      "message": "$inputRoot.message",
      "details": ""
    }
  ]
```

In this case, as with others, various parameters have been generated with the wrong case. Example:

```
[DataMember(Name="length", EmitDefaultValue=false)]
public string Length { get; set; }
```

This needs to be "Length".

Further, the parameter names aren't even correct sometimes, with the api client supplying "unitOfMeasure" instead of "Unit" as expected by the end point.

In other situations the expected enum value simply doesn't exist in the generated code:

PutTransportDetails expects weight units to be specified as either 'kilograms' or 'pounds' (yes, this time in lower case) but the Weight model is generated only with these options:

```
            [EnumMember(Value = "G")]
            G = 1,
            
            [EnumMember(Value = "Kg")]
            Kg = 2,
            
            [EnumMember(Value = "Oz")]
            Oz = 3,
            
            [EnumMember(Value = "Lb")]
            Lb = 4
```

I can't speak to the underlying causes of these issues, but I'm surprised that this isn't more straightforward to use.

Scary that MWS is being deprecated into what feels like an incomplete and inconsistent product relying on an outdated code gen tool.

**Comment by rcalv002** [comment]
Amen.

**Comment by coder771** [comment]
@athena9  are you creating separate clients for each API?
