### ISSUE TITLE
Orders.OrderItem API Error

### ISSUE THREAD

**Issue by pearson0601** [amzn/selling-partner-api-models#155]
Error converting value "CA_MPF" to type 'System.Nullable`1[Model.Orders.OrderItem+DeemedResellerCategoryEnum]'. Path 'payload.OrderItems[0].DeemedResellerCategory', line 1, position 746.！

**Comment by pearson0601** [comment]
{"payload":{"OrderItems":[{"TaxCollection":{"Model":"MarketplaceFacilitator","ResponsibleParty":"Amazon Services, Inc."},"ProductInfo":{"NumberOfItems":"1"},"BuyerInfo":{},"ItemTax":{"CurrencyCode":"CAD","Amount":"1111.75"},"QuantityShipped":1,"ItemPrice":{"CurrencyCode":"CAD","Amount":"111.99"},"ASIN":"111111","SellerSKU":"ALSJDB-24CA","Title":"Automatic Male Masturbator Cup Electric Pocket Pussy Thrusting & Spinning Masturbation Cup with 10 Vibration Modes and 3D Realistic Vagina Pussy Oral","IsGift":"false","IsTransparency":false,"QuantityOrdered":1,"PromotionDiscountTax":{"CurrencyCode":"CAD","Amount":"0.00"},"PromotionDiscount":{"CurrencyCode":"CAD","Amount":"0.00"},"OrderItemId":"09923998463898","DeemedResellerCategory":"CA_MPF"}],"AmazonOrderId":"DDD"}}

**Comment by pearson0601** [comment]
"DeemedResellerCategory":"CA_MPF"  not support

**Comment by stefnats** [comment]
Seems like a bug with the used library. Have you tried filing a bug report with the library you are using?

**Comment by pearson0601** [comment]
GET /orders/v0/orders/{orderId}/orderItems  api "DeemedResellerCategory":"CA_MPF" not support

**Comment by xbaha** [comment]
Are you using sandbox?
How come: "AmazonOrderId":"DDD" ?

**Comment by pearson0601** [comment]
Not a sandbox, but a production environment. Because of data security considerations, I modified the AmazonOrderId and submitted a question.

**Comment by xbaha** [comment]
Are you using the official API from swagger or a different one?

**Comment by pearson0601** [comment]
using the official API from swagger！

**Comment by xbaha** [comment]
go to the OrderItems model,
find this code and modify it:

`        public enum DeemedResellerCategoryEnum
        {
            
            /// <summary>
            /// Enum IOSS for value: IOSS
            /// </summary>
            [EnumMember(Value = "IOSS")]
            IOSS = 1,

            /// <summary>
            /// Enum UOSS for value: UOSS
            /// </summary>
            [EnumMember(Value = "UOSS")]
            UOSS = 2,

//add this
==>            [EnumMember(Value = "CA_MPF")]
==>            CA_MPF = 3,

}`

**Comment by pearson0601** [comment]
Adding can indeed solve the problem, but ca_mfp = 3, is the official amazon value?

**Comment by pearson0601** [comment]
Adding can indeed solve the problem, but ca_mpf = 3, is the official amazon value?

**Comment by xbaha** [comment]
no, but it doesn't matter if you are not utilizing this variable in a useful analysis.

**Comment by pearson0601** [comment]
ok，thanks

**Comment by contrebande-labs** [comment]
Found this because we had the exact same problem. The bug is in Amazon's OpenAPI model and that's where it should be fixed. So why is it closed?
