### ISSUE TITLE
Report type, not supported? _GET_CONVERGED_FLAT_FILE_SOLD_LISTINGS_DATA_

### ISSUE THREAD

**Issue by pearson0601** [amzn/selling-partner-api-models#157]
MWS support _GET_CONVERGED_FLAT_FILE_SOLD_LISTINGS_DATA_，but spapi _GET_CONVERGED_FLAT_FILE_SOLD_LISTINGS_DATA_？

**Comment by Bitschuster** [comment]
I have the same problem, i get access denied while using this Report by SpApi. All other Reports are working fine.
I have all Roles aktivated, on the Developer Site.
Is this a restricted Report ? I dont found any hints in the net.
