### ISSUE TITLE
Issue with OrderItem.ProductInfo.NumberOfItems type

### ISSUE THREAD

**Issue by dominikznidar** [amzn/selling-partner-api-models#158]
The schema for the OrderItem.ProductInfo.NumberOfItems states the value should be an integer while the API returns a string containing an integer. 
This unfortunately breaks decoding JSON to an object in go and requires manual changes to the schema to get decoding to work.

**Comment by dominikznidar** [comment]
Found a similar issue in `OrderItem.IsGift`. The schema defines the item as a boolean, while the returns a string with the boolean value (`"true"` or `"false"`).

**Comment by Roman991** [comment]
Same here
```javascript
{
    ProductInfo: {
      NumberOfItems: "1",
    },
    IsGift: "false",
    ...
}
```

**Comment by xbaha** [comment]
I'd suggest you program a string check first in your code, if you want to fix your issue fast and for good, make a universal code to handle any kind of reply, the API frequently changes and we can't have a bug every now and then.

**Comment by Roman991** [comment]
> I'd suggest you program a string check first in your code, if you want to fix your issue fast and for good, make a universal code to handle any kind of reply, the API frequently changes and we can't have a bug every now and then.

thx, it's exactly what i did. But its kinda hilarious that amazon makes these mistakes
