### ISSUE TITLE
Python API client

### ISSUE THREAD

**Issue by diwu1989** [amzn/selling-partner-api-models#16]
I would like to use Python to interact with the seller API.
Would you be able to generate official API bindings for Python?

**Comment by charliecode** [comment]
Here are two links which might help. I would suggest using openapi-generator over swagger-codegen as the docs are much easier and the generators appear to be less buggy. 

[Creating SP-API client from models.](https://github.com/amzn/selling-partner-api-models)
[OpenAPI generators and docs](https://openapi-generator.tech/docs/generators)

**Comment by GriceTurrble** [comment]
Interested in this as well from the developer side, though I do not have a Seller account myself. Have been working part-time on the [python-amazon-mws](https://github.com/python-amazon-mws/python-amazon-mws/) middleware for some time now, and would like to cover SP-API in a separate project when I have some time there.

Of course, if there were an official client, or just official Mustache templates to build off, that would be nice to have. :)

**Comment by charliecode** [comment]
@GriceTurrble A good place to start would be to customize the templates the generator uses? [Here are the docs for customizing with openapi-generator](https://openapi-generator.tech/docs/customization).

**Comment by seanevan** [comment]
Hi all,

Python client libraries are planned, but I am not at liberty to share a timeline for when we'll provide them. We'll leave this issue open for others to register interest in Python client libs.

Thanks,
Sean Evans
Manager, Support Engineering

**Comment by diwu1989** [comment]
I tried to use the generator, but the code that it spewed out seem to be broken :(
I think it's best if amzn officially generated the Python bindings & published it as a proper package onto Pypi for us all to use.
Thanks

**Comment by numenory** [comment]
Hi, yes also been looking for a while on python documentation / python libraries.  Currently developing using python on mws

**Comment by wernight** [comment]
The current documentation can be followed up to creating requests, however it gives some 403 errors and my guess is that the [signing describe here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-create-and-sign-your-request) is actually required. Implementing and testing this signing is however non-trivial. Especially if you're unsure if everything before that is actually set up properly. I'd really welcome a Python client, better error messages, and a way to test this signature or at least hard of the system (just as an example I can use the user's ARN or the role's ARN at [step 6](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#step-6-register-your-application) and both give no error).

**Comment by dorian-i** [comment]
@seanevan any update on the python clients?
