### ISSUE TITLE
Serious issue in Finances API: missing subtype (marketplace) in special financial event groups

### ISSUE THREAD

**Issue by Baranthebor** [amzn/selling-partner-api-models#165]
Hi there,

We are using the Finances API to gather and provide detailed information to our european customers.
(financial events contained in financial event groups) 

We encounter serious issues trying to determine to which marketplace specific groups belong. 
Currently we provide data of 8 european marketplaces with 3 different currencies to our customers.

For most of the groups, it is possible to determine the associated marketplace using the contained financial events. 
However there are groups that only contain specific events like service fees or debt recoveries which makes it impossible to determine the marketplace of the group. (Only shipment events specify marketplaces!).

Therefore, we implemented an algorithm that tries to assign groups without marketplace to a specified marketplace.
That algorithm uses start dates and end dates of all available groups to create sequences of groups.

Unfortunately, this solution only works for roughly 85% of our customers.
The reason for this is that there are often multiple groups without marketplace having identical start dates and/or end dates.

In those cases, we do not provide data to our customers any longer.
We expect about 50,000 accounts in the future, so that would affect about 7,500 accounts - and therefore roughly the same number of unsatisfied customers.

We need a solution for this problem, e.g. by providing the associated marketplace directly at each group itself!

Kind regards
Baranthebor

**Comment by xbaha** [comment]
Do you mean that there are 5 EU markets that uses the same currency and the field CurrencyCode for these markets  is the same?

**Comment by Baranthebor** [comment]
That's right. Currently we are supporting the following marketplaces:

| marketplace | country | currency code | currency |
| -- | --| --|--|
|amazon.co.uk|United Kingdom|GBP|Pound Sterling|
|amazon.de|Germany|EUR|Euro|
|amazon.es|Spain|EUR|Euro|
|amazon.fr|France|EUR|Euro|
|amazon.it|Italy|EUR|Euro|
|amazon.nl|Netherlands|EUR|Euro|
|amazon.se|Sweden|SEK|Swedish Krona|
|amazon.pl|Poland|PLN|Poland Zloty|

**Comment by xbaha** [comment]
Why don't you request the report for a specific marketplace then?

**Comment by Baranthebor** [comment]
We tried working with reports first but the handling was very complex.
In addition to this not all needed data was provided in the reports.
That's because we switched to the Finances API.

**Comment by J-W-Chan** [comment]
> We tried working with reports first but the handling was very complex. In addition to this not all needed data was provided in the reports. That's because we switched to the Finances API. Unfortunately the Finances API does not support filtering by marketplace.

Hello, have you found a solution？

**Comment by jesusvalle** [comment]
I am having the same problem. There has been no update from amazon?
