### ISSUE TITLE
FTXGatewayService.estimateLtlShipment returned error code: 412

### ISSUE THREAD

**Issue by gaurav-webs** [amzn/selling-partner-api-models#1653]
@ShivikaK  @parvathm 

When I am calling `estimateTransport` every time it returns the same error,

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "FTXGatewayService.estimateLtlShipment returned error code: 412",
      "details": ""
    }
  ]
}
```
also not found any information in documentation regarding this error.

Also when I check in the seller center in **4. Shipping charges** section

It displays **"Unable to calculate shipping cost, please try again later."** something like this,
 
![screenshot-sellercentral amazon com-2021 07 22-16_28_10](https://user-images.githubusercontent.com/78719205/126629413-54c02f31-5110-4a11-9326-e3e3454b2626.jpg)

Can anyone explain why I am getting this?

**Updated (20-Aug-2021 08:45 AM(IST)) :-**

**_As I am still getting the above error but, after doing the following steps it solves, <ins>but this is not the solution<ins>_**,

As this issue is solved but for that,
Step1:-  I have passed the `SellerDeclaredValue` in `putTransportContent` API (As per the doc this field is optional).

![screenshot-github com-2021 08 20-09_00_09](https://user-images.githubusercontent.com/78719205/130174798-8550a39f-27bb-4990-a74d-87c649ef5fa7.jpg)

Step2:- Then need to login in Seller Center > Edit That shipment and then I press any up, down, left, right key from the keyboard in the Seller Declared Value textbox.
Step3:- Then I called `estimateTransport` and I am getting a successful response.

as this is not the solution.
as per the doc, the first thing the **seller declared value is optional**. but If I am not sending that value I am not able to call `estimateTransport`. because in seller center edit shipment page it display  **"Unable to calculate shipping cost, please try again later."**.
Also, every time user is not able to follow the above step that, the user calls the `putTransportContent` API then login to the seller center and edits the shipment and then presses any key seller declared value textbox, then again go to the website and then call `estimateTransport` API.

@ShivikaK  @parvathm 

any solution regarding this error?

**Comment by asjad-trafilea** [comment]
Facing the same issue, did anyone find a solution for this ?

**Comment by defenderjim** [comment]
@asjad-trafilea 
I have it working.


        private (ErrorResponse, bool) putTransportDetails(
			  string shipmentId
			, bool   isPartnered
			, bool   isLtl
			, object payload
			, String accessToken, String sellerParnterAPIlUrl, String marketplaceId)
		{
			// Sends transportation information to Amazon about an inbound shipment.
			// https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#puttransportdetails

			bool success = false;

            ErrorResponse errorResponse = new ErrorResponse();

			IRestRequest restRequest = new RestRequest("fba/inbound/v0/shipments/" + shipmentId + "/transport", Method.PUT);

			restRequest.AddHeader("Content-Type"           , "application/json");
			restRequest.AddHeader("x-amz-access-token"     , accessToken);
			restRequest.AddHeader("X-Amz-Security-Token"   , this.GetAMZAWSSecurityToken(marketplaceId));


			PutTransportDetailsRequest requestParams = new PutTransportDetailsRequest {
				 IsPartnered  = isPartnered
				, ShipmentType = isLtl ? "LTL" : "SP"
				, TransportDetails = new TransportDetails {
					  PartneredSmallParcelData    = payload as PartneredSmallParcelData
					, NonPartneredSmallParcelData = payload as NonPartneredSmallParcelData
					, PartneredLtlData            = payload as PartneredLtlData
					, NonPartneredLtlData         = payload as NonPartneredLtlData
				}
			};


            String body = JsonConvert.SerializeObject(requestParams
				, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });


            restRequest.AddJsonBody(body);

			this._aWSSigV4Signer = new AWSSigV4Signer(
                    new AWSAuthenticationCredentials
                    {
                        AccessKeyId = this._assumeRoleAccess.accessKeyId,
                        SecretKey = this._assumeRoleAccess.secretKey,
                        Region = AmazonRegion.GetAWSRegionByMarketplaceId(marketplaceId)
                    },
                    new AWSSignerHelper()
                );


			// A selling partner identifier, such as a seller account or vendor code. Note: Required when identifiersType is SKU.
			RestClient client = new RestClient(sellerParnterAPIlUrl);
			IRestResponse apiResponse = client.Put(
				this._aWSSigV4Signer.Sign(
					restRequest,
					new Uri(sellerParnterAPIlUrl).Host
				)
			);

			if (apiResponse.IsSuccessful) {
				TransportDetailsResponse detailsResponse = JsonConvert.DeserializeObject<TransportDetailsResponse>(apiResponse.Content);
                errorResponse = new ErrorResponse();
				if (detailsResponse.payload.TransportResult.TransportStatus == "WORKING")
				{
					success = true;
				}


                errorResponse.errors.Add(new Error
                {
                    status = detailsResponse.payload.TransportResult.TransportStatus
                });
            }
            else
            {
                errorResponse = JsonConvert.DeserializeObject<ErrorResponse>(apiResponse.Content);
                errorResponse.errors.ForEach(f => f.status = "");
            }
            return (errorResponse, success);
        }


        private (ErrorResponse, bool) estimateTransport(string shipmentId, String accessToken, String sellerParnterAPIlUrl, String marketplaceId)
        {

bool success = false;
            ErrorResponse errorResponse = new ErrorResponse();
	//		POST /fba/inbound/v0/shipments/{shipmentId}/transport/estimate
			IRestRequest restRequest = new RestRequest("fba/inbound/v0/shipments/" + shipmentId + "/transport/estimate", Method.POST);

			//restRequest.AddHeader("Content-Type"           , "application/json");
			restRequest.AddHeader("x-amz-access-token"     , accessToken);
			restRequest.AddHeader("X-Amz-Security-Token"   , this.GetAMZAWSSecurityToken(marketplaceId));

			this._aWSSigV4Signer = new AWSSigV4Signer(
                   new AWSAuthenticationCredentials
                    {
                        AccessKeyId = this._assumeRoleAccess.accessKeyId,
                        SecretKey = this._assumeRoleAccess.secretKey,
                        Region = AmazonRegion.GetAWSRegionByMarketplaceId(marketplaceId)
                    },
                    new AWSSignerHelper()
                );

			// A selling partner identifier, such as a seller account or vendor code. Note: Required when identifiersType is SKU.
			RestClient client = new RestClient(sellerParnterAPIlUrl);
			IRestResponse apiResponse = client.Post(
				this._aWSSigV4Signer.Sign(
					restRequest,
					new Uri(sellerParnterAPIlUrl).Host
				)
			);

			if (apiResponse.IsSuccessful) 
xxx

}
