### ISSUE TITLE
Minor Issue - Generating SDK with LWA token exchange - productPricingV0.json

### ISSUE THREAD

**Issue by adalgobbo** [amzn/selling-partner-api-models#166]
When generating the SDK with LWA token exchange using the "productPricingV0.json" template I get a compilation error:

![product-pricing-error-message](https://user-images.githubusercontent.com/90683686/133225023-85bab265-de79-4989-84b1-246b6814ba5d.png)

Caused by duplicate:

`    @SerializedName("sellerId")
`
`
     private String sellerId = null;
`

and respective getter and setter.

Solved by removing those lines from OfferDetail.java

**Comment by ShivikaK** [comment]
Hello @adalgobbo 

Thank you for raising this issue.

We were able to identify the duplicate sellerId in the model and will work on removing it from the model.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello,

The duplicate sellerID field has been removed and the model has been updated. 

Thank you for bringing this to our attention and for providing a workaround for this.

Thanks,
Shivika Khare
Selling Partner API Developer Support
