### ISSUE TITLE
The BuyerInfo from OrdersV0.GetOrders() is Empty.

### ISSUE THREAD

**Issue by wangyufenghff** [amzn/selling-partner-api-models#170]
We used the  the getOrders operation to get buyer information for  orders, but  all buyer information is empty.

**Comment by heitke** [comment]
Your developer profile needs to be approved to get PII (Personal Identifiable Information) and then you need to use a security access token to access this data.  See more information here:

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-authorization-to-access-pii-for-bulk-orders

**Comment by Feng-Xg** [comment]
> The buyerInfo endpoint is actually being deprecated at the end of the year. See here: https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#getorderbuyerinfo
> 
> "Important. We recommend using the getOrders operation to get buyer information for an order, as the getOrderBuyerInfo operation is scheduled for deprecation on January 12, 2022. For more information, see the Tokens API Use Case Guide."

I had ignored this important tip, thanks.
