### ISSUE TITLE
[BUG] getReport api GET_SELLER_FEEDBACK_DATA report always return processingStatus=CANCELLED

### ISSUE THREAD

**Issue by promisepk** [amzn/selling-partner-api-models#1724]
**Describe the bug**
Created a GET_SELLER_FEEDBACK_DATA  report 
and then  call getReport api.

AWS4 Canonical Request: '"GET
/reports/2020-09-04/reports/50039018845

The Response processingStatus is cancelled.

**GetReportResponse **
```
class GetReportResponse {
    payload: class Report {
        marketplaceIds: [ATVPDKIKX0DER]
        reportId: 50039018845
        reportType: GET_SELLER_FEEDBACK_DATA
        dataStartTime: 2021-01-01T00:00Z
        dataEndTime: 2021-08-06T01:23:49Z
        reportScheduleId: null
        createdTime: 2021-08-06T01:23:49Z
        processingStatus: CANCELLED
        processingStartTime: 2021-08-06T01:23:55Z
        processingEndTime: 2021-08-06T01:24:01Z
        reportDocumentId: null
    }
    errors: null
}
```

**Comment by johnkw** [comment]
This is a duplicate of bug https://github.com/amzn/selling-partner-api-models/issues/393 (which is still a critical bug and should be reopened instead of being moved to a discussion).
