### ISSUE TITLE
Feature request: expose restock limits data

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-models#1741]
Please expose the Restock Limits data.

Not to be confused with "Restock Inventory Report" (`GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT`)

I'm talking about this report:

![screenshot-20210810T121955-BXLMg9Bf](https://user-images.githubusercontent.com/491247/128812228-843f31dc-0f6a-410d-a923-cf62a9328a69.png)

**Comment by johnkw** [comment]
Why was this ticket closed?

**Comment by moltar** [comment]
@johnkw Don't worry, they are nuking this whole repo soon. It's pointless.

**Comment by johnkw** [comment]
(Thankfully yes these are still searchable in Google after all this craziness of moving them and closing them.  This is for example still the #1 search result for "expose restock limits data".  They're only hidden by default within the github search.)

Nonetheless tickets which are still open issues should remain open.

**Comment by moltar** [comment]
> Nonetheless tickets which are still open issues should remain open.

Yes, I agree!

**Comment by moltar** [comment]
@shreeharsh-a Can you please keep this issue open until it is addressed?

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
