### ISSUE TITLE
Sandbox feeds issue

### ISSUE THREAD

**Issue by vicky-3001** [amzn/selling-partner-api-models#179]
I am trying to call sandbox feeds api for feed type POST_ORDER_FULFILLMENT_DATA. When I check in https://github.com/amzn/selling-partner-api-models/blob/main/models/feeds-api-model/feeds_2021-06-30.json, I dont find 
x-amzn-api-sandbox entry
Only sandbox entry I find in doc is POST_PRODUCT_DATA

Can you please add sandbox for other feed types as well? POST_ORDER_FULFILLMENT_DATA and others

**Comment by franciscocha** [comment]
@vicky-3001 If I'm not mistaken the feed response is universal for all the feeds. Adding one specifically for POST_ORDER_FULFILLMENT_DATA would not change the response whatsoever.

**Comment by rodrifed** [comment]
Hi @vicky-3001,

Thank you for reaching our regarding your issue.

As @franciscocha mentioned, the API response from Feeds API doesn't depend on the feed type you are submitting. That is the reason why we don't provide one sandbox example for each feed type.
You can rely on the [example provided in the model](https://github.com/amzn/selling-partner-api-models/blob/main/models/feeds-api-model/feeds_2021-06-30.json#L375-L397).

Thanks,
Federico
Selling Partner API Developer Support
