### ISSUE TITLE
When can we expect the C# library for feeds

### ISSUE THREAD

**Issue by girija45701** [amzn/selling-partner-api-models#18]
Hi all,

We have the Java project for the feed encryption and download. When is it that we can expect the C# equivalent of the same? Is there a time limit.

- Shankar

**Comment by seanevan** [comment]
Hi @girija45701, as a general rule we don't comment on upcoming features. But we're definitely aware of the need for C# Feeds helper code!. We'll close this issue once we deliver it.

Best regards,
Sean Evans
Manager, Support Engineering

**Comment by girija45701** [comment]
Hi seanevan,

Thanks for the reply. I know. But since this is new and like me there are developers who are trying to work with Amazon for first time helper codes are such a help. I did see the java but that does not help much.

Anyways, i do not think i have any options rather than waiting.

- Shankar

**Comment by NetRushJacob** [comment]
We would love to have this as well, to the extent that, if anyone is willing and able, we would love to colab on getting something put together and shared here.

We're having issues on both feeds and reports with the encryption; nothing seems to work.

**Comment by tenitre** [comment]
hey guys 

I have explained a very simple example here https://github.com/amzn/selling-partner-api-models/issues/31 if anyone is still interested

thx
