### ISSUE TITLE
vendor-direct-fulfillment-inventory-api-model's issue with only submitting vendorProductIdentifier in an item 

### ISSUE THREAD

**Issue by jdliangli** [amzn/selling-partner-api-models#180]
For vendor-direct-fulfillment-inventory-api-model, I'm trying to update inventory of items by calling  the operation submitInventoryUpdate.

Inside the documentation, for SubmitInventoryUpdateRequest, inside ItemDetails, there are buyerProductIdentifier and vendorProductIdentifier. The document says "Either buyerProductIdentifier or vendorProductIdentifier should be submitted".

But when I only submitted the vendorProductIdentifier, the update transaction failed. But If I submitted both identifiers or only buyerProductIdentifier, the transaction was successful.

The error transaction status response Object is 

class TransactionStatus {
    transactionStatus: class Transaction {
        transactionId: 174362f1-90f3-435d-a6a7-44fea05d4bd4-20211012202546
        status: Failure
        errors: class ErrorList {
            [class Error {
                code: INVALID_ITEM_ID
                message: 409304 is not a valid product ID
                details: Ensure that your product ID (SKU/UPC/EAN) is correctly mapped to an Amazon ASIN.
            }]
        }
    }
}

The request Object is

class SubmitInventoryUpdateRequest {
    inventory: class InventoryUpdate {
        sellingParty: class PartyIdentification {
            partyId: J####
        }
        isFullUpdate: false
        items: [class ItemDetails {
            buyerProductIdentifier: null
            vendorProductIdentifier: 409304
            availableQuantity: class ItemQuantity {
                amount: 9
                unitOfMeasure: Each
            }
            isObsolete: false
        }]
    }
}

The vendorProductIdentifier is correct, I can get the value inside the vendor-direct-fulfillment-order-api-model;s Order object.

So, I want to ask, can I update the item inventory by only submitting the vendorProductIdentifier? Or the document is not correct?

**Comment by coder771** [comment]
@jdliangli where do you get buyerProductIdentifier from? I'm having same issue
