### ISSUE TITLE
listings-items-api operation putListingItem

### ISSUE THREAD

**Issue by salvatoremondino** [amzn/selling-partner-api-models#1829]
Hi,
I need the correct JSON object to add new product to Amazon with listings-items-api operation "putListingItem".
I tried with example in this link (https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/listings-items-api-use-case-guide/listings-items-api-use-case-guide_2020-09-01.md#tutorial-create-or-fully-update-a-listing). The response is "ACCEPTED", but I don't see the product in Amazon Seller Center.

It's really urgent. Thank you very much

**Comment by Lemonn8** [comment]
> These guides outline the main components to building out an end-to-end listings workflow using Selling Partner APIs: https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide and https://developer-docs.amazon.com/sp-api/docs/manage-product-listings-guide.
> 
> For most workflows, the general pieces to put together are:
> 
> * Retrieving JSON Schemas from the Product Type Definitions API
> * Submit Requests with the Listings Items API (PUT/PATCH/DELETE) and/or JSON_LISTINGS_FEED (Feeds API)
> * Subscribe to Listings Status and Issues Change Notifications
> * Read Post-Submission Processing Errors Using the Listings Items API (GET)
> 
> By validating using the JSON Schemas, most submission errors can be avoided. Additionally, there is a new "validation preview" option on the Listings Items API that provides a deeper preview of asynchronous processing to identify potential conflict errors (where submissions fail due to conflicting with existing catalog data) or eligibility errors.

Took you guys 3 years to get to it, after it's already been resolved. Guess better late than never, lol.
