### ISSUE TITLE
In getCompetitivePricing payload, the Product field is not getting.

### ISSUE THREAD

**Issue by raja1621** [amzn/selling-partner-api-models#184]
In getCompetitivePricing payload, the Product field is missing. In documentation the product field is there, where as in sdk's output is as below:

class GetPricingResponse {
    payload: class PriceList {
        [class Price {
            amount: null
            currencyCode: null
        }]
    }
    errors: null
}

Please let us know whether the Product Field is available in getCompetitivePricing or not

**Comment by stefnats** [comment]
I had a similar issue. Could you please check if you have multiple APIs (for example product pricing and product fees Api) in the same namespace? If so, try changing the namespace for each Api in swagger codegen.
