### ISSUE TITLE
Can't generate client library for .netstandard framework

### ISSUE THREAD

**Issue by tarurar** [amzn/selling-partner-api-models#186]
Steps to reproduce:

- install swagger-codegen client
- clone the selling partner api models repository
- run the code generation for example, for Sellers API: `swagger-codegen generate -i ../selling-partner-api-models/models/sellers-api-model/sellers.json -l csharp-dotnet2 -t ../selling-partner-api-models/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/resources/swagger-codegen/templates`

Output:
```
i.s.codegen.v3.AbstractGenerator - writing file /Users/atarutin/RiderProjects/selling-partner-api-client-library/./docs/Participation.md
Exception in thread "Thread-0" java.lang.RuntimeException: Could not generate api file for 'Sellers'
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:579)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:782)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:388)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/csharp-dotnet2/Users/atarutin/RiderProjects/selling-partner-api-client-library/../selling-partner-api-models/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/resources/swagger-codegen/templates/api.mustache:1:3: The partial '/handlebars/csharp-dotnet2/partial_header.mustache' at '/handlebars/csharp-dotnet2/partial_header.mustache' could not be found
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:236)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:25)
	at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:795)
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:538)
	... 3 more
```

**Comment by coder771** [comment]
> Steps to reproduce:
> 
> * install swagger-codegen client
> * clone the selling partner api models repository
> * run the code generation for example, for Sellers API: `swagger-codegen generate -i ../selling-partner-api-models/models/sellers-api-model/sellers.json -l csharp-dotnet2 -t ../selling-partner-api-models/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/resources/swagger-codegen/templates`
> 
> Output:
> 
> ```
> i.s.codegen.v3.AbstractGenerator - writing file /Users/atarutin/RiderProjects/selling-partner-api-client-library/./docs/Participation.md
> Exception in thread "Thread-0" java.lang.RuntimeException: Could not generate api file for 'Sellers'
> 	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:579)
> 	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:782)
> 	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:388)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/csharp-dotnet2/Users/atarutin/RiderProjects/selling-partner-api-client-library/../selling-partner-api-models/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/resources/swagger-codegen/templates/api.mustache:1:3: The partial '/handlebars/csharp-dotnet2/partial_header.mustache' at '/handlebars/csharp-dotnet2/partial_header.mustache' could not be found
> 	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:236)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
> 	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
> 	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
> 	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:25)
> 	at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:795)
> 	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:538)
> 	... 3 more
> ```

did this ever work for you?

**Comment by franciscocha** [comment]
@tarurar If you don't specify and output it will try to output the results on the folder you are executing this command. So it might be a permissions issue. I would suggest to use the "-o" option in order to specify an output.

**Comment by smargoli2** [comment]
I'm having a similar issue with the templates. When I try to generate using -t and the folder with the templates, I get the following error:
ERROR io.swagger.codegen.AbstractGenerator - csharp-dotnet2\partial_header.mustache (The system cannot find the path specified)
java.lang.RuntimeException: can't load template csharp-dotnet2\partial_header.mustache

**Comment by franciscocha** [comment]
@smargoli2 can you post the entire string that you are trying to execute?

**Comment by smargoli2** [comment]
I ended up creating empty partial_header.mustache and visibility.mustache files and the templates processed correctly. Now I have an error that 'The type or namespace name 'IApiAccessor' could not be found (are you missing a using directive or an assembly reference?)' in each API. Where is this interface defined?
Also, how can I generate one API Client to use for all the models, instead of having an API client generated for each model?

**Comment by franciscocha** [comment]
@smargoli2 I haven't run into any issues with the code generation. If you post the full generation string you are using I might be able to help you troubleshoot.

**Comment by smargoli2** [comment]
`java -jar swagger-codegen-cli.jar generate -i "AmazonAPIJsonModels\models\fba-small-and-light-api-model\fbaSmallandLight.json" -l csharp-dotnet2 -o "AmazonGeneratedModels\FBASmallLight" -t "AmazonAPIJsonModels\clients\sellingpartner-api-aa-csharp\src\Amazon.SellingPartnerAPIAA\resources\swagger-codegen\templates" --api-package FBASmallLightApi -DpackageName=FBASmallLightModel`
The json file and templates are downloaded to my machine.

**Comment by franciscocha** [comment]
@smargoli2 we use Java and I don't remember if we ran into this issue. But I do remember that how the swagger json was made the namespace of various classes were set to swagger.io. I manually fixed all of them to a more sensical namespace before generating anything from that.

**Comment by smargoli2** [comment]
Right, I did customize those namespaces. The Java ApiClient.mustache has this import statement:
`import com.google.common.util.concurrent.RateLimiter;` while the C# version says `using RateLimiter;` but the Nuget package is not included. Do you have the package in your generated Java code...?

**Comment by franciscocha** [comment]
We do have have that package imported and had no issues using it. But again this is in Java and I did have some issues with dependencies but I don't remember if it was specific to import com.google.common.util.concurrent.RateLimiter. I'm not sure if you run into these types of issues in C# but when we do in Java I end up removing all of the downloaded dependencies and force the application to redownload them.
