### ISSUE TITLE
C# Working Code Examples - HOW TO GET STARTED!

### ISSUE THREAD

**Issue by antonycartwright** [amzn/selling-partner-api-models#188]
Hi Everyone,

A year ago, I lamented about poor documentation and no working examples. Now, it's much better. Instructions for C# are still very poor. To get started from the very start, this is what you need to do:

**Follow the guide for setting up credentials, but ignore the rest of the guide completely. You only want to achieve one thing with the guide; that is getting the 5 pieces of data mentioned below.**

At the start, you need only 5 things; A client Id, Client Secret, Refresh Token, an access key and a secret key. These 5 things will allow you to start - pretty much. There's no point in investing time reading anything else or practicing any code until you have these items. The guide shows you how to set them up. It's pretty heavy but it does work. When you're set up:

**_A client Id, Client Secret, Refresh Token:_**
Get these from https://sellercentral.amazon.co.uk/marketplacedeveloper/applications
Look for View app and also the word authorise. You'll be able to see the three things for your app. Make a note of them.

**_Access key and secret key_**
Get these from https://console.aws.amazon.com/iamv2/home#/users
Click your user, go to security, then under access keys, you should see the access key, click it and you should be able to see the secret/make a new one, etc.

When you have these things, you're almost ready to start, but you need a few more things:
You need your client region endpoint, for me it's https://sellingpartnerapi-eu.amazon.com.
You need you marketplace Id, for me it's A1F83G8C2ARO7P.
You also need you AWS region code, for me it's eu-west-1.

**_If you mess up any of these details, you'll likely get "permission denied" or something similar._**

Now! When you have those things, go here to download a working barebones project:
https://github.com/Cxiaoao/amazon-sellingpartner-api/archive/refs/heads/master.zip

Extract the zip.

Create a new project of your own and add all of the existing .cs files from the Amazon.SellingPartnerAPIAA folder of the zip which you just extracted. (LWAClient, LWAAccessToke, etc etc etc)

In your form, add a simple button, and for the handler, paste in this code:

<code>
            LWAAuthorizationCredentials lwaAuthorizationCredentials = new LWAAuthorizationCredentials
            {
                ClientId = "amzn1.application-oa2-client.ce043fgfgf",
                ClientSecret = "394e9e9fe991aacc859hh2fgfgfgfgf",
                RefreshToken = "Atzr|IwEBINhhhfgfgnNj",
                Endpoint = new Uri("https://api.amazon.com/auth/o2/token")
            };

            RestClient client = new RestClient("https://sellingpartnerapi-eu.amazon.com");

            RestRequest request = new RestRequest("/orders/v0/orders", Method.GET);
            request.AddQueryParameter("MarketplaceIds", "A1F83G8C2ARO7P");
            request.AddQueryParameter("CreatedAfter", "2020-12-01T00:00:00Z");
            LWAAuthorizationSigner auth = new LWAAuthorizationSigner(lwaAuthorizationCredentials);
            auth.Sign(request);

            AWSAuthenticationCredentials aws = new AWSAuthenticationCredentials();

            aws.AccessKeyId = "dfdfdfdf";
            aws.SecretKey = "dfdf+dfdfdf";
            aws.Region = "eu-west-1";
            AWSSigV4Signer signer = new AWSSigV4Signer(aws);
            signer.Sign(request, client.BaseUrl.Host);

            var resp = client.Execute(request);
            Console.WriteLine(resp.StatusCode);
            Console.WriteLine(resp.Content);
</code>

With the NuGet package manager, add in RestSharp and Netwonsoft.Json. Fix any import issues. 

Put a break on the line; "var resp = client.Execute(request); "

Run your project and click the button! Look at the response. If you get "OK", you're good to go, if not, your credentials are most likely wrong. This works for me!

:-D

**Comment by coder771** [comment]
do we need to add all files from Amazon.SellingPartnerAPIAA folder in the project. can we not add it as a library?

**Comment by coder771** [comment]
> Hi Everyone,
> 
> A year ago, I lamented about poor documentation and no working examples. Now, it's much better. Instructions for C# are still very poor. To get started from the very start, this is what you need to do:
> 
> **Follow the guide for setting up credentials, but ignore the rest of the guide completely. You only want to achieve one thing with the guide; that is getting the 5 pieces of data mentioned below.**
> 
> At the start, you need only 5 things; A client Id, Client Secret, Refresh Token, an access key and a secret key. These 5 things will allow you to start - pretty much. There's no point in investing time reading anything else or practicing any code until you have these items. The guide shows you how to set them up. It's pretty heavy but it does work. When you're set up:
> 
> **_A client Id, Client Secret, Refresh Token:_** Get these from https://sellercentral.amazon.co.uk/marketplacedeveloper/applications Look for View app and also the word authorise. You'll be able to see the three things for your app. Make a note of them.
> 
> **_Access key and secret key_** Get these from https://console.aws.amazon.com/iamv2/home#/users Click your user, go to security, then under access keys, you should see the access key, click it and you should be able to see the secret/make a new one, etc.
> 
> When you have these things, you're almost ready to start, but you need a few more things: You need your client region endpoint, for me it's https://sellingpartnerapi-eu.amazon.com. You need you marketplace Id, for me it's A1F83G8C2ARO7P. You also need you AWS region code, for me it's eu-west-1.
> 
> **_If you mess up any of these details, you'll likely get "permission denied" or something similar._**
> 
> Now! When you have those things, go here to download a working barebones project: https://github.com/Cxiaoao/amazon-sellingpartner-api/archive/refs/heads/master.zip
> 
> Extract the zip.
> 
> Create a new project of your own and add all of the existing .cs files from the Amazon.SellingPartnerAPIAA folder of the zip which you just extracted. (LWAClient, LWAAccessToke, etc etc etc)
> 
> In your form, add a simple button, and for the handler, paste in this code:
> 
> `` LWAAuthorizationCredentials lwaAuthorizationCredentials = new LWAAuthorizationCredentials { ClientId = "amzn1.application-oa2-client.ce043fgfgf", ClientSecret = "394e9e9fe991aacc859hh2fgfgfgfgf", RefreshToken = "Atzr|IwEBINhhhfgfgnNj", Endpoint = new Uri("https://api.amazon.com/auth/o2/token") }; ``` RestClient client = new RestClient("https://sellingpartnerapi-eu.amazon.com"); RestRequest request = new RestRequest("/orders/v0/orders", Method.GET); request.AddQueryParameter("MarketplaceIds", "A1F83G8C2ARO7P"); request.AddQueryParameter("CreatedAfter", "2020-12-01T00:00:00Z"); LWAAuthorizationSigner auth = new LWAAuthorizationSigner(lwaAuthorizationCredentials); auth.Sign(request); AWSAuthenticationCredentials aws = new AWSAuthenticationCredentials(); aws.AccessKeyId = "dfdfdfdf"; aws.SecretKey = "dfdf+dfdfdf"; aws.Region = "eu-west-1"; AWSSigV4Signer signer = new AWSSigV4Signer(aws); signer.Sign(request, client.BaseUrl.Host); var resp = client.Execute(request); Console.WriteLine(resp.StatusCode); Console.WriteLine(resp.Content); ``` ``
> With the NuGet package manager, add in RestSharp and Netwonsoft.Json. Fix any import issues.
> 
> Put a break on the line; "var resp = client.Execute(request); "
> 
> Run your project and click the button! Look at the response. If you get "OK", you're good to go, if not, your credentials are most likely wrong. This works for me!
> 
> :-D

You are not using AssumeRoleResponse ARN code to make the request, I can see in this example its using that. does it not cause issue by not using that?
https://github.com/amzn/selling-partner-api-models/issues/31

**Comment by jadanah** [comment]
Here's a link to my repo which has all the amazon selling partner api client's with some usage samples built via nswag using httpclient vs. amazon's restsharp implementation.

https://github.com/jadanah/amazon-selling-partner-api-csharp-samples
