### ISSUE TITLE
Product Feed submission stuck in IN_PROGRESS for last 48 hrs..

### ISSUE THREAD

**Issue by SouravPal95** [amzn/selling-partner-api-models#1899]
I was using the feeds API to submit a json listings feed payload. Usually the feed processing report gets generated quite fast but on this particular occassion it has been stuck for 48 hours in IN_PROGRESS stage without any developments. I have reached out to developer support and they have been least helpful..... case id: 7377409152.

**Comment by limeng92** [comment]
Hello, I am a developer. I need to synchronize inventory to Amazon in batches. I use the feed API to upload XML and modify it synchronously. I try to test the API debugging function. However, the feed I submitted before (304792019903) can be processed normally. The feed I submitted today is always in the IN_PROGRESS state. Have you encountered such a problem? How do you deal with it? Thank you.

**Comment by lmarkenson** [comment]
Hello

I'm experiencing a JSON_LISTING_FEED that has been stuck in progress for almost 48 hours.
Has anyone else encountered this issue?

Thank you!
