### ISSUE TITLE
createProductReviewAndSellerFeedbackSolicitation response codes

### ISSUE THREAD

**Issue by lswamy** [amzn/selling-partner-api-models#19]
The response code for successfully submitting a product review request is 201 as documented.
However, submitting a request again for the same order id responds with a 403 error code and the response
`{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "The requested solicitation is not available for this amazonOrderId.",
      "details": ""
    }
  ]
}`

Is it possible to return a different error code in this scenario such as a 409? 
It would help differentiate between authentication errors and failed requests that have valid tokens

**Comment by hinavinayak** [comment]
Hello,  
Thank you for the feedback. We have relayed it to our product team for consideration
