### ISSUE TITLE
Feature: Add Departure Country for FBA Orders

### ISSUE THREAD

**Issue by WO-GernotGoetz** [amzn/selling-partner-api-models#190]
Hi, we need the departure country for each order (for tax reasons it is important for us to know from which country orders are send to other countries). 

This information is in the report VAT_TRANSACTION, but this report is generated up to a month later than an order happens, so we can not wait for this report before importing the orders to our system. 

Could you please add the information departure country to ordersV0?

Thank you.

**Comment by technityPacini** [comment]
this is still an issue
