### ISSUE TITLE
I test it in sandbox with calling putTransportDetails(PUT /fba/inbound/v0/shipments/{shipmentId}/transport) method, but return 500 error.

### ISSUE THREAD

**Issue by xupucha** [amzn/selling-partner-api-models#192]
I need sends transportation information to Amazon about an inbound shipment refer to fulfillmentInboundV0.json.
So I test it in sandbox with calling putTransportDetails(PUT /fba/inbound/v0/shipments/{shipmentId}/transport) method, but return 500 error.

invove params:
class PutTransportDetailsRequest {
    isPartnered: true
    shipmentType: SP
    transportDetails: class TransportDetailInput {
        partneredSmallParcelData: null
        nonPartneredSmallParcelData: class NonPartneredSmallParcelDataInput {
            carrierName: USPS
            packageList: class NonPartneredSmallParcelPackageInputList {
                [class NonPartneredSmallParcelPackageInput {
                    trackingId: werwrwerwrwrer
                }]
            }
        }
        partneredLtlData: null
        nonPartneredLtlData: null
    }
}

error:
{
  "errors": [
    {
      "message": "We encountered an internal error. Please try again.",
     "code": "InternalFailure"
    }
  ]
}

any help? Thanks a lot.

**Comment by franciscocha** [comment]
@xupucha I was able to get a successful call to work. Below is the body I used:

```
{
    "IsPartnered": true,
    "ShipmentType": "SP",
    "TransportDetails": {
        "NonPartneredLtlData": {
            "CarrierName": "USPS",
            "ProNumber": "3746274"
        },
        "NonPartneredSmallParcelData": {
            "CarrierName": "USPS",
            "PackageList": [
                {
                    "TrackingId": "werwrwerwrwrer"
                }
            ]
        },
        "PartneredLtlData": {
            "BoxCount": 1,
            "Contact": {
                "Email": "abc@test.com",
                "Fax": "234-343-3434",
                "Name": "Test1",
                "Phone": "234-343-3434"
            },
            "FreightReadyDate": "2020-03-27",
            "PalletList": [
                {
                    "Dimensions": {
                        "Height": 13,
                        "Length": 13,
                        "Unit": "inches",
                        "Width": 13
                    },
                    "IsStacked": true,
                    "Weight": {
                        "Unit": "pounds",
                        "Value": 13
                    }
                }
            ],
            "SellerDeclaredValue": {
                "CurrencyCode": "USD",
                "Value": 20
            },
            "SellerFreightClass": "50",
            "TotalWeight": {
                "Unit": "pounds",
                "Value": 13
            }
        },
        "PartneredSmallParcelData": {
            "CarrierName": "string",
            "PackageList": [
                {
                    "Dimensions": {
                        "Height": 11,
                        "Length": 11,
                        "Unit": "inches",
                        "Width": 11
                    },
                    "Weight": {
                        "Unit": "pounds",
                        "Value": 11
                    }
                }
            ]
        }
    }
}
```

**Comment by rodrifed** [comment]
Hi @xupucha,

Thanks for bringing your issue to our attention.

While using the sandbox endpoints, please make sure that the input parameters of your API call are the same than the ones provided in the [API model](https://github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-inbound-api-model/fulfillmentInboundV0.json#L1748). Otherwise, the call will fail with HTTP 500.

Thanks,
Federico
Selling Partner API Developer Support
