### ISSUE TITLE
Connecting to the Selling Partner API using a generated Java SDK

### ISSUE THREAD

**Issue by codelang** [amzn/selling-partner-api-models#193]
1、
AWSCredentialsProvider
credentialsProvider = new STSAssumeRoleSessionCredentialsProvider
  .Builder("myRoleArn", "uniqueNameForRoleSession")
  .withStsClient(AWSSecurityTokenServiceClientBuilder.standard()
    .withRegion(“region”)
    .withCredentials(awsCreds)
    .build())
  .build();

 .withCredentials(awsCreds);  
error：com.amazonaws.auth.BasicAWSCredentials can not be changed to com.amazonaws.auth.AWSCredentialsProvider

2、
SellersApi sellersApi = new SellersApi.Builder()
  .awsAuthenticationCredentialsProvider(credentialsProvider)
  .lwaAuthorizationCredentials(lwaAuthorizationCredentials)
  .endpoint("https://sellingpartnerapi-na.amazon.com")
  .build();
sellersApi.getMarketplaceParticipations()

 .awsAuthenticationCredentialsProvider(credentialsProvider)
error： com.amazonaws.auth.AWSCredentialsProvider  can not be changed to 
 com.amazon.SellingPartnerAPIAA.AWSAuthenticationCredentialsProvider

**Comment by franciscocha** [comment]
```
Your credential provider is wrong. Use the code below: 
AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = 
AWSAuthenticationCredentialsProvider.builder()
            .roleArn("arn:aws:iam::XXXXXXXXX:role/XXXXXXXXX")
            .roleSessionName("session-name")
            .build();
```

**Comment by Adrian-T-AMZN** [comment]
Hello @codelang,

Thank you for reaching out regarding the issue with the credentials provider.

Please follow the suggestion from [franciscocha](https://github.com/franciscocha).

If that does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian T.
Selling Partner API Developer Support
