### ISSUE TITLE
Getting "Access token is missing in the request header" error for getauthorizationCode operation.

### ISSUE THREAD

**Issue by Sai-Srikar** [amzn/selling-partner-api-models#194]
Hi all,

I am trying to convert an existing MWS authorization into SP-API one using getauthorizationCode call mentioned in the API docs.
But i am getting the following error. 
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": "Access token is missing in the request header."
        }
    ]
}

Please find the request details below

GET /authorization/v1/authorizationCode?sellingPartnerId=A1*****RCK1H&developerId=*****&mwsAuthToken=*******HTTP/1.1
Host: sellingpartnerapi-na.amazon.com
grant_type: client_credentials
scope: sellingpartnerapi::migration
client_id: **********
client_secret: ****************
X-Amz-Date: 20211126T041730Z
Authorization: AWS4-HMAC-SHA256 Credential=**********/20211126/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date, Signature=9f78b181ba158bd11cd276a4d73ba8b698c1822ab47cf71c1ba7b94e9da22faf

Can anyone correct me if i am passing any incorrect headers or parameters. In general while making this call we won't be having the access token so not sure why amazon is again asking access token

Thank you

**Comment by yiiprogrammer** [comment]
which programming language are you using?
