### ISSUE TITLE
In CatalogItem-API the attribute 'productGroup' is only available under 'vendorDetails' in Version 2020-12-01 

### ISSUE THREAD

**Issue by Schubi1981** [amzn/selling-partner-api-models#199]
When making requests to the CatalogItem-API, the attribute "productGroup" is currently only available under vendorDetails. So if you don't have the permission to request vendorDetails, it is not possible to get that information. In Version v0 the productGroup is available under AttributeSets for everyone. So I would have to make two calls to get all the information I need (in v0 on the other hand no EANs are returned, for example). It would be nice, if the productGroup would also appear under summaries and/or attributes.

**Comment by chapmanjw** [comment]
@Schubi1981 Thank you for the feedback. The "productGroup" in the v2020-12-01 `vendorDetails` is a different ASIN property from the "ProductGroup" in the v0 version. They do overlap in some cases, but are different in others.

For example `B09313QPSV` in the US marketplace is "Toy" for both values. Whereas `B07GRLXH7X` in the US marketplace is "Sports" in the `vendorDetails` of the v2020-12-01 version and "Apparel" in the v0 version. 

I'm taking two pieces of feedback from this issue:

1. Porting forward the product group property from the v0 into the `summaries` section of the v2020-12-01 version. 
2. Provide disambiguation/clarity on the distinction between the two values (I'm not entirely sure at the moment what the difference is, so I need to do some deep diving on that).

We are planning iterations on the v2020-12-01 version for 2022. I will include this in the list of items to address. Thanks!

**Comment by julian-eggers** [comment]
@chapmanjw  Any updates/timeline on this?

The migration-hub is saying that v0 will be removed at the end of september 2022.

**Comment by chapmanjw** [comment]
@julian-eggers The `websiteDisplayGroup` (which is what the MWS Products API actually referenced) is included in the summaries data for the newly released v2022-04-01 version: https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference
