### ISSUE TITLE
finances-api-model not properly formatted JSON

### ISSUE THREAD

**Issue by charliecode** [amzn/selling-partner-api-models#2]
The finances-api-model/financesV0.json is not properly formatted. 

I tested all of the other models without this error. It happened via SwaggerHub, locally run Swagger open source as well as through my Webstorm OpenAPI plugin, so it appears to def be improperly formatted.

I noticed there were some recent changes made to that file so I also tested the most recent commit and got the same error as well.

**Comment by seanevan** [comment]
@charliecode, thanks for the report! We're looking into it.

**Comment by BilalHasanKhan** [comment]
The bracket after RemovalShipmentItemAdjustment is redundant and closes the block prematurely

![image](https://user-images.githubusercontent.com/1527108/93314355-4566cf00-f827-11ea-8eb0-d43f04c736d9.png)

**Comment by seanevan** [comment]
We are fixing this in our internal pipeline, with a fix forthcoming. We are also investigating how this syntax error escaped our API linter.

**Comment by charliecode** [comment]
Already submitted a PR to fix. After looking over multiple files and seeing similar issues it does seem the linter is not catching things.

**Comment by evdeg** [comment]
@charliecode Thanks again for reporting this issue! The fix was pushed in [f64f4a2](https://github.com/amzn/selling-partner-api-models/commit/f64f4a2dd8d3693d8a45bd549f51efcb5ba7f251).
