### ISSUE TITLE
Intermittent LWA Token Access Error

### ISSUE THREAD

**Issue by jhullparkseed** [amzn/selling-partner-api-models#201]
In that past few months, starting in Nov 2021 the program we havre to do Data integration with Amazon using SP-API has been throwing either of two errors:

Error message is: Error getting LWA Access Token
Error message is: Error getting LWA Access Token: Unsuccessful LWA token exchange

I am also getting a third error that occurs within a provided function called '.SignWithSTSKeysAndSecurityTokenn'

What troubles me is that the are not *consistant* errors for at times the program runs with no errors, at times I get one of the three.  When I did development and testing before Nov 2021 I did not receive these errors not had issues with security.  Since Nov 2021 they appear daily and I have not changed the program.

I feel there us some timing issue within Amazon' SP-API processing because I do send a refresh token with each request and again....

these errors are inconsistent.  I've searched Google and here and I have verified that the code is setting up the correct conditions so did somet4hing change in Nov 2021 to cause these issues to occur?  In one example I can get 22 orders in a call, then as I am processing to get the shipping address I will process the protected data till I hit the throttle, wait the required time, then pull two more before I get the error.  Each one of those calls goes through the same source, 21 work, it fails on the 22 and that is just one example.  It happens on one or many, but not all the time.

That is happening to cause this error?

Did Amazon Kind of now require a restricted Token on all SP-API order calls because I do not get this on feed calls.

**Comment by hanxiao123** [comment]
I meet same error and solved ,your refresh token must be error!
