### ISSUE TITLE
Generating report for GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 resulting in error Request for report type 1118 is not allowed at this time

### ISSUE THREAD

**Issue by shahviren1985** [amzn/selling-partner-api-models#2010]
POST Request URL - https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports

Request Body - {
  "reportType": "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2",
  "marketplaceIds":["A21TJRUUN4KGV"]
}

Response - 400 bad request
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Request for report type 1118 is not allowed at this time",
            "details": ""
        }
    ]
}

**Comment by yashraj021** [comment]
> Anuj,
> 
> you need to call GET api using this URL - change the api endpoint and marketlace ids according to your marketplace. In response you will get the auto generated settlement reports from Amazon.
> 
> https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports?reportTypes=GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE&marketplaceIds=A21TJRUUN4KGV
> 
> This is working and you will get the settlement data reports.

Why is this sending reports for multiple market IDs when I am just mentioning the USA Marketplace ID

**Comment by b1bee** [comment]
> > Anuj,
> > you need to call GET api using this URL - change the api endpoint and marketlace ids according to your marketplace. In response you will get the auto generated settlement reports from Amazon.
> > https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports?reportTypes=GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE&marketplaceIds=A21TJRUUN4KGV
> > This is working and you will get the settlement data reports.
> 
> Why is this sending reports for multiple market IDs when I am just mentioning the USA Marketplace ID

Same here

**Comment by jonagoldman** [comment]
From the [Settlement Reports Docs](https://developer-docs.amazon.com/sp-api/docs/report-type-values-settlement):

> [!WARNING]
> Settlement reports cannot be requested or scheduled. They are automatically scheduled by Amazon (usually every 14 days) and are tied to the disbursement cycle of a seller account.

> [!IMPORTANT]
> A report is available for 90 days after creation. After this time, you must manually regenerate the report in Seller Central.

So you can't generate a settlement report.
