### ISSUE TITLE
Missing Package Quantity in API Catalog 2020-12-01

### ISSUE THREAD

**Issue by hoangtrucit** [amzn/selling-partner-api-models#202]
I call `Catalog 2020-12-01` with `includedData=[attributes,productTypes,salesRanks,images,identifiers,summaries,variations]` it returns lot of data but I couldn’t find Package Quantity anywhere in the result. Whereas I use `Catalog V0` it returns Package Quantity. Did I miss anything here? Can you help me where I can find Package Quantity.
ASIN = https://www.amazon.com/dp/B001E0W1ZW?th=1&psc=1
Package Qty. should be 2

**Comment by Adrian-T-AMZN** [comment]
Hello @[hoangtrucit](https://github.com/hoangtrucit),

Thank you for reaching out regarding the Package Quantity element for the Catalog Items API.

You can find the information you need using the latest version of the Catalog Items API:

https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#itemsummarybymarketplace

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian T.
Selling Partner API Developer Support
