### ISSUE TITLE
Selling Partner API Authentication/Authorization Library not compatible with RestSharp V107

### ISSUE THREAD

**Issue by ThomasL1973** [amzn/selling-partner-api-models#203]
Selling Partner API Authentication/Authorization Library does not work with RestSharp V107 because IRestRequest is deprecated with V107

**Comment by corbin-munce** [comment]
I updated my own copy https://github.com/corbin-munce/selling-partner-api-models/commit/75b5daed502728d464c16c45bb619682eb97d237

**Comment by smargoli2** [comment]
I am dealing with this issue as well. Can the models be updated to use the most recent version of RestSharp? The code will not compile unless I install version 105.1.0!

**Comment by arpetris** [comment]
I agree. I had to downgrade several libraries including RestSharp to get the models and the Authentication/Authorization library to compile.
