### ISSUE TITLE
merchantFulfillmentV0 sandbox call invalid number format

### ISSUE THREAD

**Issue by kkolodzi** [amzn/selling-partner-api-models#204]
In a few sandbox requests, it's expected to receive integer number when documentation says `Type : number (double)`  sending double (10.0) returns error ` "ErrorMessage": "[\r\n  {\r\n    \"code\": \"InvalidInput\",\r\n    \"message\": \"Could not match input arguments\"\r\n  }\r\n]"` for example: GetEligibleShipmentServices.
Same problem spotted in PackageDimension and Weight objects
![image](https://user-images.githubusercontent.com/20204400/149757064-ec68f8df-1fc7-45e6-bd94-db4ab7341617.png)
![image](https://user-images.githubusercontent.com/20204400/149757084-3081fef8-7a94-4f75-9a33-d534d30f2a56.png)

**Comment by xbaha** [comment]
I found the sandbox to be useless for all calls, try on real account, my data comming accurate.

**Comment by parvathm** [comment]
Hi @franciscocha/ @kkolodzi  ,

Thank you for letting us know about this issue. We are looking into it. Can you also please open a [support case](https://sellercentral.amazon.com/gp/mws/contactus.html?) with details which helps in troubleshooting quickly. If you have already created a support case please provide us the case id.

Thanks,
Parvathm,
Selling Partner API Developer Support.

**Comment by franciscocha** [comment]
@parvathm I've opened a support case according to your instructions. Case ID: 9635642951

**Comment by franciscocha** [comment]
@jevoniuk @parvathm Is there any progress on this issue? Our development is on hold because we are unable to test our code.

**Comment by franciscocha** [comment]
@jevoniuk @parvathm Can you please reach out to whoever responded to my case? Case ID: 9635642951. They did not understand that the issue isn't about creating a request but that the Sandbox isn't able to accept the request because the Sandbox is expecting an integer value instead of a decimal value.

**Comment by franciscocha** [comment]
@ShivikaK Can you please share your sandbox request that you claim is getting a valid response? I have tried it many times and the only way to get a response is when both the weight and dimension values are integers.
