### ISSUE TITLE
Listings API patchListingsItem operation possible fulfillment_channel_code replace issue

### ISSUE THREAD

**Issue by NetrushAbhijit** [amzn/selling-partner-api-models#2061]
Hello,

With reference to:
**API: Listings
Operation: patchListingsItem** 

We noticed that - when we tried updating the fulfillment_channel_code on a listing using the 'patchListingsItem' operation, it created an additional fulfillment_channel_code on the listing instead of replacing an existing one. 

Here's what we tried - On one of our SKUs, we tried flipping the fulfillment_channel_code from 'DEFAULT' (MFN) to 'AMAZON_NA' (FBA) by firing the below mentioned request. 

```
{
	{
		"productType": "PRODUCT",
		"patches": [
			{
				"op": 1, //Replace
				"path": "/attributes/fulfillment_availability",
				"value": [
					{
						"fulfillment_channel_code": "AMAZON_NA",
						"quantity": 0
					}
				]
			}
		]
	},
	"sellerId ": "[SellerId]",
	"sku": "[SKU]",
	"marketplaceIds": [
		"ATVPDKIKX0DER"
	],
	"issueLocale": "en_US"
}
```

We then fired the Listings API 'getListingsItem' to see how it looks like on the listing and found below json under the fulfillment_availability node of the response:

```
"attributes": {
		"fulfillment_availability": [
			{
				"fulfillment_channel_code": "DEFAULT",
				"quantity": 21,
				"marketplace_id": "ATVPDKIKX0DER"
			},
			{
				"fulfillment_channel_code": "AMAZON_NA",
				"quantity": 0,
				"marketplace_id": "ATVPDKIKX0DER"
			}
		],
```

So, instead of replacing existing "fulfillment_channel_code": "DEFAULT", it created a new fulfillment_channel_code. So, just wondering if this is by design or we are missing something?

Thanks,
Abhijit

**Comment by enochlev** [comment]
Is there a way to decrement listing? Like what if a listing was sold within the 15min time window to update? I can see there is room for race conditions
