### ISSUE TITLE
Get Orders call without RDT?

### ISSUE THREAD

**Issue by coder771** [amzn/selling-partner-api-models#210]
Can you call GetOrders call without RDT Token if you are not looking for PII information and just get order details?

**Comment by ghaliano** [comment]
Yes you can

**Comment by puppsupr** [comment]
Hi,

You need RDT only if you would like to access the PII data. Without RDT you can still access the Get Order/Get Orders where you receive response without the PII.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
