### ISSUE TITLE
The processingStatus of Report GET_SELLER_FEEDBACK_DATA  is always return CANCELLED

### ISSUE THREAD

**Issue by sinpobox** [amzn/selling-partner-api-models#2144]
Hi, We need to obtain a customer feedback data from amazon, so we created the type of GET_SELLER_FEEDBACK_DATA Report ,and got the reportId. When we want to get the report with the reportId, the api always return CANCELLED of processingStatus, That why ?  and What can we do to fix this ?

**Comment by johnkw** [comment]
This is a duplicate of bug #393 (which is still a critical bug and should be reopened instead of being moved to a discussion).
