### ISSUE TITLE
GET /definitions/2020-09-01/productTypes marketplaceIds is required but sandbox data has empty params

### ISSUE THREAD

**Issue by minifreak** [amzn/selling-partner-api-models#218]
I'm quite sure that for those whom rely on `x-amzn-api-sandbox` because we don't want to mess with production data, find incredibly difficult to handle it if that data doesn't honor the operation specs. Can you add marketplaceIds to it please?

And yea, I do parse and cache that model crap, so I can play with that terrible static sandbox. It doesn't seem too much to ask if that could be done in a more decent way, for coherence sake you know...

**Comment by franciscocha** [comment]
@minifreak I've ran into this issue with merchant fulfillment. The documentation states a double value for package dimensions and weight, however the sandbox expects integer values so I can't get a valid test response. I was told to open up a support case directly with Amazon. (They are still troubleshooting but at least someone is looking at it) I would recommend you do the same.

**Comment by minifreak** [comment]
yea, I'll do that. Thanks @franciscocha

**Comment by puppsupr** [comment]
Hi,

Were you able to get help on this issue ? If its still an issue, can you please provide the case numbers raised to the support team ?

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
