### ISSUE TITLE
Response on MFN createShipment is not conform to API Modell Address->Name

### ISSUE THREAD

**Issue by Inbasecom** [amzn/selling-partner-api-models#219]
In your JSON definition at https://github.com/amzn/selling-partner-api-models/blob/main/models/merchant-fulfillment-api-model/merchantFulfillmentV0.json a maximum length of 30 characters is clearly defined for the name in the address.

Based on this JSON file our client side script is generated.
If the API then returns strings longer than 30 characters, the client generates an exception.

So please adjust either the JSON definition or the responses of your API accordingly.
Both should be consistent with each other!

Best regards

**Comment by tomaszhanc** [comment]
@puppsupr can you help us with that?

**Comment by tomaszhanc** [comment]
@Inbasecom did you solve it?
