### ISSUE TITLE
audience-rating- or pegi-rating-informations are not available in CatalogItem-API in Version 2020-12-01

### ISSUE THREAD

**Issue by Schubi1981** [amzn/selling-partner-api-models#220]
When making requests to the CatalogItem-API in Version v0 there are attributes such as "AudienceRating" or "PegiRating". These informations are not available in Version 2020-12-01. So I would have to make two calls to get all the information I need (in v0 on the other hand no EANs are returned, for example). It would be nice, if the mentioned attributes would also be available in Version 2020-12-01. Maybe there are also some further age-related attributes, that could be provided (such as CeroAgeRating or EsrbAgeRating, which are documented in the CatalogItem-v0-reference).

**Comment by chapmanjw** [comment]
@Schubi1981 Currently, the Catalog Items API v2020-12-01 `getCatalogItem` limits the available `attributes` data based upon whether or not the product type of the ASIN has launched in the Product Type Definitions API. We are implementing a change to remove this limitation (in the next week or two). 

Could you provide an example ASIN (and marketplace) that include these attributes in the v0 APIs? (I will verify what is returned once this filtering logic is adjusted). Thanks.

**Comment by Schubi1981** [comment]
@chapmanjw Here's an example:

Asin: B07RN6W6M5, MarketplaceID: A1PA6795UKMFR9

Contains in v0-API both AudienceRating and PegiRating and in v2020-12-01 none of such information.

**Comment by AhmedX6** [comment]
Hi, any update of these issue, still pegi not available on 2020-12-01...
