### ISSUE TITLE
couldn't add sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar to my local maven repository

### ISSUE THREAD

**Issue by wassimrim** [amzn/selling-partner-api-models#221]
Hi there, I'm following the steps of "Generating a Java SDK with LWA token exchange and authentication" ,  all the steps works fine for me until i reached step 10 :Build the AA Library and add it as a dependency of the SDK: so in this step i need to install the JAR file in my local Maven repository.For this purpose  i executed this command from my desktop path: mvn install:install-file -Dfile ~/Bureau/selling-partner-api-models/clients/sellingpartner-api-aa-java/target/sellingpartnerapi-aa-java-1.0-jar-with-dependencies.jar -DgroupId=com.amazon.sellingpartnerapi -DartifactId=sellingpartnerapi-aa-java -Dversion=1.0 -Dpackaging=jar , but it throws an error : The goal you specified requires a project to execute but there is no POM in this directory (/home/wassim/Bureau). Please verify you invoked Maven from the correct directory. -> i need some guide and advice thank you!
![Capture d’écran de 2022-02-16 15-27-44](https://user-images.githubusercontent.com/44126885/154285292-770da5b9-4566-49bc-832c-993952f3010b.png)

**Comment by puppsupr** [comment]
Hi, 

If you are still facing the issue, please refer to this blog which has step by step process to generate the Java SDK and make a connection to SP API : https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-java-sdk

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
