### ISSUE TITLE
[BUG] - Encoding of URI Components that have a / forward slash

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-models#2218]
I am still trying to find a solution for how to encode and sign requests when the URI element contains a slash.

so for example:
POST
/products/fees/v0/listings/{sku}/feesEstimate

if {sku} = “mysku/withaslash”…

The supplied dotnet swagger client does not work.

what is the second line of the canonical string to sign to send?
What is the actual raw query string passed to the REST call?
I have tried every combination of encoding I can think of without any love.

**Comment by hexrw** [comment]
Please re-open the issue. Many devs already encountered it and nothing was yet done to fix it.

**Comment by sreecodeslayer** [comment]
Funny enough a bunch of us still keeps fighting the atrocities the API throws at us. even today we just learnt amazon storage fee report headers are different for DE and IN, yet both countries fall under same EU region for API.

**Comment by hexrw** [comment]
Worst DX in my life. This whole thing is a joke.

**Comment by hexrw** [comment]
Issue seems to still be present. I have included a targeted fix in my custom SP API client [github.com/hexrw/amz/spapi](https://github.com/hexrw/amz/tree/main/packages/spapi) (Open-Source)
