### ISSUE TITLE
Unclear How To Obtain Brand Analytics Selling Partner API Role

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-models#2225]
The "Brand Analytics Selling Partner API role" is required to make requests for various reports. However, unlike most other roles, this is not a role we can select for our application. There is no Brand Analytics check box. The documentation is vague on this point as well. 

Can someone provide some details on how we can attach this role so customers can get access to these reports? Thanks.

**Comment by landoncope** [comment]
Getting the Brand Analytics role has been a very frustrating experience. No matter what we do, we get this same rejection:

> Thank you for updating your Amazon Selling Partner API (SP-API) Developer Profile.
>
> We have completed our assessment and have determined that you do not meet criteria for Brand Analytics role access on SP-API. To protect Amazon Customers, we require Developers to have an online business website with publicly available, descriptive information about the analytical products and services provided for Amazon Selling Partners. Services and product must be consistent with section 4.4 and 4.5 of our Acceptable Use Policy.
>
> No changes have been made to your SP-API access at this time.

We've modified our website a dozen times. I even stood up a separate website, with completely different content, and I got the same rejection. I've contacted every Amazon support rep/channel I could find, and they are as useless as ever. 

Any advice?

**Comment by vikingcodes** [comment]
We have multiple seller and we showing Brand Analytics Data, But some seller don't have brand analytics data due to they don't have any brand on amazon. So, we need hide Brand Analytics tab on our app.  Its possible to check that seller have brand on amazon or is seller registred for brands on amaozn ?

**Comment by vollie** [comment]
Hi @saras-daton, @RMagician, @Blochergroup, @sreejithlillydoo2, @vikingcodes; would any of you be willing to share any insights and/or the `Organisation website` used that got you an approval on the Brand Analytics role?🙏

Like @landoncope above, we too keep getting rejected the role based on this point despite modifying the site and would welcome any additional information on getting approved.

**Comment by ranbstar** [comment]
Hi @vollie, @landoncope, @vikingcodes and everyone, following up on this thread - has anyone had success getting approved for the Brand Analytics role since the last update here? We’re running into the same rejection issue (organization website not meeting requirements) and would really appreciate any tips or examples from those who’ve managed to get through. Thanks in advance! 🙏

**Comment by karanrana-artoon** [comment]
Hi @ranbstar
Any luck on how to get approval of Brand Analytics Role. We’re also running into the same rejection issue.

**Comment by vollie** [comment]
Hey, @ranbstar, @karanrana-artoon ; yes, we did. In our case we first hired someone to check/rewrite our T&C's and such (still got us a "no" from them), then we just tried some things and finally on the 7th attempt or something got some actual feedback indicating we had some no-no text somewhere on the site (irt competitor analyses if I recall correctly). We changed that, and then we got approved.

so currently the only "solution" I can give, is to just try something and keep requesting, hoping you get some feedback from them... 😢

**Comment by karanrana-artoon** [comment]
Thank you, @vollie 😊, for sharing this valuable information. We’re continuing our efforts as well and hope to receive approval soon.
I also have a quick question—did you submit any login credentials for your app during the review process? Was the approval based on a hands-on review of the app itself, or solely on the information available on your application website?
