### ISSUE TITLE
listFinancialEvents CustomError required field

### ISSUE THREAD

**Issue by masterevgeni** [amzn/selling-partner-api-models#223]
I using SP-API, I trying get [listFinancialEvents](https://github.com/amzn/selling-partner-api-docs/blob/main/references/finances-api/financesV0.md#listfinancialevents), 
I sending all fields as described.
request:
```method: 'GET',
  url: 'https://sellingpartnerapi-na.amazon.com/finances/v0/financialEvents?details=true&granularityId=ATVPDKIKX0DER&granularityType=Marketplace&marketplaceIds=ATVPDKIKX0DER',
  body: null,
  headers: {
    Authorization: 'AWS4-HMAC-SHA256 Credential=xxxxxxxx, SignedHeaders=host;x-amz-access-token;x-amz-date, Signature=f2c14070a4dc2ae63fbd336938df6085e2e2560d38a94cd3e9562f6cb512f269',
    'Content-Type': 'application/json; charset=utf-8',
    host: 'sellingpartnerapi-na.amazon.com',
    'x-amz-access-token': 'xxxxxxxxx',
    'x-amz-security-token': 'xxxxxxxxx',
    'x-amz-date': '20220303T185615Z'
  }
}
```

response:

```res: {
  body: '{\n' +
    '  "errors": [\n' +
    '    {\n' +
    '      "code": "InvalidInput",\n' +
    '      "message": "Must specify a valid value of atleast one of : 1)AmazonOrderId, 2)FinancialEventGroupId and 3)PostedAfter",\n' +
    '      "details": ""\n' +
    '    }\n' +
    '  ]\n' +
    '}',
```

As I checked "AmazonOrderId" doesn't appear in SP_API, it looks like this field belongs to [MWS api](https://docs.developer.amazonservices.com/en_US/finances/Finances_ListFinancialEvents.html)
as well I tried to pass "AmazonOrderId: "xxx-xxxxx-xxxxxxx"," in query but still getting same error.

any solution or workaround?

Thanks

**Comment by franciscocha** [comment]
@masterevgeni Yeah it looks like they still need to do some more testing with their SPA. However if you are looking for order specific financial events I was able to use /finances/v0/orders/{orderId}/financialEvents.

**Comment by masterevgeni** [comment]
> @masterevgeni Yeah it looks like they still need to do some more testing with their SPA. However if you are looking for order specific financial events I was able to use /finances/v0/orders/{orderId}/financialEvents.

**Comment by adrian-amz** [comment]
Hello @masterevgeni ,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation, as additional details are required from your end.

Thanks,
Adrian C
Selling Partner API Developer Support
