### ISSUE TITLE
Suggest to change tags vendorTransaction and listings

### ISSUE THREAD

**Issue by Mike-the-one** [amzn/selling-partner-api-models#225]
The following models have the same tag `vendorTransaction`:

https://github.com/amzn/selling-partner-api-models/blob/main/models/vendor-transaction-status-api-model/vendorTransactionStatus.json

https://github.com/amzn/selling-partner-api-models/blob/main/models/vendor-direct-fulfillment-transactions-api-model/vendorDirectFulfillmentTransactionsV1.json

and the following models have the same tag: `listings`:

https://github.com/amzn/selling-partner-api-models/blob/main/models/listings-items-api-model/listingsItems_2021-08-01.json

https://github.com/amzn/selling-partner-api-models/blob/main/models/listings-restrictions-api-model/listingsRestrictions_2021-08-01.json

When the code is generated from swagger, the apis end with the same name, so confusing.  Suggest to change to different tags so that we don't end up with the same api names.

thanks

**Comment by smargoli2** [comment]
I'm experiencing this issue as well, can the tag be updated?

**Comment by Mike-the-one** [comment]
> I'm experiencing this issue as well, can the tag be updated?

You wish.  I opened the issue 6 months ago, no one from Amazon replied.

If they need you, they will come here, if the don't need you, they will never.
