### ISSUE TITLE
How to fetch RDT token for Selling Partner API for Direct Fulfillment Orders and Direct Fulfillment Shipping

### ISSUE THREAD

**Issue by rajat-garg** [amzn/selling-partner-api-models#2256]
I am trying to fetch the shipping labels and packaging slips for our Seller Central account but I am not able to generate the RDT token for these requests. 

Acc. to these docs:
https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide
https://github.com/amzn/selling-partner-api-docs/issues/822

we need RDT for following operations/apis. 
getShippingLabels
getPackingSlips
getCustomerInvoices

But on the Token Api references page (https://github.com/amzn/selling-partner-api-docs/blob/main/references/tokens-api/tokens_2021-03-01.md#createrestricteddatatoken) , is showing path available only for orders and shipping api. (PFA screenshot)

![image](https://user-images.githubusercontent.com/6449114/153846370-bed7dff4-363f-44ee-b38e-27d903eeb1d9.png)

Can you please update the document with the other paths as well, I have already tried these paths for getPackingSlips and CustomerInvoices api but it is throwing following error.

Request URL: https://sellingpartnerapi-eu.amazon.com/vendor/directFulfillment/orders/v1/purchaseOrders?createdBefore=20211212T120000Z&createdAfter=20211111T110000Z

(Called it with RDT and STS tokens on postman)

```
{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}

```

**Comment by AnnapurnaNeerukonda** [comment]
Hi @rajat-garg  Did this solution work .
