### ISSUE TITLE
Access was working fine but now I am getting "Access to requested resource is denied" - no changes have been made to process - whats changed ?

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-models#230]
Access was working fine but now I am getting "Access to requested resource is denied" - no changes have been made to process - whats changed ?

Error calling GetCatalogItem: {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": "The access token you provided is revoked, malformed or invalid."
    }
  ]
}

**Comment by franciscocha** [comment]
@nrogers805 Have you checked your refresh token? Also how are you making this call?

**Comment by stefnats** [comment]
I agree with @franciscocha
Are you generating an access token with the refresh token but you are using that access token longer as it is valid? In that case you need to regenerate the access token from the same refresh token.
