### ISSUE TITLE
Sandbox for getReportDocument only provides GET_MERCHANT_LISTINGS_ALL_DATA report

### ISSUE THREAD

**Issue by johnventions** [amzn/selling-partner-api-models#231]
The SP API allows a merchant to call the createReport operation to create nearly 100 different [report types](https://developer-docs.amazon.com/sp-api/docs/report-type-values)

However, the sandbox endpoint for getReportDocument is set to statically always return the report: "GET_MERCHANT_LISTINGS_ALL_DATA" (see [sandbox docs](https://github.com/amzn/selling-partner-api-models/blob/2539b7e83a7cc8b8a3da77689858ecefa693fcdf/models/reports-api-model/reports_2021-06-30.json#L1804))

If we are writing a script to pull another report (i.e. "GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING"):
1. we cannot get that report in the sandbox for unit testing and verification
2. we have to assume what the output data model will be (no example report or documentation on the data model of the report)

Requesting:
- Sandbox provides additional parameter options to simulate other report types
- OR a folder in [reports-api-model](https://github.com/amzn/selling-partner-api-models/blob/main/models/reports-api-model) that has an example output file for each report type

In the meantime, can I get an example output file for GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING ?

**Comment by puppsupr** [comment]
Hi, 

Please see the below schema for GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING report.

order-id     order-item-id     purchase-date     payments-date     reporting-date     
promise-date     days-past-promise     buyer-email     buyer-name     buyer-phone-number
sku     product-name     quantity-purchased     quantity-shipped     quantity-to-ship
ship-service-level     recipient-name     ship-address-1     ship-address-2     ship-address-3
ship-city     ship-state     ship-postal-code     ship-country
gift-wrap-type     gift-message-text     sales-channel     purchase-order-number

Regarding the sandbox/example output file for each report type, I will take your feedback to our internal teams.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
