### ISSUE TITLE
For Amazon SP-API how do you close and re-list a listing by API?

### ISSUE THREAD

**Issue by crazybee69** [amzn/selling-partner-api-models#2316]
In the sellercentral interface i can close listing and re-list closed listing.

![image](https://user-images.githubusercontent.com/32307323/157917192-ebb0c742-76d2-441b-835f-4bb7b4e1985c.png)

I didn’t find these methods in the SP-API. I tried to do this through ListingPutRequest, and loading POST_FLAT_FILE_INVLOADER_DATA feed, specifying “d” in the add-delete column. Unsuccessfully.

Please tell me if there is a way to Close and Re-list listing via the SP-API?

**Comment by daiqi77777** [comment]
no solution

**Comment by johnkw** [comment]
I documented a solution in bug #410.

My documentation should be added to the official Amazon documentation.
