### ISSUE TITLE
Reports API Endpoint - Cancelled Reports

### ISSUE THREAD

**Issue by benkingery** [amzn/selling-partner-api-models#2346]
I have been using MWS API for Reports successfully for years.  I am developing new engine internally to request/download/consume Reports Endpoint for SP-API.

All of the reports that I request are coming back "CANCELLED".  Can anyone help me know why these are all coming back as Cancelled?  Below is a list of report types that I am requesting.

GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA
GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING (I understand this one may be because I have not called it with RDT)
GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA
GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA

**Comment by johnkw** [comment]
This is a duplicate of bug #393 (which is still a critical bug and should be reopened instead of being moved to a discussion).
