### ISSUE TITLE
Invalid Access: You do not have permissions to view this page

### ISSUE THREAD

**Issue by tspicer** [amzn/selling-partner-api-models#2364]
We have users reporting that when attempting to authorize our app, they are getting "Invalid Access; You do not have permissions to view this page". Our customers are fairly sophisticated and this error is occurring across a number of the seller accounts they are managing.  There appears to be no documentation on the specific user permissions settings required in Seller Central "User Permissions". We attempted to document this ourselves, but the customer still gets this error.

Would appreciate any recommendations for user permissions, especially for reporting API and Order API access.

https://docs.openbridge.com/en/articles/5391780-amazon-selling-permissions

**Comment by zakm** [comment]
I used to have access to the "Develop Apps" page even without being an admin. I am no longer able to do so even with all admin permissions enabled. Why has this been changed? The primary account holder is not the manager of our applications and so it doesn't make sense to restrict access only to that account.
