### ISSUE TITLE
Invalid request on getListingOffers operation for SKUs containing special characters

### ISSUE THREAD

**Issue by umutyusuf** [amzn/selling-partner-api-models#237]
We are facing an issue with calling the `getListingOffers` operation with special characters. SKUs that remain the same after URL encoding works properly but the ones that change after the URL encode operation result in an invalid response. We are using generated Java SDK to perform the calls.

Here is the response
``` JSON
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "HE14-367\u0026@2\u0026$388 is an invalid SKU for marketplace ATVPDKIKX0DER",
      "details": ""
    }
  ]
}
```

Requested URL: `https://sellingpartnerapi-na.amazon.com/products/pricing/v0/listings/HE14-367%26%402%26%24388/offers?MarketplaceId=ATVPDKIKX0DER&ItemCondition=New`

**Comment by puppsupr** [comment]
Hi,

Our engineering has fixed the getListingsItem issue. Can you please check and let me know if the issue is resolved ?

Thanks and Regards,
Supriya Puppala,
Solutions Architect, Selling Partner API
