### ISSUE TITLE
JSON_LISTINGS_FEED - Some basic operations.

### ISSUE THREAD

**Issue by BashaBill** [amzn/selling-partner-api-models#2372]
Before I start: I have been here > https://developer.amazonservices.com/support. After logging in there is no 'Create a Question' button available, so I cannot create a question. Maybe its only available to Americans.

My question is relating to JSON_LISTINGS_FEED product feed type.

Basically, I am working from a starting point of having an Ean with a free stock value and a platform price.

What I need to be able to do is:

1. Create a new listing using the Ean, free stock value and platform price (if its not already listed)
2. Update the free stock value and price (using the Ean) if we already have the item listed.

As it stands we have implemented most of the sandbox test calls to Amazon SP-API and these are just fine.

We are now attempting to submit a feed (FeedType : JSON_LISTINGS_FEED) with only a couple of products but cannot find any documentation showing us what the structure of the JSON should be.

We are successfully creating the feed and submitting JSON via the returned URI and FeedId and are receiving responses like "Missing attributes".. which is not very helpful.

This is useful: => https://github.com/amz-tools/amazon-sp-api/issues/68
This is useful too: => https://github.com/amzn/selling-partner-api-models/issues/417

It seems like there are a lot of developers struggling with trying to work out how to use SP-API, due to the lack of documentation provided by Amazon.

Has anyone even found a the list of acceptable JSON attributes for this feed type?

Any help appreciated.

**Comment by ALPBRCH** [comment]
Hi,
there is an excellent converter tool here : 

Amazon has deprecated [most listings-related XML and flat-file feeds](https://developer-docs.amazon.com/sp-api/docs/sp-api-release-notes#feeds). They built an [Amazon feed converter](https://tools.highsidelabs.co/) tool for easily converting the deprecated feeds to the newer JSON_LISTINGS_FEED format with a few lines of code. Read the full documentation [here](https://docs.highsidelabs.co/feed-transformer).
