### ISSUE TITLE
[C#] Signature error if there is an equal (=) in nextToken

### ISSUE THREAD

**Issue by hosokawa1008** [amzn/selling-partner-api-models#241]
HI.
Let me apologize for my poor English.

I using the Amazon Seller Partner Api C# library to get catalog items.
Here is my code to get response on their api
```
        private static IRestResponse GetCatalogItems(string researchWords, string accessToken, string nextToken)
        {
            var LiveUrlBase = "https://sellingpartnerapi-na.amazon.com";

            // Create Get Orders API Request
            var restClient = new RestClient(LiveUrlBase);

            StringBuilder sbUrl = new StringBuilder("/catalog/2020-12-01/items?marketplaceIds=ATVPDKIKX0DER&includedData=summaries&pageSize=20");
            sbUrl.Append("&keywords=");
            sbUrl.Append(researchWords.Replace(" ", ","));
            if (nextToken != string.Empty)
            {
                string encodedNextToken = System.Web.HttpUtility.UrlEncode(nextToken);
                sbUrl.Append("&pageToken=");
                sbUrl.Append(encodedNextToken);
            }

            IRestRequest restRequest = new RestRequest(sbUrl.ToString(), Method.GET);
            restRequest.AddHeader("x-amz-access-token", accessToken);

            AWSAuthenticationCredentials awsAuthenticationCredentials = new AWSAuthenticationCredentials
            {
                AccessKeyId = “xxxxxxxxxxxxxx”,
                SecretKey = “xxxxxxxxxxxxxxxx”,
                Region = "us-east-1"
            };

            // AWS Signature
            restRequest = new AWSSigV4Signer(awsAuthenticationCredentials)
                .Sign(restRequest, restClient.BaseUrl.Host);

            restRequest.AddHeader("user-agent", "ResearchByKeyworkd (Language=csharp;Platform=Windows/10)");

            return restClient.Execute(restRequest);
        }

```

After getting the access token by LWAClient, I set the access token in the header x-amz-access-token and the first page of 20 was successfully retrieved.

`https://sellingpartnerapi-na.amazon.com/catalog/2020-12-01/items?marketplaceIds=ATVPDKIKX0DER&includedData=summaries&pageSize=20&keywords=harry,potter,books`

Using the nextToken contained in the response to the first page, I was also able to retrieve the 20 items on the second page.The request looks like this. nextToken is encoded in UTF-8. but no characters are encoded.

`https://sellingpartnerapi-na.amazon.com/catalog/2020-12-01/items?marketplaceIds=ATVPDKIKX0DER&includedData=summaries&pageSize=20&keywords=harry,potter,books&pageToken=9HkIVcuuPmX_bm51o3-igBfN45pxW4Ru7ElIM6GCECYCuXJKzT26f7ffhG_Vx3-R2y1lRhahGa5wt_JvE7qiRqrFC0wYyWwWyB6KE99dVcU5bdGiP2_hRq5oVWILV75HuxmK_rHmqDPMCMT4jkGCLx1l1vj7KQoFIa7pWiOPHyaYWP7sBE9Fg7cGN2wE0an5ePw96h6ZL7mnNKMrrdFg-GNanEVRjipq`

Using the nextToken contained in the response on page 2, I was also able to retrieve the 20 results on page 3.
However, when I tried to retrieve the 20 items on page 4 using the nextToken included in the response on page 3, the following error message was returned: 
`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`
The nextToken contains "=" at the end, which seems to cause an error at this time.

nextToken
9HkIVcuuPmX_bm51o3-igBfN45pxW4Ru7ElIM6GCECYCuXJKzT26f7ffhG_Vx3-RskXbLpkmeXxwt_JvE7qiRqrFC0wYyWwWyB6KE99dVcU5bdGiP2_hRq5oVWILV75HuxmK_rHmqDPMCMT4jkGCLx1l1vj7KQoFIa7pWiOPHyaYWP7sBE9Fg7cGN2wE0an5ePw96h6ZL7niJ7q1VFTczfp50DAC1n52f21sjEmsFr8=

utf-8 encoded nextToken
9HkIVcuuPmX_bm51o3-igBfN45pxW4Ru7ElIM6GCECYCuXJKzT26f7ffhG_Vx3-RskXbLpkmeXxwt_JvE7qiRqrFC0wYyWwWyB6KE99dVcU5bdGiP2_hRq5oVWILV75HuxmK_rHmqDPMCMT4jkGCLx1l1vj7KQoFIa7pWiOPHyaYWP7sBE9Fg7cGN2wE0an5ePw96h6ZL7niJ7q1VFTczfp50DAC1n52f21sjEmsFr8%3d

When I send the same request with postman, I receive page 4 correctly.
Am I making a mistake in my call? Or is this a bug?
Please advise. Thank you very much.

**Comment by corbin-munce** [comment]
Instead of encoding the string and building the URL yourself, try using the AddQueryParameter function with the unencoded toekn, eg: 

`
if (!string.IsNullOrEmpty(nextToken))
            {
                restRequest.AddQueryParameter("NextToken", $"{nextToken}");
            }
`

**Comment by hosokawa1008** [comment]
Thanks for the reply.
I took your advice and was able to get it to work correctly by adding pageToken as a parameter.
In postman, I needed to encode nextToken. So I added the encoding process in C#.

```
            IRestRequest restRequest = new RestRequest(sbUrl.ToString(), Method.GET);
            if (!string.IsNullOrEmpty(nextToken))  { restRequest.AddQueryParameter("pageToken", nextToken); }
            restRequest.AddHeader("x-amz-access-token", accessToken);

```
Thank you very much.
