### ISSUE TITLE
GET_V2_SELLER_PERFORMANCE_REPORT - still stuck on "IN PROGRESS"

### ISSUE THREAD

**Issue by therubioftw** [amzn/selling-partner-api-models#2415]
Currently we are automating the requests for 3 reports for a few hundred customers, daily.
As of this morning, 2 of them are working, but `GET_V2_SELLER_PERFORMANCE_REPORT` is stuck on `IN PROGRESS` on all of them.

Anyone else seeing this? I realize there was a full-on outage over the past few days - could it be related to that?
Perhaps there's just a long queue of requests Amazon is currently working through?

**Comment by J-W-Chan** [comment]
+1
