### ISSUE TITLE
Invalid dimensions type in new 2022-04-01 catalog-items-api

### ISSUE THREAD

**Issue by tusbar** [amzn/selling-partner-api-models#242]
Hey,

The `Item` return type of `getCatalogItem` is broken in the new models of the 2022-04-01 catalog-items-api: `dimensions` should be an array of `ItemDimensionsByMarketplace` but is defined as just an `ItemDimensionsByMarketplace`.

```json
    "dimensions": {
      "$ref": "#/definitions/ItemDimensionsByMarketplace"
     },
```

There should be an intermediate type, just like for the other properties of `Item` that does something like this:

```json
  "ItemDimensionsArray": {
    "description": "Dimensions associated with the item in the Amazon catalog for the indicated Amazon marketplace",
    "items": {
      "$ref": "#/definitions/ItemDimensionsByMarketplace"
    },
    "type": "array"
  },
```

**Comment by vikingcodes** [comment]
@tusbar In doc its array

![image](https://user-images.githubusercontent.com/976073/169566809-ce781538-ecb5-4eb0-81a7-78368f336676.png)

**Comment by tusbar** [comment]
Fixed in https://github.com/amzn/selling-partner-api-models/commit/1001e73a7d29092e1050f4591cd0e0912e640211
