### ISSUE TITLE
Update POM Lombok Module to org.projectlombok:lombok:1.18.22 for Oracle Javac 17 support

### ISSUE THREAD

**Issue by PureIllusionCo** [amzn/selling-partner-api-models#244]
https://github.com/amzn/selling-partner-api-models/blob/36faf699bedc73d9fe82a4871d00945e2fe944d0/clients/sellingpartner-api-aa-java/pom.xml#L56

Open issue #181 was closed by bot.

**Comment by dahuangqiao** [comment]
Hi,

the api work very well but i have one question !When i use the listing-item-Api  get the sku informations under seller , i requested the "description" value  in "attributes" always null .

I already use the listing-item-Api to request the "attributes", "procurement", "issues" but the "description" value in "attributes" always remain null.

So how can i get the product description by listing-item-Api

Maybe ther is a simple solution. Someone have an idea?
![1654780505375](https://user-images.githubusercontent.com/24861963/172855889-1548f24e-0ce4-4547-ac4a-7de5fa9876c7.png)

**Comment by franciscocha** [comment]
@CVEngineer0523 you may want to open a new issue. As what you described doesn't relate to the current issue.
