### ISSUE TITLE
Confirm Order & Update Tracking info

### ISSUE THREAD

**Issue by Kernel1453** [amzn/selling-partner-api-models#245]
Hi All,

We are getting all orders with Orders API. We see an order is pending. Then Approved. Now we want to Confirm or Cancel Order and then update shipment status and Carrier & TrackingID for fbm orders. Which api can help us? we are trying Feed API, Order UpdateShipmentStatus but we could not overcome this.
For any example we'll appreciated.

Thanks.

**Comment by franciscocha** [comment]
Can you provide the error that you are running into when trying to do it via the Feeds API? Or if it isn't an error can you provide more details on the issues you are running into?

**Comment by adrian-amz** [comment]
Hello @Kernel1453,

Thank you for reaching out regarding {issue reported}.

You can find details regarding this in our [Merchant Fulfillment API](https://developer-docs.amazon.com/sp-api/docs/merchant-fulfillment-api-v0-reference).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian C.
Selling Partner API Developer Support
