### ISSUE TITLE
How does the Java SDK set the restrictedDataToken parameter?

### ISSUE THREAD

**Issue by liunancun** [amzn/selling-partner-api-models#248]
How does the Java SDK set the restrictedDataToken parameter?

**Comment by franciscocha** [comment]
Do you have a specific endpoint you are trying to call? 

Bullet point 13 has a few examples.
https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#tutorial-generate-a-java-sdk-for-the-tokens-api

**Comment by liunancun** [comment]
@franciscocha You may have misunderstood what I mean. I have got the RDT now, but I need to pass this RDT when calling the com.amazon.spapi.api.OrdersV0Api#getOrders interface. Is there any way for the SDK to pass the RDT?

**Comment by liunancun** [comment]
https://github.com/amzn/selling-partner-api-models/blob/main/clients/sample-code/RestrictedDataTokenWorkflow.java
In this example, it is called directly through OkHttpClient, so there is no SDK concise

**Comment by mjp91** [comment]
@liunancun I had the same issue, ended up creating an anonymous class and overriding the `sign` method of the `LWAAuthorizationSigner` to replace the x-amz-access-token with an RDT:

```java    
ordersV0ApiClient.getApiClient().setLWAAuthorizationSigner(new LWAAuthorizationSigner(getLwaAuthorizationCredentials(refreshToken)) {
      @Override
      public Request sign(Request originalRequest) {
        return originalRequest.newBuilder().addHeader("x-amz-access-token", restrictedDataToken.getRestrictedDataToken()).build();
      }
    });
```

**Comment by liunancun** [comment]
@mjp91 This is a way, it's just not elegant, I still hope to get official support, such as one-hour cache and so on

**Comment by liunancun** [comment]
@franciscocha This example uses relatively low-level code to send messages. Based on OkHttpClient, many parameters must be encapsulated by themselves, not based on the SDK.

**Comment by franciscocha** [comment]
@liunancun The example was provide by Amazon for the use of the available SDK code that they themselves provided.

**Comment by smargoli2** [comment]
I submitted a PR to update the mustache templates so that the code will be generated correctly and check for additional headers.
https://github.com/amzn/selling-partner-api-models/pull/288/files
