### ISSUE TITLE
[BUG] [SP-API] [Issue] PUT listings does not create a parent item

### ISSUE THREAD

**Issue by frankbarry** [amzn/selling-partner-api-models#2489]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
/listings/2021-08-01/items/{sellerId}/{sellerSku}

## Expected Behavior

Attempts to create a parent ASIN by setting `attributes.parentage_level` to "parent". The request is accepted (returns no errors or warnings). Expectation: a parent listing is created in Amazon's catalog.

## Current Behavior

No parent ASIN is created. 

## Context/Screenshots

In order to create a listing page with multiple variants (e.g. different sizes) there must be a parent ASIN to which all the variants relate to as children using the `child_parent_sku_relationship.parent_sku` attribute.

Since a parent ASIN fails to be created, all the variants are listed in the catalog as separate listing pages. This is a bad user experience, as they will see multiple listings in search results that look like duplicates, and differ only by size.

## Your Environment

I included a sample response by the SP-API to a recent request at creating a parent ASIN:

```
{
    "sku":"parent-let-ehop",
    "status":"ACCEPTED",
    "submissionId":"562d5c69e1754139b96667d449066f4b",
    "issues":[]
}
```

**Comment by HubertBokszczanin** [comment]
> I'm happy to say this issue is now resolved, after the schema was fixed a few months ago. Parent skus are created as expected, and product variants are working again.

@frankbarry Hi, could You show example of this parent sku creation request please?
