### ISSUE TITLE
There is a missing event code in fulfillmentOutbound_2020-07-01.json.

### ISSUE THREAD

**Issue by Tetsuya-Takiguchi** [amzn/selling-partner-api-models#249]
Hello, I am a web application developer using SP-API.

I used this model to get the return value with `getPackageTrackingDetails` of `GET /fba/outbound/2020-07-01/tracking`.
Upon reviewing the results retrieved, I noticed that there was an event code that was not set in `selling-partner-api-models/fulfillmentOutbound_2020-07-01.json`.

I found that the event codes are `EVENT_438 `, `EVENT_444` and I checked with amazon support and received the following response.

```
EVENT_438 : Customer has requested delivery appointment to be rescheduled. Delivery may be delayed due to the customer request.
EVENT_444 : Customer has requested the package to be forwarded to a different address. The request will be processed shortly.
```

Could you please update the event codes set in `selling-partner-api-models/fulfillmentOutbound_2020-07-01.json` to the latest?

**Comment by owsiakl** [comment]
We're also missing event code: `EVENT_320`.
can you help us with that? It's [this enum](https://github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-outbound-api-model/fulfillmentOutbound_2020-07-01.json#L5471).
Thanks.

**Comment by adrian-amz** [comment]
Hello @Tetsuya-Takiguchi ,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian C
Selling Partner API Developer Support
