### ISSUE TITLE
how to get SKU number for a product using ASIN ? 

### ISSUE THREAD

**Issue by arcmax1998** [amzn/selling-partner-api-models#2507]
SP o i am working with the Amazon seller api. I have my catalog and pricing api working. I am able to retrieve the details using the ASIN values. What i need is the inventory for those products. The inventory feed required SKU number. I cant seem to find the SKU number in any of the feeds. And the inventory feed seems to only work with sku, i have tried other identifiers available in the summery but none of them work.

any help would be appreciated.

thanks

**Comment by Xkta** [comment]
> > Is there a planned update for the CatalogItems to return the seller SKUs when querying by ASIN and providing the SellerId as well? Edit: Some marketplaces like France may not always provide asin1, so this is not a suitable method: [#580 (comment)](https://github.com/amzn/selling-partner-api-models/issues/1199)
> 
> Not as part of the Catalog Items API. In a future release of the Listings Items API, a search operation will be added that allows for querying listings (SKUs) for a given list of ASINs (or other product identifiers).

Could you please let me know if the search operation that allows for querying listings (SKUs) for a given list of ASINs (or other product identifiers) has been released? This feature is crucial for our operations, and any details about its availability would be greatly appreciated.

**Comment by chapmanjw** [comment]
@Xkta It has not been released yet, our teams are working on getting it read. Stay tuned for launch announcements: https://developer-docs.amazon.com/sp-api/changelog.

**Comment by Xkta** [comment]
Hi,
Thank you for your prompt reply and for all the effort you’ve put in over
time, even though there hasn't been substantial progress on the issue.
Best regards

John Chapman ***@***.***) ***@***.***> 于2024年8月7日周三 02:47写道：
