### ISSUE TITLE
May you make your SDK available as a Maven repository?

### ISSUE THREAD

**Issue by MarErm27** [amzn/selling-partner-api-models#252]
May you make your SDK available as a Maven repository? How to deploy an application containing your SDK on our servers without doing all those manual steps with swagger described here on each node?
https://developer-docs.amazon.com/sp-api/docs/generating-a-java-sdk-with-lwa-token-exchange-and-authentication

**Comment by arielcostas** [comment]
Any updates on this? Generating the library manually is a huge PITA, and having to do this on every computer where I want to run my application is really dumb when a simple maven package could be provided by Amazon.

**Comment by bug3048** [comment]
Why doesn't Amazon provide an easy-to-use SDK to connect to the SP API? I really can't imagine

**Comment by rodrifed** [comment]
Hi,

We are happy to announce that the SP-API Java SDK is now available in Maven: https://central.sonatype.com/artifact/software.amazon.spapi/spapi-sdk

You can find more details in the source repository: https://github.com/amzn/selling-partner-api-sdk/tree/main/java

Thank you,
Federico Rodriguez
Selling Partner Developer Services
