### ISSUE TITLE
New Ledger Reports GET_LEDGER_DETAIL_VIEW_DATA & GET_LEDGER_SUMMARY_VIEW_DATA - Adjustment Documentation

### ISSUE THREAD

**Issue by nrogers805** [amzn/selling-partner-api-models#2525]
I'm looking for documentation for the reason code given for Adjustments in the new Inventory Ledger reports.

I have information for these codes for the original adjustment report but the new ledger report has introduced new codes, example new code is "G"

**Comment by johnkw** [comment]
This is still broken. Please reopen these tickets that are not fixed.  Please do not close issues until they're actually fixed. It's extremely counterproductive and confusing.  It becomes harder to find the discussion on these critical issues that are still open.  And it becomes harder to keep track of which things have been previously reported as bugs.

https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba still has nothing on this issue.
