### ISSUE TITLE
Selling Partner API Authentication/Authorization Library in python or PHP?

### ISSUE THREAD

**Issue by franclin** [amzn/selling-partner-api-models#253]
Any chance we can get the Selling Partner API Authentication/Authorization Library in other languages such as Python or PHP?

**Comment by adrian-amz** [comment]
Hello @franclin,

Thank you for reaching out regarding API Authentication/Authorization Library in python or PHP.

We, currently, don't have API Authentication/Authorization Library in Python or PHP, but we have available in Java and C#.

You can find details regarding this in our [C# SDK with LWA token exchange and authentication](https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp).
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian C
Selling Partner API Developer Support

**Comment by franclin** [comment]
Hello @adrian-amz 

 In that case, is there a way to write those functions (signing HTTP requests for Amazon Selling Partner APIs) from scratch for people who don't use Java or C#?

Thanks,
 Franclin
