### ISSUE TITLE
Inventory Update via Upload/Feeds Resets Handling Time

### ISSUE THREAD

**Issue by nicolasheady** [amzn/selling-partner-api-models#2530]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
FEEDS API - POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA

The docs that seem to cover this are here: https://sellercentral.amazon.com/help/hub/reference/201576480
The page does not mention "handling-time", but it IS mentioned in the template you can download from that page. The template instructions, paragraph 3 in "How to use the file" says:
"If you do not provide a value for an attribute in the template, Amazon will retain the existing value that is already in your catalog."

When using the feed type "POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA" to submit a feed via SP-API, I'm submitting it with only the "sku" and "quantity" attributes. After the feed processes successfully, I can see the quantity updated correctly, but the handling time for the products was reset even though I did not provide a value.

I'm submitting my feeds using NodeJS.

**Comment by dvuljakMTS** [comment]
Is anyone from Amazon working on this issue? Problem is still there.

**Comment by Gurjap** [comment]
I am facing the same issue.

Inventory updates to amazon from increff (they use inventory update api) resets handling time.

is it possible to open this issue?
