### ISSUE TITLE
"salesRanks" does not return the BSR of the root category

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#2533]
Dear Amazon,

Currently then "salesRanks" node only does not return the root BSR, it only returns children salesrank

https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#getcatalogitem

For example, the ASIN **B07G39GXL5**. This is what we see on Amazon product page:
Best Sellers Rank: amzn/selling-partner-api-docs#25,790 in Beauty & Personal Care (See Top 100 in Beauty & Personal Care)
amzn/selling-partner-api-models#1242 in Nail Polish
amzn/selling-partner-api-models#1403 in Climate Pledge Friendly: Beauty
 
This is what returned by the API:
`"salesRanks": [
                {
                    "marketplaceId": "ATVPDKIKX0DER",
                    "classificationRanks": [
                        {
                            "classificationId": "11059321",
                            "title": "Nail Polish",
                            "link": "https://www.amazon.com/gp/bestsellers/beauty/11059321",
                            "rank": 626
                        },
                        {
                            "classificationId": "21377129011",
                            "title": "Climate Pledge Friendly: Beauty",
                            "link": "https://www.amazon.com/gp/bestsellers/climate-pledge/21377129011",
                            "rank": 803
                        }
                    ],
                    "displayGroupRanks": [
                        {
                            "websiteDisplayGroup": "climate_product_display_on_website",
                            "title": "Climate Pledge Friendly",
                            "link": "https://www.amazon.com/gp/bestsellers/climate-pledge",
                            "rank": 4346
                        }
                    ]
                }
            ],`

So is there a way we can get the BSR of the root. In this case, I would like to get 25,790 in Beauty & Personal Care

Thank you

**Comment by Vituli** [comment]
any updated?
