### ISSUE TITLE
Optionally return 'offers' with searchCatalogItems operation

### ISSUE THREAD

**Issue by JTimings** [amzn/selling-partner-api-models#256]
Now that we can get 100 products / second from Catalog Items API, this feels like the defacto endpoint for product data. Would be good if this endpoint also returned 'offers', otherwise we need to go through the Listings Items API at only 5 products / second.

**Comment by chapmanjw** [comment]
@JTimings, 

We do not have any plans at this time to combine the data from the Catalog and Listings APIs together in a single API response. However, we are working on a `searchListingsItems` operation for the Listings Items API that will enable listing, search, filtering, and paginating through listings for a selling partner. This will include the ability to retrieve multiple listings in a single request in the same fashion as the `searchCatalogItems` operation on the Catalog Items API.

Stay tuned for future launch announcements.

Thanks.
