### ISSUE TITLE
[BUG] [SP-API] [Issue] getMyFeesEstimates() returnsThere is an client-side error. Please verify your inputs

### ISSUE THREAD

**Issue by somin-developer** [amzn/selling-partner-api-models#2561]
## I'm submitting a...

<pre>Issue regarding fees related sp api.Please let me know if this is required to assign 
any permission from Amazon Developer Central </pre>

## SP-API Name and Version or Report/Feed Type
Product Fees API v0
getMyFeesEstimateForASIN

## Expected Behavior
Should return fees value

## Current Behavior
Working good for marketplace UK but giving error for other marketplaces(DE,FR,IT,ES).

## Context/Screenshots

THIS IS THE RESPONSE OF LISTING API.
![image](https://user-images.githubusercontent.com/127078588/230554294-656e1771-7b11-4513-87b2-acb20adfcabd.png)

**Comment by cmlkx** [comment]
We are observing similar behavior, and it is getting worse over time.
