### ISSUE TITLE
Outbound Fulfillment API model enums are missing some values

### ISSUE THREAD

**Issue by owsiakl** [amzn/selling-partner-api-models#257]
Hey guys,
there are some enum values in this API that aren't documented anywhere. So far we detected missing values for:

- [CurrentStatus](https://github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-outbound-api-model/fulfillmentOutbound_2020-07-01.json#L4933)
  - `UNDISPLAYED`
  
- [AdditionalLocationInfo](https://github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-outbound-api-model/fulfillmentOutbound_2020-07-01.json#L5031)
  - `FRONT_DOOR/PORCH`
  - `FRONT DOOR/PORCH`
  - `INDIVIDUAL PICKED UP AT PO`
  - `Office`
  - `Inside Delivery`
  - `IN/AT MAILBOX`
  - `TO ORIGINAL SENDER`
  
Can you help us with that? It breaks when validating data against schema provided in this repo.
Also, do anyone noticed more values like that in those enums?

There is also open issue for missing values in `EventCode` enum - https://github.com/amzn/selling-partner-api-models/issues/249 - it's the same API.

Thanks!

**Comment by adrian-amz** [comment]
Hello @owsiakl ,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian C
Selling Partner API Developer Support
