### ISSUE TITLE
GET to /fba/inbound/v0/shipmentItems - Invalid Input [BUG] [SP-API]

### ISSUE THREAD

**Issue by GonzaloGDV** [amzn/selling-partner-api-models#2582]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

It should return a list of items in a specified inbound shipment, or a list of items that were updated within a specified time frame.

## Current Behavior

It returns an error message.  "code": "InvalidInput", "message": "Either the ShipmentId or a pair of LastUpdatedAfter and LastUpdatedBefore must be passed in input", "details": "".

## Your Environment

I am working in Postman and amazon-sp-api NPM package. Both return the same error message.
My URL: https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipmentItems?ShipmentId=FBA16QYHFC4N&LastUpdatedAfter=2022-04-30T03:58:30Z&LastUpdatedBefore=2022-05-15T03:58:30Z

**Comment by smargoli2** [comment]
Still an issue
