### ISSUE TITLE
listings-items-api-model/listingsItems_2021-08-01 live API is returning the property 'currency' and not 'currencyCode' in offers

### ISSUE THREAD

**Issue by sellistix** [amzn/selling-partner-api-models#259]
https://github.com/amzn/selling-partner-api-models/blob/7127fcf2a1b340e10b0faaaa7ed5c92efb1a26fb/models/listings-items-api-model/listingsItems_2021-08-01.json#L1375

https://github.com/amzn/selling-partner-api-models/blob/7127fcf2a1b340e10b0faaaa7ed5c92efb1a26fb/models/listings-items-api-model/listingsItems_2021-08-01.json#L1375

This means generated apis are going to fail since they will be looking for 'currencyCode' for the Offer price. In other apis it is currencyCode so the model appears correct/consistent.

Link to docs for this specific property:

[Offer Price](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#money)

Example response snippet from API:
`"offers": [
    {
      "marketplaceId": "ATVPDKIKX0DER",
      "offerType": "B2C",
      "price": {
        "currency": "USD",
        "amount": "34.33"
      }
    }
  ]`

**Comment by chapmanjw** [comment]
Thanks @sellistix for reporting this. I have created an item in my team backlog to address this.

**Comment by chapmanjw** [comment]
@sellistix We have a fix going out to address this. It should be out in the next day or two. 

Since there may be clients that have coded around the incorrect responses, the update is returning both `currency` and `currencyCode`. 

Thanks.

**Comment by chapmanjw** [comment]
This has been deployed to prod. 

Thanks.
