### ISSUE TITLE
'400 bad request' without error message in all of my calls to SP-API

### ISSUE THREAD

**Issue by yablichdada** [amzn/selling-partner-api-models#2590]
Good afternoon, all.
I have a problem when trying to receive orders using SP-API. I get the authorization token correctly. After I make a request using the GET method:
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?MarketplaceIds=A13V1IB3VIYZZH,...,2CA1F83G8C2ARO7P&createdAfter=2023-04-25

And the headers:
"x-amz-content-sha256": "e3b0c......c1c149afbf4c8996fb92427ae......9b934ca495991b7852b855"
"Accept": "*/*"
"Accept-Encoding": "gzip"
"host": "sellingpartnerapi-eu.amazon.com"
"x-amz-access-token": "Atza|I*redacted*"
"Authorization": "AWS4-HMAC-SHA256 Credential=AKIA56........V3QN6E/20230525/eu-west-1/execute-api/aws4_request, SignedHeaders=host;x-amz-access-token;x-amz-content-sha256;x-amz-date, Signature=9f809769c....................f8bae920fef59f6ed9bddff0c4cba30482a"
"x-amz-date": "20230525T152824Z"
"Connection": "keep-alive"
"user-agent": "1CDrive/1.0(Language=1C/8.3;Platform=Windows/10)"

The answer I get:
StatusCode 400
The body of the answer is a string of the form: 

> <!DOCTYPE html><html><head><title>x</title></head><body></body></html>

Who can tell me what the problem is and how to solve it?
Thanks

**Comment by yatanasov** [comment]
> <title>Website Temporarily Unavailable</title>
@tobidon have you found out what the issue was? :) Thanks!

**Comment by Prashantkr3001** [comment]
I have also face the same issue any idea?
