### ISSUE TITLE
Brand Analytics Report always Fatal

### ISSUE THREAD

**Issue by Polaroid-Sang** [amzn/selling-partner-api-models#261]
Hi All,

Can someone help me with the brand analytics report? I am newbiee, i just use python to call the api. However, the process always Fatal and it is not return any error information.

from datetime import datetime, timedelta
from sp_api.api import Reports
from sp_api.base.reportTypes import ReportType
from sp_api.api import ReportsV2
reports_client = ReportsV2(credentials=credentials)
res = reports_client.create_report(
    reportType=ReportType.GET_VENDOR_TRAFFIC_REPORT,
    dataStartTime=("2022-07-04"),
    dataEndTime=("2022-07-07"),
    reportPeriod="Week",
    marketplaceIds=["ATVPDKIKX0DER"])

Thanks a lots.

![Screenshot 2022-07-21 at 14 39 17](https://user-images.githubusercontent.com/109582094/180215791-5231ad05-b41e-470a-aed9-97bad6c2f2a2.png)

**Comment by Adrian-T-AMZN** [comment]
Hello @Polaroid-Sang,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
