### ISSUE TITLE
[EXPLANATION NEEDED] CatalogItems keywords search

### ISSUE THREAD

**Issue by MaksymV1999** [amzn/selling-partner-api-models#2619]
Good day!

In documentation it is said :

> A comma-delimited list of keywords to search the Amazon catalog for. Note: Cannot be used with identifiers.

But there was nothing about the logic of searching by keywords.

Could you kindly explain the logic behind keywords? 
Is it type of: `keyword || keywords || keywords`  search
or: `keywords && keywords && keywords`  search?

Or  it works even differently?

Many thanks in advance!

**Comment by sharjeel-mukhtar-qbatch** [comment]
Hi @rodrifed 

Thank you for your response, i have another query here. Can you please guide me.
How we can send 10 products titles in keyword at a single time to get the 10 products matching listings over amazon using catalog items sp api.

Many thanks in advance!

**Comment by rodrifed** [comment]
Hi @sharjeel-mukhtar-qbatch,

The [/searchCatalogItems operation](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#paths) from the Catalog Items API will return items matching **all** keywords. That means that if you specify 10 different product titles, the result will most likely be an empty list.

While it is possible to do a bulk search, this functionality is limited to search by identifiers (ASIN/EAN/GTIN/etc.).
To do it you have to use `identifiersType` and `identifiers` attributes. Please find an example below:
```
https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?identifiersType=ASIN&identifiers=B09JBG5JV3, 0307887898&marketplaceIds=ATVPDKIKX0DER&includedData=identifiers,summaries,attributes&locale=en_US
```

I hope the information above helps clarify your question.

Thank you,
Federico
Selling Partner Developer Services
