### ISSUE TITLE
Old LWA access token expiry date

### ISSUE THREAD

**Issue by lowzijian** [amzn/selling-partner-api-models#263]
I found the old LWA access token is usable around 45 minutes after you made the secure HTTP POST to the LWA authorization server (https://api.amazon.com/auth/o2/token) with correct parameters. May I know the exact expiry duration of the old LWA token ?

**Comment by Adrian-T-AMZN** [comment]
Hello @lowzijian,

Thank you for reaching out regarding the exact expiry duration of the LWA access token.

An LWA access token expires one hour after it is issued.

You can find details regarding this in our documentation link: https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api#step-1-request-a-login-with-amazon-access-token

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Adrian T.
Selling Partner API Developer Support
