### ISSUE TITLE
JSON_LISTINGS_FEED or POST_INVENTORY_AVAILABILITY_DATA

### ISSUE THREAD

**Issue by liamseys** [amzn/selling-partner-api-models#2657]
Hello,

We have a significant inventory on Amazon and want to efficiently update our listings, including **price**, **stock**, and **delivery times**. After reviewing the Selling Partner API documentation, we found two options for this task: creating a JSON feed with messages or submitting a ```POST_INVENTORY_AVAILABILITY_DATA``` inventory file. We need to update approximately **5 million** offers across multiple marketplaces. Can you please advise on the best method to achieve this?

**Comment by omarbossoni** [comment]
Hello Leonardo,
I'm having some trouble figuring out how to send large quantities of offers to inventory with the new APIs.
POST_INVENTORY_AVAILABILITY_DATA is deprecated and will be retired on March 31, 2025.
To update the offers I used that API but now I haven't understood how to switch to JSON_LISTINGS_FEED.
Is there perhaps another way to send a CSV, a TSV or an excel file via API and not via seller central?

BR
Omar

**Comment by leonardonakagawa** [comment]
Thanks for opening another issue of that manner @omarbossoni, will follow up there. https://github.com/amzn/selling-partner-api-models/issues/4588

**Comment by cmlkx** [comment]
Yea, the processing time on JSON_LISTINGS_FEED is extremely slow and disappointing.
