### ISSUE TITLE
[HELP] Retriving all my merchant shipping groups from API.

### ISSUE THREAD

**Issue by silasfrigo** [amzn/selling-partner-api-models#2661]
Hello. Is there a way for me to retrieve all my merchang_shippign_groups from the SP API? 
I tried passing seller_id in the product definitions API as the docs said, but it was not successfull. 
```
By providing the sellerId parameter with the Product Type Definitions API, you can retrieve the available shipping templates configured by the seller as an enumeration on the merchant_shipping_group attribute value.
```  https://developer-docs.amazon.com/sp-api/docs/migrating-listings-management-workflows#migrating-shipping-override-feeds-workflows

Thanks!

**Comment by Barakros** [comment]
hi
related to this 
what can be a valid value for merchant_shipping_group
and if the below is a valid?
thx

{
  "header": {
    "sellerId": "xxx",
    "version": "2.0",
    "issueLocale": "en_US"
  },
  "messages": [
    {
      "messageId": 1,
      "sku": "aaabbbccc",
      "operationType": "PATCH",
      "productType": "PRODUCT",
      "patches": [
        {
          "op": "replace",
          "path": "/attributes/merchant_shipping_group",
          "value": [
            {
              "marketplace_id": "ATVPDKIKX0DER",
              "value": [
                "Prime Template"
              ]
            }
          ]
        }
      ]
    }
  ]
}

**Comment by leonardonakagawa** [comment]
Hi @Barakros,

Each selling partner has their own valid values for merchant_shipping_group. This [tutorial](https://developer-docs.amazon.com/sp-api/docs/tutorial-retrieve-merchant-shipping-templates) explains how to retrieve it for a certain selling partner.


Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by Barakros** [comment]
hi
thx
I figured that out 2 days ago...
it also shows as part of the url when you hover over the template name on
the seller central

**Comment by whitedevils** [comment]
Hi, i follow this tutorial https://developer-docs.amazon.com/sp-api/docs/tutorial-retrieve-merchant-shipping-templates but in my schema the merchant_shipping_group item property does not contain enum values! What is wrong??
