### ISSUE TITLE
GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE gets cancelled everytime 

### ISSUE THREAD

**Issue by fermions75** [amzn/selling-partner-api-models#2668]
I am requesting GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE report and it gets cancelled everytime. I have tried it with many `dataStartTime` and `dataEndTime`, but no result. 

here is my request format - 
`{
    "reportType": "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
    "dataStartTime": "2023-03-01",
    "dataEndTime" : "2023-03-30",
    "marketplaceIds": [
        "ATVPDKIKX0DER"
    ]
}`

The response is - 
`{
    "reportType": "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE",
    "processingEndTime": "2023-07-30T18:25:38+00:00",
    "processingStatus": "CANCELLED",
    "marketplaceIds": [
        "ATVPDKIKX0DER"
    ],
    "reportId": "189396019568",
    "dataEndTime": "2023-03-30T00:00:00+00:00",
    "createdTime": "2023-07-30T18:25:24+00:00",
    "processingStartTime": "2023-07-30T18:25:31+00:00",
    "dataStartTime": "2023-03-01T00:00:00+00:00"
}`

**Comment by johnkw** [comment]
This is a duplicate of bug #393 (which is still a critical bug and should be reopened instead of being moved to a discussion).
