### ISSUE TITLE
[BUG] [SP-API] [Some values not getting  returned in the response]

### ISSUE THREAD

**Issue by raghavkunkee** [amzn/selling-partner-api-models#2677]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP-API Catalog Items API v2022-04-01   

## Expected Behavior

The attribute values product_description , bullet_list should be presemt in the response of the search.

## Current Behavior

The attribute values product_description , bullet_list are missing in many ISBN's when searching. 
However the same is available on the site.
e.g : ISBN : 0007112491 

## Your Environment

Ubuntu

**Comment by Azay961** [comment]
This issue is still not resolved.

**Comment by raghavkunkee** [comment]
Yes the issue is still open

**Comment by Azay961** [comment]
to overcome this issue i am using below code

def fetch_product_details(access_token, sku_asin, marketplace_id, search_type="sku"):
    if search_type == "sku":
        url = f"{ENDPOINT}/catalog/v0/items?MarketplaceId={marketplace_id}&SellerSKU={urllib.parse.quote(sku_asin)}" #neeeded sku for query
    elif search_type == "asin":
        url = f"{ENDPOINT}/catalog/2020-12-01/items/{sku_asin}?marketplaceIds={marketplace_id}&includedData=attributes"
        
        
  as i do have the lists of skus but not asins
  
  Versions:
  v0 --> not giving bullet points and product description
  2020-12-01/2022-04-01 ---> details are not fetched using skus
  
  so i have to use the above two different urls to handle my case.
