### ISSUE TITLE
[BUG] [SP-API] Invalid Date-Time field(s) error if lastUpdatedAfter in getOrders is in iso8601 format (Japan time)

### ISSUE THREAD

**Issue by asagawa0519** [amzn/selling-partner-api-models#2687]
https://sellingpartnerapi-fe.amazon.com/orders/v0/orders?LastUpdatedAfter=2023-08-18T00:00:00+09:00&OrderStatuses=Unshipped,PartiallyShipped&MarketplaceIds=1VC38T7YXB528&FulfillmentChannels=MFNwould result in the following error.

> JSON.parse(response.body)
=> errors"=>[{"code"=>"InvalidInput", "message"=>"This is invalid input", "details"=>"Invalid date/time field [lastUpdatedAfter]"}]}]
+09:00 is removed and the response is returned normally. Why is this?

If it succeeds

https://sellingpartnerapi-fe.amazon.com/orders/v0/orders?LastUpdatedAfter=2023-08-18T00:00:00&OrderStatuses=Unshipped,. PartiallyShipped&MarketplaceIds=A1VC38T7YXB528&FulfillmentChannels=MFN

**Comment by worksasintended** [comment]
> I'm not sure about this issue, but I noticed another related
> 
> I'm getting error from amazon if I try null for all four lastuupdate & create dates, saying lastupdate values are required, they are marked optional in code

It actually says in code:
` **Note**: Either the &#x60;CreatedAfter&#x60; parameter or the &#x60;LastUpdatedAfter&#x60; parameter is required.`
I think, this is only true if `nextToken` is not set, though.
