### ISSUE TITLE
Incomplete enum list for FulfillmentInbound ShipmentStatus in fulfillmentInboundV0.json

### ISSUE THREAD

**Issue by jasonhebert** [amzn/selling-partner-api-models#270]
Please update the [fulfillmentInboundV0.json](models/fulfillment-inbound-api-model/fulfillmentInboundV0.json) model file to include undocumented `ShipmentStatus` value `READY_TO_SHIP`.

In the fulfilment-inbound-api-v0-model file it lists the following accepted values for the `ShipmentStatus` enum:
```
[
        "WORKING",
        "SHIPPED",
        "RECEIVING",
        "CANCELLED",
        "DELETED",
        "CLOSED",
        "ERROR",
        "IN_TRANSIT",
        "DELIVERED",
        "CHECKED_IN"
]
```

An additional value of `READY_TO_SHIP` is also returned from the API as shown here:
``` json
{
    "payload":
    {
        "ShipmentData":
        [
            {
                "ShipmentId": "FBA********C",
                "ShipmentName": "FBA **********",
                "ShipFromAddress":
                {
                    "Name": "Tian******",
                    "AddressLine1": "******",
                    "DistrictOrCounty": "Na******",
                    "City": "Hu******",
                    "StateOrProvinceCode": "T******",
                    "CountryCode": "**",
                    "PostalCode": "*****"
                },
                "DestinationFulfillmentCenterId": "ONT8",
                "ShipmentStatus": "READY_TO_SHIP",
                "LabelPrepType": "SELLER_LABEL",
                "BoxContentsSource": "INTERACTIVE"
            }
        ]
    }
}
```

**Comment by Proladge** [comment]
@jasonhebert ,  could the issue be closed?

**Comment by jasonhebert** [comment]
I received email response on another ticket in a different ticketing system for Amazon that the READY_TO_SHIP status should not be returned from the API. Nothing since then so I am not sure if the issue has been resolved or not. No official word from any Amazon devs on this issue.

**Comment by clayton-k** [comment]
Hello @jasonhebert, I think the READY_TO_SHIP status has not been added to the model document:
https://github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-inbound-api-model/fulfillmentInboundV0.json#L6168

**Comment by jasonhebert** [comment]
They added it to the `getShipments` operation as an input value for the `ShipmentStatusList` parameter but I now see that they have NOT added it to the actual enum that is returned from the operation. Dealing with them on this has been a total nightmare and no-one knows what is going on. It seems there are multiple teams working on this and they have no clue what each is doing. I've received multiple different responses from multiple people over 4 tickets I've filed, nothing has actually been done except this change, and it is incorrect as well it seems.

Would someone else like to take this on? I'm tired boss, so tired.
