### ISSUE TITLE
[BUG] [SP-API] [Notification] Failed to subscribe to some type

### ISSUE THREAD

**Issue by delbertheihei** [amzn/selling-partner-api-models#2709]
### Question
When I create or get a subscription, the type of the subscription is [ITEM_INVENTORY_EVENT_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#item_inventory_event_change), [ITEM_SALES_EVENT_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#item_sales_event_change), but the return message: `"code": "Unauthorized", "message": "Access to requested resource is denied."`. 

But it's ok when I subscribe to other types, I don't see in the user guide documentation that this type requires a specific token, and I get all authorisation when I authorise the app.

I searched the previous Issue and found that someone else had the same problem, but didn't get a reply.
Hopefully I can figure out if it's just me or if it's a bug in the SP API

### Subscription Failure Return Message
![image](https://github.com/amzn/selling-partner-api-docs/assets/131223074/d06fc543-7a9a-44fa-b07c-b17694d9238b)

### Other types of subscription success
![image](https://github.com/amzn/selling-partner-api-docs/assets/131223074/a2cbb0e3-e554-4665-ac2a-5bfbca3169e6)

### Scope of authorisation of the  APP
![image](https://github.com/amzn/selling-partner-api-docs/assets/131223074/d5dcda41-b156-4a57-9b67-02e26ce7e579)

**Comment by hexrw** [comment]
Amazon lists the createSubscription operation under grantless operations, that is simply not true, this operation is done per-seller and requires a regular LWA access token. Don't trust the docs, you don't know nothing for certain until you try. Don't trust an authority that has typos all over the place.
