### ISSUE TITLE
searchCatalogItems not working and produce only Invalid Input

### ISSUE THREAD

**Issue by nejimz** [amzn/selling-partner-api-models#2717]
Hello,

I have a problem like this but the identifiers type is SKU.
Can you help me on this?

Endpoint: `https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items`
Operation: `searchCatalogItems`

Request ID: `1b5f4ed8-1896-43ea-b193-109e0b45694f`
Run Datetime: `2023-10-05 00:12:17`

Params:
```
[
 "marketplaceIds" => "XXXXXXXX"
  "identifiers" => "sku_1"
  "identifiersType" => "SKU"
  "includedData" => "identifiers,attributes,images,productTypes,salesRanks,summaries"
  "sellerId" => "xxxxx"
  "pageSize" => 20
]
```

Errors:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```

_Originally posted by @nejimz in https://github.com/amzn/selling-partner-api-docs/issues/2490#issuecomment-1748229996_

**Comment by nejimz** [comment]
> @nejimz Did you figure out what the issue was?

Yes, i just do some modification on amazon spapi library because it was outdated.

**Comment by Noor0** [comment]
@nejimz Which library are you using?

**Comment by nejimz** [comment]
> @nejimz Which library are you using?

We use clousale and it was no longer update last Aug 2022.
The updated one is jlevers/selling-partner-api.
