### ISSUE TITLE
Catalog API not returning product_description fields

### ISSUE THREAD

**Issue by IsaacSee** [amzn/selling-partner-api-models#2721]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP-API Catalog Items API v2022-04-01

## Expected Behavior
The attribute values `product_description` should be present in the response of the search.

## Current Behavior
`product_description` is missing while requesting the `attribute` scope.

## Context/Screenshots
This product https://www.amazon.com.br/dp/B086H5CJZC has a description, which is not returned by the catalog API

## Your Environment
dotnet

**Comment by ozgurbesbudak** [comment]
any update on this bug?

**Comment by leonardonakagawa** [comment]
Hi @ozgurbesbudak, 

We are still working on this feature. I recommend you stay tuned in our [RSS feeds](http://developer-docs.amazon.com/sp-api/changelog.rss) once we have it solved, we will announce in there.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
