### ISSUE TITLE
createUploadDestinationForResource interface call returns Unauthorized, Why?

### ISSUE THREAD

**Issue by chengpan9** [amzn/selling-partner-api-models#2727]
createUploadDestinationForResource interface call returns Unauthorized.
 
param:
POST https://sellingpartnerapi-na.amazon.com/uploads/2020-11-01/uploadDestinations/aplus/2020-11-01/contentDocuments?contentType=image/jpeg&contentMD5=9e92dc1ed22ffc814f063f02b1c0f233&marketplaceIds=ATVPDKIKX0DER

ResponseBody:
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }
  ]
}

**Comment by Zengyinqi** [comment]
I also made the same mistake. How did you solve it
