### ISSUE TITLE
[BUG] [SP-API] [Issue] Report type GET_FBA_SNS_FORECAST_DATA return status CANCELLED

### ISSUE THREAD

**Issue by krystian-rzepa** [amzn/selling-partner-api-models#2728]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
API: createReport
Report: GET_FBA_SNS_FORECAST_DATA

## Expected Behavior

The report should be successfully created.

## Current Behavior

After run createReport, status is changing from IN_QUEUE -> IN_PROGRESS -> CANCELLED.
Other reports like GET_FBA_INVENTORY_PLANNING_DATA works fine with my config.

**Comment by johnkw** [comment]
This is a duplicate of bug #393 (which is still a critical bug and should be reopened instead of being moved to a discussion).
