### ISSUE TITLE
https://sellingpartnerapi-na.amazon.com/vendor/orders/v1/purchaseOrders/6QM89PQI API Not Giving Purchase Order

### ISSUE THREAD

**Issue by armipyle** [amzn/selling-partner-api-models#273]
Response:-
{
    "errors": [
        {
            "code": "ResourceNotFound",
            "message": "Cannot find resource by the given URI"
        }
    ]
}

**Comment by franciscocha** [comment]
@armipyle are you sure that's a valid Purchase Order #? Have you also tried hitting the sandbox with the test value?

**Comment by puppsupr** [comment]
Hi @armipyle,

Are you still facing the issue ? If yes please provide me the request and response details.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
