### ISSUE TITLE
Support Shipping API v2 model

### ISSUE THREAD

**Issue by nguyentoanit** [amzn/selling-partner-api-models#274]
Hi,

I found out the [Shipping API v2 model](https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-model) in documentation site. But they were not added into this repository.

Was this version available?
And is there any schedule to add the model into here.

Thanks

**Comment by sungolivia** [comment]
Please contact our Shipping v2 team at amazonshippingintegrations@amazon.com  and they will guide you through!

**Comment by psyklopz** [comment]
Seems odd that this issue was closed without actually solving the issue...  With Amazon re-launching this program in the US, it would be nice to have these models available in the repo.  The old v1 models are available in the repo after all.
