### ISSUE TITLE
catalog api attributes is null after deserializing.

### ISSUE THREAD

**Issue by getvicky83** [amzn/selling-partner-api-models#276]
This new version is not working for me. I can get author and publisher in attributes raw json object, but if i use the latest model and de serialize with gson.fromJSON(body, returnType) whole attirbutes object becomes null. 

Has anyone faced this. I need to fix this as mws is already deprecated. We ask for extension but didnt get any reply in caselog.

**Comment by Adrian-T-AMZN** [comment]
Hello @getvicky83,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
