### ISSUE TITLE
can't find IsIBA field on order model 

### ISSUE THREAD

**Issue by mitnick2012** [amzn/selling-partner-api-models#277]
Hello, 
I need isIBA field but can't find it in the order model, it exist in order swagger json from amazon 

https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-model

**Comment by shreeharsh-a** [comment]
Hi,
Which API are you trying to use? Please provide details like URL, payload etc so that we can help, thanks!

**Comment by shreeharsh-a** [comment]
Hi @mitnick2012,
Looks like you have resolved this on your own as we have not received a response. Closing this issue but please feel free to open a new one quoting this one if you are still facing the issue so that we can help.

Thanks!
