### ISSUE TITLE
How to use the UPLOAD_VAT_INVOICE feed?

### ISSUE THREAD

**Issue by sauladam** [amzn/selling-partner-api-models#2777]
I've been trying for quite a while now and I just can't get the `UPLOAD_VAT_INVOICE` feed working.

All of our other feeds (`POST_ORDER_ACKNOWLEDGEMENT_DATA`, `POST_ORDER_FULFILLMENT_DATA`) do work just fine , but `UPLOAD_VAT_INVOICE` just won't.

any `POST` request to `/feeds/2021-06-30/feeds` with a `feed_type` of `UPLOAD_VAT_INVOICE` returns a `403 Unauthorized` with the message "Access to the resource is forbidden"

Yes, *Tax Invoicing* is ticked for the app roles:

![image](https://github.com/amzn/selling-partner-api-docs/assets/5918276/ef10aaa9-9b26-4ba7-b9ea-d500355778ce)

Most of the the issues with the same problem (like amzn/selling-partner-api-models#1042) refer to the feeds API version 2020-09-04 which still involves encryption of the attached feed documents. The encryption part was removed in version 2021-06-30 and the *createFeedDocument* operation `/feeds/2021-06-30/documents` does not return any encryption details anymore, so I'm guessing this is definitely not the issue.

Apart from that, we just follow the the docs like with the other feeds:

- create a feed document (works fine)
- write content to that document (in this case as `application/pdf`) (works fine)
- pass the document id to the createFeed operation (**fails**)

The docs even have a code example specifically for `UPLOAD_VAT_INVOICE` in Java: https://developer-docs.amazon.com/sp-api/docs/option-3-upload-invoices-through-sp-api-or-seller-central

We do follow the same steps. It still does not work. But the example seems quite outdated anyway. It mainly focuses on constructing the feed data, and then sets an "MWS auth token" (`request.setMWSAuthToken(configuration.getAmazon().getMwsAuthToken());`). So that's not really helpful.

So, just a sanity check - **does anybody have it working?** 
If you have it working - what are you doing differently than with other feeds? Do we need an RDT for this operation or something ([according to the docs we don't](https://developer-docs.amazon.com/sp-api/docs/tax-invoicing-restricted-role#apis))? 
There are a few issue disucssions claiming that it works, but others still seem unresolved (like amzn/selling-partner-api-models#2437). 

We had it working fine on MWS (and it's still doing the job there until this last issue is resolved and we are finally able to migrate).

**Comment by Philomath88** [comment]
@sauladam 

`async function uploadInvoice(orderDetails, invoicePath) {
    try {
        console.log("Starting invoice upload process...");
        console.log("Invoice upload order details", orderDetails);
        console.log(`Invoice file path: ${invoicePath}`);
        //console.log('upload invoice orderDetails ', JSON.stringify(orderDetails, null, 2));
        //console.log('invoice numnber: ', orderDetails.invoiceNumber);

        // const totalAmount = orderDetails.OrderTotal?.Amount;
        // if (totalAmount === undefined) throw new Error('OrderTotal.Amount is not defined');
        // console.log('OrderTotal Amount INvoice Upload:', totalAmount);

        // Extract values from orderDetails
        const orderId = orderDetails.AmazonOrderId;
        const totalAmount = parseFloat(orderDetails.OrderTotal.Amount);

        // Sum up the total VAT amount directly from the sample order

        // let totalVATAmount = 0;
        // for (const item of orderDetails.OrderItems) {
        //     totalVATAmount += parseFloat(item.ItemTax.Amount);
        //     totalVATAmount += parseFloat(item.ShippingTax.Amount);
        // }
        // totalVATAmount = totalVATAmount.toFixed(2);

        let totalVATAmount = 0;
        for (const item of orderDetails.OrderItems) {
            console.log('Processing item:', JSON.stringify(item, null, 2)); // Log each item

            // Check if ItemTax is defined and has Amount property
            if (item.ItemTax && item.ItemTax.Amount !== undefined) {
                totalVATAmount += parseFloat(item.ItemTax.Amount);
            } else {
                console.warn(`ItemTax or Amount not defined for item: ${item.ASIN}`);
            }

            // Check if ShippingTax is defined and has Amount property
            if (item.ShippingTax && item.ShippingTax.Amount !== undefined) {
                totalVATAmount += parseFloat(item.ShippingTax.Amount);
            } else {
                console.warn(`ShippingTax or Amount not defined for item: ${item.ASIN}`);
            }
        }
        totalVATAmount = totalVATAmount.toFixed(2);

        console.log(`Total Amount: ${totalAmount}`);
        console.log(`Total VAT Amount: ${totalVATAmount}`);

        // Create a feed document and get upload URL
        console.log("Requesting feed document creation...");

        const feedDocument = await sellingPartner.callAPI({
            operation: 'createFeedDocument',
            endpoint: 'feeds',
            body: {
                contentType: 'application/pdf'
            }
        });

        console.log("Feed document details received:", feedDocument);

        if (!feedDocument.url) {
            throw new Error('Feed document creation did not return a URL for uploading');
        }

        console.log(`Uploading PDF to: ${feedDocument.url}`);

        // Prepare feed details for upload
        const feed = {
            url: feedDocument.url,
            file: invoicePath,
            contentType: 'application/pdf'
        };

        // Upload the PDF invoice
        const uploadResponse = await sellingPartner.upload(feedDocument, feed);
        console.log("Upload response:", uploadResponse);

        // Create the feed for uploaded invoice
        console.log("Creating feed for uploaded invoice...");
        const feedCreationBody = {
            marketplaceIds: [orderDetails.MarketplaceId],
            feedType: 'UPLOAD_VAT_INVOICE',
            inputFeedDocumentId: feedDocument.feedDocumentId,
            feedOptions: {
                "metadata:documenttype": "Invoice",
                "metadata:invoicenumber": orderDetails.invoiceNumber,
                "metadata:orderid": orderId,
                "metadata:totalamount": totalAmount.toFixed(2),
                "metadata:totalvatamount": totalVATAmount,
                "metadata:taxDocumentNumber": orderId
            }
        };

        console.log("Feed Creation Body:", feedCreationBody);

        const feedCreationInfo = await sellingPartner.callAPI({
            operation: 'createFeed',
            endpoint: 'feeds',
            body: feedCreationBody
        });

        console.log("Checking feed status...");
        let feedStatus = await checkFeedStatus(feedCreationInfo.feedId);
        console.log("Initial feed status:", feedStatus);

        while (feedStatus.processingStatus !== 'DONE') {
            console.log("Waiting for feed processing to complete...");
            await new Promise(resolve => setTimeout(resolve, 30000));
            feedStatus = await checkFeedStatus(feedCreationInfo.feedId);
            console.log("Updated feed status:", feedStatus);
        }

        if (feedStatus.processingStatus === 'DONE') {
            console.log("Downloading feed processing report...");
            const reportContent = await downloadFeedProcessingReport(feedStatus.resultFeedDocumentId);
            //console.log("Feed processing report content:", reportContent);
            return reportContent
        }
    } catch (error) {
        console.error('Error during the invoice upload process:', error);
    }
}
`

**Comment by sauladam** [comment]
@Philomath88 What do you mean exactly "it shows up blank on Amazon"? So you can see an associated invoice for the order in your Seller Central dashboard, but it's a blank PDF?

If that's the case, I think that would indeed indicate an issue on your end. Make sure the PDF is not actually blank, that it's being read properly by your library and so on. I know, it sounds stupid, but if the upload actually works and it actually shows up *somehow*, I would assume that the API part works fine.

Definitely check out what is returned in `reportContent`. Here's what a sucessful report looks like for us:

```
Feed Processing Summary:
	Number of records processed		1
	Number of records successful		1
```

Also, after uploading the feed document:

`const uploadResponse = await sellingPartner.upload(feedDocument, feed);`

try reading it back again and check its contents. My code is in PHP, so I can't give you an example in JS, but there is definitely an option to retrieve an uploaded document via the API.

And yeah, what the support is basically saying that you either use VCS, a third party service or do your own uploads, and that you can't mix them within a due period. We've never touched VCS, so I don't know if that really might cause issues even after opting out. But, again, it sounds like it's working, just that the document does not seem to be read properly.

**Comment by Philomath88** [comment]
@sauladam can you give me your PHP code? I have chatGPT :) 

Thanks for your swift answer!

Regarding the invoices showing up blank - I upload the same invoice document manually and everything works fine...

**Comment by sauladam** [comment]
@Philomath88 Haha, I don't think my code would be of any help - I'm definitely not rawdogging the API 🤡 I'm using an auto generated client just like you, so my code is just calls into a wrapper library, not directly interacting with HTTP requests. 

Check out the documentation of your API client.

I'm assuming you're using [amz-tools/amazon-sp-api](https://github.com/amz-tools/amazon-sp-api) -- in that case the call should look something like this:

```javascript
let feedDocumentDetails = await sellingPartner.callAPI({
    operation: "getFeedDocument",
    path:{
      feedDocumentId: feedDocument.feedDocumentId
    }
});

let res = await sellingPartner.download(feedDocumentDetails);
```

So basically you have an operation `getFeedDocument` and you pass it the `documentId`. Not sure if this code works, just did a quick search through the repo. 

But of course you can always refer to the SP-API docs: https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-reference#get-feeds2021-06-30documentsfeeddocumentid

So you call `GET /feeds/2021-06-30/documents/{feedDocumentId}`, which returns you a `FeedDocument` with an URL and an optional `compressionAlgorithm`, and then you call that URL (and decompress the result if it's gzipped). But as mentioned above, your client library probably handles all that for you.

> Regarding the invoices showing up blank - I upload the same invoice document manually and everything works fine...

Then it's pretty unlikely that it's VCS related in any way. There must be an issue somewhere in your code or in the client library. So your best bet is to verify every single step, and the first one would be to check if the uploaded PDF document actually got uploaded with all its contents.

**Comment by sauladam** [comment]
@Philomath88 As far as I can see this is the exact same code you already posted before. 

The overall structure seems fine, but what exactly have you tried to resolve your issue? In fact, you still haven't really explained what the exact issue is. 

Does the whole upload logic go through? Are there any errors / exceptions? What is stated in the feed report? Have you tried to read back the uploaded PDF document via the API? Can you pinpoint which step / part of your logic exactly doesn't seem to work as expected? And what happens instead?

**Comment by Philomath88** [comment]
@sauladam 

I always get the error: 

The uploaded document is invalid.

There are no forum posts or anything

**Comment by Philomath88** [comment]
@sauladam I solved the issue. I am currently tipsy and angry (at Amazon). At the moment, I am not willing to post the solution. Sorry, I hope everyone being tortured by the SP-API will understand.

**Comment by careyminaieva** [comment]
Hi, sorry for this update as it might be inappropriate to ask it, but does anybody knows what report structure for this feed type is? Is there a documentation for it on Amazon SP-API? Just trying to write a parser for this type of feed report to know about errors that happen during automated invoices upload in our system. Thanks!
