### ISSUE TITLE
Can't access report GET_VENDOR_TRAFFIC_REPORT

### ISSUE THREAD

**Issue by rodelrebs** [amzn/selling-partner-api-models#2778]
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

I need help about what roles or rights I need to access **GET_VENDOR_TRAFFIC_REPORT**. Access to other reports like **GET_VENDOR_SALES_REPORT** is working fine but **GET_VENDOR_TRAFFIC_REPORT** returns:

`{
  "errorDetails": "Error in report request: Report requested with invalid user inputs. Please verify if you have correct Vendor Group Rights and/or required permissions to request this report."
}
`

**Comment by nguyentoanit** [comment]
@chrisskhoury : 
I got the same issue here. And pretty sure that I had Brand Analytics Role and used a vendor refresh token for this flow.
Because, I was able to request to `GET_VENDOR_TRAFFIC_REPORT` with `SOURCING` distributor view.
But, wasn't able to with `MANUFACTURING`. 🤔
