### ISSUE TITLE
[BUG] [SP-API] Updating an offer price to a product listing doesn't work

### ISSUE THREAD

**Issue by barruka** [amzn/selling-partner-api-models#2785]
We are trying to update the price of a product via listings API, we have tried with v2020-09-01 and v2021-08-01, we got ACCEPTED in the response but after 30 minutes the price is never updated.

```
  {
	"sku": "f58b9597-2e11-4e3b-b23e-4786b00475d8",
	"status": "ACCEPTED",
	"submissionId": "beeb8d7642904dfe9f7e5b0a0d55de81",
	"issues": []
}
```

![image](https://github.com/amzn/selling-partner-api-docs/assets/22612223/b5a2ba4c-c164-468b-ace0-5eaa0e8b24d9)

```
{
	"productType": "PRODUCT",
	"patches": [
		{
			"op": "replace",
			"path": "/attributes/purchasable_offer",
			"value": [
				{
					"currency": "EUR",
					"our_price": [
						{
							"schedule": [
								{
									"value_with_tax": 10.49
								}
							]
						}
					],
					"marketplace_id": "A1RKKUPIHCS9HS"
				}
			]
		}
	]
}
```

Endpoint:
```
https://sellingpartnerapi-eu.amazon.com/listings/2020-09-01/items/ADZ2XN1RK5LNB/f58b9597-2e11-4e3b-b23e-4786b00475d8?marketplaceIds=A1RKKUPIHCS9HS
```
method 
```
PATCH
```

We hope you can give us some light!

**Comment by HristiyanGeorgiev** [comment]
Hello, how do we update the RRP of a product? I have managed to successfully update the sale price, but the RRP does not appear at all on the listing. I've tried with list_price, uvp_list_price, also tried sending the sale price as discounted_price and the RRP as our_price, but with no luck
