### ISSUE TITLE
Data exchange through XML - unable to locate the product type

### ISSUE THREAD

**Issue by ringorainbow** [amzn/selling-partner-api-models#279]
We would like to upload product in 

Category: Clothing, Shoes & Jewelry Women Accessories Scarves & Wraps
Product Type: SCARF

in XSD
https://sellercentral.amazon.com/help/hub/reference/G1611

Category XSDs
Clothing, Accessories & Luggage
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/ClothingAccessories.xsd

or
ProductClothing.xsd
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/ProductClothing.xsd

We are unable to locate the ClothingType or ProductType "SCARF" in the xsd file and therefore we are unable to upload the product without the ClothingType or ProductType 

Can anyone help?

**Comment by Adrian-T-AMZN** [comment]
Hello @ringorainbow,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
