### ISSUE TITLE
[BUG] [SP-API] [Issue] Get Listing and catalogue for Vendors

### ISSUE THREAD

**Issue by gaelayo** [amzn/selling-partner-api-models#2794]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
I would like to be able to obtain the full listing and catalogue for a given Vendor. This is currently possible for _sellers_ with the **GET_MERCHANT_LISTINGS_ALL_DATA** report type.
The `searchCatalogItems` operation does not permit getting all the ASIN for a given seller, without specifying `keywords` or `identifiers`, thus having an incomplete results.

## Current Behavior
There is not way to get the catalogue or the listing for a vendor using the API.
The catalogue is obtainable from the front-end of Vendor central, but I would like to be able to 

## Context/Screenshots
This is certainly related to https://github.com/amzn/selling-partner-api-models/issues/2350 where @chapmanjw stated that there was no way to accomplish this, but that this was on the roadmap. It was two years ago, so I was wondering if there were any news about this.

**Comment by HamzaDevz** [comment]
Hello @chapmanjw,

A report is existing to get the whole live catalog for Vendors ?

**Comment by FilipMasar** [comment]
@chapmanjw any updates when `searchListingsItems` might be available? We would also like to fetch all products posted by a specific seller. In the meantime, is there some other way that you would recommend us doing that?

**Comment by torykeplerpci** [comment]
@chapmanjw Is there an update on when the searchListingsItems operation will be available?  The current experience for vendors using the SP API is not good...Being able to query all products in a vendor account is a basic necessity and it is extremely limiting needing to query items one by one using the getListing operation.

**Comment by HamzaDevz** [comment]
I agree, Vendors are really left behind compared to Sellers.
