### ISSUE TITLE
[BUG] [SP-API] [Issue] No 404s for price updates

### ISSUE THREAD

**Issue by Faithfinder** [amzn/selling-partner-api-models#2797]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
[Patch Listing Item](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku) and POST_PRODUCT_PRICING_DATA Feed,

## Expected Behavior
When I send an incorrect SKU to either, if there's an error in SKU, I get an error in the `issues` array

## Current Behavior
Instead everything is reported as good - price change is accepted, feed result returns successful processing

**Comment by chapmanjw** [comment]
@Faithfinder I've sent this over to our product team to evaluate. Doesn't necessarily mean that it will change, but providing your feedback for their consideration. Thanks!
