### ISSUE TITLE
想问一下，RateLimitConfiguration配置的设置

### ISSUE THREAD

**Issue by lcy0186** [amzn/selling-partner-api-models#280]
我代码是这样写的
RateLimitConfiguration rateLimitOption = RateLimitConfigurationOnRequests.builder()
.rateLimitPermit(200d)
.waitTimeOutInMilliSeconds(1000l)
.build();
OrdersV0Api ordersApi = new OrdersV0Api.Builder()
.awsAuthenticationCredentials(awsAuthenticationCredentials)
.lwaAuthorizationCredentials(lwaAuthorizationCredentials)
.awsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
.endpoint(item.getEndpoint())
.disableAccessTokenCache()
.rateLimitConfigurationOnRequests(rateLimitOption)
.build();
这样好像没有起作用啊，要怎么写这个亚马逊速率的问题？rateLimitPermit与waitTimeOutInMilliSeconds这两个参数如何写，同时怎么使用

**Comment by dengliming** [comment]
rateLimitPermit代表每秒生成的令牌数，waitTimeOutInMilliSeconds代表等待超时时间的方式获取令牌，如果超timeout为Long.MAX_VALUE，则代表一直阻塞直到返回。
