### ISSUE TITLE
[BUG] [SP-API] Fulfillment Inbound API v2024-03-20. How to get contents of shipments?

### ISSUE THREAD

**Issue by ArseniyK** [amzn/selling-partner-api-models#2800]
Is there a way to retrieve shipment contents in the new API? Something similar to what we have in UI
<img width="431" alt="Screenshot 2024-05-24 at 14 26 05" src="https://github.com/amzn/selling-partner-api-docs/assets/144217/02f4b3b6-5789-462c-9dd1-272964e1a0bb">
How are we supposed to understand what items we should send if there is no information in the API about the contents of the shipments generated by Amazon?

Even after confirming the shipment, there is no such information.

Am I missing something or the API is completely broken and not usable???

**Comment by KirillChekalin** [comment]
Hi everyone,

Like many developers, I am also disappointed with the lack of information about the contents of shipments generated by Amazon through the API.

The current API does not provide detailed information about the items included in the shipments, even after confirming the shipment. This missing feature can lead to confusion and inefficiencies.

To partially address this issue, I am using the legacy API, which still provides the necessary details about shipment contents. While not ideal, it serves as a temporary workaround.

**Comment by shreeharsh-a** [comment]
Hi @ArseniyK,
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
