### ISSUE TITLE
Sandbox for Get reports/2021-06-30/documents/{documentId} does not support report type GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE

### ISSUE THREAD

**Issue by AbdelrahmanTarek97** [amzn/selling-partner-api-models#284]
Hello, I cannot use sandbox to get the schema for the GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE report type. if possible can someone assist with giving me a sample file that mocks the real report with the real fields or at least give me the fields and their types? Thank you in advance.

**Comment by franciscocha** [comment]
Not sure if you ever got this data but here it is:
Order ID 
Order date 
Return request date 
Return request status 
Amazon RMA ID 
Merchant RMA ID 
Label type 
Label cost 
Currency code 
Return carrier 
Tracking ID 
Label to be paid by 
A-to-Z Claim 
Is prime 
ASIN 
Merchant SKU 
Item Name 
Return quantity 
Return Reason 
In policy 
Return type 
Resolution 
Invoice number 
Return delivery date 
Order Amount 
Order quantity 
SafeT Action reason 
SafeT claim id 
SafeT claim state 
SafeT claim creation time 
SafeT claim reimbursement amount 
Refunded Amount

**Comment by puppsupr** [comment]
Hi @AbdelrahmanTarek97,

Are you still looking for the schema ?

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
