### ISSUE TITLE
[FEATURE] enable downloading for product catalog like the one shown in vendor central console

### ISSUE THREAD

**Issue by hongfei-zhou** [amzn/selling-partner-api-models#2889]
We are trying to download the `Product Catalog` report through the API but couldn't find an appropriate way. The existing catalog item API requires ASINs and only 20 ASINs at a time. It would be best if we can download all Product Catalog for the authorized account.

**Comment by wolendranh** [comment]
@chapmanjw @krithic15 Is there any update on this?
@civetworks did you manage to solve this in any way?
