### ISSUE TITLE
Invalid ASIN causes a batch SearchCatalogItems request fail

### ISSUE THREAD

**Issue by gokigoks** [amzn/selling-partner-api-models#2894]
If a batch request for the SearchCatalogItems endpoint includes an invalid asin (ex. 20DOMINANT), it returns an error that basically disregards the rest. 

The error message we get back is only:
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid \u0027asin\u0027 provided.",
      "details": ""
    }
  ]
}

This is unacceptable as SPAPI doesn't even return which ASIN is invalid IN A BATCH REQUEST along with failing the whole request. This is obviously a bug so please fix it asap. We're desperately trying to migrate before the end-of-life date and these big issues are a real stopper.

**Comment by patelnimesh1988** [comment]
ASIN should be 10 character log
