### ISSUE TITLE
Cannot get TBYB Order Payment type order financial data

### ISSUE THREAD

**Issue by juebanwei** [amzn/selling-partner-api-models#2906]
Cannot get TBYB Order Payment type order financial data

Interface : https://developer-docs.amazon.com/sp-api/docs/finances-api-reference#listfinancialeventsbyorderid

**Comment by tspicer** [comment]
Hello @CrionaAm ,

It has been a couple of years, and I'm not sure this issue is fixed; at least, I could not discern where the TBYB Trial Shipment is being set. Can you provide an update?
