### ISSUE TITLE
[FEATURE] Is it possible to determine which account a Disbursement (GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2) is for without parsing the file?

### ISSUE THREAD

**Issue by bjpierre** [amzn/selling-partner-api-models#2911]
Our company sells in both the US and Canada. We'd like to keep the two seperate for marketing purposes. Calling the GetReports end point for GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 with the United States marketplaceId (ATVPDKIKX0DER) returns every Settlement report ever, and they all have 6 marketplace Id's listed. Calling with the Canada MarketplaceId (A2EUQ1WTGCTBG2) yields the same exact results. But I'm able to look at these reports and the last ten (I didn't look any further) seem to be separated out, one report is all of our Canada Sales, one report is all of our US sales. The two are never mixed. 

Can I tell this information somehow or filter my results to only be for one or the other without downloading the report and parsing it out to see if the lines are for the US or CA?

Also, I know we're supposed to open a support case for things like this, not post here, but the three times I've tried that I've been told to refer to the documentation (twice with a link that was a copy of the link I referenced in my request) and that if the docs don't answer then to refer to third party forums. So here we are.

**Comment by albert-le-whoop** [comment]
This bug has existed for so long it might as well be a feature. If Amazon fixes it, many downstream things will break across a variety of users.

**Comment by arpetris** [comment]
I'm running into this as well. The documentation clearly states:

marketplaceIds
array of strings
length between 1 and 10
**A list of marketplace identifiers used to filter reports. The reports returned will match at least one of the marketplaces that you specify.**

But the list returns every report. I've also found the date filters are funky. I can request reports for the last 60 days and not get all the reports in that range but then get reports months older than the request.

Is there anyone from Amazon to comment on this? Is there an official way to send bug reports on the API?
