### ISSUE TITLE
PUT https://sellingpartnerapi-na.amazon.com/listings/2020-09-01/items/SellerId/SKU000012?marketplaceIds=ATVPDKIKX0DER

### ISSUE THREAD

**Issue by gbconstacloud** [amzn/selling-partner-api-models#2918]
I am getting this error in putListingsItem api for LUGGAGE productType

Request :

`{
    "productType": "LUGGAGE",
    "requirements": "LISTING",
    "attributes": {
        "condition_type": [
            {
                "value": "new_new",
                "marketplaceIds": "ATVPDKIKX0DER"
            }
        ],
        "item_name": [
            {
                "value": "My Basics 16 inch Underseat Spinner Carry-On",
                "language_tag": "en_US",
                "marketplace_id": "ATVPDKIKX0DER",
                "model_name": "test"
            }
        ],
        "brand": [
            {
                "value": "not_applicable"
            }
        ],
        "model_name": [
            {
                "value": "not_applicable"
            }
        ],
        "merchant_suggested_asin": [
            {
                "value": "B0937LGVY7"
            }
        ],
        "supplier_declared_dg_hz_regulation": [
            {
                "value": "not_applicable"
            }
        ],
        "batteries_required": [
            {
                "value": false
            }
        ],
        "material": [
            {
                "value": "not_applicable"
            }
        ],
        "style": [
            {
                "value": "Samsung_12"
            }
        ],
        "bullet_point": [
            {
                "value": "not_applicable"
            }
        ],
        "model_number": [
            {
                "value": "not_applicable"
            }
        ],
        "item_type_keyword": [
            {
                "value": "not_applicable"
            }
        ],
        "product_description": [
            {
                "value": "not_applicable"
            }
        ],
        "item_type_name": [
            {
                "value": "not_applicable"
            }
        ],
        "color": [
            {
                "value": "red"
            }
        ],
        "country_of_origin": [
            {
                "value": "US"
            }
        ],
        "item_package_dimensions": [
            {
                "height": {
                    "unit": "inches",
                    "value": {
                        "title": "Item Package Height",
                        "description": "Provide the package height as a numeric value.",
                        "editable": true,
                        "hidden": false,
                        "examples": [
                            "3"
                        ],
                        "type": "number",
                        "minimum": 0,
                        "maximum": 9878954
                    }
                }
            },
            {
                "length": {
                    "value": 16.50,
                    "unit": "inches"
                }
            },
            {
                "width": {
                    "value": 4.20,
                    "unit": "inches"
                }
            }
        ],
        "department": [
            {
                "value": "US"
            }
        ],
        "supplier_declared_material_regulation": [
            {
                "value": "not_applicable"
            }
        ],
        "item_package_weight": [
            {
                "value": "4",
                "unit": "kilograms"
            }
        ]
    }
}
`

Response 

`{
    "sku": "SKUABV789654",
    "status": "INVALID",
    "submissionId": "2aa4950e8f9a4b1e8f71dbf126d0a95a",
    "issues": [
        {
            "code": "99022",
            "message": "Required value missing for field width.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        },
        {
            "code": "99022",
            "message": "Required value missing for field height.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        },
        {
            "code": "99022",
            "message": "Required value missing for field length.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        },
        {
            "code": "90180",
            "message": "The value '{hidden:\"false\",examples:[\"3\"],editable:\"true\",description:\"Provide the package height as a numeric value.\",maximum:\"9878954\",title:\"Item Package Height\",type:\"number\",minimum:\"0\"}' in the field 'height.value' for the attribute 'item_package_dimensions' has the wrong type. The provided type is 'STRUCT' while the expected type is 'DECIMAL'.",
            "severity": "ERROR",
            "attributeName": "item_package_dimensions"
        }
    ]
}`

**Comment by gauravbairwa** [comment]
working json for "LUGGAGE" `productType`  
`
"messages": [
    {
      "messageId": 1,
      "sku": "01-1GAN-IK",
      "operationType": "UPDATE",
      "productType": "LUGGAGE",
      "requirements": "LISTING",
      "attributes": {
        "model_name": [
          {
            "value": "Model XYZ",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "color": [
          {
            "value": "Red",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "item_type_keyword": [
          {
            "value": "luggage"
          }
        ],
        "material": [
          {
            "value": "Polyester"
          }
        ],
        "model_number": [
          {
            "value": "XYZ123",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "item_package_weight": [
          {
            "value": 2.5,
            "unit": "pounds"
          }
        ],
        "department": [
          {
            "value": "Travel"
          }
        ],
        "batteries_required": [
          {
            "value": "No"
          }
        ],
        "product_description": [
          {
            "value": "This is a high-quality luggage for all your travel needs."
          }
        ],
        "brand": [
          {
            "value": "GHESG",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "style": [
          {
            "value": "Modern"
          }
        ],
        "externally_assigned_product_identifier": [
          {
            "value": "0123456789012"
          }
        ],
        "country_of_origin": [
          {
            "value": "CN"
          }
        ],
        "bullet_point": [
          {
            "value": "Durable and lightweight."
          },
          {
            "value": "Stylish design."
          }
        ],
        "item_name": [
          {
            "value": "Your Item Name"
          }
        ],
        "condition_type": [
          {
            "value": "new_new",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "number_of_items": [
            {
                "value": 10,
                "marketplace_id": "ATVPDKIKX0DER"
            }
        ],
        "list_price": [
          {
            "currency": "USD",
            "value": 100
          }
        ],
        "item_package_dimensions": [
          {
            "length": {
              "unit": "inches",
              "value": 5.0
            },
            "width": {
              "unit": "inches",
              "value": 10.0
            },
            "height": {
              "unit": "inches",
              "value": 20.0
            },
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "merchant_suggested_asin": [
          {
            "value": "ABCDEFGHIJ"
          }
        ],
        "supplier_declared_dg_hz_regulation": [
          {
            "value": "unknown"
          }
        ]
      }
    }
  ]
`
