### ISSUE TITLE
Unauthorized.  Access to requested resource is denied

### ISSUE THREAD

**Issue by gwilburn68** [amzn/selling-partner-api-models#2944]
@khanakia

I posed this question on another thread which is now closed...

I am also getting this error. Migrating from MWS, so I followed the setup process as outlined in dev guide (and in your previous responses). In Postman (and using my code) I am able to

1. Get an LWA access token
2. Use the access token to assume selling partner role using STS

But when I use the Access Key, Secret Key, Session Token from the assumeRole and Access Token to hit the Restricted Data Token.  I get:
{
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}
This is a Private (Internal) Developer Application
I can currently access PII using the MWS API
I had to write my own signing software (I'm on an IBM i system and cannot use the SDKs)
I had updated my profile to add "Tax" access and now my "Developer Registration is Under Review"
My App ID is in Draft status and is associated with my user ARN

I have a case open with Amazon currently 

Any suggestions?

**Comment by supoman-service** [comment]
If you need it, you can take a look or contact me.

https://www.sellerhub.cn/archives/amazon-pii-question
