### ISSUE TITLE
The "CatalogCategories" endpoint in "Selling Partner API for Catalog Items" is only available in the v0.

### ISSUE THREAD

**Issue by Cacodaimon** [amzn/selling-partner-api-models#297]
The v0 Version of [Selling Partner API for Catalog Items](https://github.com/amzn/selling-partner-api-models/tree/main/models/catalog-items-api-model) contains an endpoint for fetching the categories: [`/catalog/v0/categories`](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItemsV0.json#L802) for a specific item.

This endpoint is missing in the [2020-12-01](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItems_2020-12-01.json#L5) as well as in the [2022-04-01](https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItems_2022-04-01.json#L5) version.

Using the v0 API works without any problem, and it returns the desired results, e.g. for the ASIN *B00Q8UN6IY*:

```
class ListCatalogCategoriesResponse {
    payload: class ListOfCategories {
        [class Categories {
            productCategoryId: 316964011
            productCategoryName: Netzkabel
            parent: {ProductCategoryId=1382774031, ProductCategoryName=Kabel, parent={ProductCategoryId=1382748031, ProductCategoryName=Zubehör, parent={ProductCategoryId=571760, ProductCategoryName=Hifi & Audio, parent={ProductCategoryId=569604, ProductCategoryName=Kategorien, parent={ProductCategoryId=562066, ProductCategoryName=Elektronik & Foto}}}}}
        }]
    }
    errors: null
}
```

This endpoint is quite useful for us because it allows to fetch the item's parent category. But I am wondering whether it is **missing** on the newer API model definitions for **purpose** e.g. because of deprecation or by **accident**?

**Comment by rugved1991** [comment]
Hi @Cacodaimon,

Thanks for sharing feedback. We currently do not have an equivalent operation on the newer versions of the Catalog Items API. Until we have the getCatalogCategories operation on the newer version of the API, we will continue to support the V0 version.

Best,
Rugved
Solutions Architect, SP API
