### ISSUE TITLE
Finances API: Marketplace as Information in a FinacialEventGroup

### ISSUE THREAD

**Issue by VanDeMeer** [amzn/selling-partner-api-models#30]
Would it be possible to provide the _'marketplace'_ belonging to the **FinancialEventGroup** directly 
as information in the **FinancialEventGroup**?

At present, the _'marketplace'_ has to be laboriously determined using the **FinancalEvents** belonging
to the **FinacialEventGroup**. This only works with shipments or refunds.
Therefore we cannot deal with **FinancialEventGroups** which only contain ServiceFees, DebtRecovery or else, 
because the _'marketplace'_ is missing in these event types.

**Comment by beastmike1** [comment]
Please, is also very important for us to have the marketplace, also there are other event types that doesn't have any kind of date, that would be also awesome to have.

**Comment by beastmike1** [comment]
This haven't been adressed yet, and the problem haven't been solved.

**Comment by 401009641** [comment]
Amazon API programmers are the most garbage apes I've ever seen, a lot of idiots brain-dead write code and design, fucking brainless, many interfaces are the same as mentally retarded, even elementary school students are not as good as writing, fuck your mother, what a comparison

A lot of fees are structured differently, messy, really idiotic design
