### ISSUE TITLE
Bug: `NotificationType` enum was removed from the spec

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-models#300]
I think this is a regression.

https://github.com/amzn/selling-partner-api-models/commit/095609498fdb838e265475d95d3b0321a1a8e69e?diff=split#diff-98dc8df9f35a9edfc82ee516a663189ca9c017ee7210d62d518459ea5fda64b9L1927-L1942

**Comment by moltar** [comment]
Any updates on this?

@jevoniuk @waldrogi @andiec1

**Comment by moltar** [comment]
@hudalexa

**Comment by rugved1991** [comment]
Hi @moltar,

Please refer to our [SP API Documentation website](https://developer-docs.amazon.com/sp-api/docs) for latest swagger model of each API. 

Best,
Rugved
Solutions Architect, SP API

**Comment by moltar** [comment]
@rugved1991 Your answer does to at all explain my question. I, of course, did check the documentation.

The `NotificationType` enum is removed, without any warning, which is a breaking change.

My question is why? As I think it is a regression.

We auto-generate code a library from OpenAPI spec, which generated an `enum` type, but with the referenced commit, the type is just simply not being generated, which breaks compatibility.
