### ISSUE TITLE
ItemImage.variant enum coming from the API should be uppercase

### ISSUE THREAD

**Issue by alexluca89** [amzn/selling-partner-api-models#301]
https://github.com/amzn/selling-partner-api-models/blob/main/models/catalog-items-api-model/catalogItems_2022-04-01.json

<img width="772" alt="image" src="https://user-images.githubusercontent.com/37292947/211520740-2a0e09b1-2727-4e15-a82a-bc1f7011deb8.png">

I am getting this error: `Invalid value 'Main' for 'variant', must be one of 'MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06', 'PT07', 'PT08', 'SWCH'` 

Maybe this fix should be inside the API so it always comes as uppercase?

**Comment by shreeharsh-a** [comment]
Hi,
Which API are you trying to use for which you are getting the mentioned error? Please provide more details along with payload etc.

**Comment by chapmanjw** [comment]
@alexluca89 Do you have an example ASIN + marketplace we can investigate? And an example response payload showing the invalid values?

**Comment by shreeharsh-a** [comment]
Hi @alexluca89
Looks like you have resolved this on your own as we have not received a response. Closing this issue but please feel free to open a new one quoting this one if you are still facing the issue so that we can help.

Thanks!
