### ISSUE TITLE
searchCatalogItems 2022-04-01 - Invalid \\u0027asin\\u0027 provided.

### ISSUE THREAD

**Issue by AndreyBaryshev** [amzn/selling-partner-api-models#3013]
I faced with the issue for searchCatalogItems.
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#get-catalog2022-04-01items

Yesterday `[16 06 2022 11:58:24 UTC]` I did this request and got success response with data.
`GET https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items?sellerId=XXXXXXX&identifiers=XXXXXXX%2CYYYYYYY%2CZZZZZZZ&marketplaceIds=ATVPDKIKX0DER&identifiersType=ASIN&pageSize=20&includedData=attributes%2Cdimensions%2Cidentifiers%2Cimages%2CproductTypes%2Crelationships%2CsalesRanks%2Csummaries
`

Today `[17 06 2022 06:06:22 UTC]` I tried to make the same request but I got this error:
`'{\n  "errors": [\n    {\n      "code": "InvalidInput",\n      "message": "Invalid \\u0027asin\\u0027 provided.",\n      "details": ""\n    }\n  ]\n}'`

Also, request with **JUST ONE** identifier works ok, but if I try to pass more than one it returns error above.

**Comment by patelnimesh1988** [comment]
ASIN should be 10 character log
