### ISSUE TITLE
Brand Analytics Search Query Performance Report

### ISSUE THREAD

**Issue by ykuni-software-developer** [amzn/selling-partner-api-models#3026]
I have not seen the availability to access Brand Analytics Search Query Performance Report in the documentation. Is this available in the SP-API or not yet?

**Comment by monoteos** [comment]
+1 waiting for it as well, whole Ad agency and all clients are waiting...

**Comment by naman7474** [comment]
+1 waiting for it as well.

**Comment by tspicer** [comment]
It has been many years, and this is still not available. Amazon should strive for parity in available data as an export from the UI and the API.  Data scraping software tools are commercially offering reports like this and others like PII exports, bypassing the API. For companies that will only use official APIs, this puts us at a disadvantage to backdoor software tools willing to violate Amazon AUP and DPP.

**Comment by fret423** [comment]
+1

**Comment by or-en** [comment]
+1

**Comment by shishank-bsc** [comment]
+1

**Comment by styoe** [comment]
+1

**Comment by nikolajalejandro** [comment]
New update from Amazon:
[](https://developer-docs.amazon.com/sp-api/docs/report-type-values-analytics)

**Comment by styoe** [comment]
Still no top clicked categories in the search terms report :/
