### ISSUE TITLE
I am not able to retrieve 'Amazon Fees' of the Transaction View from the Selling Partner API

### ISSUE THREAD

**Issue by maggiep-1** [amzn/selling-partner-api-models#3030]
I am trying to retrieve data from the Transaction View fields, especially from the ‘Amazon Fees’ field. I have tried to retrieve different report types such as ‘GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA’, ‘GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2’, etc.  but I am not able to retrieve the desired data. Is there any chance that this field is named differently on the API compared to the UI terminology? 
According to a Selling Partner API issue (refer to: https://github.com/amzn/selling-partner-api-models/issues/389), there is still no answer for this problem. Can you take care of this issue, please?

The Transaction View on UI:
![Screenshot 2022-06-03 160002](https://user-images.githubusercontent.com/106821251/171869194-f1ee00fc-d9e1-4c95-87f4-f861c2550c46.jpg)

**Comment by tom-it** [comment]
We cannot get any fees not on the  /finances/v0/orders/{orderId}/financialEvents also not on the  /finances/v0/financialEvents endpoint, we keep getting access denied, even though I think we have all the needed permissions
