### ISSUE TITLE
[TYPE] orders/orderItems wrong type for `IsGift` and `ProductInfo`

### ISSUE THREAD

**Issue by Roman991** [amzn/selling-partner-api-models#304]
`GET /orders/v0/orders/{orderId}/orderItems`

The response type for ProductInfo and IsGift is wrong

The first should be an INTEGER https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#productinfodetail
The latter a BOOLEAN https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#orderitem
```javascript
{
    ProductInfo: {
      NumberOfItems: "1",
    },
    IsGift: "false",
    ...
}
```

_Originally posted by @Roman991 in https://github.com/amzn/selling-partner-api-models/issues/158#issuecomment-1426695386_

**Comment by shreeharsh-a** [comment]
Hi,
Per the [docs](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-model), the schema for ProductInfo is:
```
"ProductInfo": {
          "description": "Product information for the item.",
          "$ref": "#/definitions/ProductInfoDetail"
        }
```
```
"ProductInfoDetail": {
      "type": "object",
      "properties": {
        "NumberOfItems": {
          "type": "string",
          "description": "The total number of items that are included in the ASIN."
        }
      },
      "description": "Product information on the number of items."
    }
```
Similarly for IsGift, its:
```
"IsGift": {
          "type": "string",
          "description": "Indicates whether the item is a gift.\n\n**Possible values**: `true`, `false`."
        }
```
This is currently as designed, thanks!
