### ISSUE TITLE
Report Type of "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT" can't work

### ISSUE THREAD

**Issue by lynmison** [amzn/selling-partner-api-models#308]
hi all.
  when i create report type of GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT, api return reportId and seem that run collectly.
create report code:
`		ReportsV1Api api = buildApi();

		CreateReportSpecification body = new CreateReportSpecification();
		String reportType = "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT";
							 
		OffsetDateTime start = OffsetDateTime.parse("2023-02-01T00:00:00.0Z");
		OffsetDateTime end = OffsetDateTime.parse("2023-02-28T00:00:00.0Z");
		body.setDataStartTime(start);
		body.setDataEndTime(end);

		ReportOptions option = new ReportOptions();
		option.put("reportPeriod", "MONTH");

		body.setReportOptions(option);
		body.setReportType(reportType);

		List<String> marketplaceIds = new ArrayList<>();
		marketplaceIds.add("ATVPDKIKX0DER");
		body.setMarketplaceIds(marketplaceIds);

		try {
			CreateReportResponse response = api.createReport(body);
			System.out.println(response.toString());
		}catch(ApiException e) {
			e.printStackTrace();
		}

`
but when i retriew the report status by report id, api tell me that the report created fatal.

`
class Report {
    marketplaceIds: [ATVPDKIKX0DER]
    reportId: 112371019446
    reportType: GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT
    dataStartTime: 2023-02-01T00:00Z
    dataEndTime: 2023-02-28T00:00Z
    reportScheduleId: null
    createdTime: 2023-03-30T09:45:49Z
    processingStatus: FATAL
    processingStartTime: 2023-03-30T09:45:56Z
    processingEndTime: 2023-03-30T09:46:07Z
    reportDocumentId: amzn1.spdoc.1.4.na.sfafdfsd-3e06-4bfe-xxx-xxxxxx.Tssssdd.5600
}

`

what's the reason?

**Comment by puppsupr** [comment]
Hi [lynmison](https://github.com/lynmison),

Are you still facing the same issue ?

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by lynmison** [comment]
> Hi [lynmison](https://github.com/lynmison),
> 
> Are you still facing the same issue ?
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

Hi [puppsupr](https://github.com/puppsupr),
Thanks for your reply.
I try to create GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT just now, 
I can create and download report successfully. 
But i foud that the data i created and downloaded by API is inconsistent with the official backend. for example:

`
API data =>

{
  "reportSpecification" : {
    "reportType" : "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
    "reportOptions" : {
      "reportPeriod" : "DAY"
    },
    "dataStartTime" : "2023-04-01",
    "dataEndTime" : "2023-04-01",
    "marketplaceIds" : [ "ATVPDKIKX0DER" ]
  },
  "dataByDepartmentAndSearchTerm" : [ {
    "departmentName" : "Amazon.com",
    "searchTerm" : "avatar the way of water",
    "searchFrequencyRank" : 1,
    "clickedAsin" : "B0B73WDCX9",
    "clickedItemName" : "Avatar: The Way of Water",
    "clickShareRank" : 1,
    "clickShare" : 0.7989,
    "conversionShare" : 0.0000
  }, {
    "departmentName" : "Amazon.com",
    "searchTerm" : "avatar the way of water",
    "searchFrequencyRank" : 1,
    "clickedAsin" : "B0B72T9GNZ",
    "clickedItemName" : "Avatar: The Way of Water",
    "clickShareRank" : 2,
    "clickShare" : 0.1364,
    "conversionShare" : 0.0000
  }, {
    "departmentName" : "Amazon.com",
    "searchTerm" : "avatar the way of water",
    "searchFrequencyRank" : 1,
    "clickedAsin" : "B00BRNALH6",
    "clickedItemName" : "Avatar",
    "clickShareRank" : 3,
    "clickShare" : 0.0254,
    "conversionShare" : 0.0000
  }, {
    "departmentName" : "Amazon.com",
    "searchTerm" : "creed 3",
    "searchFrequencyRank" : 2,
    "clickedAsin" : "B0B8TGB4W9",
    "clickedItemName" : "Creed III",
    "clickShareRank" : 1,
    "clickShare" : 0.6363,
    "conversionShare" : 0.0000
  }, {
    "departmentName" : "Amazon.com",
    "searchTerm" : "creed 3",
    "searchFrequencyRank" : 2,
    "clickedAsin" : "B0B8V5Y3QY",
    "clickedItemName" : "Creed III Extended Clip",
    "clickShareRank" : 2,
    "clickShare" : 0.1675,
    "conversionShare" : 0.0000
  }, {
    "departmentName" : "Amazon.com",
    "searchTerm" : "creed 3",
    "searchFrequencyRank" : 2,
    "clickedAsin" : "B0B8TFCPHM",
    "clickedItemName" : "Creed III",
    "clickShareRank" : 3,
    "clickShare" : 0.0910,
    "conversionShare" : 0.0000
  }, {
    "departmentName" : "Amazon.com",
    "searchTerm" : "john wick",
    "searchFrequencyRank" : 3,
    "clickedAsin" : "B00R8L51BC",
    "clickedItemName" : "John Wick",
    "clickShareRank" : 1,
    "clickShare" : 0.2675,
    "conversionShare" : 0.0000
  }
...
`

`
the official backend data=>

searchTerm                         searchFrequencyRank
avatar the way of water                    1
iphone charger                                 2
creed 3                                             3
...
`

searchTerm isn't the same started from the sencond searchRank keyword.
API Version: v2021-06-30

Thanks again & Regards
lynmison
