### ISSUE TITLE
What is the difference between UPDATE, PATCH and PARTIAL_UPDATE?

### ISSUE THREAD

**Issue by Philomath88** [amzn/selling-partner-api-models#311]
What is the difference between UPDATE, PATCH and PARTIAL_UPDATE?

**Comment by rodrifed** [comment]
Hi @Philomath88,

Could you please provide some more context on which API section/operation you are referring to?

Thank you,
Federico
Selling Partner Developer Services

**Comment by Philomath88** [comment]
updating a listing with JSON or with XML

**Comment by rodrifed** [comment]
Hi @Philomath88,

Our APIs provide the following functionality for listings:

- Create
- Update
- Delete

Updating can be done in full, or partially. For example, the PUT operation from the Listings Items API allows you to do a full update of your listings; the PATCH operation, on the other hand, allows you to do a partial update.
I encourage you to take a look at the [Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide), which will provide useful details.

Thank you,
Federico
Selling Partner Developer Services

**Comment by Philomath88** [comment]
@rodrifed Thank you. Could you also tell me how I can change the productType programmatically?

**Comment by rodrifed** [comment]
Hi @Philomath88,

Amazon assigns the product type to each product. This is not something you can modify or influence.
If you feel a product is incorrectly categorized, please contact Seller Support.

Thank you,
Federico
Selling Partner Developer Services
