### ISSUE TITLE
Where can I view all possible values for ProductCategoryId?

### ISSUE THREAD

**Issue by Philomath88** [amzn/selling-partner-api-models#312]
Where can I view all possible values for ProductCategoryId?

**Comment by rodrifed** [comment]
Hi @Philomath88,

You can use the [GET_XML_BROWSE_TREE_DATA](https://developer-docs.amazon.com/sp-api/docs/report-type-values-browse-tree) report to get the data you are looking for.

Thank you,
Federico
Selling Partner Developer Services
