### ISSUE TITLE
2 type problem(object vs array) in specification: model/financesV0.json

### ISSUE THREAD

**Issue by bencevegert** [amzn/selling-partner-api-models#316]
There are 2 problems where i think should be array instead of the currently object type:
1, **ValueAddedServiceChargeEventList**, in specification it's an object, but the response JSON of the API is look like a collection (the json to object mapping failed in .NET, C#):
  "ValueAddedServiceChargeEventList":[],
in spec:
"ValueAddedServiceChargeEventList": {
      "type": "object",
      "properties": {
        "TransactionType": {
          "type": "string",
          "description": "Indicates the type of transaction.\n\nExample: 'Other Support Service fees'"
        },
        "PostedDate": {
          "description": "The date and time when the financial event was posted.",
          "$ref": "#/definitions/Date"
        },
        "Description": {
          "type": "string",
          "description": "A short description of the service charge event."
        },
        "TransactionAmount": {
          "description": "The amount of the service charge event.",
          "$ref": "#/definitions/Currency"
        }
      },
      "description": "An event related to a value added service charge."
    },

2,The same problem with FailedAdhocDisbursementEventList.

Also see problems in the official API documentation:
https://developer-docs.amazon.com/sp-api/docs/finances-api-reference
FailedAdhocDisbursementEventList

If this property is a list, then should be something like this:
DirectPaymentList
A list of direct payment information.

Type : < [DirectPayment](https://developer-docs.amazon.com/sp-api/docs/finances-api-reference#directpayment) > array 

The API gives this response: 
![image](https://github.com/amzn/selling-partner-api-models/assets/8543713/6886cc03-1b89-46e2-82b2-4bf31d745fb0)

**Comment by shreeharsh-a** [comment]
Hi,
1. Per the [docs](https://developer-docs.amazon.com/sp-api/docs/finances-api-v0-model), the schema is:
```
"ValueAddedServiceChargeEventList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ValueAddedServiceChargeEvent"
      },
      "description": "A list of `ValueAddedServiceCharge` events."
    }
```
```
"ValueAddedServiceChargeEvent": {
      "type": "object",
      "properties": {
        "TransactionType": {
          "type": "string",
          "description": "Indicates the type of transaction.\n\nExample: 'Other Support Service fees'"
        },
        "PostedDate": {
          "description": "The date and time when the financial event was posted.",
          "$ref": "#/definitions/Date"
        },
        "Description": {
          "type": "string",
          "description": "A short description of the service charge event."
        },
        "TransactionAmount": {
          "description": "The amount of the service charge event.",
          "$ref": "#/definitions/Currency"
        }
      },
      "description": "An event related to a value added service charge."
    }
```
Thus the response JSON is correct.

2. Similarly, the schema is:
```
"FailedAdhocDisbursementEventList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/FailedAdhocDisbursementEvent"
      },
      "description": "A list of `FailedAdhocDisbursementEvent`s."
    }
```
```
"FailedAdhocDisbursementEvent": {
      "type": "object",
      "properties": {
        "FundsTransfersType": {
          "type": "string",
          "description": "The type of fund transfer. \n\nExample \"Refund\""
        },
        "TransferId": {
          "type": "string",
          "description": "The transfer identifier."
        },
        "DisbursementId": {
          "type": "string",
          "description": "The disbursement identifier."
        },
        "PaymentDisbursementType": {
          "type": "string",
          "description": "The type of payment for disbursement. \n\nExample `CREDIT_CARD`"
        },
        "Status": {
          "type": "string",
          "description": "The status of the failed `AdhocDisbursement`. \n\nExample `HARD_DECLINED`"
        },
        "TransferAmount": {
          "description": "The amount of the Adhoc Disbursement.",
          "$ref": "#/definitions/Currency"
        },
        "PostedDate": {
          "description": "The date and time when the financial event was posted.",
          "$ref": "#/definitions/Date"
        }
      },
      "description": "Failed ad hoc disbursement event list."
    }
```
Thus the response JSON is correct. Please try searching the above schema text in the doc link mentioned above.

Thanks!
