### ISSUE TITLE
What to put in a message JSON_LISTINGS_FEED with requirements LISTING_PRODUCT_ONLY

### ISSUE THREAD

**Issue by Liritt** [amzn/selling-partner-api-models#319]
Hello, as I tried to make a code that would create offers in bulk, I tried to find in the documentation the content I have to put for a message inside the JSON_LISTINGS_FEED with requirements LISTING_PRODUCT_ONLY.

For offers for example, you put a messageId, a sku, requirements, attributes and an operation_type. But for the operation_type, there is either delete or update options but nothing for create.
Do I have to put UPDATE ? Or can I just omit this field ?

Thanks in advance for the help

**Comment by chrisskhoury** [comment]
Hello @Liritt,

Are you relying on [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference) to fetch the latest schema depending on marketplace and product category?

After doing so, you can build and validate your schema based on the following documentation: https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#list-an-item-that-does-not-already-exist-in-the-amazon-catalog 

And to answer the question for creating a new item in the amazon catalog, you can rely on the **UPDATE** operation. 

We also have this guide to explain how to use JSON_LISTINGS_FEED to do bulk operations with a sequence diagram as well: https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#creating-and-updating-listings-items-in-bulk

Type of operation to perform for the listings data submission in this message. 

- **UPDATE**: indicates the full set of item attributes are provided and any existing attributes data will be replaced with the provided attributes. This can also be used when creating a new item.
- **PARTIAL_UPDATE**: indicates only the provided item attributes will be updated with the provided attribute data. 
- **PATCH**: indicates the provided JSON Patch operations will be used to update the applicable attributes. 
- **DELETE**: indicates the listings item will be deleted.

Thanks and I hope this answers your question:)

Chris
Solution Architect, Amazon
