### ISSUE TITLE
Programmatically refresh LWA Secret key

### ISSUE THREAD

**Issue by jhullparkseed** [amzn/selling-partner-api-models#320]
With the recent policy change by Amazon to now require the LWA Secret Key be refreshed every 180 days, is there a way to perform the refresh programmatically and is there a way to check on the expiration date of the LWA Secret key so the program can check the date and send out a warning before it expires?

Knowing it lasts only 180 days is fine, but now an alert is needed and a manual access to sellers central developer to refresh.  It would be cleaner if the program could perform the change.  I have searched and have not found documentation on being able to do this action, but maybe it is deeper in the API.

**Comment by chrisskhoury** [comment]
Hello @jhullparkseed,

We currently do not provide an API for rotating the LWA credentials programatically. 

Thank you for the feedback, we will take it into account moving forward!

Best,
Chris Khoury
Solution Architect, Selling Partner API
