### ISSUE TITLE
sendInvoice - Upload API error: Attachment with ID does not exist

### ISSUE THREAD

**Issue by Kernel1453** [amzn/selling-partner-api-models#325]
Hello Everyone,
I'm trying to send invoice via MessageAPI by using Upload API. But whatever i tried, i get this error. Could you please help what i must do to overcome this error? And please confirm that md5Content is right. You can find my php code below.

            $uploadApi = new UploadsV20201101Api($config);
            $fileContents = $request->file($fileName)->get();
          
            $filepath = $request->file($fileName)->path();
            $md5Content = base64_encode(md5_file($filepath));
            $destination = 'messaging/v1/orders/' . $amazonOrderId . '/messages/' . $messageType ?? $request->mesage_type;
            $result = $uploadApi->createUploadDestinationForResource($marketplaceIds, $md5Content, $destination);
            $resultPayload = $result->getPayload();
            $url = $resultPayload->getUrl();

            $headers = $resultPayload->getHeaders();
            $headers['Content-MD5'] =   $md5Content = base64_encode(md5_file($filepath));

            $headers['Content-Type'] = 'Binary';
            $filename = $messageType . $amazonOrderId . '.' . $request->file($fileName)->extension();
            $response = Http::attach(
                'attachment', $fileContents, $filename,$headers
            )->withHeaders($headers)
            ->put($url);

          
            $attachment = new Attachment([
                'upload_destination_id' => $resultPayload['upload_destination_id'],
                'file_name' => $filename
            ]);

Thank you very much,
Best Regards

**Comment by shreeharsh-a** [comment]
Hi,
Whats the error that you currently see? Please provide error details as well, thanks!

**Comment by shreeharsh-a** [comment]
Hi @Kernel1453
Looks like you have resolved this on your own as we have not received a response. Closing this issue but please feel free to open a new one quoting this one if you are still facing the issue & we will help you out.

Thanks!
