### ISSUE TITLE
FinanceApi error : InvalidInput

### ISSUE THREAD

**Issue by yan15195755798** [amzn/selling-partner-api-models#326]
Getting the next page always reports an error ：
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "$errorResponse.Message",
      "details": ""
    }
  ]
}
maxResultsPerPage  这个值我传了 1 - 100也解决不了

**Comment by Aayush-Kapur** [comment]
Hey @yan15195755798 , can you provide a snippet of how/where you're passing the value, so that we can understand your issue clearly.
