### ISSUE TITLE
financesV0 json

### ISSUE THREAD

**Issue by mnxk21** [amzn/selling-partner-api-models#328]
I need to use https://developer-docs.amazon.com/sp-api/docs/finances-api-reference this method, according to documents, amazon I downloaded financesV0 json, then get DefaultApi. Java but I can't through the Java program to use it. How can I use?
(ordersV0. Json, OrdersV0Api. Java can I through the build method is to use it)

**Comment by MeenaAmz** [comment]
Please use https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-java-sdk to generate the corresponding client library as per the API and then a specific api file (say orders if you use orders json) will be generated under io.swagger.client\api folder which you can use to call the API. Please try this and let us know if you run into any issues

**Comment by supoman-service** [comment]
我已经处理了Finance API的拉取账单数据。确实很复杂。
