### ISSUE TITLE
Inbound fulfillment and FBA inbound eligibility models overwrite each other during generation

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-models#34]
Since the `fulfillment-inbound-api-model/fulfillmentInboundV0.json` and `fba-inbound-eligibility-api-model/fbaInbound.json` models both use the `fbaInbound` tag, they can block each other from generating if you're autogenerating all models (as I am).

I'm generating a Java client library, and both models write to `<package>/api/FbaInboundApi.java`. Whichever model gets generated first (in my case, `fulfillmentInboundV0.json`) blocks the inbound eligibility model from generating, because the generator skips over the second model once it sees that `FbaInboundApi.java` already exists.

Here's how I'm autogenerating all models:

```bash
#!/bin/bash

# In selling-partner-api-models/
models=(models/**/*)

for model in "${models[@]}"
do
    java -jar swagger-codegen-cli.jar generate \
        --input-spec $model \
        --lang java \
        --template-dir clients/sellingpartner-api-aa-java/resources/swagger-codegen/templates \
        --output ../spapi-generated
done
```

There's an easy fix to this issue: just change the tag on one of the two models.

**Comment by gjbradleyiii** [comment]
I am having the exact same issue and agree with the proposed change.

**Comment by ericblade** [comment]
I had to make some changes to my code to rename those endpoints to handle that.
