### ISSUE TITLE
[SP-API] [Issue] Generated Java SDK Client Library - Request Headers "host" and "X-Amz-Date"

### ISSUE THREAD

**Issue by S4T-TP** [amzn/selling-partner-api-models#342]
Hello!

We are currently testing the generated Java SDK client library version 2.0. The Java SDK client library is working well, but I have one point, and I don't know if it is an issue of the Java SDK client library or an issue of documentation.

In the documentation [https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api#step-3-add-headers-to-the-uri](https://developer-docs.amazon.com/sp-api/docs/connecting-to-the-selling-partner-api#step-3-add-headers-to-the-uri) under the third step, there are mentioned four header entries (host, user-agent, x-amz-date and x-amz-access-token). But the generated Java SDK client sets only two of them, and the host and x-amz-date are not defined by the Java SDK client library.

We can confirm that the calls are working without these two headers (host and x-amz-date).

Is it an issue for the Java SDK client library, and do both headers (host and x-amz-date) have to be sent too? Or the documentation is inconsistent and has to be repaired?

**Comment by supoman-service** [comment]
Hello，我基于2.0整合了 java SDK，你可以参考一下：https://github.com/supoman-service/Amazon-SP-API-JAVA
