### ISSUE TITLE
Okhttp 2.7.5 outdated

### ISSUE THREAD

**Issue by wolfixsol** [amzn/selling-partner-api-models#349]
#126 This is still an issue. Okhttp is pinned to 2.7.5 and is EOL. Most recent version is 4.12 by now. Unfortunately there is no backwards compatibility.

From the project page since version 3.0:
> This release obsoletes OkHttp 2.x, and all code that uses OkHttp’s com.squareup.okhttp package should upgrade to the okhttp3 package. Libraries that depend on OkHttp should upgrade quickly to prevent applications from being stuck on the old version.

**Comment by harguph** [comment]
Hi,

Thank you for bringing this up, we have created a backlog item for consideration with the relevant team.
