### ISSUE TITLE
ProductPricingV0: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY

### ISSUE THREAD

**Issue by dfreudenberger** [amzn/selling-partner-api-models#355]
I'm working with Amazon's SP-API SDK to pull item offers using the Product Pricing V0 API.

However, when I make a batch request and any of the batched requests returns an error, the `getItemOffersBatch` method throws an IllegalStateException. Ideally, I'd like the request to go through, and for the response list to include a `GetOffersResponse` object filled with any errors that happened.

Please find attached one of the responses that will lead to the mentioned exception.

```json
{
  "responses": [
    {
      "headers": {
        "x-amzn-RequestId": "f53e7f5f-61b8-4a2b-8d2e-028809d6eb84",
        "Date": "Tue, 19 Mar 2024 17:02:02 GMT"
      },
      "status": {
        "statusCode": 400,
        "reasonPhrase": "Bad Request"
      },
      "body": {
        "errors": [
          {
            "message": "B00ZUXG6GY is an invalid ASIN for marketplace A1PA6795UKMFR9",
            "details": "",
            "code": "InvalidInput"
          }
        ]
      },
      "request": {
        "MarketplaceId": "A1PA6795UKMFR9",
        "ItemCondition": "Used",
        "Asin": "B00ZUXG6GY"
      }
    }
  ]
}
```

Swagger codegen generates the following classes (stripped down to what is important) from the v0 model.

```java
public class GetOffersResponse {
  @SerializedName("payload")
  private GetOffersResult payload = null;

  @SerializedName("errors")
  private ErrorList errors = null;
}

public class ErrorList {
  @SerializedName("errors")
  private List<Error> errors = new ArrayList<>();
}

public class Error {
  @SerializedName("code")
  private String code = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("details")
  private String details = null;
} 
```

**Comment by shreeharsh-a** [comment]
Hi @dfreudenberger 

Looks like `B00ZUXG6GY` is an invalid ASIN for marketplace `A1PA6795UKMFR9` please cross check this ASIN & marketplace once. If you still continue to face issues please create a developer support case so that we can better help you via calls etc.

Thanks!
