### ISSUE TITLE
Embarrassingly bad error message for GET inventory summaries

### ISSUE THREAD

**Issue by simeyla** [amzn/selling-partner-api-models#358]
I got this error message for `/fba/inventory/v1` for `summaries`

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Query startDateTime cannot not be earlier than 19",
      "details": ""
    }
  ]
}
```

Read it out loud.
Slowly.

**Comment by rugved1991** [comment]
Hi @simeyla,

Thanks for sharing the error message. Can you please also share the complete request URL that caused this error? I am unable to replicate this issue on my end.
If you could share the exact URL that is causing the issue, we can reach out to the backend teams to get this fixed.

Best,
Rugved
Solutions Architect, SP-API

**Comment by simeyla** [comment]
Appreciate the quick reply.

It seems the issue was when using a value older than 18 months for `startDateTime` (I use the C# API)

     startDateTime = DateTime.Now.AddYears(-2)

Making it null uses the default maximum of 18 months in the past.

So the error message should say something like: 'startDateTime must be within the past 18 months, or null to use the maximum range'. And not with a double negative!
