### ISSUE TITLE
Feature Request: Option to Exclude PAN-European Inventory in getInventorySummaries operation

### ISSUE THREAD

**Issue by PoneraLucas** [amzn/selling-partner-api-models#360]
Hello,

We have been trying to use the "getInventorySummaries" operation to retrieve our stock across differents Marketplaces in real-time.
However, it is currently not possible because this operation returns a sum of inventory quantities from all the EU marketplaces.
We've since been trying to do it using inventory report but they only get updated every 30 minutes so it is not ideal.

We think maybe add a parameter to the getInventorySummaries operation that would return only local fulfillment quantities?
Or create a new operation that would do that?

We think this would help a lot of people tring to get their stocks quantities right.

**Comment by shreeharsh-a** [comment]
Hi,
You can also get inventory summaries for specified seller SKUs (up to 50) by supplying the _sellerSkus_ parameter for e.g.:

GET https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?details=true&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&sellerSkus=msku314best%2Cmsku271good&marketplaceIds=ATVPDKIKX0DER

For more details please see docs: https://developer-docs.amazon.com/sp-api/docs/fba-inventory-api-v1-use-case-guide#tutorial-get-inventory-summaries-for-the-specified-seller-skus

Please see if this works for you.

Thanks!
