### ISSUE TITLE
AnyOfferChangedNotification has no `IsBuyBoxWinner` field

### ISSUE THREAD

**Issue by AlexeyKosov** [amzn/selling-partner-api-models#362]
The `IsBuyBoxWinner` field is missing in AnyOfferChangedNotification.json
It should be under `Payload / AnyOfferChangedNotification / Offers / OfferItem`

**Comment by shreeharsh-a** [comment]
Hi,
Per the [docs](https://developer-docs.amazon.com/sp-api/docs/notification-type-values#offer) the `IsBuyBoxWinner` field is an optional field & may not be included if its value is not set.

Thanks!
