### ISSUE TITLE
FinancesAPI - Intermittent Invalid Input Errors

### ISSUE THREAD

**Issue by Aseelaldallal** [amzn/selling-partner-api-models#366]
Making a request to GET /finances/v0/financialEventGroups/{eventGroupId}/financialEvents
occasionally returns 
```
{ 
code: "InvalidInput"
details: ""
message: "Request was not valid or data requested exceeds data retention period."
}
```

Retrying the exact same request a second later returns a valid response.

**Comment by shreeharsh-a** [comment]
Hi @Aseelaldallal 
Please reach out to developer support so that we can analyze your calls & help you out with more details / information as to why this might be occurring, thanks!
