### ISSUE TITLE
No `MyOffer` field in any offer response.

### ISSUE THREAD

**Issue by gabrielpiassetta** [amzn/selling-partner-api-models#369]
Hi,

I need to know which offer on the Offers list is mine, for that, we have this `MyOffer` field which should come in the response JSON, but I can't manage to get it, no matter what I do.

I think this isn't clear how the (optional) fields on the response JSON works, seems to me that optional is something that is optional to me to send, the response JSON should be deterministic, I must know the format I will receive before the actual request.

How can I confirm that the `MyOffer` field will be in the response?

https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#offerdetail

**Comment by shreeharsh-a** [comment]
This is a very old issue that is probably not getting as much attention as it deserves. We encourage you to check if this is still an issue after the latest release and if you find that this is still a problem, please feel free to open a new issue and make a reference to this one.

**Comment by johnkw** [comment]
This is still broken. Please reopen these tickets that are not fixed.  Please do not close issues until they're actually fixed. It's extremely counterproductive and confusing.  It becomes harder to find the discussion on these critical issues that are still open.  And it becomes harder to keep track of which things have been previously reported as bugs.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
