### ISSUE TITLE
getshipmentsresult returns NextToken even if there are no more results in the NextToken call

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#370]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getshipmentsresult

This seems to be a bug in the server API, but maybe it is intentional and should be addressed in documentation?

Right now NextToken says "When present and not empty, pass this string token in the next request to return the next response page."  However, it seems that "NextToken" is always returned, even if the "ShipmentData" section only has a single record.  The subsequent call using "NextToken" just returns an empty '{"ShipmentData": []}' response.  It's bizarre though to provide NextToken when there are no more records, as it forces the client to do another call just to make sure, which is a waste of bandwidth.

**Comment by shreeharsh-a** [comment]
This is a very old issue that is probably not getting as much attention as it deserves. We encourage you to check if this is still an issue after the latest release and if you find that this is still a problem, please feel free to open a new issue and make a reference to this one.

**Comment by johnkw** [comment]
This is still the latest release. See https://github.com/amzn/selling-partner-api-models/issues/556#issuecomment-2127634337

Please do not close issues until they're actually fixed. It's extremely counterproductive and confusing. It becomes harder to find the discussion on these critical issues that are still open.

**Comment by cpiggott** [comment]
> This is still the latest release. See https://github.com/amzn/selling-partner-api-models/issues/556#issuecomment-2127634337
> 
> 
> 
> Please do not close issues until they're actually fixed. It's extremely counterproductive and confusing. It becomes harder to find the discussion on these critical issues that are still open.

Can't hit ticket quotas if they don't randomly close out old tickets... 

Often how it feels with this repo...

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.

**Comment by emakunin** [comment]
2024, the bug is still there. BTW the `getShipmentItemsByShipmentId` schema even does not QueryType/nextToken param. Should I expect the items are always returned in 1 reply? (sor far worked for me but I didn't ship more than ±20 different SKUs)

**Comment by kpconnell** [comment]
confirm still a bug

**Comment by PhilJeffcock** [comment]
Still a bug. Just had its 5 anniversary.

**Comment by johnkw** [comment]
The documentation is now at https://developer-docs.amazon.com/sp-api/reference/getshipments and still doesn't mention this.  It still says:
> When present and not empty, pass this string token in the next request to return the next response page.

But should mention that it will be returned even when there are no more actual pages of response to get.

It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.  Although presumably search engines still are finding this, since people keep coming here.

**Comment by jtbiron** [comment]
Why was this closed but never fixed? It's clearly not working properly.

**Comment by emakunin** [comment]
It's to raise the bar in customer obsession :)

**Comment by kpconnell** [comment]
Just a bit of side commentary - 

when you look at upcoming API fees...  and the historical "support" for these types of issues... which is an obvious bug, amongst 100's of others that never get addressed, even in MWS days, decades old bugs..

what is the conclusion?
