### ISSUE TITLE
GET Labels for shipment

### ISSUE THREAD

**Issue by tokicnikolaus** [amzn/selling-partner-api-models#371]
I have no previous experience with Amazon MWS so maybe I'm not understanding the whole process flow. Now I'm trying to get labels for shipments I manually created over the Seller Central UI. Shipments I created are successfully fetched (Operation: getShipments) and now I have issue when getting the labels.

Here is my error response from API:
```
{'errors': [{'code': 'InvalidInput',
   'message': 'Provided SellerCartonIds are not valid: [[FBAxxxxxxxxxU000001]] for Shipment: [FBAxxxxxxxxx]',
   'details': ''}]}
```
If I print labels from UI FBAxxxxxxxxxU000001 label is printed in pdf - also found out about naming [here](https://stackoverflow.com/questions/56249677/getuniquepackagelabels-doesnt-use-cartonid-from-post-fba-inbound-carton-conten)

In general, I don't know where to find parameter of package labels `PackageLabelsToPrint` from [GetLabelDocs](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getlabels) also I'm not sure if this parameter is same as `cartonIdList` parameter?

Here are data if you don't provide `PackageLabelsToPrint` (in docs [not required!](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getlabels) ) query param in request:
Headers and url:
```
url : 'https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA1xxxxx/labels?PageType=PackageLabel_A4_2&LabelType=UNIQUE'
{
	'User-Agent': 'python-requests/2.25.1 auth-aws-sigv4/0.6',
	'Accept-Encoding': 'gzip, deflate',
	'Accept': '*/*',
	'Connection': 'keep-alive',
	'x-amz-access-token': 'Atza|Ixxxxw',
	'Host': 'sellingpartnerapi-eu.amazon.com',
	'X-AMZ-Date': '20210122T130603Z',
	'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
	'X-Amz-Security-Token': 'xxxx',
	'Authorization': 'AWS4-HMAC-SHA256 Credential=Axxx/20210122/eu-west-1/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token, Signature=c580d12b684bcaf54c9076afaa01441f17cab301ba8af360a99b38717aec554c'
}
```
```
response:
{'errors': [{'code': 'InvalidInput',
   'message': "1 validation error detected: Value null at 'cartonIdList' failed to satisfy constraint: Member must not be null",
   'details': ''}]}
```
I spent a LOT of time on this already and it gets a bit annoying!

Thanks!

**Comment by shreeharsh-a** [comment]
This is a very old issue that is probably not getting as much attention as it deserves. We encourage you to check if this is still an issue after the latest release and if you find that this is still a problem, please feel free to open a new issue and make a reference to this one.

**Comment by johnkw** [comment]
This is still the latest release. See https://github.com/amzn/selling-partner-api-models/issues/556#issuecomment-2127634337

Please do not close issues until they're actually fixed. It's extremely counterproductive and confusing. It becomes harder to find the discussion on these critical issues that are still open.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
