### ISSUE TITLE
"Invalid Input" is not a reasonable error message under any circumstance

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#372]
I'm not sure where this belongs, but what does "InvalidInput" "Invalid Input" mean?  If I do any POST to /fba/inbound/v0/plans with a body, then the response is:

`{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}`

(If there's no HTTP body then the response is different: `{
  "errors": [
    {
      "code": "InvalidInput",
      "message": " Reason: Country field is missing, Name field is missing, AddressLine1 field is missing.",
      "details": ""
    }
  ]
}
`)

Currently the https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#createinboundshipmentplan documentation doesn't really address 400 errors. It just says "Request has missing or invalid parameters and cannot be parsed."  But, "invalid" in what way?

The API needs to be MUCH more specific regarding what it thinks is "Invalid Input" in that error message.  Perhaps the documentation could get examples as well though.

On a related note, any additional tips on actually getting /fba/inbound/v0/plans to work would be helpful.

**Comment by shreeharsh-a** [comment]
This is a very old issue that is probably not getting as much attention as it deserves. We encourage you to check if this is still an issue after the latest release and if you find that this is still a problem, please feel free to open a new issue and make a reference to this one.

**Comment by johnkw** [comment]
This is still the latest release. See https://github.com/amzn/selling-partner-api-models/issues/556#issuecomment-2127634337

Please do not close issues until they're actually fixed. It's extremely counterproductive and confusing. It becomes harder to find the discussion on these critical issues that are still open.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by menporulporiayalan** [comment]
I have received the same error while calling the finances API. I searched all around the internet and  I found this in the Amazon sp API documentation.  I guess this will be helpful for some. 

> The maximum number of results to return per page. If the response exceeds the maximum number of transactions or 10 MB, the API responds with 'InvalidInput'.
> Minimum : 1
> Maximum : 100
