### ISSUE TITLE
Is "array" in a Type Query parameter always a comma-separated unquoted string?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#374]
This occurs perhaps hundreds of times in the documentation, but see for example ShipmentStatusList in: 
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getshipments

It says `< enum (ShipmentStatusList) > array` but there's no explanation of how to encode the array. It turns out what it wants is a comma-separated string with no quotation marks. It does NOT allow for an actual URL-encoded JSON array (which is seemingly what the API always uses in the body of a REST call). Also quotation marks are seemingly banned as well, ie the following doesn't work:

`...&QueryType=SHIPMENT&ShipmentStatusList=%27WORKING%27%2C%27SHIPPED%27%2C%27RECEIVING%27%2C%27ERROR%27%2C%27IN_TRANSIT%27`

What it does want is something like:

`...&ShipmentStatusList=WORKING%2CSHIPPED%2CRECEIVING%2CERROR%2CIN_TRANSIT`

Every time the documentation uses the word "array" for a Query, it should link to a section describing what the means. Is it always a comma-separated list? If not, what are the other ways in which an "array" Query is specified?

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
