### ISSUE TITLE
How to get shipment events for an inbound?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#375]
The information in the "Shipment events NEW!" tab of the shipment on Seller Central has a timeline of critical information, such as:
- when BOL was generated
- when Amazon Partnered Carrier picked up
- when delivered to the fulfillment center
- when fulfillment center plans to get it from the fulfillment center parking lot and start unloading

I can't find any mention of this in the API documentation, so it's possible the API currently lacks access to all of this entirely?  It would certainly be good to add to the API so we don't have to go back to Seller Central to find this critical part of the workflow. Either way it, should be documented on https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
