### ISSUE TITLE
Document actual contents of reports

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#378]
Document actual contents of reports.

If you go to https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md it lists reports, but doesn't document them at all.

I just stumbled upon https://sellercentral.amazon.com/gp/help/help-page.html?itemID=201074420 which documents many reports.  (It would probably be good if the SP-API documentation just linked directly to those sellercentral documentation pages, rather than duplicating that documentation.)

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this issue to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.

**Comment by johnkw** [comment]
Can we convert this to a "discussion" or whatever to keep it open?

**Comment by nrcjea001** [comment]
+1
