### ISSUE TITLE
Where is the Shipment reconcile date in the API?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#379]
I don't see the word "reconcile" anywhere on https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md

I'm not sure if this is a documentation oversight or if it's actually missing from the API entirely.

The date I'm referring to is on this page: https://sellercentral.amazon.com/gp/fba/inbound-shipment-workflow/index.html/ref=ag_fbaisw_name_fbasqs#FBAXXXXXXXXX/summary/discrepancies

The date changes frequently, seemingly at random, so it seems impossible for the user to calculate it. It would need to be provided by the API, but it's not in the `InboundShipmentInfo` object, where I was expecting it to be.

**Comment by shreeharsh-a** [comment]
Thank you for bring this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
