### ISSUE TITLE
AES 256 Encryption for upload document through Feeds API

### ISSUE THREAD

**Issue by mashhood1995** [amzn/selling-partner-api-models#38]
Hi , I am trying to connect with feeds api for uploading inventory information. **I am successfully able to retrieve key and initializationVector .**  But when i use those keys in   [online tool](https://www.devglan.com/online-tools/aes-encryption-decryption) for AES encryption . I get this error "Length of secret key should be 32 for 256 bits key size" . When i  try [aes js library](https://github.com/ricmoo/aes-js) in my javascript code , I get the this error 
"_Error: invalid initialation vector size (must be 16 bytes)_".
I have tried different things e.g decoded key and initialation  from base64 to utf-8 ,base64 to hex etc but it doesn't work and i get same error . Does anyone know what is the issue ? Am i missing out something ?

**Comment by esalesplatform** [comment]
You must convert initializationVector string from base64 string to byte array. And use it for encryption.

**Comment by mashhood1995** [comment]
Thanks . What about key ? shall i convert that to byte array as well ?

**Comment by esalesplatform** [comment]
sure. in the same way, from base64 string to byte array.

**Comment by esalesplatform** [comment]
I can`t say something about XML, since I using CSV files.
After uploading encrypted CSV file (I also using PUT Http request type for that) - I getting empty response and this is fine.
After that - I do CreateFeed using FeedDocumentId which I got from CreateFeedDocument request.

**Comment by MrYing** [comment]
@esalesplatform  Thanks
