### ISSUE TITLE
Where is the report with "Offer Start Date" for a listing?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#380]
Where is the report with "Offer Start Date" for a listing?  I would expect this to be part of `GET_MERCHANT_LISTINGS_ALL_DATA`, but it's not there.

There are some other key fields like "Max Order Quantity", and sales/MSRP fields, that I would have expected in that same report, but I can't find any of them.

(See also bug amzn/selling-partner-api-models#378.)

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this issue to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
