### ISSUE TITLE
Why is `MarketplaceId` required when `NextToken` is provided for getshipments?  

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#381]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getshipments

Why is `MarketplaceId` required when `NextToken` is provided for getshipments?  As a user this seems to be very strange behavior.  `NextToken` is supposed to just be a continuation of retrieving results from the previously specified query.  What would it mean to change the `MarketplaceId` in the middle of getting `NextToken` records?  It seems to be completely nonsensical to change `MarketplaceId`, and if so, then it shouldn't be an allowed parameter at all. `NextToken` should simply have the marketplace information embedded in it.

Surely it seems the SP-API should remove the requirement to send `MarketplaceId` for a `NextToken` request.  But if not, it should be documented that `MarketplaceId` must remain the same, or if not, what the consequence is of it not remaining the same.

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.

**Comment by shreeharsh-a** [comment]
Thanks @johnkw but it wont be possible for us to track / update issues related to SP API here as its manage by another team. Please reach out to developer support for latest etc on the issue raised. However, any issues raised that's related to the content published in this repo will be tracked to closure.

**Comment by johnkw** [comment]
Seller Support does not have a publicly-visible bug-tracking system, so that's not of any help.  This is or was the only publicly-visible bug-tracking system for SPAPI.

Whether the SPAPI team is managing these bugs or not, open bugs should remain open so that it's easy to find information on the bug. Closing them is horribly counterproductive.

While they still show up in Google, they're harder to find in Github when "closed".
