### ISSUE TITLE
/fba/inbound/v0/shipments/?/labels has 4 documented fields which seem to not actually exist

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#382]
Currently the documentation https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getlabels states that `PackageLabelsToPrint` is optional. As mentioned in bug amzn/selling-partner-api-models#371 already, this is not the case - it is a required field.  If you don't provide it, you get the incorrect and confusing error message `"1 validation error detected: Value null at \u0027cartonIdList\u0027 failed to satisfy constraint: Member must not be null"`.

Confusingly the following parameters are all ignored:
```
NumberOfPackages
NumberOfPallets
PageSize
PageStartIndex
```

I suspect the documentation of those 4 is an error, and `/fba/inbound/v0/shipments/?/labels` is just ignoring them entirely. It weirdly also ignores all other parameters. For example if you specify `ABCDEF=1`, in addition to a valid value for `PackageLabelsToPrint`, then you get back a PDF as normal. Specifying undocumented parameters should always result in an error message to help detect typos.

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
