### ISSUE TITLE
How to retrieve Seller Profile information from Selling Partner API?

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-models#383]
According to documentation only thing that is related to Seller profile is `selling_partner_id`. For Advertising API it is possible to retrieve Profile, how can I do something similar for Selling Partner API?

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
