### ISSUE TITLE
[BUG] 400 Bad Request when using NextToken on listFinancialEventGroups

### ISSUE THREAD

**Issue by cgaugel** [amzn/selling-partner-api-models#384]
I recieve an 400 Bad Request response, when calling the /finances/v0/financialEventGroups endpoint.

The request is submitted as described in the documentation. I already submitted an CaseID: 6902927832

Please fix this as soon as possible. Your API is still full of bugs and we have to pay for it.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by joeybab3** [comment]
While I agree this issue should be closed since it became a catch-all of unrelated 400 errors can you provide a link for where we can go to contact developer support?

> Please reach out to developer support so that we can better help you with issues related to SP API.
> 
> `Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by shreeharsh-a** [comment]
Sure, here's the link for developer support: https://developer.amazonservices.com/support
