### ISSUE TITLE
Can't get labels if Shipment has more than 1000 "cartons"

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#387]
As noted in bug amzn/selling-partner-api-models#371 the current label printing is not well-documented, and as also noted in bug amzn/selling-partner-api-models#1114 the system crashes with no error message if you try to print too many at once. However it is possible normally to work around those issues and get the labels for a shipment.

There is a new issue though that seems to prevent getting labels entirely.  If there are more than 1000 "cartons" in the shipment, no label can be downloaded for any of the cartons.

In Seller Central, the Shipment is in a strange state as well. The carrier information only shows 1000 under "# of boxes" even though the "1. Review shipment contents" section at the top of the page correctly shows 1092 units or whatever.

Also weirdly the "# of boxes" under the "Box labels" section is pre-selected with 1000 as well, meaning if you click "Generate box labels", you'll actually only get the first 1000 boxes, and the remainder are left off. You can edit it manually to get all the boxes, but it prints them in groups of 1000.

There seems to be some sort of undocumented magic 1000 number that impacts several different things here.  It would be good to document that, or just fix it so the limit is no longer there.  However, there's also a bug it seems for label downloading that means that API can't create orders over 1000 units without manually getting the labels via Seller Central's awkward interface.

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
This appears to be fixed now!
