### ISSUE TITLE
Is "Payments Transactions View" in SP-API, or is it missing?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#389]
As previously mentioned in bug amzn/selling-partner-api-models#378 there isn't much documentation on reports currently.  But one I'm urgently looking for is "Payments Transactions View" which is documented here in general: https://sellercentral.amazon.com/gp/help/200141650?language=en_US&ref=ag_200141650_cont_201074420

Is there a corresponding SP-API report, and if so, what is it?

Nothing on https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md stands out as obviously it to me.

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.

**Comment by ronen-taktook** [comment]
I definitely agree with @johnkw
Open the issue until you fix it
Or give us a link so we can see the status

**Comment by shreeharsh-a** [comment]
@ronen-taktook Please be advised that only issues related to the content published on this repo will be tracked to closure here.

**Comment by johnkw** [comment]
Ok but keep in mind that no one cares about "selling-partner-api-models" or whatever this repo is about now. Everyone only cares about the API being functional.  Can this open bug report be moved/transformed to a "discussion"?
