### ISSUE TITLE
How to use Uploads and Messaging APIs?

### ISSUE THREAD

**Issue by fengmiq** [amzn/selling-partner-api-models#39]
1.I use https://sellingpartnerapi-na.amazon.com/messaging/v1/orders/xxx/messages/confirmCustomizationDetails?marketplaceIds=ATVPDKIKX0DER,send message fail,error:
Client error: POST https://sellingpartnerapi-na.amazon.com/messaging/v1/orders/xxxxx/messages/confirmCustomizationDetails?marketplaceIds=ATVPDKIKX0DER resulted in a 403 Forbidden response: { "errors": [ { "code": "Unauthorized", "message": "Invalid amazonOrderId and template combination.", (truncated...)

METHOD:POST
BODY:{"text":"test message"}
2.
POST https://sellingpartnerapi-na.amazon.com/uploads/2020-11-01/uploadDestinations/messaging resulted in a 403 Forbidden response: { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "det (truncated...)

url:/uploads/2020-11-01/uploadDestinations/messaging
method:POST
request is:
array:3 [▼
"query" => array:2 [▼
"marketplaceIds" => "ATVPDKIKX0DER"
"contentMD5" => "c72b9698fa1927e1dd12d3cf26ed84b2"
]
"headers" => array:1 [▼
"x-amz-access-token" => "Atza|IwEBIOinGtHdX9lGS0NGVYDKL3ZG9w4YJEDelbkLwdUk59nrl1UpjW4D_flZoFoq9_z_H_ic-f-8z0MKgQmJJcumDDlC_0xPApsD9fjg4tJKBVLKuJaZZTePWoEpk9nCw2JBs8V2L9LT9sx5ZNgrph7kTSW ▶"
]
"synchronous" => true
]

**Comment by LeanCai** [comment]
@fengmiq 我也遇到和你一样的问题，你的接口调通了吗？有没有qq联系一下。

**Comment by LeanCai** [comment]
@fengmiq 我已经解决了问题，接口没问题，与这个订单状态有关系

**Comment by Adrian-T-AMZN** [comment]
Hello @[fengmiq](https://github.com/fengmiq),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Adrian T.
Selling Partner API Developer Support
