### ISSUE TITLE
Need documentation of datestringtype

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#390]
It was originally noted as early as Bug amzn/selling-partner-api-models#996 that datestringtype is undocumented.

At https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#datestringtype its format should be described. Possibly it's YYYY-MM-DD, for example.

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
