### ISSUE TITLE
Need Clarification on Carton Information Submission for Labels in Fulfillment Inbound API v2024-03-20

### ISSUE THREAD

**Issue by zaki-siddiqui** [amzn/selling-partner-api-models#3908]
I am currently using the Fulfillment Inbound API v2024-03-20 to receive labels from the getLabel operation. Do I still need to provide carton information via the Carton Information Feed (POST_FBA_INBOUND_CARTON_CONTENTS), or does the new API have an alternative method for submitting carton information to get labels?

**Comment by KirillChekalin** [comment]
Hi,

The operation getLabel is actually part of the Fulfillment Inbound API v0, not the Fulfillment Inbound API v2024-03-20.

For the new API, you might try using the setPackingInformation operation to submit carton information, which should then allow you to receive labels. This operation is designed to handle packing details and is likely what you need for your current requirements.

Additionally, you will need to follow all the necessary steps in the workflow for the Fulfillment Inbound API v2024-03-20 to ensure everything is set up correctly.

**Comment by zaki-siddiqui** [comment]
@KirillChekalin 
Oh, I see. Thank you for your reply, it has clarified some of my doubts.

**Comment by harguph** [comment]
Closing this.

Please feel free to open a new issue for any more queries.
