### ISSUE TITLE
Amazon SP-API "GET_FLAT_FILE_SALES_TAX_DATA "

### ISSUE THREAD

**Issue by michelexport** [amzn/selling-partner-api-models#3909]
We activated **GET_FLAT_FILE_SALES_TAX_DATA** and what we get is what is downloadable manually from amazon seller central, report
"**Sales Tax Calculation Report**". This report only contains orders where "Tax_Collection_Responsible_Party = Seller" though.

We need to pull down via API even:
"**Combined Sales Tax Report**" since it includse orders where "Tax_Collection_Responsible_Party=Amazon" as well.

Solution anyone?
Quite urgent, thanks a lot!

**Comment by shreeharsh-a** [comment]
Hi @michelexport,
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
