### ISSUE TITLE
Feature Request - Allow REST Post to replace feed type POST_FBA_INBOUND_CARTON_CONTENTS

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-models#391]
In my client's inbound shipping workflow, this step takes by far the longest and is critical path to getting labels.  The data volumes for most shipments are very small and a REST API  to be able to directly Post contents would be a huge improvement.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
