### ISSUE TITLE
Issue with Amazon Partnered SPD Carrier in Fulfillment Inbound API v2024-03-20

### ISSUE THREAD

**Issue by KirillChekalin** [amzn/selling-partner-api-models#3910]
Hi everyone,

I am currently working with the Fulfillment Inbound API v2024-03-20 and have encountered a very strange issue during the creation of a shipment plan.

Problem Description:
When I set Amazon Partnered SPD as the carrier, I face the following problems:

Seller Central Issue: After setting Amazon Partnered SPD as the carrier, I am unable to make any further changes to the shipment plan on the Amazon Seller Central website (sellercentral.amazon.com). Even the cancel button is disabled.
Placement Option Resets: The placement option I selected earlier gets reset.
No API Errors: I do not receive any errors during the creation of the shipment plan via the API.
Observations:
When I choose a non-Amazon partnered carrier, everything works correctly, and I can manage the shipment plan without any issues on Seller Central.
This issue seems to be specifically tied to selecting Amazon Partnered SPD as the carrier.
Question:
Has anyone else encountered a similar issue? If so, how did you resolve it? Any insights or suggestions would be greatly appreciated.

Thank you!

Before
<img width="1656" alt="Before" src="https://github.com/amzn/selling-partner-api-models/assets/44983843/4a40055b-341d-446f-87d6-2e3ba163de60">
After
<img width="1029" alt="After" src="https://github.com/amzn/selling-partner-api-models/assets/44983843/28c9e8f0-89ff-4d50-a350-0acc25ef0120">

**Comment by garply1** [comment]
This is happening to us also. Also notice that once you confirm your placement options with partnered carrier small parcel it flipped your shipping method to LTL - see the pic you posted. It is garbage and Amazon knows it. Yet they put a deadline on some crap they don't even have close to ready. It boils down to they are so big they simply don't care.  Great developer support!

**Comment by shreeharsh-a** [comment]
Hi @KirillChekalin,
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by malekashkar** [comment]
I guess were never going to get an update on this?

**Comment by gu-te** [comment]
Is there a solution?
