### ISSUE TITLE
Unable retrieve asin options

### ISSUE THREAD

**Issue by quanlndzt** [amzn/selling-partner-api-models#3913]
Hey team, I spend a lot of time to get options of specific asin in [developer-docs.amazon.com](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference)
But I can't find any docs contain asin options.
I try use `LISTINGS` , `PRODUCT PRICING API` , `CATALOG ITEMS API` but can' t retrieve options info

Please help me to get it
Thanks

**Comment by quanlndzt** [comment]
The asin options
![image](https://github.com/amzn/selling-partner-api-models/assets/167730783/f99e4308-f5c9-4ec6-933c-422441f1c02d)

**Comment by shreeharsh-a** [comment]
Hi @quanlndzt 
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
