### ISSUE TITLE
[BUG] Documentation - Incorrect content type

### ISSUE THREAD

**Issue by sherlock270** [amzn/selling-partner-api-models#392]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
The incorrect content type is listed under "Consumes" for the patchListingsItem operation under the listings items api

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md#consumes-3

**Description of what the documentation currently says**
Documentation says the operation consumes` application/json`

**Description of what the documentation should say**
Documentation should state the operation consumes `application/json-patch+json` per [IETF](https://datatracker.ietf.org/doc/html/rfc6902#section-6)

**Additional context**
The operation returns an `InvalidInput` error when using `application/json` content type. The operation works correctly when using the `application/json-patch+json` content type

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
