### ISSUE TITLE
[BUG] [SP-API] [Issue] createInboundPlan requires phoneNumber

### ISSUE THREAD

**Issue by 111L12** [amzn/selling-partner-api-models#3931]
createInboundPlan didn't used to require a phone number as part of the sourceAddress. The documentation doesn't mention phoneNumber at all for the "sourceAddress" https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#createinboundplanrequest
![Uploading {6C122C9C-6632-45B4-9546-70B2ACBECB2D}.png…]()

**Comment by 111L12** [comment]
> 不是 sourceAddress.phoneNumber 而是 contactInformation.phoneNumber

I know, but the interface returned in 400 suggest is sourceAddress phoneNumber, my sourceAddress phoneNumber in value, there is

**Comment by 111L12** [comment]
![Uploading {6C122C9C-6632-45B4-9546-70B2ACBECB2D}.png…]()

**Comment by 111L12** [comment]
> 不是 sourceAddress.phoneNumber 而是 contactInformation.phoneNumber

 "errors": [
    {
      "code": "InvalidInput",
      "message": "1 validation error detected: Value null at \u0027request.sourceAddress.phoneNumber\u0027 failed to satisfy constraint: Member must not be null",
      "details": ""
    }
  ]
This is the return value

**Comment by 111L12** [comment]
> > > 不是 sourceAddress.phoneNumber 而是 contactInformation.phoneNumber
> > 
> > 
> > “errors”： [ { “code”： “InvalidInput”， “message”： “检测到 1 个验证错误：\u0027request.sourceAddress.phoneNumber\u0027 处的值为 null\u<> 无法满足约束：成员不得为空”， “details”： “” } ] 这是返回值
> 
> 可能提示语错了。你传一下contactInformation.phoneNumber就不会报错了

Request contactInformation. PhoneNumber is value

**Comment by 111L12** [comment]
> > > 不是 sourceAddress.phoneNumber 而是 contactInformation.phoneNumber
> > 
> > 
> > “errors”： [ { “code”： “InvalidInput”， “message”： “检测到 1 个验证错误：\u0027request.sourceAddress.phoneNumber\u0027 处的值为 null\u<> 无法满足约束：成员不得为空”， “details”： “” } ] 这是返回值
> 
> 可能提示语错了。你传一下contactInformation.phoneNumber就不会报错了

When sending a request, contactInformation.PhoneNumber has value

**Comment by 111L12** [comment]
> > > 不是 sourceAddress.phoneNumber 而是 contactInformation.phoneNumber
> > 
> > 
> > “errors”： [ { “code”： “InvalidInput”， “message”： “检测到 1 个验证错误：\u0027request.sourceAddress.phoneNumber\u0027 处的值为 null\u<> 无法满足约束：成员不得为空”， “details”： “” } ] 这是返回值
> 
> 可能提示语错了。你传一下contactInformation.phoneNumber就不会报错了

You can see what's going on at this address: https://github.com/amzn/selling-partner-api-models/issues/654 I'm having the same problem as him.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
