### ISSUE TITLE
Fulfillment Inbound API 2024-03-20: List Packing Group Items - 403 Unauthorized

### ISSUE THREAD

**Issue by brandondev1** [amzn/selling-partner-api-models#3937]
The API is returning a 403 for all requests regardless of sending valid access token.

**Comment by shreeharsh-a** [comment]
@puppsupr

**Comment by akowi-mmueller** [comment]
They changed the parameters, it is `/packingGroups/{packingGroupId}/items ` now

**Comment by brandondev1** [comment]
> They changed the parameters, it is `/packingGroups/{packingGroupId}/items ` now

Are you saying they changed something recently (over the weekend)?  The same request I sent on Friday last week, returns a 403 this week.

**Comment by shreeharsh-a** [comment]
@MeenaAmz

**Comment by puppsupr** [comment]
Hi,
We have a [new release](https://developer-docs.amazon.com/sp-api/changelog/new-fulfillment-inbound-api-v2024-03-20-june-release) and change in the [model](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-model). Please try to import the new model and retry.
