### ISSUE TITLE
POST_FLAT_FILE_LISTINGS_DATA Documentation

### ISSUE THREAD

**Issue by DmytroShumeyko** [amzn/selling-partner-api-models#3943]
Hello! I can't find documentation about POST_FLAT_FILE_LISTINGS_DATA details:

1. I'm looking for a description of these attributes: https://developer-docs.amazon.com/sp-api/docs/listings-feeds-attributes#post_flat_file_listings_data
2. I'm looking for documentation on which fields are required to add products directly to a merchant's FBA inventory. If it was possible using the same MWS report, I believe I can do the same using this one.

Thanks for your help.

**Comment by shreeharsh-a** [comment]
@MeenaAmz
