### ISSUE TITLE
Fulfillment Inbound API 2024-03-20: java generateTransportationOptions SDK  readyToShipWindow ISO 8601

### ISSUE THREAD

**Issue by shadowJourney** [amzn/selling-partner-api-models#3948]
This API interface has one parameter

            "readyToShipWindow": {
                "start": "2024-06-17T00:00:00.000Z"
            }
This is the required format

But the API data format in the java SDK package corresponds to the OffsetDateTime class.

This is where the question arises... If the end of the time format is not 00:00.000Z 
will simply return an error:
ERROR: DateTime value \'2024-06-17T00:00:00.029Z\' must have 00:00 for its time component.

If it's 00:00.00.000Z. 

![image](https://github.com/amzn/selling-partner-api-models/assets/112471375/7c641fb5-b021-4afd-b20b-4fd070c15daa)

This type of problem can lead to the problem of not displaying the 00:00.000Z directly after it.

ERROR: DateTime value \'2024-06-17T00:00:00Z\' is not in a valid ISO 8601 format. The expected ISO 8601 format is yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'\

Is the tech team toying with us?

**Comment by mikhaill** [comment]
I struggled with this one for a bit too. What they are looking for is:

yyyy-MM-ddTHH:mm:ss.sssZ

https://developer-docs.amazon.com/sp-api/docs/iso-8601

**Comment by shadowJourney** [comment]
> I struggled with this one for a bit too. What they are looking for is:
> 
> yyyy-MM-ddTHH:mm:ss.sssZ
> 
> https://developer-docs.amazon.com/sp-api/docs/iso-8601

I know this problem because I've gone through the whole process before, but this is an officially generated SDK, but their SDK is suddenly unsupported. They added too many strong checksums and didn't update their own SDK, which caused the problem.

**Comment by shadowJourney** [comment]
And I'm wondering if this readyToShipWindow date is the ship date? Why does the actual call to getShipment when it's set doesn't

**Comment by puppsupr** [comment]
Hi,
The issue is fixed. Please do check and let us know if it works now !

**Comment by kaipaysen** [comment]
I ran into this issue as well using the generated SDK for Java. Took me a while so it might be worth to share. `OffsetDateTime` can be made to serialize into the required format by converting it to UTC. My code:

```
    var windowInputStart = OffsetDateTime.now()
        .plus(1, ChronoUnit.HOURS)
        .truncatedTo(ChronoUnit.MINUTES)
        .withOffsetSameInstant(ZoneOffset.UTC);
```
