### ISSUE TITLE
Amazon Stock Status from ASIN

### ISSUE THREAD

**Issue by GeorgeRukasin** [amzn/selling-partner-api-models#3949]
Hello Support Team and Devs!
Is there and method to get product stock status from ASIN?
Using FBA Inventory API and Listing Item API, I couldn't do like that.
Thanks.

**Comment by chapmanjw** [comment]
What do you mean by "stock status"? Are you looking to identify if your specific seller has inventory available or are you looking to know if an ASIN has inventory available from any seller?

**Comment by GeorgeRukasin** [comment]
@chapmanjw 
Thanks for reply.
I am looking to know if an ASIN has inventory available from any seller.

**Comment by chapmanjw** [comment]
@GeorgeRukasin I *believe* that can be inferred based on if there are active buyable offers via the Product Pricing APIs. However, we do not have any APIs that directly indicate stock levels (as that is proprietary information for each seller that we cannot share).

**Comment by GeorgeRukasin** [comment]
@chapmanjw 
Thank you so much.
I will try that method.
As another question, could we get reviews from clients using sp api?

**Comment by rugved1991** [comment]
Hi @GeorgeRukasin,

Currently it is not possible to fetch reviews on ASINs through the SP-API. For now, you can request buyers to submit a seller feedback and product review based on orders using the [Solicitations API](https://developer-docs.amazon.com/sp-api/docs/solicitations-api-use-case-guide). 

Best,
Rugved
Solutions Architect, SP-API

**Comment by GeorgeRukasin** [comment]
Hello @rugved1991 and Team
Thank you for your reply.
Best regards.

**Comment by GeorgeRukasin** [comment]
As thinking that the issue is solved successfully, I will close this issue.
