### ISSUE TITLE
Document content of the various "Listings Items" calls

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#395]
The documentation on https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2020-09-01.md is missing for almost every parameter.

I was hoping to find an SP-API replacement for using the "Add Products via Upload" offers feed.  At this point the documentation is so vague and unclear, that I'm not even certain if "Listings Items" calls will even do that.  Do they?

As for specific documentation missing:

* `productType` says "The Amazon product type of the listings item.", but doesn't say what that is.  What are the options for that string?

* What is `path`? How can we get the list of valid paths?

* `value` is a `< object > array`, which doesn't explain much.  What is an "object"?  I would guess it's an arbitrary dictionary of JSON key/value pairs, but... if so, what are the valid keys and values?

Edit: see https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-items-api/listingsItems_2021-08-01.md#patchoperation for the new version of the document, though the same issues apply.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
This isn't something "support" can help with.  It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
