### ISSUE TITLE
YTD net PPM not available through API

### ISSUE THREAD

**Issue by tonghoo** [amzn/selling-partner-api-models#3950]
I am currently utilizing the Vendor Central API and have a specific inquiry regarding the "Vendor Net Pure Product Margin Report."

I can find Year to Date (YTD) Net Pure Product Margin (Net PPM) in the Vendor central portal (see attached screen shot). 
<img width="713" alt="Screenshot 2024-06-07 at 9 15 03 AM" src="https://github.com/amzn/selling-partner-api-models/assets/20525203/fcfb84e1-6ecb-4975-950d-d7a7d0769e2a">

How can I get the same data via API? I have tried "reportOptions":{"reportPeriod": "YEAR"} with today or end of year day as 'dataEndTime'. I was able to create the report. But the status of the reports were always 'FATAL'.

Thank you in advance for your assistance.

**Comment by rodrifed** [comment]
Hi @tonghoo,

Thank you for your message.

Are you also specifying a `dataStartTime` in your request? This is a required attribute for **GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT**.
If you are doing it and still getting errors, I will kindly ask you to please open a [Developer Support case](https://developer.amazonservices.com/support), and provide merchant/seller Id, report Id, and timestamp. Our support team will be able to assist you.

Thank you,
Federico
Selling Partner Developer Services
