### ISSUE TITLE
JSON_LISTINGS_FEED List an offer for an item that already exists in the Amazon catalog - Can't set up LIST PRICE

### ISSUE THREAD

**Issue by DmytroShumeyko** [amzn/selling-partner-api-models#3958]
Hello! 
I'm using JSON_LISTINGS_FEED  to List an offer for an item that already exists in the Amazon catalog to FBA invintory.

As result I see added listing to my FBA inventory but it's with status "Incomplete" and the "List price" is missing.

![image](https://github.com/amzn/selling-partner-api-models/assets/22177017/5801a702-a318-46ce-a602-29cf8621c616)

How to set up "List price" using JSON_LISTINGS_FEED, what I have missed?

Please help with this.

Here is my JSON for JSON_LISTINGS_FEED:

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Selling Partner Listings Feed (v2)",
  "header": {
    "sellerId": "A3I07C5PD33KVE",
    "version": "2.0",
    "issueLocale": "en_US"
  },
  "messages": [
    {
      "messageId": 1,
      "sku": "ABC11214112FINAL3",
      "operationType": "UPDATE",
      "productType": "PRODUCT",
      "requirements": "LISTING_OFFER_ONLY",
      "attributes": {
        "batteries_required": [
          {
            "value": false,
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "supplier_declared_dg_hz_regulation": [
          {
            "value": "not_applicable",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "merchant_suggested_asin": [
          {
            "value": "B0799NJSTP",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "condition_type": [
          {
            "value": "new_new",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ],
        "purchasable_offer": [
          {
            "currency": "USD",
            "marketplace_id": "ATVPDKIKX0DER",
            "our_price": [
              {
                "schedule": [
                  {
                    "value_with_tax": 10.99
                  }
                ]
              }
            ],
                                        "minimum_seller_allowed_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 10.00
                                        }
                                    ]
                                }
                            ],
                            "maximum_seller_allowed_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 11.00
                                        }
                                    ]
                                }
                            ]
          }
        ],
        "fulfillment_availability": [
          {
            "fulfillment_channel_code": "AMAZON_NA"
          }
        ],
        "product_tax_code": [
          {
            "value": "A_GEN_TAX",
            "marketplace_id": "ATVPDKIKX0DER"
          }
        ]
      }
    }
  ]
}

**Comment by W00Dface222** [comment]
I'm having the same issue...

The problem with the solution provided, is LISTING appears to want to create a whole new listing from scratch, where as LISTING_OFFER_ONLY, is for adding your own offer.

Amazon has now forced you to provide a list_price regardless of if you are just adding an offer or creating a whole new listing.

Therefore, it leaves using the API to create an offer useless in most categories now.

**Comment by rodrifed** [comment]
Hi @W00Dface222,

If you are adding an offer for an existing item, `list_price` shouldn't come as part of the JSON schema if you use LISTING_OFFER_ONLY mode while calling the [/getDefinitionsProductType operation](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#getdefinitionsproducttype).

If you find that `list_price` is actually included in the JSON schema, and considering that you are creating an offer for an item that already exists in the Amazon catalog, you can read the ASIN using the [/getCatalogItem operation](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#getcatalogitem) and retrieve the value for `list_price` from the response.

Thank you,
Federico
Selling Partner Developer Services

**Comment by W00Dface222** [comment]
Hi @rodrifed , thanks for the swift reply.

Correct in that list_price doesn't come as part of the Schema for LISTING_OFFER_ONLY , however, listing created using LISTING_OFFER_ONLY are now failing since Amazons update. Like @DmytroShumeyko said, they are going inactive and you have to manually go in to Seller Central to add a listing_price before they will become active.

If you have access to a sandbox, you can try this with ABIS_BOOK in marketplace A1F83G8C2ARO7P

You will see that the offer is created, but won't become active.

It appears that Amazon now requires the field to be filled in every time an offer is created (Which is crazy as the list price shouldn't change with every offer).

**Comment by W00Dface222** [comment]
Also, to add to this, list_price seems to have disappeared from /getCatalogItem too. It was appearing in there until around two weeks ago too. ASIN B01LP65I22 is an example of this.

**Comment by rodrifed** [comment]
Hi @W00Dface222,

Thanks for all your input and feedback.

The `list_attribute` should still be part of the /getCatalogItem response if the value was provided for that ASIN. I have just confirmed this with ASIN B0CN9GXC2R in US marketplace (ATVPDKIKX0DER):
```
...,
"list_price": [
    {
        "currency": "USD",
        "value": 349.0,
        "marketplace_id": "ATVPDKIKX0DER"
    }
]
```
Are you seeing this behaviour for all ASINs in A1F83G8C2ARO7P?

Regarding the manual work you have to do in Seller Central, you could replace that with a [/patchListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patchlistingsitem) call. If you retrieve the JSON schema using `requirements = LISTING` and `productType = PRODUCT` you will find the `list_attribute` attribute, which you can just patch with the Listings API.
In any case, we will review this internally to see if there's an opportunity to improve the current logic.

Thank you,
Federico
 Selling Partner Developer Services

**Comment by W00Dface222** [comment]
Thanks for the reply @rodrifed 

After much head scratching, I managed to fix the issue this morning.

Certainly for the UK market "value" itself doesn't work, and you actually need "value_with_tax".

									 'list_price'=> [
										[
										'marketplace_id'=> 'A1F83G8C2ARO7P',
										'value_with_tax'=> 25,
										'currency'=> 'GBP'
										  
										]
										
The main issue / annoyance comes when Amazon suddenly forces a change on what is a required field for a listing, but gives no notice.
