### ISSUE TITLE
Process Returns and Refunds for FBM

### ISSUE THREAD

**Issue by acitystacie** [amzn/selling-partner-api-models#3959]
Which API and methods should be used to process returns and refunds for Fulfillment by Merchant accounts?

**Comment by rugved1991** [comment]
Hi @acitystacie,

We do not have a separate API for the returns use case. You will have to use the [Returns reports](https://developer-docs.amazon.com/sp-api/docs/report-type-values-returns) to fetch information related to returns for Fulfillment by Merchant.

For refunds, we do not have any API for processing the refund. The seller will have to perform this action on their seller central account. You can use the [Settlement Report](https://developer-docs.amazon.com/sp-api/docs/report-type-values-settlement) or the [Finance API](https://developer-docs.amazon.com/sp-api/docs/finances-api-reference) to reconcile the amounts.

Best,
Rugved
Solutions Architect, SP-API
