### ISSUE TITLE
What's the purpose of ReportDocument.reportDocumentId ?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#396]
In order to get https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#reportdocument you have to provide `reportDocumentId`.  Then the `ReportDocument` that is returned contains `reportDocumentId`, sent right back. It seems redundant and pointless, and is therefore confusing.

Why is `ReportDocument.reportDocumentId` there?  If there really is some reason to return the input right back, the documentation should explain why, in detail, given how strange it is.

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It's great that the SPAPI team has been informed of this bug report. However it would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
