### ISSUE TITLE
Fulfillment Inbound V2024-03-20 API  UpdateShipmentTrackingDetails

### ISSUE THREAD

**Issue by liangfeng520** [amzn/selling-partner-api-models#3960]
response：
{
    "operation": "updateShipmentTrackingDetails",
    "operationId": "e57db516-b62b-4f03-9330-b7f46be64b3d",
    "operationStatus": "SUCCESS",
    "operationProblems": [
    ]
}，

but I can't see trackingId，how can i search trackingId.
![image](https://github.com/amzn/selling-partner-api-models/assets/12791623/f31be2e8-97e3-4cd5-b0eb-7ce8ec2acb96)

**Comment by harguph** [comment]
Hello @liangfeng520 ,

Per the API [updateShipmentTrackingDetails](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#put-inboundfba2024-03-20inboundplansinboundplanidshipmentsshipmentidtrackingdetails), a [trackingid](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#trackingid) is "The tracking number of the package, provided by the carrier." ( which is updated by the seller ). It is not possible to search by trackingid. For more details on various Fulfillment Inbound API refer [use case guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#what-is-the-fulfillment-inbound-api).

Regards

**Comment by liangfeng520** [comment]
I uploaded the tracking number through the V2024-03-20 API UpdateShipmentTrackingDetails. How can I view the uploaded tracking number?  thanks

**Comment by liangfeng520** [comment]
> Hello @liangfeng520 ,
> 
> Per the API [updateShipmentTrackingDetails](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#put-inboundfba2024-03-20inboundplansinboundplanidshipmentsshipmentidtrackingdetails), a [trackingid](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#trackingid) is "The tracking number of the package, provided by the carrier." ( which is updated by the seller ). It is not possible to search by trackingid. For more details on various Fulfillment Inbound API refer [use case guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#what-is-the-fulfillment-inbound-api).
> 
> Regards

I uploaded the tracking number through the V2024-03-20 API UpdateShipmentTrackingDetails. How can I view the uploaded tracking number? thanks

**Comment by ArseniyK** [comment]
I have the same issue, updated trackingId via API, not visible through API nor UI.

**Comment by he0212** [comment]
> response： { "operation": "updateShipmentTrackingDetails", "operationId": "e57db516-b62b-4f03-9330-b7f46be64b3d", "operationStatus": "SUCCESS", "operationProblems": [ ] }，
> 
> but I can't see trackingId，how can i search trackingId. ![image](https://private-user-images.githubusercontent.com/12791623/338808778-f31be2e8-97e3-4cd5-b0eb-7ce8ec2acb96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTY2NTMsIm5iZiI6MTcyMDQ5NjM1MywicGF0aCI6Ii8xMjc5MTYyMy8zMzg4MDg3NzgtZjMxYmUyZTgtOTdlMy00Y2Q1LWIwZWItN2NlOGVjMmFjYjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAzMzkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzOGVmNjE5M2IxYzZhZDAwZjI2OTVlODhiYTcyOTU4Mjg0NTQ3YjJiZDk3ZDUyNjMzNjZjMDZiM2Y4YzFjZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hrj-tM34UH1TE9Yu3TzLPziWx-ocNK4JqPUreoilVZ0)

Hi @liangfeng520 , I'm so sorry to disturb you.
I notice that you used to ask in other issue about how to solve `UpdateShipmentTrackingDetails` repsonse operationStatus : FAILED, but no any operationProblems returns. I met this problem too. It seems that you succeeded in that step, could you tell me what you have done? I I would appreciate it very much!!!
