### ISSUE TITLE
How to get All SKU of the ASIN

### ISSUE THREAD

**Issue by rugved-bodke-stigya** [amzn/selling-partner-api-models#3962]
Hi,
I am trying to get all the SKU's of an ASIN, but so far I have tried with catalog router but not getting the desired results, Just wanted to get all the associated SKU's for that ASIN

Thanks in Advance

**Comment by chapmanjw** [comment]
@rugved-bodke-stigya There won't ever be a feature where you would be able to see all SKUs for every seller on an ASIN. However, we are working on the Listings Item Search API that will let you query by ASIN to retrieve all SKUs for a given seller. Stay tuned for launch announcements on that later this year.
