### ISSUE TITLE
Selling Partner API (SP API) : ApiError : Fulfillment Inbound : GET deliveryWindowOptions issue

### ISSUE THREAD

**Issue by qdev89** [amzn/selling-partner-api-models#3964]
hi all,
I try to use https://sellingpartnerapi-na.amazon.com/inboundPlans/:inboundPlanId/shipments/:shipmentId/deliveryWindowOptions 
This also not listed in the document in https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#step-8-select-transportation-options ? (or I'm missing something)
with correct params but get result error:
{
    "errors": [
        {
            "code": "InternalFailure",
            "message": "We encountered an internal error. Please try again.",
            "details": ""
        }
    ]
}
I'm totally stuck on this step you can check

thanks

**Comment by shreeharsh-a** [comment]
@MeenaAmz

**Comment by qdev89** [comment]
turn out we need to call exactly same POST before can call GET.
thank you
