### ISSUE TITLE
FeedsApi Can I upload using JSON messages？

### ISSUE THREAD

**Issue by txq236** [amzn/selling-partner-api-models#3968]
Document address：https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#json-feeds
Why is it mentioned in the user guide that you can upload JSON messages？
An 5001 error occurred when I tried to change the inventory using the JSON format

Follow the document steps to set when calling createFeedDocument contentType=application/json; charset=UTF-8
Upload the feed data Also set contentType=application/json; charset=UTF-8
Up until step 6, I didn't get any errors, but when I finally downloaded the results, I was told that the XML format was wrong

Step 7. Download the feed processing report The response results are as follows：
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
<Header>
<DocumentVersion>1.02</DocumentVersion>
<MerchantIdentifier>merchantid</MerchantIdentifier>
</Header>
<MessageType>ProcessingReport</MessageType>
<Message>
<MessageID>1</MessageID>
<ProcessingReport>
<DocumentTransactionID>133837019889</DocumentTransactionID>
<StatusCode>Complete</StatusCode>
<ProcessingSummary>
<MessagesProcessed>0</MessagesProcessed>
<MessagesSuccessful>0</MessagesSuccessful>
<MessagesWithError>1</MessagesWithError>
<MessagesWithWarning>0</MessagesWithWarning>
</ProcessingSummary>
<Result>
<MessageID>0</MessageID>
<ResultCode>Error</ResultCode>
<ResultMessageCode>5001</ResultMessageCode>
<ResultDescription>XML Parsing Fatal Error at Line 1, Column 1: Content is not allowed in prolog. Content is not allowed in prolog.</ResultDescription>
</Result>
</ProcessingReport>
</Message>
</AmazonEnvelope>

Step 3. Upload the feed data Upload the message as follows ：
{
    "header": {
        "issueLocale": "en_US",
        "sellerId": "merchantId",
        "version": "2.0"
    },
    "messages": [
        {
            "messageId": 1,
            "operationType": "PARTIAL_UPDATE",
            "attributes": {
                "fulfillment_availability": [
                    {
                        "quantity": 199,
                        "fulfillment_channel_code": "DEFAULT"
                    }
                ]
            },
            "sku": "SKU1"
        },
        {
            "messageId": 2,
            "operationType": "PARTIAL_UPDATE",
            "attributes": {
                "fulfillment_availability": [
                    {
                        "quantity": 199,
                        "fulfillment_channel_code": "DEFAULT"
                    }
                ]
            },
            "sku": "SKU2"
        }
    ]
}

**Comment by xyloneX** [comment]
feedtype="JSON_LISTINGS_FEED"  ?

**Comment by txq236** [comment]
> feedtype="JSON_LISTINGS_FEED" ?

Thank you very much. It is for this reason that I made a stupid mistake

**Comment by harguph** [comment]
Hello @txq236 ,

Great to see the issue is resolved.

In the issue re-occurs or if you need any further assistance, Please feel free to open a case with [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

Regards
