### ISSUE TITLE
Is it possible to get `GET_CATEGORY_LISTINGS_DATA` report?

### ISSUE THREAD

**Issue by moltar** [amzn/selling-partner-api-models#397]
Is it possible to get `GET_CATEGORY_LISTINGS_DATA` report?

References:

 - https://sellercentral.amazon.com/forums/t/how-to-request--get-category-listings-data--report/176695/4
 - https://help.zentail.com/en/articles/1196450-category-listing-report-from-amazon-seller-central

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
