### ISSUE TITLE
Please tell me how to query the marketplace_ids array.

### ISSUE THREAD

**Issue by sugaular** [amzn/selling-partner-api-models#3970]
Please tell me how to query the marketplace_ids array.	
	
Here's what I've tried:	
(in POSTMAN)
	
1	https://sellingpartnerapi-fe.amazon.com/catalog/2022-04-01/items/B0B3GCDXDD?marketplace_ids[]=A1VC38T7YXB528
	
response
	    <h1>HTTP Status 400 – Bad Request</h1>
	    <hr class="line" />
	    <p><b>Type</b> Exception Report</p>
	    <p><b>Message</b> Invalid character found in the request target
	        [&#47;catalog&#47;2022-04-01&#47;items&#47;B0B3GCDXDD?marketplace_ids[]=A1VC38T7YXB528 ]. The valid characters
	        are defined in RFC 7230 and RFC 3986</p>
	
2	https://sellingpartnerapi-fe.amazon.com/catalog/2022-04-01/items/B0B3GCDXDD?marketplace_ids=A1VC38T7YXB528
	
response
	{
	    "errors": [
	        {
	            "code": "InvalidInput",
	            "message": "Invalid 'marketplaceIds' provided.",
	            "details": ""
	        }
	    ]
	}

**Comment by xyloneX** [comment]
You are too careless in this question. Please read the document params.

**Comment by sugaular** [comment]
I realized I was stupid.
I had been working on the python sample for a while, so I was late in noticing.

marketplaceIds: Correct
marketplace_ids: Incorrect

Thanks for pointing that out.

**Comment by harguph** [comment]
Hello @sugaular ,

Great to hear the issue is resolved.

Please feel free to reach-out to [developer support](https://developer.amazonservices.com/support) for any issues related to SP API.

`Note: We can help if the issue is related to the content published on this repo.`
