### ISSUE TITLE
Error in api-model-descriptions 

### ISSUE THREAD

**Issue by linde9821** [amzn/selling-partner-api-models#3974]
We have discovered the following error when using the openapi-descriptions to generate typesafe clients and datamodels.

**Catalog_Items_API_v2022-04-01:**

- for the `searchCatalogItems` Endpoint the descriptions states:

```json
        "pagination": {
          "description": "If available, the `nextToken` and/or `previousToken` values required to return paginated results.",
          "$ref": "#/definitions/Pagination"
        }
        
       // ....
        
              "required": [
        "numberOfResults",
        "pagination",
        "refinements",
        "items"
      ],
```

As by the pagination description it seems like `pagination` can be `null` however it is listed as required. When testing the api we found that indeed it can be `null` so the description should look like this

```json
      "required": [
        "numberOfResults",
        "items"
      ],
```
 
**ordersV0**

- for the `getOrders` Endpoint it states that for `OrderItem`

```json
    "OrderItem": {
      "type": "object",
      "required": [
        "ASIN",
        "OrderItemId",
        "QuantityOrdered"
      ],
```

However the required field leads to some errors. After some testing we figured that actually everything can be absent from the response so the whole `required` should be removed.

**Comment by arpetris** [comment]
This issue is causing me problems with the prebuilt C# api. 1) The API expects pagination but it does not exist if there are fewer results than the page size. 2) When you search using identifiers such as UPC, the api does not return refinements. This is causing the prebuilt C# api to throw and exception as it expects these values.
