### ISSUE TITLE
confirmTransportOptions APi could not confirm

### ISSUE THREAD

**Issue by FireworksWD** [amzn/selling-partner-api-models#3979]
I  generate the PlacementOptins API and confirmed it was successful,but when I confirm the ConfirmTransportationOptions API ,it says I didn't confirm ConfrimPlacementOptions API.

![image](https://github.com/amzn/selling-partner-api-models/assets/102148682/3a382521-942f-4a0a-ab75-841843e48fb6)
![image](https://github.com/amzn/selling-partner-api-models/assets/102148682/ec3eafb0-26af-479c-9e2d-6cc64886a372)

Confirm the error at the time of the ConfirmTransportationOptions API:
![image](https://github.com/amzn/selling-partner-api-models/assets/102148682/c2679187-aabc-40f5-b30c-48b1081a26ad)

**Comment by shreeharsh-a** [comment]
@MeenaAmz

**Comment by puppsupr** [comment]
Hi,
Do you still see this issue ?

**Comment by utexasscott** [comment]
We are also experiencing this issue.

confirmPlacementOption returns a success, but then confirmTransportOptions fails:

`No placement option is confirmed for inboundPlan ...`

**Comment by puppsupr** [comment]
> We are also experiencing this issue.
> 
> confirmPlacementOption returns a success, but then confirmTransportOptions fails:
> 
> `No placement option is confirmed for inboundPlan ...`

you need to confirm the placementOption before confirming the transportationOption.
