### ISSUE TITLE
Report status return FATAL

### ISSUE THREAD

**Issue by gaurav-webs** [amzn/selling-partner-api-models#398]
When I call a report in a loop and when we get the report data it always returns a FATAL status, what is the reason?

I am fetching reports of the whole week in a loop day by day, so I get the report id from createReport API, but when I call getReport it will always return FATAL, can anyone explain to me why it returns FATAL.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
