### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 HOW TO CHOOSE SPD?

### ISSUE THREAD

**Issue by tangshuai3211** [amzn/selling-partner-api-models#3981]
Before confirm the order(confirmPlacementOption), I did not find a place to choose the shipping method at any step, so all of my shipping methods were defaulted to LTL. In which step should I pass what attributes to confirm my delivery method.
![image](https://github.com/amzn/selling-partner-api-models/assets/45872296/13986dd4-d943-4029-8ada-8b8b1ecc285b)

I have now reached this stage of the process，and returned successfully.
![image](https://github.com/amzn/selling-partner-api-models/assets/45872296/1ff762ea-1ea6-401e-81ce-3367a3e4901f)

**Comment by Prez5er** [comment]
hey, how was it solved?? I have the same doubt

**Comment by dishcheng** [comment]
> hey, how was it solved?? I have the same doubt

+1

**Comment by dishcheng** [comment]
In this step:listTransportationOptions 
view `shippingMode` attribute ,you will get answer
