### ISSUE TITLE
report's ReportDocument compressionAlgorithm is confusing and unnecessary

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#399]
As mentioned previously in Bug amzn/selling-partner-api-models#1280 (and some other bugs that involved the old API's extra crypto layer), the report's ReportDocument compressionAlgorithm is confusing.  It's also unnecessary as HTTP supports this feature natively.

I recently requested (accidentally) a `GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA` report with 11 megabytes of data uncompressed. It was sent as documented per https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md#reportdocument and that all works.

However it is needlessly confusing the way the SP-API does this though.

The HTTP protocol natively supports compression encoding. Instead of all of this `"compressionAlgorithm": "GZIP"` that has to be documented separately, the SP-API should just send the standard HTTP header: `Content-Encoding: gzip`.  And then the HTTP client will seamlessly perform decompression.  This also would solve a current oddity where the content type doesn't seem to be specified properly.  (It's UTF-8 seemingly, but I didn't see that in the SP-API protocol.)

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
I just noticed this was actually fixed (optionally).  Well that's good.  On the https://developer-docs.amazon/sp-api/reference/getreportdocument page it shows a new optional `enableContentEncodingUrlHeader` field.  Specifying it gives you normal HTTP behavior for compression, instead of compression being awkwardly done at the SPAPI level.

I wonder why someone thought it needed to be optional.
