### ISSUE TITLE
Error "Invalid Request Parameters" When Submitting Feed "POST_FBA_INBOUND_CARTON_CONTENTS"

### ISSUE THREAD

**Issue by zaki-siddiqui** [amzn/selling-partner-api-models#3992]
I have been attempting to submit a feed for "POST_FBA_INBOUND_CARTON_CONTENTS." I successfully created a feed document and constructed a feed with my XML (generated from the given XSD), and the response was 200 OK. However, when I try to create a feed with the appropriate parameters, I consistently receive the error "Invalid request parameters." Has anyone successfully created a "POST_FBA_INBOUND_CARTON_CONTENTS" feed with an XML file? If so, please guide me accordingly.

My XML file
```
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.01</DocumentVersion>
		<MerchantIdentifier>Merchant-Id</MerchantIdentifier>
	</Header>
	<MessageType>CartonContentsRequest</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<CartonContentsRequest>
			<ShipmentId>Shipment-Id</ShipmentId>
			<NumCartons>1</NumCartons>
			<Carton>
				<CartonId>234567</CartonId>
				<Item>
					<SKU>CP-XXXX</SKU>
					<QuantityShipped>2</QuantityShipped>
					<QuantityInCase>1</QuantityInCase>
				</Item>
				<Item>
					<SKU>CP-XXXX</SKU>
					<QuantityShipped>1</QuantityShipped>
					<QuantityInCase>1</QuantityInCase>
				</Item>
			</Carton>
		</CartonContentsRequest>
	</Message>
</AmazonEnvelope>
```

**Comment by harguph** [comment]
Hello @zaki-siddiqui ,


Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.
`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
