### ISSUE TITLE
Product upload issues

### ISSUE THREAD

**Issue by wszwc** [amzn/selling-partner-api-models#3995]
1. Does the current json publication support non-branded products?
2. How to publish follow-up links?

**Comment by leonardonakagawa** [comment]
Hi @wszwc,

Are you looking to publish items with GTIN exemption? 

If yes in the JSON schema, there is an attribute called: `supplier_declared_has_product_identifier_exemption` a bool where you indicate if that product has or not exemption. 


For your other question, could you please elaborate on that?

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by wszwc** [comment]
> Are you looking to publish items with GTIN exemption?
> 


Thank you very much for your answer, I understand what you mean.
But some of our customers want to upload products through the interface without applying for brand whitelist exemption.
They said that products without brands can also be uploaded in the background.
The GTIN exemption products you mentioned may just not need to fill in the external product ID? For example, UPC? But the brand still needs to be filled in, and the premise is that this store account has obtained brand exemption.
I want to know if this is feasible? Thank you very much for your answer.

**Comment by leonardonakagawa** [comment]
Hi @wszwc,

What your customer can do is, request the GTIN exemption with `GENERIC` as brand name, then you will be able to set the `supplier_declared_has_product_identifier_exemption` as `true` and use the Generic as brand name.

You can find details regarding this in this [link](https://sellercentral.amazon.com/help/hub/reference/G200426310).
If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
