### ISSUE TITLE
How to register a SKU for an existing product in the Amazon catalog using SP-API as of July 1, 2024

### ISSUE THREAD

**Issue by sugaular** [amzn/selling-partner-api-models#3996]
We attempted to use the Feed API (/feeds/2021-06-30/) to UPDATE, but we couldn't find all the required parameters.
We also attempted to use the Listing API (/listings/2021-08-01/items/), but we couldn't find all the required parameters.

Example: ASIN: 'B09MTGCWBP'
Missing parameters:
- output_voltage
- country_of_origin
- product_description

I just want to register the SKU. (PATCH of Feed API worked)
I don't mind using an older version of the SP-API, 
I would like advice from someone who has already done this.

Isn't the purpose of the Amazon catalog to share product details information?
Why do they ask for this information again from all sellers?
Or, is it best to wait for SP-API development to progress?

**Comment by jawheral** [comment]
Hi @sugaular,

Try using the [Catalog Items API v2022-04-01](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference) in order to get the information needed for the Listings Items API (putListingsItem) or Feeds API payload.

Best,
Jawher,
SP API - Solutions Architect

**Comment by sugaular** [comment]
Sure, here is the translation:

---

Of course, I am using it.

Catalog API
`/catalog/2022-04-01/items/`
Listing API
`/listings/2021-08-01/items/`

But it hasn't improved.

It is clearly stated that it is currently under development, so I can wait.

However, I would like to know if the current requirement to input all parameters in order to register even a SKU will remain as it is.

Can you tell me just that?

**Comment by jawheral** [comment]
Hi @sugaular,

Required listings attributes will depend on the [Requirements](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#requirements) type you choose and the productType.

You can inspect the required attributes for each type using the [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference).

Can you also elaborate or share the link to the resource on what you've referred to be stated as _currently under development_?

Best,
Jawher
SP API - Solutions Architect

**Comment by sugaular** [comment]
I understand that the reason for asking the parameters again is to help the seller better understand the product.

Thanks for the information. I'll give it a try.

**Comment by sugaular** [comment]
It worked. Thank you.

**Comment by sugaular** [comment]
It worked. Thank you.

**Comment by jawheral** [comment]
Hi @sugaular,

I'm happy this was helpful to you. 

Thank you for reaching out!

Best,
Jawher
SP-API Solutions Architect
