### ISSUE TITLE
OAuth Redirect URI Impossible to edit URI

### ISSUE THREAD

**Issue by ghena** [amzn/selling-partner-api-models#3997]
Hi,

in my application is not possible to edit redirect_uri or add a new authorized uri.
I asked to amazon support to explain to solve it.

Someone had the same experience ?
Regards.

![image](https://github.com/amzn/selling-partner-api-models/assets/548424/92ea2afb-b831-4f80-a25d-ac2ef4f49887)

**Comment by leonardonakagawa** [comment]
Hi @ghena,

Could you please share the case id opened with developer support? Your application is currently published to the AppStore? 

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by rugved1991** [comment]
Hi @ghena,

This app config page looks like an app for a private developer. It is not possible to configure OAuth for a private developer as you would be using Self-Authorization to receive a refresh token.
Is there a particular reason, you would like to setup OAuth on your application? This is only required if you are public developer developing solution for other sellers or vendors.

Best,
Rugved
Solutions Architect, SP-API
