### ISSUE TITLE
Report GET_MERCHANT_LISTINGS_ALL_DATA Don`t contain all fields according documentation 

### ISSUE THREAD

**Issue by maciej-kosiedowski** [amzn/selling-partner-api-models#3999]
Hi,
GET_MERCHANT_LISTINGS_ALL_DATA starts returning different result from couple of days.
Now report returns:
```
item-name	item-description	listing-id	seller-sku	price	quantity	open-date	Deprecated column	item-is-marketplace	product-id-type	Deprecated column	item-note	item-condition	Deprecated column	Deprecated column	Deprecated column	asin1	Deprecated column	Deprecated column	will-ship-internationally	expedited-shipping	Deprecated column	product-id	Deprecated column	add-delete	pending-quantity	fulfilment-channel	merchant-shipping-group	status	Minimum order quantity	Sell remainder
```
"Deprecated column" -> Change is undocumented https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory

It' intended change and we need update our code, or it`s mistake form your side?

**Comment by maciej-kosiedowski** [comment]
Issue is observed right now only for one connected account

**Comment by B3lg4r4th** [comment]
I'm pretty sure some of the inventory reports that are available through Seller Central as well as the SP-API can be customized in Seller Central in regards to which columns they have when exported - perhaps this is one of them?

**Comment by maciej-kosiedowski** [comment]
Thanks @B3lg4r4th for comment. I tested this theory. 
For "reportOptions":{"custom":"true or false"} I`m still getting "Deprecated column" in response.

Default for this field is set to False, so we generally fetch always default version of reports

**Comment by leonardonakagawa** [comment]
Hi @maciej-kosiedowski,

I tried to reproduce this behavior in my side calling the GET_MERCHANT_LISTINGS_ALL_DATA for US marketplace and no Deprecated Columns are being returned. Could you please try again and let us know?

The `createReport` operation was done with the body below:

```
{
  "reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
  "marketplaceIds":["ATVPDKIKX0DER"]
}

```

If the behavior is still happening, could you also paste your request here? 


Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by skcxck** [comment]
Hi @leonardonakagawa
deprecated columns affects only some customers for unknown reason on this report. 
We fetch reports for marketplace Germany `A1PA6795UKMFR9`

Request: 
```
POST https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports
{
"reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
"marketplaceIds": ["A1PA6795UKMFR9"]
}
```

Result report headers via 
`GET https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/documents/{$reportDocumentId}`
```
item-name
item-description
listing-id
seller-sku
price
quantity
open-date
Deprecated column
item-is-marketplace
product-id-type
Deprecated column
item-note
item-condition
Deprecated column
Deprecated column
Deprecated column
asin1
Deprecated column
Deprecated column
will-ship-internationally
expedited-shipping
Deprecated column
product-id
Deprecated column
add-delete
pending-quantity
fulfilment-channel	
optional-payment-type-exclusion
merchant-shipping-group
status
Minimum order quantity
Sell remainder
```

I am happy to provide further details. 
thanks

**Comment by koradiyayash26** [comment]
There is an issue with GET_MERCHANT_LISTINGS_ALL_DATA for the FR profile, as it is not returning valid data such as ASINs, while other profiles are retrieving them correctly, like asin geting wrong on some of prodcut like geting this 5056001680715 asin
