### ISSUE TITLE
GET_FLAT_FILE_OPEN_LISTINGS_DATA Report Has Outdated Data

### ISSUE THREAD

**Issue by bpyzikvc** [amzn/selling-partner-api-models#400]
I noticed that when I run this report I am not always getting the most up to date inventory that I can see from my Seller Central account. I changed the inventory in the Seller Central account and kept running the report about every 15 minutes and finally got the updated information after an hour and 20 minutes. 

Is there a plan to fix this or is this just the way it is? Hoping that Amazon devs may be aware of this and looking to get the report to be more up to date.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the documentation bug open until it's fixed, so people know where to look for information on this bug.
