### ISSUE TITLE
getMyFeesEstimateForASIN not working for some ASINs

### ISSUE THREAD

**Issue by fullbeats** [amzn/selling-partner-api-models#4001]
I do get a strange behavior in the "[getMyFeesEstimateForASIN](https://developer-docs.amazon.com/sp-api/docs/product-fees-api-v0-reference#getmyfeesestimateforasin)"-Endpoint  from the _Product Fees API_ (getMyFeesEstimates affected as well):

I want to retrieve the fees for a specific ASIN.
Most of the calls go through and I get a detailed list of all the applied fees. 
But for some ASINs, this does not work and I get an error message like this:

> "Error": {"Type": "Sender","Code": "InvalidParameterValue","Message": "There is an client-side error. Please verify your inputs.","Detail": []}}}}'

Examples:
ASIN that works: B004DI7350
ASIN that does not work: B003Z7CW0Q, B00FQW709G

As I said, I use the _exact same code_, but it does not work for the example ASINs shown.
I can reproduce this as often as I want to.
This is the call to the SP-API I am making:

```python

    request_params = {
        "FeesEstimateRequest": {
            "Identifier": str(uuid.uuid4()),
            "MarketplaceId": marketplace_id, # Marketplace DE --> marketplace_id = "A1PA6795UKMFR9"
            "IsAmazonFulfilled": is_fba, # True or False
            "PriceToEstimateFees": {
                "ListingPrice": {
                    "Amount": price, # this is a float with two digits
                    "CurrencyCode": currency, # "EUR"
                }
            }
        }
    }
    try:
        fees = requests.post(
            SP_API_DEFAULT_ENDPOINT
            + f"/products/fees/v0/items/{asin}/feesEstimate", # asin = e.g. "B003Z7CW0Q"
            data=json.dumps(request_params),
            headers={
                "x-amz-access-token": token, 
                "Accept-Encoding": "gzip, deflate, br", # add compression to the request
            },
        )
    except Exception as e:
        pass # simplified here
```

Please let me know if you can reproduce this issue or if you know why this is failing for some specific ASINs while it works for others like a charm.

**Comment by mafge** [comment]
Hi @fullbeats,
thanks for reaching out! 
I just checked the ASINs on my side and I get successful responses for the ones that were failing for you. In case you still see the error on your end, please feel free to contact developer support via [seller central](https://sellercentral.amazon.de/help/center). They can help you out and also can check if there is any error with your specific account.

Best,
Marc
Selling Partner Developer Services

**Comment by fullbeats** [comment]
> Hi @fullbeats, thanks for reaching out! I just checked the ASINs on my side and I get successful responses for the ones that were failing for you. In case you still see the error on your end, please feel free to contact developer support via [seller central](https://sellercentral.amazon.de/help/center). They can help you out and also can check if there is any error with your specific account.
> 
> Best, Marc Selling Partner Developer Services

Hi @mafge,
thanks for your answer!
That is interesting - have you checked those ASINs with the German marketplace though?
Because after some back and forth with the Amazon Developer Support, we kind of found out that all those affected ASINs tend to have FBM offers only. With very relevant information about packaging, size and weight missing in those cases on the Amazon end, the API is unable to process the calculation of fees.

**Comment by mafge** [comment]
Hi @fullbeats,
yes, I checked your ASINs for german marketplace, but I didn't check for FBA though. I only see your error when setting `IsAmazonFulfilled` to true. Anyway, glad that Developer Support was able to help you out!
