### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 confirmTransportationOptions Provided shipment ids [sh9d5eed29-907a-4161-a2ac-734c5c66979f] do not match the shipments in the confirmed placement option

### ISSUE THREAD

**Issue by HaHaVip123** [amzn/selling-partner-api-models#4003]
Unable to confirm
![Uploading 企业微信截图_da18a12b-1b4d-4397-b7b0-125f52b1bc8a.png…]()

**Comment by HaHaVip123** [comment]
<img width="477" alt="企业微信截图_da18a12b-1b4d-4397-b7b0-125f52b1bc8a" src="https://github.com/amzn/selling-partner-api-models/assets/173242862/4cff06a7-f17b-463f-bc8c-3cb28922984a">

**Comment by xEverth** [comment]
Hello @HaHaVip123,
ShipmentId provided by Amazon in user interface on SellerCentral (starting with FBA...) don't match with shipmentId UUID used in the API. This is very unfortunate. You should be able to retrieve the "FBA..." id by querying for the specific shipment information.
Waiting for more and better information from Amazon SP API team

**Comment by HaHaVip123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HaHaVip123** [comment]
1 validation error detected: Value \\u0027FBA18677FXB1\\u0027 at \\u0027request.transportationSelections.1.member.shipmentId\\u0027 failed to satisfy constraint: Member must have length greater than or equal to 38
