### ISSUE TITLE
 After POST_PRODUCT_PRICING_DATA is deprecated, what can be replaced?

### ISSUE THREAD

**Issue by Ironkyy** [amzn/selling-partner-api-models#4004]

**Comment by abc1978785513** [comment]
That's what I'm asking.

**Comment by leonardonakagawa** [comment]
Hi @abc1978785513,

To update prices in bulk, you can rely on the JSON_LISTINGS_FEED if you are submitting more than 1,500 - 10,000 updates per request. Less than that, you can rely on the patchListingsItem API.

The [Building Listings Management Workflows Guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#creating-and-updating-listings-items-in-bulk) can you building this flow.


Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by abc1978785513** [comment]
@leonardonakagawa   but   JSON_LISTINGS_FEED  can't  support  BusinessPrice  and QuantityPrice      What should we do?

**Comment by chapmanjw** [comment]
@abc1978785513 Support for B2B pricing (business pricing and quantity discounts) will be available in the Listings APIs and JSON_LISTINGS_FEED soon (~August/September). Stay tuned for announcements.

**Comment by leonardonakagawa** [comment]
Thanks, @chapmanjw :star-struck:

@abc1978785513 I'll tag this as closing soon, but if you still have any questions, feel free to post it here!

Thanks,
Leonardo

**Comment by maik5** [comment]
@chapmanjw 

Can you please post here when B2B pricing (business pricing and quantity discounts)  will be live?

Thanks

**Comment by jlevers** [comment]
Hey @maik5 – they're live as of a little over a month ago, in case you hadn't seen already :)

**Comment by maik5** [comment]
> Hey @maik5 – they're live as of a little over a month ago, in case you hadn't seen already :)

Thanks 
Is already implemented live
