### ISSUE TITLE
The return-related reports are not working.

### ISSUE THREAD

**Issue by sugaular** [amzn/selling-partner-api-models#4005]
I tried to retrieve a Return report using `https://sellingpartnerapi-fe.amazon.com/reports/2021-06-30/reports` with `dataStartTime` set to 50 days ago (even 60 days ago), but all `reportType` are getting `CANCELLED`.
(GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL worked)

I've seen similar inquiries before, but they went unanswered.

Could you provide any advice?

Return management is very important, so your help would be greatly appreciated.

**Comment by mafge** [comment]
Hi @sugaular,
thanks for reaching out!
If your report is getting cancelled this either means there is no data found or you explicitly cancelled the report before processing. Can you provide more information on how you create your reports (which type of report exactly, request body etc.)?

Thanks,
Marc
Selling Partner Developer Services

**Comment by sugaular** [comment]
The report type is GET_XML_RETURNS_DATA_BY_RETURN_DATE

The source(perl) is:
----
#!/usr/bin/perl
use strict;
use warnings;

use LWP::UserAgent;
use HTTP::Request::Common;
use HTTP::Headers;
use HTTP::Response;
use utf8;
use JSON;
use Data::Dumper;
use DateTime;

my $client_id = "XXXXXXXXXXXXXX";
my $client_secret = "XXXXXXXXXXXXXX";
my $refresh_token = "XXXXXXXXXXXXXX";
my $seller_id = "XXXXXXXXXXXXXX";

sub get_access_token {
    my $client_id = $_[0];
    my $client_secret = $_[1];
    my $refresh_token = $_[2];

    my $uri = 'https://api.amazon.com/auth/o2/token';

    my $ua = LWP::UserAgent->new;
    my $response = $ua->post(
        $uri,
        {
            grant_type    => 'refresh_token',
            client_id     => $client_id,
            client_secret => $client_secret,
            refresh_token => $refresh_token
        }
    );

    if ($response->is_success) {
        my $content = decode_json($response->decoded_content);
        return $content->{access_token};
    } else {
        die $response->status_line;
    }
}

# my $res_createReport = createReport($endpoint, $reportType, $dataStartTime, $access_token);
sub createReport {
    my ($endpoint, $reportType, $dataStartTime, $access_token) = @_;
    my $marketplaceId = "A1VC38T7YXB528";
    my $ua = LWP::UserAgent->new;
    my $headers = [
        'Content-Type' => 'application/json',
        'x-amz-access-token' => $access_token,
        'x-amz-date' => gmtime() . 'Z',
        #'Authorization' => 'AWS4-HMAC-SHA256 Credential=' . $aws_access_key_id . '/' . $region . '/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token, Signature=YOUR_SIGNATURE'
    ];
    my $body = encode_json({
        'contentType' => 'application/json',
        'marketplaceIds' => [$marketplaceId], 
        'dataStartTime' => $dataStartTime,
        'reportType' => $reportType 
    });

    my $uri = $endpoint."/reports/2021-06-30/reports";
    print "uri[".$uri."]\n";
    print Dumper $headers;
    print Dumper $body;
    my $req = HTTP::Request->new('POST', $uri, $headers, $body);

    my $res = $ua->request($req);
    print Dumper $res;
    if ($res->is_success) {
        return decode_json($res->decoded_content);
    } else {
        die $res->status_line;
    }
}

# my $res_getReport = getReport($endpoint, $reportId, $access_token);
sub getReport {
    my ($endpoint, $reportId, $access_token) = @_;
    my $ua = LWP::UserAgent->new;
    my $headers = [
        'Content-Type' => 'application/json',
        'x-amz-access-token' => $access_token,
        'x-amz-date' => gmtime() . 'Z',
        #'Authorization' => 'AWS4-HMAC-SHA256 Credential=' . $aws_access_key_id . '/' . $region . '/execute-api/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-security-token, Signature=YOUR_SIGNATURE'
    ];
    my $uri = $endpoint."/reports/2021-06-30/reports/".$reportId;
    print "uri[".$uri."]\n";
    my $req = HTTP::Request->new('GET', $uri, $headers);

    my $res = $ua->request($req);

    if ($res->is_success) {
        return decode_json($res->decoded_content);
    } else {
        die $res->status_line;
    }
}


############################################################# get_access_token
my $access_token = get_access_token($client_id,$client_secret,$refresh_token);

print "access_token[".$access_token."]";


my $marketplaceId = "A1VC38T7YXB528";
my $endpoint = 'https://sellingpartnerapi-fe.amazon.com';
my %content = ('contentType' => 'application/json');

my $days = 60;
my ($s, $m, $h, $d, $m, $y) = localtime(time - $days * 24 * 60 * 60);
$m = $m + 1;
$y = $y + 1900;
my $date = sprintf("%04d-%02d-%02d", $y, $m, $d);

my $dataStartTime = $date;
my $reportType = "GET_XML_RETURNS_DATA_BY_RETURN_DATE";

print $endpoint. "\n";

############################################################# createReport
my $res_createReport = createReport($endpoint, $reportType, $dataStartTime, $access_token);

#my $response_hash = decode_json($response_data);
my $reportId = $res_createReport->{'reportId'};
print "reportId: ". $reportId. "\n";

############################################################# getReport
my $processingStatus = "START";
my $res_getReport;
while ($processingStatus ne "CANCELLED" && $processingStatus ne "DONE" && $processingStatus ne "FATAL"){
    $res_getReport = getReport($endpoint, $reportId, $access_token);
    $processingStatus = $res_getReport->{'processingStatus'};
    print "processingStatus: ". $processingStatus. "\n";
    sleep 60;
}
my $reportDocumentId = $res_getReport->{'reportDocumentId'};
print "reportDocumentId: ". $reportDocumentId. "\n";
----

The results are as follows:
----
>perl test.pl
"my" variable $m masks earlier declaration in same statement at test.pl line 165.
access_token[Atza|IwEBIE4zsg-zocTGvsDnOQuoSCZKBSmHsEBbpCJtGunEgiksbRWxPCk5zuHYIv7f4L1QfuOJkFOZyuUNROfR8s-oAJ4XVPI1WcJftcXkUjDitLfyioFq-pZ1ijq8WeAcHDY-b4w9qDVV0DoUe2-q3wAyazuVHvZ6CNHtUlnpwHvLENzUtv0VKnwqbqNSuLyhl-Fi7rhUdORKZ19HMOLT6iSbBMPaaK_RXQWvgpp7Rqx0MYsDNNI3gZ9DnfT0U5CQt_92MPKjpIPZ2Gqt38FeRoYwATu55j5c_mQsEcRQevQGSKX2wApxX6kqm8cNZ5fioPevPZV8PZx2ayJ6N9GVBwh7Fy97DfCiLAO7pe2jdcCZE39ngw]https://sellingpartnerapi-fe.amazon.com
uri[https://sellingpartnerapi-fe.amazon.com/reports/2021-06-30/reports]
$VAR1 = [
          'Content-Type',
          'application/json',
          'x-amz-access-token',
          'Atza|IwEBIE4zsg-zocTGvsDnOQuoSCZKBSmHsEBbpCJtGunEgiksbRWxPCk5zuHYIv7f4L1QfuOJkFOZyuUNROfR8s-oAJ4XVPI1WcJftcXkUjDitLfyioFq-pZ1ijq8WeAcHDY-b4w9qDVV0DoUe2-q3wAyazuVHvZ6CNHtUlnpwHvLENzUtv0VKnwqbqNSuLyhl-Fi7rhUdORKZ19HMOLT6iSbBMPaaK_RXQWvgpp7Rqx0MYsDNNI3gZ9DnfT0U5CQt_92MPKjpIPZ2Gqt38FeRoYwATu55j5c_mQsEcRQevQGSKX2wApxX6kqm8cNZ5fioPevPZV8PZx2ayJ6N9GVBwh7Fy97DfCiLAO7pe2jdcCZE39ngw',
          'x-amz-date',
          'Sat Jul 13 07:03:16 2024Z'
        ];
$VAR1 = '{"dataStartTime":"2024-05-14","reportType":"GET_XML_RETURNS_DATA_BY_RETURN_DATE","contentType":"application/json","marketplaceIds":["A1VC38T7YXB528"]}';
$VAR1 = bless( {
                 '_content' => '{"reportId":"162341019917"}',
                 '_max_body_size' => undef,
                 '_rc' => '202',
                 '_headers' => bless( {
                                        'client-peer' => '18.246.99.235:443',
                                        'client-ssl-cipher' => 'TLS_AES_128_GCM_SHA256',
                                        'vary' => 'Content-Type,Accept-Encoding,User-Agent',
                                        'x-amzn-ratelimit-limit' => '0.0167',
                                        'client-date' => 'Sat, 13 Jul 2024 07:03:17 GMT',
                                        'client-ssl-cert-issuer' => '/C=US/O=Amazon/CN=Amazon RSA 2048 M01',
                                        'x-amzn-requestid' => '9fa2d095-492d-40be-b01d-e0612cffc9b6',
                                        'client-ssl-version' => 'TLSv1_3',
                                        'x-amz-rid' => 'PQTY7VMB3H0971H4XDET',
                                        'date' => 'Sat, 13 Jul 2024 07:03:15 GMT',
                                        'x-amz-apigw-id' => 'OPF9fa2d095492d',
                                        'content-type' => 'application/json',
                                        'content-length' => '27',
                                        'x-amzn-trace-id' => 'Root=1-669226b3-9fa2d095492d40be',
                                        'client-ssl-socket-class' => 'IO::Socket::SSL',
                                        'client-ssl-cert-subject' => '/CN=spapi-jp.amazon.com',
                                        'strict-transport-security' => 'max-age=47474747; includeSubDomains; preload',
                                        'client-response-num' => 1,
                                        'connection' => 'close',
                                        '::std_case' => {
                                                          'x-amz-apigw-id' => 'X-Amz-Apigw-Id',
                                                          'x-amzn-trace-id' => 'X-Amzn-Trace-Id',
                                                          'client-ssl-cert-subject' => 'Client-SSL-Cert-Subject',
                                                          'client-ssl-socket-class' => 'Client-SSL-Socket-Class',
                                                          'strict-transport-security' => 'Strict-Transport-Security',
                                                          'client-response-num' => 'Client-Response-Num',
                                                          'client-peer' => 'Client-Peer',
                                                          'client-ssl-cipher' => 'Client-SSL-Cipher',
                                                          'x-amzn-ratelimit-limit' => 'X-Amzn-RateLimit-Limit',
                                                          'client-date' => 'Client-Date',
                                                          'x-amzn-requestid' => 'X-Amzn-RequestId',
                                                          'client-ssl-cert-issuer' => 'Client-SSL-Cert-Issuer',
                                                          'client-ssl-version' => 'Client-SSL-Version',
                                                          'x-amz-rid' => 'X-Amz-Rid'
                                                        },
                                        'server' => 'Server'
                                      }, 'HTTP::Headers' ),
                 '_msg' => '',
                 '_request' => bless( {
                                        '_method' => 'POST',
                                        '_max_body_size' => undef,
                                        '_uri' => bless( do{\(my $o = 'https://sellingpartnerapi-fe.amazon.com/reports/2021-06-30/reports')}, 'URI::https' ),
                                        '_content' => '{"dataStartTime":"2024-05-14","reportType":"GET_XML_RETURNS_DATA_BY_RETURN_DATE","contentType":"application/json","marketplaceIds":["A1VC38T7YXB528"]}',
                                        '_headers' => bless( {
                                                               '::std_case' => {
                                                                                 'if-ssl-cert-subject' => 'If-SSL-Cert-Subject',
                                                                                 'x-amz-date' => 'X-Amz-Date',
                                                                                 'x-amz-access-token' => 'X-Amz-Access-Token'
                                                                               },
                                                               'x-amz-date' => 'Sat Jul 13 07:03:16 2024Z',
                                                               'content-type' => 'application/json',
                                                               'user-agent' => 'libwww-perl/6.66',
                                                               'x-amz-access-token' => 'Atza|IwEBIE4zsg-zocTGvsDnOQuoSCZKBSmHsEBbpCJtGunEgiksbRWxPCk5zuHYIv7f4L1QfuOJkFOZyuUNROfR8s-oAJ4XVPI1WcJftcXkUjDitLfyioFq-pZ1ijq8WeAcHDY-b4w9qDVV0DoUe2-q3wAyazuVHvZ6CNHtUlnpwHvLENzUtv0VKnwqbqNSuLyhl-Fi7rhUdORKZ19HMOLT6iSbBMPaaK_RXQWvgpp7Rqx0MYsDNNI3gZ9DnfT0U5CQt_92MPKjpIPZ2Gqt38FeRoYwATu55j5c_mQsEcRQevQGSKX2wApxX6kqm8cNZ5fioPevPZV8PZx2ayJ6N9GVBwh7Fy97DfCiLAO7pe2jdcCZE39ngw'
                                                             }, 'HTTP::Headers' ),
                                        '_uri_canonical' => $VAR1->{'_request'}{'_uri'}
                                      }, 'HTTP::Request' ),
                 '_protocol' => 'HTTP/1.1'
               }, 'HTTP::Response' );
reportId: 162341019917
uri[https://sellingpartnerapi-fe.amazon.com/reports/2021-06-30/reports/162341019917]
processingStatus: IN_QUEUE
uri[https://sellingpartnerapi-fe.amazon.com/reports/2021-06-30/reports/162341019917]
processingStatus: CANCELLED
Use of uninitialized value $reportDocumentId in concatenation (.) or string at test.pl line 192.
reportDocumentId:


----

**Comment by mafge** [comment]
Hi @sugaular,
thanks for providing more information!
Something that I noticed is that `dataStartTime` needs to be in `DateTime` format as per [specification](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#createreportspecification). More details on date time formatting can be found [here](https://developer-docs.amazon.com/sp-api/docs/iso-8601).

Best,
Marc
Selling Partner Developer Services

**Comment by sugaular** [comment]
"dataStartTime":"2024-05-17T00:00:00Z"
I tried this and it was the same.

**Comment by mafge** [comment]
@sugaular Have you tried to request the report with a shorter period for `dataStartTime`, e.g. like 10 days?

**Comment by sugaular** [comment]
"dataStartTime":"2024-05-07T00:00:00Z"
is processingStatus: FATAL

**Comment by mafge** [comment]
@sugaular You can only request a period of 60 days. So if you don't explicitly specify an end date for 2024-05-07 it will fail because end date will be set to today. Which will result in a period longer than 60 days.

So what I meant with setting a shorter period is something like trying `dataStartTime` set to 2024-07-07 and check whether that works or not. I have seen some cases where your reports get cancelled when there is too much data in the given time period. That is why I meant to shorten the period to double check that this is not the case for you.

**Comment by sugaular** [comment]
Sorry.
I got the date wrong.
"dataStartTime":"2024-07-07T00:00:00Z"
is "processingStatus: CANCELLED".

**Comment by mafge** [comment]
Thanks for the information provided. I recommend to contact [developer support](https://developer.amazonservices.com/support). They will work with you to resolve the issue. Thanks!
