### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 updateShipmentTrackingDetails UpdateShipmentTrackingDetails cannot be processed because the following invalid boxIds were found in the request: [FBA185PR4JRNU000001] 

### ISSUE THREAD

**Issue by HaHaVip123** [amzn/selling-partner-api-models#4006]
![Uploading QQ20240704-171325@2x.png…]()

**Comment by HaHaVip123** [comment]
<img width="509" alt="QQ20240704-171325@2x" src="https://github.com/amzn/selling-partner-api-models/assets/173242862/7adb1b72-5994-49ba-9154-c39df19607c8">
Why cannot the returned boxId update logistics information

**Comment by Ironkyy** [comment]
Is this problem solved now? I'm having the same problem now

**Comment by wonsky87** [comment]
I have the same trouble.

**Comment by alexftian** [comment]
Have same problem here, seems to be a schema validation error?

**Comment by puppsupr** [comment]
Hi, 
Are the IDs matching with what you see on https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplanboxes or listShipmentBoxes ?

**Comment by superauu** [comment]
I'm having the same problem.
I'm using a boxID that is identical to the BoxId returned by ListShipmentBoxes and ListInboundPlanBoxes.

**Comment by zhihui** [comment]
> I'm having the same problem. I'm using a boxID that is identical to the BoxId returned by ListShipmentBoxes and ListInboundPlanBoxes.

Me too

**Comment by puppsupr** [comment]
Please provide actual request and response to check the issue. Along with the inboundPlanId.

**Comment by wanjj2014** [comment]
@HaHaVip123  hi, I'm having the same problem. is the problem solved now?

**Comment by puppsupr** [comment]
Can you please provide actual request and response to check the issue. Along with the inboundPlanId.

**Comment by chuckchill** [comment]
@puppsupr hi,I'm having the same problem. 
request:
inbound/fba/2024-03-20/inboundPlans/wf7a9ff614-b69e-4ea0-baa8-6aac183f592e/shipments/sh34a7976f-df5e-4f39-b02e-eff60f35e64e/trackingDetails
`{
    "trackingDetails": {
        "spdTrackingDetail": {
            "spdTrackingItems": [
                {
                    "boxId": "FBA15JGS4KPNU000002",
                    "trackingId": "GHJ129"
                },
                {
                    "boxId": "FBA15JGS4KPNU000003",
                    "trackingId": "GHJ121"
                }
            ]
        }
    }
}`
response:
`
{
    "errors": {
        "code": "BadRequest",
        "message": "ERROR: UpdateShipmentTrackingDetails cannot be processed because the following invalid boxIds were found in the request: [FBA15JGS4KPNU000002, FBA15JGS4KPNU000003]",
        "details": ""
    }
}`

**Comment by puppsupr** [comment]
checking with team on this.

**Comment by heren9182** [comment]
Has anyone solved this problem?

**Comment by puppsupr** [comment]
Hi [chuckchill](https://github.com/chuckchill),

The root cause of the issue is that you are attempting to update the SPD (Small Parcel Delivery) tracking details, but the workflow data shows that you had chosen the LTL (Less Than Truckload) transportation option. You should update the LTL tracking details instead of the SPD tracking details.

The UpdateShipmentTrackingDetails API for updating LTL tracking should be as below,

{
  "trackingDetails": {
    "ltlTrackingDetail": {
      "freightBillNumber": [
        "{{freightBillNumber}}"
      ]
    }
  }
}

**Comment by HaHaVip123** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
