### ISSUE TITLE
Cannot query the catalog

### ISSUE THREAD

**Issue by gaelayo** [amzn/selling-partner-api-models#4007]
Hello, 
I am trying to request data from the catalog in a very simple way, with the following Python script:

```
import requests

query = {
      "marketplaceIds": "ATVPDKIKX0DER",
      "keywords": "shoes"
}

headers = {
        "x-amz-access-token": <REDACTED>,
        "User-Agent": <REDACTED>
    }
    

items = requests.get("https://sellingpartnerapi-na.amazon.com/catalog/2022-04-01/items", data=query, headers=headers)
print(items)
print(items.content)
```

However, the output looks like:

```
<Response [400]>
b'<!DOCTYPE html><html><head><title>x</title></head><body></body></html>\n'
```

without much details, as you can see.

Could you tell me what is wrong with the previous request ?

**Comment by harguph** [comment]
Hello,

Per the [searchcatalogitems](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#get-catalog2022-04-01items) api, I was able to make the call successfully. 

<img width="1062" alt="Screenshot 2024-07-05 at 12 31 01" src="https://github.com/amzn/selling-partner-api-models/assets/89893499/2edf79a0-7948-47fb-80df-8d5d986ca1ba">


It seems the invocation configuration is wrong, please check your requests.get code ( for passing query parameters it must be params= and not data= refer : https://requests.readthedocs.io/en/latest/user/quickstart/#passing-parameters-in-urls  )

Regards
