### ISSUE TITLE
BuyerCustomizedInfo CustomizedURL connect ETIMEDOUT

### ISSUE THREAD

**Issue by ronaldofreitas** [amzn/selling-partner-api-models#4008]
In our integration with SP-API we need to get the URL data from BuyerCustomizedInfo CustomizedURL, and this is working, but with some frequency it has given an error:

connect ETIMEDOUT [52.46.134.66:443](https://52.46.134.66/)

Here is part of the code and environment.

const zipurl = 'URL_CustomizedURL'
const orderItemId = '_ORDER_ITEM_ID'
const outputPath = `./zip_files/${orderItemId}.zip`
await axios({
  method: 'GET',
  url: zipurl,
  responseType: 'stream'
}).then(response => {
    const writer = createWriteStream(resolve(outputPath))
    response.data.pipe(writer)
    return new Promise((resolve, reject) => {
        writer.on('finish', resolve)
        writer.on('error', reject)
    });
}).then(async () => 

...

const buyerInfoEndpoint = `/orders/v0/orders/${orderId}/orderItems/buyerInfo`
const rdt_object_buyerinfo = {"method": "GET", "path": `${buyerInfoEndpoint}`}

...

"axios": "^1.6.8"
Nodejs V18
Ubuntu 23.04

Does anyone have any idea why this happens completely unexpectedly and randomly, while everything else works correctly?

**Comment by leonardonakagawa** [comment]
Hello @ronaldofreitas,

Thank you for reaching out regarding Orders API.

Could you please share what is the API response when you face issues? 

Take in consideration that the BuyerCustomizedInfo is an optional field, that can be sent only for attribute is only available for MFN (Fulfilled by the seller) orders.

Buyer information for custom orders from the Amazon Custom program.

You can find details regarding this in our [ItemBuyerInfo](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#itembuyerinfo).

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
