### ISSUE TITLE
createInboundShipmentPlan has misleading error message and documentation

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#401]
Various error messages return "This operation may be partially successful, Please check the status." which is misleading/incorrect. No part of the create plan is successful after this error. Also "Please check the Status" appears to be a nonsense statement in this case. There's no "Status" to check on. The call has failed, and that's the end of it.

The documentation at https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#createinboundshipmentplan indicates that HTTP 400 is reserved for "Request has missing or invalid parameters and cannot be parsed."  However this is not true, as there is at least one failure that was nothing to do with the request being "parsed". The "and cannot be parsed" should be removed from the above documentation sentence.

See for example:

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "This operation may be partially successful, Please check the status. Reason: [Item(s) ineligible from being inbounded, with reason: ITEM_STRANDED. Corresponding items for the error: [[FNSKU: ********, MSKU: *******]]].",
      "details": ""
    }
  ]
}
```

(I redacted the skus in the above.) (I originally noticed this in bug amzn/selling-partner-api-models#1212 but it deserves its own bug.)

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. We have noted & forwarded this to the relevant team for review & action.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
