### ISSUE TITLE
feeds api  POST_FLAT_FILE_FBA_CREATE_REMOVAL  .xsd Get it from there.?

### ISSUE THREAD

**Issue by shadowJourney** [amzn/selling-partner-api-models#4010]
![image](https://github.com/amzn/selling-partner-api-models/assets/112471375/884f36a7-ec74-484d-9e18-251e709ab4dd)

As the above picture, I don't know the specific parameter format and type of the pass parameter because I don't have the related XSD, does anyone know or have the related .XSD file to provide it to me?

thank you.

**Comment by jawheral** [comment]
Hi @shadowJourney,

This feed requires a flat file and so you don't need an XSD for POST_FLAT_FILE_FBA_CREATE_REMOVAL.

You can use Seller Central to find and download the flat file template. Please search for "Remove inventory in bulk" under FBA Inventory for more details.

Best,
Jawher
SP-API Solutions Architect

**Comment by shadowJourney** [comment]
@jawheral Thank you very much. I'll try it.

**Comment by jawheral** [comment]
Hi @shadowJourney,

Thank you for reaching out. Closing this issue for now. Feel free to reopen if you have further questions.

Best,
Jawher
SP-API Solutions Architect
