### ISSUE TITLE
[SP-API]Fulfillment Inbound API v2024-03-20: After creating inbound shipment via SP-API, Send to Amazon UI is abnormal : "Step 4: Confirm carrier and pallet information" and "Final step: Tracking details" missing!!!

### ISSUE THREAD

**Issue by he0212** [amzn/selling-partner-api-models#4011]
I creating inbound shipment via SP-API, then I found Send to Amazon UI is abnormal : "Step 4: Confirm carrier and pallet information" and "Final step: Tracking details" are not displayed.

The inbound plan were devided into 5 shipments ,and their shipping modes  were consist of SPD and LTL. Once LTL appear , UI will display "Step 4: Confirm carrier and pallet information" normally. BUT now it's missing! What's more ,the next step "Final step: Tracking details" is missing too.

Anyone else come across this case? How to solve this problem?

![PixPin_2024-07-08_17-28-27](https://github.com/amzn/selling-partner-api-models/assets/173978125/c9f208a1-a290-4cb9-ba3f-090191ca25ea)

**Comment by he0212** [comment]
@puppsupr  Hi, I need your help sincerely.

**Comment by he0212** [comment]
Hi @puppsupr 

I do have created an inbound plan, which was devided into 5 shipments, and 3 shipments were small parcel delivery, the other 2 were LTL. 

I'm so sorry it's a little bit hard for me to search the details about request and response , as it's a little long ago since now.

**As of the time I opened this issue**, my call flow was these steps:

1.createInboundPlan
2.generatePackingOptions
3.listPackingOptions
4.listPackingGroupItems
5.confirmPackingOption
6.setPackingInformation
7.generatePlacementOptions
8.listPlacementOptions
9.getShipment
10.listShipmentBoxes
11.generateTransportationOptions
12.listTransportationOptions
13.generateDelieryWindowOptions
14.listDelieryWindowOptions
15.confirmPlacementOptions
16.getShipment
17.confirmDelieryWindowOptions
18.confirmTransportationOptions
19.getLabels

**Comment by puppsupr** [comment]
Hi [he0212](https://github.com/he0212),
LTL options will only be generated if you provide pallet information in [generateTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatetransportationoptions)

**Comment by he0212** [comment]
> Hi [he0212](https://github.com/he0212), LTL options will only be generated if you provide pallet information in [generateTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatetransportationoptions)

Hi @puppsupr ,

I think maybe what you said has nothing to do with my problem. Becacuse I had generate some LTL options on previews step, and that's how I choose LTL option to be my shippinng mode.

**Comment by wimoor-erp** [comment]
me too

**Comment by he0212** [comment]
> me too

Hi @wimoor-erp，

Whta's the situation your issue happen? Mainly about the **shipping mode you choose in a whole inbound plan**.

Now I create a new inbound, and spilt into 2 shipments. Then I choose LTL shipping mode for both of them. Later I found this inbound in STA UI display as normal as others.

I subspect maybe the abnormal UI webpage is caused by the mixed shipping mode I used to chose, as my issue happened when I choose 2 LTL and 3 SPD, and now succeed when choosing all LTL shipping mode. It's a Amazon bug.

**Comment by gu-te** [comment]
> > 我也是
> 
> 你好@wimoor-erp，
> 
> 您遇到的问题是什么情况？主要与**您在整个入库计划中选择的运输方式**有关。
> 
> 现在我新建一个入库单，分成2个货件，然后两个货件都选择LTL运输方式，后来发现这个入库单在STA UI上显示和其他入库单一样正常。
> 
> 我怀疑 UI 页面异常可能是我之前选择的混合运输模式造成的，因为我的问题发生在我选择 2 LTL 和 3 SPD 时，而现在选择所有 LTL 运输模式时成功了。这是亚马逊的一个错误。

问一下，选择LTL和SPD是在哪个接口选的，listTransportationOptions所展示的运输方式全部都是LTL,并没有SPD,   执行generateTransportationOptions，我也并没有提供托盘信息，我需要选择SPD
