### ISSUE TITLE
How to upload Aces data through the SP API

### ISSUE THREAD

**Issue by JokeLove0915** [amzn/selling-partner-api-models#4012]
Now we are trying to upload Aces data to Amazon through the SP API, but it seems that we have not found any interface related to this. Can you help us answer this question

**Comment by harguph** [comment]
Hello @JokeLove0915 ,

Can you describe your use-case in detail and share screenshots, examples & more to understand the requirement.

**Comment by JokeLove0915** [comment]
Hello @harguph  ,  I haven't written any related demos yet. In the existing documentation, I tried to find the relevant API but couldn't find it

**Comment by harguph** [comment]
Can you explain your use-case ?

**Comment by ritikacd** [comment]
Hi @JokeLove0915 

Thanks for reaching out! If you are looking to upload ACES/Fitment data for your automobile listings to Amazon via SP-APIs, you can use Feeds API of [POST_STD_ACES_DATA](https://developer-docs.amazon.com/sp-api/docs/listings-feed-type-values#aces-30-data-automotive-part-finder-feed) Feed type to upload the information. 

Please reach out if you have additional questions.

Thank you, 
Ritika Chaudhary
Selling Partner API Team

**Comment by ritikacd** [comment]
Hi @JokeLove0915 

Do you still have questions for uploading ACES data through SP-APIs? 

Thanks,
Ritika

**Comment by andygravs** [comment]
Hi @ritikacd , reopening this thread. I'm looking for any feed type called POST_STD_ACES_DATA, it looks like the original link you sent just drops me on to the [listing feed types values section](https://developer-docs.amazon.com/sp-api/docs/listings-feed-type-values#aces-30-data-automotive-part-finder-feed) but it doesn't show POST_STD_ACES_DATA as one of your supported feed types. Has this been deprecated or moved somewhere?

**Comment by ritikacd** [comment]
> Hi [@ritikacd](https://github.com/ritikacd) , reopening this thread. I'm looking for any feed type called POST_STD_ACES_DATA, it looks like the original link you sent just drops me on to the [listing feed types values section](https://developer-docs.amazon.com/sp-api/docs/listings-feed-type-values#aces-30-data-automotive-part-finder-feed) but it doesn't show POST_STD_ACES_DATA as one of your supported feed types. Has this been deprecated or moved somewhere?

Hi @andygravs, Support for sending fitment data using `POST_STD_ACES_DATA` Feed type is no longer available through SP-APIs. Please use the Automotive Fitment Manager (AFM) tool in Vendor Central/Seller Central in order to submit fitment data instead. Refer to [Overview of Automotive Fitment Manager (AFM)](https://sellercentral.amazon.com/help/hub/reference/G201710040?mons_sel_mkid=amzn1.mp.o.ATVPDKIKX0DER&mons_sel_mcid=amzn1.merchant.o.AMY6FKRUBY7XV&mons_sel_persist=true) for more details. 

Thank you, 
Ritika
