### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 confirmTransportationOptions Provided shipment ids [shcf0c60e6-6d52-4265-b1fb-4bc4411ec0a2] do not match the shipments in the confirmed placement option

### ISSUE THREAD

**Issue by HaHaVip123** [amzn/selling-partner-api-models#4013]
Unable to confirm logistics when assigning multiple shipment ids

**Comment by HaHaVip123** [comment]
![Uploading 321.png…]()

**Comment by HaHaVip123** [comment]
<img width="689" alt="321" src="https://github.com/amzn/selling-partner-api-models/assets/173242862/a47455e5-49c7-4fe5-a906-432d07d2fe7a">

**Comment by HaHaVip123** [comment]
<img width="731" alt="345" src="https://github.com/amzn/selling-partner-api-models/assets/173242862/1d731158-8bf5-4530-ad3a-29ef2bb25c33">

**Comment by puppsupr** [comment]
Hi [HaHaVip123](https://github.com/HaHaVip123),
Are you still facing this issue ?

**Comment by BluePositive** [comment]
I have the same issue

**Comment by puppsupr** [comment]
Please provide complete request and responses for full flow if you still see the same issue.

**Comment by HaHaVip123** [comment]
Has this problem been solved? I still have this problem. I cannot confirm the logistics information when there are multiple shipments.

**Comment by HaHaVip123** [comment]
@puppsupr

**Comment by HaHaVip123** [comment]
@puppsupr Has this problem been solved? I still have this problem. I cannot confirm the logistics information when there are multiple shipments.

**Comment by puppsupr** [comment]
Hi team,
As requested before, Please provide complete request and responses along with inbound planID for full flow if you still see the same issue.
