### ISSUE TITLE
ListPlacementOptions returns always empty placementOptions list in the response

### ISSUE THREAD

**Issue by maxim-saltanov-skuvault** [amzn/selling-partner-api-models#4017]
I am trying to implement the new workflow https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow for the case when "box packing info" is "NO":
CreateInboundPlan -> GeneratePlacementOptions -> ListPlacementOptions -> ConfirmPlacementOptions

But stuck on the **ListPlacementOptions** step - it's always returns empty response: {"pagination":{},"placementOptions":[]}

I researched and found out an initial reason

When I try to request the status of any **GeneratePlacementOptions** operation, after the first query I get status = IN_PROGRESS and a few seconds after the second status = FAILED with details
![image](https://github.com/amzn/selling-partner-api-models/assets/80940351/7f33ddb8-eeea-4dc5-b87d-fae6983a60a2)

If I try to request the status of CreateInboundPlan, I see the next problem for an item I am trying to send "approval is required before this item can be sent to Amazon":

![image](https://github.com/amzn/selling-partner-api-models/assets/80940351/f5a6716e-6df2-4cc4-964b-700625205aca)

Any reason and how to fix it?

**Comment by puppsupr** [comment]
Hi [maxim-saltanov-skuvault](https://github.com/maxim-saltanov-skuvault),
Are you still facing this issue ?
