### ISSUE TITLE
[SP-API]Fulfillment Inbound API v2024-03-20 updateShipmentTrackingDetails 

### ISSUE THREAD

**Issue by he0212** [amzn/selling-partner-api-models#4018]
I plan to update tracking number for my  LTL shipment.

I call operation `updateShipmentTrackingDetails`，request:
`{"trackingDetails":{"ltlTrackingDetail":{"freightBillNumber":["***"]}}}`

 I get a success response:
`{"operationId":"***"}`

Then I call operation `getInboundOperationStatus` to check previous operation, get a response for:
`{"operationStatus":"FAILED","operationId":"***","operation":"updateShipmentTrackingDetails","operationProblems":[]}`

It shows my operation finish processing, but in a failed state. What's more, the operationProblems was empty. I can't know why it failed.

How to solve this preblem?

**Comment by mafge** [comment]
Hi @he0212,
thanks for reaching out!
The fulfillment inbound shipment workflow is quite complex. Please check this [workflow diagram](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow) in the use case guide to make sure that you did not miss any of the required steps before calling `updateShipmentTrackingDetails`.
If that doesn't help feel free to reach out to the [developer support](https://developer.amazonservices.com/support). They can check if your account is properly setup and all required information is available.

Best,
Marc
Selling Partner Developer Services

**Comment by he0212** [comment]
Hi @mafge ,

The use case guide doesn't mention which step is required or not. I do skip some steps as I think some steps are noting to do with my process.

I skipped the `GetBillofLading` and `ListInboundPlanBoxes`, please help me to check out whether thoes 2 steps are necessary step leading my fault.

 What's more,  I tried to update tracking number for my SPD shipment.  And I succeeded... It's so strange

**Comment by mafge** [comment]
Hi @he0212,
have you tried to follow the [tutorial]https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#tutorial-creating-a-shipment-when-the-seller-does-not-know-the-carton-level-information-up-front) in the use case guide? This gives you a step by step description of which calls needs to be done and which information needs to be provided.

If that doesn't help please reach out to our [developer support](https://developer.amazonservices.com/support).
Best,
Marc
Selling Partner Developer Services

**Comment by he0212** [comment]
Every time I create the inbound plan are  following the call order below:
1.createInboundPlan
2.generatePackingOptions
3.listPackingOptions
4.listPackingGroupItems
5.confirmPackingOption
6.setPackingInformation
7.generatePlacementOptions
8.listPlacementOptions
9.getShipment
10.listShipmentBoxes
11.generateTransportationOptions
12.listTransportationOptions
13.generateDelieryWindowOptions
14.listDelieryWindowOptions
15.confirmPlacementOptions
16.getShipment
17.confirmDelieryWindowOptions
18.confirmTransportationOptions
19.getLabels
20.updateShipmentTrackingDetails

My SPD shipments were updated successful, while LTL  shipments failed.

I follow the tutorial, but skip the `GetBillofLading` and `ListInboundPlanBoxes` , as it's useless to me.

**Comment by mafge** [comment]
Hi @he0212,
the order of calls looks fine for me. Also `GetBillofLading` and `ListInboundPlanBoxes` are not required, this is just for you getting the information in case you need it.

I would suggest you reach out to [developer support](https://developer.amazonservices.com/support).
Best,
Marc
Selling Partner Developer Services

**Comment by he0212** [comment]
> Hi @he0212, the order of calls looks fine for me. Also `GetBillofLading` and `ListInboundPlanBoxes` are not required, this is just for you getting the information in case you need it.
> 
> I would suggest you reach out to [developer support](https://developer.amazonservices.com/support). Best, Marc Selling Partner Developer Services

Fine, thank you for your generous help.

**Comment by mafge** [comment]
Sure, please don't hesitate to reach out in case of other questions.
