### ISSUE TITLE
Document (or remove) ITEM_STRANDED for createInboundShipmentPlan 

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#402]
The `ITEM_STRANDED` code is not documented, and needs to be.  One possible reason for that error code is if inventory is being sent for a SKU, where some other SKU in that ASIN has inventory in the so-called "stranded" status.  (In our case this occurred in bug amzn/selling-partner-api-models#401 due to inventory stuck in "FC Processing", but it could probably happen with regularly available inventory as well.)

If you hit this, a fix is apparently to change the so-called "stranded" SKU briefly from Closed to Open, then create the Shipment, and then restore the SKU to its correct Closed state again.  The problem is this pointless flip-flopping exposes a few seconds or minutes of a SKU being in the wrong state, and a sale could happen then for a SKU that you don't want being sold.

This all should be documented.... or just removed.  `ITEM_STRANDED` is a seemingly pointless check that has no benefit, and working around it exposes the SKU to problems.  It seems to be a case of FBA trying to warn you that you're sending inventory in when you don't need to be, but the warning is horrible and incorrect in this situation.  It's unclear what situation it would possibly be useful for, but there needs to be some way to override it if it is going to remain.

**Comment by johnkw** [comment]
This is still an open API bug. This should not be closed, in order to allow everyone to see the current state of things.

**Comment by shreeharsh-a** [comment]
Please be advised that API related bugs will not be tracked on this repo i.e. selling-partner-api-models. Only issues related to this repo will be tracked to closure here. If this is still an issue, please reach out to developer support. Thanks again!

**Comment by johnkw** [comment]
It's long been the case that Amazon has irresponsibly ignored these bug reports. However, even if they are going to be ignored, the still-open bug reports should be left in the open state, so that the developer community can more easily find information on these bugs and discuss workarounds and other options.

Please leave open bugs open. Only close bugs that are fixed.

**Comment by johnkw** [comment]
@shreeharsh-a "developer support" is not capable of addressing issues like this.  This is something that needs to be communicated to the SP-API team.  In the mean time though this ticket should remain open so that the community can understand the state of existing open bugs.

**Comment by shreeharsh-a** [comment]
@johnkw thank you for your feedback but reaching out to developer support is the best mechanism to leverage as they can escalate / forward your issues, etc to the right backend team for resolution. Also, please use discussions instead of issues to keep things open so that the community can discuss etc.
