### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 listInboundPlanBoxes  Unable to obtain box information

### ISSUE THREAD

**Issue by HaHaVip123** [amzn/selling-partner-api-models#4025]
Unable to obtain box information 
use setPackingInformation  Upload successful but Unable to obtain box information

**Comment by sheep110** [comment]
how  did you  "setPackingInformation" upload  successful,  what's format, tks

**Comment by puppsupr** [comment]
Hi,
Please provide complete request and response along with inboundPlanId.
