### ISSUE TITLE
Invalid json schema for BAKEWARE product type.

### ISSUE THREAD

**Issue by marketplacehub-com** [amzn/selling-partner-api-models#4026]
Hi there, looks like SP API provides invalid json schema for BAKEWARE product type with version details: 

```
    "productType": "BAKEWARE",
    "displayName": "BAKEWARE",
    "productTypeVersion": {
        "version": "UAAAAAAAAAAAAAAAAlYD1to6_8U32A_6LXdwhrABdmMg=",
        "latest": true,
        "releaseCandidate": false
    }
```

When I try download product type details for that schema - I getting such exception from Newtonsoft:
`Newtonsoft.Json.Schema.JSchemaReaderException: Enum array must have at least one value. Path 'properties.item_shape.items.properties.value.anyOf[1].enum', line 1, position 39811.`

When I go to schema details I really see there is no values in enum array:

![image](https://github.com/user-attachments/assets/5326e07f-8c67-4630-9b20-df8fa7b59ba7)

Looks like like as part of json schema validation - there should be at least one value.

Pls advice.

**Comment by mafge** [comment]
Hi @marketplacehub-com,
thanks for reaching out!
Looks indeed like a bug, let me follow up internally and I come back to you as soon as I have more information.
Best,
Marc
Selling Partner Developer Services

**Comment by marketplacehub-com** [comment]
@mafge ,I also found same issue for following product types as well: BAKEWARE,  BAKEWARE_SET, BAKING_CUP, BAKING_PAN, BAKING_PAPER, BAKING_STONE

**Comment by mafge** [comment]
Hi @marketplacehub-com,
the problem has been fixed on the backend and will land in the API on 9/30/2024.
Thanks again for reaching out!
