### ISSUE TITLE
Handling the Winning Contribution Factor When Updating Listings

### ISSUE THREAD

**Issue by rugved-bodke-stigya** [amzn/selling-partner-api-models#4028]
After updating all the SKUs for an ASIN in a specific marketplace, the changes are not reflecting on the frontend catalog. However, when updating the attributes using the product template fill and upload, and selecting the product's winning country for that particular attribute, the changes reflect on the catalog quickly. When using the SP-API patch method, attributes are updated on the listing within a few minutes, but they do not reflect on the catalog even after waiting for several days.

Do we need to create an offer again for the updated product listing? I am referring to updating an existing listing item.

**Comment by rugved1991** [comment]
Hi @rugved-bodke-stigya,

Nice to run into another Rugved!
There is no way to influence the winning contribution through the APIs. You should only make sure if the values you sent through the submission in APIs are reflected on the seller or vendor catalog. If that doesn't happen, then open a developer support case to investigate the issue further after confirming there were no issues with the submission.
We do not guarantee that the submission you made on the SKU will show up on the ASIN as there might be other contribution winner for those attributes. But, If you are a brand owner and would like to override the values you see on the Amazon catalog for your ASINs, then you can open a seller support case to override the details.

Best,
Rugved
Solutions Architect, SP-API

**Comment by rugved-bodke-stigya** [comment]
Hi @rugved1991 

Appreciate your quick response!!!

Thank you for your response. I have a few follow-up questions and concerns:

> Influencing Winning Contribution:
> There is no way to influence the winning contribution through the APIs. You mentioned ensuring that the values sent through the APIs are reflected in the seller or vendor catalog. If the values do not reflect, we should open a developer support case to investigate further.

- How do we open a developer support case?

- I can confirm there are no issues with submission, as per the response received from the update listing API. However, it seems like the submission on the SKU might not show up on the ASIN due to other contribution winners.

> Contributor Countries for ASIN Attributes:
- How can we get the contributor countries for the ASIN attributes if other contributions are winning?

> Overriding Values as a Brand Owner:

- As a brand owner, you mentioned opening a seller support case to override details on the Amazon catalog for our ASINs. Given that we have 1000+ products listed on Amazon in different marketplaces, do you think opening a seller support case for updating individual/group attributes is an efficient way?

> Manual Request for Winning Contributors:

![image](https://github.com/user-attachments/assets/d5a963b5-dbec-44e7-9683-49d3b2f7d3ee)
- Currently, we are manually requesting the winning contributors for the products by creating a seller support case. The response file provides regions, not countries. How can we identify the specific country within a region (e.g., EU region with 10-12 countries)?

> Creating an Offer for Existing Listing Item:

- If we create an offer for the existing listing item, will it help reflect the changes quickly?


Could we schedule a 30-minute meeting to discuss these points further? This issue is currently a roadblock for us.

Best regards,

Rugved
Senior Software Engineer
Stigya

**Comment by rugved1991** [comment]
Hi @rugved-bodke-stigya,

You can use the below links to open a developer support case:
Developer Support EU: https://developer.amazonservices.co.uk/support
Developer Support NA: https://developer.amazonservices.com/support
Developer Support APAC: https://developer.amazonservices.com.au/support 

Unfortunately, there is no scalable way to override values on Amazon catalog as a brand owner. You have to use the seller support route to change these values. 

I am not aware of the process of requesting winning contributors. I wont be able to comment on how to get that information.

We recommend that if there already exists an ASIN which can be used for reselling, you can just create an Offer only listing using the ASIN details. You can check out [this tutorial](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#list-an-offer-for-an-item-that-already-exists-in-the-amazon-catalog) for more information on how to create an offer only listing. 
There is no significant difference in time, but the steps required to perform this workflow is different and the details you would need to submit this type of listing will be different.

Unfortunately, we wont be able to jump on a call, but happy to take more information regarding your use case for using the country_of_origin value from the Amazon catalog. This would help submit the feature request and provide data on the impact.

Best,
Rugved
Solutions Architect, SP-API

**Comment by J-W-Chan** [comment]
Use patchListingItem and flat file to update listing information, with different time intervals for reflecting on the frontend catalog. This should not be an issue of contribution value. We have encountered many times where the seller needs to modify it in the store backend before it can function properly

**Comment by rugved-bodke-stigya** [comment]
Hello @J-W-Chan,

Thank you for your response.

We have tried using patchListingItem and flat files to update listing information. However, we are facing issues where TF/TB updates are not reflecting on the frontend catalog, and we suspect it might be due to contribution value. You mentioned that this might not be the case and that modifications might be needed in the store backend.

Could you please provide more details or guidance on how to address this issue? Any specific steps or best practices would be greatly appreciated.

Best regards,
Rugved
Stigya

**Comment by rugved-bodke-stigya** [comment]
Dear Amazon Support Team,
@rugved1991 @chapmanjw 

I am reaching out for assistance regarding an ongoing issue with updating listing information via the patchListingItem and flat file methods. Despite opening GitHub issues, support cases with Amazon Seller Central, and Amazon SP-API developer cases, I have not received a satisfactory response.

The concept of "winning contributor" has been mentioned repeatedly, yet there is no clear documentation available to understand its importance or how it affects the process. In a recent thread with the Amazon Developer Support Team, Amalia mentioned that the winning contributor would not influence the TF image reflection on the catalog if it is provided by another merchant account.

For context, I created an app from Amazon Seller Central US using the primary user account, and obtained the seller ID and refresh token. However, the app is still in draft mode, which I suspect is because we registered the profile as a private developer profile. Our organization has multiple accounts and operates in different marketplaces with over 1000 ASINs.

Currently we are manually uploading product attribute update requests through the template file and upload process, specifically regarding the winning country. We are currently opening cases to get the winning contributor country for each ASIN, and receiving PSS files in response. Our primary requirement is to reflect the TF/TB changes on the catalog page.

Could you please provide detailed guidance on how to achieve this using the SP-API? Your assistance in this matter would be greatly appreciated. Apologies if my previous messages seemed frustrated or rude.

Thank you for your understanding and support.

Best regards,
Rugved
Stigya
