### ISSUE TITLE
Issue with Image Updates

### ISSUE THREAD

**Issue by abc1978785513** [amzn/selling-partner-api-models#4029]
Why do the images I update for the Polish site also get overwritten on the main German site? The ASINs are the same.

How can I update images for a single site independently?

**Comment by rugved1991** [comment]
Hi @abc1978785513,

Currently, the image submissions are done on the ASIN level. We do not support localized image submissions through the API. We have taken this as a feature request and informed the backend team that this is a highly requested feature. We cannot provide any ETAs on when this feature would be made available on the API. But, please feel free to subscribe to our RSS feed to receive notifications for future updates.

Best,
Rugved
Solutions Architect, SP-API
