### ISSUE TITLE
Report Cancellation Reasons are not documented correctly

### ISSUE THREAD

**Issue by kpconnell** [amzn/selling-partner-api-models#403]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
The documentation only describes two reasons a report has been cancelled, and that is not correct

**URL of the content on GitHub**
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2021-06-30.md

**Description of what the documentation currently says**
The report was cancelled. There are two ways a report can be cancelled: an explicit cancellation request before the report starts processing, or an automatic cancellation if there is no data to return.

**Description of what the documentation should say**
It should state the other reasons why a report has been cancelled.  At least one of those reasons is you are requesting it too frequently.  

**Screenshots**

**Additional context**

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by belalali0626** [comment]
Still a issue for me :/

**Comment by kpconnell** [comment]
The issue **is** related to the docs.

**Comment by johnkw** [comment]
FYI, the original bug report bug #393 was moved to "discussion" for some reason, even though it's a bug report and not a discussion: https://github.com/amzn/selling-partner-api-models/discussions/4037
