### ISSUE TITLE
GET_MERCHANT_LISTINGS_ALL_DATA report is using chartset:CP1252 ，getting incorrect characters 

### ISSUE THREAD

**Issue by liuzhenggang** [amzn/selling-partner-api-models#4031]
We use sp-api to download the GET_MERCHANT_LISTINGS_ALL_DATA report, and its response header Content-Type value is text/plain; charset=Cp1252.
 We use cp1252 to parse the file, and some characters will be parsed as question marks. For example, '＆' and '：' (Chinese colon)

**Comment by jawheral** [comment]
Hi @liuzhenggang,

Please check whether your report was compressed and which CompressionAlgorithm was it compressed with. You can find this in the `getReportDocument` endpoint response.

https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#compressionalgorithm

You can also follow the following guide to steps on how to [download and decompress a report](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-retrieve-a-report#step-2-download-the-report).


Best,
Jawher
Selling Partner API Solutions Architect

**Comment by liuzhenggang** [comment]
@jawheral  We will still encounter the problem of converting special characters into question marks when we use the method you described to pull the data again

**Comment by jawheral** [comment]
Hi @liuzhenggang,

I suggest that you request the report again and troubleshoot your decompress and decoding logic.

If you still face this issue, then I kindly ask you to contact [DeveloperSupport](https://developer.amazonservices.com/support) to report it.

Best,
Jawher
Solutions Architect - Selling Partner API

**Comment by liuzhenggang** [comment]
Hi@jawheral, 
 I tried again, but the problem still persists.
