### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 listShipmentBoxes or getLabels boxes with chaotic order

### ISSUE THREAD

**Issue by JuCongBoy** [amzn/selling-partner-api-models#4033]
After calling setPackingInformation to set the box number, calling getLabels and listShipmentBoxes to download the external packing list to return the box number and the corresponding weight are confused (currently only more than 10 boxes will be problematic).

@puppsupr
@chapmanjw 
@sungolivia 
@weilinggu 
@seanevan 
I sincerely need your help

**Comment by puppsupr** [comment]
Hi [JuCongBoy](https://github.com/JuCongBoy),
Can you please provide your request and response. What information you are looking for via the API ?

**Comment by JuCongBoy** [comment]
> Hi [JuCongBoy](https://github.com/JuCongBoy), Can you please provide your request and response. What information you are looking for via the API ?

I am providing you with some outer packing lists obtained through the getLabels interface. Of course, this is just one of the pictures, and I have also blurred important information
![Uploading defb724768572772a33740446a42eed.png…]()

**Comment by JuCongBoy** [comment]
[DGHM240723006（FBA187LBT20N）.pdf](https://github.com/user-attachments/files/16356720/DGHM240723006.FBA187LBT20N.pdf)

**Comment by JuCongBoy** [comment]
I provide a picture of the list of outer packaging that I have obtained through getLabels. Of course, this photo is one of several outer packing lists. I also obscured some private information
[defb724768572772a33740446a42eed.pdf](https://github.com/user-attachments/files/16356766/defb724768572772a33740446a42eed.pdf)

**Comment by JuCongBoy** [comment]
Hi [puppsupr](https://github.com/puppsupr)
May I ask if you are dealing with this problem?

**Comment by sheep110** [comment]
Hi， JuCongBoy:
How did  you   calling getLabels  successful,   can you tell me,
The error was : Provided SellerCartonIds are not valid     when  I calling getLables,   the   SellerCartonIds   where  are you got
Thanks

**Comment by JuCongBoy** [comment]
> Hi， @JuCongBoy : How did you calling getLabels successful, can you tell me, The error was : Provided SellerCartonIds are not valid when I calling getLables, the SellerCartonIds where are you got Thanks

I have not encountered this information, I can successfully get the outer packing list but the outer packing list is confused

**Comment by sheep110** [comment]
> > Hi， @JuCongBoy : How did you calling getLabels successful, can you tell me, The error was : Provided SellerCartonIds are not valid when I calling getLables, the SellerCartonIds where are you got Thanks
> 
> I have not encountered this information, I can successfully get the outer packing list but the outer packing list is confused

The  API： getLables ,  what do you  input  that the  'PackageLabelsToPrint'  param, thanks

**Comment by JuCongBoy** [comment]
> > > Hi， @JuCongBoy : How did you calling getLabels successful, can you tell me, The error was : Provided SellerCartonIds are not valid when I calling getLables, the SellerCartonIds where are you got Thanks
> > 
> > 
> > I have not encountered this information, I can successfully get the outer packing list but the outer packing list is confused
> 
> The API： getLables , what do you input that the 'PackageLabelsToPrint' param, I don't know where can found the SellerCartonIds , thanks

No input

**Comment by JuCongBoy** [comment]
> > > Hi， @JuCongBoy : How did you calling getLabels successful, can you tell me, The error was : Provided SellerCartonIds are not valid when I calling getLables, the SellerCartonIds where are you got Thanks
> > 
> > 
> > I have not encountered this information, I can successfully get the outer packing list but the outer packing list is confused
> 
> The API： getLables , what do you input that the 'PackageLabelsToPrint' param, I don't know where can found the SellerCartonIds , thanks
Pass only shipmentId, pageType, labelType, pageSize

**Comment by sheep110** [comment]
> > > > Hi， @JuCongBoy : How did you calling getLabels successful, can you tell me, The error was : Provided SellerCartonIds are not valid when I calling getLables, the SellerCartonIds where are you got Thanks
> > > 
> > > 
> > > I have not encountered this information, I can successfully get the outer packing list but the outer packing list is confused
> > 
> > 
> > The API： getLables , what do you input that the 'PackageLabelsToPrint' param, I don't know where can found the SellerCartonIds , thanks
> > Pass only shipmentId, pageType, labelType, pageSize

It's  tips : 1 validation error detected: Value null at 'cartonIdList' failed to satisfy constraint: Member must not be null     when  I   only  pass shipmentId, pageType, labelType, pageSize。
![image](https://github.com/user-attachments/assets/fa5872fb-da9d-4b28-854d-0bda754625de)

Did you  have encountered this information.

**Comment by puppsupr** [comment]
Hi,
For getLabels, you need to provide

{{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}

Here shipmentId must be the shipmentConfirmationId that you can fetch from v2024 getShipment operation.

**Comment by JuCongBoy** [comment]
@puppsupr 
Excuse me, are you dealing with this problem? Our team is waiting for your reply, thank you.

**Comment by JuCongBoy** [comment]
@puppsupr 
Hi
Excuse me, how is this problem going? Can you give me an answer?

**Comment by Christin519** [comment]
@JuCongBoy 
Hi , Can you tell me the parameters you used to call getLabels? Thanks!

**Comment by Christin519** [comment]
@puppsupr 
Hi excuse me, how is this problem going? Can you give me an answer?

**Comment by JuCongBoy** [comment]
Hi
[puppsupr](https://github.com/puppsupr)
Excuse me, are you investigating this problem? How can I solve this problem? Could you please reply?

**Comment by JuCongBoy** [comment]
@puppsupr 
This issue has been over for so long and so far you have not responded positively to this matter. How do we properly upgrade the Fulfillment Inbound API?

**Comment by puppsupr** [comment]
Hi [JuCongBoy](https://github.com/JuCongBoy), 
Sorry for the delay. What is the exact issue you are seeing ? Is it that the listShipmentBoxes not giving data that you have set using the setPacking ? or are you unable to print the labels ?

**Comment by JuCongBoy** [comment]
> Hi [JuCongBoy](https://github.com/JuCongBoy), Sorry for the delay. What is the exact issue you are seeing ? Is it that the listShipmentBoxes not giving data that you have set using the setPacking ? or are you unable to print the labels ?

When the shipment is more than 10 boxes, setPackingInformation such as Box1=20KG, subsequent calls to listShipmentBoxes or getLabels may return information that should be Box1=20KG instead of Box11=20KG.

**Comment by JuCongBoy** [comment]
@puppsupr 
I have provided everything you need. It has been quite some time since I raised the question. May I ask if you are currently investigating and resolving this issue?

**Comment by puppsupr** [comment]
Thanks for the info, can you provide both the call sample request responses along with inboundPlanId.

**Comment by JuCongBoy** [comment]
@puppsupr 
I'll provide you with an example of the request and the results returned later

**Comment by JuCongBoy** [comment]
@puppsupr 
I'll provide you with sample requests and results later
