### ISSUE TITLE
New boolean enumerated attributes causing problems to update listing with patchListingsItem

### ISSUE THREAD

**Issue by alexisbellido** [amzn/selling-partner-api-models#4034]
Hello, I have a few listings of the SHOES product type that I've been updating correctly using patchListingsItem and a Node.js library (https://github.com/amz-tools/amazon-sp-api)  for about a couple of years until a few days ago when SP-API stopped accepting my updates.

I noticed some new attributes had been added to the SHOES product type and they were not being updated via patchListingsItem: /attributes/gpsr_safety_attestation and /attributes/contains_pfas). The library I'm using just returns a generic internal error with no more details when this particular patchListingsItem operation fails.

Both of the attributes mentioned above are enumerated fields of type boolean, which I have already handled correctly in the past, and I wonder if there's something special about these new attributes or if this is a bug on Amazon's side.

I already created a support ticket (https://sellercentral.amazon.com/cu/case-dashboard/view-case?caseID=15656140621) for the SP-API team but unfortunately I only got two very generic responses that didn't help me.

Here's an example of one of the patches I'm using to call patchListingsItem:

```
        "patches": [
            {
                "op": "replace",
                "path": "/attributes/contains_pfas",
                "value": [
                    {
                        "marketplace_id": "ATVPDKIKX0DER",
                        "value": true
                    }
                ]
            }
        ],

```

I have also tested with "op": "add" and it didn't work either.

I use exactly the same data structure for similar attributes such as /attributes/batteries_required and they work just fine; my updates are reflected on my listings.

I tried to set /attributes/contains_pfas for my listing on Seller Central but the changes were not saved and Seller Central didn't report why so I'm wondering if this problem may go beyond SP-API; or maybe Seller Central uses SP-API too?

The schema coming from the Product Type Definitions API /attributes/contains_pfas (one of the problematic attributes) and /attributes/batteries_required (an attribute that works just fine) are practically identical, I'm including the relevant data below, and without spotting any difference there is difficult to figure out what may be causing these problems.

I have only tested with a few listings of the SHOES product type and have only identified the attributes I mentioned above but it's just common sense to assume that this could be happening with many other attributes and product types so before I embark on long, and potentially useless, journey to programmatically test all attributes for all product types I'd appreciate an official response from the Amazon team.

Thank you.

```
"contains_pfas": {
                    "meta": {
                        "title": "Contains PFAS",
                        "description": "Provide whether the item contains PFAS (perfluoroalkyl or polyfluoroalkyl substances), a common but complex group of synthetic chemicals.",
                        "type": "array",
                        "maxUniqueItems": 1
                    },
                    "value": {
                        "meta": {
                            "title": "Contains PFAS",
                            "description": "Provide whether the item contains PFAS (perfluoroalkyl or polyfluoroalkyl substances), a common but complex group of synthetic chemicals.",
                            "type": "boolean",
                            "selectOptions": [
                                [
                                    false,
                                    "No"
                                ],
                                [
                                    true,
                                    "Yes"
                                ]
                            ]
                        }
                    },
                    "marketplace_id": "ATVPDKIKX0DER"
                }
```

```
"batteries_required": {
                    "meta": {
                        "title": "Are Batteries Required",
                        "description": "Indicate if batteries are required.",
                        "type": "array",
                        "maxUniqueItems": 1
                    },
                    "value": {
                        "meta": {
                            "title": "Are batteries required?",
                            "description": "Select \"yes\" if batteries are required to power the item (or if the item is a battery) or \"no\" if they are not. Please note that an internal rechargeable battery is also considered a battery",
                            "type": "boolean",
                            "selectOptions": [
                                [
                                    false,
                                    "No"
                                ],
                                [
                                    true,
                                    "Yes"
                                ]
                            ]
                        }
                    },
                    "marketplace_id": "ATVPDKIKX0DER"
                },
```

**Comment by chapmanjw** [comment]
@alexisbellido There is an internal issue with the configuration for the `contains_pfas` attribute. I'm opening a ticket with the corresponding team to get this fixed and will update this issue once resolve. Thanks for reporting the issue.

**Comment by alexisbellido** [comment]
That's good to hear, @chapmanjw , just a reminder that I also identified a similar problem with `/attributes/gpsr_safety_attestation`.

Thank you.

**Comment by chapmanjw** [comment]
@alexisbellido The configuration for the `contains_pfas` attribute has been fixed and should be working for you now. The `gpsr_safety_attestation` attribute was not having the same configuration issue and I haven't found any requests containing it that resulted in a 500 internal server error like the other. Do you have a request id and timestamp I can look at for one of your requests where that attribute is not working as expected?

**Comment by alexisbellido** [comment]
Hey, @chapmanjw , I just retested my patchListingsItem call and everything is working as expected with `contains_pfas` now.

And you are correct, I couldn't see any problem with `gpsr_safety_attestation`.

Thank you for taking care of this issue.
