### ISSUE TITLE
"Relist" feed

### ISSUE THREAD

**Issue by JokeLove0915** [amzn/selling-partner-api-models#4041]
I tried to modify the end_date and checked that the end_date has been successfully modified, but the product has not been republished 

{
	"productType": "AUTO_PART",
	"patches": [{
		"op": "replace",
		"path": "/attributes/purchasable_offer",
		"value": [{
			"currency": "USD"
		}, {
			"marketplace_id": "ATVPDKIKX0DER"
		}, {
			"start_at": {
				"value": "2024-07-21T08:09:51.000-07:00"
			}
		}, {
			"end_at": {}
		}]
	}]

**Comment by chapmanjw** [comment]
@JokeLove0915 We would need to investigate the state of this listing to identify what is preventing the listing from going live. I would recommend contacting developer support with the affected seller identifier and SKU for them to troubleshoot. Thanks.

https://developer.amazonservices.com/support
