### ISSUE TITLE
ProductType and Battery Attribute Field Required Issues

### ISSUE THREAD

**Issue by abc1978785513** [amzn/selling-partner-api-models#4043]
I chose "Lamp" as my ProductType, but it does not actually use batteries. However, the Listing API returns an error requiring me to fill in the 'power_plug_type' field. What should I do in this situation?

**Comment by mafge** [comment]
HI @abc1978785513,
thanks for reaching out!
The attribute `power_plug_type` is describing the type of power plug that you put in the wall. This has nothing to do with the battery. As this field is a enum you can check the JSON schema for available options (including `no_plug`).
Hope that answers your question!
Best,
Marc
Selling Partner Developer Services
