### ISSUE TITLE
[Feature request] Fulfillment Inbound API v2024-03-20 Allow adding custom fields or vendor SKU mappings to box labels

### ISSUE THREAD

**Issue by emakunin** [amzn/selling-partner-api-models#4045]
### Customer problem
We create inbound shipments to do FBA inbound. The shipments are handled by product suppliers. They ship the products from theirs warehouse. The problem comes from the fact that vendors have theirs own "Vendor SKU" to track the product while Amazon generates box labels using "Amazon SKU/FNSKU" as item identifiers. It makes it difficult for the vendor to understand how to label the product boxes as the vendors are not aware about Amazon IDs.

### Proposed solution
**Option1:** Once we create shipments from seller central we can specify a box template that then comes to the box label PDF. It would be nice to extend this functionality and to allow adding custom messages that would appear in the PDF so that all parties could easily understand the content.

**Option 2:** Amazon could share labels data in JSON-like format so that API clients could generate PDF files themselves.

**Comment by puppsupr** [comment]
Hi [emakunin](https://github.com/emakunin),
The FBA Inbound APIs are only available to sellers.

**Comment by emakunin** [comment]
Hi @puppsupr,

Yes. But as a seller i want to send shipment labels to my vendors. They will see my SKUs on the label and will have issues with understanding which box they should stick the labels to. As of now I have to generate a "map.xlsx" file with SKU -> Vendor SKU mappings. It would be nice if Amazon could include some short custom map to the label. Similar way you do for "box template name" that will be printed to the PDF if it's used. However I cannot use it via the inbound API.

**Comment by emakunin** [comment]
Hi @puppsupr,

Do you have any updates for this request? Is it feasible to implement it? Do we need to wait for this feature?

Also could you please confirm there's no way to add "Box template name" to the shipment label through the API?

I do not see it in the schema/docs. Our business team wishes an official amazon confirmation it is not possible to print the box templates through the api as it affects our integrations with vendors that expect box template names on the labels. With the api it does not work we have to manually create plans in SellerCentral. So we need to adjust our planning based on the responses.

**Comment by puppsupr** [comment]
Hi @emakunin, What do you mean by box template ? Can you share sample ? FBA labels have FBA Inbound plan name.

**Comment by emakunin** [comment]
Hi @puppsupr ,

I mean box templates in seller central.
![image](https://github.com/user-attachments/assets/f3ac332c-341c-4a6d-9fb1-4df502c65ae9)

See https://www.youtube.com/watch?v=cdqvD3NaFpw

When you ship the items via sellercentral there's an option to provide a template name. However there's no way to provide it via the API. 

When we print shipment labels for shipments created via sellercentral that hat used box templates the labels contain the template name
![image](https://github.com/user-attachments/assets/d39b613f-93bd-4965-aa56-e86bcbee23f6)


However when I create the shipments using the API the highlited field contains just "P1-B1" text that makes it cryptic for the workers in the FC that handle the shipment. 

That is why we need to know how to provide the info. The problem is described here: https://github.com/amzn/selling-partner-api-models/issues/4044. I just noticed your reply there, sorry. So I can assume "it is planned for next release". Would it be a fair assumption?

**Comment by puppsupr** [comment]
[emakunin](https://github.com/emakunin), thanks for the detailed info. Yes so the set prep and label categories APIs will be released soon. Will pass this to product team to see if there are any alternatives for now.

**Comment by puppsupr** [comment]
Is this for multi-sku box labels ?

You should use the APIs that relate box IDs with shipment IDs and items/qty in the box to identify the right ones. Try using the [Postman Collections](https://www.postman.com/galactic-rocket-691225/selling-partner-api-for-fulfillment-inbound-fba-v2024/collection/wzuz1hj/fulfillment-inbound-api-v2024-fetch-inbound-plan-details) for fetching the inbound plan details to check. 

As of now you can't have custom labels.

**Comment by johnkw** [comment]
At the very least this bug should remain open until the documentation is updated on https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#boxinput to explain that there is currently no way to set the ` P1 - B121` values that mysteriously show up on the label PDF.
