### ISSUE TITLE
 Fulfillment Inbound v2024-03-20: Error on confirmTransportationOptions

### ISSUE THREAD

**Issue by Prez5er** [amzn/selling-partner-api-models#4048]
Hi team

I'm trying to create a shipment, but at the end of the workflow to generate it, the **confirmTransportationOptions** endpoints threw me an error once I checked it on the **getInboundOperationStatus**

![imagen](https://github.com/user-attachments/assets/175a5260-0c35-43f1-bbd4-037568cc34e9)

I previously checked the **getInboundOperationStatus** on each request and only this threw me an error, but I don't know what's going on.

**Comment by a344241086** [comment]
Fail to execute CONFIRM_CARRIERS API with errors.  这是怎么回事呢

**Comment by dishcheng** [comment]
> Fail to execute CONFIRM_CARRIERS API with errors. 这是怎么回事呢

[
                        'shipmentId' => $shipmentId,//use this 
//                        'placementOptionId' => $placementOptionId,//not use this
                        'pageSize' => 20
                    ]

**Comment by a344241086** [comment]
我也有遇到这种问题, 目前还没找到根本原因
&nbsp;


344241086
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月29日(星期一) 上午9:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [amzn/selling-partner-api-models]  Fulfillment Inbound v2024-03-20: Error on confirmTransportationOptions (Issue #4048)














  
Fail to execute CONFIRM_CARRIERS API with errors. 这是怎么回事呢
  
[
 'shipmentId' =&gt; $shipmentId,//use this
 //                        'placementOptionId' =&gt; $placementOptionId,//not use this
 'pageSize' =&gt; 20
 ]

**Comment by puppsupr** [comment]
Hi,
Are you still facing the issue ? If yes, can you please provide complete request and response along with inboundPlanId.

**Comment by emakunin** [comment]
Hi @puppsupr, I have same issue for one of my plans

Below request gives me a cryptic error that I'm not able to understand to fix
```
POST https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf29089345-c6a7-44a2-aed5-0d8d4a580ae7/transportationOptions/confirmation 

{
  "transportationSelections": [
    {
      "contactInformation": null,
      "shipmentId": "she72b775d-7a72-4b52-b36f-52e8ee8fe3df",
      "transportationOptionId": "tofdd3696f-061f-426d-8d44-9003088822d2"
    }
  ]
}
```

Response
```
operationalProblems=[class OperationProblem {
    code: BadRequest
    details: null
    message: ERROR: Fail to execute CONFIRM_CARRIERS API with errors.
    severity: ERROR
}]
```

**Comment by puppsupr** [comment]
Hi [emakunin](https://github.com/emakunin),
The use-case guide will be corrected. Thanks for the feedback.

Generate Transportation Request,

{
  "placementOptionId": "{{placementOptionId}}",
  "shipmentTransportationConfigurations": [
    {
      "readyToShipWindow": {
        "start": "{{startDate}}"
      },
      "shipmentId": "{{shipmentId}}",
      "contactInformation": {
        "name": "TestName",
        "phoneNumber": "1234567890",
        "email": "test@email.com"
      }
    }
  ]
}

Confirm transportation Request,

{
  "transportationSelections": [
    {
      "shipmentId": "{{shipmentId}}",
      "transportationOptionId": "{{transportationOptionId}}"
    }
  ]
}

You need to either omit the contact info or provide actual values. You cant write it as null.

**Comment by emakunin** [comment]
@puppsupr 

It doesn't help. I've sent

```JSON
{
  "transportationSelections": [
    {
      "shipmentId": "she72b775d-7a72-4b52-b36f-52e8ee8fe3df",
      "transportationOptionId": "tofdd3696f-061f-426d-8d44-9003088822d2"
    }
  ]
}
```

RESPONSE
```
{
  "operationId": "c94f5f70-cfd7-4cc2-80e7-aa3bd016b344"
}

{
  "operationStatus": "FAILED",
  "operationId": "7ef66731-e45f-4fff-9ae8-80d411171846",
  "operation": "confirmTransportationOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "BadRequest",
      "message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors."
    }
  ]
}
```

Note: operationId is a new one in the GetInboundOperationStatus reply. It is the exact API response, not a typo.

As per documentation it needs to be set only for LTL shipments. In my case it's SPD

> You cant write it as null.

Is it a new change? I was able to create quite some plans before passing exactly this payload. Even more.

**Comment by emakunin** [comment]
Hi @puppsupr, Any updates here? I still keep receiving same error and I see others do have it as well: https://github.com/amzn/selling-partner-api-models/issues/4102

**There are 2 problems here**:
1. Api error does not have any details of what went wrong while **sometimes** sellercentral can show you more details (see attachments)
   1. Sometimes the error can be related to "no capacity". Like in this ticket: https://github.com/amzn/selling-partner-api-models/issues/4107, that Amazon has been ignoring for long time. The error must be returned in the API response. Your customers cannot check every exception in seller central manually.
1. The error is not factually correct. I'm sure I've called all required APIs but the error still occurs during "confirmTransportationOptions" call

#### attachments
![Screenshot 2024-09-03 104644](https://github.com/user-attachments/assets/5836c0d8-f738-4746-9157-cf0a5666f211)

**Comment by hellokids86** [comment]
Any update here? We are also receiving the same error. It seems to work sometimes when different carriers are chosen. However in certain situations with Amazon Partnered LTL, we receive this error.

**Comment by emakunin** [comment]
Hi @puppsupr,

Do you have any updates? I keep receiving the erorr. (noted that most of them are related to UK marketplace/address)

#### Attachment
```
Request: POST https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/inboundPlans/wfe52d1cde-4c79-4484-ac99-91283f5e937e/placementOptions/pl46282e26-c0fa-4cab-bf7e-5e92f88624e1/confirmation Headers[***],
Body:
(empty)

Response: POST https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/inboundPlans/wfe52d1cde-4c79-4484-ac99-91283f5e937e/placementOptions/pl46282e26-c0fa-4cab-bf7e-5e92f88624e1/confirmation, Status[202 ], Headers[***],
Body:
{     "operationId": "74c70e5c-3943-4c55-8450-cf8b0b1a3521" }

....

Response GET https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/operations/74c70e5c-3943-4c55-8450-cf8b0b1a3521, Status[200 ], Headers[], 
Body:
{     "operationStatus": "SUCCESS",     "operationId": "64ccb29e-4720-4bbf-9dc8-50ef5312373f",     "operation": "confirmPlacementOption",     "operationProblems": [] }

....

 Request: POST https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/inboundPlans/wfe52d1cde-4c79-4484-ac99-91283f5e937e/transportationOptions/confirmation Headers[***],
Body:
{     "transportationSelections": [         {             "contactInformation": null,             "shipmentId": "sh4858d3fb-9461-4669-ba5d-034b2d858447",             "transportationOptionId": "tocdd67cb1-d0e8-4acd-bc85-f1379fa29a3b"         }     ] }

Response: POST https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/inboundPlans/wfe52d1cde-4c79-4484-ac99-91283f5e937e/transportationOptions/confirmation, Status[202 ], Headers[***],
Body:
{     "operationId": "7581b19c-3e43-4e19-b94f-f33ea06c86b5" }


Response: GET https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/operations/7581b19c-3e43-4e19-b94f-f33ea06c86b5, Status[200 ], Headers[***],
Body:
{     "operationStatus": "FAILED",     "operationId": "66322b0b-6add-4c7e-b583-3eb45bf8ff90",     "operation": "confirmTransportationOptions",     "operationProblems": [         {             "severity": "ERROR",             "code": "InternalServerError",             "message": "ERROR: Something went wrong. Please try again later."         }     ] }

... Retrying later ...

Request: GET https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/operations/b839fa84-135a-4c9d-93a9-a69479102db0 Headers[***],
Body:
(Empty body)

Response: GET https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/operations/b839fa84-135a-4c9d-93a9-a69479102db0, Status[200 ], Headers[***],
 Body:
{"operationStatus":"FAILED","operationId":"be58dccf-cd08-41db-996a-9852beea6f39","operation":"confirmTransportationOptions","operationProblems":[{"severity":"ERROR","code":"BadRequest","message":"ERROR: Fail to execute CONFIRM_CARRIERS API with errors."}]}

```

Can I at least have a reason of what went wrong

**Comment by hamduc7** [comment]
Dear All,

I have this exact problem with 2 shipments using a non-partnered Amazon carrier.
Then I tried another STA with only 1 shipment and it worked.

I have no idea about the error because the API only returns "**Fail to execute CONFIRM_CARRIERS API with errors**"

I hope the API returns the details of the error instead of a general error like that.

@mafge Could you please give us some instructions to troubleshoot the issue?

Thank you

**Comment by puppsupr** [comment]
Hi [emakunin](https://github.com/emakunin),
Checking with team on this.

[hamduc7](https://github.com/hamduc7), can you please provide your sample request and response.

Also we have this [Postman Collections](https://www.postman.com/galactic-rocket-691225/selling-partner-api-for-fulfillment-inbound-fba-v2024/overview) which you try use for different flows.

**Comment by hamduc7** [comment]
@puppsupr 

_inboundPlanId = wf0ed151e5-c5fa-48ff-abf1-8b22c50e3c83
These are the confirmTransportation request
`{
	"transportationSelections": [
		{
			"shipmentId": "sh92edb88c-c6af-4401-a995-672e763f3e09",
			"transportationOptionId": "to0fb4801a-1784-498c-a59d-cfbcf4670af4"
		},
		{
			"shipmentId": "shf35f281e-a8d2-4a83-9918-16cab12a2e0c",
			"transportationOptionId": "to0fb4801a-1784-498c-a59d-cfbcf4670af4"
		}
	]
}`

Response:
`{"operationId":"bb814235-4ef7-4550-bfdc-ed9358d7f0a0"}`

BadRequest
ERROR: Fail to execute CONFIRM_CARRIERS API with errors.

P/S: It works if I have one shipment.

Thank you

**Comment by hellokids86** [comment]
Try to include the delivery window went confirming your transport. This worked for me. The example provided by amazon online shows this but the docs don't.


{
   "transportationSelections" : [ {
     "contactInformation" : {
       "email" : "email@email.com",
       "name" : "John Smithy",
       "phoneNumber" : "1234567890"
     },
     "deliveryWindow" : {
       "start" : "2024-01-01T00:00Z"
     },
     "shipmentId" : "sh1234abcd-1234-abcd-5678-1234abcd5678",
     "transportationOptionId" : "to1234abcd-1234-abcd-5678-1234abcd5678"
   } ]
 }

**Comment by hamduc7** [comment]
Hi All,

I found the root reason in my case and I solved it. 
As mentioned, It works successfully if I have 1 shipment. But if I have 2 or more shipments I will receive that error.

What I see on Amazon UI confuses me. As you know, on Amazon, if you have 2 shipments ->you only select one shipping carrier. =>This causes me think all shipments have same Transportation Option Id.

In this case, you must set correct transportation Id for each shipment. As you know, let say the same UPS, and if you have 2 shipments, you will see 2 transportation ids.

**Comment by emakunin** [comment]
Hi @puppsupr ,

Thx for checking.

> I do see "contactInformation": null as I told you need to omit this or add [right structure](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#contactinformation).

As I told before, ommiting it **does not help**: https://github.com/amzn/selling-partner-api-models/issues/4048#issuecomment-2299382549. The same if I specify full contact details.

```
Request: POST https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/inboundPlans/wfef914ab2-5d3e-4ee8-aac4-929d3ce08373/transportationOptions/confirmation Headers[Authorization=***]
Body:
{     "transportationSelections": [         {             "contactInformation": {                 "email": "sa**a@e**h.com",                 "name": "**** *** ltd",                 "phoneNumber": "+44**********"             },             "shipmentId": "shcf968c59-d084-4651-96d9-59eaeb70bf47",             "transportationOptionId": "to23d44fa5-ad5d-4109-b936-d247921420aa"         }     ] }
Response:
{
    "operationId": "e0733a70-b011-4fcf-8297-0b3f224bbadd"
}


GET https://sellingpartnerapi-eu.amazon.com/inbound/fba/2024-03-20/operations/e0733a70-b011-4fcf-8297-0b3f224bbadd, Status[200 ], Headers[***],
Response:
{     "operationStatus": "FAILED",     "operationId": "8c2994a1-fb1a-42a4-b9b9-1d0b4b57f933",     "operation": "confirmTransportationOptions",     "operationProblems": [         {             "severity": "ERROR",             "code": "InternalServerError",             "message": "ERROR: Something went wrong. Please try again later."         }     ] }

```

I have only 1 shipment in my case (but 2 placement options)

**Comment by brandondev1** [comment]
An example of GenerateTransportationOptions 

```
{
  "placementOptionId": "pldb50c298-f6b0-4705-bd2e-0405ab4e7468",
  "shipmentTransportationConfigurations": [
    {
      "readyToShipWindow": {
        "start": "2024-09-20T00:00:00.000Z"
      },
      "shipmentId": "sh4a2e9733-4912-434d-bc54-ac6cfdf0aaef",
      "contactInformation": {
        "phoneNumber": "813-333-2233",
        "email": "sam@email.com",
        "name": "Sam Iam"
      },
      "pallets": [
        {
          "quantity": 1,
          "stackability": "NON_STACKABLE",
          "weight": {
            "unit": "LB",
            "value": 515
          },
          "dimensions": {
            "unitOfMeasurement": "IN",
            "length": 48,
            "width": 40,
            "height": 40
          }
        }
      ],
      "freightInformation": {
        "freightClass": "FC_50",
        "declaredValue": {
          "code": "USD",
          "amount": 1000
        }
      }
    },
    {
      "readyToShipWindow": {
        "start": "2024-09-20T00:00:00.000Z"
      },
      "shipmentId": "sh55961153-0cc6-4700-beaa-ab48e8db2f1d",
      "contactInformation": {
        "phoneNumber": "813-333-2233",
        "email": "sam@email.com",
        "name": "Sam Iam"
      },
      "pallets": [
        {
          "quantity": 2,
          "stackability": "NON_STACKABLE",
          "weight": {
            "unit": "LB",
            "value": 931
          },
          "dimensions": {
            "unitOfMeasurement": "IN",
            "length": 48,
            "width": 40,
            "height": 40
          }
        }
      ],
      "freightInformation": {
        "freightClass": "FC_50",
        "declaredValue": {
          "code": "USD",
          "amount": 1000
        }
      }
    },
    {
      "readyToShipWindow": {
        "start": "2024-09-20T00:00:00.000Z"
      },
      "shipmentId": "sh82936ced-0dba-4827-ab74-fd4f36bd845b",
      "contactInformation": {
        "phoneNumber": "813-333-2233",
        "email": "sam@email.com",
        "name": "Sam Iam"
      },
      "pallets": [
        {
          "quantity": 2,
          "stackability": "NON_STACKABLE",
          "weight": {
            "unit": "LB",
            "value": 1470
          },
          "dimensions": {
            "unitOfMeasurement": "IN",
            "length": 48,
            "width": 40,
            "height": 40
          }
        }
      ],
      "freightInformation": {
        "freightClass": "FC_50",
        "declaredValue": {
          "code": "USD",
          "amount": 1000
        }
      }
    }
  ]
}
```
Subsequent call to GetInboundOperationStatus:

```
{
  "operationStatus": "FAILED",
  "operationId": "e99673ae-d32f-4b41-ae9f-97370a78e041",
  "operation": "generateTransportationOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "BadRequest",
      "message": "ERROR: Fail to execute COMPUTE_TRANSPORTATION_OPTIONS API with errors."
    }
  ]
}

```

**Comment by hamduc7** [comment]
Hi @emakunin 
I am not sure but I only use shipmentId and transportationOptionId
I don't use contactInformation, deliveryWindow

Anyway, I think your structure is not correct, I don't see DeliveryWindow here:
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#transportationselection

In my case, the key point is the transportationOptionId MUST be belong to the shipmentId. As you know, you got the list of transportation based on each ShipmentId

Hope that help you.

**Comment by emakunin** [comment]
Hi  @hamduc7, Thx for the comment
 
>  I think your structure is not correct, I don't see DeliveryWindow here:

It was an suggestion from @hellokids86 to try. Normally I pass only docummented values.

>In my case, the key point is the transportationOptionId MUST be belong to the shipmentId. As you know, you got the list of transportation based on each ShipmentId

Yes, i use the corresponding one. 

Hi @puppsupr ,
I know it's not under your control, but could you please work with the owning teams to prioritise/escalate this problem?

I also see a similar problem for placement options (https://github.com/amzn/selling-partner-api-models/issues/4113). It blocks up to 50% plans i've tried to create last 2 days. **It makes the API not usable**. This is a Sev2+ issue. Many users have provided real requests with IDs. It should be feazible to check the logs and at least tell the reason what is wrong. 
For sure it can be my fault in using the API, but it's close to impossible to understand what is wrong based on the errors the API returns. 

50% ([26 out of 52 opeen issues](https://github.com/amzn/selling-partner-api-models/issues?q=is%3Aissue+is%3Aopen+Fulfillment+Inbound+)) in this repository are related to the new inbound api. **Most of the issues are open during 1-2 months**  I don't count closed ones.

 - "Customer obsession" (c) ?
 - "Insist on highest standards" (c) ? 
 
I believe it deserves a COE and an escalation. I'm sorry, but it looks like Amazon simply uses it's customers as a free QA team.

**Comment by brandondev1** [comment]
> Hi @hamduc7, Thx for the comment
> 
> > I think your structure is not correct, I don't see DeliveryWindow here:
> 
> It was an suggestion from @hellokids86 to try. Normally I pass only docummented values.
> 
> > In my case, the key point is the transportationOptionId MUST be belong to the shipmentId. As you know, you got the list of transportation based on each ShipmentId
> 
> Yes, i use the corresponding one.
> 
> Hi @puppsupr , I know it's not under your control, but could you please work with the owning teams to prioritise/escalate this problem?
> 
> I also see a similar problem for placement options (#4113). It blocks up to 50% plans i've tried to create last 2 days. **It makes the API not usable**. This is a Sev2+ issue. Many users have provided real requests with IDs. It should be feazible to check the logs and at least tell the reason what is wrong. For sure it can be my fault in using the API, but it's close to impossible to understand what is wrong based on the errors the API returns.
> 
> 50% ([26 out of 52 opeen issues](https://github.com/amzn/selling-partner-api-models/issues?q=is%3Aissue+is%3Aopen+Fulfillment+Inbound+)) in this repository are related to the new inbound api. **Most of the issues are open during 1-2 months** I don't count closed ones.
> 
> * "Customer obsession" (c) ?
> * "Insist on highest standards" (c) ?
> 
> I believe it deserves a COE and an escalation. I'm sorry, but it looks like Amazon simply uses its customers as a free QA team.

Absolutely.  We have spent so much time/money working through these errors and reporting them to Amazon.  I have submitted 9 of them with some being opened 3+ months ago with no resolution.

**Comment by puppsupr** [comment]
> Tried a trick suggested by @hamduc7, it does not work for me.
> 
> I tried different payloads and combination of delivery window property, but always get same error
> 
> ```json
> {
>     "transportationSelections": [
>       {
>           "contactInformation": {
>           "email": "***@***.com",
>           "name": "*** *** ltd",
>           "phoneNumber": "+44*********"
>         },
>         "shipmentId": "shde1ec09a-2ad7-4194-8a8a-d81cd5585829",
>         "transportationOptionId": "tocdb11961-45f1-4b99-974b-db8c4388715c",
>         "deliveryWindow": {
>           "id": "dw617ea900-6bf8-4435-9a15-a220663d2d70",  // tried to omit as well, data come from "generateDeliveryWindows options
>           "start": "2024-09-28T00:00Z",  // tried to select different dates and formats
>           "end": "2024-10-05T00:00" // tried to omit as well, data come from "generateDeliveryWindows options
>         }
>       }
>     ]
> }
> ```

Hi,
You shouldn't use the delivery window within the transportation options. We do have separate APIs.

Can you please let me know if you are using partnered carrier or non-partnered carrier ? Also are all your plans failing ?

**Comment by pacton** [comment]
Any word on this? We are getting deep in the year. You guys gonna call off the deadline until you get this POS fixed? There are all sorts of "show stopper" issues still. It is ridiculous that Amazon is doing this to your dev community ...

Half the time this request works - half it don't ...

POST /inbound/fba/2024-03-20/inboundPlans/wff22c3e70-b0ff-42f9-b3f6-e2be43a3daf5/transportationOptions/confirmation HTTP/1.1

{
  "transportationSelections": [
    {
      "shipmentId": "sh15a7dd23-d670-48a4-87a6-2a9e2efcf1dd",
      "transportationOptionId": "to10e08266-6912-4daa-9af1-bdd7f8ac78fc"
    },
    {
      "shipmentId": "sh2cc7b21e-88f5-4d93-b418-8bcd297941f8",
      "transportationOptionId": "to94ed749a-b616-43c5-963e-141a356c626f"
    },
    {
      "shipmentId": "sh4c827b0b-9f9e-4b99-9fa4-512bf7319111",
      "transportationOptionId": "to8f9a0491-3807-4caf-b833-2c1fe8742add"
    },
    {
      "shipmentId": "sh909f8416-f974-406d-96b1-cfe0e69a30d1",
      "transportationOptionId": "to744359da-13a1-45ea-aaef-0b108994b900"
    },
    {
      "shipmentId": "sh978ba295-7878-402a-b8a2-5188c9ed431d",
      "transportationOptionId": "toe8df2a60-7981-4489-8803-d315820932be"
    }
  ]
}
--------------
{
  "operationStatus": "FAILED",
  "operationId": "54e9fafa-d0c9-428d-b699-12eaaf42b0f1",
  "operation": "confirmTransportationOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "BadRequest",
      "message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors."
    }
  ]
}

**Comment by pacton** [comment]
Half the time this request will confirm - then the other half I get this ...

POST /inbound/fba/2024-03-20/inboundPlans/wff22c3e70-b0ff-42f9-b3f6-e0be4313daf5/transportationOptions/confirmation HTTP/1.1

{
  "transportationSelections": [
    {
      "shipmentId": "sh15a7dd23-d670-48a4-87a6-2a9e1efcf0dd",
      "transportationOptionId": "to10e08266-6912-4daa-1afe-bdd7f8ac78fc"
    },
    {
      "shipmentId": "sh2cc7b21e-88f5-4d93-b418-8bcd291941f8",
      "transportationOptionId": "to94ed749a-b616-43c5-961e-b41a356c626f"
    },
    {
      "shipmentId": "sh4c827b0b-9f9e-4b99-9fa4-512bf731111b",
      "transportationOptionId": "to8f9a0491-3807-4caf-b831-2c4fe8742add"
    },
    {
      "shipmentId": "sh909f8416-f974-406d-96b1-cfe0e69a31d6",
      "transportationOptionId": "to744359da-13a1-45ea-aaef-1b508994b900"
    },
    {
      "shipmentId": "sh978ba295-7878-402a-b8a2-5188c9ed431d",
      "transportationOptionId": "toe8df2a60-7981-4489-8803-d315820932be"
    }
  ]
}

--------------

{
  "operationStatus": "FAILED",
  "operationId": "54e9fafa-d0c9-428d-b699-12eaaf42b0f9",
  "operation": "confirmTransportationOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "BadRequest",
      "message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors."
    }
  ]
}

**Comment by puppsupr** [comment]
Hi [pacton](https://github.com/pacton),

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

**Comment by emakunin** [comment]
Hi @puppsupr,

I have exactly same behaviour. Some shipments (most of the times when there are more than 1 shipment per plan) simply fail without any details (pls check my samples above).

**Comment by MeenaAmz** [comment]
@emakunin Are you providing delivery window separately using delivery window operations([generateDeliveryWindowOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatedeliverywindowoptions),[listDeliveryWindowOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listdeliverywindowoptions),[confirmDeliveryWindowOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#confirmdeliverywindowoptions)) and still seeing failures? Delivery window options should not be added within [confirmTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#confirmtransportationoptions) operation. If that doesn't work please provide us with request/response examples and also raise a support case for troubleshooting if you haven't already. 

Thanks 
Meena
Selling Partner Developer Services

**Comment by puppsupr** [comment]
> Hi @puppsupr,
> 
> I have exactly same behaviour. Some shipments (most of the times when there are more than 1 shipment per plan) simply fail without any details (pls check my samples above).

Are you generating and confirming the transportation options including all the shipments for an inbound plan ? The v2024 APIs are at inbound level and you need to confirm all the shipmentIDs in a single call.

**Comment by capatina** [comment]
THIS API IS ABSOLUTE GARBAGE. AMAZON SHOULD BE ASHAMED

**Comment by weilinggu** [comment]
@emakunin Have you opened a support case regarding the issue you are encountering? If so, can you share the case ID so we can help investigate?
If you have not opened a support case, please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here.

Weiling
Amazon Selling Partner Services

**Comment by xyloneX** [comment]
> > 你好@puppsupr，
> > 我也有同样的情况。有些发货（大多数情况下，每个计划有多个发货）会直接失败，没有任何详细信息（请查看上面的示例）。
> 
> 您是否正在生成并确认包括入站计划的所有货物在内的运输选项？v2024 API 处于入站级别，您需要在一次调用中确认所有货物 ID。

@puppsupr 
Planid:wf7e69382a-8ed3-4e54-bd7d-1f8fa5e1b322

**Comment by puppsupr** [comment]
Hi @xyloneX,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

**Comment by johnkw** [comment]
See also bug #4253 which notes the only current workaround is delete everything and retry.

**Comment by Prez5er** [comment]
> See also bug #4253 which notes the only current workaround is delete everything and retry.

Well for now I will try that way, I hope that they correct it soon.

**Comment by membra99** [comment]
When I called ConfirmPlacementOption, I received an OperationID in the response. When I pass that operationId to the next api enpoint GetInboundOperationStatus, I get an error. Does anyone know what this is about ?

![error](https://github.com/user-attachments/assets/7463c9ff-474d-423b-adc5-3753564fea1b)

**Comment by johnkw** [comment]
I've only ever seen `"code":"InternalServerError","message":"ERROR: Something went wrong. Please try again later."` on `"generateTransportationOptions"`.   That probably deserves a separate github issue and a separate Seller Support case, since it could be different from `Fail to execute CONFIRM_CARRIERS API with errors.` which is what this issue is.

**Comment by brandondev1** [comment]
> @puppsupr When I called ConfirmPlacementOption, I received an OperationID in the response. When I pass that operationId to the next api enpoint GetInboundOperationStatus, I get an error. Does anyone know what this is about ?
> 
> ![error](https://private-user-images.githubusercontent.com/92085940/383122488-7463c9ff-474d-423b-adc5-3753564fea1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjQ3MjUsIm5iZiI6MTczMDgyNDQyNSwicGF0aCI6Ii85MjA4NTk0MC8zODMxMjI0ODgtNzQ2M2M5ZmYtNDc0ZC00MjNiLWFkYzUtMzc1MzU2NGZlYTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE2MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNmJkOTQxOGYwZmE4ZDc0ZWY5MjJiYWFkYWE1NTU3ODIxMzJhMWEyMDY3ZDhkNjNkMDE4MmI4ZDY0YTE2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DalcWjQ_gIihU8u4-4ZACUudwDl3JkbsBneZDLRwP9I)

This issue is about confirmTransportationOptions.  I have an open issue #4113 for the error you are seeing from confirmPlacementOption

**Comment by puppsupr** [comment]
Hi,
The inbound plans might fail due to different reasons and each one could be specific to that particular plan. In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

**Comment by emakunin** [comment]
But why can't we see the failure message to troubleshoot ourselves?

**Comment by weilinggu** [comment]
Hi @emakunin,

We are working on improving error messaging. Please [open a support case](https://developer.amazonservices.com/support) and provide the request, response of the API calls that have unclear error messaging so we can verify and improve.

Thanks
Weiling
Selling Partner API Developer Services

**Comment by brandondev1** [comment]
> Hi @emakunin,
> 
> We are working on improving error messaging. Please [open a support case](https://developer.amazonservices.com/support) and provide the request, response of the API calls that have unclear error messaging so we can verify and improve.
> 
> Thanks Weiling Selling Partner API Developer Services

Unclear like "Something went wrong.  Please try again later".  At least it's being polite.

**Comment by SReynolds81** [comment]
@puppsupr @weilinggu @MeenaAmz On behalf of everyone else here trying to make the Fulfillment Inbound v2024-03-20 APIs work, I am _**begging**_ you to have some internal discussions regarding the extension of the December 20 removal of legacy v0 operations. It has to be clear to everyone at this point that v2024-03-20 is simply not ready for prime time. There are still so many open issues stretching back months, as well as new problems that get created when a bug fix to a reported issue introduces a new breaking change. Despite all this, the specter of a [December 20 drop dead date still looms](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference).

Everyone here is stressed out and frustrated; extending the deadline would provide the time both we and Amazon need to get these wrinkles ironed out and let us all catch our collective breath.

**Comment by johnkw** [comment]
There is a workaround for this bug, which is to delete everything and retry. However, given that the new API only became fully implemented around October 20 when the prep functions were finally added, having only a ~60 day time frame between the new API being created and the old one being removed is extremely unfriendly. Especially with that ~60 day time frame being the busiest time of the year for shipping and holiday vacations.
