### ISSUE TITLE
CPSIAwarning  Issue

### ISSUE THREAD

**Issue by abc1978785513** [amzn/selling-partner-api-models#4050]
![20240726-104806](https://github.com/user-attachments/assets/4ea58a2b-eea1-4297-9b5d-e8bf83bc9f79)
I can't find the related attribute field under the ProductType schema. What should I do?

**Comment by jawheral** [comment]
Hi @abc1978785513,

Can you provide more information on which exact ProductType/Schema you are interested in?

I was able to lookup multiple TOY related ProductType schemas and the CPSIA warning attribute is available as **cpsia_cautionary_statement**.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by abc1978785513** [comment]
@jawheral  The PLAY_SLIDE ProductType/Schema does not have the cpsia_cautionary_statement attribute field, but we still received such an error. What should we do?

**Comment by jawheral** [comment]
Hi @abc1978785513,

That's right, it seems that the ProductType PLAY_SLIDE doesn't support this attribute.

Did you make sure that seller support case is addressing this same product you are trying to list?
A quick check for products in the PLAY_SLIDE product type on Amazon shows that they don't require this warning field. Other Toy related product types require this field though. 
Did you verify that you are picking the right ProductType for your product?

You can use the `getCatalogItems` API to look for ASINs of products similar to yours in the Amazon catalog to double check the product type.

If this doesn't work, I suggest to continue your case with Seller Support to double check and better understand the requirements for your product/productType.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by abc1978785513** [comment]
@jawheral   I have a new question regarding the DRESSER product type. Why does the size field have to be set as required? Since this field is related to parent-child products, our business does not want to provide this field when initially creating the listing. Is there a good solution for this?

**Comment by jawheral** [comment]
@abc1978785513 
If I understand correctly, you would like to list a product that already exists in the Amazon Catalog. 
For this, you can add the **requirements** parameter which is available in the productTypeDefinitions API and the putListingsItem operation. With that you won't have to add the size field.

You can refer to this workflow guide: [Requirements](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#list-an-offer-for-an-item-that-already-exists-in-the-amazon-catalog)

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by abc1978785513** [comment]
@jawheral I am creating a new catalog.      not  exists in the Amazon Catalog.

**Comment by jawheral** [comment]
@abc1978785513 
In this case, I recommend that you check the same workflows guide but specifically [Configuring related listings items](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#configuring-related-listings-items-variations-package-hierarchies). In this case, you have both new items in the catalog (Parent) but once the parent is available you create child listings following the Listings for Already Existing products.

I hope this helps!

**Comment by abc1978785513** [comment]
"if": {
						"anyOf": [
							{
								"not": {
									"required": [
										"parentage_level"
									],
									"properties": {
										"parentage_level": {
											"items": {
												"required": [
													"value"
												]
											}
										}
									}
								}
							},
							{
								"not": {
									"required": [
										"parentage_level"
									],
									"properties": {
										"parentage_level": {
											"contains": {
												"required": [
													"value"
												],
												"properties": {
													"value": {
														"enum": [
															"parent"
														]
													}
												}
											}
										}
									}
								}
							}
						]
					},
					"then": {
						"required": [
							"size"
						]
					}              
 This is the schema under the producttype. So, does it have to be filled out when creating a new catalog?

**Comment by jawheral** [comment]
@abc1978785513 you have to validate the listing you are creating against the schema.
Please follow this link https://developer-docs.amazon.com/sp-api/docs/product-type-definition-meta-schema for how to validate against json schemas.

Best,
Jawher
Selling Partner API Solutions Architect
