### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 listShipmentBoxes No ID is returned to identify the given box

### ISSUE THREAD

**Issue by JuCongBoy** [amzn/selling-partner-api-models#4052]
Hi @puppsupr 

Call listShipmentBoxes interface Not return box ID, which leads to the subsequent calls updateShipmentTrackingDetails interfaces provide logistics tracking number can't upload

**Comment by puppsupr** [comment]
Hi @JuCongBoy,
Has the transportation confirmed ?
Also is this for small parcel delivery or LTL ?

**Comment by JuCongBoy** [comment]
> Hi @JuCongBoy, Has the transportation confirmed ? Also is this for small parcel delivery or LTL ?

The mode of transportation has been confirmed and spd is used.

**Comment by puppsupr** [comment]
Can you try out https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplanboxes. Also please provide the inboundPlanId

**Comment by JuCongBoy** [comment]
> Can you try out https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplanboxes. Also please provide the inboundPlanId

I tried the https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplanboxes.boxId still not returned.
inboundPlanId = wf6e1b637b-a6e9-4a6b-8d9c-73234d6df757

**Comment by puppsupr** [comment]
Hi @JuCongBoy, Checking with Product team on this.

**Comment by JuCongBoy** [comment]
> Hi @JuCongBoy, Checking with Product team on this.

Look forward to your reply.
But there is another problem, you have not replied to me, I do not know whether your product team is verifying：https://github.com/amzn/selling-partner-api-models/issues/4033

**Comment by puppsupr** [comment]
Hi,
Our team is looking for more details on this including the inboundPlanId, complete request and response. Also the flow of operations you used.

**Comment by JuCongBoy** [comment]
> Hi, Our team is looking for more details on this including the inboundPlanId, complete request and response. Also the flow of operations you used.

Hi,
How is the progress of this problem? Our business team is eagerly waiting for your team to solve a series of problems in the new process. Thank you very much!

**Comment by puppsupr** [comment]
Hi [JuCongBoy](https://github.com/JuCongBoy),
As stated, our team is asking for more details on this including the inboundPlanId, complete request and response. Also the flow of operations you used.

**Comment by JuCongBoy** [comment]
> Hi [JuCongBoy](https://github.com/JuCongBoy), As stated, our team is asking for more details on this including the inboundPlanId, complete request and response. Also the flow of operations you used.

Hi,
inboundPlanId = wf6e1b637b-a6e9-4a6b-8d9c-73234d6df757
requestBody = inboundPlanId: wf6e1b637b-a6e9-4a6b-8d9c-73234d6df757, shipmentId: sh83bdbbc2-efda-416d-bf94-f2925246b374, pageSize: 500, paginationToken: null
response = [{"boxId":null,"contentInformationSource":"BOX_CONTENT_PROVIDED","destinationRegion":null,"dimensions":{"height":"38","length":"56","unitOfMeasurement":"CM","width":"38"},"items":[{"asin":"B0D73KYYLK","expiration":null,"fnsku":"X00221FTBN","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0WE2XL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":20},{"asin":"B0D73KY3X8","expiration":null,"fnsku":"X00221001R","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0CTM","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73LMTD1","expiration":null,"fnsku":"X00221FRCJ","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0CTS","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":9},{"asin":"B0D73KPQR3","expiration":null,"fnsku":"X0022101ED","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0CT2XL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":5},{"asin":"B0D73L9PTX","expiration":null,"fnsku":"X002213PN7","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0CTL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73MVXNM","expiration":null,"fnsku":"X00221FT6D","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0CTXL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10}],"packageId":"pk18fbb51c-b5db-4352-941b-d545a7187f65","quantity":1,"templateName":"P1 - B4","weight":{"unit":"KG","value":"17.46"}},{"boxId":null,"contentInformationSource":"BOX_CONTENT_PROVIDED","destinationRegion":null,"dimensions":{"height":"38","length":"56","unitOfMeasurement":"CM","width":"38"},"items":[{"asin":"B0D73NKQ11","expiration":null,"fnsku":"X00221F9YF","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0AG2XL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73L7B8V","expiration":null,"fnsku":"X00221JER3","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0AGM","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73L664D","expiration":null,"fnsku":"X00221FHO7","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0AGS","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":9},{"asin":"B0D73L85VV","expiration":null,"fnsku":"X00221FT81","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0AGL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73NRY99","expiration":null,"fnsku":"X002213Q77","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BK2XL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":18},{"asin":"B0D73MVY4T","expiration":null,"fnsku":"X00220ZZJ5","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0AGXL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10}],"packageId":"pk2709c67c-5943-4e03-96ac-b783d99484d9","quantity":1,"templateName":"P1 - B1","weight":{"unit":"KG","value":"17.85"}},{"boxId":null,"contentInformationSource":"BOX_CONTENT_PROVIDED","destinationRegion":null,"dimensions":{"height":"28","length":"56","unitOfMeasurement":"CM","width":"38"},"items":[{"asin":"B0D73KLRPJ","expiration":null,"fnsku":"X00221FBG1","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0WEL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":20},{"asin":"B0D73M2FWG","expiration":null,"fnsku":"X00221BX6D","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0WEM","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":20},{"asin":"B0D73L1LNH","expiration":null,"fnsku":"X0022100PX","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0WES","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":9}],"packageId":"pk5c208e69-2d97-4d14-9735-b300f927f26d","quantity":1,"templateName":"P1 - B5","weight":{"unit":"KG","value":"12.45"}},{"boxId":null,"contentInformationSource":"BOX_CONTENT_PROVIDED","destinationRegion":null,"dimensions":{"height":"38","length":"38","unitOfMeasurement":"CM","width":"28"},"items":[{"asin":"B0D73J5HH8","expiration":null,"fnsku":"X00221JEZ5","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0WEXL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":20},{"asin":"B0D73L1LNH","expiration":null,"fnsku":"X0022100PX","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0WES","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":11}],"packageId":"pkc46483aa-7823-4fcc-a8a5-2406f2bd48bd","quantity":1,"templateName":"P1 - B6","weight":{"unit":"KG","value":"8.44"}},{"boxId":null,"contentInformationSource":"BOX_CONTENT_PROVIDED","destinationRegion":null,"dimensions":{"height":"38","length":"56","unitOfMeasurement":"CM","width":"38"},"items":[{"asin":"B0D73L1C8P","expiration":null,"fnsku":"X00221BXIL","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BKXL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":5},{"asin":"B0D73NJPSZ","expiration":null,"fnsku":"X00221FCFV","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BKS","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":20},{"asin":"B0D73LBCFN","expiration":null,"fnsku":"X00221JG8P","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BKL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":20},{"asin":"B0D73KKRWS","expiration":null,"fnsku":"X00221FRP1","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BKM","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":20},{"asin":"B0D73NRY99","expiration":null,"fnsku":"X002213Q77","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BK2XL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":2}],"packageId":"pke7251eb3-1fa3-48c4-b2a5-f78dd6220003","quantity":1,"templateName":"P1 - B2","weight":{"unit":"KG","value":"16.66"}},{"boxId":null,"contentInformationSource":"BOX_CONTENT_PROVIDED","destinationRegion":null,"dimensions":{"height":"38","length":"56","unitOfMeasurement":"CM","width":"38"},"items":[{"asin":"B0D73M14L8","expiration":null,"fnsku":"X00221FH2J","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BNL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73L1C8P","expiration":null,"fnsku":"X00221BXIL","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BKXL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":15},{"asin":"B0D73KSFJY","expiration":null,"fnsku":"X00221FU8F","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BNM","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73LRZM7","expiration":null,"fnsku":"X002213PMD","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BNS","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":8},{"asin":"B0D73KG6T2","expiration":null,"fnsku":"X002213PFP","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BNXL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10},{"asin":"B0D73KPQR3","expiration":null,"fnsku":"X0022101ED","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0CT2XL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":5},{"asin":"B0D73L5M55","expiration":null,"fnsku":"X00221BXVD","labelOwner":"SELLER","manufacturingLotCode":null,"msku":"UKBEBL0744L0P0BN2XL","prepInstructions":[{"fee":null,"prepOwner":"SELLER","prepType":"ITEM_LABELING"}],"quantity":10}],"packageId":"pkfa6b60d8-f4f7-48b8-9bce-8c66071a16aa","quantity":1,"templateName":"P1 - B3","weight":{"unit":"KG","value":"18.13"}}]

**Comment by JuCongBoy** [comment]
> Hi [JuCongBoy](https://github.com/JuCongBoy), As stated, our team is asking for more details on this including the inboundPlanId, complete request and response. Also the flow of operations you used.
The operation process you need is the process on the left side of the SP-API new shipment

**Comment by JuCongBoy** [comment]
> Hi [JuCongBoy](https://github.com/JuCongBoy), As stated, our team is asking for more details on this including the inboundPlanId, complete request and response. Also the flow of operations you used.



The operation process you need is the process on the left side of the SP-API new shipment

**Comment by JuCongBoy** [comment]
Hi [puppsupr](https://github.com/puppsupr)

Please ask your team to reply to this problem as soon as possible. How should I deal with it

**Comment by JuCongBoy** [comment]
Hi
[puppsupr](https://github.com/puppsupr)
Excuse me, has your team got any results on this question?

**Comment by JuCongBoy** [comment]
@puppsupr 
It has been a month since this question was asked. Can you give me a reply?

**Comment by puppsupr** [comment]
Hi [JuCongBoy](https://github.com/JuCongBoy),
Our team is still investigating the issue. I will provide an update as soon as possible.

**Comment by JuCongBoy** [comment]
> Hi [JuCongBoy](https://github.com/JuCongBoy), Our team is still investigating the issue. I will provide an update as soon as possible.

Please investigate this problem as soon as possible and reply to us as soon as possible.

**Comment by JuCongBoy** [comment]
@puppsupr 
It has been so long, may I ask about the current progress of this issue?

**Comment by JuCongBoy** [comment]
@puppsupr 
Just to give you one more piece of information, it seems that only European sites do not return BoxId at the moment

**Comment by puppsupr** [comment]
Hi @JuCongBoy, This issue is currently identified as a bug which we need more investigation to find the root cause. In the meantime, if you can reproduce the issue in a new plan and provide a complete list of request/response logs (starting from CreateInboundPlan and all the actions against this plan) that will be very helpful. So it works everytime in other countries than Europe ?

**Comment by JuCongBoy** [comment]
> Hi @JuCongBoy, This issue is currently identified as a bug which we need more investigation to find the root cause. In the meantime, if you can reproduce the issue in a new plan and provide a complete list of request/response logs (starting from CreateInboundPlan and all the actions against this plan) that will be very helpful. So it works everytime in other countries than Europe ?
So far, this has only happened in Europe. I'll provide you with a sample request and return interface later

**Comment by JuCongBoy** [comment]
> Hi @JuCongBoy, This issue is currently identified as a bug which we need more investigation to find the root cause. In the meantime, if you can reproduce the issue in a new plan and provide a complete list of request/response logs (starting from CreateInboundPlan and all the actions against this plan) that will be very helpful. So it works everytime in other countries than Europe ?

So far, this has only happened in Europe. I'll provide you with a sample request and return interface later

**Comment by JuCongBoy** [comment]
@puppsupr   #4033 How to deal with this problem?

**Comment by JuCongBoy** [comment]
@puppsupr 
[CreateInboundPlanRequest.txt](https://github.com/user-attachments/files/16777387/CreateInboundPlanRequest.txt)
[CreateInboundPlanResponse.txt](https://github.com/user-attachments/files/16777389/CreateInboundPlanResponse.txt)
[SetPackingInformationRequest.txt](https://github.com/user-attachments/files/16777390/SetPackingInformationRequest.txt)
[SetPackingInformationResponse.txt](https://github.com/user-attachments/files/16777391/SetPackingInformationResponse.txt)
[ListShipmentBoxesRequest.txt](https://github.com/user-attachments/files/16777393/ListShipmentBoxesRequest.txt)
[ListShipmentBoxesResponse.txt](https://github.com/user-attachments/files/16777394/ListShipmentBoxesResponse.txt)

The above files are examples of each important node request and the results returned.Please focus on the SetPackingInformationRequest and ListShipmentBoxesResponse files, as they include request examples and their responses for various critical nodes. Although some less important steps are not listed here, these two files remain key to understanding the process.

**Comment by JuCongBoy** [comment]
@puppsupr 
What is the progress of fixing this BUG?

**Comment by puppsupr** [comment]
team is still checking on this.

**Comment by xyloneX** [comment]
> @puppsupr 这个BUG修复进度如何了？

Our current solution is to encrypt the quantity and msku for comparison and matching

**Comment by JuCongBoy** [comment]
> > @puppsupr 这个BUG修复进度如何了？
> 
> Our current solution is to encrypt the quantity and msku for comparison and matching

But he doesn't return the box ID, so how do you match it?

**Comment by JuCongBoy** [comment]
@puppsupr 
What is the progress of fixing this BUG?

**Comment by JuCongBoy** [comment]
@puppsupr 
This issue has been occurring for two months now. Can it be resolved? Can you please provide a response on the current progress?

**Comment by puppsupr** [comment]
Hi,
Our team has identified the issue and working on priority to resolve this. I will update as soon as this is fixed. Thanks for your patience !
