### ISSUE TITLE
Fulfillment Inbound v2024-03-20: setPackingInformation: Shipments only support BOX_CONTENT_PROVIDED

### ISSUE THREAD

**Issue by brick13th** [amzn/selling-partner-api-models#4056]
Hi all, 

I was trying the right-side path of the flowchart and got the this message when calling `setPackingInformation` with `BARCODE_2D`: 

> Packing groups support BOX_CONTENT_PROVIDED, MANUAL_PROCESS, or BARCODE_2D. Shipments only support BOX_CONTENT_PROVIDED.

It's such an inconvenience. Since users are allowed to populate packing information at this step, why limit to BOX_CONTENT_PROVIDED?

**Comment by mafge** [comment]
Hi @brick13th,
thanks for reaching out!
Can you provide the request body which leads to the error above?
Thanks!
Best,
Marc
Selling Partner Developer Services

**Comment by brick13th** [comment]
Hi @mafge, 

Here's the request body I sent: 
```
'packageGroupings':
[{
   'boxes':
    [{
      'contentInformationSource': 'BARCODE_2D',
      'dimensions': {'height': 10, 'length': 10, 'width': 17, 'unitOfMeasurement': 'IN'},
      'weight': {'value': 32, 'unit': 'LB'},
      'quantity': 8,
      'items': [],            # Must be empty if BARCODE_2D or MANUAL_PROCESS.
    }],
   'packingGroupId': '',      # Empty since the righ-side path does not have it.
   'shipmentId': shipmentId
}]
```

I was taking the right-side path, so the steps were: 
```
createInboundPlan
↓
generatePlacementOptions
↓
listPlacementOptions, confirmPlacementOptions
↓
setPackingInformation
```

And then I got this warning message: 
```
'message': 'ERROR: Box content information source BARCODE_2D is not allowed in package grouping sh2b02025f-ee81-44fd-8a14-40b4063a79c5. 
Packing groups support BOX_CONTENT_PROVIDED, MANUAL_PROCESS, or BARCODE_2D. Shipments only support BOX_CONTENT_PROVIDED.'
```

inboundPlanId = "wfabf537e8-72a7-4ae1-978b-ce068e617b73"
shipmentId = "sh2b02025f-ee81-44fd-8a14-40b4063a79c5"

**Comment by mafge** [comment]
Hi @brick13th,
thanks for adding additional information!
Please be aware that currently only `BOX_CONTENT_PROVIDED` is supported for `setPackingInformation` when the carton level information is not known up-front (right side path of the diagram).
Best,
Marc

**Comment by brick13th** [comment]
Hi @mafge, 

Thank you so much for the prompt reply. 

Will `Barcode_2D` and `MANUAL_PROCESS` be supported soon? For users with various suppliers, Barcode_2D and MANUAL_PROCESS are necessary, as some suppliers may not be able to provide detailed packing slips.

**Comment by mafge** [comment]
Hi @brick13th,
the responsible backend team is aware of that issue. Unfortunately there is no timeline on when this will land in the API.

**Comment by BluePositive** [comment]
@mafge  why was this issue closed if it is not fixed yet?

**Comment by mafge** [comment]
Hi @BluePositive,
the initial question has been answered, the backend team is aware of that request and further progress will be tracked internally (and not here). Unfortunately there is no timeline when this functionality will be available in the API. You can follow the [SP API changelog](https://developer-docs.amazon.com/sp-api/changelog) to get informed when this has been implemented. Other developers can still find this conversation on Github or by using their preferred search engine.

**Comment by daviddecorso** [comment]
This seems like a critical issue that should be fixed before v0 API deprecation, has there been any timeline established for this?

**Comment by pa1983** [comment]
Just found this as I've had exactly the same problem and deprecation is now less than 2 weeks away, meaning we're going to have to entirely change internal packing processes to work around this.  Such a farse.
