### ISSUE TITLE
How  to  got  "SellerCartonIds"

### ISSUE THREAD

**Issue by sheep110** [amzn/selling-partner-api-models#4057]
I use the  Fulfillment Inbound API v2024-03-20    to  create  shipment.

When I call the getLabels interface, an error message appears:  
         Provided SellerCartonIds are not valid: [[FBA*****WXU000001]] for Shipment: [FBA******WX]
The parameter format is as follows:
      
![image](https://github.com/user-attachments/assets/dd5845b0-3807-437c-a34b-1ad28590fde3)

so, where can I get the SellerCartonIds    or  PackageLabelsToPrint   ?
@

**Comment by puppsupr** [comment]
Hi @sheep110,
For getLabels, you need to provide 

{{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}

Here shipmentId must be the shipmentConfirmationId that you can fetch from v2024 getShipment operation.

**Comment by sheep110** [comment]
> SellerCartonIds

Yeah, I did it this way, using v2024-03-20 to create shipment. But when I assigned boxId to PackageLabelsToPrint, it said SellerCartonIds was wrong, so I would like to know what value should be filled in PackageLabelsToPrint,  Thanks

**Comment by rustyfausak** [comment]
Also having this problem. We have resorted to grabbing the labels via the Seller Central UI.

**Comment by puppsupr** [comment]
Hi @sheep110 ,
Can you please provide complete request and response ?

**Comment by sheep110** [comment]
> Hi @sheep110 , Can you please provide complete request and response ?
FBA18853VMSK  ，   FBA18853VMSKU000001
![image](https://github.com/user-attachments/assets/a78b41fa-4641-47f5-a3e1-46a844e14650)
![image](https://github.com/user-attachments/assets/9ae64d89-3ece-439d-b8de-548e56790ac5)

**Comment by Christin519** [comment]
哥们解决了吗

**Comment by Christin519** [comment]
@puppsupr Also having this problem.

**Comment by sheep110** [comment]
> 哥们解决了吗

No

**Comment by puppsupr** [comment]
Hi,
For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.

We have identified the issue for Unique labelType. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).

**Comment by sheep110** [comment]
> Hi, For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.
> 
> We have identified the issue for Unique labelType. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).

We just tried DEFAULT type, we got 1000 lables from this API. Which is way more than what we expected like UNIQUE type.

**Comment by Christin519** [comment]
> > Hi, For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.
> > We have identified the issue for Unique labelType. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).
> 
> We just tried DEFAULT type, we got 1000 lables from this API. Which is way more than what we expected like UNIQUE type.

PageSize传多少就会生成多少标签，虽然你的shipment可能没那么多，不知道amazon怎么设计的。目前的方法是，有多少箱，PageSize就传多少，这样勉强能用

**Comment by sheep110** [comment]
> > > Hi, For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.
> > > We have identified the issue for Unique labelType. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).
> > 
> > 
> > We just tried DEFAULT type, we got 1000 lables from this API. Which is way more than what we expected like UNIQUE type.
> 
> PageSize传多少就会生成多少标签，虽然你的shipment可能没那么多，不知道amazon怎么设计的。目前的方法是，有多少箱，PageSize就传多少，这样勉强能用

谢谢

**Comment by Christin519** [comment]
> > > > Hi, For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.
> > > > We have identified the issue for Unique labelType. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).
> > > 
> > > 
> > > We just tried DEFAULT type, we got 1000 lables from this API. Which is way more than what we expected like UNIQUE type.
> > 
> > 
> > PageSize传多少就会生成多少标签，虽然你的shipment可能没那么多，不知道amazon怎么设计的。目前的方法是，有多少箱，PageSize就传多少，这样勉强能用
> 
> 谢谢， 你对FBM Orders 的发站内信 有了解吗

完全不了解

**Comment by sheep110** [comment]
> > > > > Hi, For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.
> > > > > We have identified the issue for Unique labelType. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).
> > > > 
> > > > 
> > > > We just tried DEFAULT type, we got 1000 lables from this API. Which is way more than what we expected like UNIQUE type.
> > > 
> > > 
> > > PageSize传多少就会生成多少标签，虽然你的shipment可能没那么多，不知道amazon怎么设计的。目前的方法是，有多少箱，PageSize就传多少，这样勉强能用
> > 
> > 
> > 谢谢， 你对FBM Orders 的发站内信 有了解吗
> 
> 完全不了解

好的
