### ISSUE TITLE
Since pallet info has not been provided, we may not be able to produce PCP-LTL options as part of GenerateTransportationOptions for the following shipment IDs: [sh1e18ff11-f2e1-4576-9e15-9

### ISSUE THREAD

**Issue by a344241086** [amzn/selling-partner-api-models#4070]
Call Interface GenerateTransportationOptions  
parameter: 
    placementOptionId: pl56d62d0d-9335-4d7f-8c01-a*****
    shipmentTransportationConfigurations: [{
        contactInformation: null
        freightInformation: null
        pallets: null
        readyToShipWindow: class WindowInput {
            start: 2024-08-15T16:00:00.000Z
        }
        shipmentId: sh624cb85f-78a5-40bb-8394-4d76d6****
    }]

**Comment by xyloneX** [comment]
I also encountered such a issue

**Comment by emakunin** [comment]
+1
