### ISSUE TITLE
Clarification on Deprecation Status of getShipments and getShipmentItems

### ISSUE THREAD

**Issue by ElyeM** [amzn/selling-partner-api-models#4072]
I am seeking clarification regarding the deprecation status of the getShipments and getShipmentItems endpoints in the Amazon Selling Partner API. I have come across conflicting information on various official documentation pages:

1. [General Availability of Fulfillment Inbound API v2024-03-20](https://developer-docs.amazon.com/sp-api/changelog/general-availability-of-fulfillment-inbound-api-v2024-03-20) explicitly states that these endpoints will not be deprecated.
2. [SP-API Deprecations](https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations) indicates that they will be deprecated.
3. [Fulfillment Inbound API v0 Reference](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference) states that they will not be deprecated.
4. [getShipments Endpoint Documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipments) mentions that the endpoint is deprecated.

Could you please provide clear guidance on whether the getShipments and getShipmentItems endpoints are being deprecated or not? 

Thank you for your help.

**Comment by puppsupr** [comment]
Hi @ElyeM,
Thanks for bringing this up. Will update to have consistency around the docs.
The below operations won't deprecate on Dec 20, 2024.
getLabels
getBillOfLading
getPrepInstructions
getShipments
getShipmentItemsByShipmentId
getShipmentItems

**Comment by wolendranh** [comment]
@puppsupr Hi! 

Are any docs updated and reflect this? As our team received Deprecation Reminder email with link to doc here 
https://developer-docs.amazon.com/sp-api/changelog/deprecation-reminders-july-31-2024

which mentioned that `Fulfillment Inbound API v0`

`getShipmentItems`
`getShipments`

Are going to be deprecated?

Can you please point to updated docs?
