### ISSUE TITLE
[BUG] [BLOCKER] [SP-API] Fulfillment Inbound v2024-03-20. Impossible to print UNIQUE shipment labels

### ISSUE THREAD

**Issue by emakunin** [amzn/selling-partner-api-models#4073]
### Context
[Amazon strongly recommends using the UNIQUE option to get package labels](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#labeltype) to print shipment labels. However the **API does not work for UNIQUE label type**. 

### Problem
1. v2024-03-20 api [asks to use](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#step-9-printing-labels) old [v0 getLabels](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getlabels) to generate labels.
2. V0 API in its turn [requires to submit POST_FBA_INBOUND_CARTON_CONTENTS feed](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#step-9-request-shipping-labels-for-your-inbound-shipment)
3. During POST_FBA_INBOUND_CARTON_CONTENTS feed submission, result document reports an error (yes, in German for any MP) saying that the shipment cannot be modified as it's converted to an STA one.
```xml
<MessageID>1</MessageID>
<ResultCode>Error</ResultCode>
<ResultMessageCode>1</ResultMessageCode>
<ResultDescription>Die Sendung FBA***** wurde zu "An Amazon senden" (wfee1f3b7e-1800-496a-8b6b-a452dad4b9d6) umgewandelt. Es können keine weiteren Änderungen in der API vorgenommen werden. Verwenden Sie "An Amazon senden", um die Sendung anzuzeigen und zu bearbeiten. Weitere Informationen finden Sie unter <a href="/help/hub/reference/G6925SDD66GDLXJW">Sendungen mit "An Amazon senden" erstellen</a>. (FBA_INBOUND_CARTON_058)</ResultDescription>
<AdditionalInfo>
<SKU>-</SKU>
</AdditionalInfo>
</Result>
```
4. However v2024-03-20 api says: [You must confirm a transportation option before printing labels.](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#step-8-select-transportation-options) At this step we already have shipment confirmation IDs in FBA**** format meaning it's impossible to submit the feed with box details for UNIQUE shipment label.
5. Attempts to print UNIQUE labels without the feed (or after submitting the failed ones) always gives an error
```json
// Request: https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/{{shipmentId}}/labels?PageType=PackageLabel_A4_2&LabelType=UNIQUE&PackageLabelsToPrint=FBA***U000001,FBA***U000002&PageSize=2
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Provided SellerCartonIds are not valid: [[FBA***U000002, FBA***U000001]] for Shipment: [FBA***]",
      "details": ""
    }
  ]
}
```

### Customer impact
1. UNIQUE Shiment labels recommended by Amazon cannot be generated via the API. It blocks the automated process for sellers. Currently sellers have to download shipment labels maunally from SellerCentral 
2. API works for undocumented  label types. However, it is not clear whether other label types such as non-documented "DEFAULT" or "BARCODE_2D can be used interchangeably for the shipments. The generated documents are slightly different (see attachments).

**As a mitigation please at least provide some guidance whether shipment labels of other types like DEFAULT or BARCODE_2D can be used.** Note: that now API supports only `BoxContentInformationSource.BOX_CONTENT_PROVIDED` for the box content. So no 2D barcodes are available during plan creation.

#### Alternative labels
I tried using alternative label types. BARCODE_2D and partially documented "DEFAULT" value. (it's not in the enum schema)
However the files are different with the ones generated in seller central. 

- DEFAULT is mentioned in [v0 #step-9-request-shipping-labels](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#step-9-request-shipping-labels-for-your-inbound-shipment). However it's not a part of the schema nor the documentation. See: [doc](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#labeltype) [schema](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-model)
- BARCODE_2D is mentioned to be not used ["This option is provided only for shipments where 2D Barcodes will be applied to all packages. Amazon strongly recommends using the UNIQUE option to get package labels instead of the BARCODE_2D option."](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#labeltype)

<details><summary>Click to show generated labels attachments</summary>
<p>

**Label from seller central:**
![SC-label](https://github.com/user-attachments/assets/13cda214-9bd1-47ad-a162-447f832288eb)

**BARCODE_2D label:**
Note how empty is the second half of the doc. Section with EDI and barcode is empty.

 ![2D-label](https://github.com/user-attachments/assets/82803ccc-8547-4760-ae78-0a6c1312fe27)

**DEFAULT** label (note: the api accepts any random string as a `LabelType` param value with the same result)
![Default-label](https://github.com/user-attachments/assets/775ddc32-a2ac-4581-8a01-65606b16fb04)

</p>
</details>

**Comment by emakunin** [comment]
Hi @puppsupr,

Could you please take a look? In combination with below issues, it will make the API not usable.

https://github.com/amzn/selling-partner-api-models/issues/3951, 
https://github.com/amzn/selling-partner-api-models/issues/551

**Comment by puppsupr** [comment]
Hi [emakunin](https://github.com/emakunin),
Checking with Product Team on it.

**Comment by Christin519** [comment]
I have the same problem

**Comment by jlevers** [comment]
I know this is an old issue, but for anyone else who stumbles across this – the documentation for the FBA Inbound API v2024-03-20 says that you need to submit the `POST_FBA_INBOUND_CARTON_CONTENTS` feed with carton info, but as far as I can tell that's not actually necessary (and I get errors every time I try to submit it). I've been able to go straight from the `confirmTransportationOptions` call to the `getLabels` call, if I call `getLabels` as @puppsupr described above with the `DEFAULT` label type.

**Comment by luap2703** [comment]
> Hi, For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.
> 
> We have identified the issue for this. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).

Maybe you should update this in the docs or is this github issue part of the official docs? ;)
