### ISSUE TITLE
Need Seller Information - Seller ID & Seller Name

### ISSUE THREAD

**Issue by pradeep-gox** [amzn/selling-partner-api-models#4076]
I am opening this issue as the related issues were closed.

Currently we can get only the selling partner id who authorized our app and not the seller id which he/she had selected while authorization.

Basically I need the basic seller identifiable information to distinguish sellers. Mainly I require seller id and possible the seller name as well.

I wish it to be added in the selling partner api in some way as this is a much requested feature.

Thanks

**Comment by rugved1991** [comment]
Hi @pradeep-gox,

Thanks for sharing the feature request. I will +1 this request internally on your behalf. We cannot provide an ETA on when and if this feature would be made available. 
If you have any other issue or concern please feel free to open a new issue.

Best,
Rugved
Solutions Architect, SP-API
