### ISSUE TITLE
performance metrics (like onTimeDeliveryRate) doesn't match between shop backstage page and GET_V2_SELLER_PERFORMANCE_REPORT report api

### ISSUE THREAD

**Issue by oh0123** [amzn/selling-partner-api-models#4078]
hi, there.
we found that the metric from shop backstage page about onTimeDeliveryRate is not same as we got from report api, the report type is GET_V2_SELLER_PERFORMANCE_REPORT. It turned out to be the report period is different, 14 day VS 30 day. 

So，we want know there is any plan to sync two data source to keep consistency？

thanks

**Comment by jawheral** [comment]
Hi @oh0123,

The _GET_V2_SELLER_PERFORMANCE_REPORT_ report has a **UnitOnTimeDelivery** for the US marketplace sellers which is a 14-day period. The **onTimeDelievery** metric is still there with the same time range: 30 days. 

The documentation will be updated.

I hope this helps!

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by oh0123** [comment]
@jawheral 
Hi，
Thank you for your reply, It really works.

**Comment by snowbordheathen** [comment]
@jawheral Is there any way to download historical data for the GET_V2_SELLER_PERFORMANCE_REPORT . Regardless of start/to date it always returns the same report matching most current metrics only.  I was curious if there is a way via the api or the maybe a downloadable csv etc, to get historical data?

**Comment by jawheral** [comment]
@snowbordheathen There's currently no way to get historical data via API. Nevertheless, there's a Performance Over Time report on Seller Central which might be of help. Do you need to access this data on behalf of sellers via API and how would it help?

Best,
Jawher
Selling Partner API Solutions Architect
