### ISSUE TITLE
[SP-API] Fulfillment Inbound v2024-03-20. How can I get the unique label through the getLabels api?

### ISSUE THREAD

**Issue by Christin519** [amzn/selling-partner-api-models#4084]
I have completed the following steps

1. createInboundPlan
2. generatePackingOptions  listPackingOptions  listPackingGroupItems  confirmPackingOption
3. setPackingInformation
4. generatePlacementOptions  listPlacementOptions
5. generateTransportationOptions  generateDeliveryWindowOptions
6. listTransportationOptions  listDeliveryWindowOptions getShipment
7. confirmPlacementOption  
8. confirmDeliveryWindowOptions  confirmTransportationOptions

my inboundPlanId: **wf71f62b72-6eea-4c8f-95e7-ffe93ddfdc6c**

When I was doing step 9,I cannot successfully call **getLabels**

The error message is "**Provided SellerCartonIds are not valid: [[FBA1897MLQDHU000001]] for Shipment: [FBA1897MLQDH]**"

request:
```
{
	"pageType": "PackageLabel_Plain_Paper",	
	"labelType": "UNIQUE",
	"packageLabelsToPrint":["FBA1897MLQDHU000001"],
	"numberOfPackages": 1,
	"shipmentId": "FBA1897MLQDH"
}
```

i get the value 'FBA1897MLQDHU000001' from **listShipmentBoxes**
```
{
        "boxes": [{
                "quantity": 1,
                "templateName": "P1 - B3",
                "packageId": "pk0a38ed8b-5807-464b-869a-c3301ce8319e",
                "weight": {
                        "unit": "LB",
                        "value": 8
                },
                "items": [{
                        "labelOwner": "SELLER",
                        "msku": "160912-W-NEW-BLACK DK.GREY-SZ-06",
                        "quantity": 1,
                        "fnsku": "X001MNO5ZL",
                        "asin": "B077GDVX2C",
                        "prepInstructions": [{
                                "prepType": "ITEM_LABELING",
                                "prepOwner": "SELLER"
                        }]
                }],
                "boxId": "FBA1897MLQDHU000001",
                "dimensions": {
                        "unitOfMeasurement": "IN",
                        "length": 20,
                        "width": 20,
                        "height": 20
                },
                "contentInformationSource": "BOX_CONTENT_PROVIDED"
        }],
        "pagination": {}
}
```

When I try to use the pageSize parameter, the error message is "**1 validation error detected: Value null at 'cartonIdList' failed to satisfy constraint: Member must not be null**"

request:
```
{
	"pageType": "PackageLabel_Plain_Paper",
	"labelType": "UNIQUE",
	"shipmentId": "FBA1897MLQDH",
	"pageSize": 10
}
```

Do I still need to provide carton information via the Carton Information Feed (POST_FBA_INBOUND_CARTON_CONTENTS), or does the new API have an alternative method for submitting carton information to get labels?

Can anyone help me? Plese!

**Comment by mafge** [comment]
Hi @Christin519,
thanks for reaching out!
Yes, you still have to provide carton information via the Carton Information Feed. Please have a look at our [documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#step-9-request-shipping-labels-for-your-inbound-shipment) for further details.
Best,
Marc
Selling Partner Developer Services

**Comment by Christin519** [comment]
> Hi @Christin519, thanks for reaching out! Yes, you still have to provide carton information via the Carton Information Feed. Please have a look at our [documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#step-9-request-shipping-labels-for-your-inbound-shipment) for further details. Best, Marc Selling Partner Developer Services

So do I still have to upload the box contents via feed as before to get the labels, even if I use the new api?Why?

**Comment by Christin519** [comment]
> Hi @Christin519, thanks for reaching out! Yes, you still have to provide carton information via the Carton Information Feed. Please have a look at our [documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#step-9-request-shipping-labels-for-your-inbound-shipment) for further details. Best, Marc Selling Partner Developer Services

but i have been provide carton information via **setPackingInformation**. Isn't that enough?

**Comment by Christin519** [comment]
@mafge I tried using feed(POST_FBA_INBOUND_CARTON_CONTENTS) to provide box information. But this obviously doesn't work

<Result>
<MessageID>1</MessageID>
<ResultCode>Error</ResultCode>
<ResultMessageCode>1</ResultMessageCode>
<ResultDescription>Shipment FBA1897HGY0X was converted to Send to Amazon wf71f62b72-6eea-4c8f-95e7-ffe93ddfdc6c, and no further edits can be made in API. Please use Send to Amazon to view and edit the shipment. For more information, go to <a href="/help/hub/reference/G6925SDD66GDLXJW">Create shipments with Send to Amazon</a>. (FBA_INBOUND_CARTON_058)</ResultDescription>
</Result>

**Comment by mafge** [comment]
@Christin519 What happens when you omit `packageLabelsToPrint` from the `getLabels` request?

**Comment by Christin519** [comment]
> "**1 validation error detected: Value null at 'cartonIdList' failed to satisfy constraint: Member must not be null**"

"1 validation error detected: Value null at 'cartonIdList' failed to satisfy constraint: Member must not be null"

{
	"pageType": "PackageLabel_Plain_Paper",
	"labelType": "UNIQUE",
	"shipmentId": "FBA1897HGY0X",
	"pageSize": 10
}

**Comment by Christin519** [comment]
> @Christin519 What happens when you omit `packageLabelsToPrint` from the `getLabels` request?

"1 validation error detected: Value null at 'cartonIdList' failed to satisfy constraint: Member must not be null"

request:

```
{
	"pageType": "PackageLabel_Plain_Paper",
	"labelType": "UNIQUE",
	"shipmentId": "FBA1897HGY0X",
	"pageSize": 10
}
```

**Comment by Christin519** [comment]
> @Christin519 Can you try using the `packageId` instead of `boxId` in `packageLabelsToPrint`?

Still doesn't work

the error message is:

"Provided SellerCartonIds are not valid: [[pk0a38ed8b-5807-464b-869a-c3301ce8319e]] for Shipment: [FBA1897HGY0X]"

"Provided SellerCartonIds are not valid: [[FBA1897HGY0XU000001]] for Shipment: [FBA1897HGY0X]"

Although the two values ​​I use are what I get from **listShipmentBoxes**

**Comment by mafge** [comment]
@Christin519 Ok, thanks for trying. So it seems there is a general issue with the API currently. I will check with the backend team. In the meantime you can generate the labels via seller central website.

**Comment by Christin519** [comment]
> @Christin519 Ok, thanks for trying. So it seems there is a general issue with the API currently. I will check with the backend team. In the meantime you can generate the labels via seller central website.

Thank you. How long will it take to get a reply? Can it be as soon as possible? This affects our work. This is very important to me.

**Comment by puppsupr** [comment]
Hi,
For getLabels you need to provide, {{baseUrl}}/fba/inbound/v0/shipments/:shipmentId/labels?PageType={{PageType}}&PageSize={{PageSize}}, where shipmentId is shipmentConfirmationId.

We have identified the issue for this. We recommend to use DEFAULT type as it fetches the same labels just not by ID, but all at once (paginated).

**Comment by puppsupr** [comment]
#4073 Related issue, track it for updates.

**Comment by Christin519** [comment]
Thank you so much!!!

This is a successful demo, No need for shipmentId(shipmentConfirmationId), labelType, etc. as parameters

https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments/FBA1234ABCD/labels?PageType=PackageLabel_Plain_Paper&PageSize=10

**Comment by brandondev1** [comment]
> shipmentConfirmationId

Where does the shipmentConfirmationId come from in the new API?
