### ISSUE TITLE
Browse Tree Reports - multiple productTypeDefinitions for leaf category

### ISSUE THREAD

**Issue by BarnetMichal** [amzn/selling-partner-api-models#4086]
I downloaded the BTR for IT(APJ6JRA9NG5V4) via GET_XML_BROWSE_TREE_DATA and I came across end categories that contain more Product types see, 

3628458031;"Casa e cucina,Aspirapolvere e pulizia di pavimenti e finestre,Accessori per aspirapolvere,Bocchette";KITCHEN,HOME_BED_AND_BATH,HOME_FURNITURE_AND_DECOR,ABIS_KITCHEN,HOME;
733017031;"Casa e cucina,Aspirapolvere e pulizia di pavimenti e finestre,Accessori per aspirapolvere,Cuscinetti e spazzole a disco";KITCHEN,HOME_BED_AND_BATH,HOME_FURNITURE_AND_DECOR,ABIS_KITCHEN,HOME;
733012031;"Casa e cucina,Aspirapolvere e pulizia di pavimenti e finestre,Accessori per aspirapolvere,Cover";KITCHEN,HOME_BED_AND_BATH,HOME_FURNITURE_AND_DECOR,ABIS_KITCHEN,HOME;

Do you know if this is a bug or can this situation happen? Thanks for reply!

**Comment by jawheral** [comment]
Hi @BarnetMichal,

Can you provide more information and highlight the exact concern you are having and what you are expecting?

Did you go through the report documentation: https://developer-docs.amazon.com/sp-api/docs/report-type-values-browse-tree?

You can also validate the report against the [BrowseTreeReport.xsd schema](https://images-na.ssl-images-amazon.com/images/G/01/mwsportal/doc/en_US/Reports/XSDs/BrowseTreeReport.xsd).

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by BarnetMichal** [comment]
Hi @jawheral 
This is one of the node from GET_XML_BROWSE_TREE_DATA for IT market (APJ6JRA9NG5V4)
I`m expecting that leaf category node will have just one Product type or nothing. 
I want to create a listing with recommended_browse_nodes = 3628458031 and need a product type. Which one should I pick from productTypeDefinitions? I mean for the other 99% of browse nodes, there is one type or nothing, so this is suspicious to me. 


<Node>
        <browseNodeId>3628458031</browseNodeId>
        <browseNodeAttributes count="1">
            <attribute name="recommended_browse_nodes">3628458031</attribute>
        </browseNodeAttributes>
        <browseNodeName>Bocchette</browseNodeName>
        <browseNodeStoreContextName>Bocchette per aspirapolvere</browseNodeStoreContextName>
        <browsePathById>524015031,524016031,732998031,733008031,3628458031</browsePathById>
        <browsePathByName>Casa e cucina,Aspirapolvere e pulizia di pavimenti e finestre,Accessori
            per aspirapolvere,Bocchette</browsePathByName>
        <hasChildren>false</hasChildren>
        <childNodes count="0"></childNodes>
        <productTypeDefinitions>KITCHEN,HOME_BED_AND_BATH,HOME_FURNITURE_AND_DECOR,ABIS_KITCHEN,HOME</productTypeDefinitions>
        <refinementsInformation count="0"></refinementsInformation>
    </Node>

**Comment by jawheral** [comment]
Hi @BarnetMichal,

Thanks for sharing. 
This might mean that your listing could go with multiple similar product type definitions.

I also suggest that you use the Catalog API - searchCatalogItems to look for similar products and see what productTypeDefinition they belong to or query each product type definition provided and analyse which one works best for you.



Best,
Jawher
Selling Partner API Solutions Architect
