### ISSUE TITLE
createConfirmDeliveryDetails

### ISSUE THREAD

**Issue by sheep110** [amzn/selling-partner-api-models#4087]
About this [api](https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference#createconfirmdeliverydetails),  what kind of  type order  can  use  or  what status  order  can use.

**Comment by jawheral** [comment]
Hi @sheep110,

You can use the [_**getMessagingActionsForOrder**_](https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference#getmessagingactionsfororder) operation to inspect which messaging actions are allowed for the order specified.

When an order allows **createConfirmDeliveryDetails**, it will be part of the actions in the response of **getMessagingActionsForOrder**

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by sheep110** [comment]
> Hi @sheep110,
> 
> You can use the [_**getMessagingActionsForOrder**_](https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference#getmessagingactionsfororder) operation to inspect which messaging actions are allowed for the order specified.
> 
> When an order allows **createConfirmDeliveryDetails**, it will be part of the actions in the response of **getMessagingActionsForOrder**
> 
> Best, Jawher Selling Partner API Solutions Architect

We already tested 50 orders, include shipped and unshipped FBM orders. None of these have the **createConfirmDeliveryDetails** function based on **getMessagingActionsForOrder** response.

Thanks,

**Comment by jawheral** [comment]
Hi @sheep110,

I initiated contact with our internal teams about your concerns.

I will provide updates here once available.

Best,
Jawher
Selling Partner API Solutions Architect
