### ISSUE TITLE
Feature Request: Best and Lightning Deal creation

### ISSUE THREAD

**Issue by Dejo-commerce** [amzn/selling-partner-api-models#4089]
It would be really amazing to have an endpoint that allows us to create Best and Lightning Deals.

**Comment by jawheral** [comment]
Hi @Dejo-commerce,

How would such an api help you in your use cases and what would you miss if it is not added?

**Comment by jawheral** [comment]
Hi @Dejo-commerce,

We don't currently offer an API to programmatically create Deals such Best and Lightning deals.

Thank you for the feedback. I will take deliver this information to our product teams for future plannings.

Best,
Jawher
Selling Partner API Solutions Architect
