### ISSUE TITLE
Fulfillment Inbound API 2024-03-20 How to updates or removes items?

### ISSUE THREAD

**Issue by Christin519** [amzn/selling-partner-api-models#4090]
In the past, we could use **updateInboundShipment** to modify the quantity of a certain sku in the shipment. Is there no way to modify it in the new API (v2024-03-20)?

If I fill in a certain quantity when createInboundPlan, but later I find that the quantity is wrong and I need to update or remove it, is this not allowed, no matter at which step?

I can only cancel the entire inboundPlan？

**Comment by Christin519** [comment]
Can someone help me？ please！

**Comment by ccyun06** [comment]
I didn’t see the interface either.Have you encountered this problem?https://github.com/amzn/selling-partner-api-models/issues/4102

**Comment by Alvaromero** [comment]
Hi @puppsupr, Is there an endpoint to modify or delete elements of a plan?

thanks in advance

**Comment by CWillHan** [comment]
In the past, we could use updateInboundShipment to modify the quantity of a certain sku in the shipment. Is there no way to modify it in the new API (v2024-03-20)?
--how to update Shipment? what's the new interface? I can't get any valid information from reply messages above

**Comment by CWillHan** [comment]
Hi  @Christin519  , How do you update the shipment finally?

**Comment by Christin519** [comment]
> Hi @Christin519 , How do you update the shipment finally?

Unable to modify, only cancel the inbound plan

**Comment by puppsupr** [comment]
Hi All,
You can update the quantities/boxes before Amazon receives them. Please see [Update information in a shipment](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#update-information-in-a-shipment) for more details.
