### ISSUE TITLE
Fulfillment Inbound API 2024-03-20  getInboundPlan  is not supported for the cross border Amazon Global Logistics program ?

### ISSUE THREAD

**Issue by yan15195755798** [amzn/selling-partner-api-models#4091]
{
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: GetInboundPlan is not supported for the cross border Amazon Global Logistics program.",
      "details": ""
    }
  ]
}

**Comment by yan15195755798** [comment]
The first two weeks were okay, but not this week. Can you give me a response ?

**Comment by yan15195755798** [comment]
Can you give me a response ?

**Comment by Ironkyy** [comment]
Has your problem been resolved? I'm having the same problem now

**Comment by or-en** [comment]
I have this issue too. Anyone was able to resolve it?

**Comment by jsrgqinbin** [comment]
I have this issue too. Anyone was able to resolve it?

**Comment by puppsupr** [comment]
Hi,
Can you please provide complete request and response along with inbound plan id (if created).

**Comment by Ironkyy** [comment]
{"placementOptionId":"plf0841453-6e71-4ad2-b7c4-f0a7f66191df","shipmentTransportationConfigurations":[{"contactInformation":{"name":"xxxx","phoneNumber":"xxxxxxxx"},"freightInformation":{"freightClass":"FC_200"},"readyToShipWindow":{"start":{"dayOfMonth":17,"dayOfWeek":"THURSDAY","dayOfYear":291,"hour":0,"minute":0,"month":"OCTOBER","monthValue":10,"nano":0,"offset":{"rules":{"fixedOffset":true,"transitionRules":[],"transitions":[]},"totalSeconds":0},"second":0,"year":2024}},"shipmentId":"sh146a20aa-19d0-4fea-a367-dfe3a66d1a99"},{"contactInformation":{"$ref":"$.shipmentTransportationConfigurations[0].contactInformation"},"freightInformation":{"$ref":"$.shipmentTransportationConfigurations[0].freightInformation"},"readyToShipWindow":{"$ref":"$.shipmentTransportationConfigurations[0].readyToShipWindow"},"shipmentId":"shdbfc8d3f-77a9-44bb-ac2b-a7ebc9403d45"}]}        This is my request entity class, but the response always returns transportation options of the USE_YOUR_OWN_CARRIER type. @puppsupr

**Comment by weilinggu** [comment]
@Ironkyy Can you create a support case regarding this issue?

Thanks
Weiling
Amazon Selling Partner Services

**Comment by Ironkyy** [comment]
@weilinggu How do I submit a support case?

**Comment by puppsupr** [comment]
Please [open a support case](https://developer.amazonservices.com/support) here.
