### ISSUE TITLE
Can Vendor Central utilize the Feed API? I'm encountering difficulties in creating a Feed Document

### ISSUE THREAD

**Issue by 13058194015** [amzn/selling-partner-api-models#4092]
I have changed the value of the "MerchantIdentifier" field in the XML to the "Vendor code" value, but it has not succeeded and keeps returning errors{"code":400,"message":"","data":null,"errors":[{"code":"InvalidInput","details":"","message":"Invalid request parameters"}]}

**Comment by jawheral** [comment]
Hi @13058194015,

There are no XML feeds available for vendors. The only feed type available for vendors is the JSON_LISTINGS_FEED.

To explore the different feeds we have, please check out this [page](https://developer-docs.amazon.com/sp-api/docs/feed-type-values) and navigate to the right category you are interested in. For every feed, you can find an ### _Availability_ attribute which tells you it is available for sellers or vendors or both.

You can also check this page for all the [vendor use cases](https://developer-docs.amazon.com/sp-api/docs/sp-api-vendor-use-cases) possible using SP-API.

You didn't mention the Feed Type you were trying and for which you are receiving an issue, but in case that's Listings, please explore the Listings API and the JSON_LISTINGS_FEED.

I'm closing this as it is not an issue.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by 13058194015** [comment]
I have another question I hope you can help me with. If I use the JSON_LISTINGS_FEED, does that mean I must use AWS S3? I've noticed that during testing, if the image URLs are not hosted on S3, I receive errors. Is this a requirement？, and are there any alternative solutions for hosting images outside of S3?

**Comment by 13058194015** [comment]
I have another question I hope you can help me with. If I use the JSON_LISTINGS_FEED, does that mean I must use AWS S3? I've noticed that during testing, if the image URLs are not hosted on S3, I receive errors. Is this a requirement？, and are there any alternative solutions for hosting images outside of S3?

**Comment by 13058194015** [comment]
jawheral  Thank you for your reply
I have another question I hope you can help me with. If I use the JSON_LISTINGS_FEED, does that mean I must use AWS S3? I've noticed that during testing, if the image URLs are not hosted on S3, I receive errors. Is this a requirement？and are there any alternative solutions for hosting images outside of S3?
