### ISSUE TITLE
OAuth: Blank Page after Authorizing the app

### ISSUE THREAD

**Issue by Bhanishi-at-Github** [amzn/selling-partner-api-models#4093]
After Authorizing the app, A blank screen is shown and unable to authorize it.

the URL after authorization

https://sellercentral.amazon.com/apps/authorize/?amazon_callback_uri=https%3A%2F%2Fsellercentral.amazon.com%2Fapps%2Fauthorize%2Fconfirm%2Famzn1.sp.solution.8d796277-9887-484c-b059-bb7******&amazon_state=MTcyMzc5ODkyNTY5Me-_ve-_ve-_vXTvv73vv73vv73ftO-_vTjvv70UI2RUGw41Ju-_vXI177-977-977-977-9W13vv73vv71m77-977-9Ae-_vRFn77-9x5zvv70d77-9ZAZs77-9HV1cEO-_ve-_ve-_vXV977-9PwYK77-977-9&version=beta&selling_partner_id=A3FYFXKZF8****

this is the code that I have written to execute the application running on local host 

def amazonAuth(request):

    url = f'https://sellercentral.amazon.com/apps/authorize/consent?application_id={app_id}&redirect_uri={redirect_uri}&version=beta'
    
    if request.method == 'GET':

        try:

            return redirect (url)
        
        except requests.exceptions.RequestException as e:

            return JsonResponse({
                'message': 'Failed to redirect to Amazon',
                'status': 500,
                'error': str(e)
            })
    

@require_http_methods(["GET"])
def amazon_callback(request):

    print ("Amazon Callback")

    code = request.GET.get('code')
    print(code)

    if not code:
        return JsonResponse({
            'message': 'Authorization code not provided',
            'status': 400
        })

    try:
        # Exchange the authorization code for tokens
        token_data = exchange_code_for_token(
            client_id=client_id,
            client_secret=client_secret,
            code=code,
            redirect_uri=redirect_uri
        )

        print(token_data)
        
        # Extract tokens from the response
        access_token = token_data.get('access_token')
        refresh_token = token_data.get('refresh_token')

        # Store the refresh token securely (this is just an example, use your method)
        save_refresh_token(refresh_token)

        print('Access token:', access_token)

        return JsonResponse({
            'message': 'Authorization successful',
            'status': 200,
            'access_token': access_token,
        })
    

    except requests.exceptions.RequestException as e:
        
        return JsonResponse({
            'message': 'Failed to exchange authorization code for tokens',
            'status': 500,
            'error': str(e)
        })

def exchange_code_for_token(client_id, client_secret, code, redirect_uri):

    print ("Exchange code for token")
    token_url = "https://api.amazon.com/auth/o2/token"
    data = {
        'grant_type': 'authorization_code',
        'code': code,
        'client_id': client_id,
        'client_secret': client_secret,
        'redirect_uri': redirect_uri
    }

    print("Data:", data)

    final_token_url = f'{token_url}?grant_type=authorization_code&code={code}&client_id={client_id}&client_secret={client_secret}&redirect_uri={redirect_uri}'
    response = requests.post(final_token_url, data=data)
    response.raise_for_status()
    return response.json()

def save_refresh_token(refresh_token):

    refresh_token = refresh_token

    refresh_token_file = 'refresh_token.txt'

    with open(refresh_token_file, 'w') as file:

        file.write(refresh_token)

    print('Refresh token saved')

Please help me out with this
![Authorization Page](https://github.com/user-attachments/assets/c3124f9c-2ac9-40b2-8644-512e8d02bfe9)
![After Authorization](https://github.com/user-attachments/assets/5c9b7b05-4626-4e2c-bb39-92ec431638e0)

**Comment by jawheral** [comment]
Hi @Bhanishi-at-Github,

OAuth redirect URI doesn't support localhost. You can see this information here in the [FAQ](https://developer-docs.amazon.com/sp-api/docs/general-faq#what-are-the-login-and-redirect-uri-values-to-be-added-in-oauth-information-when-i-am-registering-my-app). 

Furthermore, please follow the right Auth workflow, depending on whether you are testing an authorization from website or from App Store - https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by Bhanishi-at-Github** [comment]
As a redirect URI, I have provided a website URL, but the link is generated
through localhost. Do I have to publish the app for that purpose also?

**Comment by jawheral** [comment]
HI @Bhanishi-at-Github,

Localhost wouldn't work as a redirect URI. 
You can probably either host your app or try to use some localhost tunnel tool for this purpose.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by Bhanishi-at-Github** [comment]
After hosting the application, it still stop at this url:
https://sellercentral.amazon.com/apps/authorize/?amazon_callback_uri=https%3A%2F%2Fsellercentral.amazon.com%2Fapps%2Fauthorize%2Fconfirm%2Famzn1.sp.solution.8d796277-*******c-b059-bb78ef5bc5c4&amazon_state=MTcyNDEzNTE2ODE1NFHv.........O--_vXwtfO-_vQbvv71h77-9Re-_ve-_vUld77-9MO-_vSrZhiHvv73vv719JO-_vWrvv73vv73vv70CUO-_vXIx77-9KVszGAfvv73vv73vv73vv73vv73vv71A77-977-977-977-9Qe-_vQ%3D%3D&version=beta&selling_partner_id=A3***XKZF***XQ

Is this related to callback functionality?

@require_http_methods(["GET"])
def amazon_callback(request):

    print ("Amazon Callback")

    code = request.GET.get('code')
    print(code)

    if not code:
        return JsonResponse({
            'message': 'Authorization code not provided',
            'status': 400
        })

    try:
        # Exchange the authorization code for tokens
        token_data = exchange_code_for_token(
            client_id=client_id,
            client_secret=client_secret,
            code=code,
            redirect_uri=redirect_uri
        )

        print(token_data)

        # Extract tokens from the response
        access_token = token_data.get('access_token')
        refresh_token = token_data.get('refresh_token')

        # Store the refresh token securely (this is just an example, use
your method)
        save_refresh_token(refresh_token)

        print('Access token:', access_token)

        return JsonResponse({
            'message': 'Authorization successful',
            'status': 200,
            'access_token': access_token,
        })


    except Exception as e:

        return JsonResponse({
            'message': 'Failed to exchange authorization code for tokens',
            'status': 500,
            'error': str(e)
        })


def exchange_code_for_token(client_id, client_secret, code, redirect_uri):

    import http.client
    import urllib.parse
    import json

    print("Exchange code for token")
    token_url = "https://api.amazon.com/auth/o2/token"
    data = {
        'grant_type': 'authorization_code',
        'code': code,
        'client_id': client_id,
        'client_secret': client_secret,
        'redirect_uri': redirect_uri
    }

    print("Data:", data)

    # Parse the URL
    parsed_url = urllib.parse.urlparse(token_url)
    conn = http.client.HTTPSConnection(parsed_url.netloc)

    # Encode the data
    encoded_data = urllib.parse.urlencode(data)
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded'
    }

    try:
        # Send the POST request
        conn.request("POST", parsed_url.path, encoded_data, headers)
        response = conn.getresponse()
        response_data = response.read()

        # Check for successful response
        if response.status != 200:
            raise Exception(f"Request failed: {response.status} {response.
reason}")

        # Parse the response JSON
        response_json = json.loads(response_data)
        print("Response JSON:", response_json)
        return response_json
    except Exception as e:
        print(f"Request failed: {e}")
    finally:
        conn.close()


Please help me out with this.

**Comment by jawheral** [comment]
Hi @Bhanishi-at-Github,

did you make sure you are following the right [authorization workflow](https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications#how-is-my-application-authorized) for your app? Can you specify which auth workflow (Website or AppStore) you are trying to achieve?

Did you double check your developer profile? whether it is public or private?
Can you check the OAuth Redirect URI you set for your app on developer central? 

<img width="803" alt="Screenshot 2024-08-20 at 11 20 24" src="https://github.com/user-attachments/assets/4e51677b-1579-486f-a478-9f1eccce7d8d">

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by Bhanishi-at-Github** [comment]
I have registered as public developer, I have private web app and
generating link for different sellers.

I have assigned callback URL as redirect URL

**Comment by Bhanishi-at-Github** [comment]
Can you review this ?

https://github.com/Bhanishi-at-Github/printasta_build

**Comment by jawheral** [comment]
@Bhanishi-at-Github can you debug your code? 
Amazon should send you a "spapi_oauth_code" and not simply "code". 
This value must be used for LWA later and be passed as the value for the parameter "code".

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by Bhanishi-at-Github** [comment]
Okay, I will make the changes

**Comment by Bhanishi-at-Github** [comment]
Is there any other change which I have to make?

**Comment by Bhanishi-at-Github** [comment]
https://github.com/user-attachments/assets/e6dd4e52-2557-40e9-812f-3b9eaed99b64

This issue persist and I am unable to figure it out.

**Comment by jawheral** [comment]
Hi @Bhanishi-at-Github,


I suggest that you debug your application. You need to find out whether your callback is being triggered to start (from the logs in the videos, it doesn't look like it's being called: auth/callback).

If it's reaching the callback, please debug the callback code and check if the right values are received.
The parameter name must be in "code", see in Bold below:
`
# Exchange the authorization code for tokens
        token_data = exchange_code_for_token(
            client_id=client_id,
            client_secret=client_secret,
            **code**=spapi_oauth_code,
            redirect_uri=redirect_uri
        )`

I also suggest that you add the state query parameter here to some value you generate: https://github.com/Bhanishi-at-Github/printasta_build/blob/main/appAuth/views.py#L25

Additionally, I suggest that you log out from Seller Central and clear your cookies and site data. Also check your app on Developer Central page, make sure it is in DRAFT status as you are using version=beta and that it didn't reach any authorization limits.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by Bhanishi-at-Github** [comment]
Do I have to add callback URL in redirect URI of Amazon app

**Comment by Bhanishi-at-Github** [comment]
Can you please provide a sample code for this function?

**Comment by Bhanishi-at-Github** [comment]
Callback is triggered but unable to get spapi code. Can you please provide sample code for callback function.

**Comment by Bhanishi-at-Github** [comment]
I am unable to get the code. Also tried with a random code and it worked. 

The url doesn't contain any error it only gives state and seller id after Authorization

**Comment by jawheral** [comment]
Hi @Bhanishi-at-Github,

Can you debug/print the callback request?
E.g `print(request.GET)` and inspect the result?
You should see the query parameters and they must include: state, selling_partner_id and spapi_oauth_code

**Comment by Bhanishi-at-Github** [comment]
![image](https://github.com/user-attachments/assets/0b33d8f1-53ea-425a-8918-a4eaf2e4cde3)

Getting this

**Comment by Bhanishi-at-Github** [comment]
only the code is missing

**Comment by jawheral** [comment]
@Bhanishi-at-Github Please fix the url here
https://github.com/Bhanishi-at-Github/printasta_build/blob/main/appAuth/views.py#L30
It shouldn't contain response_type or scope but add a state

**Comment by Bhanishi-at-Github** [comment]
How can I add a state before hitting the url

**Comment by jawheral** [comment]
@Bhanishi-at-Github,
Can you double check the status of your app on the [Developer Central console](https://sellercentral.amazon.com/sellingpartner/developerconsole/)? 

If you are still facing issues, then kindly contact [Developer Support](https://developer.amazonservices.com/support).

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by Bhanishi-at-Github** [comment]
It's in draft status.

**Comment by Bhanishi-at-Github** [comment]
The redirect URL contains state and seller id query parameters but doesn't include spapi oauth code.
