### ISSUE TITLE
createInboundShipment show "-" in the name of Ship From address

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#4099]
Dear All,

We noticed in recent weeks, the **createInboundShipment** show "-" in the name of the Ship From address
POST /fba/inbound/v0/shipments/{shipmentId}
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#createinboundshipment

![image](https://github.com/user-attachments/assets/c25e0625-12e3-4547-9473-6fd6e2d2a7e1)

This is an Amazon API issue or there was a change that I did not notice?
It has been working fine until recent weeks.

Regards

**Comment by B3lg4r4th** [comment]
I can confirm that we're experiencing the same issue, seems to have started on 30th July.

**Comment by hamduc7** [comment]
Dear All, Any update on this issue?

@amvreddy-amazon

**Comment by hamduc7** [comment]
Today is 30-Aug-2024, Amazon has fixed this issue himself. It works like before now.
