### ISSUE TITLE
[C#] Add implementation to get the credentials from STS

### ISSUE THREAD

**Issue by xavierhd** [amzn/selling-partner-api-models#41]
The library's documentation should specify how to get the developper credentials for the [AWSSigV4Signer](https://github.com/amzn/selling-partner-api-models/tree/main/clients/sellingpartner-api-aa-csharp#awssigv4signer)
Like a lot of others, I thought that I had to use the IAM's `Access key ID`+ `Access key Secret` directly into the `AWSAuthenticationCredentials`. I was wrong.

Like suggested in #31, the `AWSAuthenticationCredentials` properties need to be populated by the value returned by a request to `Amazon.SecurityToken.AmazonSecurityTokenServiceClient.AssumeRoleAsync(...)`.

Note that the missing and required `x-amz-security-token` header is also derived from the call to `AssumeRoleAsync`.

**Comment by jadanah** [comment]
Here's a link to my repo which has all the amazon selling partner api client's with some usage samples built via nswag using httpclient vs. amazon's restsharp implementation.

https://github.com/jadanah/amazon-selling-partner-api-csharp-samples

**Comment by hinavinayak** [comment]
Hello, We have a blog that gives a walkthrough the [C# SDK implementation](https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-the-c-sdk).

Here is the Code Snippet that helps with the STS call and AWS sigv4 signature:

`//Configure your AWS credentials provider :
        AWSAuthenticationCredentialsProvider awsAuthenticationCredentialsProvider = AWSAuthenticationCredentialsProvider.Builder()
            .RoleArn("arn:aws:iam::************:role/SellingPartner")
            .RoleSessionName("postmanSpApi")
            .Build();

        //Configure your LWA credentials :
        LWAAuthorizationCredentials lwaAuthorizationCredentials = LWAAuthorizationCredentials.Builder()
            .ClientId("amzn1.application-*********************")
            .ClientSecret("***********************************")
            .RefreshToken("Atzr|******************************")
            .Endpoint("https://api.amazon.com/auth/o2/token")
            .Build();

        //For Grantless operations (Authorization API and Notifications API), use following code :
        /* LWAAuthorizationCredentials lwaAuthorizationCredentials = LWAAuthorizationCredentials.Builder()
         * .ClientId("amzn1.application-*********************")
         * .ClientSecret("***********************************")
         * .WithScopes(ScopeConstants.SCOPE_NOTIFICATIONS_API, ScopeConstants.SCOPE_MIGRATION_API)
         * .Endpoint("https://api.amazon.com/auth/o2/token")
         * .Build(); */

        //Create an instance of the Sellers API and call an operation :
        SellersApi sellersApi = new SellersApi.Builder()
            .AwsAuthenticationCredentials(awsAuthenticationCredentials)
            .LwaAuthorizationCredentials(lwaAuthorizationCredentials)
            .AwsAuthenticationCredentialsProvider(awsAuthenticationCredentialsProvider)
            .Endpoint("https://sellingpartnerapi-na.amazon.com") // use Sandbox URL here if you would like to test your applications without affecting production data.
            .Build();

        try
        {
            GetMarketplaceParticipationsResponse result = sellersApi.GetMarketplaceParticipations();
            Console.WriteLine(result);
        }
        catch (ApiException e)
        {
            Console.WriteLine("Exception when calling SellersApi#getMarketplaceParticipations");
            Console.WriteLine(e.Message);
        }
    }
}`
