### ISSUE TITLE
How can the API "relist" a SKU, or move it from "closed" to "open"?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#410]
How can the API "relist" a SKU that already exists, or move it from "closed" to "open"?

Is this possible anywhere, via a REST call, or Feed upload, or anything?

Also what about going the other way and moving a SKU into the "closed" state?

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by JokeLove0915** [comment]
I tried to modify the end_date and checked that the end_date has been successfully modified, but the product has not been republished

**Comment by docasar** [comment]
About the PATCH via to close the listing, when I am using the body but I get the error: 90000900 as attribute invalid as offer.end_date can no t be used as this:

{
    "productType": "PRODUCT",
    "patches": [
        {
            "op": "replace",
            "path": "/attributes/offer",
            "value": [
                {
                    "end_date": {
                        "value": "2001-06-06T07:00:00.000Z"
                }}
            ]}
        ]
    }

Another option I tried for body json is: 
{
    "productType": "PRODUCT",
    "patches": [
        {
            "op": "replace",
            "path": "/attributes/offer.end_date",
            "value": ["2001-06-06T07:00:00.000Z"
            ]}
        ]
    }

I got his error: "code": "InvalidInput",
            "message": "Invalid path provided in patch at index of 0.",

Any ideas how to proceed?

**Comment by jawheral** [comment]
Hi @docasar,

Only top-level listings item attributes can be patched. Patching nested attributes is not supported. Please refer to the patchListingsItem operation in the documentation [here](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku).

According to this, the patch operation's path as "path": "/attributes/offer.end_date" is wrong for multiple reasons:
1 - the top-level attribute name is `purchasable_offer` and not `offer`.
2 - it targets a nested attribute `end_date`
3 - the actual property your are looking for is `end_at`

This means the path must be: "/attributes/purchasable_offer". Now the value you provide when the `op` is `replace` will replace the whole purchasable offer and not the specific attribute so make sure not to override any existing data you would like to keep. You can always get the currently saved attributes by using the `getListingsItem` operation. You can then provide replace only the needed.

For example:

```json
{
  "productType": "PRODUCT",
  "patches": [
    {
      "op": "replace",
      "path": "/attributes/purchasable_offer",
      "value": [
        {
          "our_price": [
            {
              "schedule": [
                {
                  "value_with_tax": 10
                }
              ]
            }
          ],
          "end_at": {
            "value": "2024-10-01"
          }
        }
      ]
    }
  ]
}
```

Note: the example is for demonstration purposes and might have validation issues.
Please always refer to the schema from the product type definitions API.

I hope this helps!

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by MetaMan2023** [comment]
> I recently noticed that when you "Closed" a listing on the Seller Central site, it automatically sets the `offer.end_date` field to the time of that update.
> 
> So, I tried updating it via the PATCH thing (see bug [#2562](https://github.com/amzn/selling-partner-api-models/issues/2562) for some oddities there) to set the `offer.end_date` to the normal `None` value. It worked. The listing exited the "Closed" state, although it took about an hour for the SKU to show the difference in Seller Central.
> 
> I then tried again with the PATCH thing to set `offer.end_date` to a date in the past (year 2000), and that also worked. About an hour later Seller Central updated to show the SKU "Closed" again.

Hi John, thanks for this info -- support told me about the "end_date" option, I did not realize (and they did not) that it is pretty much the same option as "Closed".

Questions (if you know from your testing)

* Do you know where "End Date" appears in Seller Central?  I can't seem to find an end date box to manually enter... does it only appear if a date has been actually entered (or the listing "closed")?

* Do you know if a listing is closed (end date set in past), does the ASIN/SKU still appear in the listing reports including FBA listings?   In the past certain situations like pricing too high issues would make a listing not appear in certain reports (I think FBA reports) like they didn't exist at all.  I'm looking for a solution to make a listing be "off" but still exist in reports.

**Comment by johnkw** [comment]
This ticket needs to be reopened until it's fixed. It's insane having a discussion in a closed ticket. @shreeharsh-a 

I don't think "End Date" appears in Seller Central. The 2 dev teams decided to represent the same information in different ways, and hid each from the other. I haven't noticed closed SKUs get removed from reports.

**Comment by MetaMan2023** [comment]
I have gotten "end_by" to work -- and I found out you can "cancel" and end_by by providing a "null" value.

However I am running into a new issue -- if I supply a price for the listing and also "end_by" at the same time (to cancel the listing), if the price puts the listing into a high pricing error, the end_by is ignored....  I'm wondering if it is due to the order other array?

I am doing these in this order in the array:

* Set price
* end_by
* set pricing minimum
* set pricing maximum

If Amazon considers the price too high (pricing error) it seems to accept the price but then not process the "end_by" and close the listing.

Has anyone noticed this?  I'm now testing what happens if I put the "end_by" first in the array, will it accept the end_by status first, then move on to the price?

I understand that in theory setting the price too high is an "error" -- but it's not a "true" error, as Amazon can change it's mind as to what a high pricing error is at any time -- so if we set a price, let's say $100 AND close the listing, Amazon may consider $100 too high now, but it may not consider it too high later -- but in this situation the listing won't be closed when it should be, which creates a problem.  Also of note, Amazon seems to accept the high price, even though it's an error -- so since it accepts the price, it should complete the other tasks.

**Comment by mgrist** [comment]
> I recently noticed that when you "Closed" a listing on the Seller Central site, it automatically sets the `offer.end_date` field to the time of that update.
> 
> So, I tried updating it via the PATCH thing (see bug [#2562](https://github.com/amzn/selling-partner-api-models/issues/2562) for some oddities there) to set the `offer.end_date` to the normal `None` value. It worked. The listing exited the "Closed" state, although it took about an hour for the SKU to show the difference in Seller Central.
> 
> I then tried again with the PATCH thing to set `offer.end_date` to a date in the past (year 2000), and that also worked. About an hour later Seller Central updated to show the SKU "Closed" again.

This used to work for me. Using TypeScript/JavaScript, I would submit a request to set `purchasable_offer.end_at.value` to null, which would reactivate a listing that was previously closed. However, this no longer works for me. The only way I can accomplish it now is by setting the `end_at` property to a future date. Currently, I am setting the date to 5 years in the future until I can find a better solution. 

I noticed that when reactivating a listing in the console UI, the end_at value is set to null (see picture below), but when I try to do the same with the patchListings API, it doesn't work. When setting the end_at to null via the API, it completely removes the property.

<img width="1056" height="500" alt="Image" src="https://github.com/user-attachments/assets/0d6cf709-bbd8-4584-9c07-8d965e7c9999" />

**Comment by TW-API-1** [comment]
Did you ever find a solution please, or are you still setting the end date to a future date e.g. 5 years in the future?

**Comment by johnkw** [comment]
https://github.com/amzn/selling-partner-api-models/issues/410#issuecomment-2102349120 is a solution. It just needs to be fixed in the documentation and then this bug could be closed. It should be re-opened until then. @shreeharsh-a

**Comment by mgrist** [comment]
@TW-API-1 I have found the solution [in the SP-API docs](https://developer-docs.amazon/sp-api/docs/manage-purchasable-offer#delete-an-optional-sub-attribute) under the "Delete an optional sub-attribute" section. It says:

> To granularly delete an optional sub-attribute, use op: "merge" and set the sub-attribute to null
>```json
>{
>    "productType": "PRODUCT",
>    "patches": [
>        {
>            "op": "merge",
>            "path": "/attributes/purchasable_offer",
>            "value": [
>                {
>                    "currency": "USD",
>                    "audience": "ALL",
>                    "marketplace_id": "ATVPDKIKX0DER",
>                    "<sub_attribute>": null
>                }
>            ]
>        }
>    ]
>}
>```


I tested this with the `end_at` attribute, and it worked! So, just use the merge op and set the end_at to `null`. 
```json
{
      "op": "merge",
      "path": "/attributes/purchasable_offer",
      "value": [
            {
                "end_at": null,
                "currency": "USD",
                "audience": "ALL",
                "marketplace_id": "ATVPDKIKX0DER"
            }
        ]   
    }
```
