### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 listPackingOptions Always returns "po00000000-0000-0000-0000-000000000000"

### ISSUE THREAD

**Issue by andyslack** [amzn/selling-partner-api-models#4101]
As per this ticket which was closed: https://github.com/amzn/selling-partner-api-models/issues/641

I am also getting the following response: 

```
[
  {
    "packingOptions": [
      {
        "packingGroups": [
          "pgdeb9e9b2-230d-4782-9d3c-9cd220b43a30"
        ],
        "fees": [],
        "discounts": [],
        "packingOptionId": "po00000000-0000-0000-0000-000000000000",
        "supportedShippingConfigurations": [],
        "status": "ACCEPTED"
      }
    ],
    "pagination": {}
  }
]
```

I have already Created the Inbound plan, generated packing options:

![Screenshot 2024-08-18 at 10 38 07](https://github.com/user-attachments/assets/81b6b7f1-2ab4-4d3c-8fff-fa536c150a55)

However the above is returned... any ideas?

**Comment by ccyun06** [comment]
me too.Have you encountered this problem?https://github.com/amzn/selling-partner-api-models/issues/4102

**Comment by mafge** [comment]
Hello @andyslack.
thanks for reaching out!
Have you tried to continue the flow with the provided `packingOptionId` and ran into some issues? If so please post the error response and the specific call details. Thanks!
Best,
Marc
Selling Partner Developer Services

**Comment by mehrdadsamadie** [comment]
I am having same issue is someone find how to resolve it?

**Comment by mafge** [comment]
Hello @mehrdadsamadie,
thanks for reaching out!
Have you tried to continue the flow with the provided `packingOptionId` and ran into some issues? If so please post the error response and the specific call details. Thanks!
Best,
Marc
Selling Partner Developer Services

**Comment by puppsupr** [comment]
Hi,
Only one packing option is an expected behavior at this time. Team is aware of this and as of now there is no ETA available for when multiple packing options will be shown.
