### ISSUE TITLE
Customer-comment for returns (FBM)

### ISSUE THREAD

**Issue by dustin-bel** [amzn/selling-partner-api-models#4104]
Hi,

I'm using the [xml-returns-report-by-return-date](https://developer-docs.amazon.com/sp-api/docs/report-type-values-returns#xml-returns-report-by-return-date) report to receive the returns. What I am missing is the customer comment, the text that a customer can add to the return reason.

It seems like that [GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA](https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba#fba-concessions-reports) has a customer-comment.

Is there any way to get the return reason and the customer comment for the return (FBM)? Am I using the wrong api or are there other ways to get that data?

**Comment by jawheral** [comment]
Hi @dustin-bel,

Can you try the [Flat File Returns Report by Return Date](https://developer-docs.amazon.com/sp-api/docs/report-type-values-returns#flat-file-returns-report-by-return-date)? This report has a Return Reason attribute.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by dustin-bel** [comment]
Thanks for your response @jawheral. The return reason is not the problem because I receive that one in the flat file and the xml variant. What I am missing is the comment from the customer (buyer comment). See the image below.

![image (1)](https://github.com/user-attachments/assets/e56d4a1f-8c59-43c2-98b7-a29bec6a6bca)

**Comment by jawheral** [comment]
Hi @dustin-bel,

The comments don't seem to be available currently on the reports. Only the reason code is available.

I'm however reaching out to our internal teams to get some more information on this. I will post here when I have updates.

Thank you for the feedback.

Best,
Jawher
Selling Partner API Solutions Architect
