### ISSUE TITLE
Fulfillment Inbound API v2024-03-20. CreateInboundPlan address validation fails without any meaningfull error

### ISSUE THREAD

**Issue by emakunin** [amzn/selling-partner-api-models#4106]
Hello,

I'm using `CreateInboundPlan` operation however for certain addressed it fails with a cryptic validation error. It is impossible to understand what and why is not valid. Even for the addresses that are totally fine from other validation services perspective.

Could you please provide details of what is wrong/missed? Given that most of the fields are optional it's hard to guess/validate what is needed as an input

#### Request
```JSON
{
  "destinationMarketplaces": [
    "A1PA6795UKMFR9"
  ],
  "items": [
     ...
  ],
  "name": "5OD-TXZ",
  "sourceAddress": {
    "addressLine1": "*** ",
    "addressLine2": null,
    "city": "Ghaziabad",
    "companyName": "***",
    "countryCode": "IN",
    "email": "***@***.in",
    "name": "Jeff Besos",
    "phoneNumber": "+91773*******",
    "postalCode": "201007",
    "stateOrProvinceCode": null
  }
}
```
#### Output
```JSON
{
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: Provided address is invalid. Please correct the address and try again.",
      "details": ""
    }
  ]
}
```

**Comment by mafge** [comment]
Hi @emakunin,
thanks for reaching out!
Please have a look at [the docs](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#addressinput) to identify required address fields. There are also length constraints for each field so make sure to comply with them. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by emakunin** [comment]
Hi @mafge the document you refer to is not useful. you can see that half of the fields are optional. However if I don't specify some of them the operation fails. Sometimes when I supply postal code as AP-1234 it fails, but when I supply just 1234 it passes. Each time I have to guess and try.

**Comment by emakunin** [comment]
I believe you should provide a schema for all fields or (actually "and") provide proper error message

**Comment by emakunin** [comment]
Sure,

I cannot provide exact addresses as it's customer's data. So you can assume that "X" chars are valid characters

Input:
```
"sourceAddress": {
    "addressLine1": "XXXX XXXXX ",
    "addressLine2": null,
    "city": "Ghaziabad",
    "companyName": "XXXX XXXXX",
    "countryCode": "IN",
    "email": "XXXXXX@XXXXXX.in",
    "name": "XXXXXX XXXXXX",
    "phoneNumber": "+91773XXXXXXX",
    "postalCode": "201007",
    "stateOrProvinceCode": null
  }
```

Sync response error: 
```
{
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: Provided address is invalid. Please correct the address and try again.",
      "details": ""
    }
  ]
}
```

Input:
```
"sourceAddress": {
    "addressLine1": "XX/X-XX, BASEMENT & XND FLOOR, XXXXXXXX ROAD",
    "addressLine2": null,
    "city": "NEW DELHI",
    "companyName": "XXXXXX XXXXX",
    "countryCode": "IN",
    "email": "XXXXXX@XXXXXX.in",
    "name": "XXXXXX XXXXXX",
    "phoneNumber": "+91773XXXXXXX",
    "postalCode": "110015",
    "stateOrProvinceCode": "DELHI"
  }
```

Async operation error:
```
Operation problems: Problem: WARNING: Address was unable to be verified. Please ensure that this is the address you wish to use before proceeding. Severity: WARNING Details: null Problem code: BadRequest Problem: ERROR: Something went wrong. Please try again later. Severity: ERROR Details: null Problem code: InternalServerError

there's no way to understand what's going wrong.
```

**Comment by mafge** [comment]
@emakunin Thanks for providing the sample addresses! I was able to reproduce your issues on my side. I will follow up with the responsible backend team to improve documentation/error messages.

**Comment by emakunin** [comment]
Hi @mafge,

Any updates? I like the Amazon's resolving approach. Just wait and If no enough complaints from the customers -> close... Is it a new amazon "earn trust" and "customer obsession" ?

**Comment by mafge** [comment]
Hi @emakunin,
thanks for reminding me! The corresponding backend team deployed a fix to show more specific error messages when trying to create an inbound plan with invalid addresses.
