### ISSUE TITLE
Fulfillment Inbound API v2024-03-20. CreateInboundPlan operation failure response does not provide any meaningfull details

### ISSUE THREAD

**Issue by emakunin** [amzn/selling-partner-api-models#4107]
Hello,

I'm trying to create an inbound plan using `CreateInboundPlan` api and the operation fails without any details.

```
    {
      "severity": "ERROR",
      "code": "InternalServerError",
      "message": "ERROR: Something went wrong. Please try again later."
    }
```

After diving deep I tried to create same plan via STA in SellerCentral. And seller central showed an error about insufficient capacity
![image](https://github.com/user-attachments/assets/5360c425-66aa-4828-98bb-1d03bc73edcf)

This error is not provided as an API operation details that makes it impossible for our customers to understand what went wrong. It would be impossible to check every shipment manually to understand what went wrong. Can you please provide the failure context in the response? Or maybe at least some API that I can call to validate the params

**Comment by pacton** [comment]
When will this be resolved? We have the same issue.

**Comment by puppsupr** [comment]
Hi,
In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.
