### ISSUE TITLE
the new api for generate deliveryWindowOptions, it only return abount 45 days data

### ISSUE THREAD

**Issue by jackmin-sw** [amzn/selling-partner-api-models#4109]
Hi, Amazon team
we try to use the new api, when we generate deliveryWindowOptions, it only return abount 45 options, 
`    {
            "availabilityType": "AVAILABLE",
            "endDate": "2024-10-06T00:00Z",
            "validUntil": "2024-10-06T00:00Z",
            "deliveryWindowOptionId": "dwd98b0186-f902-4d68-8bcb-c089eaa79c35",
            "startDate": "2024-09-29T00:00Z"
        }`
Does it mean we have to send our goods to amazon before 2024-10-06T00:00Z? Some times it takes more than 60 days to send our goods to amzon warehouse, could you give some advice for this case?

**Comment by ccyun06** [comment]
me too.

**Comment by mafge** [comment]
Hi @jackmin-sw and @ccyun06,
thanks for reaching out!
Let me check with the backend team if there is a way to get delivery window options that are more than 45 days in the future. I'll come back to you as soon as I have an answer.
Best,
Marc
Selling Partner Developer Services

**Comment by mafge** [comment]
Hi @jackmin-sw and @ccyun06,
the API follows the Send to Amazon flow that you can find on Seller Central. Have you tried if you are able to get other delivery window options in Seller Central? Thanks!

**Comment by jackmin-sw** [comment]
Hi, @mafge when we try to do it in the amzon Seller Central, we can select any date.

**Comment by Christin519** [comment]
Me too

**Comment by puppsupr** [comment]
https://github.com/amzn/selling-partner-api-models/issues/4102 Tracking via the linked thread !
