### ISSUE TITLE
Details about get refresh token

### ISSUE THREAD

**Issue by lisbuenas** [amzn/selling-partner-api-models#4112]
Following the step 4 in the docs https://developer-docs.amazon.com/amazon-shipping/docs/website-authorization-workflow when try to fetch the refresh token from the request.

`curl --location 'https://api.amazon.com/auth/o2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'code=CODE' \
--data-urlencode 'client_id=CLIENT_ID' \
--data-urlencode 'client_secret=CLIENT_SECRET' \
--data-urlencode 'redirect_uri=REDIRECT_URL'`

I got this error below

{
    "error_index": "DRNVjLgflg2etF8bo5d3gwAAAAAAAAABTVTNlk8n99ply_2yROf5-v2h9Lbi83xGcckTNJvqmnLzIW4bK0rQESb3KO-IYGowceaS5l-8ow0LSP9aAyV2n63Ara6IO3o4POrj9ZmGxRrYWNVbCfXB6dZrOOumbDrEqa7JAxwfjlu_rbk0sjtciFchZeGv_73fMgIz6NZ_8t7CvOv4Q_dz-Fz98P7U9de9aXE5vMC2l_OJNYSH2gnkDNvygAsANXeejXtK4w==",
    "error_description": "The request has an invalid grant parameter : code",
    "error": "invalid_grant",
    "request_id": "fb9b8c63-5f84-42b1-a50b-54a5757bdba9"
}

And when remove the code parameter (shows that 'code' is missing)

Which steps we must follow to be able retrieve the refresh token properly?

**Comment by jawheral** [comment]
Hi @lisbuenas,

An LWA authorization code expires after five minutes. Make sure you use it to generate an LWA refresh token before it expires. 

The LWA authorization code is the value you must pass to the "code" parameter.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by jawheral** [comment]
Hi @lisbuenas,

Please reach out our [Developer Support](https://developer.amazonservices.com/support) and provide all data such as client id, seller id and the request id. They will be able to check your actual requests and see if there's any issue on the API side.

Best,
Jawher
Selling Partner API Solutions Architect
