### ISSUE TITLE
Fulfillment Inbound v2024-03-20 Confirm Placement Option failing "Something went wrong"

### ISSUE THREAD

**Issue by brandondev1** [amzn/selling-partner-api-models#4113]
After submitting a confirmPlacementOption request and subsequently checking the status with getInboundOperationStatus, we are getting the following error. The exact same inboundPlanRequest and workflow can be subsequently executed and succeed.  This happens randomly.  
```
{
    "operationStatus": "FAILED",
    "operationId": "c95b5934-4d45-4f3b-a84b-e153925493b9",
    "operation": "confirmPlacementOption",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "InternalServerError",
            "message": "ERROR: Something went wrong. Please try again later."
        }
    ]
}

```

ConfirmPlacementOption request:  
https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf897a2a57-0a5e-4160-9079-b413c61fca5b/placementOptions/pl3d45db51-01e9-4d1a-84f7-98d26a57c161/confirmation

**Comment by mafge** [comment]
Hello @brandondev1,
thanks for reaching out!
Have you tried to call `confirmPlacementOption` again?
Best,
Marc
Selling Partner Developer Services

**Comment by brandondev1** [comment]
> Hello @brandondev1, thanks for reaching out! Have you tried to call `confirmPlacementOption` again? Best, Marc Selling Partner Developer Services

Yes, I try three times to confirm the placement but it fails each time.

**Comment by mafge** [comment]
Hi @brandondev1,
in this case I would recommend to reach out to [developer support](https://sellercentral.amazon.com/gp/mws/contactus.html).
Thanks!

**Comment by brandondev1** [comment]
This was initially happening intermittently, but is now occurring every time

**Comment by brandondev1** [comment]
> This is a very old issue that is probably not getting as much attention as it deserves. We encourage you to check if this is still an issue after the latest release and if you find that this is still a problem, please feel free to open a new issue and make a reference to this one.

Definitely still an issue.  Amazon just hasn't done anything about it.

**Comment by brandondev1** [comment]
Finally got a reply form Developer Support for this issue:

```
Our Internal team has found that bug causing failure of Placement Option and is working on fixing the issue. While I don’t currently have an update, I will follow up with you as soon as additional information is available.
```

**Comment by weilinggu** [comment]
@brandondev1 Good to hear that you are able to get response, Can you share the the case ID?

Thanks
Weiling
Amazon Selling Partner Services

**Comment by brandondev1** [comment]
> @brandondev1 Good to hear that you are able to get response, Can you share the the case ID?
> 
> 
> 
> Thanks
> 
> Weiling
> 
> Amazon Selling Partner Services

15904616761

**Comment by luap2703** [comment]
> [@brandondev1](https://github.com/brandondev1) Good to hear that you are able to get response, Can you share the the case ID?
> 
> Thanks Weiling Amazon Selling Partner Services

This is definitely not yet solved. Happens all the time. Can you please fix this one as soon as possible? We get plenty of customer requests...
