### ISSUE TITLE
How to get the list item attributes property names as a human readable strings?

### ISSUE THREAD

**Issue by brunoamorimdev** [amzn/selling-partner-api-models#4115]
Hello,

I need to be able to get the attributes titles from the property name form to a human readable string.
Are there any resources available to get this information from the API?
 
I assume it has a pattern because I does something similar to what I need in the [Product Types Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#getdefinitionsproducttype).

To ilustrate, I want to be able to get the names of the properties like this:
```
...
"attributes": {
    "total_hdmi_ports": [ // Get this property from "total_hdmi_ports" to, for example, "Total HDMI Ports"
      {
        "value": 4,
        "marketplace_id": "ATVPDKIKX0DER"
      }
    ],
    "resolution": [ // Or get this property from "resolution" to, for example, "Resolution"
      {
        "language_tag": "en_US",
        "value": "4K",
        "marketplace_id": "ATVPDKIKX0DER"
      }
    ],
}
...
```

The purpose is to extract this information as closely as possible to the information available by Amazon.

**Comment by jawheral** [comment]
Hi @brunoamorimdev,

You can take the ProductType for the Catalog item/Listing you are inspecting, fetch the relevant schema from the Product Types Definitions API and get the human readable string you need from the title property.

For example, for the TELEVISION product type:
<img width="475" alt="Screenshot 2024-08-23 at 09 58 10" src="https://github.com/user-attachments/assets/d285bcac-bc94-4bd9-b57b-4b864671532e">

I hope this helps!

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by brunoamorimdev** [comment]
> Hi @brunoamorimdev,
> 
> You can take the ProductType for the Catalog item/Listing you are inspecting, fetch the relevant schema from the Product Types Definitions API and get the human readable string you need from the title property.
> 
> For example, for the TELEVISION product type: <img alt="Screenshot 2024-08-23 at 09 58 10" width="475" src="https://private-user-images.githubusercontent.com/173008950/360840672-d285bcac-bc94-4bd9-b57b-4b864671532e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTUyMDMsIm5iZiI6MTcyNDQxNDkwMywicGF0aCI6Ii8xNzMwMDg5NTAvMzYwODQwNjcyLWQyODViY2FjLWJjOTQtNGJkOS1iNTdiLTRiODY0NjcxNTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMjA4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmMyMDY4MGFiNTlkZmUwYjllYmExOGZmMDdkNDEzYWNkMDllYzQ4M2MzODg2NWVkNGZjNmI5ZjQwNGI2OWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JDKzciNFDZ8qOXxUcgHsR0abDVGJ_i5FYAhkyEQx4v4">
> 
> I hope this helps!
> 
> Best, Jawher Selling Partner API Solutions Architect

Hi Jawher,

Thanks for the help!

Do you happend to have the documentation about this Use Case you showed me?

**Comment by brunoamorimdev** [comment]
Thank you @jawheral .

**Comment by brunoamorimdev** [comment]
> Hi @brunoamorimdev,
> 
> You can take the ProductType for the Catalog item/Listing you are inspecting, fetch the relevant schema from the Product Types Definitions API and get the human readable string you need from the title property.
> 
> For example, for the TELEVISION product type: <img alt="Screenshot 2024-08-23 at 09 58 10" width="475" src="https://private-user-images.githubusercontent.com/173008950/360840672-d285bcac-bc94-4bd9-b57b-4b864671532e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjAzNzksIm5iZiI6MTcyNDQyMDA3OSwicGF0aCI6Ii8xNzMwMDg5NTAvMzYwODQwNjcyLWQyODViY2FjLWJjOTQtNGJkOS1iNTdiLTRiODY0NjcxNTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QxMzM0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2MxZTkwMTA3YWU2YTQ5YzM1Zjg0MjQ4ZjBiZGY1MGUwMTZiY2EwYjY2OGM1Mjg0YTAyYzYzZjk0ZjE5NWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TonOjf7Bz9ZxS1ZLuQvVGlmT5719ghsFga91dZI_5WE">
> 
> I hope this helps!
> 
> Best, Jawher Selling Partner API Solutions Architect

Hey, @jawheral 

One last thing, can you please provide a complete request example that returns this payload?
Would really help to understand which endpoint and the response json we should expect from it.
We are in a documentation oriented phase right now and since this Use Case is not documented, would be glad to have this information to continue our integrations.

**Comment by jawheral** [comment]
Hi @brunoamorimdev,

I can't provide a response example as it varies by different factors such as seller/vendor/marketplace. You need to be registered to call SP-API.

Please refer to this [link](https://developer-docs.amazon.com/sp-api/docs/sp-api-registration-overview) in case you still didn't finish the registration process and learn more about [authorization](https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications) here.

Please navigate to this Product Type Definitions API [operation](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#get-definitions2020-09-01producttypesproducttype). You will find the different parameters needed to call the api. You can also use the [Swagger model](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-model) available for this api to generate code or import in an api client.

Furthermore, check out the Selling Partner API [Sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) to receive static or dynamic responses for your testing and documentation phases.

Additionally, please refer to our videos on youtube. This [video](https://www.youtube.com/watch?v=I8w7OvLU4Q4) shows how the Product Type Definitions API is called (ignore the Listing API part if it doesn't apply to your use case for now).

I hope this helps!

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by brunoamorimdev** [comment]
> Hi @brunoamorimdev,
> 
> I can't provide a response example as it varies by different factors such as seller/vendor/marketplace. You need to be registered to call SP-API.
> 
> Please refer to this [link](https://developer-docs.amazon.com/sp-api/docs/sp-api-registration-overview) in case you still didn't finish the registration process and learn more about [authorization](https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications) here.
> 
> Please navigate to this Product Type Definitions API [operation](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference#get-definitions2020-09-01producttypesproducttype). You will find the different parameters needed to call the api. You can also use the [Swagger model](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-model) available for this api to generate code or import in an api client.
> 
> Furthermore, check out the Selling Partner API [Sandbox](https://developer-docs.amazon.com/sp-api/docs/the-selling-partner-api-sandbox) to receive static or dynamic responses for your testing and documentation phases.
> 
> Additionally, please refer to our videos on youtube. This [video](https://www.youtube.com/watch?v=I8w7OvLU4Q4) shows how the Product Type Definitions API is called (ignore the Listing API part if it doesn't apply to your use case for now).
> 
> I hope this helps!
> 
> Best, Jawher Selling Partner API Solutions Architect

This video helped a lot, just connected the dots on how to retrieve this information!

Thanks, @jawheral
