### ISSUE TITLE
Can I use the listings items API to delete product images?

### ISSUE THREAD

**Issue by Ironkyy** [amzn/selling-partner-api-models#4116]
The product originally had multiple images, I want to use the listings items API to delete the images, leaving only one main image, is that okay?

**Comment by mafge** [comment]
Hi @Ironkyy,
thanks for reaching out!
You can use [patchListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patchlistingsitem) operation to add, replace or delete product values. Please be aware that required attributes cannot be deleted.
Best,
Marc
Selling Partner Developer Services
