### ISSUE TITLE
How to get the number of seller from "ASIN"

### ISSUE THREAD

**Issue by georgelxl6** [amzn/selling-partner-api-models#4118]
I tried to get the sellers number which is selling the same product from ASIN.

**Comment by XinYi1313** [comment]
View the seller ID in the Amazon Seller Central backend

**Comment by GeorgeRukasin** [comment]
I am am going to do by using catalog api and products/pricing api

**Comment by leonardonakagawa** [comment]
Hi @gerogelxl6,

You can look this information by calling the [getCompetitiveSummary](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide#get-the-competitive-summary) API.

With the body below, you can look the ASIN and look the lowestPricedOffers which contains the offers for new condition.

Method: POST
URI: /batches/products/pricing/2022-05-01/items/competitiveSummary

```

{
  "requests": [
    {
      "asin": "B07R89PJY6",
      "marketplaceId": "ATVPDKIKX0DER",
      "includedData": [
        "featuredBuyingOptions",
        "referencePrices",
        "lowestPricedOffers"
      ],
      "method": "GET",
      "uri": "/products/pricing/2022-05-01/items/competitiveSummary"
    }
  ]
}

```

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by georgelxl6** [comment]
Thank you.
Yes I am trying like that.
But I am not sure if the offers number is same as the number of sellers.

**Comment by leonardonakagawa** [comment]
Currently, that is the main method to get this type of data. What is the use case you are looking for? 

Other method is going subscribing for the ANY_OFFER_CHANGED notification, where you can get a notification whenever there is a price change in the top 20 offers and with that you receive a payload with the top 20 competitors offers. Including Seller ID.

Thanks,
Leonardo
