### ISSUE TITLE
Website Authorization Workflow: spapi_outh_token not found in query parameters

### ISSUE THREAD

**Issue by Bhanishi-at-Github** [amzn/selling-partner-api-models#4119]
Hey there!

I am new to amazon seller central as a developer. After building the application which is draft status for my client, I raised one issue #4093 where I was unable to get the callback. Once I fixed that issue, another thing came up, I got query parameters from amazon as mentioned

https://printasta-build.vercel.app/auth/callback/?amazon_callback_uri=https%3A%2F%2Fsellercentral.amazon.com%2Fapps%2Fauthorize%2Fconfirm%2Famzn1.sp.solution.8d796277-9887-484c-b059-bb78ef5bc5c4&amazon_state=MTcyNDQwMjI3NTkxN8i177-9Y2vvv71gOO-_vXLvv71T77-9We-_vRfvv73vv70o77-9a--_vS_vv73vv707eiYa77-977-9H--_vS57dO-_vSVd77-9T--_vU5t77-977-9Vu-_ve-_ve-_vSN5KHJWTO-_ve-_vVnvv73vv7*************&version=beta&selling_partner_id=A3FYFX****V0XQ

In this uri, the spapi_oauth_code was missing and I was getting this screen according to my code.

{
  "message": "Authorization code not provided",
  "status": 400,
  "state": "{amazon_state}",
  "seller_id": "{seller_id}"
}

I have tried with a sample parameter of spapi_outh_code by assigning a random value and it worked until the validation.

Please refer this repo: https://github.com/Bhanishi-at-Github/printasta_build.git

**Comment by Bhanishi-at-Github** [comment]
I needed to do this within a few days please let me know how I can proceed

**Comment by Mizan3050** [comment]
Make sure you are adding state (has to be a number like 1234) parameter in the URI
for eg 
https://sellercentral.amazon.in/apps/authorize/consent?application_id=YOU_APP_ID&version=beta&state=1234

**Comment by Bhanishi-at-Github** [comment]
Yes,  I am adding it

**Comment by Bhanishi-at-Github** [comment]
Still not working

**Comment by leonardonakagawa** [comment]
Hi @Bhanishi-at-Github,

Could you please verify, if you are following this workflow? [Website Authorization Workflow
](https://developer-docs.amazon.com/sp-api/docs/website-authorization-workflow) 

Also, have you updated your app OAuth Login URI and OAuth Redirect URI correctly into the Seller Central?

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by leonardonakagawa** [comment]
Hi @Bhanishi-at-Github,

Can you please [open a support case](https://developer.amazonservices.com/support) with us, providing all of your app details? 

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by Bhanishi-at-Github** [comment]
I have resolved that issue but now I am facing Readonly Database error when storing data in the database.
