### ISSUE TITLE
How to get all listing items from a seller?

### ISSUE THREAD

**Issue by brunoamorimdev** [amzn/selling-partner-api-models#4120]
Hi,

I've been looking for resources to get all products from a seller. 
The resources I've found like the [Listings Items API v2020-09-01](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2020-09-01-reference), which must be used with keywords to search and list items or the identifiers, but I need to list all, without filtering the list.
The [All Listings Report](https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory#all-listings-report) would be great but it's S3 based and requires a lot of work to just get a basic JSON objects list.

Are there any other alternatives for this Use Case?

**Comment by mafge** [comment]
Hi @brunoamorimdev,
thanks for reaching out!
In order to get all listings for a seller you have to use `GET_MERCHANT_LISTINGS_ALL_DATA` report. What do you mean by it's S3 based? Technically you can request the report, check for processing and download the report via the API. No AWS services are required.
Best,
Marc
Selling Partner Developer Services

**Comment by brunoamorimdev** [comment]
> Hi @brunoamorimdev, thanks for reaching out! In order to get all listings for a seller you have to use `GET_MERCHANT_LISTINGS_ALL_DATA` report. What do you mean by it's S3 based? Technically you can request the report, check for processing and download the report via the API. No AWS services are required. Best, Marc Selling Partner Developer Services

Hi @mafge ,

Thank you for the quick and helpful response!

I apologize for the confusion—I misinterpreted the documentation regarding the S3 part. I now understand that the report can be fully managed through the API without needing to involve AWS services.

Thanks again for the clarification!

Best regards,
Bruno
