### ISSUE TITLE
How to retrieve all questions and answers of a product?

### ISSUE THREAD

**Issue by brunoamorimdev** [amzn/selling-partner-api-models#4123]
Hi,

I am currently working on integrating with the Amazon Selling Partner API, and I need to retrieve all the questions and answers related to a specific product.

I’ve thoroughly reviewed the official documentation but couldn’t find any endpoint or clear guidance on how to achieve this.

Could you please provide guidance on the following:
	1. Is there a specific API endpoint that allows me to retrieve all questions and answers for a given product?
	2. If not, is there an alternative method or a combination of endpoints that can be used to achieve this?
	3. Are there any plans to include this functionality in future updates, or is it something that should be handled externally?

I would appreciate any pointers or documentation references that could help with this.

Thank you for your support!

Best regards,
Bruno

**Comment by jawheral** [comment]
Hi @brunoamorimdev,

There is currently no API or report to retrieve all the questions and answers related to a specific product.

Best,
Jawher
Selling Partner API Solutions Architect
