### ISSUE TITLE
How to retrieve all conversations and messages for a given seller?

### ISSUE THREAD

**Issue by brunoamorimdev** [amzn/selling-partner-api-models#4124]
Hi,

I am integrating with the Amazon Selling Partner API and need to retrieve all conversations and messages associated with a specific seller.

After reviewing the official documentation, including the [Messaging API](https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference), I wasn’t able to find a direct way to retrieve all conversations and messages for a seller.

Could you please provide guidance on the following:
	1. Is there a specific API endpoint or a combination of endpoints that allows me to retrieve all conversations and messages for a seller?
	2. If not, what is the recommended approach to obtain this data?
	3. Are there any best practices or limitations I should be aware of when attempting to gather this information?

Any help or pointers to the appropriate documentation would be greatly appreciated.

Thank you for your assistance!

Best regards,
Bruno

**Comment by jawheral** [comment]
Hi @brunoamorimdev,

There is currently no way to retrieve all conversations and messages for a specific seller.

Best,
Jawher
Selling Partner API Solutions Architect
