### ISSUE TITLE
Cancelling inbound shipments does not void plans

### ISSUE THREAD

**Issue by jlnstrk** [amzn/selling-partner-api-models#4126]
We're seeing a major issue with the new `2024-03-20` Inbound API where cancelling all shipments of a plan on Seller Central does not seem to void the associated plan, and it is unclear if costs are still charged because of this.

To reproduce:
1. Go through the inbound plan creation flow via the inbound v2024-03-20 API.
2. Navigate to Seller Central and cancel each shipment there.
3. Call `listInboundPlans`: The status is still `ACTIVE`.

**Comment by mafge** [comment]
Hi @jlnstrk,
thanks for reaching out!
There are some limits to the interoperability between Seller Central and the Fulfillment Inbound API. 
From the docs:

> Plans created with the Fulfillment Inbound API can be accessed and edited on Amazon's UI (called [Send to Amazon](https://sellercentral.amazon.com/help/hub/reference/G6925SDD66GDLXJW) (STA)) once placement and transportation options are confirmed. You can also use the API to access plans that were created in [STA](https://sellercentral.amazon.com/help/hub/reference/G6925SDD66GDLXJW) after you confirm placement and transportation options.

Is there any reason for you to cancel the shipment via Seller Central vs. cancel the inbound plan via the API?
Thanks,
Marc
Selling Partner Developer Services

**Comment by jlnstrk** [comment]
> Hi @jlnstrk, thanks for reaching out! There are some limits to the interoperability between Seller Central and the Fulfillment Inbound API. From the docs:
> 
> > Plans created with the Fulfillment Inbound API can be accessed and edited on Amazon's UI (called [Send to Amazon](https://sellercentral.amazon.com/help/hub/reference/G6925SDD66GDLXJW) (STA)) once placement and transportation options are confirmed. You can also use the API to access plans that were created in [STA](https://sellercentral.amazon.com/help/hub/reference/G6925SDD66GDLXJW) after you confirm placement and transportation options.
> 
> Is there any reason for you to cancel the shipment via Seller Central vs. cancel the inbound plan via the API? Thanks, Marc Selling Partner Developer Services

We don’t intend to use Seller Central for cancellation as part of any regular workflow, but we do expect this to be a way to safely clean things up when something breaks. 

This is most certainly something that our customers need: Let’s say an inbound plan with shipments is created via API and issues arise after that; maybe around the OAuth flow or there’s some other issue that causes the customer to lose the ability to cancel via our software. It must be possible to successfully cancel the shipment and void the transport fees via Seller Central in such a case, as long as the void deadline hasn’t passed yet.

**Comment by mafge** [comment]
@jlnstrk Makes sense. My recommendation is to contact [developer support](https://sellercentral.amazon.com/gp/mws/contactus.html) in this case.
Thanks!
