### ISSUE TITLE
Inbound shipment marked as `DELIVERED` directly after creation

### ISSUE THREAD

**Issue by jlnstrk** [amzn/selling-partner-api-models#4127]
We're seeing a major bug with the new 2024-03-20 Inbound API where shipments are marked as `DELIVERED` immediately after creation. In those instances, no further API calls have been sent after `confirmTransportationOptions`.

**Comment by mafge** [comment]
Hi @jlnstrk,
thanks for reaching out!
Does this happen for all inbound plans or only in certain instances?
My advice is to contact [developer support](https://sellercentral.amazon.com/gp/mws/contactus.html) for help in this case. Thanks!
Best,
Marc
Selling Partner Developer Services
