### ISSUE TITLE
SubmitShipments Vendor Retail Procurement Breaks Shipments Page

### ISSUE THREAD

**Issue by rsitteam** [amzn/selling-partner-api-models#4131]
Hello,

We're a retail vendor attempting to transition to the SP-API for shipment related functions. We've tested on 2 separate shipments in 2 weeks, and have found that anytime we submit a shipment via API rather than directly in the Vendor portal, our shipment page completely breaks. By breaking, I mean we can't access any past shipments, can't see our recently created shipment, and can't search via ARN or PO Number. This issue somewhat resolves itself after creating enough shipments to fill a full page; however, this definitely seems to be a pretty large bug that needs to be resolved.

**Endpoint:** POST /vendor/shipping/v1/shipments
**Operation:** SubmitShipments
**Payload:**
```
{
  "vendorShipmentIdentifier": "AB12345",
  "transactionType": "New",
  "transactionDate": "2024-08-27T10:54:18",
  "shipmentFreightTerm": "Collect",
  "sellingParty": { "partyId": "ABC12" },
  "shipFromParty": {
    "partyId": "warehouse_id",
    "address": {
      "name": "Company 1",
      "addressLine1": "123 Main Street",
      "city": "New York",
      "stateOrRegion": "NY",
      "postalCode": "12345",
      "countryCode": "US"
    }
  },
  "shipToParty": { "partyId": "ABC1" },
  "shipmentMeasurements": {
    "totalCartonCount": "1",
    "totalPalletStackable": "0",
    "totalPalletNonStackable": "0",
    "shipmentWeight": { "unitOfMeasure": "Lb", "value": "3" },
    "shipmentVolume": { "unitOfMeasure": "CuFt", "value": "10" }
  },
  "collectFreightPickupDetails": { "requestedPickUp": "2024-08-30T00:00:00" },
  "purchaseOrders": [
    {
      "purchaseOrderNumber": "ABC1234",
      "items": [
        {
          "itemSequenceNumber": "1",
          "buyerProductIdentifier": "B00000000",
          "shippedQuantity": {
            "amount": 3,
            "unitOfMeasure": "Eaches",
            "unitSize": 1
          }
        }
      ]
    }
  ]
}
```

**Comment by jawheral** [comment]
Hi @rsitteam,

Please reach out to [Developer Support](https://developer.amazonservices.com/support) and provide all the details. This way we are able to check your requests and reach to the right teams to investigate/fix bugs.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by rsitteam** [comment]
@jawheral I've reached out to Developer Support several times now, with plenty of provided information, and each support rep I've encountered doesn't seem to understand the actual issue. I've provided request headers, request body, endpoint, everything that was asked for, and still nobody seems to be able to assist or misunderstood the issue. This is what brought me here, as I have to assume we're not the only Vendors encountering this issue.

**Comment by jawheral** [comment]
Hi @rsitteam,

I understand your concern. However, even if this issue seems to happen after an SP-API call, it still occurred on Vendor Central.

In case you face this bug again, kindly contact [Vendor Support]([Vendor support](https://vendorcentral.amazon.com/hz/vendor/members/contact)) with the right information including the broken shipment page and other broken functionality on Vendor Central.

Best,
Jawher
Selling Partner API
