### ISSUE TITLE
Restock Report being phased out

### ISSUE THREAD

**Issue by napter** [amzn/selling-partner-api-models#4132]
The restock report states "This report is being phased out in favor of the new FBA Inventory report."

However, I do not see the "FBA Inventory report" available as a report type in the reports API.

**Comment by mafge** [comment]
Hi @napter,
thanks for reaching out!
You can find the available FBA inventory reports on [this page](https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba#fba-inventory-reports). Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by napter** [comment]
Hi, the report that is replacing the restock report is not on the list.

**Comment by mafge** [comment]
@napter Have you checked `GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT`? If yes it would be nice if you could provide some more details on what exactly you are looking for. Thanks!

**Comment by napter** [comment]
Yes, that is the report we use. However that report is being removed by Amazon. The report that is replacing it is missing. 

This is what Amazon says about the restock recommendation report "This report is being phased out in favor of the new FBA Inventory report."

**Comment by napter** [comment]
Ok I'm glad we're on the same page. 

The fba planning data report doesn't have the recommended restock fields. 

The fba inventory report Amazon is referring to is new and does not appear to be in the list of reports available via the API.

**Comment by mafge** [comment]
@napter The reports you can download via Seller Central are not the same you can get via the API. These are two different things, the deprecation for Seller Central doesn't have an effect on the API. You can still continue to use GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT unless it gets deprecated - which is right now not the case according to the [deprecation schedule](https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations).
