### ISSUE TITLE
how can i use JSON_LISITNG_FEED to remove listing's discounted price

### ISSUE THREAD

**Issue by stackWang** [amzn/selling-partner-api-models#4134]
i was trying to delete my discounted price, when i use [patchListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patchlistingsitem) to request.
below is my request body, 
the **body1** request was success, it returns status is ACCEPTED, bus after that when i request [getListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#getlistingsitem),the discounted price still there .
the **body2** was fail, error message is invalid input.
so how can i delete the discounted price as standard request.

**body1**:
```
{
  "productType": "CAMERA_CLEANER",
  "patches": [
    {
      "op": "replace",
      "path": "/attributes/purchasable_offer",
      "value": [
        {
          "currency": "GBP",
          "marketplaceId": "A1F83G8C2ARO7P",
          "our_price": [
            {
              "schedule": [
                {
                  "value_with_tax": 2.09
                }
              ]
            }
          ],
          "discounted_price": []
        }
      ]
    }
  ]
}
```

**body2**:
```
{
  "productType": "CAMERA_CLEANER",
  "patches": [
    {
      "op": "delete",
      "path": "attributes/purchasable_offer/0/discounted_price",
      "value": null
    }
  ]
}
```

**Comment by stackWang** [comment]
can anyone help me figure out this problem (= =!)

**Comment by jawheral** [comment]
Hi @stackWang,

For body2, it is expected that it doesn't work. Only top-level listings item attributes can be patched. Patching nested attributes is not supported. You can read this in the operation's [reference](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku).

For body1, did you wait some time before checking that the discounted price has been removed?

If not, can you try this instead (fully removing the discounted_price)?

```
{
  "productType": "CAMERA_CLEANER",
  "patches": [
    {
      "op": "replace",
      "path": "/attributes/purchasable_offer",
      "value": [
        {
          "currency": "GBP",
          "marketplaceId": "A1F83G8C2ARO7P",
          "our_price": [
            {
              "schedule": [
                {
                  "value_with_tax": 2.09
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
``` 

Another option you could try is to delete the purchasable offer attribute using patchLisitingsItem and then add it again without the discounted_price.

```
{
  "productType": "CAMERA_CLEANER",
  "patches": [
    {
      "op": "delete",
      "path": "/attributes/purchasable_offer"
    }
  ]
}
```

```
{
  "productType": "CAMERA_CLEANER",
  "patches": [
    {
      "op": "add",
      "path": "/attributes/purchasable_offer",
      "value": [
        {
          "currency": "GBP",
          "marketplaceId": "A1F83G8C2ARO7P",
          "our_price": [
            {
              "schedule": [
                {
                  "value_with_tax": 2.09
                }
              ]
            }
          ] 
    }
  ]
}
``` 

Another option is to use the [putListingsItems](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#put-listings2021-08-01itemsselleridsku) operation but here you need to make sure you are providing all your current attributes (you can use the getListingsItem operation to get all your current attributes and use that to provide in the put request update request).

**Comment by stackWang** [comment]
> Hi @stackWang,
> 
> For body2, it is expected that it doesn't work. Only top-level listings item attributes can be patched. Patching nested attributes is not supported. You can read this in the operation's [reference](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku).
> 
> For body1, did you wait some time before checking that the discounted price has been removed?
> 
> If not, can you try this instead (fully removing the discounted_price)?
> 
> ```
> {
>   "productType": "CAMERA_CLEANER",
>   "patches": [
>     {
>       "op": "replace",
>       "path": "/attributes/purchasable_offer",
>       "value": [
>         {
>           "currency": "GBP",
>           "marketplaceId": "A1F83G8C2ARO7P",
>           "our_price": [
>             {
>               "schedule": [
>                 {
>                   "value_with_tax": 2.09
>                 }
>               ]
>             }
>           ]
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> Another option you could try is to delete the purchasable offer attribute using patchLisitingsItem and then add it again without the discounted_price.
> 
> ```
> {
>   "productType": "CAMERA_CLEANER",
>   "patches": [
>     {
>       "op": "delete",
>       "path": "/attributes/purchasable_offer"
>     }
>   ]
> }
> ```
> 
> ```
> {
>   "productType": "CAMERA_CLEANER",
>   "patches": [
>     {
>       "op": "add",
>       "path": "/attributes/purchasable_offer",
>       "value": [
>         {
>           "currency": "GBP",
>           "marketplaceId": "A1F83G8C2ARO7P",
>           "our_price": [
>             {
>               "schedule": [
>                 {
>                   "value_with_tax": 2.09
>                 }
>               ]
>             }
>           ] 
>     }
>   ]
> }
> ```
> 
> Or one more option is to use the [putListingsItems](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#put-listings2021-08-01itemsselleridsku) operation but here you need to make sure you are providing all your current attributes (Full Update) (you can use the getListingsItem operation to get all your current attributes and use that to provide in the put request update request). Check this [guide](https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#updating-a-listings-item) for more information.
> 
> Best, Jawher Selling Partner API Solutions Architect

thanks for your help, @jawheral 
yes, i been try fully remove discounted price like your suggest, and wait for few hours then request the api getListingItem, but it still not working.

the second option it need 2 request, what if one of them fail, so it's not stable.
and third option need fully listing attributes, the body is kind large, i guess it will be working.
so that's no way to patch it use one request and few body content right?

thanks again~

**Comment by jawheral** [comment]
@stackWang 
I expected the first patch with replace op to work. Please also double check that your Sku, sellerId and marketplaceId are all correct.
If this still didn't work, then kindly try one of the other suggested options.
If you are still blocked, then please reach out to [Developer Support](https://developer.amazonservices.com/support) to check your specific requests and what could be going wrong.

Best,
Jawher
Selling Partner API

**Comment by stackWang** [comment]
> @stackWang I expected the first patch with replace op to work. Please also double check that your Sku, sellerId and marketplaceId are all correct. If this still didn't work, then kindly try one of the other suggested options. If you are still blocked, then please reach out to [Developer Support](https://developer.amazonservices.com/support) to check your specific requests and what could be going wrong.
> 
> Best, Jawher Selling Partner API

yes , the first patch i being try, the feed result seems no problem, but actually the result not change, so im not sure what the action did. 
now i found a new way to delete the discounted price, the way is set a expired time to the start_at & end_at, haha, not a good idea but it worked.
thanks for your help.
