### ISSUE TITLE
Unable to create a subscription when adding "marketplaceIds" to the payload.

### ISSUE THREAD

**Issue by ngtuan96lc** [amzn/selling-partner-api-models#4135]
We have three marketplaces in South America, including the US, CA, and MX.
Currently, we just want to receive notifications from the US marketplace. We performed calling SP-API to create it, but I always got the error that looked like this:
```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Request has missing or invalid parameters and cannot be parsed.",
            "details": "EventFilter Payload {\"marketplaceIds\":[\"ATVPDKIKX0DER\"],\"eventFilterType\":\"ORDER_CHANGE\"} failed to validate for notification type ORDER_CHANGE"
        }
    ]
}
```

This's cURL: 
```
curl --location 'https://sellingpartnerapi-na.amazon.com/notifications/v1/subscriptions/ORDER_CHANGE' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'x-amz-access-token: Atza|IwEBIHjH6oj1 ...' \
--header 'Cookie: session-id=142-2150161-1610463; session-id-time=2353226218l; session-token=e3J80rd5pidqbj4 ... ; ubid-main=132-7846095-7891406' \
--data '{
    "destinationId": "e78d72a1-ee4c-45dd-97fa-b173b84539e1",
    "payloadVersion": "1.0",
    "processingDirective": {
        "eventFilter": {
            "eventFilterType": "ORDER_CHANGE",
            "marketplaceIds": [
                "ATVPDKIKX0DER"
            ]
        }
    }
}'
```

Please help to check the API. We are looking forward to your response.
Thanks.

**Comment by jawheral** [comment]
Hi @ngtuan96lc,

Can you also try adding the [orderChangesTypes](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-reference#orderchangetypes) array to the payload and see that fixes the issue? 
If you are interested in both order change types, try adding both available values to the payload such as:

`"orderChangeTypes": [
            "OrderStatusChange",
            "BuyerRequestedChange"
          ]`

I also suggest that you check the ORDER_CHANGE subscription tutorial: https://developer-docs.amazon.com/sp-api/docs/tutorial-subscribe-to-order-change-notification

And use the Notifications API swagger model https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-model (can be imported to api client such as Postman for example) to run the API and make sure it is not an issue in your current way of formulation the request.

If all this doesn't fix the issue, then please reach out to [Developer Support](https://developer.amazonservices.com/support) and provide all the request details.

I hope this helps.

Best,
Jawer
Selling Partner API Solutions Architect

**Comment by ngtuan96lc** [comment]
Hi @jawheral , I've just tried. 
The result was the same when adding orderChangeTypes. 
![image](https://github.com/user-attachments/assets/0b9e9359-b978-4d79-a8a0-da4300f308a2)

**Comment by ngtuan96lc** [comment]
I created a new developer support ticket to get help. Thank you @jawheral

**Comment by yukselaktepe** [comment]
I encountered this error today as well, and I’m making the request as described in the documentation. It seems like the issue persists on the API side. @ngtuan96lc  , are you still experiencing the issue?

**Comment by leonardonakagawa** [comment]
Hi @yukselaktepe,

I recommend you try again using the request from the documentation that @jawheral informed [Step 1. Subscribe to the ORDER_CHANGE notification](https://developer-docs.amazon.com/sp-api/docs/tutorial-subscribe-to-order-change-notification#step-1-subscribe-to-the-order_change-notification). I reproduced the behavior using the payload from the documentation and it is working as expected.

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
