### ISSUE TITLE
Inquiry: Workflow Impact Due to Deprecation of Existing APIs with the Introduction of Fulfillment Inbound API v2024-03-20

### ISSUE THREAD

**Issue by umutyusuf** [amzn/selling-partner-api-models#4136]
Our workflow is significantly impacted by the updates to the Fulfillment Inbound API, specifically the deprecation of existing APIs. Currently, we provide a solution to sellers that enables them to scan each item, print a label, and immediately apply it before moving on to the next item. This process is facilitated by the createInboundShipmentPlan operation from Fulfillment Inbound API v0. By supplying a single SKU to this API, we receive the fnsku, allowing the seller to instantly print and apply the label to the scanned item. This scan-and-label workflow is crucial for many sellers we support. After all items are labeled, the seller proceeds with boxing and shipping the items to Amazon fulfillment centers, following the previous Seller Central workflow.

  However, with the introduction of the new Fulfillment Inbound API v2024-03-20 and the deprecation of the createInboundShipmentPlan operation, we can no longer offer the same experience. Specifically, we are unable to obtain the fnsku necessary for sellers to print labels for scanned items in real-time. To address this, we have explored the following approaches, but none have met our requirements:

  We attempted to use the putListingsItem operation from the Listings Items API v2021-08-01 and then call getListingsItem to retrieve the fnsku. However, this process takes at least an hour for the fnsku to be ready for a single item, which is not practical for our workflow.

  We also tried sending feeds, such as POST_FLAT_FILE_INVLOADER_DATA (which is deprecated and will soon be removed) or the JSON_LISTINGS_FEED. Once processed, we checked for the fnsku. Unfortunately, since this approach is asynchronous and has stricter rate limitations, it is not feasible for sellers who need to scan 200 items within an hour.

  Despite thoroughly reviewing the documentation, we have not found any operations that provide the fnsku before creating the listing. Are we overlooking something, or does the new API structure make it impossible to support this workflow going forward?

We would greatly appreciate your guidance in resolving this issue.

**Comment by umutyusuf** [comment]
> Hi @umutyusuf, thanks for reaching out! After calling `createInboundPlan` you can use [listInboundPlanItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20inboundplansinboundplaniditems). The response should contain the fnsku for each item. Hope that helps! Best, Marc Selling Partner Developer Services

@mafge Thanks for immediate response, but I think you missed the main concern I laid out in the issue. The issue is not failing to obtain fnsku eventually. I'm trying to investigate if it's possible to obtain it as the listing process goes. `createInboundPlan` is the final stage of the listing in our phisical workflow in terms of arranging all the items and finalizing the labeling.

**Comment by mafge** [comment]
@umutyusuf So just to clarify, you want to get the fnsku while the listing not even has been created/listing creation is ongoing?

**Comment by umutyusuf** [comment]
> @umutyusuf So just to clarify, you want to get the fnsku while the listing not even has been created/listing creation is ongoing?

@mafge exactly. current workflow allows this via `createInboundShipmentPlan` method being invoked with a single item.

**Comment by gitsaved** [comment]
We have the same issue along with many 3p listing services as well that offer "label as you list" as part of the workflow. This is crucial for us so the client does not need to handle the items multiple times. They have the product in hand to scan the barcode to list a new product so being able to label it at that stage is highly desirable. Many 3p listing services have offered this as a core workflow enhancement for 10+ years.

With the new workflow we can offer label printing only at the box contents phase, but there is a catch. When we list a new SKU with listings api (exists in catalog, but new sku for seller), it takes 45+ minutes for the price field to update allowing us to request a shipment with the particular SKU. The listing shows "discoverable" within minutes but with "0.00" price. Despite the price being sent with the JSON request, it takes usually around 45 mins to populate which delays us from creating a shipment with the new SKU or getting the FNSKU value. We have even tried running a PATCH on the price once the listing is discoverable, which does not seem to help.

As it stands I think we have users scan in items to create listings, then wait one hour before the next steps can be performed. Once we can create a shipment and get FNSKU the customer must match up the labels with the products they scanned in an hour ago which is a lot more difficult than the previous capabilities.

I would love to know how we can get the price to update faster on a new SKU so the offer is not sitting in incomplete so long as well.

**Comment by mafge** [comment]
@puppsupr Any ideas for this use case?

**Comment by umutyusuf** [comment]
Testing the new APIs that are expected to replace the existing ones, we ran into a huge issue and are currently communicating with the support team. The initial response was appalling because not only is it now impossible to provide the label as you listed, but it also seems impossible to provide any kind of workflow with the new APIs where the prep owner field is not required for the listed product.
The API returns the available prep owner types that can be provided for a given SKU, and if you provide (only NONE in our use case) one from the list, the operation fails, stating that the prep type is required. The response from Seller Central was that the seller is expected to perform some operations on Seller Central STA UI prior to performing the inbound plan prepare action, and the API is not there yet.

Are we the only ones left in the dark and missing some announcements, or is this a common disaster?

**Comment by midi-red** [comment]
We are facing same issue: https://github.com/amzn/selling-partner-api-models/issues/4195
This is very critical for users. It will affect the existing workflow and cause labelling mistakes when you add several items in a plan and later on print their label.

**Comment by puppsupr** [comment]
Hi,
The new APIs doen't generate FNSKU. The pre-req to use the FBA Inbound v2024 APIs is to convert your listings to FBA listings using [JSON Listings Feeds API](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#prerequisite-step-create-a-listing-and-convert-it-to-fba). This is expected behavior. You can't create an FBA shipment without first having made a SKU be an FBA SKU.

Your feedback had been taken to the product team.

**Comment by cmlkx** [comment]
Agreed, this blocks real-time labeling workflows and would prevent real-time boxing.

@puppsupr Please look at the way the old API calls used to work.  They would take: MSKU+ASIN+Condition and return FNSku.

cross-reference:
https://github.com/amzn/selling-partner-api-models/issues/4195

**Comment by puppsupr** [comment]
Hi @cmlkx, 
We submitted the feature request for review. Once we receive additional information we will post an update. Please note that we do not have an estimated time of when the implementation will be completed, however, as soon as this occurs, we will post an announcement in the [Announcements Section] (https://developer-docs.amazon.com/sp-api/changelog) of our documentation site.
You can also review our [Release Notes] (https://developer-docs.amazon.com/sp-api/page/release-notes) regarding all changes made to our APIs and you can subscribe to our [RSS feed] (https://developer-docs.amazon.com/sp-api/changelog.rss) to get notified as soon as there is an update.

**Comment by cmlkx** [comment]
any updates here?   The 20th is coming soon

**Comment by cmlkx** [comment]
still not resolved.
