### ISSUE TITLE
MAJOR BUG: Inbound Shipment API: Cancelled/Voided inbound shipment costs (DHL) are not voided. Still getting charged.

### ISSUE THREAD

**Issue by luap2703** [amzn/selling-partner-api-models#4138]
### We are facing a business-critical error with the new inbound shipments API:

Inbound Shipment costs for Amazon carriers (in this case DHL) are not voided/reimbursed when creating a shipment via the new inbound API and cancelling it in <10min manually via the seller central dashboard.
In other words:
When creating and confirming shipment(-plan)s via the API and cancelling/voiding them via the dashboard by the user, the costs are not reimbursed.

This is a bug since deletions in less than 24h must also reimburse the shipping costs as also stated by the FBA inbound shipment dashboard in seller-central and the AGBs/business terms.

**We currently have +30 shipments that are cancelled in minutes after the creating but don't receive a refund for the shipping costs leading to +11k€ in additionally charged costs for one of our users. Please find the list of all relevant shipments attached. The ID should be unique throughout amazon, right?**

**We need a really fast fix and reimbursement here since this critically affects our user/the business we are testing the API with.**

**WE NEED IMMEDIATE HELP TO REFUND THESE COSTS, PLEASE REACH OUT VIA GITHUB OR THE CONTACT DETAILS OF OUR DEVELOPER ACCOUNT THAT CREATED THE SHIPMENTS**

Our email is dev@silkhub.co (we also use this for the developer profile)

We have also opened a ticket at the seller-central but the support is not able to help. We think its an issue with the new API. When creating and cancelling a shipment via the DASHBOARD, the costs are removed from the attached account balance overview. The costs also don't show up on the shipment anymore. This is different for shipments created via API and voided through the seller central.

When creating and confirming a shipment via API and then canceling it, the costs are still in the balance overview and on the shipment.

<img width="1067" alt="Screenshot 2024-08-28 at 16 32 57" src="https://github.com/user-attachments/assets/996ea182-9e01-4c48-a493-76130933d6f2">

A shipment created via API and immediately cancelled via Dashboard still has the costs mentioned on the shipment page and they are noted in the accounts financial balance overview:
<img width="1588" alt="Shipment created via API" src="https://github.com/user-attachments/assets/aae52876-dab7-4fb6-8546-c7c999c9882f">

A shipment created and cancelled via the dashboard has the costs removed and does not show up in the financial overview of the account.
<img width="1607" alt="Shipment created via Dashboard" src="https://github.com/user-attachments/assets/5aed059c-8e2e-4d12-9b13-39adc2aa4493">

[20240828_Missing Reimbursement Shipments.csv](https://github.com/user-attachments/files/16785019/20240828_Missing.Reimbursement.Shipments.csv)

**Comment by luap2703** [comment]
@mafge Could you please help us with this? It's quite urgent. Thanks in advance!

**Comment by mafge** [comment]
Hi @luap2703,
thanks for reaching out!
I will forward this issue internally and come back to you as soon as possible (but this can take awhile). Unfortunately I am not able to help you with the reimbursement, you would need to contact [Amazon Seller Support](https://sellercentral.amazon.com/help/center) and raise a ticket there (small hint: You can ask them to call you back as soon as possible to speed up things). Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by mafge** [comment]
@luap2703 Can you by the way check the status of your inbound plans? Thanks!

**Comment by luap2703** [comment]
@mafge  we checked the status again via API and they were still set to active. We then canceled them again via API so they are now voided, but the costs are still displayed and charged on the balance tab. This must be an API issue and our design customer is charged with 11k€. How do we handle this? How does he get the refund?

**Comment by luap2703** [comment]
@mafge Is there any ad-hoc support we can get for the respective shipments? This is financially more than relevant and we are afraid of having to discuss multiple months with the seller-central support until someone has figured out the mistake.

**Comment by luap2703** [comment]
@mafge We found even more bugs. When creating (also creating the shipments, confirming the costs etc) AND cancelling a Shipment plan via the API, it is not visibly cancelled in the users dashboard. The shipment there is still up and running.

Please see this shipment plan we created for testing purposes: wfaa37461e-37ae-44f7-8d67-a5cfeb8bc207. We created it as stated via API and voided it <10min after creation.

It is VOIDED when you call getInboundPlan but ACTIVE when calling listInboundPlans. In the dashboard it is also still ACTIVE.


The new API seems to be yet disfunctional now and we migrate back to the old one. Still we have 11k€ outstanding inbound shipment fees. We opened so far 3 tickets but haven't heart back from any of them.

**Could you please escalate this case internally? We are more than desperate at the moment since the amount of outstanding costs is business critical for the test user and if charged could even lead to temporary bankcrupty. We don't see anything we can further do at the moment.**

**Comment by luap2703** [comment]
> Hi @luap2703, thanks for reaching out! I will forward this issue internally and come back to you as soon as possible (but this can take awhile). Unfortunately I am not able to help you with the reimbursement, you would need to contact [Amazon Seller Support](https://sellercentral.amazon.com/help/center) and raise a ticket there (small hint: You can ask them to call you back as soon as possible to speed up things). Hope that helps! Best, Marc Selling Partner Developer Services

Hi @mafge we opened so far 3 tickets but haven't heard back. We are now involving a lawyer since we don't see any way that the support will help us in reasonable time (we are more than familiar with the support being unable to solve the simplest tickets and taking months to figure out what is going on, this is much more complicated).

**In your own interest, I would clarify this bug as soon as possible. It would be more than irresponsible to not interfere since more and more sellers / service-providers switch towards the new API and not receiving refunds for shipments is a serious financial thread.**

**Comment by mafge** [comment]
Hi @luap2703,
first of all sorry for the inconveniences! I forwarded your request to the responsible backend team, but due to public holidays in the US I didn't get a response so far. I'll let you know as soon as I have something to report.

**Comment by luap2703** [comment]
Neither is this a very old issue nor does it seem to be fixed.

@mafge  could you please follow up on this? The seller support (after writing through our lawyer) has admitted the bug and refunded the costs. Is the bug already fixed in the meantime?

**Comment by mafge** [comment]
Hi @luap2703,
great to hear that seller support was able to help you!
I tested today and I wasn't able to reproduce the issue anymore.
