### ISSUE TITLE
Missing Attributes for CatalogAPI v20220401 

### ISSUE THREAD

**Issue by cmlkx** [amzn/selling-partner-api-models#4139]
Hello!

Thank you for the recent enhancements to the CatalogAPI v20220401 that you announced in this message:
 https://developer-docs.amazon.com/sp-api/changelog/catalog-items-v2022-04-01-updated-to-include-additional-attributes

Unfortunately it looks like some critical information is still missing.  For a very simple example ASIN of 1778400329 these items are still missing (I will upload a sample json document to accompany this ticket):

- Page Count (present in v0 as payload.Items[0].AttributeSets.NumberOfPages)
- MSRP (present in v0 as payload.Items[0].AttributeSets.ListPrice.Amount)
- Binding (present in v0 as payload.Items[0].AttributeSets.ListPrice.Binding)
- Edition (present in v0 as payload.Items[0].AttributeSets.Edition)**

These fields are critical for us to ensure customers are listing the correct items.  Can you please look in to the missing product specific attributes and escalate with a dev team ASAP?

Sample JSON (see attached) is included for both CatalogAPIv0 and CatalogAPIv20220401.

[1778400329-CatalogItemsAPIv0.getCatalogItem.json](https://github.com/user-attachments/files/16788047/1778400329-CatalogItemsAPIv0.getCatalogItem.json)
[1778400329-CatalogItemsAPIv20220401.searchCatalogItems.json](https://github.com/user-attachments/files/16788048/1778400329-CatalogItemsAPIv20220401.searchCatalogItems.json)

_Also see ticket #15917724531 via SellerCentral dev support_

Thank you!

**Comment by mafge** [comment]
Hi @cmlkx,
thanks for reaching out!
Are you aware of [includedData](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#includeddata) query param for `getCatalogItem` as well as `searchCatalogItem`? I was able to find the information you are requesting by setting `includedData: attributes`. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by cmlkx** [comment]
@mafge - you are my freaking hero sir!!!   That was the issue!!!!

Is there any way I can buy you a beer????? 😭🍺

**Comment by mafge** [comment]
@cmlkx glad that I was able to help! 
I take a virtual beer - Cheers!
