### ISSUE TITLE
Report GET_MERCHANT_LISTINGS_ALL_DATA does not contain all fields according documentation

### ISSUE THREAD

**Issue by skcxck** [amzn/selling-partner-api-models#4140]
Hi, 
referring to Issue #3999 
for Report `GET_MERCHANT_LISTINGS_ALL_DATA` we receive undocumented fields `deprecated column`.

deprecated columns affects only some customers for unknown reason on this report.
We fetch reports for marketplace Germany `A1PA6795UKMFR9`

Request:

```
POST https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/reports
{
"reportType": "GET_MERCHANT_LISTINGS_ALL_DATA",
"marketplaceIds": ["A1PA6795UKMFR9"]
}
```

Result report headers via
`GET https://sellingpartnerapi-eu.amazon.com/reports/2021-06-30/documents/{$reportDocumentId}`

```
item-name
item-description
listing-id
seller-sku
price
quantity
open-date
Deprecated column
item-is-marketplace
product-id-type
Deprecated column
item-note
item-condition
Deprecated column
Deprecated column
Deprecated column
asin1
Deprecated column
Deprecated column
will-ship-internationally
expedited-shipping
Deprecated column
product-id
Deprecated column
add-delete
pending-quantity
fulfilment-channel	
optional-payment-type-exclusion
merchant-shipping-group
status
Minimum order quantity
Sell remainder
```

I am happy to provide further details.
thanks

**Comment by mafge** [comment]
Hi @skcxck,
thanks for reaching out!
"Deprecated column" are deprecated attributes that are retained to preserve the ordinals as many dependencies (internal and external) rely on ordering of the columns. There is no way to remove them when requesting reports programmatically. Make sure to comply with our [best practices](https://developer-docs.amazon.com/sp-api/docs/reports-api-best-practices) to not run into any issues. Hope that helps!
Best,
Marc
Selling Partner Developer Services
