### ISSUE TITLE
How to get notifications about changes in the Listing Item details?

### ISSUE THREAD

**Issue by brunoamorimdev** [amzn/selling-partner-api-models#4141]
Hi,

I’m looking for a notification type that can inform me if a seller’s listing item has changed. Specifically, I’d like to be notified about changes in:

• Item name
• Description
• Attributes

I’ve reviewed the [ITEM_PRODUCT_TYPE_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notification-type-values#item_product_type_change), [LISTINGS_ITEM_STATUS_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notification-type-values#listings_item_status_change), and [LISTINGS_ITEM_ISSUES_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notification-type-values#listings_item_issues_change) documentation, but none of these seem to fit my use case.

I am considering the possibility of scheduling a [GET_MERCHANT_LISTINGS_DATA_LITE](https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory#all-listings-report) report and then retrieving each item’s details from the SKUs. This seems to be the only available option.

Any help or pointers to the appropriate documentation would be greatly appreciated.

Thank you for your assistance!

Best regards,
Bruno

**Comment by jawheral** [comment]
Hi @brunoamorimdev,

SP-API doesn't currently offer a notification on the listings attributes changes.

The report you are referring to cannot be scheduled, it can only be requested but you can experiment whether it serves your use case.

FYI, there's a [notification](https://developer-docs.amazon.com/sp-api/docs/notification-type-values#branded_item_content_change) informing about an item content changes such as attributes and images but only for branded items currently.

Closing this issue. For similar questions, please start a Q&A [Discussion](https://github.com/amzn/selling-partner-api-models/discussions).

Best,
Jawher
Selling Partner API
