### ISSUE TITLE
An error occurred in confirmTransportationOptions. As long as fba is divided into multiple warehouses, the following error will occur. Why is this?

### ISSUE THREAD

**Issue by asd6979448** [amzn/selling-partner-api-models#4144]
{"operation":"confirmTransportationOptions","operation_id":"028e327c-1d1b-4ff9-a8c2-95d3a81c9598","operation_problems":[{"code":"InternalServerError","message":"ERROR: Something went wrong. Please try again later.","severity":"ERROR"}],"operation_status":"FAILED"}

**Comment by a344241086** [comment]
me too

**Comment by kxrdit-2** [comment]
Hi, have you solved this problem? I have the same problem.

**Comment by asd6979448** [comment]
> Hi, have you solved this problem? I have the same problem.

No, it still is.

**Comment by loco925** [comment]
Hi, have you solved this problem? I have the same problem.您好，您解决了这个问题吗？我有同样的问题。

**Comment by puppsupr** [comment]
Hi,
In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

**Comment by johnkw** [comment]
See also bug #4436 -- did anyone find a fix for this?
