### ISSUE TITLE
UpdateShipmentTrackingDetails failed

### ISSUE THREAD

**Issue by wanjj2014** [amzn/selling-partner-api-models#4145]
The Transportation Options were all  FREIGHT_LTL, because we use non_amazon_parterned_carriers,so we choose the carrier OTHER.
We got the boxIds from the Operation listShipmentBoxes. 
When we update the trackingIds with the operation UpdateShipmentTrackingDetails, we get the errors response "UpdateShipmentTrackingDetails cannot be processed because the following invalid boxIds were found in the request",
Was anyone update shipment tracking details successfull，I need you help ?

**Comment by puppsupr** [comment]
HI for LTL you need to provide below structure,

{{baseUrl}}/inbound/fba/2024-03-20/inboundPlans/:inboundPlanId/shipments/:shipmentId/trackingDetails

{
  "trackingDetails": {
    "ltlTrackingDetail": {
      "freightBillNumber": [
        "{{freightBillNumber}}"
      ],
      "billOfLadingNumber": "{{billOfLadingNumber}}"
    }
  }
}

Attaching the [postman collections](https://www.postman.com/galactic-rocket-691225/selling-partner-api-for-fulfillment-inbound-fba-v2024/overview) to check for specific use-cases

**Comment by wanjj2014** [comment]
@puppsupr The Transportation Options were all FREIGHT_LTL，but we actually use non-Amazon partnered Small Parcel Delivery (SPD), So I have no freightBillNumber and billOfLadingNumber. How did we do?

**Comment by puppsupr** [comment]
Hi,
billOfLadingNumber is optional but you need to provide the freightBillNumber that you get from your carrier
