### ISSUE TITLE
JSON merchant group enumerated?

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4148]
Hi, I'm getting following error

            "messageId": 1,
            "code": "90244",
            "severity": "ERROR",
            "message": "Invalid enumerated value '\"Parcels\"' for attribute 'merchant_shipping_group'.",
            "attributeName": "merchant_shipping_group"

In the feed:

         "merchant_shipping_group":[{"value":"Parcels"}]

This works OK in XML feed:

    <MerchantShippingGroupName>Parcels</MerchantShippingGroupName>

It's also weird that merchant_shipping_group should be Enum? In schema property "value" is "string"

Would you have any advice

**Comment by jawheral** [comment]
Hi @NoxArt,

Please review this [tutorial](https://developer-docs.amazon.com/sp-api/docs/tutorial-retrieve-merchant-shipping-templates) to see how you can retrieve you merchant templates and set them using the merchant_shipping_group attribute. You basically should call the Product Type Definitions API to retrieve the enum value and not the enum name for the Listings API.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by NoxArt** [comment]
Thank you, I will try

**Comment by NoxArt** [comment]
@jawheral May I ask how to I find out which Enum/GUID belongs to which Group/Enum Name?
I thought it's keeping the same order, but in this case it's clearly wrong
![image](https://github.com/user-attachments/assets/e84ef243-81aa-4429-8cf0-8d25550ed11f)
I'm pretty sure legacy-template-id belongs to the Standard-something but legacy-template-id is 4rd while Standard is 3th, so there's a mismatch

Thank you

**Comment by jawheral** [comment]
Hi @NoxArt,

I understand that you are not able to identify which shipping template id is for which enumName.
Could you please share the request id that returned the response in your screenshot? or a similar request id?

Can you also share which one is set to be the Default template in the Seller Central account in case you have access to this?

I need this information in order to support you here.

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by NoxArt** [comment]
It looks like it's actually correct, I just didn't expect the legacy template to be named Toners and not Standard, sorry
