### ISSUE TITLE
New ASINs exhaustion error

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4153]
Hello, we have a problem that we attempted to create a new ASIN, but got an error that our ASIN creation limit has been exhausted ... however as far as we know we haven't created any (or just very few). But maybe we did unintentionally - is there a way to list newest created (not updated?) ASINs, which would show those that led to the exhaustion? Or even some history or log of updates like new listing, deleted listing etc
I checked the Api docs but could not find a call to search listings or anything

Thank you so so much for any help!

**Comment by mafge** [comment]
Hi @NoxArt,
thanks for reaching out!
To protect the onsite shopping experience for our customers, we limit the number of listings (new ASINs) that you can create in a given week until you establish a sales history with Amazon. As you increase your sales, your capacity will increase. We encourage you to prioritize the products you are listing to increase your sales quickly. So it is really about the total number of new ASINs that you create, not specific ones. You can find further information on [Seller Central](https://sellercentral.amazon.com/help/hub/reference/G201844590).
Best,
Marc
Selling Partner Developer Services

**Comment by NoxArt** [comment]
Thank you, I understand, but we are not a new seller, we are there for like 10 years ... and we have not intentionally added new ASINs, but somehow we are getting the error anyway, so there's an issue somewhere and we don't know where, and I'm at loss how to investigate. I tried to compare Inventory reports and All listings reports and it does give some info, but I don't know to see which ASINs are newly created there

**Comment by mafge** [comment]
@NoxArt I see. Sorry for the inconveniences. Unfortunately there is no easy way to check which ASINs have been created by you. Please reach out to [Selling Partner Support](https://sellercentral.amazon.com/help/center) for further clarification.

PS: What you could do is check the creation date of your listings and check whether you are the only offer for that product on the local Amazon page -> most likely you created that ASIN.
