### ISSUE TITLE
Fulfillment Inbound 2024-03-20:  Almost never get more than one placement option

### ISSUE THREAD

**Issue by brandondev1** [amzn/selling-partner-api-models#4154]
When getting placement options, we almost never get more than one option which is always 1 shipment.  We always get multiple options when using Seller central.

**Comment by kxrdit-2** [comment]
I also encountered such a problem, and then I found some instructions here https://sellercentral.amazon.com/help/hub/reference/external/GC3Q44PBK8BXQW3Z, I hope it will be useful to you

**Comment by brandondev1** [comment]
> I also encountered such a problem, and then I found some instructions here https://sellercentral.amazon.com/help/hub/reference/external/GC3Q44PBK8BXQW3Z, I hope it will be useful to you

Thank you.  That helps to see how the options are calculated

**Comment by jawheral** [comment]
Hi @brandondev1,

This is not an issue and as provided on https://sellercentral.amazon.com/help/hub/reference/external/GC3Q44PBK8BXQW3Z there are valid reasons for why a placement option will or will not be available.

If this is still a problem for you, please create a new issue with more details about the request and potential differences with Seller Central.

Best,
Jawher
Selling Partner API
