### ISSUE TITLE
SalesRankings data has gone missing from getCompetitivePricingData operation

### ISSUE THREAD

**Issue by repriceit** [amzn/selling-partner-api-models#4156]
Starting yesterday afternoon (9/4), all 'salesRankings' data is now empty for all products on Amazon.  This is for Products Pricing API getCompetitivePricing operation.  This is causing a lot of issues for many Sellers that we support who base their pricing on Amazon Sales Ranks.

Anyone else experiencing this issue?  Amazon can you please address this.

Thanks!

**Comment by jawheral** [comment]
Hi @repriceit,

I'm sorry to learn that you are experiencing issues.

We are aware of this defect and you can find this on the [API Status](https://sellercentral.amazon.com/sp-api-status) page. Our teams are aware of this and will work to resolve it soon.

Best,
Jawher
Selling Partner API

**Comment by jawheral** [comment]
@repriceit,

The issue should be fixed now. Can you confirm that it is fixed for you?

**Comment by repriceit** [comment]
Yep, all better, thanks!  We started seeing sales rank information return as of around 3pm yesterday.

Thanks!
