### ISSUE TITLE
Is there an API to get awd shipping boxes right now?

### ISSUE THREAD

**Issue by Ironkyy** [amzn/selling-partner-api-models#4157]
I need to get the box details of my AWD shipment to fulfill my business needs, is there any way I can get it?

**Comment by jawheral** [comment]
Hi @Ironkyy,

You can check the Amazon Warehousing and Distribution API of the Selling Partner API. These might fulfil your use case.
You can follow the API [reference](https://developer-docs.amazon.com/sp-api/docs/awd_2024-05-09-reference) and the [use case guide](https://developer-docs.amazon.com/sp-api/docs/amazon-warehousing-and-distribution-api-use-case-guide) for more details.

I hope this helps.

Best,
Jawher
Selling Partner API Solutions Architect
