### ISSUE TITLE
update shipment items

### ISSUE THREAD

**Issue by xyloneX** [amzn/selling-partner-api-models#4158]
generateShipmentContentUpdatePreviews
getShipmentContentUpdatePreview
confirmShipmentContentUpdatePreview
Are these three interfaces used to modify the items in the shipment boxes?

**Comment by Alvaromero** [comment]
Yes

**Comment by puppsupr** [comment]
Yes, please let us know if you see any issues on the same !

**Comment by xyloneX** [comment]
After calling the above three interfaces, I called getShipmentBox and found that boxId became packageId, and the quantity in items did not change.

**Comment by puppsupr** [comment]
Hi @xyloneX,
Please provide full request and response along with inboundPlanId
