### ISSUE TITLE
ListShipmentBoxesResponse: has no destinationRegion in the Box

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#4159]
Hi all,
The below function returns a list of boxes in a shipment:

GET /inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}/boxes

But the box.destinationRegion is not returned.

**Comment by mafge** [comment]
Hi @hamduc7,
thanks for reaching out!
Please note that `destinationRegion` is an optional field according to the [documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#box). Can you tell me which information you exactly need from the region (countryCode, state, warehouseId)? Then I can check if there is another way to get that data for your shipment boxes.
Best,
Marc
Selling Partner Developer Services

**Comment by mafge** [comment]
@hamduc7 You get the available shipment splits by calling [generatePlacementOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generateplacementoptions) followed by [listPlacementOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20inboundplansinboundplanidplacementoptions). Unfortunately there is no possibility to filter specific regions, you will always get all available options in the response.

**Comment by hamduc7** [comment]
@mafge 
Yes, I knew how to get the replacement options but I am looking for a way to filter the Inbound region.

"Inbound Region" in this screen is the carrier that ships to that region?

**Comment by mafge** [comment]
@hamduc7 There is no way to filter the inbound region via the API. 

> "Inbound Region" in this screen filters the carriers that ship to that region?. Am i right?

This is not correct. By `Inbound Region` you choose the location/region of the fulfillment centers you send your inventory. The carrier selection happens later when you generate and list transportation options based on the selected inbound region.

**Comment by hamduc7** [comment]
@mafge Thank you.
Does Amazon have a plan to add this API in recent months?

**Comment by mafge** [comment]
@hamduc7 As far as I know there is no plan to support this feature. The API tries to stick to the flow from Seller Central UI as close as possible. But I'll let the backend team know of your feature request!

**Comment by hamduc7** [comment]
@mafge Thank you very much for your quick response.
