### ISSUE TITLE
How to retrieve the seller notes for FBA orders via Orders API

### ISSUE THREAD

**Issue by sugatabagchi** [amzn/selling-partner-api-models#4161]
Hello SP API Support Team,

We are trying to read the seller notes API field value from the UI, but not sure which API to call.  Since this is an editable field in the UI - so that we can use this field to mark order processed,shipped ,canceled et.c during the life cycle of the orders.
Request to Amazon Support SP API team: 
1. How to update sellernotes for FBA orders using  SP-API
2. How to fetch the sellernotes for FBA orders using SP-API

Thank You
Sugata

**Comment by jawheral** [comment]
Hi @sugatabagchi,

This data is currently not available through SP-API. Are you maybe trying to access the Order Status information? Order status can be retrieved using getOrder from the [Orders API](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#orderstatus).

If there are more reasons why you need this data through the API, please share, I will be happy to learn more about your use cases.

I hope this helps!

Best,
Jawher
Selling Partner API Solutions Architect

**Comment by sugatabagchi** [comment]
Hello @jawheral 
We want to use this to put notes and fetch the same during an order life cycle.

Thanks
Sugata

**Comment by sugatabagchi** [comment]
@amazon-auto @jawheral https://github.com/GitHub-Action
It is still a pending issue and we need amazon API support team's help to review and add this feature.

**Comment by jmac-willko** [comment]
It makes zero sense why a piece of data like Seller Notes, which are integral to reflect in external ERPs, is not something that can be obtained from the API. I can't see a realm where the implementation of this from the SP-API Team is too nuanced to add.
