### ISSUE TITLE
Fulfillment Inbound 2024-03-20 Generate Transportation Options:  Fail to execute COMPUTE_TRANSPORTATION_OPTIONS API with errors

### ISSUE THREAD

**Issue by brandondev1** [amzn/selling-partner-api-models#4165]
Another random ambiguous error from the amazing Fulfillment Inbound v2024-03-20 API with no indication on what the actual issue is.  Seeing this randomly (happens sometimes, but subsequent identical plans will succeed) when executing GetInboundOpertationStatus after GenerateTransportationOptions

```
{
  "operationStatus": "FAILED",
  "operationId": "3bffa62a-8722-46c6-9ae1-f4f7d7e5f49a",
  "operation": "generateTransportationOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "BadRequest",
      "message": "ERROR: Fail to execute COMPUTE_TRANSPORTATION_OPTIONS API with errors."
    }
  ]
}
```

**Comment by puppsupr** [comment]
Hi [brandondev1](https://github.com/brandondev1),
Please provide full request and response along with inbound plan ID.

**Comment by puppsupr** [comment]
#4048

**Comment by brandondev1** [comment]
How is this "similar" to issue 4048?  That is a ConfirmTransportationOptions issue.  This is a different error from GenerateTransportationOptions.
