### ISSUE TITLE
How to know if a placement option is Amazon Optimized, Partial Shipment Split or Minimal Shipment Split?

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#4166]
Dear All,

I see that we can see 3 placement categories on Amazon UI:
Amazon Optimized
Partial Shipment Split
Minimal Shipment Split

![image](https://github.com/user-attachments/assets/b0ffc3ff-bfce-4dc1-aec6-99d23bb4ede8)

But I don't see any API that returns this data.

The **listPlacementOptions** does not have any information about this
The **getShipment** function returns _**shipment.destination.destinationType:**_ AMAZON_OPTIMIZED and AMAZON_WAREHOUSE. So looks like this is the function we want but how to know if it is Partital Split or Mininal Split?

@mafge 

Thank you very much

**Comment by mafge** [comment]
Hi @hamduc7,
thanks for reaching out!
Currently there is no way to determine via API whether a placement option is determined amazon-optimized, partial or minimal shipment split. However you get all the relevant data like fee and number of shipments for each placement option. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by hamduc7** [comment]
@mafge thank you

**Comment by bitdan** [comment]
Hi @hamduc7 ，thank you for raising this issue.

I'm currently encountering a similar problem and was wondering how you managed to resolve it in your case. Could you kindly share your solution or any workaround that worked for you?

Appreciate your help!

**Comment by hamduc7** [comment]
Hi @bitdan 
Unfortunately I also have no way to solve it now. I hope the API will support this in the future.
