### ISSUE TITLE
 How to get shipping options for AMAZON_PARTNERED_CARRIER？

### ISSUE THREAD

**Issue by Ironkyy** [amzn/selling-partner-api-models#4167]
I would like to ask what are the conditions for obtaining the shipping method AMAZON_PARTNERED_CARRIER? Why do I get USE_YOUR_OWN_CARRIER?

**Comment by jawheral** [comment]
Hi @Ironkyy,

Thanks for reaching out.

Please check this [part](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#step-6-use-an-amazon-partnered-carrier-for-your-inbound-shipments-optional) of our Fulfillment Inbound API use case guide.
There are pre-requisites in order to be eligible such as the region or marketplace. Please make sure to go through the seller central page depending on your region/marketplace.

I hope this helps!

Best,
Jawher
Selling Partner API

**Comment by jawheral** [comment]
Hi @Ironkyy,

As you are in the US marketplace, please go through the [Amazon Partnered Carrier program](https://sellercentral.amazon.com/help/hub/reference/201119120) page to learn more about eligibility and requirements of this program.

If this still doesn't help, then please reach out to [Developer Support](https://developer.amazonservices.com/support).

Best,
Jawher
Selling Partner API

**Comment by blairanderson** [comment]
We are seeing about 20% of our shipments coming back without AMAZON_PARTNERED_CARRIER options. 

We are familiar with AMAZON_PARTNERED_CARRIER and have been able to ship many packages to FBA with UPS. 

Some items (seemingly random, non-hazmat) return hundreds of USE-OWN-CARRIER options but we need PARTNERED. 

```json
{
  "inbound_plan_id": "wf86432a00-aef8-42f5-8cc7-2a79223b36ec",                                                
  "destination_marketplaces": "ATVPDKIKX0DER",                                                                
  "status": "ACTIVE",
  "shipments": [
    {
      "status": "WORKING",
      "shipment_id": "sh560db692-ecfc-42a8-bd1d-58a1597cfc28"
    },
    {
      "status": "WORKING",
      "shipment_id": "sh6b7b6e9e-18c9-41f9-b91d-b3286b5dc6b6"
    },
    {
      "status": "WORKING",
      "shipment_id": "sh6ea1fade-10ef-4ceb-8ee6-cf7059f44d78"
    },
    {
      "status": "WORKING",
      "shipment_id": "sh907e9995-c8ab-4655-ad16-86ef7df1a11a"
    },
    {
      "status": "WORKING",
      "shipment_id": "shc10a9396-a1f9-4546-b4c0-b4fe1fc8006a"
    }
  ],
  "placement_options": [
    {
      "status": "ACCEPTED",
      "placement_option_id": "pla50bea2c-d5fd-48ae-9a1d-78d5ff15ad8d"
    }
  ],
  "packing_options": [
    {
      "status": "ACCEPTED",
      "packing_option_id": "pocef57a77-24eb-49ec-a538-1b7a6289c2ec"
    }
  ]
}
 ```
