### ISSUE TITLE
Filter Transportation Option in the listTransportationOptions function

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#4169]
Hi Amazon Team,

Currently, the function listTransportationOptions returns many options that we don't need. 
Is there a way we can filter this list such as shippingMode=GROUND_SMALL_PARCEL

My system only uses GROUND_SMALL_PARCEL carrier but I must wait for all carriers to return.

@mafge 

Thank you

**Comment by mafge** [comment]
Hi @hamduc7,
thanks for reaching out (again)!
Unfortunately there is currently no way to request specific transportation options. You will always get all available options from the backend.
Best,
Marc
Selling Partner Developer Services

**Comment by mafge** [comment]
@hamduc7 Sure, we will take your feedback into account. This post is enough, I'll make sure to let the backend teams know about your feature request.

**Comment by JonLaliberte** [comment]
@mafge Any movement on this?
This process is incredibly slow without this option.
