### ISSUE TITLE
updateshipmentname does not allow its default name.

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#4170]
Hi Amazon,

Amazon generated a default shipment name like: FBA STA (09/12/2024 03:55)-TMB8

As you see, this name  it contains (, /, ):

But the updateshipmentname DOES NOT ALLOW these characters, it only allows **[a-zA-Z0-9-._\s]***

https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#updateshipmentname

Error:
`1 validation error detected: Value 'FBA STA (09/12/2024 03:55)-TMB8' at 'request.name' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9-._\s]*`

So if we want to change the name, we must remove all these invalid characters.

I think this is a bug

**Comment by mafge** [comment]
Hi @hamduc7,
thanks for reaching out!
I understand your confusion regarding the naming conventions. Usually developers use `updateShipmentName` endpoint to replace the name to an internal code/id they use for tracking in their systems. Can you share more information on your use case (why do you submit the same name in the call)?
Best,
Marc
Selling Partner Developer Services

**Comment by hamduc7** [comment]
Hi @mafge 

I don't submit the same name.  What I would like to say is, that the original name has invalid characters but this function does not allow these characters.

For example, let's say the default name is **FBA STA (09/12/2024 03:55)-TMB8**
Now I want to change to FBA STA (09/12/2024 03:55) ABC

=>It is impossible because this new name has invalid characters

But If I change the name to FBA STA 09_12_2024 03_55-ABC=>It will work.

So to update this name: the user must remove invalid characters

Regards,

**Comment by hamduc7** [comment]
@mafge Thank you.
