### ISSUE TITLE
put_listings_item

### ISSUE THREAD

**Issue by baisedongtian** [amzn/selling-partner-api-models#4173]
About List products that do not have a Product ID (UPC, EAN, JAN or ISBN),
I want to upload products using method put_listings_item, but I want to upload them using GTIN exemption. How can I do this? I have already applied for GTIN exemption on Amazon, but when I try to upload using method put_listings_item, I get an error.
'payload': {'issues': [{'attributeNames': ['externally_assigned_product_identifier'],
                         'categories': ['MISSING_ATTRIBUTE'],
                         'code': '90220',
                         'message': '「externally_assigned_product_identifier」は必須ですが、入力されていません。',
                         'severity': 'ERROR'},
                        {'attributeNames': ['merchant_suggested_asin'],
                         'categories': ['MISSING_ATTRIBUTE'],
                         'code': '90220',
                         'message': '「merchant_suggested_asin」は必須ですが、入力されていません。',
                         'severity': 'ERROR'}],

**Comment by mafge** [comment]
Hi @baisedongtian,
thanks for reaching out!
There are very strict rules you have to follow in order to upload products under GTIN exemption, e.g. you have to wait until your exemption has been approved. You can find all the details on [this page](https://sellercentral.amazon.com/help/hub/reference/G200426310). Are you able to add a listing via Seller Central?
Best,
Marc
Selling Partner Developer Services

**Comment by baisedongtian** [comment]
Thank you for your answer. Indeed, I haven't added these items, but I don't know what items I should add and what their values should be. Could you please send me a list of all the items and their possible values?

**Comment by mafge** [comment]
@baisedongtian As far as I can see you only need to provide `supplier_declared_has_product_identifier_exemption` with `true` in your request, then you don't need to specify `merchant_suggested_asin` and `externally_assigned_product_identifier`.

**Comment by baisedongtian** [comment]
Thank you for your answer. I have successfully uploaded now. Additionally, for categories, where can I find information about which fields are mandatory and which are optional? I couldn't find relevant information in the documentation.

**Comment by mafge** [comment]
@baisedongtian You can get a JSON schema from [Product Type Definitions API](https://developer-docs.amazon.com/sp-api/docs/product-type-definitions-api-v2020-09-01-reference) for each specific product type which contains information about required/optional attributes. You can also use this schema to validate your listing before calling `putListingsItem`.
