### ISSUE TITLE
[Err no 30] Read-only file system: '/home/sbx_user1051'

### ISSUE THREAD

**Issue by Bhanishi-at-Github** [amzn/selling-partner-api-models#4174]
Hello !

Recently I am building a project for a company using amazon sp-api. During this process, I have deployed the application and database on Vercel. While retrieving the data from amazon, this OS error comes and it says that someone is trying to write in the file system. I have searched the error online but unable to find a right solution. 

I am sharing my repo of the project. Please review ASAP as I have to meet the deadline of the project.

https://github.com/Bhanishi-at-Github/printasta_build.git

**Comment by mafge** [comment]
Hi @Bhanishi-at-Github,
thanks for reaching out!
Please note that we do not offer individual consulting by looking at the whole code of your solution. This is also not related to SP API but rather to your app setup. Therefore I will close this issue. Thank you four your understanding!
Best,
Marc
Selling Partner Developer Services
