### ISSUE TITLE
putListingsItem INVALID 属性「purchasable_offer」の列挙値「B2B」が無効です。

### ISSUE THREAD

**Issue by Hikigaya-github** [amzn/selling-partner-api-models#4175]
![image](https://github.com/user-attachments/assets/99358b9d-fca4-49cd-8a5c-ab41e405e80f)
This is the enumeration value of the audience attribute displayed in the response of DefinitionsApi. It does not seem to contain [B2B]. How should I use it?

**Comment by mafge** [comment]
Hi @Hikigaya-github,
thanks for reaching out!
Have you tried to use B2B as a value? Please also note that you have to be enrolled in the Amazon Business (B2B) program in order to create listings for business. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by Hikigaya-github** [comment]
Hi @mafge 
thank you very much for your reply!
I have not to be enrolled in the Amazon Business (B2B) program.I'll try using it again later.
Best,
Louis
