### ISSUE TITLE
GetAccount returning unauthorized 

### ISSUE THREAD

**Issue by iw-an** [amzn/selling-partner-api-models#4176]
I'm trying to use the new `getAccount` route at `/sellers/v1/account` but I'm hit with the error:
`Access to requested resource is denied.`

I can use the `/sellers/v1/marketplaceParticipations` route just fine in the same API and in the documentation and change log I see nothing mentioning extra permissions are required.

**Comment by mafge** [comment]
Hi @iw-an,
Please note that the [getAccount](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference#getaccount) operation is only available for Sandbox endpoints, and only in the EU marketplace (link to [docs](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v2024-07-14-use-case-guide#what-is-the-sellers-api)). Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by mafge** [comment]
@iw-an I see. Sorry for the inconveniences. I was able to reproduce the issue on my side. Let me check with the corresponding backend team!

**Comment by mafge** [comment]
@iw-an Once again sorry for the inconveniences. Backend team is working on a fix. I'll let you know as soon as it is working again!

**Comment by supoman-service** [comment]
I opened a case with the authorities a while ago, and they kept emphasizing that there was something wrong with my authorization or request. The Amazon team is really bad at doing their job. A very amateur group of people

**Comment by sarathZam** [comment]
This does not work

**Comment by sarathZam** [comment]
> Hi @iw-an, Please note that the [getAccount](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference#getaccount) operation is only available for Sandbox endpoints, and only in the EU marketplace (link to [docs](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v2024-07-14-use-case-guide#what-is-the-sellers-api)). Hope that helps! Best, Marc Selling Partner Developer Services

This Does not fix anything!!

**Comment by DmitryIordanov** [comment]
It's already 2025 and this endpoint still doesn't work!

**Comment by umairge66** [comment]
still same issue
