### ISSUE TITLE
Why /finances/v0/financialEvents has no FBALiquidationEventList data

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4177]
![image](https://github.com/user-attachments/assets/cde6aef3-bbd2-48af-9bce-58d7a20049c1)
https://user-images.githubusercontent.com/87471695/150062311-4e8b55c3-534e-4c48-a25a-e7a01fc6a784.png

**Comment by jawheral** [comment]
Hi @thesky2017,

Thanks for reaching out. I'm sorry that you are facing some issues with Finance API.
Can you elaborate more on the issue and explain the screenshot you provided and where is it from?
Did you make sure your postedDate (before and after) account for the transactions dates?

Best,
Jawher
Selling Partner API Solutions Architect
