### ISSUE TITLE
[BUG]  QuotaExceeded 

### ISSUE THREAD

**Issue by yukselaktepe** [amzn/selling-partner-api-models#418]
When I make a request to any endpoint in the notification api, I get a QuotaExceeded error.

I've been getting this error for 2 days.

{
  "errors": [
    {
      "code": "QuotaExceeded",
      "message": "You exceeded your quota for the requested resource.",
      "details": ""
    }
  ]
}

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
