### ISSUE TITLE
 /finances/v0/financialEvents 中ServiceFeeEventList 节点中费用没有时间 如何关联每一笔费用的时间？

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4182]
/finances/v0/financialEvents 中ServiceFeeEventList 节点中费用没有时间 如何关联每一笔费用的时间？

**Comment by jawheral** [comment]
Hi @thesky2017,

Thank you for the feedback.
Is there a particular reason you need to know the exact time associated with a ServiceFee transaction. You can for sure know that the service fee transaction is within a time interval which is the time between your `postedAfter` and `postedBefore` request parameters.

Best,
Jawher
Selling Partner API Solutions Architect

We will need to check this internally and I will get back to you once I have more information.

**Comment by thesky2017** [comment]
那新的api那些类型的数据加起来和日本站点账单pdf截图中这个字段的一样的呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月7日(周一) 下午3:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models]  /finances/v0/financialEvents 中ServiceFeeEventList 节点中费用没有时间 如何关联每一笔费用的时间？ (Issue #4182)




 
Hi @thesky2017,
 
Please check the newly released Finance API - version v2024-06-19. You can now list all transactions for a seller, each transaction returned with the corresponding postedDate field.
 
Nevertheless, I contacted our teams regarding the missing postedDate for ServiceFeeEvent on v0 and I will provide updates if available.
 
I hope this helps!
 
Best,
 Jawher
 Selling Partner API Solutions Architect

**Comment by thesky2017** [comment]
> version v2024-06-19
这个新的API 调用nextToken 报错了，请尽快处理下
