### ISSUE TITLE
Fulfillment Inbound 2024-03-20 Generate Transportation Options: Fail to execute COMPUTE_TRANSPORTATION_OPTIONS API with errors

### ISSUE THREAD

**Issue by brandondev1** [amzn/selling-partner-api-models#4184]
Seeing this randomly (happens sometimes, but subsequent identical plans will succeed) when executing GetInboundOpertationStatus after GenerateTransportationOptions.  

I submitted this issue previously, but it was closed for some reason as being "similar" to issue [4048 ](https://github.com/amzn/selling-partner-api-models/issues/4048 )even though that is a ConfirmTransportationOptions issue with a completely different error.

GenerateTransportationOptions
```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf5b422a1d-6a93-480a-876c-261f701ca50f/transportationOptions ",
    "method": "POST",,
    "body": {
        "placementOptionId": "pl758be03e-58f0-4d49-b093-ae36637ef346",
        "shipmentTransportationConfigurations": [
            {
                "readyToShipWindow": {
                    "start": "2024-09-23T00:00:00.000Z"
                },
                "shipmentId": "she7dc40c7-e8d5-4e34-a90c-8764e99cd96b",
                "contactInformation": {
                    "phoneNumber": "813-333-2233",
                    "email": "sam@email.com",
                    "name": "Sam Iam"
                },
                "pallets": [
                    {
                        "quantity": 1,
                        "stackability": "NON_STACKABLE",
                        "weight": {
                            "unit": "LB",
                            "value": 466
                        },
                        "dimensions": {
                            "unitOfMeasurement": "IN",
                            "length": 48,
                            "width": 40,
                            "height": 40
                        }
                    }
                ],
                "freightInformation": {
                    "freightClass": "FC_50",
                    "declaredValue": {
                        "code": "USD",
                        "amount": 1000
                    }
                }
            }
        ]
    }
}

RESPONSE:
{
  "operationId": "6d482cc5-52df-40d9-953a-c78634d61065"
}
```  
Subsequent request to GetInboundOperationStatus

```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/operations/6d482cc5-52df-40d9-953a-c78634d61065",
    "method": "GET",
}

RESPONSE:
{
  "operationStatus": "FAILED",
  "operationId": "64b29674-80b4-4064-ab13-bbd7019b45d1",
  "operation": "generateTransportationOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "BadRequest",
      "message": "ERROR: Fail to execute COMPUTE_TRANSPORTATION_OPTIONS API with errors."
    }
  ]
}

```

**Comment by amitvaghani** [comment]
I'm facing the same problem when I tried to confirmTransportationOptions
My response:

ERROR:
{
"operationStatus": "FAILED",
"operationId": "c954b3b8-afa7-44ca-8dcf-41dcb807a0d8",
"operation": "confirmTransportationOptions",
"operationProblems": [
{
"severity": "ERROR",
"code": "BadRequest",
"message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors."
}
]
}

Body Data:
{
"transportationSelections": [
{
"shipmentId": "sh5b7e755e-2f85-47f2-XXXX-XXXXXXXXXXXX",
"transportationOptionId": "toebc71138-8e68-XXXX-XXXX-XXXXXXXXXXXX",
"contactInformation": {
"name": "XXXXXXXX",
"phoneNumber": "XXXXXXXXXX",
"email": "XXXXXXXXXXXXXXXXX"
}
},
{
"shipmentId": "shd3b71197-c50d-4b3a-XXXX-XXXXXXXXXXXX",
"transportationOptionId": "toebc71138-8e68-XXXX-XXXX-XXXXXXXXXXXX",
"contactInformation": {
"name": "XXXXXXXX",
"phoneNumber": "XXXXXXXXXX",
"email": "XXXXXXXXXXXXXXXXX"
}
]
}

based on:

list_of_transportaion_option = {
"carrier": {
"name": "UPS",
"alphaCode": "UPSN"
},
"quote": {
"cost": {
"amount": 5.3,
"code": "USD"
}
},
"preconditions": [],
"shipmentId": "sh5b7e755e-2f85-XXXX-XXXX-XXXXXXXXXXXXX",
"shippingMode": "GROUND_SMALL_PARCEL",
"transportationOptionId": "toebc71138-8e68-XXXX-XXXX-XXXXXXXXXX",
"shippingSolution": "AMAZON_PARTNERED_CARRIER"
}

placement_option = {
"fees": [
{
"description": "Placement service fee represents service to inbound with minimal shipment splits and destinations of skus",
"type": "FEE",
"value": {
"amount": 0.49,
"code": "USD"
},
"target": "Placement Services"
}
],
"shipmentIds": [
"sh5b7e755e-2f85-XXXX-XXXX-XXXXXXXXXXX",
"shd3b71197-c50d-XXXX-XXXX-XXXXXXXXXXXX"
],
"discounts": [],
"expiration": "2024-10-03T06:48:14.748Z",
"placementOptionId": "pl60108e3d-45fc-XXXX-XXXX-XXXXXXXXXXXXX",
"status": "OFFERED"
}

How to solve?

**Comment by puppsupr** [comment]
Hi,

The left flow refers to pack first and right flow is pack later from the [use-case guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow).

Your order of operation was like so: SetPackingInformation -> GeneratePlacementOptions -> . . . -> generateTransportationOptions. This indicates that you were trying to inbound in the pack first scenario, but the workflow actually switched to pack later. See below for explanation.

Your SetPackingInformation request was unsuccessful. This was because you sent the request while the manifest was still in PENDING state. You've could've caught this by checking the response of the API before moving on to the next one.

Then during the generatePlacementOptions call, workflow is decided if its pack later or pack first. Since SetPackingInformation failed, [that meant CLI information was not correctly provided, and as a result this workflow was assigned as pack later].

Then when you tried to generateTransportationOptions, the request fails because when it is a requirement that confirmPlacementOptions must be called before generateTransportationOptions in the pack later scenario. Since this workflow was now a pack later workflow, and ConfirmPlacementOptions was not called, it resulted in an error. This error can be seen in the generateTransportationOptions response.

Going forward, I recommend you call the [getInboundOperationStatus](getInboundOperationStatus) after each post (async operation) to confirm the API completed successfully.

This is an expected behaviour.

Please check on the [sample solution code](https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/fulfillment-inbound) for the actual steps to call the workflows.

**Comment by brandondev1** [comment]
> Hi [brandondev1](https://github.com/brandondev1),
> 
> The left flow refers to pack first and right flow is pack later from the [use-case guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow).
> 
> Your order of operation was like so: SetPackingInformation -> GeneratePlacementOptions -> . . . -> generateTransportationOptions. This indicates that you were trying to inbound in the pack first scenario, but the workflow actually switched to pack later. See below for explanation.
> 
> Your SetPackingInformation request was unsuccessful. This was because you sent the request while the manifest was still in PENDING state. You've could've caught this by checking the response of the API before moving on to the next one.
> 
> Then during the generatePlacementOptions call, workflow is decided if its pack later or pack first. Since SetPackingInformation failed, [that meant CLI information was not correctly provided, and as a result this workflow was assigned as pack later].
> 
> Then when you tried to generateTransportationOptions, the request fails because when it is a requirement that confirmPlacementOptions must be called before generateTransportationOptions in the pack later scenario. Since this workflow was now a pack later workflow, and ConfirmPlacementOptions was not called, it resulted in an error. This error can be seen in the generateTransportationOptions response.
> 
> Going forward, I recommend you call the [getInboundOperationStatus](getInboundOperationStatus) after each post (async operation) to confirm the API completed successfully.
> 
> This is an expected behaviour.
> 
> Please check on the [sample solution code](https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/fulfillment-inbound) for the actual steps to call the workflows.

I'm not sure what you mean by "...the manifest was still in a PENDING state".  What manifest?

**Comment by brandondev1** [comment]
@puppsupr  - If you are referring to checking the status of ConfirmPackingOption before SetPackingInformation, I am doing that.  I check the status of every operation before proceeding to the next.  I GetInboundOperationStatus for ConfirmPackingOption until operationStatus = "SUCCESS", then I SetPackingInformation.  Even though ConfirmPackingOption succeeded, I execute GetInboundOperationStatus after SetPackingInformation and get:  
```
{
    "operationStatus": "FAILED",
    "operationId": "31b29a4e-dfaf-440b-b533-71a7afcf4df7",
    "operation": "setPackingInformation",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "BadRequest",
            "message": "ERROR: There are read-only or pending entity statuses [WorkflowStatusEntry{entityGroup=MANIFEST, status=PENDING}]"
        }
    ]
}

``` 
This issue is a month old and a complete blocking issue.

**Comment by puppsupr** [comment]
Hi,
Your SetPackingInformation request was unsuccessful. This was because you sent the request while the manifest was still in PENDING state. You've could've caught this by checking the response of the API before moving on to the next one.

Manifest here means the API System. You made a call to setPacking operation when the confirmPacking operation was still in progress.  Please try to create a new plan and let me know if you see same issue.

**Comment by brandondev1** [comment]
Did you read my post?  I did that and get the same result.  

Result of GetIInboundOperationStatus for ConfirmPackingOption
```
{
  "operationStatus": "SUCCESS",
  "operationId": "181a16a5-48a5-4f19-967b-6bc3b279f9e5",
  "operation": "confirmPackingOption",
  "operationProblems": []
}

```

Subsequently call SetPackingInformation followed by GetInboundOperationStatus:
```
{
    "operationStatus": "FAILED",
    "operationId": "f937c5a4-1395-44ba-8ecc-a3c84e9c8d8e",
    "operation": "setPackingInformation",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "BadRequest",
            "message": "ERROR: There are read-only or pending entity statuses [WorkflowStatusEntry{entityGroup=MANIFEST, status=PENDING}]"
        }
    ]
}

``

**Comment by brandondev1** [comment]
> What is the inbound plan ID for this new call ?

wf3974d7eb-21cc-44d0-9552-347333a2c4fd

**Comment by puppsupr** [comment]
Please provide full request and responses for createInboundPlan, generate, list, confirm placement and setPacking operations.

**Comment by johnkw** [comment]
We're seeing tons of errors like `"ERROR: Fail to execute COMPUTE_TRANSPORTATION_OPTIONS API with errors."` as well. The error message is so vague as to be completely useless, however retrying the original `POST /transportationOptions` call eventually succeeds.  It sometimes takes several tries though.

**Comment by brandondev1** [comment]
CreateInboundPlan
```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans",
    "method": "POST",
    "body": {
        "contactInformation": {
            "phoneNumber": "555-555-1234",
            "email": "sam@email.ccc",
            "name": "Same Iam"
        },
        "destinationMarketplaces": [
            "ATVPDKIKX0DER"
        ],
        "items": [
            {
                "prepOwner": "NONE",
                "msku": "16016101656",
                "labelOwner": "NONE",
                "quantity": 20
            }
        ],
        "sourceAddress": {
            "addressLine1": "1601 McCloskey Blvd",
            "city": "Tampa",
            "countryCode": "US",
            "name": "Sam Iam",
            "postalCode": "33605",
            "companyName": "AOCUSA",
            "stateOrProvinceCode": "FL",
            "phoneNumber": "555-555-1234"
        },
        "name": "Plan1"
    }
}

RESPONSE:
{
  "operationId": "06837ff2-1d3e-4343-b801-71fc9e62d9e1",
  "inboundPlanId": "wf2e0325b1-bd5e-424e-9f3b-0006395fdff9"
}
```
GeneratePackingOptions:
```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf2e0325b1-bd5e-424e-9f3b-0006395fdff9/packingOptions",
    "method": "POST"
}

RESPONSE:
{
  "operationId": "c2b43c75-e9f3-497f-adcf-87b18bbabeb5"
}
```

ListPackingOptions
```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf2e0325b1-bd5e-424e-9f3b-0006395fdff9/packingOptions",
    "method": "GET"
}

RESPONSE:
{
  "packingOptions": [
    {
      "packingGroups": [
        "pgbdc4e978-8f6a-40e2-a02c-9aff1ab147f6"
      ],
      "fees": [],
      "discounts": [],
      "packingOptionId": "po00000000-0000-0000-0000-000000000000",
      "supportedShippingConfigurations": [],
      "status": "ACCEPTED"
    }
  ],
  "pagination": {}
}
```

ConfirmPackingOption
```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf2e0325b1-bd5e-424e-9f3b-0006395fdff9/packingOptions/po00000000-0000-0000-0000-000000000000/confirmation",
    "method": "POST"
}

RESPONSE:
{
  "operationId": "f9f12d59-229b-4a30-a829-bb7b177c4942"
}
```

SetPackingInformation
```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf2e0325b1-bd5e-424e-9f3b-0006395fdff9/packingInformation",
    "method": "POST"
    "body": {
        "packageGroupings": [
            {
                "boxes": [
                    {
                        "contentInformationSource": "BARCODE_2D",
                        "dimensions": {
                            "height": "9.13",
                            "length": "13.25",
                            "unitOfMeasurement": "IN",
                            "width": "9.75"
                        },
                        "quantity": "20",
                        "templateName": "SS",
                        "weight": {
                            "unit": "LB",
                            "value": "24.5"
                        }
                    }
                ],
                "packingGroupId": "pgbdc4e978-8f6a-40e2-a02c-9aff1ab147f6"
            }
        ]
    }
}

RESPONSE:
{
  "operationId": "d9bd7fb8-0d0c-428a-8808-9f794593cb87"
}
```

**Comment by johnkw** [comment]
These calls fail more often than they succeed, roughly 55.2% of the time.  We also get lots of `[{'severity': 'ERROR', 'code': 'InternalServerError', 'message': 'ERROR: Something went wrong. Please try again later.'}]` but if you just retry over and over with the same exact inputs it eventually works.
