### ISSUE TITLE
Return Authorization Third Party Processing

### ISSUE THREAD

**Issue by iaars** [amzn/selling-partner-api-models#4185]
I have found the Return Report `GET_XML_RETURNS_DATA_BY_RETURN_DATE` to get the information on the returns, but I didn't find a way to send it back and trigger a refund for a specific RMA. Is there an endpoint that I can use to trigger the refund/return authorization based on the information from that report?

**Comment by mafge** [comment]
Hi @iaars,
thanks for reaching out!
You can use the [order adjustment feed](https://developer-docs.amazon.com/sp-api/docs/order-feed-type-values#flat-file-order-adjustments-feed) to issue a refund. You can find a tutorial on how to do this in the [documentation](https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide#flat-file-order-adjustments-feed). Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by iaars** [comment]
Thanks @mafge

**Comment by iaars** [comment]
@mafge I have a question after reviewing the docs. 

- I noticed this feed uses some fields from an `OrderReport`.  Would it be better to use one of those reports to retrieve the data from the RMAs? If that is the case, which one would be recommended? Otherwise, should I use the `GET_XML_RETURNS_DATA_BY_RETURN_DATE` in conjunction with one of the `OrderReport`?

Thanks!
