### ISSUE TITLE
getItemOffers with CustomerType=Business return wrong data comparing to amazon.com

### ISSUE THREAD

**Issue by qaisarikram** [amzn/selling-partner-api-models#4186]
We are using the getItemOffer api, the complete end point is given below:
_https://sellingpartnerapi-na.amazon.com/products/pricing/v0/items/B06XSQTS1R/offers?MarketplaceId=ATVPDKIKX0DER&ItemCondition=New&CustomerType=Business_

We are facing a serious issue with info in BuyBox Array, given by the api.
**In BuyBox array, we have data that is not matching to amazon.**

For instance, in Amazon.com, we are seeing the **B2B Feature price $363.62** (screenshot is attached)
![image](https://github.com/user-attachments/assets/d8d60ed8-b203-47c8-9e43-8f5fc00a559b)

But in the api, we are getting **B2B Feature price $377.00** (screenshot is attached)
![image](https://github.com/user-attachments/assets/51e60305-d2ff-4b02-a462-632f8ffc38fb)

This mismatching info is causing a serious problem for us.
can you please help in this regard?

Thank You

**Comment by mafge** [comment]
Hi @qaisarikram,
thanks for reaching out!
I was able to reproduce your issue on my side. The price you are seeing for buy box price with quantity tier of 1 is actually the B2C (consumer) offer. Let me follow up with the backend team to clarify this.
Best,
Marc
Selling Partner Developer Services
