### ISSUE TITLE
Amazon SP-API - How to set up SPD options for FBA inbound

### ISSUE THREAD

**Issue by gu-te** [amzn/selling-partner-api-models#4189]
We have developed for the newest version of the SP API (Fulfillment Inbound API v2024-03-20).

After confirming the placement option, the shipping method is set to LTL by default. How to set it to SPD?

Thanks in advance!

**Comment by gu-te** [comment]
The process for creating a shipment when the carton-level information is not known upfront is only available for LTL shipments at this time.

**Comment by B3lg4r4th** [comment]
Are there any plans to fix this state of the matter before the December deadline? We won't be able to ship otherwise

**Comment by collery** [comment]
> 

hello ,  did you fix this issus ?
