### ISSUE TITLE
Issue with Expired Placement Option - Fulfillment Inbound API v2024-03-20

### ISSUE THREAD

**Issue by Alvaromero** [amzn/selling-partner-api-models#4194]
Hi everyone, 

We are facing an issue when processing shipment plans where box-level information is not provided in advance.

The process is as follows: when creating the inbound plan, we select a placement option from the list provided by the API. These options come with an expiration attribute of 72 hours.

After selecting the placement, we begin the process of product picking, packing, and labeling, which can take longer than 72 hours.

When we try to execute the `setPackingInformation` method to subsequently generate the `transportation options`, we receive the following error:

`“Operation cannot be processed because the requested placement option is expired.”`

Additionally, it is not possible to generate a new placement as we receive the following message:

`“Operation GeneratePlacementOptions cannot be processed because a placement option is already confirmed.”`

**Request for Guidance:**

Could you please advise us on how we can avoid this issue for future shipment plans? Is there any documentation that explains why the placement option expires after 72 hours and how to manage this process when the packing takes longer?

We appreciate your assistance and look forward to your guidance.

**Comment by puppsupr** [comment]
Hi [Alvaromero](https://github.com/Alvaromero),
Which flow are you using ? Is it the right hand flow or left hand on the [use-case guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow) ?

**Comment by Alvaromero** [comment]
pack later flow

**Comment by MeenaAmz** [comment]
Every placement option comes with an expiration data for that option. It will not be fixed at 72 hours. When a placement option expires, you can regenerate placement options by calling generatePlacementOption. Have you tried that? Also I would like to understand why you confirm the placement prior to picking product, packing etc. Is there a specific reason for that?

Thanks 
Meena
Selling Partner Developer Services

**Comment by Alvaromero** [comment]
Hi @MeenaAmz,

Thank you for your response.

We are using the "pack later" flow because we do not have the box information available upfront; our suppliers ship products in boxes that do not meet Amazon's specifications, so we need to repack all these products. Due to space limitations in our warehouse, we have chosen to use the "pack later" flow (as illustrated on the right side of the diagram), which allows us to confirm placement before packing.

Once we confirm the placement and obtain the shipmentConfirmationId, we begin the process of packing and palletizing the products. However, since some of our shipments contain thousands of products, this process can sometimes take more than 72 hours.

As you suggested, we attempted to regenerate placement options after the original placement expired, but since the placement was already confirmed, we encountered the following error:

“Operation GeneratePlacementOptions cannot be processed because a placement option is already confirmed.”

Given that this flow requires us to confirm placement early in the process, is there a recommended way to handle expired placements or a method to reset the confirmed placement when it expires before packing is complete?

We would appreciate any guidance on how to manage this situation to avoid future issues.

Best regards,
![image](https://github.com/user-attachments/assets/c71703ec-5c4a-48ef-be35-022ba3495a34)

**Comment by puppsupr** [comment]
Hi,
Unfortunately, there is no work around for the 72hrs time frame. The placement options for your workflow are valid for only 72 hours pending shipment confirmation. If you leave the workflow and return more than 72 hours later, the fulfillment center placement options are invalid and when a placement option expires, you must regenerate placement options by calling generatePlacementOption. But we have taken your feedback into account.
