### ISSUE TITLE
When confirming DeliveryWindowOptions, it said Delivery window options are expired, please regenerate.

### ISSUE THREAD

**Issue by asd6979448** [amzn/selling-partner-api-models#4199]
The last time I generated Delivery Window Options was in July. For various reasons, I did not call listDeliveryWindowOptions to obtain delivery_window_option_id to confirm the Delivery Window Options. Now this problem occurs again when I call listDeliveryWindowOptions to obtain delivery_window_option_id to confirm the Delivery Window Options. What should I do?

**Comment by asd6979448** [comment]
I re-requested generateDeliveryWindowOptions to generate new data according to the prompt, and found that the data was still the original one.

**Comment by puppsupr** [comment]
Hi [asd6979448](https://github.com/asd6979448),
All the list operations will have an "expiration":"yyyy-mm-ddT00:00:00.00Z" date. Once this is past and you don't confirm, you need to call the generate operations again then do the list to view the list.
