### ISSUE TITLE
[C# SwaggerGen] Url parameters are not replaced before signing the request.

### ISSUE THREAD

**Issue by xavierhd** [amzn/selling-partner-api-models#42]
# Swagger generated APIs which requires URL parameters are failling authentication.
I'll use this exemple to explain: 
```cs
string marketPlaceId = "ATVPDKIKX0DER";
string itemCondition = "New";
string asin = "B08KGT79CH";
ProductPricingApi api = new ProductPricingApi(configuration);
api.GetItemOffers(marketPlaceId, itemCondition, asin);
```
In this exemple, RestSharp use `/products/pricing/v0/items/{asin}/offers` to request `/products/pricing/v0/items/B08KGT79CH/offers`.

## Cause : 
AWSSigV4Signer use the property `RestRequest.Resource` to build the canonical request. The value returned by `RestRequest.Resource` is not calculated. Therefore, `{asin}` is embeded in the canonical request string instead of `B08KGT79CH`.
Exemple of produced bad canonical request: 
```
GET
/products/pricing/v0/items/%257BAsin%257D/offers
ItemCondition=New&MarketplaceId=ATVPDKIKX0DER
accept:application/json
host:sellingpartnerapi-na.amazon.com
x-amz-access-token:Atza|[access-token]
x-amz-date:20201218T010030Z
x-amz-security-token:[security-token]
```
Note that `%257BAsin%257D` is the value `{Asin}` which has been URI encoded.
The request is still made correctly by RestClient.Execute to https://sellingpartnerapi-na.amazon.com/products/pricing/v0/items/B08KGT79CH/offers, but the authentication fail because of the wrong canonical request string.

Furthermore, RestSharp source code show that nothing is done to the value of `Resource` until `RestClient.Execute` is called : https://github.com/restsharp/RestSharp/blob/e3280ab99f09aa080f5c49ea97bcaf28201a2050/src/RestSharp/RestClient.cs#L293

**Comment by stephenfung** [comment]
Thanks @xavierhd, I ran into this as well and your clearly written issue helped.  I made some changes to the swagger templates that seemed to work for me and hopefully will help you and/or others!  (See pull request above.)

**Comment by smithburger** [comment]
> Thanks @xavierhd, I ran into this as well and your clearly written issue helped. I made some changes to the swagger templates that seemed to work for me and hopefully will help you and/or others! (See pull request above.)

I don't know how to use swagger. I am using the models provided in this github and they are working great but I am running into this same issue. I am having to (+) concatenate the resource string to get these calls to work. 

When you generate the sdk with swagger is it giving you the classes or is it generating a library for you? I was hoping to get the class with this fix applied so I can use it in my solution. If it generates a complete dll library I guess I would need to learn swagger.

Follow up would your fix also let us use .AddJsonBody instead of needing to serialize and add as a normal parameter? Ran into that web submitting inventory changes.

**Comment by 38popugaev** [comment]
It looks like a bug in Amazon.SellingPartnerAPIAA.AWSSignerHelper.ExtractCanonicalURIParameters ([https://github.com/amzn/selling-partner-api-models/blob/main/clients/sellingpartner-api-aa-csharp/src/Amazon.SellingPartnerAPIAA/AWSSignerHelper.cs](url)) for me. It doesn't replace UrlSegment parameters in the request resource string.

**Comment by heitke** [comment]
I should have looked a little closer before creating my own PR for this!  But I think this is a slightly better way to fix this: https://github.com/amzn/selling-partner-api-models/pull/93

**Comment by diegocvazquez** [comment]
@parvathm 
This is a bug, using the generated code at least in c# I cannot call any endpoint having parameters in the URL

**Comment by parvathm** [comment]
Hi All,

Thank you for your feedback. I will work on this issue and update if there is any fix needed. 

Thanks,
Parvathm,
Selling Partner API Developer Support.

**Comment by codingkondi** [comment]
@parvathm  please tell us your correct url enocode rule

**Comment by michaellavoie** [comment]
While we wait for an official fix, I was able to resolve the bug by running this find-replace on the generated swagger output:
Find: `var localVarPath = "`
Replace: `var localVarPath = $"`

**Comment by tecorraltd** [comment]
@michaellavoie legend. thanks a lot. This also highlighted several invalid variable names (case wrong) which seem to be fixed in a pending PR

**Comment by codingkondi** [comment]
> Hi All,
> 
> Thank you for your feedback. I will work on this issue and update if there is any fix needed.
> 
> Thanks,
> Parvathm,
> Selling Partner API Developer Support.

well, this issue was been fixed? and could you tell us correct encoding code rule? ex: "seller 001" => "seller%20001"

**Comment by wisdomleo** [comment]
> While we wait for an official fix, I was able to resolve the bug by running this find-replace on the generated swagger output: Find: `var localVarPath = "` Replace: `var localVarPath = $"`

Thanks very much!!! The perfect solution to my problem!!!

**Comment by parvathm** [comment]
Hi,

We have provided a fix to  signature mismatch for resource path with UrlSegment  in our recent commit.
Please let us know if you still have any issues,

Thanks,
Parvathm
Selling Partner Developer Support.
