### ISSUE TITLE
"Invalid request during APS call!. "[sic] for putTransportDetails

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#420]
The complete error message is:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request during APS call!. ",
      "details": ""
    }
  ]
}
```

In my particular case the issue was due to `"TransportDetails": {"PartneredLtlData": { "Phone": "..." ...` where the `Phone` text was 22 characters long which apparently exceeds the limit.

The limit is documented in https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#contact and that part may be correct.  Not documented however, is the ridiculous and nonsensical error message.  I can't come up with a guess as to what "APS" might stand for, and the bizarre punctuation is pasted here as-is.

The error message for such a situation could be documented, however really it should just be fixed to make sense, and require no further documentation, such as:
`TransportDetails.PartneredLtlData.Phone exceeds length limit of 20 characters.`

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
