### ISSUE TITLE
How to obtain vendor SKUs in bulk

### ISSUE THREAD

**Issue by frankHHHHHHH** [amzn/selling-partner-api-models#4201]
I did not find any reports to obtain vendor SKUs
I can't get the SKU through the interface searchCatalogItems

**Comment by mafge** [comment]
Hi @frankHHHHHHH,
thanks for reaching out!
I can suggest the following two resources to look into:
- [Vendor Inventory Report](https://developer-docs.amazon.com/sp-api/docs/report-type-values-analytics#vendor-inventory-report)
- Data Kiosk Vendor Analytics: [Use Case Guide ](https://developer-docs.amazon.com/sp-api/docs/vendor-analytics-dataset-guide) and [Schema Explorer](https://sellercentral.amazon.com/datakiosk-schema-explorer?schema=analytics_vendorAnalytics_2024_09_30) to check available attributes.
Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by Ananauze** [comment]
Hi Frank. I've been trying to solve this problem for several days now. You realy can use GET_VENDOR_INVENTORY_REPORT to recieve all your ASINs. But that's all. We are Vendors too, we cant use GET_MERCHANT_LISTINGS_DATA or somthing like that. Only Vendors reports. After that I try "catalog/2022-04-01/items/{asin}" with 'includedData' : 'identifiers', but only EAN.
