### ISSUE TITLE
[V0 Inbound Api] GetShipments does not work

### ISSUE THREAD

**Issue by emakunin** [amzn/selling-partner-api-models#4205]
Hello,

I'm trying to retrieve all inbound shipments using v0 API (cause the new one doesn't have it ant the `getshipments` api is not deprecated).

The problem is that itegation with `NextToken` simply doesn't work no matter what I pass/skip in the first/next request.

Example
```
https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments?QueryType=SHIPMENT&MarketplaceId=ATVPDKIKX0DER&ShipmentStatusList=SHIPPED,RECEIVING,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN
```
Reply
```
...
    "NextToken": "AAAAAAAAAABB5bGSDcfFsu/27ezMLRZNlwEAAAAAAAA6j+FKehv1pMqGL1aMOD92BSRooiQX5H3VU/b2WfXRlsLAM1pI0Fjggc/ptBik6mxdGm8kfl4p/smEdaL+wjWFUTJVCvzOv3lALklsNDwe5hRdXVkCtYZtLOvwL2Yti7GJx/R78HKhikzaj+u7DdC1ah5jnP+j4GDr097CK++bpXtcp7KBtB99kZjdAhTpvyi/gPfxyEn9p1RZluFaDnE0YRUbpFeoV2/fEBQK0MayEFIdNE8V5Jt2S8lbVyAibTonp8TmJywK0TNS3Wv+O/M71E+D9wAhiheoqii3ckAt7sEMloM1jXuDTNXqbubQSBrWX8kEIp+guBTauYKezIa66ySpp8XkgXIE3QjdReEBKafARxZD+6ZQoUbIDpSRvBSMFPWliVsYILzmQczRmK3jlQq98iZbPZwU+f00c7bqvu5fSuhnBmYGrFCvJkC2jO6samkr0Me4Y3T83g7NBral7+dfiOhxFPGtEDy5QcwE8/Hnmrfw6Oebwf3BSMzHDQqUZ9aDUYH+LlWjlVpnF1dlcktXiaLuOg=="
```
Now trying the pagination as per documentation
```
https://sellingpartnerapi-na.amazon.com/fba/inbound/v0/shipments?queryType=NEXT_TOKEN&marketplaceId=ATVPDKIKX0DER&NextToken=AAAAAAAAAABB5bGSDcfFsu/27ezMLRZNlwEAAAAAAAA6j+FKehv1pMqGL1aMOD92BSRooiQX5H3VU/b2WfXRlsLAM1pI0Fjggc/ptBik6mxdGm8kfl4p/smEdaL+wjWFUTJVCvzOv3lALklsNDwe5hRdXVkCtYZtLOvwL2Yti7GJx/R78HKhikzaj+u7DdC1ah5jnP+j4GDr097CK++bpXtcp7KBtB99kZjdAhTpvyi/gPfxyEn9p1RZluFaDnE0YRUbpFeoV2/fEBQK0MayEFIdNE8V5Jt2S8lbVyAibTonp8TmJywK0TNS3Wv+O/M71E+D9wAhiheoqii3ckAt7sEMloM1jXuDTNXqbubQSBrWX8kEIp+guBTauYKezIa66ySpp8XkgXIE3QjdReEBKafARxZD+6ZQoUbIDpSRvBSMFPWliVsYILzmQczRmK3jlQq98iZbPZwU+f00c7bqvu5fSuhnBmYGrFCvJkC2jO6samkr0Me4Y3T83g7NBral7+dfiOhxFPGtEDy5QcwE8/Hnmrfw6Oebwf3BSMzHDQqUZ9aDUYH+LlWjlVpnF1dlcktXiaLuOg==
```

I get
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}
```

I tried adding/skipping the MpID/statuses/other params. Tried different combinations of the `QueryType`. But The result is always the same.

**Comment by emakunin** [comment]
the problem seems to be with how I called the api. I managed to iterate.

1. Hidden spaces once copy/paste quary params. In this params pagination simply returns same data without any error.
2. Missing URL endocing -> lead to InvalidInput. The token contains non-url characters. The client I use did not encode automatically.

**Comment by puppsupr** [comment]
Hi,
You can use [listInboundPlans](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#paths) to view all your inbound plans. 

Refer to this [Postman collection](https://www.postman.com/galactic-rocket-691225/selling-partner-api-for-fulfillment-inbound-fba-v2024/overview) to view all the required api operations for each flow. You can also refer to this [sample code solution](https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/fulfillment-inbound).
