### ISSUE TITLE
Issue in ConfirmTransportationOption.

### ISSUE THREAD

**Issue by amitvaghani** [amzn/selling-partner-api-models#4206]
Hello, 

I have a problem when trying to confirm transportation options SP-API.

ERROR:
{
    "operationStatus": "FAILED",
    "operationId": "c954b3b8-afa7-44ca-8dcf-41dcb807a0d8",
    "operation": "confirmTransportationOptions",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "BadRequest",
            "message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors."
        }
    ]
}

Body Data: 
{
  "transportationSelections": [
    {
      "shipmentId": "sh5b7e755e-2f85-47f2-XXXX-XXXXXXXXXXXX",
      "transportationOptionId": "toebc71138-8e68-XXXX-XXXX-XXXXXXXXXXXX",
      "contactInformation": {
        "name": "XXXXXXXX",
        "phoneNumber": "XXXXXXXXXX",
        "email": "XXXXXXXXXXXXXXXXX"
      }
    },
    {
      "shipmentId": "shd3b71197-c50d-4b3a-XXXX-XXXXXXXXXXXX",
      "transportationOptionId": "toebc71138-8e68-XXXX-XXXX-XXXXXXXXXXXX",
      "contactInformation": {
        "name": "XXXXXXXX",
        "phoneNumber": "XXXXXXXXXX",
        "email": "XXXXXXXXXXXXXXXXX"
      }
  ]
}

based on:

list_of_transportaion_option = {
    "carrier": {
    "name": "UPS",
    "alphaCode": "UPSN"
    },
    "quote": {
     "cost": {
            "amount": 5.3,
             "code": "USD"
             }
            },
      "preconditions": [],
      "shipmentId": "sh5b7e755e-2f85-XXXX-XXXX-XXXXXXXXXXXXX",
      "shippingMode": "GROUND_SMALL_PARCEL",
      "transportationOptionId": "toebc71138-8e68-XXXX-XXXX-XXXXXXXXXX",
       "shippingSolution": "AMAZON_PARTNERED_CARRIER"
}

placement_option = {
    "fees": [
      {
         "description": "Placement service fee represents service to inbound with minimal shipment splits and destinations of skus",
          "type": "FEE",
          "value": {
                "amount": 0.49,
                "code": "USD"
           },
           "target": "Placement Services"
       }
    ],
    "shipmentIds": [
        "sh5b7e755e-2f85-XXXX-XXXX-XXXXXXXXXXX",
         "shd3b71197-c50d-XXXX-XXXX-XXXXXXXXXXXX"
     ],
     "discounts": [],
      "expiration": "2024-10-03T06:48:14.748Z",
      "placementOptionId": "pl60108e3d-45fc-XXXX-XXXX-XXXXXXXXXXXXX",
       "status": "OFFERED"
}

How to solve?

**Comment by jlevers** [comment]
@amitvaghani what was the solution to this problem?

**Comment by johnkw** [comment]
See also bug #4253 which notes the only current workaround is delete everything and retry.
