### ISSUE TITLE
create a shipment to AWD with API

### ISSUE THREAD

**Issue by mschwartz19** [amzn/selling-partner-api-models#4213]
Is there a way to create a shipment to AWD with API?

**Comment by mafge** [comment]
Hi @mschwartz19,
thanks for reaching out!
Currently there is no possibility to create shipments to AWD. However there is a new Shipment Creation API in beta stage tested internally, so this could change in the future (no ETA yet). Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by weilinggu** [comment]
@mschwartz19 +1 to what Marc said.
In addition, as soon as the feature is implemented, we will post an announcement in the Announcements Section (https://developer-docs.amazon.com/sp-api/changelog) of our documentation site.
You can also review our Release Notes (https://developer-docs.amazon.com/sp-api/page/release-notes) regarding all changes made to our APIs and subscribe to our RSS feed (https://developer-docs.amazon.com/sp-api/changelog.rss) to get notified as soon as there is an update.

Weiling
Selling Partner Developer Services
