### ISSUE TITLE
When I created FBA, the following error message appeared when calling createInboundPlan

### ISSUE THREAD

**Issue by asd6979448** [amzn/selling-partner-api-models#4217]
reason:class OperationProblem { code: InternalServerError details: null message: ERROR: Something went wrong. Please try again later. severity: ERROR }
There were no problems before, are you making any adjustments now?

**Comment by puppsupr** [comment]
Hi,
In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.
