### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 generatePlacementOptions Consistently Failing

### ISSUE THREAD

**Issue by konoplev-roman** [amzn/selling-partner-api-models#4219]
The generatePlacementOptions operation of the Fulfillment Inbound API v2024-03-20 is consistently failing. Upon checking the status of the operation after the initial request, an error is returned. Subsequently, the listPlacementOptions request returns empty data.

generatePlacementOptions status check response:
```json
{
  "operationStatus": "FAILED",
  "operationId": "69473284-6f1c-45ce-9460-2d1b32d965f9",
  "operation": "generatePlacementOptions",
  "operationProblems": [
    {
      "severity": "ERROR",
      "code": "InternalServerError",
      "message": "ERROR: Something went wrong. Please try again later."
    }
  ]
}
```

listPlacementOptions response:
```json
{ "pagination": {}, "placementOptions": [] }
```

**Comment by puppsupr** [comment]
Hello [konoplev-roman](https://github.com/konoplev-roman),
In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.
