### ISSUE TITLE
https://sellingpartnerapi-fe.amazon.com/finances/2024-06-19/transactions  用nextToken请求报错

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4220]
请问 这个报错是什么原因   InternalFailure:We encountered an internal error. Please try again.:(RequestID:dee6af9a-a688-4a9b-b459-44145752abdd，必现。

**Comment by a344241086** [comment]
网友说是NextToken  不是nextToken  试试呢

**Comment by julioyildo** [comment]
> 网友说是NextToken 不是nextToken 试试呢

Hi,

I have tried yes this is working: 

```
{
            'postedAfter': '...',
            'postedBefore': '...',
            'marketplaceId': '...',
            'NexToken': '...'

        }
```

Use PascalCase for next token name.

**Comment by weilinggu** [comment]
@thesky2017,
提交时你是否有填入原先的request parameters？如果没有，请确保你在提交时所有参数都提供了。
如果还是没有解决问题，可以考虑开一个support case(https://developer.amazonservices.com/support)。
Thanks,
Weiling Gu
Selling Partner API Developer Services

**Comment by thesky2017** [comment]
是nexToken ，但是还是报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] https://sellingpartnerapi-fe.amazon.com/finances/2024-06-19/transactions  用nextToken请求报错 (Issue #4220)




  
网友说是NextToken 不是nextToken 试试呢
  
Hi,
 
I have tried and yes this is working:
 {             'postedAfter': '...',             'postedBefore': '...',             'marketplaceId': '...',             'NexToken': '...'         }  
Use PascalCase for next token name.

**Comment by thesky2017** [comment]
还是报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] https://sellingpartnerapi-fe.amazon.com/finances/2024-06-19/transactions  用nextToken请求报错 (Issue #4220)




  
网友说是NextToken 不是nextToken 试试呢
  
Hi,
 
I have tried and yes this is working:
 {             'postedAfter': '...',             'postedBefore': '...',             'marketplaceId': '...',             'NexToken': '...'         }  
Use PascalCase for next token name.

**Comment by thesky2017** [comment]
传入了原来的参数，还是报错



---原始邮件---
发件人: "Weiling ***@***.***&gt;
发送时间: 2024年10月11日(周五) 晚上11:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] https://sellingpartnerapi-fe.amazon.com/finances/2024-06-19/transactions  用nextToken请求报错 (Issue #4220)




 
@thesky2017,
 提交时你是否有填入原先的request parameters？如果没有，请确保你在提交时所有参数都提供了。
 如果还是没有解决问题，可以考虑开一个support case(https://developer.amazonservices.com/support)。
 Thanks,
 Weiling Gu
 Selling Partner API Developer Services

**Comment by weilinggu** [comment]
@thesky2017 我们正在修复这个问题，一旦有进展了会在这里通知你
Thanks,
Weiling Gu
Selling Partner API Developer Services

**Comment by weilinggu** [comment]
@thesky2017 问题应该已经修复. 你可以用nextToken来获取下一页。

Thanks,
Weiling Gu
Selling Partner API Developer Services

**Comment by thesky2017** [comment]
Array
(
    [sellingPartnerMetadata] => Array
        (
            [sellingPartnerId] => A3RUABD8BOQE9N
            [marketplaceId] => A1VC38T7YXB528
            [accountType] => Standard Orders
        )

    [transactionType] => ServiceFee
    [transactionId] => hbRTHEQNx5op6g0EA0znvXFhb-W9ILSxE5f6hiG-bXc
    [transactionStatus] => Released
    [relatedIdentifiers] => Array
        (
            [0] => Array
                (
                    [relatedIdentifierName] => FINANCIAL_EVENT_GROUP_ID
                    [relatedIdentifierValue] => vHbo_91F4UPm6kfL-nexWB0g6vqG0b3OG9oE7jWfP8A
                )

        )

    [totalAmount] => Array
        (
            [currencyAmount] => -12609
            [currencyCode] => JPY
        )

    [description] => FBAStorageBilling
    [postedDate] => 2024-09-07T13:38:59Z
    [marketplaceDetails] => Array
        (
            [marketplaceId] => A1VC38T7YXB528
            [marketplaceName] => Amazon.co.jp
        )

    [items] => Array
        (
            [0] => Array
                (
                    [description] => 
                    [totalAmount] => Array
                        (
                            [currencyAmount] => -618
                            [currencyCode] => JPY
                        )

                    [relatedIdentifiers] => Array
                        (
                            [0] => Array
                                (
                                    [itemRelatedIdentifierName] => TRANSACTION_ID
                                    [itemRelatedIdentifierValue] => 11324341539
                                )

                        )

                    [breakdowns] => Array
                        (
                            [0] => Array
                                (
                                    [breakdownType] => AmazonFees
                                    [breakdownAmount] => Array
                                        (
                                            [currencyAmount] => -618
                                            [currencyCode] => JPY
                                        )

                                    [breakdowns] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [breakdownType] => FBAStorageFee
                                                    [breakdownAmount] => Array
                                                        (
                                                            [currencyAmount] => -618
                                                            [currencyCode] => JPY
                                                        )

                                                    [breakdowns] => Array
                                                        (
                                                            [0] => Array
                                                                (
                                                                    [breakdownType] => Base
                                                                    [breakdownAmount] => Array
                                                                        (
                                                                            [currencyAmount] => -562
                                                                            [currencyCode] => JPY
                                                                        )

                                                                )

                                                            [1] => Array
                                                                (
                                                                    [breakdownType] => Tax
                                                                    [breakdownAmount] => Array
                                                                        (
                                                                            [currencyAmount] => -56
                                                                            [currencyCode] => JPY
                                                                        )

                                                                )

                                                        )

                                                )

                                        )

                                )

                        )

                    [contexts] => Array
                        (
                            [0] => Array
                                (
                                    [asin] => 
                                    [quantityShipped] => 0
                                    [sku] => 
                                    [fulfillmentNetwork] => 
                                    [contextType] => ProductContext
                                )

                        )

                )

        )

    [breakdowns] => Array
        (
            [0] => Array
                (
                    [breakdownType] => Sales
                    [breakdownAmount] => Array
                        (
                            [currencyAmount] => 0
                            [currencyCode] => JPY
                        )

                    [breakdowns] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [breakdownType] => Expenses
                    [breakdownAmount] => Array
                        (
                            [currencyAmount] => -12609
                            [currencyCode] => JPY
                        )

                    [breakdowns] => Array
                        (
                            [0] => Array
                                (
                                    [breakdownType] => StorageBillingFee
                                    [breakdownAmount] => Array
                                        (
                                            [currencyAmount] => -12609
                                            [currencyCode] => JPY
                                        )

                                    [breakdowns] => 
                                )

                        )

                )

        )

    [contexts] => 
)
这个items节点金额和breakdowns 仓储费  金额加起来怎么不一样？？

**Comment by jawheral** [comment]
Hi @thesky2017,

Thank you for providing feedback.
Is the `nextToken` issue fixed for you now?

Regarding the items vs breakdown issue, I made our teams aware and will investigate this. I will reach out if I receive any updates.

Best,
Jawher
Selling Partner Developer Services

**Comment by thesky2017** [comment]
已经好了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月17日(周四) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] https://sellingpartnerapi-fe.amazon.com/finances/2024-06-19/transactions  用nextToken请求报错 (Issue #4220)




 
Hi @thesky2017,
 
Thank you for providing feedback.
 Is the nextToken issue fixed for you now?
 
Regarding the items vs breakdown issue, I made our teams aware and will investigate this. I will reach out if I receive any updates.
 
Best,
 Jawher
 Selling Partner Developer Services

**Comment by jawheral** [comment]
Thanks for confirming @thesky2017. 
Closing this now!
