### ISSUE TITLE
List a new product is very slow to be active, error "Missing Offer"

### ISSUE THREAD

**Issue by hamduc7** [amzn/selling-partner-api-models#4221]
Hi Developer,

When we list a product using JSON_LISTING_FEED, it is extremely slow to be 'discoverable' and is tucked at 'Missing Offer' for very long—about 45 minutes or more.

Is there a way to make the SKU is discoverable after the Feed status is DONE?

@mafge 

Thank you

**Comment by mafge** [comment]
Hi @hamduc7,
thanks for reaching out!
The listing process is usually a two step approach. There is a synchronous processing whenever you create a new listing via the feed, followed by an asynchronous processing afterwards. The feed status is set to `DONE` when the synchronous part is finished and the submission has been accepted by the backend for further processing - this does not mean that the listing is already fully processed and online. Only until the asynchronous validation is finished, the listing will be visible on the website and correctly displayed in Seller Central. Unfortunately this may take a while, depending on the overall load of the system - we have to process a ton of submissions at any time!
Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by hamduc7** [comment]
Thanks @mafge
