### ISSUE TITLE
requested order report createReport  ,The resource request was rejected

### ISSUE THREAD

**Issue by asd6979448** [amzn/selling-partner-api-models#4222]
and the message "Access to the resource is forbidden" 
 has no problem with my account, because I previously requested GET /reports/2021-06-30/reports and it was successful.

**Comment by mafge** [comment]
HI @asd6979448,
thanks for reaching out!
With the given information it is hard to give any advice. Can you please provide further information  - which report do you request and have you requested the same report successfully before?
In general my recommendation is to check the following things:
- Do you have all the required roles to request a specific report (you can find the required roles for each report in the documentation)?
- Are your credentials valid?
- Do you use the correct marketplace id in the `createReport` operation?
- Are there any limits mentioned in the doc on how often a report can be requested?
Best,
Marc
Selling Partner Developer Services

**Comment by asd6979448** [comment]
> HI @asd6979448, thanks for reaching out! With the given information it is hard to give any advice. Can you please provide further information - which report do you request and have you requested the same report successfully before? In general my recommendation is to check the following things:
> 
> * Do you have all the required roles to request a specific report (you can find the required roles for each report in the documentation)?
> * Are your credentials valid?
> * Do you use the correct marketplace id in the `createReport` operation?
> * Are there any limits mentioned in the doc on how often a report can be requested?
>   Best,
>   Marc
>   Selling Partner Developer Services

The request for the report GET_FBA_MYI_ALL_INVENTORY_DATA is successful, but the following requests GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING, GET_ORDER_REPORT_DATA_INVOICING, GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE, etc. are all denied access.

**Comment by mafge** [comment]
@asd6979448  Have you checked that you have all the required roles? E.g. `GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING` needs other roles then `GET_FBA_MYI_ALL_INVENTORY_DATA`.

**Comment by mafge** [comment]
@asd6979448 Also some of the reports you are mentioning are [restricted reports](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-report-types), so you need a special token for authorization. You can find further details in the [documentation](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide).

**Comment by asd6979448** [comment]
> 令牌



> @asd6979448 Also some of the reports you are mentioning are [restricted reports](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-report-types), so you need a special token for authorization. You can find further details in the [documentation](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide).
OK, thanks
