### ISSUE TITLE
How to get the image address

### ISSUE THREAD

**Issue by EthanFromChina** [amzn/selling-partner-api-models#4223]
I want to get the "FRNT", "SIDE", "BACK" type data in the graph, but there is no place to return, how can I get it through the interface
![Snipaste_2024-10-11_17-56-55](https://github.com/user-attachments/assets/0afab3ab-00a0-47bb-9b13-94b1708d6263)

**Comment by EthanFromChina** [comment]
The current interface can obtain only the image addresses of the MAIN and PTO types
![image](https://github.com/user-attachments/assets/00ad63d9-9cc1-41e8-8548-34a639cebd5a)

**Comment by weilinggu** [comment]
@EthanFromChina I am actively investigating this ask. Once I have an update, I will let you know

Weiling
Selling Partner API Developer Services

**Comment by EthanFromChina** [comment]
> @EthanFromChina I am actively investigating this ask. Once I have an update, I will let you know
> 
> Weiling Selling Partner API Developer Services
May I ask whether there is a conclusion on this issue now

**Comment by EthanFromChina** [comment]
> @EthanFromChina I am actively investigating this ask. Once I have an update, I will let you know
> 
> Weiling Selling Partner API Developer Services

May I ask whether there is a conclusion on this issue now

**Comment by weilinggu** [comment]
@EthanFromChina Can you create a support case and provide the ASIN you are trying to get the images from?
Feel free to share the case ID here once you created it.

Thanks
Weiling 
Amazon Selling Partner Services
