### ISSUE TITLE
SPAPI v2024-03-20 - GeneratePackagingOptions

### ISSUE THREAD

**Issue by MeAndNotYou** [amzn/selling-partner-api-models#4225]
Hi, 

We are currently testing our migration to the new API v2024-03-20.
We created a new shipment plan and receive with the response:
inboundPlanId= wfb3ec2f6d-a33b-469a-84f5-332f0b9aedfb    and
operationId= 51582607-77c2-4628-8594-44e81c0fa34a.
When we are calling right after the generatePackingOptions then we are getting the error "ERROR: Operation GeneratePackingOptions cannot be processed on a cancelled inbound plan."

The plan had been accepted right before the call to the options. Why are we getting this error?

Thanks!

The complete data:
 ******************** AWS-Request ********************
RestRequest.Method: POST
Resource: /inbound/fba/2024-03-20/inboundPlans/wfb3ec2f6d-a33b-469a-84f5-332f0b9aedfb/packingOptions
********************  AWS - Response ********************
StatusCode: 400
StatusDescription: 
ResponseUri.AbsolutePath: /inbound/fba/2024-03-20/inboundPlans/wfb3ec2f6d-a33b-469a-84f5-332f0b9aedfb/packingOptions
ResponseUri.AbsoluteUri: https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wfb3ec2f6d-a33b-469a-84f5-332f0b9aedfb/packingOptions
ResponseUri.OriginalString: https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wfb3ec2f6d-a33b-469a-84f5-332f0b9aedfb/packingOptions
Content: {
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: Operation GeneratePackingOptions cannot be processed on a cancelled inbound plan.",
      "details": ""
    }
  ]
}

Response Headers:
-------------------------
Connection=keep-alive
x-amz-rid=RCPCAR50JMCF356F33AN
x-amzn-RateLimit-Limit=2.0
x-amzn-RequestId=3bb61a3e-e27b-4a61-b5fb-d4e874b99a1d
x-amz-apigw-id=OPF3bb61a3ee27b
X-Amzn-Trace-Id=Root=1-670ae439-3bb61a3ee27b4a61
Vary=Content-Type,Accept-Encoding,User-Agent
Strict-Transport-Security=max-age=47474747; includeSubDomains; preload
Content-Length=190
Content-Type=application/json
Date=Sat, 12 Oct 2024 21:03:53 GMT
Server=Server

Json: None

**Comment by mafge** [comment]
Hi @MeAndNotYou,
thanks for reaching out!
In general it is a good practice to call [getInboundOperationStatus](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20operationsoperationid) whenever you receive a `operationId`. Most of the operations from Fulfillment Inbound API are asynchronous which means getting a response is not a good indicator whether the operation succeeded or not. My recommendation is to check the operation status for the creation of the inbound plan, most likely you will see the reason for the cancellation in the response.
Hope that helps!
Best,
Marc
Selling Partner Developer Services
