### ISSUE TITLE
GET /finances/2024-06-19/transactions No data

### ISSUE THREAD

**Issue by asd6979448** [amzn/selling-partner-api-models#4226]
Why did I not get any information when I requested this report? I am sure that there were transactions during this time period. Did I misunderstand this report?

**Comment by jawheral** [comment]
Hi @asd6979448,

Are you providing a `marketplaceId` as part of the requests params? if so, did you make sure that's the right `marketplaceId` where you expect the transactions. 
Are these transactions very recent and do you see older transactions when you expand the interval? some transactions from the past 48 hours might not appear yet on Finance API's Transactions resource. 

Best,
Jawher
Selling Partner Developer Services

**Comment by joshsouthern** [comment]
> Why did I not get any information when I requested this report? I am sure that there were transactions during this time period. Did I misunderstand this report?

Not sure if this is your issue, but I'm finding any transactions classed as "Deferred" aren't being pulled through when running this, even if they show in Seller Central and are within the timeframe of the time interval in the request. Transactions with a status of Released are being showing in the response.

**Comment by Oanoan** [comment]
> 你好@asd6979448,
> 
> 您是否提供了`marketplaceId`作为请求参数的一部分？如果是这样，您是否确定那是`marketplaceId`您期望交易的正确位置？ 这些交易是最近发生的吗？当您扩大时间间隔时，您是否会看到较旧的交易？过去 48 小时内的某些交易可能尚未显示在 Finance API 的交易资源上。
> 
> 最佳 Jawher 销售合作伙伴开发人员服务

No matter how I adjust the parameters, the interface always returns null

**Comment by jawheral** [comment]
Hi @Oanoan,

Can you please share the HTTP response from the API call?

Best,
Jawher
Selling Partner Developer Services

**Comment by jawheral** [comment]
Hi @joshsouthern,

Regarding deferred transactions, these are not yet supported by the Finance v2024-06-19 API.

Best,
Jawher
Selling Partner Developer Services

**Comment by Oanoan** [comment]
> Hi @Oanoan,
> 
> Can you please share the HTTP response from the API call?
> 
> Best, Jawher Selling Partner Developer Services

![image](https://github.com/user-attachments/assets/c0924e94-745b-4ce8-91e1-850effc2b5fb)
class ListTransactionsResponse {
    nextToken: null
    transactions: null
}

**Comment by jawheral** [comment]
Hi @Oanoan 

This is most likely an issue within your code. Could you debug or check/share the HTTP API response? You can use a tool such as Postman to execute the request and provide the response.

I hope this helps!

Best,
Jawher
Selling Partner Developer Services

**Comment by omrishaked** [comment]
> Hi @joshsouthern,
> 
> Regarding deferred transactions, these are not yet supported by the Finance v2024-06-19 API.
> 
> Best, Jawher Selling Partner Developer Services

Any estimation for when deferred transactions will be supported?  Thanks!

**Comment by jawheral** [comment]
Hi,

Multiple bug fixes in regards with missing released (non-deferred) transactions have been recently published by our teams.

Deferred transactions support is planned by our internal teams but we can't provide any time estimation for now. 
Please keep an eye on the [announcements](https://developer-docs.amazon.com/sp-api/changelog) to learn about new releases and updates.

Please create a new issue if you notice missing transactions or other bugs again. I'm now closing this issue.

Best,
Jawher
Selling Partner Developer Services

**Comment by martin1297-hb** [comment]
I requested listTransactions of Finance v2024-06-19 API and filled in postedAfter, postedBefore, and marketplaceId correctly, but no data was returned.

**Comment by martin1297-hb** [comment]
> 我请求了 Finance v2024-06-19 API 的 listTransactions，并正确填写了 postedAfter、postedBefore 和 marketId，但是没有返回任何数据。
The result is as follows:

**Comment by litao1254** [comment]
I tracked it and found that there is data, but there was an error in the JSON parsing of the returned data

**Comment by litao1254** [comment]
There is an additional level of payload in the returned JSON data

**Comment by fangtianNT** [comment]
I have the same problem, have you solved it?

**Comment by AlexeyKosov** [comment]
Why is it closed? It's still not fixed.

**Comment by fangtianNT** [comment]
Debug it and you'll find that the data is actually returned, but the issue is caused by the incorrect entity mapping object provided by Amazon.













At 2025-06-18 14:34:23, "AlexeyKosov" ***@***.***> wrote:

AlexeyKosov left a comment (amzn/selling-partner-api-models#4226)

Why is it closed? It's still not fixed.

**Comment by AlexeyKosov** [comment]
@fangtianNT 
Yes, the JSON schema is incorrect and needs to be fixed, that's why I wrote it in this repo (api-models).
