### ISSUE TITLE
Start Selling Prime Inventory Using SP-API as an FBM Seller

### ISSUE THREAD

**Issue by surbhi-ctas** [amzn/selling-partner-api-models#4227]
I am currently an FBM (Fulfillment by Merchant) seller, and I would like to start selling Prime inventory in my Amazon Seller Central account. We manage our inventory and listings using the Selling Partner API (SP-API).

Could you help me find a solution on how to list Prime-eligible inventory using the SP-API?

**Questions:**

1. Is there a way to list Prime inventory using the Listings API?
2. Can you provide an API example for listing Prime inventory?
3. What are the steps or requirements to enable Prime inventory as an FBM seller?

Thank you for your assistance!

**Comment by mafge** [comment]
Hi @surbhi-ctas,
thanks for reaching out!
Do you want to stick with FBM or do you want to use FBA (Fulfillment by Amazon)? In the first case there is a program called [Seller Fulfilled Prime](https://sell.amazon.com/programs/seller-fulfilled-prime) but this is currently in trial and limited to the US only. Please also note that sellers have to met certain criteria to be eligible for this program. You can find all details in the FAQ at the bottom of the linked page. If you want to use FBA this is possible with SP API by using Listings Items API and Fulfillment Inbound API. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by surbhi-ctas** [comment]
Hi @mafge,

Yes, we are an FBM seller based in the EU, and we are interested in selling Prime inventory in Amazon Seller Central. However, as far as I understand, it seems that this is not currently possible for FBM sellers, correct?

Could you please confirm if there are any alternative ways to achieve this?

Thank you!

**Comment by mafge** [comment]
@surbhi-ctas Thanks for providing more information! Apparently seller fulfilled prime is also available in Europe. You can find further information on [this page](https://sellercentral.amazon.de/help/hub/reference/G201812230). You can also find a possibility  to sign up for that program on that page.
