### ISSUE TITLE
Amazon RMA ID / Unique key for returnless refunds?

### ISSUE THREAD

**Issue by dfreudenberger** [amzn/selling-partner-api-models#4229]
We are currently using the GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE report to track returns and their status.

For returns that have an Amazon RMA ID, this ID appears to be the unique identifier for the return.

However, for returnless refunds, there seems to be no Amazon RMA ID provided. How can we determine whether an entry from the report represents a new return, or if it is simply an update to a return that was already transmitted in a previous report?

Clarification on this would be greatly appreciated.

**Comment by mafge** [comment]
Hi @dfreudenberger,
thanks for reaching out!
In case of returnless refunds you need to keep track of this information on your side by using order id, asin/sku and return request date as unique identifier.
Best,
Marc
Selling Partner Developer Services
