### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 no way to get labels

### ISSUE THREAD

**Issue by nafberger** [amzn/selling-partner-api-models#4231]
Fulfillment Inbound API v2024-03-20 no way to get labels and the old get labels is getting deprecated, am i missing something

**Comment by johnkw** [comment]
Mmm no pretty sure this bug report is invalid, as the https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference page says getLabels is exempt from the old API removal.

**Comment by mafge** [comment]
Hi @nafberger,
thanks for reaching out!
As of now you have to call getLabel operation from v0 API to get the labels, even when using the new API for everything else (basically what @johnkw said). Hope that helps!
Best,
Marc
Selling Partner Developer Services
