### ISSUE TITLE
Fulfillment Inbound ShipmentId Error

### ISSUE THREAD

**Issue by CWillHan** [amzn/selling-partner-api-models#4232]
Using Fulfillment Inbound API V0 Version, Create inboundShipment Plan , theShipmentID returns a string starting with FBA that can be viewed in the frontend, for example: FBA15JCWYVLM

<img width="536" alt="image" src="https://github.com/user-attachments/assets/e9c485a5-d75a-41bc-b293-5c930d0cc825">

But when using Fulfillment Inbound API v2024-03-20 Version, ShipmentId returns an uncertain string, such as sha7d9fc6f-aaa5-499d-94dd-777a8c73893e, which cannot correspond to Amazon's front-end Shipment. How can v2024-03-20 Version obtain the ShipmentId displayed on the front-end interface

<img width="954" alt="image" src="https://github.com/user-attachments/assets/fd11cfad-7d97-4139-a4f3-affbc6729a12">

**Comment by mafge** [comment]
Hi @CWillHan,
thanks for reaching out!
You can get this string via the [getShipment](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20inboundplansinboundplanidshipmentsshipmentid) operation. The string you are looking for is called `amazonReferenceId` in the response body. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by mafge** [comment]
Hi @CWillHan,
thanks for reaching out!
It looks like you are looking for `shipmentConfirmationId` which can be fetched via [getShipment](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20inboundplansinboundplanidshipmentsshipmentid) operation. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by CWillHan** [comment]
Hello @mafge  I got it，it can get shipmentConfirmationId by using get shipment operation.after confirm Placement Option
