### ISSUE TITLE
Create Shipment Plan and following Operation Status

### ISSUE THREAD

**Issue by MeAndNotYou** [amzn/selling-partner-api-models#4233]
Greetings from here,

We are getting as PrepInstructionList for our SKU:

{"payload": 
   {
      "SKUPrepInstructionsList":    [
         {
            "SellerSKU": "696"
             , "ASIN": "B0016KTN2E"
             , "BarcodeInstruction": "RequiresFNSKULabel"
             , "PrepGuidance": "NoAdditionalPrepRequired"
             , "PrepInstructionList": ["Labeling"]
             , "AmazonPrepFeesDetailsList": 
             [{"PrepInstruction": "Labeling" , "FeePerUnit": {"CurrencyCode": "CAD" , "Value": 0.6}}]
          }
      ]
   , "InvalidSKUList": []
   }
}

... and sending via the create inbound plan
labelOwnwer = SELLER
prepOwner = NONE

Der CreatePlan call was accepted. But when we ask for the status then we are receiving

     Code: FBA_INB_0182
       Severity: ERROR
       Message: ERROR: Prep classification for this SKU was missing. Choose the prep category that applies to this SKU and apply any required prep and labeling to each sellable unit.
       Details: There's an input error with the resource '696'.

1. What is the reason for this error (We tried prepOwner = SELLER but then the CreatePlan wasn't even accepted)?
2. Do you have a table which prep categorie equals the value of which prepOwner value?

Thank you very much,

Kind regards,

Uwe

**Comment by mafge** [comment]
Hi @MeAndNotYou,
thanks for reaching out!
To handle this error, please add the prep category information for SKUs via Send to Amazon UI in Seller Central before proceeding with the CreateInboundPlan request. This has also been noted in the [usecase guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#step-1-create-an-inbound-plan). This is a one time activity that needs to be done for a new listing. We will be looking into making this more seamless via APIs in the future.
Best,
Marc
Selling Partner Developer Services
