### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 getLabel and LabelType=PALLE ERROR

### ISSUE THREAD

**Issue by liuyudong-pacvue** [amzn/selling-partner-api-models#4236]
Hello I have selected (LTL/FTL) for shipping model and Non-partnered carried for carrier, then called getLabel and LabelType=PALLET to print the pallet labels, but the api returned
`{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Sent request for 1 pallets. Actual pallet count is: 0 ",
            "details": ""
        }
    ]
}`
However, if the carrier selects Amazon partnered carrier, the download url of the label is returned.
Can you tell me exactly why?
![1729145653670](https://github.com/user-attachments/assets/b2631677-b236-4127-9e5f-041b64f4895c)

**Comment by puppsupr** [comment]
Hi,

PackageLabel_Letter_2 is only valid value for Amazon-partnered shipments in the US that use United Parcel Service (UPS) as the carrier. Please check for a valid [pageType](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#pagetype) and let me know if it works.

**Comment by liuyudong-pacvue** [comment]
After modifying pageType, return to normal, thank you for your answer.
