### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 Is there an api to change the ship date？

### ISSUE THREAD

**Issue by liuyudong-pacvue** [amzn/selling-partner-api-models#4239]
Hello, I was wondering if there is an API endpoint in the Fulfillment Inbound API v2024-03-20 that allows me to modify the ship date?  Because I noticed that it is possible to modify the ship date through the UI operation. But it's not found in the api

![1729231037768](https://github.com/user-attachments/assets/c64c10e2-027c-41b6-854a-bdb6a46b01a1)

**Comment by jawheral** [comment]
Hi @liuyudong-pacvue,

Have you checked the [confirmDeliveryWindowOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#post-inboundfba2024-03-20inboundplansinboundplanidshipmentsshipmentiddeliverywindowoptionsdeliverywindowoptionidconfirmation) operation from Fulfillment Inbound API v2024-03-20? You can use this operation to confirm the delivery window option for a chosen shipment within an inbound plan. You can list the delivery window options using the [listDeliveryWindowOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20inboundplansinboundplanidshipmentsshipmentiddeliverywindowoptions) operation.

Best,
Jawher
Selling Partner Developer Services

**Comment by liuyudong-pacvue** [comment]
Hi@jawheral

I checked the confirmDeliveryWindowOptions action and found that it's used to fill in the delivery window for Non-Amazon partnered carriers, but what I need is the change ship date action.

![1](https://github.com/user-attachments/assets/f8669b71-ae48-4d21-9cde-baf399cc63a4)
![2](https://github.com/user-attachments/assets/5bb90289-3507-4f2c-93a7-83c46f599fdb)

**Comment by jawheral** [comment]
Hi @liuyudong-pacvue,

There is no separate action for changing the `Ship date` as in the UI. It should be the `readyToShipWindow` that is provided when calling the [generateTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#post-inboundfba2024-03-20inboundplansinboundplanidtransportationoptions) operation.

Best,
Jawher
Selling Partner Developer Services

**Comment by liuyudong-pacvue** [comment]
@jawheral But I found that the ship date can be changed here.
![1729475654256](https://github.com/user-attachments/assets/af11353e-ae72-4a87-a50d-56b1883773f8)

**Comment by jawheral** [comment]
Hi @liuyudong-pacvue,

Can you confirm whether the `readyToShipWindow` on [generateTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#post-inboundfba2024-03-20inboundplansinboundplanidtransportationoptions) is not suitable for your use case?

Best,
Jawher
Selling Partner Developer Services

**Comment by liuyudong-pacvue** [comment]
Hi @jawheral 

I was trying to change the time of the ship date after `confirmTransportationOptions` as shown on the ui, but I found out that after calling `confirmTransportationOptions` and then `generatingTransportationOptions` response tells me that the Transportation Options have been confirmed and cannot be generated.

**Comment by liuyudong-pacvue** [comment]
Thank you for your answer.
