### ISSUE TITLE
GET_SALES_AND_TRAFFIC_REPORT report doesn't return records with 0 order

### ISSUE THREAD

**Issue by discover59** [amzn/selling-partner-api-models#424]
When I generate GET_SALES_AND_TRAFFIC_REPORT by ASIN and DAY dateGranularity, it returns records with 0 orders and non-zero traffic data.
But if I change it to "SKU" level, it doesn't include such records.

This makes difference between API data and business report on sellercentral.

Please check and let me know how to fix this issue.

**Comment by MILORDY** [comment]
@shreeharsh-a sabe quando vai ser resolvido ?

**Comment by fret423** [comment]
This is still open
