### ISSUE TITLE
GET /inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/transportationOptions aka listTransportationOptions response error

### ISSUE THREAD

**Issue by kxrdit-2** [amzn/selling-partner-api-models#4240]
![QQ_1729235058883](https://github.com/user-attachments/assets/4559df02-8d2c-49f8-ba10-28c894158363)
As shown in the figure, the value of the "amount" field is "$cost. mount"

**Comment by puppsupr** [comment]
Hi,
Are you still facing the issue ? You will see estimated cost only for Amazon Partnered transportation options. Sample response,

"transportationOptions": [

    {
        "carrier": {
            "name": "United States Postal Service",
            "alphaCode": "USPS"
        },
        "preconditions": [
            "CONFIRMED_DELIVERY_WINDOW"
        ],
        "shipmentId": "shxxxxxxxxxxxxxx",
        "shippingMode": "GROUND_SMALL_PARCEL",
        "transportationOptionId": "toxxxxxxxxxxxxxx",
        "shippingSolution": "USE_YOUR_OWN_CARRIER"
    },
  
    {
        "carrier": {
            "name": "UPS",
            "alphaCode": "UPSN"
        },
        "quote": {
            "cost": {
                "amount": 19.6,
                "code": "USD"
            }
        },
        "preconditions": [],
        "shipmentId": "shxxxxxxxxxxxxxx",
        "shippingMode": "GROUND_SMALL_PARCEL",
        "transportationOptionId": "toxxxxxxxxxxxxxx",
        "shippingSolution": "AMAZON_PARTNERED_CARRIER"
    }
]

**Comment by kxrdit-2** [comment]
Hello, sorry for getting back to you only now. I still found '$post. mount' in the response of the latest request.
This is the JSON I obtained:
{
  "transportationOptions": [
    {
      "carrier": {
        "name": "Amazon-Partnered Carrier",
        "alphaCode": "FBA-LTL"
      },
      "quote": {
        "cost": {
          "amount": "$cost.amount",
          "code": ""
        }
      },
      "preconditions": [],
      "shipmentId": "shxxxxxxxxxxxxxxxxxxx",
      "shippingMode": "FREIGHT_LTL",
      "transportationOptionId": "toxxxxxxxxxxxxxxxxxxx",
      "shippingSolution": "AMAZON_PARTNERED_CARRIER"
    }
  ],
  "pagination": {}
}

**Comment by puppsupr** [comment]
Hi @kxrdit-2 ,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end. Please provide request, response along with inboundPlanId in the support case.
