### ISSUE TITLE
Fulfillment Inbound v2024-03-20 ConfirmTransportationOptions error on multiple shipments

### ISSUE THREAD

**Issue by liuyudong-pacvue** [amzn/selling-partner-api-models#4241]
HI I called confirmTransportationOptions with multiple shipmentIds and then after calling getInboundOperationStatus the api returned an error.
``` json
 {
    "operationStatus": "FAILED",
    "operationId": "8d186756-dec4-4967-8bf9-b9b4f0bf99ed",
    "operation": "confirmTransportationOptions",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "BadRequest",
            "message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors."
        }
    ]
}  
 ```
Here's the process of calling my api：

**1.  createInboundPlan**
![1](https://github.com/user-attachments/assets/84798280-061e-442a-a583-1a6e59c0393a)

**2. generatePackingOptions**
![2](https://github.com/user-attachments/assets/c697e4de-f447-4958-8c87-7bbd6a55230c)

**3. listPackingOptions**
![3](https://github.com/user-attachments/assets/32a3f8e8-671d-4bc3-a751-1319c3a24a41)

**4. confirmPackingOption**
![4](https://github.com/user-attachments/assets/f6f8b0c8-a11d-454b-9629-452e02a3fc2a)

**5. setPackingInformation**
![5](https://github.com/user-attachments/assets/ee71cba2-b7be-4c7e-b793-4e4bb5da06e2)

**6. generatePlacementOptions**
![6](https://github.com/user-attachments/assets/cfd387d8-99d8-4ec6-b646-4f9d54dd1fc2)

**7. listPlacementOptions**
**tips: This selects the placementOptionId of multiple shipmentIds (if it was a single one, confirmTransportationOptions would not have reported an error).**
![7](https://github.com/user-attachments/assets/20db25df-3235-485c-96a0-2468e618173d)

**8. confirmPlacementOption**
![8](https://github.com/user-attachments/assets/09eac2d7-9e6c-4beb-92b9-fbf645113850)

**9. generateTransportationOptions**
![9](https://github.com/user-attachments/assets/7aa89500-c4a2-4e31-8368-f2d2476b431d)

**10. listTransportationOptions**
**tips: Get two shipment need to use the transportation Option Id ( For the sake of demonstration, the transportation of ups is used here. , do not need to submit delivery window Options), regardless of which two shipment use the transportation OptionId, after the confirmTransportationOptions api will report an error**
![10](https://github.com/user-attachments/assets/e44d80d2-8fed-41d1-954d-290e73b89bd3)

**11. confirmTransportationOptions**
![11](https://github.com/user-attachments/assets/03517803-52ca-4b4d-8210-99ffd727f7e3)

**12 . getInboundOperationStatus**
**tips:  Using the operationId that did not return an exception, I queried its status and found that it returned an error (this problem only occurs when multiple shipments are selected in the placementOptions).
I also tried selecting GROUND_SMALL_PARCEL or FREIGHT_LTL for the shippingModel and USE_YOUR_OWN_CARRIER or AMAZON_PARTNERED_CARRIER for the shippingSolution, no matter which option I selected, I got an error.
However, if I select a single shipment in the placementOptions, I can submit it normally.**
![12](https://github.com/user-attachments/assets/7d5f1de6-6de5-48b6-a2c2-2e10f0b9743c)

**Comment by puppsupr** [comment]
Working over.

**Comment by johnkw** [comment]
See also bug #4253 which notes the only current workaround is delete everything and retry.
