### ISSUE TITLE
GET /finances/2024-06-19/transactions  无法区分是那种赔偿

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4244]
![image](https://github.com/user-attachments/assets/d7817fe8-9b48-47b4-b183-737deda172f5)
你好，transactionType为 Adjustment 并且 description 为FBAInventoryReimbursement 无法区分是那种损坏，比喻是对应FBA Inventory Reimbursement - Lost:Outbound 还是  FBA Inventory Reimbursement - General Adjustment 还是其他的类型？？

**Comment by jawheral** [comment]
Hi @thesky2017,

Thank you for providing feedback. Our teams are aware now and I will reach out again if I receive any updates.

Best,
Jawher
Selling Partner Developer Services

**Comment by jawheral** [comment]
Hi @thesky2017 
Could you confirm whether this is resolved for you?

Best,
Jawher
Selling Partner Developer Services
