### ISSUE TITLE
【紧急-数据不准】GET /finances/2024-06-19/transactions 美国站点 VAT字段数据返回异常

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4245]
你好，API返回的数据中 没有 GiftwrapTax 金额字段返回，并且  OurPriceTax 和 ShippingTax 很多订单没有返回，
{
	"sellingPartnerMetadata": {
		"sellingPartnerId": "xxxxxxxxxxxxxx",
		"marketplaceId": "ATVPDKIKX0DER",
		"accountType": "Standard Orders"
	},
	"transactionType": "Shipment",
	"transactionId": "wkchcQAc_WjOgfiS5LcHRcDIhUK6jzwVEtkVM-TwGLk",
	"transactionStatus": "Released",
	"relatedIdentifiers": [{
		"relatedIdentifierName": "ORDER_ID",
		"relatedIdentifierValue": "112-0631468-5068257"
	}, {
		"relatedIdentifierName": "SHIPMENT_ID",
		"relatedIdentifierValue": "311651872781301"
	}, {
		"relatedIdentifierName": "FINANCIAL_EVENT_GROUP_ID",
		"relatedIdentifierValue": "yYfOpRcFagWtUvYXpHDFMW_SMO8T-Am8VXikZWmNukc"
	}],
	"totalAmount": {
		"currencyAmount": 98.88,
		"currencyCode": "USD"
	},
	"description": "Order Payment",
	"postedDate": "2024-09-18T09:13:09Z",
	"marketplaceDetails": {
		"marketplaceId": "ATVPDKIKX0DER",
		"marketplaceName": "Amazon.com"
	},
	"items": [{
		"description": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxs",
		"totalAmount": {
			"currencyAmount": 98.88,
			"currencyCode": "USD"
		},
		"relatedIdentifiers": [{
			"itemRelatedIdentifierName": "ORDER_ADJUSTMENT_ITEM_ID",
			"itemRelatedIdentifierValue": "109626759151681"
		}],
		"breakdowns": [{
			"breakdownType": "ProductCharges",
			"breakdownAmount": {
				"currencyAmount": 143.96,
				"currencyCode": "USD"
			},
			"breakdowns": [{
				"breakdownType": "OurPricePrincipal",
				"breakdownAmount": {
					"currencyAmount": 143.96,
					"currencyCode": "USD"
				},
				"breakdowns": []
			}]
		}, {
			"breakdownType": "AmazonFees",
			"breakdownAmount": {
				"currencyAmount": -45.08,
				"currencyCode": "USD"
			},
			"breakdowns": [{
				"breakdownType": "FBAPerUnitFulfillmentFee",
				"breakdownAmount": {
					"currencyAmount": -23.48,
					"currencyCode": "USD"
				},
				"breakdowns": [{
					"breakdownType": "Base",
					"breakdownAmount": {
						"currencyAmount": -23.48,
						"currencyCode": "USD"
					}
				}]
			}, {
				"breakdownType": "Commission",
				"breakdownAmount": {
					"currencyAmount": -21.6,
					"currencyCode": "USD"
				},
				"breakdowns": [{
					"breakdownType": "Base",
					"breakdownAmount": {
						"currencyAmount": -21.6,
						"currencyCode": "USD"
					}
				}]
			}]
		}],
		"contexts": [{
			"asin": "B075L7BCP8",
			"quantityShipped": 4,
			"sku": "55849US",
			"fulfillmentNetwork": "AFN",
			"contextType": "ProductContext"
		}]
	}],
	"breakdowns": [{
		"breakdownType": "Sales",
		"breakdownAmount": {
			"currencyAmount": 143.96,
			"currencyCode": "USD"
		},
		"breakdowns": [{
			"breakdownType": "ProductCharges",
			"breakdownAmount": {
				"currencyAmount": 143.96,
				"currencyCode": "USD"
			},
			"breakdowns": null
		}]
	}, {
		"breakdownType": "Expenses",
		"breakdownAmount": {
			"currencyAmount": -45.08,
			"currencyCode": "USD"
		},
		"breakdowns": [{
			"breakdownType": "AmazonFees",
			"breakdownAmount": {
				"currencyAmount": -45.08,
				"currencyCode": "USD"
			},
			"breakdowns": null
		}]
	}],
	"contexts": null
}
这个是API返回的  但是   日期范围报告 里有  11.88 元产品销售税

**Comment by jawheral** [comment]
Hi @thesky2017,

Thank you for letting us know about this issue.
Our teams are aware now, once I have any updates, I will provide them here.

Thanks,
Jawher
Selling Partner Developer Services

**Comment by thesky2017** [comment]
预计啥时候修复完成呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月21日(周一) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] 【紧急-数据不准】GET /finances/2024-06-19/transactions 美国站点 VAT字段数据返回异常 (Issue #4245)




 
Hi @thesky2017,
 
Thank you for letting us know about this issue.
 Our teams are aware now, once I have any updates, I will provide them here.
 
Thanks,
 Jawher
 Selling Partner Developer Services

**Comment by jawheral** [comment]
Hi @thesky2017,

We can't provide any estimation on a fix. Once I have any updates, I will let you know.
Thank you for your understanding.

Best,
Jawher
Selling Partner Developer Services

**Comment by thesky2017** [comment]
你好，除了日本站点正常，其他站点貌似都是这样。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月21日(周一) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] 【紧急-数据不准】GET /finances/2024-06-19/transactions 美国站点 VAT字段数据返回异常 (Issue #4245)




 
Hi @thesky2017,
 
Thank you for letting us know about this issue.
 Our teams are aware now, once I have any updates, I will provide them here.
 
Thanks,
 Jawher
 Selling Partner Developer Services

**Comment by jawheral** [comment]
Hi @thesky2017,

These issues should be fixed by now. Kindly confirm the fix when possible.

Thank you for your support and understanding!

Best,
Jawher
Selling Partner Developer Services

**Comment by thesky2017** [comment]
其他站点都fix了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] 【紧急-数据不准】GET /finances/2024-06-19/transactions 美国站点 VAT字段数据返回异常 (Issue #4245)




 
Hi @thesky2017,
 
These issues should be fixed by now. Kindly confirm the fix when possible.
 
Thank you for your support and understanding!
 
Best,
 Jawher
 Selling Partner Developer Services

**Comment by thesky2017** [comment]
我看了下us站点，还是没有税金返回



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] 【紧急-数据不准】GET /finances/2024-06-19/transactions 美国站点 VAT字段数据返回异常 (Issue #4245)




 
Hi @thesky2017,
 
These issues should be fixed by now. Kindly confirm the fix when possible.
 
Thank you for your support and understanding!
 
Best,
 Jawher
 Selling Partner Developer Services

**Comment by thesky2017** [comment]
是不是只有用户交上来的和平台代扣有差值的才返回？？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] 【紧急-数据不准】GET /finances/2024-06-19/transactions 美国站点 VAT字段数据返回异常 (Issue #4245)




 
Hi @thesky2017,
 
These issues should be fixed by now. Kindly confirm the fix when possible.
 
Thank you for your support and understanding!
 
Best,
 Jawher
 Selling Partner Developer Services

**Comment by jawheral** [comment]
Hi @thesky2017,

I suggest that you try again later. 
If this still doesn't work, please reach out to [Developer Support](https://developer.amazonservices.com/support) so we can better investigate the issues you are experiencing.

Best,
Jawher
Selling Partner Developer Services

**Comment by thesky2017** [comment]
不行呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月25日(周五) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [amzn/selling-partner-api-models] 【紧急-数据不准】GET /finances/2024-06-19/transactions 美国站点 VAT字段数据返回异常 (Issue #4245)




 
Hi @thesky2017,
 
I suggest that you try again later.
 If this still doesn't work, please reach out to Developer Support so we can better investigate the issues you are experiencing.
 
Best,
 Jawher
 Selling Partner Developer Services
