### ISSUE TITLE
Cancelation of a shipment

### ISSUE THREAD

**Issue by MeAndNotYou** [amzn/selling-partner-api-models#4246]
Greetings,

I didn't found an API call to cancel a completed shipment: Do I cancel the according inbound plan and every following operationId, option, shipment id etc become invalid?

Thanks

Uwe

**Comment by jawheral** [comment]
Hi @MeAndNotYou,

You use the `cancelInboundPlan` operation to cancel the process.
Note: `If a seller confirms the transportation request, then decides they don't want the Amazon-partnered carrier to ship the inbound shipment, they can use cancelInboundPlan to cancel the transportation request. For Small Parcel shipments, the seller has 24 hours after confirming a transportation request to void the request. For Less Than Truckload/Full Truckload (LTL/FTL) shipments, the seller has one hour after confirming a transportation request to void the request. After the relevant time period expires, the seller's account is charged for the shipping cost`

Please refer to the [cancellation section](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#cancel-an-inbound-plan) of the use case guide for more details.

Best,
Jawher
Selling Partner Developer Services

**Comment by johnkw** [comment]
Why would this be closed? The documentation is still extremely broken there.

Also, cancelinboundplan shouldn't even be allowed when Shipments exist for that Plan.  It should force you to separately cancel the Shipments first, so it's obvious what that implies.
