### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by noyessie** [amzn/selling-partner-api-models#4247]
I'm not sure this is the right place, but the SP-API documentation has not been accessible since yesterday. I keep getting an SSL error. 

![image](https://github.com/user-attachments/assets/bdd770f1-dbff-41e1-9bd5-be1db5ff2ee7)

My Chrome browser is updated to the latest version: 130.0.6723.59

**Comment by jimistep** [comment]
Sam thing on my end. I can't access the docs. SSL issue as well.

**Comment by arpetris** [comment]
Me too.

**Comment by jawheral** [comment]
Hi,

The SP-API documentation website is back to normal. 
We are sorry for the inconvenience.

Best,
Jawher
Selling Partner Developer Services
