### ISSUE TITLE
Fulfillment Inbound v2024-03-20 SetPackingInformation not working on sandbox

### ISSUE THREAD

**Issue by manish-in-java** [amzn/selling-partner-api-models#4248]
According to the API model available from Github at github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-inbound-api-model/fulfillmentInbound_2024-03-20.json, we are supposed to send the following `SetPackingInformation` request to the sandbox:

```
{
    "packageGroupings": [{
            "shipmentId": "sh1234abcd-1234-abcd-5678-1234abcd5678",
            "packingGroupId": "pg1234abcd-1234-abcd-5678-1234abcd5678",
            "boxes": [{
                    "items": [{
                            "msku": "msku",
                            "quantity": 5,
                            "expiration": "2024-01-01",
                            "prepOwner": "AMAZON",
                            "labelOwner": "AMAZON",
                            "manufacturingLotCode": "manufacturingLotCode"
                        }
                    ],
                    "contentInformationSource": "BOX_CONTENT_PROVIDED",
                    "weight": {
                        "unit": "KG",
                        "value": 5.5
                    },
                    "dimensions": {
                        "unitOfMeasurement": "CM",
                        "length": 3.0,
                        "width": 4.0,
                        "height": 5.0
                    },
                    "quantity": 2
                }
            ]
        }
    ]
}
```

However, this request always results in the following response from the sandbox:

```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Could not match input arguments",
            "details": ""
        }
    ]
}
```

How do we test this API?

**Comment by mafge** [comment]
Hi @manish-in-java,
thanks for reaching out!
I was able to reproduce the issue on my side. I'll report this to the responsible backend team immediately. I'll come back to you as soon as I have a response from them. Thanks again!
Best,
Marc
Selling Partner Developer Services

**Comment by growve-r** [comment]
Has this actually been solved? I am having the same issue as the original post.

**Comment by aapowerJames** [comment]
+1 im seeing this issue as well.

**Comment by VaishitRathore** [comment]
I’m seeing the same issue with the Fulfillment Inbound API static sandbox. Could Amazon please confirm whether the documented static sandbox fixture is currently working or provide an updated request fixture?
