### ISSUE TITLE
When I call createInboundPlan and get an operationId: cebd96c8-29b5-4074-93de-af8b3876d279, and then call the getInboundOperationStatus interface, I get the following feedback

### ISSUE THREAD

**Issue by asd6979448** [amzn/selling-partner-api-models#4249]
{"operation":"createInboundPlan","operation_id":"cebd96c8-29b5-4074-93de-af8b3876d279","operation_problems":[{"code":"InternalServerError","message":"ERROR: Something went wrong. Please try again later.","severity":"ERROR"}],"operation_status":"FAILED"}。 Is this a problem?

**Comment by asd6979448** [comment]
Can someone help me solve this problem? I haven't found a solution to this problem yet.

**Comment by puppsupr** [comment]
Hi,
In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.
