### ISSUE TITLE
"Business"/"Invoiced" orders are not distinguishable from standard orders

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#425]
According to Seller Support there is currently no report that distinguishes between "Business" orders and standard orders.  Additionally missing is whether the order is "Invoiced" or is paid normally.

Under some weird circumstances that I don't fully understand, "Business" "Invoiced" orders can have payment to the seller be delayed for 2 months, maybe longer?  There needs to be some way to account for these extremely long delays in an accounting system.  With no way to distinguish these orders, things are in limbo.

See also bug amzn/selling-partner-api-models#378.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
We did contact Support previously, and they indicated it was an open bug in SPAPI.

It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
