### ISSUE TITLE
Operation Generate Transportation Options cannot be processed because shipment configuration is not provided for all the shipments of the placement option

### ISSUE THREAD

**Issue by zaki-siddiqui** [amzn/selling-partner-api-models#4250]
I am generating TransportOptions and selecting a shipmentId from the available PlacementOptions. When there is only one shipmentId in the PlacementOptions, everything works perfectly. However, when I select a shipmentId from a set of multiple shipmentIds within the single PlacementOption, I encounter the following error while generating TransportOptions:

"Operation Generate Transportation Options cannot be processed because shipment configuration is not provided for all the shipments of the placement option."

It seems the issue arises when there are multiple shipments associated with a placement, and not all shipment configurations are provided.

How can I resolve this issue? Any help would be greatly appreciated.

**Comment by puppsupr** [comment]
Hi @zaki-siddiqui,

[generateTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatetransportationoptions) input should include the inboundPlanId, placementOptionID and shipmentTransportationConfigurations. The shipmentTransportationConfigurations should include shipmentId and readyToShipWindow start date  to generate small parcel delivery carrier options as per this tutorial. You need to include all the shipmentId's within a placementOptionID in the request.

Sample request,

{
  "placementOptionId": "plxxxxxxxxxxxxxxxxxxxx",
  "shipmentTransportationConfigurations": [
    {
      "readyToShipWindow": {
        "start": "yyyy-mm-ddT00:00:00Z"
      },
      "shipmentId": "sh1xxxxxxxxxxxxxxx"
    },
    {
      "readyToShipWindow": {
        "start": "yyyy-mm-T00:00:00Z"
      },
      "shipmentId": "sh2xxxxxxxxxxxxxx"
    }
  ]
}
