### ISSUE TITLE
List Inbound Plan

### ISSUE THREAD

**Issue by shantikolli** [amzn/selling-partner-api-models#4251]
As per the documentation, the list all inbound plans should return the placement id, packing id and shipment id  information for each shipment but it is not returning not sure why. Please look into this issue

**Comment by shantikolli** [comment]
![Uploading listinboundplans.PNG…]()

**Comment by shantikolli** [comment]
![listinboundplans](https://github.com/user-attachments/assets/acd49810-132a-4ab0-bb36-13d4ee34c4d6)

**Comment by mafge** [comment]
Hi @shantikolli,
thanks for reaching out!
[listInboundPlans](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplans) only returns a summary for each inbound plan which doesn't contain placementId, packingId and shipmentId. You need to call [getInboundPlan](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#getinboundplan) instead to get the required information. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by Waqas770** [comment]
Facing the same issue .... 

I am getting my latest shipment when call getShipments from the **Fulfillment Inbound API v0 Reference** 

6 => array:7 [▼
    "ShipmentId" => "FBAABCDEF"
    "ShipmentName" => "FBA STA (10/28/2024 19:24)-HGR6"
    "ShipFromAddress" => array:6 [▶]
    "DestinationFulfillmentCenterId" => "HGR6"
    "ShipmentStatus" => "RECEIVING"
    "LabelPrepType" => "SELLER_LABEL"
    "BoxContentsSource" => "INTERACTIVE"
  ]



But in the newer version when i call getInboundPlan(InboundPlanId) (With latest inbound plan id)


array:10 [▼ // routes/web.php:132
  "createdAt" => "2024-10-27T17:05:12Z"
  "marketplaceIds" => array:1 [▶]
  "packingOptions" => array:1 [▶]
  "sourceAddress" => array:8 [▶]
  "lastUpdatedAt" => "2024-10-28T03:17:26Z"
  "name" => ""
  "inboundPlanId" => "wff5ffb546-f261-45e3-80fb-4f27c2268a40"
  "placementOptions" => array:5 [▼
    0 => array:2 [▼
      "placementOptionId" => "pl13d05cee-593e-4c41-a72a-45e34c41a1ea"
      "status" => "OFFERED"
    ]
    1 => array:2 [▼
      "placementOptionId" => "pl97d1c70d-c605-471c-802f-b7825532b28f"
      "status" => "OFFERED"
    ]
    2 => array:2 [▼
      "placementOptionId" => "pld06cd6ef-4937-4fef-9fce-3bc1e51ba22c"
      "status" => "OFFERED"
    ]
    3 => array:2 [▼
      "placementOptionId" => "pldcc58e01-8941-4408-bd97-2c4346d044e3"
      "status" => "OFFERED"
    ]
    4 => array:2 [▼
      "placementOptionId" => "ple66e3791-2d67-488c-bb01-809037ff7b00"
      "status" => "OFFERED"
    ]
  ]
  "shipments" => []
  "status" => "ACTIVE"
]


Can anyone help how this inboundplan and shipments works in new version

**Comment by mafge** [comment]
Hi @Waqas770,
thanks for reaching out!
Looks like you need to confirm a placement option first before shipment(s) are visible in the inbound plan. You can find instructions in the [use case guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide). Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by Waqas770** [comment]
Hello @mafge Thanks for the quick reply 

Will this **(confirm a placement option first)** affect anything in the existing shipments (RECEIVING STATUS) and not created through API? manual shipment creation.


Also where I can find the placement fee for each shipment .. any endpoint or report type

Regards

**Comment by mafge** [comment]
@Waqas770 Not sure if I understand you correct. Let me try to explain: Inbound plan is the element where all the other information (like shipments) are attached to. You can have multiple inbound plans at any time, but you always only get the shipments from getInboundPlan operation that are tied to this specific inbound plan. From the screenshot you provided my guess would be that the shipment you fetched via the v0 API does not belong to the inbound plan you provided (you have to confirm a placement option first before a shipment is created).

Regarding the placement fee: You can use the [listPlacementOption](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listplacementoptions) operation, this returns fees for every placement option.
