### ISSUE TITLE
No estimated cost for LTL transportation options

### ISSUE THREAD

**Issue by lightningja** [amzn/selling-partner-api-models#4252]
I called the generateTransportationOption api to generate transportation options for LTL placement options. I got the paginated options. But none of the options provides the quote field.  So how does the new API provide estimated transportation cost for LTL shipments?

**Comment by MeenaAmz** [comment]
@lightningja Did you try using [listTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listtransportationoptions)? You should be able to get the quote for small parcel and LTL shipments for Amazon Partnered carriers  ("shippingSolution": "AMAZON_PARTNERED_CARRIER") using this operation as explained [here](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#response-example-11).You might not see the quote for non partnered options ("shippingSolution": "USE_YOUR_OWN_CARRIER").

Thanks
Meena 
Selling Partner Developer Services

**Comment by lightningja** [comment]
@MeenaAmz thx for the quick response! I figured our the problem. I was not passing the correct dimensions of the pallets for LTL.  Now I did get quote from amazon partnered carriers.  However, some quote has "$cost.amount" as value. Guess this is a bug from SPAPI side. Hope you guys fix it soon.

**Comment by MeenaAmz** [comment]
@lightningja Thanks for confirming. 

The quote issue requires further investigation, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here.
Once you open a support case, please feel free to share your case ID here so we can continue to monitor the issue status. 
Thanks,
Meena
Selling Partner API Developer Services
