### ISSUE TITLE
confirmTransportationOptions: Fail to execute CONFIRM_CARRIERS API with errors

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-models#4253]
I'm integrating with the new FBA Inbound API v2024-03-20 for a client. The end-to-end flow was working, but at some point it started failing at the `confirmTransportationOptions` step with the error `Fail to execute CONFIRM_CARRIERS API with errors`, and no additional details on what's going wrong. Here's the full error payload:

```json
{
    "operationStatus": "FAILED",
    "operationId": "c2fbebab-xxxx-xxxx-xxxx-1818a3cba30d",
    "operation": "confirmTransportationOptions",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "BadRequest",
            "message": "ERROR: Fail to execute CONFIRM_CARRIERS API with errors."
        }
    ]
}
```

Per @johnkw's comment on #4184 that says these calls fail randomly some percentage of the time with the exact same inputs, I tried automatically retrying the call up to 20 times in a row with the same inputs, but got the same exact error every time. Again, this exact code with the exact values I'm using was working at one point, but now I'm getting this error. This behavior seems to be consistent with what others are seeing from the new FBA Inbound API.

I've had an open support case on Seller Central related to this issue for going on 2 weeks with no real responses beyond "we'll get back to you."

At one point, I was getting the `ERROR: Something went wrong. Please try again later.` error as well, but that seems to have vanished and has been replaced with the `Fail to execute CONFIRM_CARRIERS API with errors` issue.

If anyone has any insight into how to get past this problem, that would be much appreciated.

**Comment by johnkw** [comment]
The retries only worked with bug #4184.  We also hit `ERROR: Fail to execute CONFIRM_CARRIERS API with errors.` and there was no way to recover from it within the workflow -- just stuck with the same error ever time (12 hours later even). I deleted the workflow, and recreated everything with the same options a second time and it worked then.

**Comment by MeenaAmz** [comment]
@jlevers Can you please share the support case that you opened for the issue?

Thanks 
Meena
Selling Partner Developer Services

**Comment by jlevers** [comment]
> The retries only worked with bug #4184. We also hit `ERROR: Fail to execute CONFIRM_CARRIERS API with errors.` and there was no way to recover from it within the workflow -- just stuck with the same error ever time (12 hours later even). I deleted the workflow, and recreated everything with the same options a second time and it worked then.

Interesting, I've retried with the same options several dozen times, with no success. But I'm 100% sure the exact same code and inputs was working a couple weeks ago. It's reassuring to hear that I'm not the only one getting inconsistent results from this endpoint.



> @jlevers Can you please share the support case that you opened for the issue?
> 
> Thanks Meena Selling Partner Developer Services

I have two – the more recent one is 16523362621, the other is 16429109411

**Comment by lightningja** [comment]
@jlevers I'm facing the same issue here. Always got ERROR: Fail to execute CONFIRM_CARRIERS API.

**Comment by jlevers** [comment]
Failing all the time – it worked a couple weeks ago, but since I started getting this error, I've never been able to make a successful call again.

**Comment by MeenaAmz** [comment]
> > The retries only worked with bug #4184. We also hit `ERROR: Fail to execute CONFIRM_CARRIERS API with errors.` and there was no way to recover from it within the workflow -- just stuck with the same error ever time (12 hours later even). I deleted the workflow, and recreated everything with the same options a second time and it worked then.
> 
> Interesting, I've retried with the same options several dozen times, with no success. But I'm 100% sure the exact same code and inputs was working a couple weeks ago. It's reassuring to hear that I'm not the only one getting inconsistent results from this endpoint.
> 
> > @jlevers Can you please share the support case that you opened for the issue?
> > Thanks Meena Selling Partner Developer Services
> 
> I have two – the more recent one is 16523362621, the other is 16429109411

Thanks for providing the ids. We are investigating the issue further based on the information provided. Please follow the support case for further updates.

Thanks
Meena
Selling Partner Developer Services

**Comment by lightningja** [comment]
@MeenaAmz @jlevers I would really appreciate it if you guys could share the investigation results here!

**Comment by jlevers** [comment]
I'll definitely update the thread when I get any response – I just got a notification that my two cases were being combined into one, but no further information.

**Comment by xyloneX** [comment]
I have been constantly reporting this error, which is causing me great distress

**Comment by MeenaAmz** [comment]
@lightningja @xyloneX Have you created support cases as well? Can you please share the numbers if you did?

Thanks
Meena
Selling Partner Developer Services

**Comment by lightningja** [comment]
@MeenaAmz yes I just created a support case today. It is: 16558452781

Thanks!

**Comment by AshwinPitroda** [comment]
I’ve been facing this error frequently recently. It seems that, for the same payload, sometimes it works fine, while other times it fails to execute the CONFIRM_CARRIERS API with errors.

Does anyone have a resolution for this?

**Comment by johnkw** [comment]
The only resolution is to delete the entire Workflow (which includes deleting the pending Shipments) and recreate it identically, and hope it works. The error doesn't have anything to do with the inputs.

**Comment by lightningja** [comment]
@jlevers @MeenaAmz Seems when I submit the contact information the api works

**Comment by xyloneX** [comment]
> I’ve been facing this error frequently recently. It seems that, for the same payload, sometimes it works fine, while other times it fails to execute the CONFIRM_CARRIERS API with errors.
> 
> Does anyone have a resolution for this?
me too,This is terrible

**Comment by xyloneX** [comment]
> I’ve been facing this error frequently recently. It seems that, for the same payload, sometimes it works fine, while other times it fails to execute the CONFIRM_CARRIERS API with errors.
> 
> Does anyone have a resolution for this?

This is terrible

**Comment by jlevers** [comment]
> @jlevers @MeenaAmz Seems when I submit the contact information the api works. Update: it worked for SPD flow. I created an LTL flow and it still failed even though I did pass contact info.

Ah, awesome, this worked for me! I still had to retry the `confirmTransportationOptions` call multiple times in a row before it succeeded, but it did eventually succeed.

Clearly there's still multiple bugs to be fixed here:
* The contact information being required even though the documentation says its optional
* Whatever the issue is that's making it so that you have to retry the `confirmTransportationOptions` call with the same data multiple times

**Comment by AshwinPitroda** [comment]
@jlevers @lightningja 

Now, I am not getting "ERROR: Fail to execute CONFIRM_CARRIERS API with errors" error but recently since last 3-4 days I am getting "ERROR: Invalid transportation option ID that either does not belong to provided shipment ID or is not AVAILABLE was passed in." error. I verified payload and I am passing correct values but still getting same error.

I tried passing contact informations but still some times getting above error.  

Does anyone facing same issue? Any resolution for this?

**Comment by johnkw** [comment]
Please delete and move other error messages to a discussion or new issue, and leave this issue #4253 for the current issue only.

**Comment by jlevers** [comment]
I'm able to resubmit on the same flow, but it sometimes takes a lot of tries...I have my code set up to re-run 20 times before it fails.

**Comment by jlevers** [comment]
I just got this response to my open case on this issue:

> I would like to inform that we have received an update from our back-end team.
>
> As per the update, this issue is caused due to the code error in our system. Our back end team has submitted code changes to fix this issue with the operation confirmTransportationOptions.
>
> The changes will be reflecting within a week.

So hopefully we'll get resolution on this relatively soon.

**Comment by lightningja** [comment]
@jlevers thx for the update! great teamwork to make it happen quickly! thx @MeenaAmz!

**Comment by AshwinPitroda** [comment]
@jlevers @lightningja Are you still experiencing this issue in the last 1-2 days?

I haven’t encountered the CONFIRM_CARRIERS failure error in the past 1-2 days, so I wanted to check if you’re also no longer seeing this issue. If none of us are experiencing it, it’s possible Amazon has pushed a fix.

**Comment by MeenaAmz** [comment]
The backend team identified a bug with confirmTransportationOptions operation and the fix was deployed earlier this week. So this issue should not occur anymore. Please [open a support case](https://developer.amazonservices.com/support) if you still see issues. Thanks for reporting the issue and updating the status.

Thanks
Meena
Selling Partner Developer Services
