### ISSUE TITLE
Fulfillment Inbound v2024 - Error Trying to UpdateShippingTrackingDetails

### ISSUE THREAD

**Issue by topkaj** [amzn/selling-partner-api-models#4255]
When I try to send the tracking details for a LTL shipment as indicated by the documentation, I correctly receive an operationId. Then, after a while consulting the result, I receive a generic error: 'ERROR: A server-side error occurred processing the operation UpdateShipmentTrackingDetails.'

I have ensured it follows the schema for the LTL case, but I can't figure out the reason behind.

`{ trackingDetails:  { ltlTrackingDetail: { freightBillNumber: [xxxxxxxxxx] } } }`

When i send the freightBillNumber directly in the platform, it is accepted correctly.

One of the operationId with this problem is `bf6acc48-700f-43d5-ae02-88bbd8682166`

I've also opened a case on support (id: 16525949211)

**Comment by Joportus** [comment]
I have the same issue :( ! If someone knows a solution please help

**Comment by narisso** [comment]
We have the same issue here, we have no idea what is the issue:

`ERROR: A server-side error occurred processing the operation UpdateShipmentTrackingDetails.`

**Comment by puppsupr** [comment]
Hi,
Please provide full request and response details along with inboundPlanId.

**Comment by topkaj** [comment]
The UpdateShippingTrackingDetails request:

```
{
  api_path: "/inbound/fba/2024-03-20/inboundPlans/wfcd1c1784-e507-4eac-bfcf-4ceae02e7d87/shipments/sh992ed848-8565-47ad-bbde-f7fdb47641ee/trackingDetails",
  method: "PUT",
  body: {
    trackingDetails: {
      ltlTrackingDetail: {
        freightBillNumber: [
          "794804696790",
        ],
      },
    },
  },
  timeouts: {
  },
}
```
returns the following:

```
{
  operationId: "90708b9f-156b-4fe0-927c-dcaa6767f7b2",
}
```

Then, after consulting the operation status as:

```
{
  api_path: "/inbound/fba/2024-03-20/operations/90708b9f-156b-4fe0-927c-dcaa6767f7b2",
  method: "GET",
  timeouts: {
  },
}
```

I get:

`'ERROR: A server-side error occurred processing the operation UpdateShipmentTrackingDetails.'`


Here is the other information requested :

```
"inboundPlanId": "wfcd1c1784-e507-4eac-bfcf-4ceae02e7d87"
"placementOptionId": "pl2f296879-672d-4e03-b039-cea725d941f9"
"shipmentId": "sh992ed848-8565-47ad-bbde-f7fdb47641ee"
"shipmentConfirmationId": "FBA18K9DGR9X"
```

**Comment by topkaj** [comment]
The UpdateShippingTrackingDetails request:

```
{
  api_path: "/inbound/fba/2024-03-20/inboundPlans/wfcd1c1784-e507-4eac-bfcf-4ceae02e7d87/shipments/sh992ed848-8565-47ad-bbde-f7fdb47641ee/trackingDetails",
  method: "PUT",
  body: {
    trackingDetails: {
      ltlTrackingDetail: {
        freightBillNumber: [
          "794804696790",
        ],
      },
    },
  },
  timeouts: {
  },
}
```
returns the following:

```
{
  operationId: "90708b9f-156b-4fe0-927c-dcaa6767f7b2",
}
```

Then, after consulting the operation status as:

```
{
  api_path: "/inbound/fba/2024-03-20/operations/90708b9f-156b-4fe0-927c-dcaa6767f7b2",
  method: "GET",
  timeouts: {
  },
}
```

I get:

`'ERROR: A server-side error occurred processing the operation UpdateShipmentTrackingDetails.'`


Here is the additional information requested :

```
"inboundPlanId": "wfcd1c1784-e507-4eac-bfcf-4ceae02e7d87"
"placementOptionId": "pl2f296879-672d-4e03-b039-cea725d941f9"
"shipmentId": "sh992ed848-8565-47ad-bbde-f7fdb47641ee"
"shipmentConfirmationId": "FBA18K9DGR9X"
```

**Comment by Christin519** [comment]
me too

**Comment by puppsupr** [comment]
Hi @topkaj,
Seems like you have a comma after the freightbillnumber 

freightBillNumber: [
          "794804696790",
        ],

Please remove the comma since its a single value, make sure the freightBillNumber array does not have a trailing comma:

"freightBillNumber": ["794804696790"],

**Comment by albertqiu2024** [comment]
Hi @puppsupr I have the save issue
{
    "api_path": "inbound/fba/2024-03-20/inboundPlans/wfab50d4f1-e53c-4054-ad91-e108960a0e02/shipments/sh88e02aac-ef01-4615-8601-9c5b385f37f7/trackingDetails",
    "header": [
        "Content-Type:application/json"
    ],
    "body": {
        "trackingDetails": {
            "ltlTrackingDetail": {
                "freightBillNumber": [
                    "123456"
                ]
            }
        }
    },
    "response": {
        "operationId": "74c1d3cd-0bda-4728-ab4c-cccb066c06f2"
    }
}

**Comment by albertqiu2024** [comment]
Hi @puppsupr I have the same issue
```
{
    "api_path": "inbound/fba/2024-03-20/inboundPlans/wfab50d4f1-e53c-4054-ad91-e108960a0e02/shipments/sh88e02aac-ef01-4615-8601-9c5b385f37f7/trackingDetails",
    "header": [
        "Content-Type:application/json"
    ],
    "body": {
        "trackingDetails": {
            "ltlTrackingDetail": {
                "freightBillNumber": [
                    "16KLY5GS"
                ]
            }
        }
    },
    "response": {
        "operationId": "74c1d3cd-0bda-4728-ab4c-cccb066c06f2"
    }
}
```  

get 'ERROR: A server-side error occurred processing the operation UpdateShipmentTrackingDetails.'

**Comment by topkaj** [comment]
N

> Hi @topkaj, Seems like you have a comma after the freightbillnumber
> 
> freightBillNumber: [ "794804696790", ],
> 
> Please remove the comma since its a single value, make sure the freightBillNumber array does not have a trailing comma:
> 
> "freightBillNumber": ["794804696790"],

It's not the comma. It's the standard format in which I copied the full request payload. I'm 100% sure i'm sending it as **an array of a single string value**. As you can see, more people have the exact same issue.

**Comment by puppsupr** [comment]
@Christin519, It might be different reasons as to why the call is failing in different cases. In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.
