### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 getShipment returns QuotaExceeded

### ISSUE THREAD

**Issue by littleylv** [amzn/selling-partner-api-models#4258]
**API:** 
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#getshipment

**response:**
```
{
  "errors": [
    {
      "code": "QuotaExceeded",
      "message": "You exceeded your quota for the requested resource.",
      "details": ""
    }
  ]
}
```

I have run Fulfillment Inbound API v2024-03-20 getShipment without errors for one month.
But from yesterday, the API return QuotaExceeded error even I did not call getShipment fast.
The document says Rate is 2:

|Rate (requests per second) | Burst|
|-- | --|
|2 | 6|

**Comment by Alvaromero** [comment]
I am experiencing the same issue. Sometimes, when I try to make a new call, I receive the 'QuotaExceeded' error, even if the last call to this endpoint was made several hours ago. Apparently, the problem started this week.

**Comment by weilinggu** [comment]
@littleylv Have you looked at the rate limit header in the response? [Here](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits) is a documentation that you can look at to understand how rate limit works.
If you still think there is an issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here. Make sure you include a sample response payload in your support case to help expedite the investigation.

Weiling
Amazon Selling Partner Services

**Comment by JuCongBoy** [comment]
@weilinggu 
@puppsupr 
Whenever a request is made, regardless of the interval, the following error response will be received:
{
  "errors": [
    {
      "code": "QuotaExceeded",
      "message": "You exceeded your quota for the requested resource.",
      "details": ""
    }
  ]
}
Return header parameters：
x-amzn-RequestId = 9e9a5949-f046-42ab-9889-7e04f4ce6ac1

**Comment by puppsupr** [comment]
Hi @JuCongBoy,
Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here. Make sure you include a sample response payload in your support case to help expedite the investigation.

**Comment by jlevers** [comment]
I've also started randomly getting 429 errors on various endpoints in the new FBA Inbound API, regardless of how long its been since I last called the endpoint. Whether or not I get the error seems to be almost entirely random.

**Comment by AshwinPitroda** [comment]
I 'have also started getting API rate limit error. It's now very frequent.

{
          "code": "QuotaExceeded",
          "message": "You exceeded your quota for the requested resource.",
          "details": ""
      }
      
      
     Since last one month many apis in new FBA Inbound API version started returning random error.

**Comment by pacton** [comment]
I am having the same issue. I am grabbing the x-amzn-RateLimit-Limit out of the header and delaying at (int)(1 / rate *  1000). I can run for hours testing on a InboundOperationStatus with no issues. But other times things fail for no reason - like this morning the first call of the day I get throttled out. Something is wrong. No question. We can't go production with this crap. How do you program for all this junk? really ...

**Comment by JackieLiu-1019** [comment]
I also encountered the same problem. I set the interval to 5 seconds and this situation will occur, and sometimes the error starts with the first request
![wenjian](https://github.com/user-attachments/assets/3a0b62a8-ed5e-4963-9686-1dd648cca229)
This is the case in the attachment. The interface was not accessed in the printed timestamp, and an error message appeared.

**Comment by puppsupr** [comment]
Hi,
Each of the operations has different rate limits. Look here in the [reference](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference) doc. For more information on [Rate Limits please look into this doc](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits).

If you still face issues please [open a support case](https://developer.amazonservices.com/support) as they can help you on this.

**Comment by theunixbeard** [comment]
@littleylv @Alvaromero  @JuCongBoy @jlevers @AshwinPitroda @pacton @JackieLiu-1019 how long did it take for your support ticket to get the rate limit issue resolved?

@weilinggu @puppsupr We have had a support ticket open for 7 days (since December 6th, Case ID 16789696631) and no resolution yet (nor ETA that could be provided)... This is an incredibly severe issue since the arbitrary / immediate rate limiting is making our app unusable! In our case it is the Financial Events API that is getting randomly rate limited...

**Comment by pacton** [comment]
@theunixbeard - they haven't resolved it. Just use a library like Polly and hammer them -
