### ISSUE TITLE
getLabels crashes with over 330 boxes

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#4260]
The URL GET line apparently is capped at around 7378 bytes.  More than that and you get an `HTTP 400` error from `Apache Tomcat/8.5.99`.  This translates to about 330 boxes.  This is a significant regression in the API since now only 330 boxes can go on 1 PDF. Previously in bug #1114 an extremely similar `HTTP 400` bug was fixed, but it appears that Amazon changed their Apache server in some way that this bug came back in a new form.

It's worth noting the box limit of only 330 is due to the fact that the boxId fields are now gigantic 19 byte strings of the format `FBAxxxxxxxxxU000123`.  Prior to /inbound/fba/2024-03-20 it was possible to specify those as short strings.  (Also, from an API perspective, there's no reason for these to even be strings at all.  They should just be counting integers starting at 1.)

The documentation on https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getlabels needs to be updated to address all of these bugs and limitations.  Although really it needs to be reimplemented as a `POST` with no such limits at all.

See also bug #4045 and bug #406 and bug #387 and bug #382.

**Comment by weilinggu** [comment]
@johnkw ,
This issue requires further inverstigation, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here.
Once you open a support case, please feel free to share your case ID here so we can continue to monitor the issue status. Thanks,
Weiling
Selling Partner API Developer Services

**Comment by johnkw** [comment]
It would be helpful to leave this open until it's fixed or at least documented as a known bug.
