### ISSUE TITLE
Can't create an inbound plan with more than 10,000 items of a single SKU

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-models#4262]
Is there some reason that when calling createInboundPlan, each inbound plan is limited to 10,000 items of a particular SKU? This limitation doesn't exist in Seller Central, and it means that if you want to ship >10,000 items through the API, you have to pay for more shipments than you would have to if you created the shipment plans manually.

**Comment by mafge** [comment]
Hi @jlevers,
thanks for reaching out!
Yes, the current limit of items per SKU is set to 10,000 (via the API). I'll let the backend team know that there is interest in increasing these limits (we have a similar issue here: https://github.com/amzn/selling-partner-api-models/issues/4266).
Best,
Marc
Selling Partner Developer Services
