### ISSUE TITLE
FBM instead of FBA problem.

### ISSUE THREAD

**Issue by WoodyWizard** [amzn/selling-partner-api-models#4265]
**Problem:** 

Even though the putListingsItem operation is used with AMAZON_NA as the fulfillment_channel_code in the fulfillment_availability attribute, the Amazon Selling Partner API is creating Fulfilled by Merchant (FBM) offers instead of the intended Fulfilled by Amazon (FBA) 

**Code Snippet:** 

`    body = {
        "productType": "ABIS_BOOK",
        "requirements": "LISTING_OFFER_ONLY",
        "attributes": {
            "purchasable_offer": [
                {
                    "marketplace_id": "A2EUQ1WTGCTBG2",
                    "currency": "CAD",
                    "our_price": [
                        {
                            "schedule": [
                                {
                                    "value_with_tax": float(data["price"])
                                }
                            ]
                        }
                    ]
                }
            ],
            "condition_type": [{
                "value": data["conditionType"]
            }],
            "fulfillment_availability": [
                {
                "fulfillment_channel_code": "AMAZON_NA"
                }
            ],
            "externally_assigned_product_identifier": [{
                "marketplace_id": "A2EUQ1WTGCTBG2",
                "type": "ean",
                "value": data["isbn"]
            }],
            "supplier_declared_dg_hz_regulation": [
                {
                    "value": "not_applicable",
                    "marketplace_id": "A2EUQ1WTGCTBG2"
                }
            ],
            "batteries_required": [
                {
                    "value": False,
                    "marketplace_id": "A2EUQ1WTGCTBG2"
                }
            ]
        },
    }
`

`
offer_data = {
    "isbn": "9781414380452",
    "conditionType": "used_very_good",
    "price": "9.99",
}
`

**Expected Behavior:**

The API should create FBA offers

**Actual Behavior:**

The API is creating FBM offers

**Comment by jlevers** [comment]
What happens if you set `requirements` to `LISTING`? I'm wondering if the `fulfillment_availability` attribute isn't considered an offer-related attribute for some reason.

**Comment by jawheral** [comment]
Hi @WoodyWizard,

How are you experiencing the actual behavior? Where did you notice that an FBA offer is not created? Did you make sure that the seller is enrolled in the FBA program?
Also, have you checked the response from the getListingsItems API for the same SKU to make sure no issues are there and that your fulfilment attributes were set as expected?

Is it the first time the offer is being created or are you trying to update inventory on an existing offer? If the offer exists already, it is recommended to use the `patchListingsItem` operation to update inventory.

Best,
Jawher
Selling Partner Developer Services

**Comment by WoodyWizard** [comment]
> Hi @WoodyWizard,
> 
> How are you experiencing the actual behavior? Where did you notice that an FBA offer is not created? Did you make sure that the seller is enrolled in the FBA program? Also, have you checked the response from the getListingsItems API for the same SKU to make sure no issues are there and that your fulfilment attributes were set as expected?
> 
> Is it the first time the offer is being created or are you trying to update inventory on an existing offer? If the offer exists already, it is recommended to use the `patchListingsItem` operation to update inventory.
> 
> Best, Jawher Selling Partner Developer Services

After waiting some time(around hour) it's became FBA.
So i think it's works as expected but i need to wait after it was added to my inventory.
So thank you for help
