### ISSUE TITLE
createInboundPlan limited to 1000 SKUs

### ISSUE THREAD

**Issue by fr3shn3ss** [amzn/selling-partner-api-models#4266]
Reporting issue with this API ==> createInboundPlan
URL : https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#createinboundplan

Call succeed when sending 1000 unique SKUs under "items". If sending anything over 1000, I receive the following error 
"errors": [
   {
    "code": "InternalFailure",
    "message": "We encountered an internal error. Please try again.",
    "details": ""
   }
  ]

1) Any workaround? Send to Amazon UI can already create shipments larger than 1000 skus
2) Anyway to create 2 shipments and merge them?

**Comment by puppsupr** [comment]
Hi [fr3shn3ss](https://github.com/fr3shn3ss),
The number of units of the specified SKU that can be shipped has limits as below,
Minimum value : 1
Maximum value : 10000

If you see something is not working as per the limits set, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

You can't merge multiple shipments.

**Comment by fr3shn3ss** [comment]
I opened a case and they said the API limit is 1k and not 10k. Is the 10k documented somewhere publicly?

**Comment by puppsupr** [comment]
Hi @fr3shn3ss,
Here is the [link](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#iteminput). Can you please provide the case number ?

**Comment by mafge** [comment]
@puppsupr @fr3shn3ss Looks like we are talking about two different things here:
- Number of individual SKUs per inbound plan: 1000 (tbc)
- Number of items per SKU per inbound plan: 10.000 (according to doc).
Please correct me if I am wrong.

**Comment by fr3shn3ss** [comment]
That's correct. It's a shame that it is 1000. Large book sellers specifically need to create 1500 sku shipments. This was possible before Send 2 Amazon
Case ID : 16552133171
