### ISSUE TITLE
【重要】/finances/2024-06-19/transactions  无法区分那种退款？？

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4268]
日期范围报告：typ 区分了 Erstattung 和 Erstattung durch Rückbuchung，但是 /finances/2024-06-19/transactions 无法区分，交易类型全部为Refund, 比喻订单：
API返回
![image](https://github.com/user-attachments/assets/f404b879-3937-436d-973e-19b4e131c4cc)
日期交易报告
![image](https://github.com/user-attachments/assets/67e1a447-efc7-4e05-be2b-1f15512b27e2)

**Comment by jawheral** [comment]
#4274

**Comment by thesky2017** [comment]
This issue has not been resolved yet. Is the transaction type still refunded


飞翔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-models"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月8日(星期五) 凌晨4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-models] 【重要】/finances/2024-06-19/transactions  无法区分那种退款？？ (Issue #4268)





 
Closed #4268 as completed.

**Comment by jawheral** [comment]
Hi @thesky2017, 
Please follow the link to the related issue I mentioned in my previous comments: https://github.com/amzn/selling-partner-api-models/issues/4274
Once available, we will provide updates on that issue.

Best,
Jawher
Selling Partner Developer Services
