### ISSUE TITLE
SetPackingInformation InternalServerError when packing group  "boxes" count is greater than 3000

### ISSUE THREAD

**Issue by miraemor** [amzn/selling-partner-api-models#4269]
Created InboundPlan with 622 SKU items
`PlanId: wfc6063f71-61e3-4d43-8a8b-f71a8daf7ed2`

Tried to call SetPackingInformation with 5166 boxes in one of the group and got ValidationError than packing group boxes collection is limited by 5000 boxes. There is no info about group limits in documentation

In second attempt limited box count to 4985 and got this result

```
{
    "operationStatus": "FAILED",
    "operationId": "6b32bcf7-bc92-41ee-a94e-94b642e691cf",
    "operation": "setPackingInformation",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "InternalServerError",
            "message": "ERROR: A server-side error occurred processing the operation SetPackingInformation."
        }
    ]
}
```

What is packing group box limit that can be processed successfully? I had previous plan with about 3000 boxes and it processed successfully, so is there some limit when this call is works and if over that amount it causes InternalServerError?

If some guys from DevTeam need more details I can provide request bodies for Plan and PackingInfo. But for now I'll skip them because they are huge.

**Comment by puppsupr** [comment]
Hi [miraemor](https://github.com/miraemor),
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.
