### ISSUE TITLE
/finances/2024-06-19/transactions 返回的 transactionType 为 Retrocharge 并且 description 为 RetroChargeRefund 的数据不对

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4271]
![image](https://github.com/user-attachments/assets/5af0e935-a6bd-4474-8cc4-5226f8b5830e)
如上图  日期范围报告有 product sales tax   和  marketplace withheld tax  
但是API 却返回如下图所示：无法区分是 product sales tax  和 marketplace withheld tax
Array
(
    [sellingPartnerMetadata] => Array
        (
            [sellingPartnerId] => xxxxx
            [marketplaceId] => xxxxxxx
            [accountType] => Standard Orders
        )

    [transactionType] => Retrocharge
    [transactionId] => xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    [transactionStatus] => Released
    [relatedIdentifiers] => Array
        (
            [0] => Array
                (
                    [relatedIdentifierName] => ORDER_ID
                    [relatedIdentifierValue] => xxxxxxxxxxxxxxxxxxxxxxxx
                )

            [1] => Array
                (
                    [relatedIdentifierName] => FINANCIAL_EVENT_GROUP_ID
                    [relatedIdentifierValue] => xxxxxxxxxxxxxxxxxxxxxxxxxx
                )

        )

    [totalAmount] => Array
        (
            [currencyAmount] => 0
            [currencyCode] => USD
        )

    [description] => RetroChargeRefund
    [postedDate] => 2024-08-18T01:24:20Z
    [marketplaceDetails] => Array
        (
            [marketplaceId] => xxxxxxxxxxxxxxxx
            [marketplaceName] => Amazon.com
        )

    [items] => 
    [breakdowns] => Array
        (
            [0] => Array
                (
                    [breakdownType] => Sales
                    [breakdownAmount] => Array
                        (
                            [currencyAmount] => 0.7
                            [currencyCode] => USD
                        )

                    [breakdowns] => Array
                        (
                            [0] => Array
                                (
                                    [breakdownType] => Other
                                    [breakdownAmount] => Array
                                        (
                                            [currencyAmount] => 0.7
                                            [currencyCode] => USD
                                        )

                                    [breakdowns] => 
                                )

                        )

                )

            [1] => Array
                (
                    [breakdownType] => Expenses
                    [breakdownAmount] => Array
                        (
                            [currencyAmount] => -0.7
                            [currencyCode] => USD
                        )

                    [breakdowns] => Array
                        (
                            [0] => Array
                                (
                                    [breakdownType] => RetrochargeReversal
                                    [breakdownAmount] => Array
                                        (
                                            [currencyAmount] => -0.7
                                            [currencyCode] => USD
                                        )

                                    [breakdowns] => 
                                )

                        )

                )

        )

    [contexts] => 
)

**Comment by weilinggu** [comment]
Hello @thesky2017,

Thank you for raising this issue.This issue requires further investigation, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here.
Please ensure you provide the following information in your support case.  

Thanks,
Weiling
Selling Partner API Developer Services
