### ISSUE TITLE
Report returns CSV instead of XML

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4272]
Hello
We request GET_XML_RETURNS_DATA_BY_RETURN_DATE, it **used to return an XML** document with return details, rma ID etc.

**Now it returns CSV** with these headers

    order-id order-item-id purchase-date payments-date reporting-date promise-date days-past-promise buyer-email buyer-phone-number sku product-name quantity-purchased quantity-shipped quantity-to-ship ship-service-level recipient-name ship-address-1 ship-address-2 ship-address-3 ship-city ship-state ship-postal-code ship-country is-business-order purchase-order-number price-designation is-iba

I don't even see RMA ID or request status
Don't know what happened, I'm not aware of changing anything on our side

Thank you!

**Comment by jawheral** [comment]
Hi @NoxArt,

The tabular data you shared is the result from an order [report](https://developer-docs.amazon.com/sp-api/docs/report-type-values-order#unshipped-orders-report): `GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING`.

`GET_XML_RETURNS_DATA_BY_RETURN_DATE` cannot return this data. Please make sure that you are creating and downloading the the right report type.

I hope this helps!

Best,
Jawher
Selling Partner Developer Services

**Comment by NoxArt** [comment]
Thank you
I'm pretty much absolutely sure we have the right type

This is the result of GET reports command
![image](https://github.com/user-attachments/assets/a2ac5ca2-8f9d-4079-959f-ede217b910b5)

There still might be an issue on our side but I just haven't found any so far

**Comment by jawheral** [comment]
Hi @NoxArt,

Thank you for reaching out. As this is not a confirmed issue with SP-API, I will close this issue. 
Please investigate your system and if an issue is confirmed, feel free to reopen while providing all the details regarding the report request.

Best,
Jawher
Selling Partner Developer Services

**Comment by NoxArt** [comment]
Now it returns XML, weird...

But btw I think it only returns it for the first marketplace, that is, this line "If you include more than one marketplace in your request, only information that relates to the first marketplace is returned." which is here https://developer-docs.amazon.com/sp-api/docs/report-type-values-returns for GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE imho applies for GET_XML_RETURNS_DATA_BY_RETURN_DATE as well, so maybe it should be updated

@jawheral
