### ISSUE TITLE
Finances API v2024-06-19 Authorization Issue

### ISSUE THREAD

**Issue by daehee-kang** [amzn/selling-partner-api-models#4273]
Hi,

I’ve been using the Finances API v0, and I’m currently migrating to the new version, v2024-06-19. However, I’m encountering an issue: when I call the listTransaction API (v2024-06-19), I receive a 403 Unauthorized response. In contrast, calls to the listFinancialEvents API (v0) return successful responses.

According to the documentation, the required configurations for both versions appear to be the same. I’m wondering if this could be a bug or if there’s an undisclosed configuration change needed for the new version.

Thank you in advance for your help!

I would have created a support ticket for this issue, but I don’t have direct access to the account. I thought it would be helpful to ask here for options I can try once I gain access, aside from just submitting a support ticket.

**Comment by ritikacd** [comment]
Hi @daehee-kang 

Thanks for reaching out. This issue requires further investigation, are you calling the API using nextToken parameter? Can you share API endpoint? 

Please ensure you don't have any of the issues mentioned [here](https://developer-docs.amazon.com/sp-api/docs/authorization-errors#error-messages) under `Unauthorized` section. 

Thanks, 
Ritika

**Comment by daehee-kang** [comment]
Hi @ritikacd 

are you calling the API using nextToken parameter? Can you share API endpoint?

 - I’m making a simple GET request to the endpoint **"finances/2024-06-19/transactions?postedAfter=2024-10-27T07:00:00.000Z"**. However, it seems that the value of the query parameters doesn't matter. I’ve tried different values for `postedAfter`, as well as including `marketplaceId` and `postedBefore`, but none have worked.

Please ensure you don't have any of the issues mentioned [here](https://developer-docs.amazon.com/sp-api/docs/authorization-errors#error-messages) under `Unauthorized` section.

 - I reviewed it, and the actual error message I received was: `Access to requested resource is denied`. However, the token seems to be working fine, as I tested it with the **"finances/v0/financialEvents"** API, and that call returned a successful response. Since the **"finances/v0/financialEvents"** API worked without any issues, I don't believe this problem falls under the `Unauthorized` category you referenced.

```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to requested resource is denied.",
      "details": ""
    }
  ]
}
```

Thanks

**Comment by ritikacd** [comment]
> Hi @ritikacd
> 
> are you calling the API using nextToken parameter? Can you share API endpoint?
> 
> * I’m making a simple GET request to the endpoint **"finances/2024-06-19/transactions?postedAfter=2024-10-27T07:00:00.000Z"**. However, it seems that the value of the query parameters doesn't matter. I’ve tried different values for `postedAfter`, as well as including `marketplaceId` and `postedBefore`, but none have worked.
> 
> Please ensure you don't have any of the issues mentioned [here](https://developer-docs.amazon.com/sp-api/docs/authorization-errors#error-messages) under `Unauthorized` section.
> 
> * I reviewed it, and the actual error message I received was: `Access to requested resource is denied`. However, the token seems to be working fine, as I tested it with the **"finances/v0/financialEvents"** API, and that call returned a successful response. Since the **"finances/v0/financialEvents"** API worked without any issues, I don't believe this problem falls under the `Unauthorized` category you referenced.
> 
> ```
> {
>   "errors": [
>     {
>       "code": "Unauthorized",
>       "message": "Access to requested resource is denied.",
>       "details": ""
>     }
>   ]
> }
> ```
> 
> Thanks

Hi @daehee-kang 

I validated the API endpoint, and I'm able to get a response successfully. In your case, we will need to investigate the authorization passed in the request. Do you have access to open a ticket with developer [support](https://developer.amazonservices.com/support)? Please note that you can open a ticket from your developer central account as well. 

Thanks,
Ritika
