### ISSUE TITLE
getPrepDetails not valid

### ISSUE THREAD

**Issue by xyloneX** [amzn/selling-partner-api-models#4278]
The uploaded sku has no space, and there is a space when reporting an error
sku:JX-BFH002473-01-DE-50st(3,6x19cm)

response
{
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: The following MSKUs are not valid: [JX-BFH002473-01-DE-50st(3, 6x19cm)].",
      "details": ""
    }
  ]
}
@puppsupr

**Comment by mafge** [comment]
Hi @xyloneX,
thanks for reaching out!
You need to encode the SKU in case it contains any special characters as it is a query parameter that is added to the url. You can find further details on [this page](https://developer-docs.amazon.com/sp-api/docs/url-encoding). Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by xyloneX** [comment]
> 你好@xyloneX， 感谢您的联系！ 您需要对 SKU 进行编码，以防它包含任何特殊字符，因为它是添加到 URL 的查询参数。您可以在[此页面](https://developer-docs.amazon.com/sp-api/docs/url-encoding)上找到更多详细信息。希望对您有所帮助！祝 好， Marc 销售合作伙伴开发者服务

{
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: The following MSKUs are not valid: [JX-BFH002473-01-DE-50st%283%2C6x19cm%29].",
      "details": ""
    }
  ]
}

**Comment by mafge** [comment]
@xyloneX SP-API is unable to distinguish encoded comma (%2C) values from literal comma (,) values. This prevents SKUs with commas from being used in comma-delimited query parameters, as the commas in those SKUs cannot be distinguished from commas separating arguments. The recommendation is to not use `,` in the SKUs.

**Comment by xyloneX** [comment]
> @xyloneX SP-API is unable to distinguish encoded comma (%2C) values from literal comma (,) values. This prevents SKUs with commas from being used in comma-delimited query parameters, as the commas in those SKUs cannot be distinguished from commas separating arguments. The recommendation is to not use `,` in the SKUs.

How to get through now?

**Comment by mafge** [comment]
@xyloneX You have multiple options. You can continue the fulfillment inbound process for that SKU on Seller Central UI but keep in mind that you have to do it forever that way. You can also delete the listing and create a new one (for FBA only possible if the inventory is 0).
