### ISSUE TITLE
【bug】finances/2024-06-19/transactions 无法返回accountType 为 Invoiced Orders 类型的订单

### ISSUE THREAD

**Issue by thesky2017** [amzn/selling-partner-api-models#4279]
为什么finances/2024-06-19/transactions 调用这个API, 同步postedBefore 和 postedAfter 传 9.1 号到 9.3号 数据能返回，但是accountType 为 Invoiced Orders 类型的订单是 9月1号 却在9月3号后返回呢？如下图
![image](https://github.com/user-attachments/assets/0b8845b5-3466-4a7f-9558-2e99b712a15f)
如果是传 9.1号到10.1号， Invoiced Orders 类型的订单的交易数据直接不返回。

**Comment by jawheral** [comment]
Hi @thesky2017,

Could you please elaborate on this issue? I need more information to better understand what is wrong.

Best,
Jawher
Selling Partner Developer Services

**Comment by thesky2017** [comment]
这个问题已经好了，我发现API 是先返回正常的订单 ，类似&nbsp; 11111-2222-3333-4444 这种格式的订单&nbsp; 然后再返回 S开头的订单号&nbsp; 最后返回发票类型的订单 ，但是 有另外一个问题，当请求的时间是一个月的时候，API同步到最后的时候就会报错，报错信息如下，ruquestId&nbsp; ccee7681-b68d-4d47-ac4c-b6d8ffb540b1
{\n&nbsp; \"errors\": [\n&nbsp; &nbsp; {\n&nbsp; &nbsp; &nbsp; \"code\": \"InternalFailure\",\n&nbsp; &nbsp; &nbsp; \"message\": \"We encountered an internal error. Please try again.\",\n&nbsp; &nbsp; &nbsp; \"details\": \"\"\n&nbsp; &nbsp; }\n&nbsp; ]\n}"},"message":"InternalFailure:We encountered an internal error. Please try again.:(RequestID:ccee7681-b68d-4d47-ac4c-b6d8ffb540b1)


但是如果把一个月的时间划分几个小的时间段去请求&nbsp; 就没有问题。


另外 以下问题也帮我看看：
https://github.com/amzn/selling-partner-api-models/issues/4271


https://github.com/amzn/selling-partner-api-models/issues/4268


https://github.com/amzn/selling-partner-api-models/issues/4244






飞翔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amzn/selling-partner-api-models"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月6日(星期三) 凌晨0:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amzn/selling-partner-api-models] 【bug】finances/2024-06-19/transactions 无法返回accountType 为 Invoiced Orders 类型的订单 (Issue #4279)





 
Hi @thesky2017,
 
Could you please elaborate on this issue? I need more information to better understand what is wrong.
 
Best,
 Jawher
 Selling Partner Developer Services

**Comment by jawheral** [comment]
Hi @thesky2017,

Thanks for confirming this issue is solved.
Regarding the other open issues, we still don't have updates, I will let you know once I have more infromation.

Please create another issue providing all the details such as sellerId, requestId, postedBefore, postedAfter and marketplace parameters so we can work on the bug you mentioned when requesting a month period.

I'm now closing this issue.

Thank you for your support and understanding!

Best,
Jawher
Selling Partner Developer Services
