### ISSUE TITLE
No documentation for the new Fulfillment Inbound v2024-03-20 API specific error codes

### ISSUE THREAD

**Issue by PoneraLucas** [amzn/selling-partner-api-models#4280]
Hello,

We have been trying to implement the new version of the Fulfillment Inbound API and during so, we noticed that we can't find some error codes that are returned in the doc.

Ex : FBA_INB_0005, FBA_INB_0180, FBA_INB_0182.

**Comment by puppsupr** [comment]
Hi [PoneraLucas](https://github.com/PoneraLucas),
Have you been receiving the mentioned errors ?

**Comment by PoneraLucas** [comment]
Hello @puppsupr,
I am receiving these errors when trying to create an Inbound plan.

FBA_INB_0005 : "This product is missing necessary information; weight need to be provided in he manufacturer's original packaging."
FBA_INB_0180 : "Expiration date required."
FBA_INB_0182 : "Prep classification for this SKU was missing. Choose the prep category that applies to this SKU and apply any required prep and labeling to each sellable unit."

I have been getting those errors when using the FulfillmentInbound v2024-03-20, are there other errors codes that are only returned by this operation?

**Comment by puppsupr** [comment]
Hi,
These errors are self explained, can you please provide the create inbound plan request you made ?
Also SKUs requiring expiration dates must include the date. Below is the sample,

POST /inbound/fba/2024-03-20/inboundPlans
{
  "destinationMarketplaces" : [ "ATVPDKIKX0DER" ],
  "items" : [ {
    "expiration" : "2024-01-01",
    "labelOwner" : "AMAZON",
    "manufacturingLotCode" : "manufacturingLotCode",
    "msku" : "Sunglasses",
    "prepOwner" : "AMAZON",
    "quantity" : 10
  } ],
  "name" : "My inbound plan",
  "sourceAddress" : {
    "addressLine1" : "123 example street",
    "addressLine2" : "Floor 19",
    "city" : "Toronto",
    "companyName" : "Acme",
    "countryCode" : "CA",
    "email" : "email@email.com",
    "name" : "name",
    "phoneNumber" : "1234567890",
    "postalCode" : "M1M1M1",
    "stateOrProvinceCode" : "ON"
  }
}

Also to get the right prep details for an SKU call [listPrepDetails](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listprepdetails) and to set preparation instructions for an MSKU call [setPrepDetails](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#setprepdetails). 

Please refer to our use-case guide for more details.

Also checkout the [Postman Collections](https://www.postman.com/galactic-rocket-691225/selling-partner-api-for-fulfillment-inbound-fba-v2024/overview) and [Sample code ](https://github.com/amzn/selling-partner-api-samples/tree/main/use-cases/fulfillment-inbound)which can help you to understand the workflows.
