### ISSUE TITLE
generateTransportationOptions

### ISSUE THREAD

**Issue by HDPAlex** [amzn/selling-partner-api-models#4281]
Hello
Is there a way to request transportation options only for small package AMAZON_PARTNERED_CARRIER like UPS only skipping USE_YOUR_OWN_CARRIER options?

**Comment by puppsupr** [comment]
Hi @HDPAlex,
You can't generate Amazon Partnered carriers only options. You need to call [generateTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatetransportationoptions) and then [listTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listtransportationoptions) to view the generated options.

To ship using the Amazon Partnered Carrier, you must select the transportationOption based on your shipment type:

* For small parcel deliveries, choose the option with shippingMode set to GROUND_SMALL_PARCEL and shippingSolution is set to AMAZON_PARTNERED_CARRIER.
