### ISSUE TITLE
Does the MLI api support vendor central users?

### ISSUE THREAD

**Issue by Yiki888** [amzn/selling-partner-api-models#4282]
Does the MLI api support vendor central users?
I now use the Listings Items API described in the mli api document to query my vc-df listing inventory and the attributes returned are empty. Is it because of the data permissions of my vendor central developer account?

**Comment by Yiki888** [comment]
This is the relevant information when my vc developer account calls the MLT api. I can use my SC developer account to return the warehouse address configuration information. So do I need to apply for my VC developer account for MLI api permissions?
![image](https://github.com/user-attachments/assets/2007dd32-c2a1-4e1d-928f-549c36a4c0b4)

**Comment by Yiki888** [comment]
![image](https://github.com/user-attachments/assets/a6983686-1730-490b-8fb8-edb3d366f656)

**Comment by puppsupr** [comment]
Hi,
MLI APIs are not available for vendors as of now.
