### ISSUE TITLE
Fulfillment Inbound v2024-03-20: Error on confirmTransportationOptions invalid option

### ISSUE THREAD

**Issue by Prez5er** [amzn/selling-partner-api-models#4284]
Hi team

I'm trying to create a shipment, but at the end of the workflow to generate it, the **confirmTransportationOptions** endpoints threw me an error sometimes, once I checked it on the **getInboundOperationStatus**

![imagen](https://github.com/user-attachments/assets/bfc21a36-4879-42e8-9053-76e0d3d2cde6)

The weird thing is that I passed the correct relations
- the **confirmTransportationOptions** payload
![{1A4646C1-1389-44FD-84E3-5837A7D5AAD6}](https://github.com/user-attachments/assets/a34998af-5d5b-448f-83f4-a70b6480bc1c)

- the **listTransportationOptions**, I used the AMAZON_PARTNERED_CARRIER
![{846ECEB8-5B5D-4B9A-BC40-7CFE61D6198D}](https://github.com/user-attachments/assets/9bf6e1dc-e087-4dbb-aaa1-a795be1b44f2)

I don't know what is going on with those, I don't know if it's because the placement option that I used in this case had amount zero

**Comment by puppsupr** [comment]
Hello,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

**Comment by HDPAlex** [comment]
Getting exactly the same error
Happening on and off
I am trying to confirm transportation option on a shipment provided via listTransportationOptions
{
	"carrier":{
		"name":"UPS",
		"alphaCode":"UPSN"
	},
	"quote":{
		"cost":{
			"amount":"9.9",
			"code":"USD"
		}
	},
	"preconditions": [ ],
	"shipmentId":"sh7fa336a1-6cb6-4ef8-b8fe-79aeddc9e8a6",
	"shippingMode":"GROUND_SMALL_PARCEL",
	"transportationOptionId":"toc8ede8a1-8601-4f52-a038-c18e509baa13",
	"shippingSolution":"AMAZON_PARTNERED_CARRIER"
},

Making a call to 
/inbound/fba/2024-03-20/inboundPlans/wf02a52e54-6998-44cc-8c1a-e591e6125f0c/transportationOptions/confirmation
passing data
{
	"transportationSelections": [
		{
			"contactInformation": {
				"email": "*******************",
				"name": "*******************",
				"phoneNumber": "*******************"
			},
			"shipmentId": "sh7fa336a1-6cb6-4ef8-b8fe-79aeddc9e8a6",
			"transportationOptionId": "toc8ede8a1-8601-4f52-a038-c18e509baa13"
		}
	]
}

After waiting for some time getting error back:
{
	"operationStatus": "FAILED",
	"operationId": "6703e679-3ac8-41c1-8562-97ea752b9381",
	"operation": "confirmTransportationOptions",
	"operationProblems": [
		{
			"severity": "ERROR",
			"code": "FBA_INB_0348",
			"details": "There's an input error with the resource 'sh7fa336a1-6cb6-4ef8-b8fe-79aeddc9e8a6'.",
			"message": "ERROR: Invalid transportation option ID that either does not belong to provided shipment ID or is not AVAILABLE was passed in."
		}
	]
}

**Comment by puppsupr** [comment]
Hello [HDPAlex](https://github.com/HDPAlex),
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

**Comment by AshwinPitroda** [comment]
I am also getting same error "Invalid transportation option ID that either does not belong to provided shipment ID or is not AVAILABLE was passed in".

Is there any solution for this error?

**Comment by puppsupr** [comment]
Hi @AshwinPitroda,
Can you please [open a support case](https://developer.amazonservices.com/support) with more details so that the team can check.

**Comment by sidiabale** [comment]
I had the same issue. I observed that the result from listTransportOptions has separate entries by shipmentId. Thus, you need to find the transportationOptionId matching each shipmentId or you'll get the reported error. Hope this helps.

**Comment by java-liupx** [comment]
I also encountered the same problem, here are my request parameters:
{
	"transportationSelections": [
		{
			"shipmentId": "shd7b9cbb1-0f94-47ee-949e-c16fda1776b4",
			"transportationOptionId": "toee5bd289-f83c-44e0-8012-39573efca377"
		},
		{
			"shipmentId": "shd7f8b326-f686-4963-a712-c82a5e284812",
			"transportationOptionId": "to0bf7dcf3-0bea-4021-a22e-8959dd1bed57"
		}
	]
}

I'm not sure how this problem arose and how it should be resolved?

**Comment by andremaytorena** [comment]
Was anyone able to solve this? I encountered the issue for 1 single shipment in the placement option so there's no way that it was incorrect, I re retrieve the transportation ID's and it gave me a different ID. Not too sure what could've happened.

**Comment by Prez5er** [comment]
Yes, i already solved a few months ago, but the problem not was the last endpoint, was the information and properties that were included on the payload of the previous steps, also could be the weight of the shipment, its somethig to consider

**Comment by emakunin** [comment]
Hello from 2026,
The issue is still here
