### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 listPackingOptions returns empty packingOptions

### ISSUE THREAD

**Issue by meareal** [amzn/selling-partner-api-models#4285]
After successfully executing CreateInboundPlan and GeneratePackingOptions, ListPackingOptions does not return packingOptions.

In other words, the ListPackingOptions calls returns 200 with an empty packingOptions.

CreateInboundPlan

```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans",
    "method": "POST",
    "body": {
        "destinationMarketplaces" : [ "ATVPDKIKX0DEX" ],
        "items" : [ {
          "expiration" : "2025-01-01",
          "labelOwner" : "SELLER",
          "manufacturingLotCode" : "manufacturingLotCode",
          "msku" : "5FFYV20000AD",
          "prepOwner" : "NONE",
          "quantity" : 10
        } ],
        "name" : "My inbound plan",
        "sourceAddress" : {
          "addressLine1" : "303 East Berry Street",
          "addressLine2" : "",
          "city" : "Middlebury",
          "companyName" : "Acme",
          "countryCode" : "US",
          "email" : "email@email.com",
          "name" : "name",
          "phoneNumber" : "1234567890",
          "postalCode" : "46540",
          "stateOrProvinceCode" : "IN"
        }
    }
}

RESPONSE:
{
    "operationId": "3135d65a-6028-43c7-80bd-27a415bc2398",
    "inboundPlanId": "wf34180d4f-29ec-47e9-98b8-9a08601de151"
}
```

GeneratePackingOptions

```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf5cb00bd2-eb85-4f71-83ae-93e55806b95f/packingOptions",
    "method": "POST"
}

RESPONSE:
{
  "operationId": "1525a93a-abab-418b-af9d-f5301fbb4c84"
}
```

ListPackingOptions

```
REQUEST:
{
    "uri": "https://sellingpartnerapi-na.amazon.com/inbound/fba/2024-03-20/inboundPlans/wf5cb00bd2-eb85-4f71-83ae-93e55806b95f/packingOptions",
    "method": "GET"
}
```
![image](https://github.com/user-attachments/assets/fc23f074-bbe5-4961-b136-988626bac9b5)

Note: I read issue [#4148](https://github.com/amzn/selling-partner-api-models/issues/4184) where johnkw mentions how often these calls fail, I tried submitting `ListPackingOptions` so many times and the response is always the same (empty)

Any suggestions?

Thanks

**Comment by mafge** [comment]
Hi @meareal,
thanks for reaching out!
Have you checked the [operation status](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20operationsoperationid) of `generatePackingOptions` operation? This is an asynchronous operation, so something might be wrong when generating the packing options.
Best,
Marc
Selling Partner Developer Services

**Comment by meareal** [comment]
Good morning @mafge 

I tried `GetInboundOperationStatus` (like you suggested) and got the following error

```
{
    "operationStatus": "FAILED",
    "operationId": "1b843a65-2ed4-4526-ae68-8fe93e40aaba",
    "operation": "generatePackingOptions",
    "operationProblems": [
        {
            "severity": "ERROR",
            "code": "BadRequest",
            "message": "ERROR: Operation GeneratePackingOptions cannot be processed because the inbound plan does not support packing options."
        }
    ]
}
```

And then found issue [4046](https://github.com/amzn/selling-partner-api-models/issues/4046) which is what I am following up on now to see this helps us, especially the posts on or after Aug 26th

**Comment by meareal** [comment]
@mafge 

If there was something wrong with `GeneratePackingOptions` I would get an error, correct? But I don't. I get the `operationId` instead so I am assuming `GeneratePackingOptions` worked.

I have tried different options for `labelOwner` and `prepOwner`  (`CreateInboundPlan`) and continue to get the same error message (posted earlier today) when I call `GetInboundOperationStatus`.

**Comment by mafge** [comment]
@meareal, your assumption is unfortunately not correct. You get an `operationId` in any case, this just means that the backend has accepted your request for further processing. You always have to check whether the operation was executed successfully afterwards (as the operation will be executed asynchronously).
Have you looked into the steps described in this [comment](https://github.com/amzn/selling-partner-api-models/issues/4046#issuecomment-2310787910)? It looks to me like you have to provide more information for the specific SKU(s) via Seller Central first.

**Comment by meareal** [comment]
Good morning. Thanks @mafge for the reply. I did check issue #4046 and especially the posts on Aug 26th. I can't find the items (in step 3) and the items I see (under Send to Amazon) I can't find the `updated prep instructions`. So I am stuck at the moment. Furthermore, it is not clear to me why I have to do this prep/configuration work in Seller Central first.

**Comment by mafge** [comment]
Hi @meareal,
I see. One suggestion: You could try to create the shipment via Seller Central (sometimes errors with your SKUs are easier to see in the UI), because the flow is essentially the same. If it works via the UI, then there is something wrong with the API and you would need to contact [developer support](https://developer.amazonservices.com/support).
