### ISSUE TITLE
Meaning of the Fulfillment-inbound-api-v2024-03-20 ListInbounPlans LastUpdateAt 

### ISSUE THREAD

**Issue by liuguoxiang9965** [amzn/selling-partner-api-models#4290]
Fulfillment-inbound-api-v2024-03-20 Whether the last updated time field (lastUpdatedAt) returned in each shipment plan in the API listInboundPlans list interface can represent:
After the shipment, boxes, goods and other related information under the shipment plan changes, the last update time field will also change. Please elaborate on the behavior involved in causing the change in the last update time field, such as: change in the status of the shipment;Can anyone help?

**Comment by liuguoxiang9965** [comment]
If I need to synchronize these data, can I incrementally obtain inboundPlan, shipments, boxes and other information through the last update time?If not, is there any other way to obtain this data incrementally?

**Comment by puppsupr** [comment]
Hi,
lastUpdatedAt will update whenever some change occurs to the inbound plan including changing the quantities, once shipment status gets updated, etc. Also we provide couple of [FBA Reports](https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba#fulfillment-by-amazon-fba-reports) where you can shipments data.

**Comment by liuguoxiang9965** [comment]
Now there is another problem: I found that the InboundPlan's LastUpdateAt does not effectively represent the most recent update time of the shipment
For example: The last update time of InboundPlan is 2024-09-09, but the most recent update time from the Amazon store is 2024-10-30
Corresponding interface to obtain InboundPlan details: FBA Fulfillment-0320 GetInboundPlan interface
Return data:
```
{
    "createdAt": "2024-08-30T05:18:53Z",
    "inboundPlanId": "wf02b5cdbd-281d-4e86-a90e-5683868689be",
    **"lastUpdatedAt": "2024-09-09T16:51:34Z",**
    "marketplaceIds": [
        "ATVPDKIKX0DER"
    ],
    "name": "",
    "packingOptions": [
        {
            "packingOptionId": "po00000000-0000-0000-0000-000000000000",
            "status": "ACCEPTED"
        }
    ],
    "placementOptions": [
        {
            "placementOptionId": "plac2a60e9-b134-4317-9962-5447c15646d8",
            "status": "ACCEPTED"
        }
    ],
    "shipments": [
        {
            "shipmentId": "sh48af4c05-630f-4029-97a2-44828cee4373",
            "status": "RECEIVING"
        },
        {
            "shipmentId": "shcd8cf986-1717-40a4-90f2-f471410a1922",
            "status": "CLOSED"
        }
    ],
    "sourceAddress": {
        "addressLine1": "BaiYunHuJie DaGang XiJie 36 hao A Dong 1 Lou 102 Shi",
        "city": "Guangzhou",
        "countryCode": "CN",
        "name": "US Rich Choices",
        "phoneNumber": "8613035791762",
        "postalCode": "510000",
        "stateOrProvinceCode": "Guangdong"
    },
    "status": "SHIPPED"
}'
```
Request header:``
headers={x-amz-apigw-id=OPFda4f4caf8e3b, Server=Server, Connection=keep-alive, x-amz-rid=BQQCV936SMCXR95XSZCD, Date=Mon,
11 Nov 2024 05: 52: 16 GMT, X-Amzn-Trace-Id=Root=1-67319b90-da4f4caf8e3b4b20, x-amzn-RateLimit-Limit=2.0, Strict-Transport-Security=max-age=47474747; includeSubDomains; preload, OkHttp-Received-Millis=1731304336717, OkHttp-Sent-Millis=1731304332535, x-amzn-RequestId=da4f4caf-8e3b-4b20-a85b-6d9561b470f1, Vary=Content-Type,Accept-Encoding,User-Agent, Content-Length=802, Content-Type=application/json
}
```
Screenshot of the background page:
![img_v3_02g7_dd9d1fa4-dfff-4e97-a98a-dda327a7901g](https://github.com/user-attachments/assets/bf67fcc2-b0f6-4665-8ef2-de0723341309)
Update time of background exported data:
![image](https://github.com/user-attachments/assets/b5846cf7-fdd1-45a3-8cf2-ff6d75b8cce7)
Why does this happen? @puppsupr

**Comment by liuguoxiang9965** [comment]
Background screenshot and exported file screenshot：
![img_v3_02g7_dd9d1fa4-dfff-4e97-a98a-dda327a7901g](https://github.com/user-attachments/assets/e7b2bb30-c9b5-4ce1-ac3f-67072b97d412)
![20241111-150945](https://github.com/user-attachments/assets/510815f4-bf82-4619-bab4-c7b4b642e46b)

**Comment by MeenaAmz** [comment]
@liuguoxiang9965 The update should be due to some related change in the inbound plan. Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can further look into the reason for update.

Thanks
Meena
Selling Partner Developer Services
