### ISSUE TITLE
GetShipment 

### ISSUE THREAD

**Issue by xyloneX** [amzn/selling-partner-api-models#4294]
```
{
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: Operation GetShipment cannot be processed, because shipment sh9612061e-307d-41bc-8437-0c00c0727b68 is not found in the confirmed placement option pl447af68f-28c4-47a2-9066-581f277f960f.",
      "details": ""
    }
  ]
}
```
The getShipment Operations does not have a placementOptionId parameter
Why is there such an error?

**Comment by xyloneX** [comment]
> ```
> {
>   "errors": [
>     {
>       "code": "BadRequest",
>       "message": "ERROR: Operation GetShipment cannot be processed, because shipment sh9612061e-307d-41bc-8437-0c00c0727b68 is not found in the confirmed placement option pl447af68f-28c4-47a2-9066-581f277f960f.",
>       "details": ""
>     }
>   ]
> }
> ```
> 
> getShipment 操作没有 placementOptionId 参数 为什么会出现这样的错误？

I think I know where the problem is. confirmPlacementOptions cannot get shipment information on other placementId.

**Comment by puppsupr** [comment]
Hi,
This has been fixed. Please try again if the generated options didn't expire. If they expired please try to generate the options again of they have not been confirmed.
