### ISSUE TITLE
No semantic errors reported in JSON feed results?

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4295]
Hello,
we have migrated part of our marketplaces to JSON feed, some are still XML. In all XML uploads we had certain % of errors, for example 

* "You may not change the brand name on this ASIN. Please use the brand name currently shown on the ASIN detail page"
* "The SKU data provided is different from what&apos;s already in the Amazon catalog."
* ...

But none of these are present in JSON feed, suddenly it has 100% success rate - it only ever reported syntax errors, which is extremely suspicious, so JSON feed does not report these at all? Or it does not even check them at all? Or is there alternative way to get to these errors? What is happening?

Amazon wants us to migrate to JSON feed but we will become blind to all these issues we still need to solve (or new ones that may appear in the future)

Thank you for help

**Comment by jawheral** [comment]
Hi @NoxArt,

The Listings API, either through the JSON_LISTINGS_FEED or the API operations, will run checks synchronously but also asynchronously. This means that when a listing is submitted, some checks including syntax checks and schema validation are executed and issues are returned immediately if present (synchronous part).Once the submission is past this level, there are other calculations and checks that are executed after the request (asynchronous part).
You can monitor your listings post-submission by either relying on the `getListingsItem` operation and including `issues` as part of the response or by subscribing to the `LISTINGS_ITEM_ISSUES_CHANGE`.

For example, you can find that the `Brand` has the property `editable`: `false` on the schema, this means you can't edit this field, and when edited, it will result in issues.

<img width="210" alt="Screenshot 2024-11-05 at 10 11 22" src="https://github.com/user-attachments/assets/98103383-106c-4bba-b1cc-c6b85c320a8e">

Best,
Jawher
Selling Partner Developer Services

**Comment by NoxArt** [comment]
Thank you very much, I'll check it out

**Comment by NoxArt** [comment]
I managed to get it working, though it only gives me sku and "ERROR" and no reason and no enforcement actions, so for every such event I still have to call getListingsItem? That's severely limits usefulness of the event and also will bring throttling issues

Also, I just tried to use getListingsItem on the pair of SKU-Marketplace sent by the Event and the listing info shows "issues" => NULL, "status" => "BUYABLE", "DISCOVERABLE" for multiple of them ... so I'm puzzled why is Amazon sending events of errored products through notification with WARNING/ERROR severity and then gives no issues through another API
(for example mrkt "A13V1IB3VIYZZH" / sku "3442" or "7768-PP18038"; or "A1805IZSGTT6HS" / sku "11586-tech2")

Can you please check it out?
Thank you

**Comment by jawheral** [comment]
Hi @NoxArt,

**Regarding the 1st point**: It is currently still needed to call `getListingsItem` to get the detailed list of issues. Is there a reason why you'd expect multiple issues at the same time causing throttling? You should make sure that you handle throttled requests and address known issues that might be happening on many Skus at the same time period. You might also prioritize addressing issues with a `Error` severity over a `Warning` serverity.

**Regarding the 2nd point**: It might be that the issues have been fixed between the time the event was received and the time you requested `getListingsItem`. 


Best,
Jawher
Selling Partner Developer Services

**Comment by NoxArt** [comment]
Thank you
Oh, I figured it out, you need to explicitly say you want issues included in the result when calling getListingsItem

Sorry
