### ISSUE TITLE
"Invalid character found in the request target" error when using Postman SP-API example

### ISSUE THREAD

**Issue by BeeBee234** [amzn/selling-partner-api-models#4297]
Hello,

I am getting an "Invalid character found in the request target" error when using the Postman SP-API example found here https://developer-docs.amazon.com/sp-api/docs/using-postman-for-selling-partner-api-models.

I can successfully acquire a LWA access token.  Here's my request (where "..." is substituted for the actual Atza token): 

https://sandbox.sellingpartnerapi-na.amazon.com/sellers/v1/marketplaceParticipations?x-amz-access-token=Atza|...&Accept=application/json

The full error response is as follows: 

<h1>HTTP Status 400 – Bad Request</h1>
    <hr class="line" />
    <p><b>Type</b> Exception Report</p>
    <p><b>Message</b> Invalid character found in the request target
        [&#47;sellers&#47;v1&#47;marketplaceParticipations?x-amz-access-token=Atza|...&amp;Accept=application&#47;json
        ]. The valid characters are defined in RFC 7230 and RFC 3986</p>
    <p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a
        client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
    </p>
    <p><b>Exception</b></p>
    <pre>java.lang.IllegalArgumentException: Invalid character found in the request target [&#47;sellers&#47;v1&#47;marketplaceParticipations?x-amz-access-token=Atza|...&amp;Accept=application&#47;json ]. The valid characters are defined in RFC 7230 and RFC 3986
	org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:497)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:492)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1698)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	java.lang.Thread.run(Thread.java:750)
	</pre>

Thanks!

**Comment by mafge** [comment]
Hi @BeeBee234,
thanks for reaching out!
`x-amz-access-token` and `Accept` (accept can also be omitted btw.) needs to be set as request headers and not as query parameters.
Best,
Marc
Selling Partner Developer Services

**Comment by BeeBee234** [comment]
That works!  Thanks for your swift reply.
