### ISSUE TITLE
The time value of the expense type returned by Finance API ListFinancialEventsByGroupId is empty

### ISSUE THREAD

**Issue by susan828** [amzn/selling-partner-api-models#4299]
Why does the Finance API ListFinancialEventsByGroupId return expense types without time, such as types like the following, which do not have time? This may cause me to miss these data when calculating based on time
FBAPerUnitFulfillmentFee
VineFee
FBARemovalFee
FBACustomerReturnPerUnitFee
FBAOverageFee
PaidServicesFee
FBAInboundConvenienceFee
InboundDefectFee
FBAStorageFee
FBADisposalFee
FBALongTermStorageFee

**Comment by jawheral** [comment]
Hi @susan828,

Thank you for the feedback.
I understand that `ServiceFeeEvent` financial events do not come with a `postedDate`. Have you considered using the recently released [Finances API v2024-06-19](https://developer-docs.amazon.com/sp-api/docs/finances-api-v2024-06-19-reference#listtransactions)?
The `listTransactions` operation response will include a `postedDate` attribute with every transaction. I recommend that you try this API and match the `ServiceFeeEvent`s to the transactions if needed.

I'm happy to learn more about your use case or any blockers faced.

I hope this helps!

Best,
Jawher
Selling Partner Developer Services
