### ISSUE TITLE
Ruby API client

### ISSUE THREAD

**Issue by ericcj** [amzn/selling-partner-api-models#43]
MWS usage from ruby is very popular https://rubygems.org/gems/peddler/ but migrating to SP-API is a large project.  Could you provide official authentication/authorization code like you did for Java/C#?

**Comment by skatkov** [comment]
+1 for ruby client, really need it!

**Comment by ulandj** [comment]
+1

**Comment by george-tigoris** [comment]
+1

**Comment by ericcj** [comment]
I published a rubygem of the codegen for each model with a minimal request signing client: https://github.com/ericcj/amz_sp_api

**Comment by iamricks** [comment]
+1

**Comment by ytsipun** [comment]
+1

**Comment by cduv** [comment]
+1

**Comment by ogonki-vetochki** [comment]
+1

**Comment by AitorUria** [comment]
+1

**Comment by kwent** [comment]
+1

**Comment by bpieck** [comment]
+1
