### ISSUE TITLE
Using the same SP API developer on different Seller accounts- Issue with ReportsID

### ISSUE THREAD

**Issue by Dikonia** [amzn/selling-partner-api-models#4301]
We have developed a private amazon seller application for one of our clients and we have followed the following steps as mentioned by https://github.com/chadsaun @chadsaun

For our SELLER_1 account we have also setup an app in "draft" status since it's a private app for our business.

I have now authorized SELLER_1 account to connect to Amazon's SP API on behalf of SELLER_2 account.

To do this, you need to "authorize your application to access a different selling partner account". The instructions can be found in Amazon's documentation under "[To self-authorize your application (seller application)](https://developer-docs.amazon.com/sp-api/docs/self-authorization#to-self-authorize-your-application-seller-application)"

The key here isn't to just authorize your app. In my case, this was already done a long time ago when I created the app for SELLER_1 to use the API. You need to click, at the bottom of the page, choose sign in to that account.

Here are my instructions:

Log into Seller Central
Menu → Apps and Services → Develop Apps
On the Action button for the app select the drop down menu and click on Authorize
Click the Authorize App button for the appropriate Marketplace
On the Authorize application page, at the bottom of the page, choose sign in to that account.
On the Seller Central sign-in page, sign in using the credentials for the selling partner account that you want your application to access.
On the Authorize application page, choose Authorize app to get a refresh token.
Once you have this refresh token, then all you need to do is use this refresh token whenever you want to call the API for SELLER_2 account. All the other credentials should stay the same as your SELLER_1.

The issue is that when we generate the ReportID for fetching the products list, it returns the same report ID for both SELLER_1 and SELLER_2 above. Due the the ReportID being the same, the report is generating the same products list for both the accounts which is incorrect. 

Can anyone please help with this. 

I read your comments in one of the answers and believe you might have answer for this as well @ShivikaK 

Looking forward to anyone's help on this.

Thanks

**Comment by Dikonia** [comment]
@chapmanjw @sungolivia @weilinggu @seanevan Can anyone help with this issue!!

**Comment by chrisskhoury** [comment]
Hello @Dikonia,

The flow you followed is correct for authorizing another seller, but to address the issue of receiving the same ReportID for both SELLER_1 and SELLER_2, we need to ensure that the API requests are correctly scoped to the respective seller accounts.

Please ensure the following steps:

1. **Check Refresh Tokens**: Confirm that the refresh tokens for SELLER_1 and SELLER_2 are different and correctly stored.
2. **Generate New Tokens**: If necessary, re-authorize the app for both seller accounts to get fresh tokens.
3. **Separate Requests**: Make sure that requests to generate reports are made separately for each seller account using their specific access tokens.
4. **Check the Request Headers**: Ensure that the `x-amz-access-token` headers are set correctly for each request.

If the issue persists, we will need to dive deeper and get more information about your requests. In such cases, please reach out to [Amazon Developer Support](https://developer.amazonservices.com/support) with detailed logs and request data for further debugging, as it is not recommended to share such information here.

Best regards,

Chris
Solution Architect
