### ISSUE TITLE
Fulfillment Inbound v2024-03-20 GenerateTransportationOptions not working on sandbox

### ISSUE THREAD

**Issue by manish-in-java** [amzn/selling-partner-api-models#4306]
According to the API model available from Github at github.com/amzn/selling-partner-api-models/blob/main/models/fulfillment-inbound-api-model/fulfillmentInbound_2024-03-20.json, we are supposed to send the following `GenerateTransportationOptions` request to the sandbox:

```
{
    "placementOptionId": "pl1234abcd-1234-abcd-5678-1234abcd5678",
    "shipmentTransportationConfigurations": [
        {
            "shipmentId": "sh1234abcd-1234-abcd-5678-1234abcd5678",
            "readyToShipWindow": {
                "start": "2024-01-01T00:00Z"
            },
            "contactInformation": {
                "name": "name",
                "phoneNumber": "1234567890",
                "email": "email@email.com"
            },
            "freightInformation": {
                "freightClass": "FC_50",
                "declaredValue": {
                    "code": "USD",
                    "amount": 500
                }
            },
            "pallets": [
                {
                    "stackability": "STACKABLE",
                    "weight": {
                        "unit": "KG",
                        "value": 5.5
                    },
                    "dimensions": {
                        "unitOfMeasurement": "CM",
                        "length": 3,
                        "width": 4,
                        "height": 5
                    },
                    "quantity": 2
                }
            ]
        }
    ]
}
```

However, this request always results in the following response from the sandbox:

```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Could not match input arguments",
            "details": ""
        }
    ]
}
```

How do we test this API?

**Comment by puppsupr** [comment]
Hello [manish-in-java](https://github.com/manish-in-java),
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

Thanks,
Selling Partner API Developer Services

**Comment by manish-in-java** [comment]
@puppsupr, can you clarify what additional information is required from me? I have provided all the information in the issue here.

For what it is worth, also see https://github.com/amzn/selling-partner-api-models/issues/4248, which is the same issue for a different API and that has been accepted. What is different about this issue?

**Comment by MeenaAmz** [comment]
@manish-in-java We do not require any further information from you. Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can track the issue and provide a resolution. All errors should be reported via support case so we can validate the request and provide an appropriate response.

Thanks
Meena
Selling Partner Developer Services
