### ISSUE TITLE
no replacement for get shipments ???!!!

### ISSUE THREAD

**Issue by nafberger** [amzn/selling-partner-api-models#4312]
amazon says that get shipments is going to be deprecated, how will we be able to get the shipments our clients make on seller central.

there seems to be no list shipments on the new inbound api..

i tried to go by list inbound plans, but IT DOES NOT give you any shipments, only when you call get inbound plan.

so a workflow would be like that,

call list inbound plans.
then for each call get plan
then for each get the shipment by calling get shipment.

that GROSSLY inefficient. what's going on?

**Comment by mafge** [comment]
Hi @nafberger,
thanks for reaching out!
`getShipments` operation will not be deprecated. I agree that the wording in the [documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference) is probably misleading, as people do not carefully enough read the first sentence of the warning. You can find the list of deprecated operations [here](https://developer-docs.amazon.com/sp-api/changelog/deprecation-reminders-november-6-2024).
Best,
Marc
Selling Partner Developer Services
