### ISSUE TITLE
SPD Options Not Generating in 'Pack Later' Workflow

### ISSUE THREAD

**Issue by Alvaromero** [amzn/selling-partner-api-models#4314]
I'm using the 'Pack Later' workflow (when the seller does not know the carton-level information upfront), but SPD options are not being generated. Could there be a reason for this?

**Comment by mafge** [comment]
Hi @Alvaromero,
thanks for reaching out!
SPD is not available when the carton-level information is unknown according to the [documentation](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#ship-inventory-into-amazons-fulfillment-network). 
Best,
Marc
Selling Partner Developer Services

**Comment by Alvaromero** [comment]
Hi @mafge, thank you for your response. I have a couple of questions:

First, is SPD also unavailable for NON-PARTNER?
Second, if SPD options are not available in this flow, why does the API offer placement options that include multiple shipments, implying that these shipments would need to be SPD?

**Comment by B3lg4r4th** [comment]
Also, the documentation and Seller Central pages state that it's only "temporarily", suggesting that it might come in the future. We would also love additional clarity on the topic.

**Comment by mafge** [comment]
@Alvaromero No, SPD is not available in any case. Placement option calculation depends on a lot of factors, so your assumption that multiple shipments equals SPD doesn't hold true.

@B3lg4r4th Unfortunately I don't have any more information when/if this will become available in the future. Please make sure to check our [changelog](https://developer-docs.amazon.com/sp-api/changelog) regularly. If it becomes available we will announce it there.
