### ISSUE TITLE
Missing CompanyName in /orders/v0/orders

### ISSUE THREAD

**Issue by psg1** [amzn/selling-partner-api-models#4315]
https://github.com/amzn/selling-partner-api-models/blob/1c23aa95cf8ca6c418e2bceaaef693c665b05900/models/orders-api-model/ordersV0.json#L3876

According to the API documentation here https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#address, the Address object should include the **CompanyName** field. However, when I make an API call to the endpoint `/orders/v0/orders`, the company name is not being returned. Could you clarify why the company name is missing in the reports segment `OrderReport\FulfillmentData\Address`?

The required data set is available by calling `/orders/v0/orders/{$orderId}/address`. However, this would require us to make unnecessary calls.

**Comment by jawheral** [comment]
Hi @psg1,

To have the `Buyer company name` returned in order reports, please note that the seller has to activate the attribute in the [column picker](https://sellercentral.amazon.com/order-reports-and-feeds/column-picker).

The company name is an optional field in Orders API so it is not returned for every order and is only returned when it was provided by the buyer. 
Is it for the same order that the `CompanyName` is not returned in [Address](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#address) but only returned using `/orders/v0/orders/{$orderId}/address`?
And on which attribute exactly do you get the company name from the `getOrderAddress` operation [response](https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#orderaddress), is it the `BuyerCompanyName` or `ShippingAddress. CompanyName`?

Best,
Jawher
Selling Partner Developer Services

**Comment by psg1** [comment]
Hi @jawheral,

The column picker only seems to apply to [https://sellercentral.amazon.de/order-reports-and-feeds/reports/allOrders](https://sellercentral.amazon.de/order-reports-and-feeds/reports/allOrders) - the report that we receive via the API call is in XML format.

It's about `CompanyName `- which can sometimes be important for shipping. The delivery address is displayed correctly in Seller Central, but the CompanyName is also missing on the Amazon generated invoice under delivery address.

I don't know if it is allowed to specify an order number or a report ID here, which serves as an example.

We know that this field is optional.

For the same order we receive in the `/orders/v0/orders` report:
```
<Message>
    <MessageID>4</MessageID>
    <OrderReport>
        <AmazonOrderID>303-7563330-...</AmazonOrderID>
        <AmazonSessionID>303-7563330-...</</AmazonSessionID>
        <OrderDate>2024-10-31T10:37:32+00:00</OrderDate>
        <OrderPostedDate>2024-10-31T10:37:32+00:00</OrderPostedDate>
        <MarketplaceName>Amazon.de</MarketplaceName>
        <BillingData>
            <BuyerEmailAddress>...</BuyerEmailAddress>
            <BuyerName>...</BuyerName>
            <BuyerPhoneNumber>...</BuyerPhoneNumber>
            <Address>
                <Name>...</Name>
                <AddressFieldOne>...</AddressFieldOne>
                <City>...</City>
                <PostalCode>...</PostalCode>
                <CountryCode>...</CountryCode>
            </Address>
        </BillingData>
        <FulfillmentData>
            <FulfillmentMethod>Ship</FulfillmentMethod>
            <FulfillmentServiceLevel>Standard</FulfillmentServiceLevel>
            <Address>
########## CompanyName is expected here ##########
                <Name>...</Name>
                <AddressFieldOne>...</AddressFieldOne>
                <City>...</City>
                <PostalCode>...</PostalCode>
                <CountryCode>...</CountryCode>
                <PhoneNumber>...</PhoneNumber>
            </Address>
        </FulfillmentData>
        <IsBusinessOrder>true</IsBusinessOrder>
....
```

And with the call `/orders/v0/orders/303-7563330-.../address`
```
  ["payload"]=>
  array(4) {
    ...
    ["AmazonOrderId"]=>
    string(19) "303-7563330-..."
    ["ShippingAddress"]=>
    array(7) {
########## This Part is needed ##########
      ["CompanyName"]=>
      string(29) "..."
#########################################
      ["AddressLine1"]=>
      string(27) "..."
      ["PostalCode"]=>
      string(5) "..."
      ["City"]=>
      string(13) "..."
      ["CountryCode"]=>
      string(2) "..."
      ["AddressType"]=>
      string(10) "..."
      ["Name"]=>
      string(13) "..."
    }
    ["BuyerCompanyName"]=>
    string(10) "..."
  }
}
```

**Comment by psg1** [comment]
Hi @jawheral,

we used a self-authorize private application. We use `/auth/o2/token`

In the [GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING](https://developer-docs.amazon.com/sp-api/docs/report-type-values-order#unshipped-orders-report) there is also no company name included - but according to the documentation it shouldn't be.

**Comment by jawheral** [comment]
Hi @psg1,

For you to retrieve all the details when using `/orders/v0/orders`, you still need to create an RDT (check the Tokens API use case guide in my previous comment). This might help you avoid the additional call to `/orders/v0/orders/{$orderId}/address`. Feel free to try it and let me know if this works for you.

With [GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING](https://developer-docs.amazon.com/sp-api/docs/report-type-values-order#unshipped-orders-report), if you activate the Buyer Company Name from the oder [column picker](https://sellercentral.amazon.com/order-reports-and-feeds/column-picker), it should be included in the report.

Best,
Jawher
Selling Partner Developer Services

**Comment by psg1** [comment]
Hi @jawheral,

I have to apologize. 

I am looking for the `CompanyName` in the report [GET_ORDER_REPORT_DATA_INVOICING](https://developer-docs.amazon.com/sp-api/docs/report-type-values-order#scheduled-xml-order-report-invoicing)
under `FulfillmentData\Address`

If you do not plan to keep this field here, you can close the issue.

**Comment by jawheral** [comment]
Hi @psg1,

Could you elaborate on your use case? Is your goal to handle Shipping or Invoice creation?
There are multiple ways to get the buyer company name, from other reports as well as from Orders API as previously explained.
For reports you can activate the `Buyer company name` column and the field will be available in your flat file reports downloaded through SP-API as well, such as [GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING](https://developer-docs.amazon.com/sp-api/docs/report-type-values-order#unshipped-orders-report) for shipping or [GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING](https://developer-docs.amazon.com/sp-api/docs/report-type-values-order#requested-or-scheduled-flat-file-order-report-invoicing) for invoicing
.
If you are trying to create invoices for the seller and the seller has VCS enabled, you can also get the [VIDR](https://developer-docs.amazon.com/sp-api/docs/report-type-values-invoice-data#xml-vat-invoice-data-report-vidr) reports, which would also include the data you are looking for.

I'm eager to learn more about your use case so I can better guide you.

Best,
Jawher

**Comment by psg1** [comment]
Hi @jawheral,

thanks for your support.

We currently only use `GET_ORDER_REPORT_DATA_INVOICING` for processing, as all the necessary data for the purchase process is available.

With the exception of the CompanyName under the `FulfillmentData\Address`, which is sometimes missing for shipping.

This automatically generated report from Amazon gives us the buyer's address for billing and the shipping address. All items are also included in this report. Now we need to add another report because we are only missing the one field `CompanyName` for the shipping address.

**Comment by jawheral** [comment]
Hi @psg1,

While we cannot guarantee any update to either `GET_ORDER_REPORT_DATA_INVOICING` or `GET_ORDER_REPORT_DATA_SHIPPING`, I will still check with our internal teams why the `companyName` is missing from these reports.
Due to this data being available through the Orders API or other reports, a change in this regard could either be delayed or not considered. 

Thank you for your feedback. I'm now closing this issue

Best,
Jawher
Selling Partner Developer
