### ISSUE TITLE
[BUG] [SP-API] [Issue] Brand Analytics Search Query Performance Report Missing from SP-API

### ISSUE THREAD

**Issue by nrcjea001** [amzn/selling-partner-api-models#432]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

The GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT (detailed [here](https://developer-docs.amazon.com/sp-api/docs/report-type-values#brand-analytics-reports)) corresponds to the top search terms report found in seller central (discussed [here](https://www.youtube.com/watch?v=HH304vJ_pOg)). However, there is also a search query performance report found in seller central (discussed [here](https://www.youtube.com/watch?v=GCY82kueAIw)), not otherwise found in SP-API.

The feature request is to add the search query performance report in SP-API and in the doc have the top search term report correspond to GET_BRAND_ANALYTICS_TOP_SEARCH_TERMS_REPORT and the search query performance report correspond to GET_BRAND_ANALYTICS_SEARCH_QUERY_PERFORMANCE_REPORT

**Comment by kmander** [comment]
I understand from conversations with Amazon employees that this will be added "this year". 

It's at least helpful to know it's on the roadmap and there's an intention to make the data more available.

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by tspicer** [comment]
This report has been released. We can confirm the update as we have released support these reports as of Friday 2025-2-28. You can read more here:
https://developer-docs.amazon.com/sp-api/changelog/update-added-new-search-query-performance-and-search-catalog-performance-analytics-report-types

**Comment by koradiyayash26** [comment]
Does it work when we want to get competitor data?
