### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 getShipment

### ISSUE THREAD

**Issue by daiqi77777** [amzn/selling-partner-api-models#4323]
The Fulfillment Inbound API v2024-03-20 getShipment method often has a call frequency limit. Can you provide a getShipments method to get all Shipment information based on inboundPlanId? thanks

**Comment by mafge** [comment]
Hi @daiqi77777,
thanks for reaching out!
Please have a look at [getShipments](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#get-fbainboundv0shipments) operation from v0 API. This could help you resolving your issues with rate limits.
Best,
Marc
Selling Partner Developer Services

**Comment by daiqi77777** [comment]
> Hi @daiqi77777, thanks for reaching out! Please have a look at [getShipments](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#get-fbainboundv0shipments) operation from v0 API. This could help you resolving your issues with rate limits. Best, Marc Selling Partner Developer Services
no!!!   i said Fulfillment Inbound API v2024-03-20

**Comment by daviddecorso** [comment]
Just saw this, #4339 may be related.
