### ISSUE TITLE
 How to get the delivery address of the shipment

### ISSUE THREAD

**Issue by Ironkyy** [amzn/selling-partner-api-models#4324]
I want to get the destination of the shipment based on the ID of FBASHIPMENT. Is there an interface I can use?

**Comment by MeenaAmz** [comment]
[getShipment](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#getshipment) provides the destination address of the fulfillment center when you pass in the inboundPlanId and shipmentId. You could also see the same information on Seller Central UI, Send to Amazon interface.

Thanks
Meena
Selling Partner Developer Services

**Comment by Ironkyy** [comment]
I am using an old version of the API and there is no inplanId

**Comment by Ironkyy** [comment]
Are there other ways to obtain destination information?

**Comment by Ironkyy** [comment]
@MeenaAmz  
Is there any other interface method that can be obtained?

**Comment by Ironkyy** [comment]
Now I can only get the destinationFulfillmentCenterId. I want to get the detailed address of the warehouse. Is there any API that can achieve this?

**Comment by Ironkyy** [comment]
Now I can only get the destinationFulfillmentCenterId. I want to get the detailed address of the warehouse. Is there any API that can achieve this?

**Comment by Ironkyy** [comment]
@MeenaAmz  Are there any API methods to achieve this?
