### ISSUE TITLE
SP-API Amazon Reports Brand analytics

### ISSUE THREAD

**Issue by pbi-sheila** [amzn/selling-partner-api-models#4326]
Hi! I'm struggling with brand analytics reports from SP-API Amazon. Everything goes well with the others reports, but when y try to get for example: "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT". I obtained a code 202, I obtained the reportid but the status is fatal, so something is wrong. I verified my credentials, the payload is exactly the same as the model on github, I have the brand analytics role, etc.. When I ask for help in amazon, the problem are the dates and they close my case. This was their answer:

Greetings from Amazon, My name is xxx, from the Selling Partner API Developer Support team. For report 60203020041 the start date and end dates entered are: Start Date 2024-11-14 17:56:15 UTCEnd Date 2024-11-14 17:56:15 UTC
 
    payload = {
    "reportType": "GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT",
    "marketplaceIds": ["A2EUQ1WTGCTBG2"],
    "reportSpecification": {
        "reportOptions": {
            "reportPeriod": "WEEK"
        },
        "dataStartTime": "2024-11-03",
        "dataEndTime": "2024-11-09"
    }
}
    

And my dates are other. I tried almost everything and I can't solve this, and Amazon is not helpful
Thanks so much

**Comment by mafge** [comment]
Hi @pbi-sheila,
thanks for reaching out!
The attributes `dataStartTime` and `dataEndTime` must be [ISO8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) compliant, this means in your case you have to add a time to the values you submit (e.g. `2019-12-10T20:11:24.000Z`).
Best,
Marc
Selling Partner Developer Services

**Comment by pbi-sheila** [comment]
Hi! Thank you for answering but i tried with that before and it doesn't work, the weird thing is that all the others reports for vendors works perfectly,  i have this problem with all the reports from brand analytics. I don't know, but i have the feeling that maybe with vendor doesn't work

**Comment by B3lg4r4th** [comment]
The start and end times for the "WEEK" option must be both Sundays, in attached code it's Sunday and Saturday, for "MONTH" it will be 2024-11-01 and 2024-11-30 respectively

**Comment by pbi-sheila** [comment]
Hi! Thanks for answering  :) 
November 3, 2024, is a Sunday, and the 9th is a Saturday. I'll try using the month, but I think you can consult Brand Analytics reports for 14-day periods

**Comment by B3lg4r4th** [comment]
I know it's Saturday - try using the 10th in your request, so it's Sunday to Sunday :)

**Comment by pbi-sheila** [comment]
Thanks!! The documentation says that the periods need to be from Sunday to Saturday. I tried using Sunday to Sunday, but I still have the same issue. Do you have access to Vendor or Selling Partner?"

**Comment by B3lg4r4th** [comment]
I see, sorry to hear about your issues :( hopefully the monthly one works for you! I had success requesting a report with the following options:
`{
reportOptions: {
                    reportPeriod: 'MONTH',
                },
                dataStartTime: '2024-10-01T00:00:00.000Z',
                dataEndTime: '2024-10-31T00:00:00.000Z',
                marketplaceIds: ['ATVPDKIKX0DER']
                }`

**Comment by pbi-sheila** [comment]
Hi! Thank you so much for your answers, i tried with your solution but it doesnt work.  i think that the problem are the brand anaytics reports for vendors, in fact i found the same issue in other forum without solutions

**Comment by pbi-sheila** [comment]
Yes :( normally i can get the reportid but with an error. This is my response {'error': {'reportId': '60323020042'}}. 
Im using this url: https://sellingpartnerapi-na.amazon.com/reports/2021-06-30/reports and i also tried using this, (just in case) https://sellingpartnerapi-na.amazon.com/reports/sellingPartnerMarketBasketAnalysisReport

**Comment by mafge** [comment]
@pbi-sheila Can you please open a new ticket with developer support/reopen the old one and post the case id here? I will follow up internally, there is definitely something wrong here.
