### ISSUE TITLE
[Orders API v0: confirmShipment]:PackageDetail: why is trackingNumber required

### ISSUE THREAD

**Issue by maximehinnekens** [amzn/selling-partner-api-models#4329]
Hi,

Below is the model for PackageDetail. It shows that trackingNumber is required. Why is it required here when it is not always required in the EU stores + order feeds do not give errors in the processing reports when used according to the rules on Tracking. I was planning to migrate to this operation to confirm the shipments but now we can't because we also have orders that are shipping with untracked shipping methods.

Is this a known inconsistency?

>     "PackageDetail": {
      "type": "object",
      "description": "Properties of packages",
      "required": [
        "packageReferenceId",
        "carrierCode",
        "trackingNumber",
        "shipDate",
        "orderItems"
      ],
      "properties": {
        "packageReferenceId": {
          "$ref": "#/definitions/PackageReferenceId"
        },
        "carrierCode": {
          "type": "string",
          "description": "Identifies the carrier that will deliver the package. This field is required for all marketplaces. For more information, refer to the [`CarrierCode` announcement](https://developer-docs.amazon.com/sp-api/changelog/carriercode-value-required-in-shipment-confirmations-for-br-mx-ca-sg-au-in-jp-marketplaces)."
        },
        "carrierName": {
          "type": "string",
          "description": "Carrier Name that will deliver the package. Required when `carrierCode` is \"Others\" "
        },
        "shippingMethod": {
          "type": "string",
          "description": "Ship method to be used for shipping the order."
        },
        "trackingNumber": {
          "type": "string",
          "description": "The tracking number used to obtain tracking and delivery information."
        },
        "shipDate": {
          "type": "string",
          "description": "The shipping date for the package. Must be in <a href='https://developer-docs.amazon.com/sp-api/docs/iso-8601'>ISO 8601</a> date/time format.",
          "format": "date-time"
        },
        "shipFromSupplySourceId": {
          "type": "string",
          "description": "The unique identifier for the supply source."
        },
        "orderItems": {
          "description": "The list of order items and quantities to be updated.",
          "$ref": "#/definitions/ConfirmShipmentOrderItemsList"
        }
      }
    },

**Comment by chrisskhoury** [comment]
Hello @maximehinnekens,

If you buy shipments using Amazon Shipment Services such as [Merchant Fulfillment API](https://developer-docs.amazon.com/sp-api/docs/merchant-fulfillment-api-v0-use-case-guide) or the [Shipping V2 API](https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference), then the confirmShipment operation with the trackingId is not required. On the other hand, if you opt in to buying shipments through different means, it is possible, but you will need to share with Amazon the trackingId via the confirmShipment.

The confirmShipment operation supports all use cases that were supported in the Order Fulfillment Feeds, including supporting multiple tracking IDs per order. To submit multiple package tracking IDs, you will need to send multiple requests with the same order ID but different package reference IDs.

Hope this clarifies your question! :)

Best,
Chris - Solution Architect

**Comment by nicolasheady** [comment]
@maximehinnekens @chrisskhoury I would like to see this capability in confirmShipment too.
