### ISSUE TITLE
Inconsistent Data in GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA Reports

### ISSUE THREAD

**Issue by skuio** [amzn/selling-partner-api-models#4333]
We are experiencing inconsistent data when generating GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA reports using the Amazon Selling Partner API. When requesting reports for the same date range at different times, the number of records returned varies significantly.

Despite following Amazon’s recommendation to wait 72 hours after the end date before requesting the report, the issue persists. This inconsistency impacts our ability to accurately analyze our fulfillment and removal activities.

**Steps to Reproduce:**
1. Request a GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA report for a specific date range using the Selling Partner API.
2. Wait for the report to be generated and note the number of records returned.
3. After a period of time (e.g., several days or weeks), request a new report for the exact same date range.
4. Compare the number of records between the two reports.

**Expected Behavior:**
- The reports generated for the same date range should consistently return the same number of records, assuming they are requested after the recommended 72-hour waiting period.

**Actual Behavior:**
- Reports generated at different times for the same date range return different numbers of records.

Examples:

We have documented several instances of this inconsistency in the following spreadsheet:

https://docs.google.com/spreadsheets/d/1-fvA8_jNHHMwS1VkGuV4dVepkteeBsQPHItzKJEtBtw/edit?gid=0#gid=0

**Additional Information:**
- 	We have verified that the API requests and parameters are correct and consistent across all report generations.
- 	Cross-checked the data returned with our internal records to confirm discrepancies.
- 	Waiting longer than 72 hours does not resolve the inconsistency.

**Questions:**
- Clarification on Report Generation Timing: Is there an updated guideline on how long we should wait after the end date to ensure all data is included in the report?
- Data Consistency Verification: Can you investigate why reports generated at different times for the same date range are returning different numbers of records?
- Resolution Steps: Are there any steps we can take to ensure that our reports consistently return complete and accurate data?

**Impact:**

This issue affects our inventory management and operational planning, as we rely heavily on these reports for accurate data analysis.

**Request:**

We kindly request your assistance in investigating this matter to help us resolve the data inconsistency issue.

**Comment by mafge** [comment]
@skuio No worries, I am able to open it now. From what I can see this is a more complex matter unfortunately. Not sure where you got the information with the 72 hours from, but I have a hard time to believe this holds true for all reports. The problem here is most likely that there is no guaranteed time until all updates have been properly reflected throughout Amazons backend. I'd like to ask you to open a ticket with [developer support ](https://developer.amazonservices.com/support) if you haven't done that so far, and ask for guidance on that matter. Thanks for raising the issue here though!

**Comment by skuio** [comment]
Yes I did raise it and got a first reply about the marketplace ids not matching, so resubmitted with the matching marketplace ids (and same incorrect results).

"No guaranteed time" is pretty problematic and deserves some attention from high-level Amazon systems architects don't you think?
