### ISSUE TITLE
[Fulfillment Inbound API v2024-03-20] Issues Migrating from `v0` to `v2024-03-20` for Shipment Retrieval

### ISSUE THREAD

**Issue by jwleePerixx** [amzn/selling-partner-api-models#4337]
## Description  
I’m currently migrating from `v0` to `v2024-03-20` and encountering multiple challenges with shipment-related APIs:  

### 1. Fetching Shipments in a Time Range  
In `v0`, I could fetch shipments updated within a specific time range using the `get_shipments` request. However, in `v2024-03-20`, it seems I need to first fetch all `inboundPlanId` and `shipmentId`, then filter them manually to find shipments within a time range.  

**Question:**  
Is there an alternative way in `v2024-03-20` to directly retrieve shipments within a specified time range without requiring this additional filtering?  

### 2. Missing Tracking Details in `get_shipment` Response  
When calling the `get_shipment` API in `v2024-03-20` for a shipment that has already been shipped, the response does not include `tracking_details`. This behavior is inconsistent and was not an issue in `v0`.  

**Question:**  
Why is this information missing, and how can I ensure `tracking_details` is included in the response for shipped items?  

### 3. Error with `GetInboundPlan`  
While using `GetInboundPlan`, I encountered the following error:  
**ERROR: GetInboundPlan is not supported for the cross border Amazon Global Logistics program.**

**Question:**  
Why does this error occur?  

## Feedback  
The new API design feels unnecessarily complicated compared to `v0`. Tasks that were straightforward now require additional steps or workarounds, which increases the complexity of integration.  

---

I’d appreciate any clarification or guidance on these issues.  

Thank you!

**Comment by puppsupr** [comment]
Hi,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

If you already have a case opened can you please provide me the case numbers ?
