### ISSUE TITLE
"Upcoming Updates to your Amazon Services API Access" - what API do I need to call successfully?

### ISSUE THREAD

**Issue by BeeBee234** [amzn/selling-partner-api-models#4338]
Howdy,

Our application is currently in the development stage.  We recently received an email warning with the subject line "Upcoming Updates to your Amazon Services API Access" that said "your account has been dormant for at least 60 days, and you must make a successful API call using an application within your Developer account before ... .  If you do not complete this action by the provided date, your account will lose access to the Amazon Services API.". 

With your assistance I was able to successfully call the marketplaceParticipations api using Postman.  

However, we recently received another email saying that our account is still dormant.  Is there a specific api that I need to call to make my account not dormant?  Or do I need to reach out to the sender of the email with response details?  Or something else?

Thanks!

**Comment by BeeBee234** [comment]
The final response from Amazon support was canned and basically said that if you still have access after the deadline then you made the correct API call.  

It appears we still have access.  

FYI, we received two more warning emails about our "dormant" status even after we made a successful API call.

Is anyone driving the bus?

**Comment by weilinggu** [comment]
@BeeBee234 

[Developer support](https://developer.amazonservices.com/support) would be the right place to check how to resolve your dormant account status.

In addition, check the [Permissions and credentials](https://developer-docs.amazon.com/sp-api/docs/resolving-400-errors#permissions-and-credentials) section in the documentation to see if that helps with your situation.

Thanks,
Weiling
Selling Partner API Developer Services
