### ISSUE TITLE
Need an updated version of the v0 getShipments API.

### ISSUE THREAD

**Issue by daviddecorso** [amzn/selling-partner-api-models#4339]
The v0 getShipments is almost completely useless since it only returns the FBA ID as an identifier on shipments and (unless I am misunderstanding something) you cannot use that to get the inbound plan or shipment objects from the v2024 API. If I wanted to, for example, cancel a shipment or change some details about it from the list I've been returned from getShipments v0 I just can't do that. For most operations you need the new shipment id AND inboundPlanId. It's basically a read-only list of shipment names and statuses at this point.

The only way I currently see to get all of someone's working shipments is to
1. Get all inbound plans
2. For each inbound plan call getShipment on the shipment ids listed in the plans
3. For each of those you may still need an additional call to get all of the items if you need those as well.

Calling these APIs in tandem takes like 30+ seconds depending on the number of plans/shipments and is subject to rate limiting.

It's fine if I need to call getShipment and/or listShipmentItems to get detailed information about a shipment, but there really needs to be a way to get a summary of all of a user's shipments, either via an updated version of getShipments that returns the relevant ids (shipmentId and inboundPlanId), or by including summary information in the inbound plan.

**Comment by puppsupr** [comment]
Hi,
As you pointed out, currently using the new FBA Inbound v2024 APIs, you need to call [listInboundPlans](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplans) to get a list of all the inbound plans based on creation/updated plan, then [getInboundPlan](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#getinboundplan) to get the associated shipment IDs. Then do a [listShipmentItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listshipmentitems). You can also use [getShipments](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipments), [getShipmentItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitems) or [getShipmentItemsByShipmentId](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitemsbyshipmentid) v0 operations which will not deprecate.

You can also use [FBA reports](https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba) for the same.

**Comment by asd6979448** [comment]
> Hi, As you pointed out, currently using the new FBA Inbound v2024 APIs, you need to call [listInboundPlans](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listinboundplans) to get a list of all the inbound plans based on creation/updated plan, then [getInboundPlan](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#getinboundplan) to get the associated shipment IDs. Then do a [listShipmentItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listshipmentitems). You can also use [getShipments](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipments), [getShipmentItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitems) or [getShipmentItemsByShipmentId](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitemsbyshipmentid) v0 operations which will not deprecate.
> 
> You can also use [FBA reports](https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba) for the same.
> 
> Thanks for the feedback on the new APIs. We will take it noted to improve.

Hello, can this batch getshipments include the content of shipmentId such as sh91808591-5682-49fb-a50e-dd653cbb8a20?

**Comment by puppsupr** [comment]
Hi [asd6979448](https://github.com/asd6979448),
The shipment id in [getShipments](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipments) corresponds to the shipment confirmation id in v2024 [getShipment](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#getshipment) operation

**Comment by lucasrossell** [comment]
This really needs to be fixed.
