### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 how to estimate small parcel partnered shipment

### ISSUE THREAD

**Issue by nafberger** [amzn/selling-partner-api-models#4340]
its unclear how to get an estimate for a small parcel fba shipment using an amazon partnered carrier. since you can only provide dimensions in a pallet context. so how is this done for small parcel. interestingly you get an estimate but how can it be accurate when the shipper does not have the dimensions and weight

**Comment by puppsupr** [comment]
Hi,
If you want to send small parcel no need to provide the pallet information in [generateTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#generatetransportationoptions), then [listTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listtransportationoptions) and choose the transportationOptionId with shippingMode as one of the [small parcel options ](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#shippingconfiguration)and shippingSolution as AMAZON_PARTNERED_CARRIER.
