### ISSUE TITLE
The Fulfillment Inbound API v2024-03-20 European Station, creates shipment, inconsistent warehouse code bug

### ISSUE THREAD

**Issue by susan828** [amzn/selling-partner-api-models#4341]
The Fulfillment Inbound API v2024-03-20 is mainly for the European site. Occasionally, when creating shipments, it is found that the shipping address warehouse in the shipment list is DTM2. When clicking on the purchase item list details, it is found that the delivery address warehouse has changed to MHG9. When will this bug be resolved? Similar to the following figure:
![33333](https://github.com/user-attachments/assets/bd43aa9b-3e4b-410f-9354-fda772a47374)
![444444](https://github.com/user-attachments/assets/aacacf63-bc09-4c93-8321-312ac0106374)

**Comment by susan828** [comment]
Yes, it has been checked. This phenomenon only occurs occasionally, and after deleting the shipment, calling the same parameters again will not cause this phenomenon

**Comment by puppsupr** [comment]
Thanks, in order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

**Comment by he0212** [comment]
I met this issue too. Have you get any useful reply?

**Comment by puppsupr** [comment]
[susan828](https://github.com/susan828), [he0212](https://github.com/he0212) if you have raised the cases, can you please provide me the case ids ?

**Comment by susan828** [comment]
> [susan828](https://github.com/susan828)，[he0212](https://github.com/he0212)如果您提出了这些案件，能否向我提供案件编号？

What does this case ID represent? Is it the workflow ID when calling the API interface ?

**Comment by puppsupr** [comment]
I mean the Developer support case IDs.

**Comment by bitdan** [comment]
> I mean the Developer support case IDs.我指的是开发人员支持案例 ID。

The same problem is now happening. The shipment list is DTM2, and the one I see in detail is KSF7. Similar shipments include FBA15K7LWRK7, FBA15K7LPNF0, FBA15K7N24L8

![Image](https://github.com/user-attachments/assets/864a22df-8433-4340-8251-1946c6e01d69)

![Image](https://github.com/user-attachments/assets/b3cb9fab-b778-4c21-8cc8-4f6a87688fdf),
