### ISSUE TITLE
Get the full listing of my account:

### ISSUE THREAD

**Issue by JesusR25** [amzn/selling-partner-api-models#4343]
Hello, I have a question: Is there any way to get the full listing of my account?
Currently, I use the following URL and get some items:

https://sellingpartnerapi-na.amazon.com/listings/2021-08-01/items/{sellerID}/

This gives me a 'nextToken', but when I use it, I receive the same items and a different 'nextToken'. Why is this happening? Is this not possible?

**Comment by jawheral** [comment]
Hi @JesusR25,

I have tried the API and can confirm the bug. I will raise the issue to our internal teams and will let you know as soon as it is fixed.

In the meantime, please check our [Inventory Reports](https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory#all-listings-report) to get the full list of your listings.

Thank you for your understanding!

Best,
Jawher
Selling Partner Developer Services

**Comment by jawheral** [comment]
Hi @JesusR25,

Please make sure you are using `pageToken` as a parameter instead of `nextToken`. This should resolve the issue.

Best,
Jawher
Selling Partner Developer Services

**Comment by JesusR25** [comment]
Done, it worked for me! That was the problem, thank you so much, really!
