### ISSUE TITLE
Listing details

### ISSUE THREAD

**Issue by JesusR25** [amzn/selling-partner-api-models#4347]
Hello, I have a few questions about the API. I'm a bit new, so I would really appreciate any help!

1. Is there any way to get the FBM and FMA stock?
2. How can I get the status of my listings? That is, active, inactive, etc.

The /listing endpoint does not return the data mentioned above.
I am trying to retrieve my listing and save it in my database.

**Comment by JesusR25** [comment]
HI, this is one example of summary:

"summaries": [
    {
      "marketplaceId": "A1AM78C64UM0Y8",
      "asin": "B07CJ51XR1",
      "productType": "SAFETY_GLASSES",
      "conditionType": "new_new",
      "status": [
        "BUYABLE",
        "DISCOVERABLE"
      ],
      "fnSku": "example",
      "itemName": "title",
      "createdDate": "2022-01-20T00:10:46.787Z",
      "lastUpdatedDate": "2024-11-19T23:46:37.156Z",
      "mainImage": {
        "link": "https://m.media-amazon.com/images/I/21R4JxDkraL.jpg",
        "height": 160,
        "width": 160
      }
    }
  ],
  
  There is a status attribute, but it doesn't specify whether my listing is active, inactive, etc. I'm not sure if I'm mistaken.

**Comment by jawheral** [comment]
Hi @JesusR25,

Inventory reports are the right way to get data on active/inactive listings. For example:
- [Active Listings Report](https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory#active-listings-report)
- [Open Listings](https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory#open-listings-report)
- [Inactive Listings](https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory#inactive-listings-report)

Best,
Jawher
Selling Partner Developer Services

**Comment by JesusR25** [comment]
Oh, thank you very much for the response @jawheral , I will give it a try!
One last question, is there any notification that tells me when this type of status changes? That is, a notification that detects the change, let's say, from active to inactive?

**Comment by jawheral** [comment]
Hi @JesusR25,

You can read more on what each of the previously mentioned reports mean and will include [here](https://sellercentral.amazon.com/help/hub/reference/G561) on Seller Central.

The status of the Listings (Buyable, Discoverable) and whether there are issues can help you find out whether a listing is active or not. For example, a listing with status `Buyable` is an active listing. A listing with suppression issues might be an inactive listing.

You can receive notifications on the status change of a listing and also the issues changes:
- [LISTINGS_ITEM_ISSUES_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notification-type-values#listings_item_issues_change)
- [LISTINGS_ITEM_STATUS_CHANGE](https://developer-docs.amazon.com/sp-api/docs/notification-type-values#listings_item_status_change)

Best,
Jawher
Selling Partner Developer Services

**Comment by JesusR25** [comment]
Oh, I understand now, I should follow those status, got it, thank you so much @jawheral !
