### ISSUE TITLE
Fulfillment Inbound API v2024-03-20  setPackingInformation  get Error response

### ISSUE THREAD

**Issue by collery** [amzn/selling-partner-api-models#4364]
hello ,we are update old api v0 to v2024-03-20, and we use **Tutorial: Creating a shipment when the seller does not know the carton level information up-front**, but we get error when  **Provide box content information**

first, we create a plan  and get 2 shipments,  wiht sku1  quantity 5 ,sku 2 quantity 4. but when i setPackingInformation  like this 
`
{
  "packageGroupings": [
    {
      "boxes": [
        {
          "contentInformationSource": "BOX_CONTENT_PROVIDED",
          "dimensions": {
            "height": "31",
            "length": "41",
            "unitOfMeasurement": "CM",
            "width": "10"
          },
          "quantity": "1",
          "weight": {
            "unit": "LB",
            "value": "10"
          },
           "items": [
            {
              "labelOwner": "NONE",
              "msku": "qtest-1212",
              "prepOwner": "NONE",
              "quantity": "5",
              "expiration": "6462-07-27"
            }
          ]
        }
      ],
      "shipmentId": "she7a7c291-cc2e-4267-9863-bcd27caca3f0"
    },
    {
      "boxes": [
        {
          "contentInformationSource": "BOX_CONTENT_PROVIDED",
          "dimensions": {
            "height": "31",
            "length": "41",
            "unitOfMeasurement": "CM",
            "width": "10"
          },
          "quantity": "1",
          "weight": {
            "unit": "LB",
            "value": "10"
          },
          "items": [
            {
              "labelOwner": "NONE",
              "msku": "ABC0329",
              "prepOwner": "NONE",
              "quantity": "4",
              "expiration": "6462-07-27"
            }
          ]
        }
      ],
      "shipmentId": "sh0d4a5104-3e03-4147-9073-efe1d2bae97a"
    }
  ]
}
`
we  get  the error
`
{
    "errors": [
        {
            "code": "BadRequest",
            "message": "ERROR: Shipment sh0d4a5104-3e03-4147-9073-efe1d2bae97a did not contain expected items and/or quantities.",
            "details": "Problem item quantities: Item(msku=ABC0329, mlc=null, expiration=6462-07-27T00:00Z, labelOwner=NONE, prepOwner=NONE, isQtyKnown=true): expected quantity: 0, actual quantity: 4, Item(msku=qtest-1212, mlc=null, expiration=5247-03-30T00:00Z, labelOwner=SELLER, prepOwner=NONE, isQtyKnown=true): expected quantity: 5, actual quantity: 0"
        },
        {
            "code": "BadRequest",
            "message": "ERROR: Shipment she7a7c291-cc2e-4267-9863-bcd27caca3f0 did not contain expected items and/or quantities.",
            "details": "Problem item quantities: Item(msku=qtest-1212, mlc=null, expiration=6462-07-27T00:00Z, labelOwner=NONE, prepOwner=NONE, isQtyKnown=true): expected quantity: 0, actual quantity: 5, Item(msku=ABC0329, mlc=null, expiration=5247-03-30T00:00Z, labelOwner=NONE, prepOwner=NONE, isQtyKnown=true): expected quantity: 4, actual quantity: 0"
        }
    ]
}
`

can you tell me the reason . thanks .
by the way , the box info is warehouse  support after packed.  in this case ,we use Creating a shipment when the seller does not know the carton level information up-front  is ok?

**Comment by mafge** [comment]
Hi @collery,
thanks for reaching out!
As far as I can see from the error message you just need to switch `shipmentId`s in your request and it should work as expected. So shipment `she7a7c291-cc2e-4267-9863-bcd27caca3f0` should contain items with sku `ABC0329` and shipment `sh0d4a5104-3e03-4147-9073-efe1d2bae97a` should contain item with sku `qtest-1212`. Hope that helps!
Best,
Marc
Selling Partner Developer Services

**Comment by collery** [comment]
> 你好@collery， 感谢您的联系！ 据我从错误消息中看到，您只需`shipmentId`在请求中切换，就应该可以正常工作。因此，发货`she7a7c291-cc2e-4267-9863-bcd27caca3f0`应包含带 sku 的商品`ABC0329`，发货`sh0d4a5104-3e03-4147-9073-efe1d2bae97a`应包含带 sku 的商品商品`qtest-1212`。希望能有所帮助！祝 好， Marc 销售合作伙伴开发者服务

thanks for your replay. i found the reason ,it's diffrent  expiration ,so  i just edit expiration ,it’s  ok
