### ISSUE TITLE
[Reports][v2021-06-30] FBA reports do not escape quotes in product title

### ISSUE THREAD

**Issue by emakunin** [amzn/selling-partner-api-models#4367]
Hello,

I'm parsing FBA inventory ledger reports that contain a product title field. Specifically GET_LEDGER_SUMMARY_VIEW_DATA, but I believe other types can be affected as well.

The problem is that product title is rendered without quotes escapes that makes the CSV file invalid and hard to process/import.

**Comment by gaecfov** [comment]
We also encountered the same problem, for example, if the original title was [Webcam for PC/Mac, 1/2" Sensor], the report would appear [" Webcam for PC/Mac, 1/2" Sensor "], The correct one would be [" Webcam for PC/Mac, 1/2 "" Sensor"]

**Comment by puppsupr** [comment]
Hi,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.
