### ISSUE TITLE
[BUG] [SP-API] [Issue] ListFinancialEvents returns incomplete data until multiple requests are made

### ISSUE THREAD

**Issue by jakeleventhal** [amzn/selling-partner-api-models#437]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

ListFinancialEventGroups

## Expected Behavior

All responses are consistent

## Current Behavior

If I run ListFinancialEventGroups with the following parameters:
```ts
FinancialEventGroupStartedAfter: moment('2022-01-01', 'YYYY-MM-DD').toISOString(),
NextToken: null
```
I get a response with 16 elements. If I run it again, I get 38, then 39, then 41, then 44 (the correct number).
After I get 44, it keeps returning 44 elements. If I try again the next day, I will get similar behavior. So for whatever reason, it doesn't return all elements until I hit the API endpoint several times (with the same parameters).

## Context/Screenshots

<img width="395" alt="Screenshot 2023-05-31 at 4 30 58 PM" src="https://github.com/amzn/selling-partner-api-docs/assets/15133828/ec6fb61b-15b8-463f-a049-152d4fc11119">

The .zip shows the API responses received for each the API calls. There is no clear pattern for what is/is not included.
[api-responses.zip](https://github.com/amzn/selling-partner-api-docs/files/11618670/api-responses.zip)

## Your Environment

Using [this library](https://github.com/amz-tools/amazon-sp-api) in TypeScript

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
