### ISSUE TITLE
Clarification on listPrepDetails - multiple prep categories?

### ISSUE THREAD

**Issue by nick-boxem** [amzn/selling-partner-api-models#4375]
![image](https://github.com/user-attachments/assets/82190ead-d46b-40f8-9475-4ca3327a32e0)

The image above suggests that it is possible for an item to belong to multiple prep categories, which makes sense. However, the `setPrepDetails` endpoint only allows you to set a single prep category for an item. How does one set multiple prep categories for an item?

Link to documentation section: https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#retrieve-preparation-instructions-for-an-msku

**Comment by puppsupr** [comment]
Hi @nick-boxem,
You can only have one prep category for an inbound. However you can keep changing the categories as required but at once the SKU will have only 1 category.

Refer here [Packaging and prep requirements](https://sellercentral.amazon.com/help/hub/reference/G200141500) and [Prep guidance](https://sellercentral.amazon.com/help/hub/reference/GF4G7547KSLDX2KC) for more details
