### ISSUE TITLE
【Fulfillment Inbound API v2024-03-20】 can i use LTL param  post  SPD traceIds

### ISSUE THREAD

**Issue by collery** [amzn/selling-partner-api-models#4381]
at past ,we just need post spd traceids , but now ,we use  [ Creating a shipment when the seller does not know the carton level information up-front] , it's  default LTL model。 but we use spd in fact .  
we want to know ,if it's can be post  and the amazon warehouse how to accept  goods

**Comment by puppsupr** [comment]
Hi @collery,
If carton information is not known, as as now this workflow is only available for LTL (pallet) shipments. You need to use the [left hand workflow](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow) to ship your small parcel delivery and also the pallet deliveries. 

You can refer to this[ Integration Guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-code-samples) for more details. Please check out this [Postman collections](https://www.postman.com/galactic-rocket-691225/selling-partner-api-for-fulfillment-inbound-fba-v2024/overview) to test out the flows.

**Comment by JimMcKenzieSmith** [comment]
@puppsupr It sounds like what you are saying is that:

1. The [right hand workflow](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow) does not support small parcel at all (currently).
2. Per @MetaMan2023's discussion thread, the [left hand workflow](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow) does not support [matching up seller box numbers to Amazon box labels](https://github.com/amzn/selling-partner-api-models/discussions/4365) during large-volume small parcel splits (currently).

If those two things are true, what exactly are we supposed to do?  What is the solution?

**Comment by MetaMan2023** [comment]
> @puppsupr It sounds like what you are saying is that:
> 
> 1. The [right hand workflow](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow) does not support small parcel at all (currently).
> 2. Per @MetaMan2023's discussion thread, the [left hand workflow](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#fulfillment-inbound-shipment-workflow) does not support [matching up seller box numbers to Amazon box labels](https://github.com/amzn/selling-partner-api-models/discussions/4365) during large-volume small parcel splits (currently).
> 
> If those two things are true, what exactly are we supposed to do? What is the solution?

It's more serious than that:

* I believe the carton matching is technically an issue for both the left and right flows -- it's just more significant for the left hand flow since you are mixing all boxes from all splits together in one big pile (vs. right hand flow you can at least narrow the boxes down to a specific shipment).

* I don't think it's  possible to ship LTL on the left hand flow when splitting to more than one center due to the box matching issue.   You don't know which boxes go on which pallets at the time you need to provide pallet information.

**Comment by collery** [comment]
@puppsupr  Sorry for the late reply. We actually tested the LTL method, but used the small package tracking number（spd）, and then Amazon received the goods. But this method is incorrect, and we are also waiting for the latest documents and processes
