### ISSUE TITLE
Issue for creating RestrictedDataToken to get restricted data of Direct Fulfillment Orders

### ISSUE THREAD

**Issue by lenhop** [amzn/selling-partner-api-models#4382]
Hi, I want to get buyer name and ship address of Direct Fulfillment Orders, as the instruction of getOrders of Vendor Direct Fulfillment Orders API, we need to obtain the restrictedDataToken first, but the errors happened just like the attachment.

another thing I have to say is that I have enable the RDT privilege or role for this vendor token.

<img width="807" alt="截屏2024-12-02 22 56 29" src="https://github.com/user-attachments/assets/a264da37-fafb-47f7-95fa-93578010df20">

**Comment by jawheral** [comment]
Hi @lenhop,

You need to call the `/vendor/directFulfillment/orders/v1/purchaseOrders` operation. For this, you need to:
1 - Make sure to re-authorize the vendor group after you applied the role to your application.
2 - if the above is not sufficient to get the data you need then in `dataElements` for `createRestrictedToken` make sure to add elements from the OrderResponse of the operation you are seeking, e.g `shipToParty`. See [here](https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-orders-api-v1-reference#orderdetails).

Best,
Jawher
Selling Partner Developer Services

**Comment by lenhop** [comment]
Hi Jawher, thanks for your feedback.

Per your  suggestion, I separately try all available values for dataElements individually, including shipToParty, shipmentDetails, shipFromParty, billToParty, but all return errors like below:

SellingApiBadRequestException: [{'code': 'InvalidInput', 'message': 'Application does not have access to one or more requested data elements: [shipToParty]', 'details': ''}]


Additional, if I don't input any value for dataElements item, surprise it works and its response return the restrictedDataToken.
![截屏2024-12-03 10 02 25](https://github.com/user-attachments/assets/6f7f489c-a420-40cf-aebf-37792764be54)

and integrate the restrictedDataToken into the getOrders API and get the buyer name , address value  xxxx from the response .
![截屏2024-12-03 10 07 51](https://github.com/user-attachments/assets/2258eb19-799d-4bbc-8ae7-a24a7c203e2a)

**Comment by jawheral** [comment]
Hi @lenhop,

RDTs behavior currently differs depending on the operation you are authorizing and might not be needed at all in the future, having the restricted role applied to your profile and application will be enough. I'm glad the above request worked for you.

Best,
Jawher
Selling Partner Developer Services
