### ISSUE TITLE
[FBA Inbound v2024] Transport via ground small parcel

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4387]
Hi,
* in V0 we were using NonPartneredSmallParcelDataInput type=SP carrier=Other
* in v2024 I createInboundPlan with EU marketplace, then generatePlacementOptions with empty request
* then the list of placementOptions is only 1 option
* we confirm it
* then in generateTransportOptions -> listOfTransportationOptions there are all only FREIGHT_LTL and no GROUND_SMALL_PARCEL + also 99% of offered carriers are from China ... this seems wrong? I have no idea what I'm doing wrong

Thank you

**Comment by puppsupr** [comment]
Hi @NoxArt,
Are you always seeing only 1 placement option ? Can you create the same inbound on the Send to Amazon UI and check if you see the same results of only one placement plan.

You can refer to this[ Integration Guide](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-code-samples) to very your workflows. Please check out this [Postman collections](https://www.postman.com/amazon-selling-partner-api/sp-api/overview) to test out the flows.

**Comment by NoxArt** [comment]
Thank you

It looks we need to go the A (left) route in the workflow instead of B
