### ISSUE TITLE
JSON feed Other offer vs Other product

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4392]
Hi, what is the difference between
**other_offer_image_locator_1**
and
**other_product_image_locator_1**
?

Offer says:

> The URL for additional images of your product. These images will be shown on the detail page when the customer clicks through to see other views associated with the product

Product says:

> The URL for additional images of your product. These images will be shown on the detail page when the customer clicks through to see other views associated with the product

-> exactly the same description

Thank you

**Comment by weilinggu** [comment]
Hi @NoxArt, please see if this [documentation](https://developer-docs.amazon.com/sp-api/docs/mapping-product-attributes#image-type-mappings) can help you with understanding the difference.

Thanks
Weiling
Amazon Selling Partner Services

**Comment by NoxArt** [comment]
Thank you, that does help ... I think the info that it's relate to non-new condition is not included in Json Schema? Would be useful to add it
