### ISSUE TITLE
Regarding the issue that SCREEN_PROTECTOR products cannot set up quantity discount plans.

### ISSUE THREAD

**Issue by baisedongtian** [amzn/selling-partner-api-models#4394]
I noticed that in the SCREEN_PROTECTOR schema, the quantity_discount_plan cannot be set. Will this be changed in the future, or are there alternative ways to set it up? Here is the explanation from the schema: 'minItems': 1, 'maxItems': 0.

**Comment by jawheral** [comment]
Hi @baisedongtian,

You can normally set the `quantity_discount_plan` for products of the `SCREEN_PROTECTOR` product type. When requesting the schema, make sure to include the `sellerId` to check the schema that applies to the seller.
Additionally, you can just use the generic `PRODUCT` product type when setting the purchasable_offer.

I hope this helps!
Best,
Jawher
Selling Partner Developer Services

**Comment by baisedongtian** [comment]
After multiple attempts, I still haven't succeeded in uploading. I'd like to share my construction of this part and the upload results with you - could you help identify the cause? Additionally, I noticed that the upload succeeds when I don't set A. Thank you.

 "purchasable_offer": [
                    {
                        "marketplace_id": "A1VC38T7YXB528",
                        "currency": "JPY",
                        "audience": "ALL",
                        "our_price": [
                            {
                                "schedule": [
                                    {
                                        "value_with_tax": 100
                                    }
                                ]
                            }
                        ],
                        "quantity_discount_plan": [
                            {
                                "schedule": [
                                    {
                                        "discount_type": "fixed",
                                        "levels": [

                                            {
                                                "lower_bound": 2,
                                                "value": 95
                                            },
                                            {
                                                "lower_bound": 20,
                                                "value": 80
                                            },
                                            {
                                                "lower_bound": 50,
                                                "value": 75
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ],

 'payload': {'issues': [{'attributeNames': ['purchasable_offer'],
                         'categories': ['INVALID_ATTRIBUTE'],
                         'code': '99016',
                         'message': '属性purchasable_offerは最大0回の発生が許可されていますが、現在1回発生しています。',
                         'severity': 'ERROR'}],
             'sku': 'm-zf',
             'status': 'INVALID',
             'submissionId': 'fb5f5507a507a78b467b89f888a4c'},
 'rate_limit': '5.0'}

**Comment by baisedongtian** [comment]
'payload': {'issues': [{'attributeNames': ['purchasable_offer'],
                         'categories': ['INVALID_ATTRIBUTE'],
                         'code': '99016',
                         'message': '属性purchasable_offerは最大0回の発生が許可されていますが、現在1回発生しています。',
                         'severity': 'ERROR'}],
             'sku': 'm-zf',
             'status': 'INVALID',
             'submissionId': 'fb5f5507a78b467b89f888a4b204521c'},
 'rate_limit': '5.0'}

I have sent it to you. Please help me check it. Thank you.

**Comment by jawheral** [comment]
Hi @baisedongtian,

You are providing a `quantity_discount_plan` with the "audience: ALL" selector (B2C offer). Quantity discount plans are only available for B2B offers - "audience": "B2B".

I hope this helps!

Best,
Jawher
Selling Partner Developer Services

**Comment by baisedongtian** [comment]
I have already solved this problem, thank you for your help.
