### ISSUE TITLE
[Listings Items API v2021-08-01] How to patch listings item fields without affecting other fields?

### ISSUE THREAD

**Issue by foobar999** [amzn/selling-partner-api-models#4406]
Hello,

we have a question regarding the call [`patchListingsItem`](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku). If we have a listing returned by [`getListingsItem`](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#get-listings2021-08-01itemsselleridsku) with a `fulfillment_availability `like this:

```
"fulfillment_availability": [
	{
		"fulfillment_channel_code": "DEFAULT",
		"quantity": 126,
		"lead_time_to_ship_max_days": 12,
		"marketplace_id": "A1PA6795UKMFR9"
	}
]
```

We would like to adjust the `quantity `for listings, without updating other fields. However, if send a `patchListingsItem `call with a body like this

```
{
	"productType": "HAIR_REMOVAL_AND_SHAVING_PRODUCT",
	"patches": [
		{
			"op": "replace",
			"path": "/attributes/fulfillment_availability",
			"value": [
				{
					"fulfillment_channel_code": "DEFAULT",
					"quantity": 127
				}
			]
		}
	]
}
```

`getListingsItem` returns now a `fulfillment_availability` like this

```
"fulfillment_availability": [
	{
		"fulfillment_channel_code": "DEFAULT",
		"quantity": 127,
		"marketplace_id": "A1PA6795UKMFR9"
	}
]
```

without the `lead_time_to_ship_max_days` available before. How can we adjust the `quantity` only without affecting other fields? This is a required use case for us.

**Comment by jawheral** [comment]
Hi @foobar999,

Only top-level listings item attributes can be patched. Patching nested attributes is not supported. You can read this in the operation's [reference](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#patch-listings2021-08-01itemsselleridsku).
For this reason, what happens is that the full "fulfillment_availability" attribute is being patched/replaced, thus removing the `lead_time_to_ship_max_days` as it was not provided. Please make sure to include the `lead_time_to_ship_max_days` as well in your patch request.
The right patch is as follows:
```
{
  "productType": "HAIR_REMOVAL_AND_SHAVING_PRODUCT",
  "patches": [
    {
      "op": "replace",
      "path": "/attributes/fulfillment_availability",
      "value": [
        {
          "fulfillment_channel_code": "DEFAULT",
          "lead_time_to_ship_max_days": 12,
          "quantity": 127
        }
      ]
    }
  ]
}
```

Best,
Jawher
Selling Partner Developer Services

**Comment by foobar999** [comment]
Thank you for your reply. 

The solution you provided forces us to store all other fields which are part of `fulfillment_availability` (`lead_time_to_ship_max_days`, `restock_date`, ...) in our database, otherwise we can't send them.
Or, we need to call `getListingsItems` to retrieve the previous state of the listings item. This generates an unnecessary API call and can therefore lead to throttling issues.
We really would appreciate a way to update for specific fields only.

**Comment by jawheral** [comment]
Hi @foobar999,

Thank you for the feedback. Our Listings teams are aware of these gaps and are working on designing solutions to address them. We are currently unable to provide a release date. Please keep an eye on our [announcements](https://developer-docs.amazon.com/sp-api/changelog).

Best,
Jawher
Selling Partner Developer Services
