### ISSUE TITLE
Issue of retrieve the response for SKUs containing spaces

### ISSUE THREAD

**Issue by BrijalAescope** [amzn/selling-partner-api-models#4410]
When calling the Product Pricing API's  API method to get offer details with an SKU like "Earrings GIA HDS 14K 3.4," the function returns an error: "Earrings%20GIA%20HDS%2014K%203.4 is an invalid SKU for the marketplace." This issue occurs because SKUs containing spaces are not properly encoded. Spaces in SKUs can lead to encoding problems when forming API requests, as they are typically encoded as %20.
Is there a way to retrieve the response for SKUs containing spaces?

**Comment by leonardonakagawa** [comment]
Hi @BrijalAescope!

Can you please share more details of the API operation are you trying to call? Which is the endpoint and parameters that you are passing.


Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by leonardonakagawa** [comment]
Hi @BrijalAescope,

We deployed a fix on our side and the API should be working as before now. If you are still not able to encode an SKU please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
