### ISSUE TITLE
【Fulfillment Inbound API v2024-03-20】listPrepDetails/createInboundPlan: "ERROR: The following MSKUs are not valid: [mskus]" when listPrepDetails or createInboundPlan is called using the v1 api (but working in v0)

### ISSUE THREAD

**Issue by lucasrossell** [amzn/selling-partner-api-models#4413]
Hello. We have an item in our inventory that has a listing but is unable to be used to create an inbound plan in the v1 api. It is able to be used in the v0 api to successfully create a shipment, however. Below is an example of what we are using in our request and the response from listPrepDetails for the item:

marketplaceId: ATVPDKIKX0DER
mskus: GGG_B08BZYPN1Z_9.99_20241209-915

{
  "error": "ERROR: The following MSKUs are not valid: [GGG_B08BZYPN1Z_9.99_20241209-915]."
}

We are able to make plans with other items using the v1 api just fine.

**Comment by daviddecorso** [comment]
+1 on this, the error message is not helpful at all

**Comment by puppsupr** [comment]
HI,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

**Comment by lucasrossell** [comment]
For anyone encountering this error, we received the following guidance from their Selling Partner API Developer Support team.

> Upon investigation I found that due to inactivity on the listing (SKU: GGG_B08BZYPN1Z_9.99_20241209-915), the listing has been discontinued from our system.
> Seller needs to submit a full update for the listing, in order to reinstate it.

Also,

> Please note that the new Fulfillment Inbound API v2024-03-20 utilizes STA (Send to Amazon) workflow and for this it is required that the listing is in active state, unlike the old Fulfillment Inbound API which does not utilizes STA.

Which is why the MSKUs worked on v0 but not the new API. 

@puppsupr Thanks for your help. maybe the error message for this could be improved to better communicate this in the future?

**Comment by puppsupr** [comment]
@lucasrossell, thanks for the feedback, yes team is working on to improve the error messaging.
