### ISSUE TITLE
GetInboundPlan is not supported for the cross border Amazon Global Logistics program.

### ISSUE THREAD

**Issue by Oanoan** [amzn/selling-partner-api-models#4419]
When I created the Workflow, I checked "I want to ship with Amazon Global Logistics." However, an exception occurred while using the GetInboundPlan to pull it.

"GetInboundPlan is not supported for the cross border Amazon Global Logistics program."

![image](https://github.com/user-attachments/assets/a7b9ad87-00bc-4cbc-9b46-aec8a3b960de)

**Comment by puppsupr** [comment]
Hi @Oanoan,
We don't support Amazon Global Logistics Program via the new FBA Inbound v2024 APIs as of now.

**Comment by kmizzi** [comment]
@puppsupr If we are supposed to stop using Fulfillment Inbound v0, how can we do this if we can't get AGL shipments with the new API?
