### ISSUE TITLE
[Fulfillment Inbound API v2024-03-20] What does "UNKNOWN" prep category mean? 

### ISSUE THREAD

**Issue by midi-red** [amzn/selling-partner-api-models#4424]
What does "UNKNOWN" prep category mean? 
When calling listPrepDetails endpoint, it sometimes returns "UNKNOWN" prep category? What would be the appropriate setPrepDetails request body?

Here a sample response for listPrepDetails:
`[
  {
    "allOwnersConstraint": null, 
    "labelOwnerConstraint": null,
    "msku": "SKU-123456",
    "prepCategory": "UNKNOWN",
    "prepOwnerConstraint": null,
    "prepTypes": [
    ]
  }
]
`
Thanks

**Comment by daviddecorso** [comment]
From the docs:
> UNKNOWN: An unknown prep category was found and needs to be updated. This value is provided by Amazon and cannot be used as an input.

[https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#prepcategory](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#prepcategory)

https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#set-preparation-instructions-for-an-msku

**Comment by puppsupr** [comment]
Thanks for the links @daviddecorso. Please let me know if you need more info @midi-red or if you are facing any issues.
