### ISSUE TITLE
CreateInboundPlan internal error 500

### ISSUE THREAD

**Issue by NoxArt** [amzn/selling-partner-api-models#4430]
Hello, today we keep getting "We encountered an internal error. Please try again." repeatedly, is the service down?
Last attempted time is 5second before posting this issue
Thank you

**Comment by PoneraLucas** [comment]
Same here, the operation crashes (and keeps crashing) as soon as we take our bad SKUs out of the calls

**Comment by weilinggu** [comment]
@NoxArt @PoneraLucas Thanks for reporting the issue. If you have not opened a support case with us, please go ahead and do so [here](https://developer.amazonservices.com/support). Additional information on your end would help speed up the issue resolution.

Thanks
Weiling
Amazon Selling Partner Services

**Comment by NoxArt** [comment]
ok, thank you, I created a case
