### ISSUE TITLE
setPackingInformation : Shipment  did not contain expected items and/or quantities

### ISSUE THREAD

**Issue by drukoz** [amzn/selling-partner-api-models#4440]
I’m encountering the same issue. I verified and set the prep details as recommended, and even tried including the BoxId in the box object, following the step 4 request example from the SP-API documentation. I also set both the prepOwner and labelOwner to "seller."

I’ve tried everything. Since we don’t use 2D barcodes, we must rely on BOX_CONTENT_PROVIDED. This issue resembles #3951, but that case involved packing groups, whereas I’m sending all shipments at once using different shipment IDs.

Here is a picture of the seller central prep owner and label owner
![image](https://github.com/user-attachments/assets/a41315ec-ea06-48ca-9474-e7e917edcd94)

**### Incase a Dev needs this info here is the request id and timestamp**
RequestId: 4e721516-da25-41ca-900a-b3b2fe2ea911
TimeStamp: Wed, 18 Dec 2024 10:02:06 GMT

Request:
`
{"packageGroupings":[{"boxes":[{"contentInformationSource":"BOX_CONTENT_PROVIDED","dimensions":{"height":5.0,"length":5.0,"unitOfMeasurement":"IN","width":5.0},"items ":[{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"RD-ZEPE-WK66","prepOwner":"SELLER","quantity":26},{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"AH-SXVZ-MKF3","prepOwner":"SELLER","quantity":8}],"quantity":1,"weight":{"unit":"LB","value":5.0}}],"shipmentId":"sh31255b63-d2ec-4e05-8894-719e8b66a9d7"},{"boxes":[{"contentInformationSource":"BOX_CONTENT_PROVIDED","dimensions":{"height":5.0,"length":5.0,"unitOfMeasurement":"IN","width":5.0},"items ":[{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"RD-ZEPE-WK66","prepOwner":"SELLER","quantity":12},{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"AH-SXVZ-MKF3","prepOwner":"SELLER","quantity":8}],"quantity":1,"weight":{"unit":"LB","value":5.0}}],"shipmentId":"sh3763c3bd-302c-40a2-a15f-254121c9c2a2"},{"boxes":[{"contentInformationSource":"BOX_CONTENT_PROVIDED","dimensions":{"height":5.0,"length":5.0,"unitOfMeasurement":"IN","width":5.0},"items ":[{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"RD-ZEPE-WK66","prepOwner":"SELLER","quantity":22},{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"AH-SXVZ-MKF3","prepOwner":"SELLER","quantity":7}],"quantity":1,"weight":{"unit":"LB","value":5.0}}],"shipmentId":"sh4a44e38c-9274-4350-8f47-8d6c50ecbb0d"},{"boxes":[{"contentInformationSource":"BOX_CONTENT_PROVIDED","dimensions":{"height":5.0,"length":5.0,"unitOfMeasurement":"IN","width":5.0},"items ":[{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"RD-ZEPE-WK66","prepOwner":"SELLER","quantity":18},{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"AH-SXVZ-MKF3","prepOwner":"SELLER","quantity":7}],"quantity":1,"weight":{"unit":"LB","value":5.0}}],"shipmentId":"sh96e1806a-7417-4749-a063-e50b90978eb3"},{"boxes":[{"contentInformationSource":"BOX_CONTENT_PROVIDED","dimensions":{"height":5.0,"length":5.0,"unitOfMeasurement":"IN","width":5.0},"items ":[{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"RD-ZEPE-WK66","prepOwner":"SELLER","quantity":18},{"expiration":"2025-12-18","labelOwner":"SELLER","msku":"AH-SXVZ-MKF3","prepOwner":"SELLER","quantity":9}],"quantity":1,"weight":{"unit":"LB","value":5.0}}],"shipmentId":"shc2b414d1-4f69-4502-982b-71466ed79622"}]}
`

Response:
`
{
"errors": [
{
"code": "BadRequest",
"message": "ERROR: Shipment sh31255b63-d2ec-4e05-8894-719e8b66a9d7 did not contain expected items and/or quantities.",
"details": "Problem item quantities: Item(msku\u003dRD-ZEPE-WK66, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 26, actual quantity: 0, Item(msku\u003dAH-SXVZ-MKF3, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 8, actual quantity: 0"
},
{
"code": "BadRequest",
"message": "ERROR: Shipment sh3763c3bd-302c-40a2-a15f-254121c9c2a2 did not contain expected items and/or quantities.",
"details": "Problem item quantities: Item(msku\u003dRD-ZEPE-WK66, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 12, actual quantity: 0, Item(msku\u003dAH-SXVZ-MKF3, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 8, actual quantity: 0"
},
{
"code": "BadRequest",
"message": "ERROR: Shipment sh4a44e38c-9274-4350-8f47-8d6c50ecbb0d did not contain expected items and/or quantities.",
"details": "Problem item quantities: Item(msku\u003dRD-ZEPE-WK66, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 22, actual quantity: 0, Item(msku\u003dAH-SXVZ-MKF3, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 7, actual quantity: 0"
},
{
"code": "BadRequest",
"message": "ERROR: Shipment sh96e1806a-7417-4749-a063-e50b90978eb3 did not contain expected items and/or quantities.",
"details": "Problem item quantities: Item(msku\u003dRD-ZEPE-WK66, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 18, actual quantity: 0, Item(msku\u003dAH-SXVZ-MKF3, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 7, actual quantity: 0"
},
{
"code": "BadRequest",
"message": "ERROR: Shipment shc2b414d1-4f69-4502-982b-71466ed79622 did not contain expected items and/or quantities.",
"details": "Problem item quantities: Item(msku\u003dRD-ZEPE-WK66, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 18, actual quantity: 0, Item(msku\u003dAH-SXVZ-MKF3, mlc\u003dnull, expiration\u003d2025-12-18T00:00Z, labelOwner\u003dSELLER, prepOwner\u003dSELLER, isQtyKnown\u003dtrue): expected quantity: 9, actual quantity: 0"
}
]
}`

**Comment by NoxArt** [comment]
It would be nice if the API reported there is missing parameter "items" and unknown parameter "items "

**Comment by drukoz** [comment]
@PoneraLucas Hello ,
Thank you for your response i fixed our typo testing this now will get back on this ASAP.

**Comment by drukoz** [comment]
that fixed me thank you! not sure how that space got there.
