### ISSUE TITLE
create feed api 

### ISSUE THREAD

**Issue by xyloneX** [amzn/selling-partner-api-models#4445]
request：
```
{
    "headers": {
        "x-amz-access-token": ""
    },
    "json": {
        "feedType": "POST_PRODUCT_DATA",
        "marketplaceIds": [
            "A2VIGQ35RCS4UG"
        ],
        "inputFeedDocumentId": "amzn1.tortuga.4.eu.92e5b56c-9f91-453c-b908-ea3683920537.T3GMUT0S9D1D9G"
    }
}
```
response：
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
  ]
}
```
Is the SA site not supported?

**Comment by MeenaAmz** [comment]
@xyloneX This issue requires further investigation, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here. Please ensure you provide the request id and feed type in your support case.  

Thanks,
Meena
Selling Partner API Developer Services
