### ISSUE TITLE
No partnered carriers in EU - Fulfillment Inbound 2024

### ISSUE THREAD

**Issue by keithbrink** [amzn/selling-partner-api-models#4446]
I just received this message from developer support:

![CleanShot 2024-12-19 at 19 25 42@2x](https://github.com/user-attachments/assets/f278ba2d-8ab2-4329-9427-f5fff7079212)

It's inexcusable to turn off the ability for merchants in Europe to create partnered fulfilment inbound shipments. We support thousands of merchants in Europe creating shipments into Amazon FBA, and this will immediately cause them huge losses in productivity and reduce their ability to sell on the Amazon marketplace.

The new workflow is missing critical functionality. Please extend the old Fulfilment Inbound API deadline until you have filled these critical gaps in the new one.

Case #: 16873789051

**Comment by puppsupr** [comment]
Hi @keithbrink,
Partnered Carrier Program (PCP) is available in EU. 

Before you use an Amazon-partnered carrier for an inbound shipment, you must read the Seller Central Help about Amazon's PCP to help ensure that you successfully follow the program instructions and guidelines (EU: https://sellercentral.amazon.co.uk/gp/help/201119120)

In the EU region, you must first review and accept the terms and conditions of the carrier and the terms and conditions of Amazon's PCP. You can do this on Seller Central (https://sellercentral.amazon.co.uk/gp/help/201119120). If you attempt to use Amazon Selling Partner APIs to create an inbound shipment by using an Amazon-partnered carrier before accepting these terms and conditions, the service returns an error.
