### ISSUE TITLE
get placement cost for an existing shipment

### ISSUE THREAD

**Issue by HDPAlex** [amzn/selling-partner-api-models#4447]
Hello
Is there a way to get placement cost and carrier cost for an existing shipment?
Call to getShipment does not return this info
GET /inbound/fba/2024-03-20/inboundPlans/{inboundPlanId}/shipments/{shipmentId}

Is there a way to reference the shipment by shipmentConfirmationId ?

**Comment by puppsupr** [comment]
Hi @HDPAlex,
Once shipments are confirmed, try to call [listPlacementOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listplacementoptions) to view the confirmed placement fees and [listTransportationOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listtransportationoptions) to view the confirmed quotes.

You can keep using [getShipmentItemsByShipmentId](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitemsbyshipmentid) as this will not be deprecated.
