### ISSUE TITLE
ConfirmTransportationOptions responed BadRequest ERROR: Provided shipment ids [sh6a441ef0-7964-4433-a5b2-cbdad59248fe] do not match the shipments in the confirmed placement option

### ISSUE THREAD

**Issue by loco925** [amzn/selling-partner-api-models#4449]
The shipping country is the United Kingdom. Is it because one packingOptionId has multiple packingGroups? Or is it because one placementOptionId has multiple shipmentIds, causing this error to be prompted when finally ConfirmTransportationOptions? We confirmed that the shipmentId and transportationOptionId are correct and there are no errors. Could you please help me find out which interface request is causing the problem?

The data requested by the interface is simple：

---------------------------

**GeneratePackingOptions**

"requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f"}

responed：
{"operationId":"2d5fe745-25eb-488a-af03-553afce5bca5"}

--------------------------------------------------------------------

**ListPackingOptions**

“requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f","pageSize":20,"paginationToken":null}

responed：
{"packingOptions":[{"packingGroups":["pg331e0c11-59d3-4385-8b93-fb483ef4b0ac","pgabb98fbe-9026-4c61-a6d0-3db05a92c88f"],"fees":[],"discounts":[],"packingOptionId":"poe0643bb6-150f-4bac-8bbf-fc1cb23d55e2","supportedShippingConfigurations":[{"shippingMode":"GROUND_SMALL_PARCEL","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"shippingMode":"FREIGHT_LTL","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"shippingMode":"FREIGHT_FTL_PALLET","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"shippingMode":"OCEAN_LCL","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"shippingMode":"OCEAN_FCL","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"shippingMode":"AIR_SMALL_PARCEL","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"shippingMode":"AIR_SMALL_PARCEL_EXPRESS","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"shippingMode":"GROUND_SMALL_PARCEL","shippingSolution":"AMAZON_PARTNERED_CARRIER"},{"shippingMode":"FREIGHT_LTL","shippingSolution":"AMAZON_PARTNERED_CARRIER"},{"shippingMode":"FREIGHT_FTL_PALLET","shippingSolution":"AMAZON_PARTNERED_CARRIER"},{"shippingMode":"OCEAN_LCL","shippingSolution":"AMAZON_PARTNERED_CARRIER"},{"shippingMode":"OCEAN_FCL","shippingSolution":"AMAZON_PARTNERED_CARRIER"},{"shippingMode":"AIR_SMALL_PARCEL","shippingSolution":"AMAZON_PARTNERED_CARRIER"},{"shippingMode":"AIR_SMALL_PARCEL_EXPRESS","shippingSolution":"AMAZON_PARTNERED_CARRIER"}],"status":"ACCEPTED"}],"pagination":{}}

---------------------------------------------------
**ConfirmPackingOption**：

"requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f","packingOptionId":"poe0643bb6-150f-4bac-8bbf-fc1cb23d55e2"}

responed：
{"operationId":"9f7701cb-d626-4afa-a2a0-0f2e9798673d"}

---------------------------------------------

**GeneratePlacementOptions：**

"requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f","body":{"customPlacement":null}}

responed：
{"operationId":"6998386a-dca4-43a2-a088-f892ca662736"}

--------------------------------------------------------------------------

**ListPlacementOptions**：

"requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f","pageSize":20,"paginationToken":null}

responed：
{"pagination":{},"placementOptions":[{"fees":[{"description":"Placement service fee represents service to inbound with minimal shipment splits and destinations of skus","type":"FEE","value":{"amount":0,"code":"GBP"},"target":"Placement Services"}],"shipmentIds":["sh6a441ef0-7964-4433-a5b2-cbdad59248fe","shdece5926-1884-4eb7-86a1-3c0186b08c5f"],"discounts":[],"expiration":"2024-12-22T05:42:34.103Z","placementOptionId":"pl14bcd7e9-c6e0-41bc-944d-7a8fb0f0eb3e","status":"OFFERED"},{"fees":[{"description":"Placement service fee represents service to inbound with minimal shipment splits and destinations of skus","type":"FEE","value":{"amount":0,"code":"GBP"},"target":"Placement Services"}],"shipmentIds":["sh519ac8ff-9a7d-48a2-af03-44402f3b8af9","shb43c85c3-b804-4a8d-baf6-8d51dd5c1697"],"discounts":[],"expiration":"2024-12-22T05:42:34.103Z","placementOptionId":"plf032d347-fbb4-477f-ac63-5d4cbed2e090","status":"OFFERED"}]}

------------------------------------------

**ConfirmPackingOption**

"requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f","packingOptionId":"poe0643bb6-150f-4bac-8bbf-fc1cb23d55e2"}

responed：
{"operationId":"9f7701cb-d626-4afa-a2a0-0f2e9798673d"}

-----------------------------------------------------------

**GenerateTransportationOptions**

"requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f","body":{"placementOptionId":"pl14bcd7e9-c6e0-41bc-944d-7a8fb0f0eb3e","shipmentTransportationConfigurations":[{"contactInformation":null,"freightInformation":null,"pallets":null,"readyToShipWindow":{"start":"2024-12-21T13:45Z"},"shipmentId":"sh6a441ef0-7964-4433-a5b2-cbdad59248fe"},{"contactInformation":null,"freightInformation":null,"pallets":null,"readyToShipWindow":{"start":"2024-12-21T13:45Z"},"shipmentId":"shdece5926-1884-4eb7-86a1-3c0186b08c5f"}]}}

responed：
{"operationId":"0f5b1865-79fa-4519-87ba-34df18541a8d"}

---------------------------------

**ConfirmTransportationOptions**

"requestData":{"inboundPlanId":"wf66a54287-6386-446f-bc0d-1e15f8b5453f","body":{"transportationSelections":[{"contactInformation":null,"shipmentId":"sh6a441ef0-7964-4433-a5b2-cbdad59248fe","transportationOptionId":"to857a1640-a5e1-4a2a-9824-cbef412824e5"}]}}

{
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: Provided shipment ids [sh6a441ef0-7964-4433-a5b2-cbdad59248fe] do not match the shipments in the confirmed placement option.",
      "details": ""
    }
  ]
}

**Comment by keithbrink** [comment]
I am experiencing this same issue, support case #: 16860472931

**Comment by puppsupr** [comment]
Hi @loco925,
In order to correctly resolve this issue, Please [open a support case](https://developer.amazonservices.com/support) following the [guidance](https://developer.amazonservices.com/support-guidelines) here so we can pursue the investigation as additional details are required from your end.

@keithbrink, I see that the investigation is in progress for your case.
