### ISSUE TITLE
Bad Request 400 issue with NextToken on OrderAPI

### ISSUE THREAD

**Issue by mehboobafridi** [amzn/selling-partner-api-models#446]
I am receiving bad request 400, when passing NextToken in the getOrders call. 

I tried to urlencode the token and this time did no receive any error, however, the call did not return any order though. I am sure there were many orders remaining.

This issue was risen about 2 years ago, which is still awaiting to resolve.

Here is the previous issue reference : is not valid; 
https://github.com/amzn/selling-partner-api-models/issues/2100
https://github.com/amzn/selling-partner-api-models/issues/1420

**Comment by harguph** [comment]
Closing this as this is an old issue.

Please feel free to open a new issue with us for any further query.
