### ISSUE TITLE
What is the SellerCentral version of the API createNegativeFeedbackRemoval call?

### ISSUE THREAD

**Issue by johnkw** [amzn/selling-partner-api-models#460]
What is the SellerCentral version of the API createNegativeFeedbackRemoval call?

As listed on https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference#createnegativefeedbackremoval this API call: `Sends a non-critical message that asks a buyer to remove their negative feedback. This message should only be sent after the seller has resolved the buyer's problem.`

But there's nothing I can find on SellerCentral regarding when this should or should not be used exactly. Usually the SellerCentral side of things has more detail.

**Comment by johnkw** [comment]
Please leave unresolved bug reports open so that they're easier for the community to find and discuss.

**Comment by shreeharsh-a** [comment]
@johnkw please use discussions instead of issues for this purpose, thanks!
