### ISSUE TITLE
[FEATURE] Documentation Getting GET_VAT_TRANSACTION_DATA with RDT Token

### ISSUE THREAD

**Issue by marfitec** [amzn/selling-partner-api-models#461]
Hello all,

I have now added the Tax Accounting and Tax Transfer roles to the DeveloperAccount.

Unfortunately, I can't manage to create a restricted token for CreateReport. I don't know which dataElements I have to pass.

It doesn't work, a DocumentID is required, but I only have it after CreateReport.

{"restrictedResources":[{"method":"GET","path":"/reports/2021-06-30/reports","dataElements":[]}]}

That doesn't work either.
{
  "restrictedResources": [
    {
      }, "method": "GET",
      "path": "/reports/2021-06-30/reports",
      "dataElements": [
        "buyerInfo",
        "paymentInfo"
      ]
    }
  ]
}

Does anyone have an idea how I can now create and retrieve the GET_VAT_TRANSACTION_DATA using the RDT?

I din´t found this in Documentation

@evangelosdaniil @sungolivia

**Comment by Philomath88** [comment]
@shreeharsh-a Developer Support is not great tbh - I never had one useful answer. I fixed it myself.
