### ISSUE TITLE
[BUG] [SP-API] [Issue] getSubscription and createSubscription do not work for notification type ORDER_CHANGE

### ISSUE THREAD

**Issue by cohlar** [amzn/selling-partner-api-models#467]
## I'm submitting a...

<pre><code>[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Notifications API v1

## Current Behavior

Operation `getSubscription` for notificationType `ORDER_CHANGE` returns the following error: 

> Invalid value "ORDER_CHANGE" for path parameter notificationType

**Comment by leonardonakagawa** [comment]
Hi @cohlar,

Hope you got this issue resolved. If not, I recommend you check our [Tutorial: Subscribe to the ORDER_CHANGE notification](https://developer-docs.amazon.com/sp-api/docs/tutorial-subscribe-to-order-change-notification)

If the information available in the documentation link provided above does not fully resolve your inquiry, please [open a support case](https://developer.amazonservices.com/support) with us.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
