### ISSUE TITLE
[BUG] [SP-API] [Issue] TLS v1 and v1.1 are not disabled, but give a spurious 400 error with an HTML response

### ISSUE THREAD

**Issue by Charlieface** [amzn/selling-partner-api-models#470]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:

## Expected Behavior

When a client makes requests using TLS 1.0 or TLS 1.1, the server's SSL handler should simply fail with a protocol mismatch (or possibly accept the insecure protocol).

There should not be an HTML response at all, there should simply be a TLS tunnel failure. This makes it much easier to debug.

## Current Behavior
The server instead returns an HTML 400 Status with a title of "Website Temporarily Unavailable". This is consistently happening across all endpoints, when using TLS v1 or v1.1. TLS v1.2 works correctly of course, and SSL 3.0 and lower are completely disabled, as they should.

While it would be prudent to also disable the lower TLS versions, returning an HTML response is not to spec. It's not a JSON response, and cannot be parsed, and there is no error information as to what happened.

This causes no end of difficulty in debugging the use of old TLS versions, because it's not clear why the endpoint is failing. It also means that the host server has a low security grading from [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=sellingpartnerapi-eu.amazon.com&hideResults=on) and friends, due to the lower versions still being enabled.

**Example response with identifying info removed:**
```
HTTP/1.1 400 Bad Request
Server: Server
Date: *****
Content-Type: text/html
Connection: keep-alive
x-amz-rid: GQ08VAP1Z36YXZ6GC25G
Vary: Content-Type,Accept-Encoding,User-Agent
Last-Modified: *******
ETag: **********
Accept-Ranges: bytes
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload
Content-Length: 521

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Website Temporarily Unavailable</title>
</head>

<body>
<p>&nbsp;</p>
<center><img src="http://g-ecx.images-amazon.com/images/G/01/website/errors/503/generic.png" alt="website temporarily unavailable" width="500" height="300"></center>
</body>

</html>
```

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
