### ISSUE TITLE
[BUG] [SP-API] [GetMyFeesEstimate client input error]

### ISSUE THREAD

**Issue by kallen** [amzn/selling-partner-api-models#479]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
Product Fees V0 getMyFeesEstimates
## Expected Behavior

Should be returning an Success status.

## Current Behavior

For some reason, we receive the error below for certain ASINs. (Until very recently?) This request works most of the time, but for some ASINs it throws the **InvalidParameterValue** error.

Sample ASINs with the issue:  
- B07CV8QLJ9  
- B007Z3U4JC  
- B07L9G3FQW  
- B085CP1CL2  
- B0B3D4HH9Q

```javascript
{
    "payload": {
        "FeesEstimateResult": {
            "Status": "ClientError",
            "FeesEstimateIdentifier": {
                "MarketplaceId": "ATVPDKIKX0DER",
                "SellerId": "XXXXXXXXXXX",
                "IdType": "ASIN",
                "IdValue": "B01K86AYSI",
                "IsAmazonFulfilled": true,
                "PriceToEstimateFees": {
                    "ListingPrice": {
                        "CurrencyCode": "USD",
                        "Amount": 0
                    }
                },
                "SellerInputIdentifier": "B01K86AYSI"
            },
            "Error": {
                "Type": "Sender",
                "Code": "InvalidParameterValue",
                "Message": "There is an client-side error. Please verify your inputs.",
                "Detail": []
            }
        }
    }
}
```

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by fullbeats** [comment]
I am having the same issue. Is there any news on why this is occuring and how the fee information can be retrieved in those cases?
