### ISSUE TITLE
Getting page views in page view id granularity

### ISSUE THREAD

**Issue by annyfedorova** [amzn/selling-partner-api-models#480]
I found Sales and Traffic Business Report in SP-API. But is it possible to see page views/user sessions for products not as a commulative sum but separately by each page view? Maybe in SP-API or AWS or some other Amazon API?

**Comment by leonardonakagawa** [comment]
Hi @annyfedorova,

We now have Data Kiosk which lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses. Currently, provides data under the Analytics Sales and Traffic dataset.

To understand the attributes for this dataset, you can look our [Data Kiosk datasets documentation](https://developer-docs.amazon.com/sp-api/v0/docs/data-kiosk-datasets#analytics).

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
