### ISSUE TITLE
[BUG] [SP-API] [ Unable to obtain the required parameters for the listing]

### ISSUE THREAD

**Issue by fitz-97** [amzn/selling-partner-api-models#484]
During the process of executing putListingsItem, where should I obtain the required mandatory parameter recommended_browse_nodes for browsing categories? In the early use of the feed operation, it was obtained through templates. However, for listing via the API, where should I get the recommended_browse_nodes list corresponding to this product type?

**Comment by liweixian** [comment]
> During the process of executing putListingsItem, where should I obtain the required mandatory parameter recommended_browse_nodes for browsing categories? In the early use of the feed operation, it was obtained through templates. However, for listing via the API, where should I get the recommended_browse_nodes list corresponding to this product type?
你好，请问这个问题解决了吗？
