### ISSUE TITLE
[BUG] [SP-API] [Issue] Quotation marks are not supported in Sku value for `products/pricing/v0/competitivePrice`

### ISSUE THREAD

**Issue by julioyildo** [amzn/selling-partner-api-models#485]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

As Data Engineer, when I call `GET /products/pricing/v0/competitivePrice` with  param `Skus = Laptop 12"`
I'm expecting to get successful api response when **_quotation marks_** is included in my **Sku**. 

## Current Behavior

Currently, I'm getting this error : 

```
{
    "payload": [
        { 
            "SellerSKU": "Laptop 12\\&quot;",
            "status": "ClientError"
        }
    ]
}
```

Quotation marks don't seem to be supported.

## Context/Screenshots

<img width="883" alt="Capture d’écran 2023-12-26 à 11 15 32" src="https://github.com/amzn/selling-partner-api-docs/assets/17247165/ec530ed6-6a7f-4c25-b627-89c8bc78614e">

## Your Environment

I'm testing this endpoint from NA region SP api `https://sellingpartnerapi-na.amazon.com` 
and for `ATVPDKIKX0DER` Marketplace_ID.

**Comment by hexrw** [comment]
Facing similar issues, most of the Selling Partner APIs has problems with SKUs that contain special symbols...

**Comment by leonardonakagawa** [comment]
Hello @julioyildo and @hexrw,

I'll get your feedback to our engineering team and understand if that is an actual issue and how this could be handled.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by rugved1991** [comment]
Hi @hexrw and @julioyildo,

Did you try encoding the characters before adding it in the query parameters? Please refer to [this documentation](https://developer-docs.amazon.com/sp-api/docs/url-encoding) for more information on URL encoding. If you are still facing the same issue after encoding the SKU, please open a developer support case and provide complete request response details along with headers showing both approaches. This will help prioritizing the issue to the backend team.

Best,
Rugved
Solutions Architect, SP-API
