### ISSUE TITLE
[BUG] [SP-API] [Issue] getLabels operation LabelType = PALLET returns no labels to print

### ISSUE THREAD

**Issue by godlyatheist** [amzn/selling-partner-api-models#486]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

An FBA inbound shipment containing 2 pallets should return an url containing the PDF file for 8 pallet labels when calling GET /fba/inbound/v0/shipments/{shipmentId}/labels

`from sp_api.base import Marketplaces
from sp_api.api import FulfillmentInbound

credentials = dict(#insert credentials#)

label_blob = FulfillmentInbound(credentials=credentials, marketplace=Marketplaces.US).get_labels(      
    shipment_id = 'FBA000000000',
    PageType = 'PackageLabel_Thermal',    
    LabelType = ['PALLET'],
    NumberOfPallets = 2        
    )
print(label_blob.payload['DownloadURL']) `

## Current Behavior

I get {'code': 'InvalidInput', 'message': 'Label for shipment cannot be found!', 'details': ''} when making the call.

## Context/Screenshots

I can't retrieve pallet labels via API

**Comment by shreeharsh-a** [comment]
@puppsupr

**Comment by puppsupr** [comment]
Hi,
Are you still facing this issue ? We have new version of [FBA APIs](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference). Please do let us know if you have started the migration.

All operations other than the following are deprecated and will be removed on December 20, 2024 from FBA v0.

getLabels
getBillOfLading
getPrepInstructions
getShipments
getShipmentItemsByShipmentId
getShipmentItems

For continued programmatic access to Fulfillment Inbound, migrate to the [Fulfillment Inbound v2024-03-20 API](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference).

**Comment by B3lg4r4th** [comment]
Hey guys, we faced the exact same issue yesterday, going through the old flow - 2D Barcodes can be generated, but the PALLET type returns "Label for shipment cannot be found" and that's it, no further info whatsoever. Sample request id: `4dcaa383-39d1-4d41-9e5e-6302a6febeb6`. Any additional info would be greatly appreciated.
