### ISSUE TITLE
upload document through Feeds API 

### ISSUE THREAD

**Issue by MrYing** [amzn/selling-partner-api-models#49]
I used the sellingpartner-api-documents-helper-java to upload document through Feeds API.

I constructed the XML and called the method (encryptAndUpload_fromString) to the specified path and return message is OK. I think the upload is successful. Then I go through the process of creatFeed, getFeed and getDocument. Finally, the returned message shows that the end-tag of the header is missing. I checked my XML and found that there is no such problem, so I want to ask if there are some problems in the encryption process, which leads to the error in verifying the correct file when the server parses it.

My xml content:
`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.02</DocumentVersion>
        <MerchantIdentifier>XXXXXXX</MerchantIdentifier>
    </Header>
    <MessageType>Product</MessageType>
    <PurgeAndReplace>true</PurgeAndReplace>
    <Message>
        <MessageID>10001</MessageID>
        <OperationType>Update</OperationType>
        <Product>
            <SKU>UK-XXXXXXX</SKU>
            <ProductTaxCode>A_GEN_TAX</ProductTaxCode>
            <LaunchDate>2021-01-05T08:17:01</LaunchDate>
            <DescriptionData>
                <Title> Bag Leakproof Lunch Box for Women Girls(Flamingo) - Test</Title>
                <Brand>XXXXXX</Brand>
                <Description>This is a test case ,please agree this product publish</Description>
                <BulletPoint>made in China</BulletPoint>
                <BulletPoint>500 thread count</BulletPoint>
                <BulletPoint>plain weave (percale)</BulletPoint>
                <BulletPoint>100% Egyptian cotton</BulletPoint>
                <Manufacturer>XXXXXX</Manufacturer>
                <SearchTerms>XXXXXX</SearchTerms>
                <SearchTerms>XXXXX-ying</SearchTerms>
                <ItemType>flat-sheets</ItemType>
                <IsGiftWrapAvailable>false</IsGiftWrapAvailable>
                <IsGiftMessageAvailable>false</IsGiftMessageAvailable>
            </DescriptionData>
            <ProductData>
                <Home>
                    <Parentage>variation-parent</Parentage>
                    <VariationData>
                        <VariationTheme>Size-Color</VariationTheme>
                    </VariationData>
                    <Material>cotton</Material>
                    <ThreadCount>500</ThreadCount>
                </Home>
            </ProductData>
        </Product>
    </Message>
</AmazonEnvelope>`

I got the return content:

`<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.02</DocumentVersion>
		<MerchantIdentifier>XXXXXXX</MerchantIdentifier>
	</Header>
	<MessageType>ProcessingReport</MessageType>
	<Message>
		<MessageID>1</MessageID>
		<ProcessingReport>
			<DocumentTransactionID>XXXXXXX</DocumentTransactionID>
			<StatusCode>Complete</StatusCode>
			<ProcessingSummary>
				<MessagesProcessed>0</MessagesProcessed>
				<MessagesSuccessful>0</MessagesSuccessful>
				<MessagesWithError>1</MessagesWithError>
				<MessagesWithWarning>0</MessagesWithWarning>
			</ProcessingSummary>
			<Result>
				<MessageID>0</MessageID>
				<ResultCode>Error</ResultCode>
				<ResultMessageCode>5001</ResultMessageCode>
				<ResultDescription>XML Parsing Fatal Error at Line 1, Column 226: The element type &quot;Header&quot; must be terminated by the matching end-tag &quot;&lt;/Header&gt;&quot;. The element type &quot;Header&quot; must be terminated by the matching end-tag &quot;&lt;/Header&gt;&quot;.</ResultDescription>
			</Result>
		</ProcessingReport>
	</Message>
</AmazonEnvelope>`

You can view the resultDescription ,  I have tried many solutions, and all the return values are this error. For example, it is also this error when the message is not transmitted; it is also this error when the header is deleted。Can you tell me how to solve this problem。

**Comment by NetRushJacob** [comment]
I'll add my plight with the ProductImage XML feed to this, albeit with slightly different error results:
```
<ResultMessageCode>5001</ResultMessageCode>
<ResultDescription>XML Parsing Fatal Error at Line -1, Column -1: Premature end of file. Premature end of file.</ResultDescription>

```

**Comment by ericblade** [comment]
@MrYing i seee you just closed this, did you figure out the problem?
