### ISSUE TITLE
Getting random cURL error on calling spapi 

### ISSUE THREAD

**Issue by pawan1793** [amzn/selling-partner-api-models#491]
I'm trying to call pricing api and inventory api , sometimes it works sometimes it dosen't work 
getting following error 
 **cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to sellingpartnerapi-na.amazon.com:443**
 and 
  **cURL error 35: error:0A000126:SSL routines::unexpected eof while reading**

**Comment by harguph** [comment]
Hello @pawan1793 ,

It seems to be an issue with your OS / network. Please try sending requests through a different host & network.


```
this usually happens when number of parallel request increases ....
```
Also, please ensure there are following rate limitations.
