### ISSUE TITLE
[BUG] [SP-API] [Issue] getCompetitivePricing and amazon's own pricing controls do not match

### ISSUE THREAD

**Issue by ericblade** [amzn/selling-partner-api-models#494]
Some of my inventory just got flagged for having prices that are too high.

Every single one of these prices came from the getCompetitivePricing API.

Also, most still have vendors with active listings available that are priced higher.  

One was last sold by Amazon at nearly 5 *times* the price I'm asking.

Make these APIs make sense please.

**Comment by shreeharsh-a** [comment]
@leonardonakagawa

**Comment by leonardonakagawa** [comment]
Hi @ericblade!

We appreciate your feedback, and I'll contact our backend team regarding this issue. For now, we have the **new** getCompetitiveSummary operation, which allows you to retrieve the current featured offers for a batch of items by ASIN. This operation allows up to 20 ASIN requests in a single batch.

For that operation you can retrieve the following information: `featuredBuyingOptions`, `referencePrices`, `lowestPricedOffers`. That operation contains our most up-to-date data.

You can find details regarding this in our [Tutorial: Retrieve a list of featured offers for a batch of up to 20 ASINs](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide#tutorial-retrieve-a-list-of-featured-offers-for-a-batch-of-up-to-20-asins).

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by ericblade** [comment]
That looks to be an improvement, for sure.  That'll definitely help in implementing repricing suggestions into my application.  *IF* the referencePrices are actually there.  MOST of the times I get a price warning on my own products, the reference pricing says "None", but will only let me price the items for a LOT lower than what the existing offers are.

**Comment by leonardonakagawa** [comment]
Hi @ericblade,

Do you have an ASIN example where this is happening?

**Comment by ericblade** [comment]
> Hi @ericblade,
> 
> Do you have an ASIN example where this is happening?

0231130899, B00002JXEA, 1603201769, 0872205932

.... pretty much my entire catalog is where this is happening.
