### ISSUE TITLE
[BUG] [SP-API] [GET_VENDOR_INVENTORY_REPORT Problems with report_Options]

### ISSUE THREAD

**Issue by ThermalSense** [amzn/selling-partner-api-models#495]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
GET_VENDOR_INVENTORY_REPORT
## Expected Behavior
I'm expecting reports with the following parameters: 

request_params = {
    "marketplaceIds": marketplace_id,
    "reportTypes" : "GET_VENDOR_INVENTORY_REPORT",
    "reportOptions": {
        "reportPeriod":"WEEK",
        "sellingProgram":"RETAIL",
        "distributorView":"MANUFACTURING"
    },
    "dataStartTime": "2023-11-05",
    "dataEndTime": "2023-11-11",
}

reports = requests.get(
    endpoint
    + "/reports/2021-06-30/reports"
    + "?"
    + urllib.parse.urlencode(request_params),
    headers={
        "x-amz-access-token": access_token
    }
)

## Current Behavior
When I submit the parameters I receive reports with the following parameters: 

{
  "reportSpecification" : {
    "reportType" : "GET_VENDOR_INVENTORY_REPORT",
    "reportOptions" : {
      "reportPeriod" : "DAY",
      "sellingProgram" : "FRESH",
      "distributorView" : "MANUFACTURING"
    },
    "dataStartTime" : "2024-01-03",
    "dataEndTime" : "2024-01-04",
    "marketplaceIds" : [ "A1PA6795UKMFR9" ]
  },
  "inventoryAggregate" : [ ],
  "inventoryByAsin" : [ ]
}

It seems as if the api doesn't recognize the submitted reportOptions. I get the same results when I leave the report Options out of my request. Do I miss something?

**Comment by shreeharsh-a** [comment]
@chrisskhoury

**Comment by ThermalSense** [comment]
Hello,

We have resolved the issue, but I cannot provide the exact steps we took due to the amount of time that has passed. However, I recommend looking into this Python library: https://python-amazon-sp-api.readthedocs.io/en/v1.4.0/endpoints/reports.html.

Please review the tutorials provided; they were helpful, and the solution involved using Python.
