### ISSUE TITLE
[BUG] [SP-API] Discrepancies between Order reports and Sales API for "Trial" orders 

### ISSUE THREAD

**Issue by clegendre** [amzn/selling-partner-api-models#497]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

We are encountering discrepancies between order reports (e.g., GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL) and the `getOrderMetrics` endpoint. This is primarily due to TBYB units (Try Before You Buy) affecting the reported item price. In all orders and shipping reports, the item price is set to 0 when an item is returned during the TBYB trial period.

The TBYB order flow is as follows:

1. On Trial
2. Pending Return
3. Payment Complete
4. Once bought by the customer, it transitions to the Complete status.

During the Pending Return status, the order is updated with item_price = 0 in all orders and shipping reports. However, the `getOrderMetrics` endpoint does not reflect this update, resulting in gross sales aggregation that includes these Pending Return units.

The question arises: Is this a bug? Should items shipped and then returned in the context of the TBYB feature be considered in the final gross sales calculation or not?
## SP-API Name and Version or Report/Feed Type
* getOrderMetrics https://developer-docs.amazon.com/sp-api/docs/sales-api-v1-reference
* GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL

## Expected Behavior

orderMetrics updated without accounting for Returned TBYB order items.
OR
Orders reports with item_price > 0 to keep track of the price when the user start the order.

**Comment by shreeharsh-a** [comment]
@chrisskhoury
