### ISSUE TITLE
[BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by minifiredragon** [amzn/selling-partner-api-models#499]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
ListingsApi 
patchListingsItem 
listings/2021-08-01/items/

## Expected Behavior

using op: delete to un-parent a listing, and it will not delete requested attributes.

## Current Behavior

Sent:

```
{
"productType":"SUGAR_CANDY",
"patches":[
     {"op":"delete",
      "path":"/attributes/variation_theme",
      "value":[
                   {"name":"SIZENAME"}
                 ]},
    {"op":"delete",
     "path":"/attributes/parentage_level",
     "value":[
                 {
                   "marketplace_id":"ATVPDKIKX0DER",
                   "value":"Child"
                }
               ]},
    {"op":"delete",
      "path":"/attributes/child_parent_sku_relationship",
      "value":[
                 {
                  "marketplace_id":"ATVPDKIKX0DER",
                  "child_relationship_type":"variation",
                  "parent_sku":"xxxxxx-parent"
                 }]
       }]
}
```
Response is ACCEPTED.  But nothing changes.

**Comment by shreeharsh-a** [comment]
@ritikacd

**Comment by rugved1991** [comment]
Hi @minifiredragon,

Currently it is not possible to remove the parent child relationship by deleting the attributes. You will have to delete the child and parent SKUs and then create them again separately. Please try deleting the SKUs using [deleteListingsItem](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-reference#deletelistingsitem). 

Best,
Rugved
Solutions Architect, SP-API

**Comment by weiler63** [comment]
Hi @rugved1991 the issue with deleting the parent is if it has existing children. Also the recreate function is not 100%, please make this part of patchlistings instead of this delete workaround
