### ISSUE TITLE
[FEATURE] How to upload main product and all variations in one go via "PutListingsItem"

### ISSUE THREAD

**Issue by wszwc** [amzn/selling-partner-api-models#516]
How are you guys, I'm uploading products using "putListingsItem" and according to the documentation description I seem to be able to associate my main product and variations via fields like "parentage_level", "child_parent_sku_relationship", etc. But this means I need to access "putListingsItem" many times to upload variations of the product one after another. So I'm wondering if it's possible to upload all the variations in one go via "putListingsItem" and if so, how can I organize the data structure. Thanks for the answer, please

**Comment by chapmanjw** [comment]
@wszwc Variations of a product are separate listings. When creating a variation family, you first create the "parent" SKU that acts as a container for the family. You then separately create each "child" SKU referencing the "parent" SKU.

As the Listings Items API operations only operate on one SKU at a time, you need to call separately for each SKU in the variation family. If you want to submit the whole variation family together, you could use the JSON_LISTINGS_FEED to send the collection of SKUs in one feed submission.
