### ISSUE TITLE
How to update the inventory quantity of a product from vendor side?

### ISSUE THREAD

**Issue by steven-switchboardcloud** [amzn/selling-partner-api-models#528]
Hi there,

I've been looking at the many discussions and issues in this repo on how to update the inventory quantity of a product but haven't had luck achieving this specifically for `vendors`

The three APIs I have looked into are

1. Feeds API using `POST_INVENTORY_AVAILABILITY_DATA`
2. Listings API `patchListingsItem`
3. Vendor Direct Fulfillment Inventory `submitInventoryUpdate`

I am convinced that number 3 might be the one we need but this requires the `Direct-To-Consumer Shipping` role.

We actually tried applying for this role on our dev profile but we were rejected.

Regards to the Feeds API, we went through this guide (https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide) with some success until Step 4 where we try to POST and create a feed, the API responds back with
```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid request parameters",
            "details": ""
        }
    ]
}
```

As for the Listings API we tried making a PATCH request with the following request body (assume the codes and ids are there)
`https://sellingpartnerapi-fe.amazon.com/listings/2021-08-01/items/<CODE>/<SKU>?marketplaceIds=<MARKETPLACEID>`
```
{
  "productType": "PRODUCT",
  "patches": [
    {
      "op": "replace",
      "path": "/attributes/fulfillment_availability",
      "value": [
        {
          "fulfillment_channel_code": "DEFAULT",
          "quantity": 5
        }
      ]
    }
  ]
}
```

but then received a response that unfortunately I cannot find anyone else has experienced.
```
{
    "sku": "<ASSUME SKU>",
    "status": "INVALID",
    "submissionId": "181b19c9706544258a0d42bb3ec7842b",
    "issues": [
        {
            "code": "90000900",
            "message": "The attributes are invalid.",
            "severity": "ERROR",
            "attributeNames": [
                "fulfillment_availability"
            ],
            "categories": []
        }
    ]
}
```

Would be great if anyone could share their experience updating inventory from the vendor side and how they did it. Or if anyone could see what I'm missing...

Thanks!

**Comment by Alex-Yub** [comment]
I've got the same problem here
