### ISSUE TITLE
Unable to Find ABIS_BOOK Product Type for Listings and Definitions

### ISSUE THREAD

**Issue by paul0440** [amzn/selling-partner-api-models#531]
Hello,

I've been encountering an issue with the Selling Partner API where I am unable to find or use the ABIS_BOOK product type. My intention is to manage book listings, but despite my efforts, I am facing challenges with both retrieving the product type definition and using it in a putListingsItem operation.

### Issue Details
Retrieving Product Type Definition: When attempting to retrieve the definition for ABIS_BOOK through the appropriate API operations, I do not receive the expected product type details. Instead, the API returns PRODUCT as the product type, which is too generic and not suited for books specifically.

Using putListingsItem Operation: Attempting to use the putListingsItem operation with ABIS_BOOK results in an error with code 4000003, indicating an issue with the product type. However, using PRODUCT as a fallback, as suggested by the API's response to the definition request, does not allow for book-specific attributes and fails to meet the needs for listing books accurately.

### Additional Context
I have verified that my application has the necessary permissions and scopes for managing listings.
I am targeting the correct regional endpoint for my marketplace.

I would greatly appreciate any guidance on how to correctly manage book listings with the appropriate product type or any advice on what might be causing these issues with ABIS_BOOK.

Thank you for your time and assistance.

**Comment by chapmanjw** [comment]
The ABIS_BOOK product type launched on the APIs a couple of months ago. When this issue was created, it was not yet available on the APIs.
