### ISSUE TITLE
[BUG] [SP-API] SearchCatalog response contains less items than it should 

### ISSUE THREAD

**Issue by iabukai** [amzn/selling-partner-api-models#538]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ x] Other... Please describe: I'm unsure that my problem is a feature or a bug
</code></pre>

Searchcatalog results contain less data than expected

## SP-API Name and Version or Report/Feed Type
https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#searchcatalogitems

## Expected Behavior
My SP API response contains 4 items 
The request
`{
  "marketplaceIds": [
    "A1F83G8C2ARO7P"
  ],
  "includedData": [
    "summaries"
  ],
  "keywords": [
    "Lectures Certain Professor farrell gill"
  ],
  "pageSize": 20
}`

## Current Behavior
We've started to use SP API responses so we can stop using MWS API due to its deprecation.
I have a question about the following response that we are getting from  the [searchcatalogitems ](https://developer-docs.amazon.com/sp-api/docs/catalog-items-api-v2022-04-01-reference#searchcatalogitems)endpoint
Response:
```
{
  "numberOfResults": 1,
  "pagination": null,
  "refinements": {
    "brands": [],
    "classifications": [
      {
        "numberOfResults": 4,
        "displayName": "Books",
        "classificationId": "1025612"
      }
    ]
  },
  "items": [
    {
      "asin": "B06XSX7BYS",
      ....
    }
  ]
} 
```
My request is the following:
```
{
  "marketplaceIds": [
    "A1F83G8C2ARO7P"
  ],
  "includedData": [
    "summaries"
  ],
  "keywords": [
    "Lectures Certain Professor farrell gill"
  ],
  "pageSize": 20
}
```

As you can see, the numberOfResults is 4 based on the classification refinement. However, if we use the classification ID or multiple IDs, the results return with 1 element. We would like to extend the results set, not flatten it.

How should we use the searchcatalogitems endpoint to get all four results for our keywords?
Should we use a different endpoint?
The MWS response contained all the 4 responses. See the attached document [mws request/respons pair].
[mws example.txt](https://github.com/amzn/selling-partner-api-docs/files/14651426/mws.example.txt)

## Context/Screenshots
What are you trying to accomplish?
I want a response that contains same/similar items that MWS does.

## Your Environment
AmazonUK

**Comment by rugved-bodke-stigya** [comment]
It's still there, unable to the pagination data in the response for search_catalog_items
