### ISSUE TITLE
unable replace or delete child_parent_sku_relationship for a child sku,

### ISSUE THREAD

**Issue by yongweixie** [amzn/selling-partner-api-models#539]
I can't replace or delete child_parent_sku_relationship for a child sku,how can i change the relationships?

**Comment by chapmanjw** [comment]
@yongweixie This is not currently supported directly. You can either delete the parent SKU to break apart the relationship family or delete the child SKU to remove it from a variation family. And then re-create the SKUs. 

In the future (hopefully early 2025, lots of pieces in-flight needed to make this work), you will be able to submit a new value for `child_parent_sku_relationship` or a PATCH delete on `child_parent_sku_relationship` to re-parent a child SKU or remove it from a variation family.
