### ISSUE TITLE
Using the PATCH method to delete a previously set value in the of maximum_seller_allowed_price or minimum_seller_allowed_price [BUG] [SP-API] [Issue]

### ISSUE THREAD

**Issue by siktec-lab** [amzn/selling-partner-api-models#542]
When using the PATCH method to update a product listing, the `maximum_seller_allowed_price` or `minimum_seller_allowed_price` values are not deleted when they are set to 0.
``` json
{
    "op": "replace",
    "path": "/attributes/purchasable_offer",
    "value": [
        {
            "marketplace_id": "ATVPDKIKX0DER",
            "currency": "USD",
            "maximum_seller_allowed_price": [
                {
                    "schedule": [
                        {
                            "value_with_tax": 0
                        }
                    ]
                }
            ]
        }
    ]
}
```

It may make sense; for some use cases, the value 0 is a valid value, but for our use case, we need to delete it.

So, Trying to delete the value by using the `delete` operation of `patchListingsItem` does not delete the value but instead returns an error.
The error is unclear: `"An internal error has occurred. Please try again.`

``` json
{
    "op": "delete",
    "path": "/attributes/purchasable_offer",
    "value": [
        {
            "marketplace_id": "ATVPDKIKX0DER",
            "currency": "USD", // tried with and without this
            "maximum_seller_allowed_price": [ // tried with many variations of this
                {
                    "schedule": [ // and this
                        {
                            "value_with_tax": 0
                        }
                    ]
                }
            ]
        }
    ]
}
```

The issue/question is, how can we delete the value of `maximum_seller_allowed_price` or `minimum_seller_allowed_price` using the PATCH method?
Is it even possible?

Thanks.

**Comment by mrhdias** [comment]
To remove the minimum_seller_allowed_price and maximum_seller_allowed_price use an old start and end date.

```json
{
    "header": {
        "sellerId": "__YOUR_SELLER_ID__",
        "version": "2.0",
        "issueLocale": "en_US"
    },
    "messages": [
        {
            "messageId": 1,
            "sku": "__YOUR_SKU__",
            "operationType": "PATCH",
            "productType": "PRODUCT",
            "patches": [
                {
                    "op": "replace",
                    "path": "/attributes/purchasable_offer",
                    "value": [
                        {
                            "audience": "ALL",
                            "currency": "EUR",
                            "our_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 15.00
                                        }
                                    ]
                                }
                            ],
                            "minimum_seller_allowed_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 10.00,
                                            "start_at": "2024-01-01",
                                            "end_at": "2024-01-31"
                                        }
                                    ]
                                }
                            ],
                            "maximum_seller_allowed_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 20.00,
                                            "start_at": "2024-01-01",
                                            "end_at": "2024-01-31"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by LysakVitaliy** [comment]
I tried the approach suggested by mrhdias - unfortunately, it didn't help me (

**Comment by yusufatalar93** [comment]
Schedule items do not have properties named start_at and end_at. They only have a property named value_with_tax.
@mrhdias 

> {
    "header": {
        "sellerId": "__YOUR_SELLER_ID__",
        "version": "2.0",
        "issueLocale": "en_US"
    },
    "messages": [
        {
            "messageId": 1,
            "sku": "__YOUR_SKU__",
            "operationType": "PATCH",
            "productType": "PRODUCT",
            "patches": [
                {
                    "op": "replace",
                    "path": "/attributes/purchasable_offer",
                    "value": [
                        {
                            "audience": "ALL",
                            "currency": "EUR",
                            "our_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 15.00
                                        }
                                    ]
                                }
                            ],
                            "minimum_seller_allowed_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 10.00,
                                            "start_at": "2024-01-01",
                                            "end_at": "2024-01-31"
                                        }
                                    ]
                                }
                            ],
                            "maximum_seller_allowed_price": [
                                {
                                    "schedule": [
                                        {
                                            "value_with_tax": 20.00,
                                            "start_at": "2024-01-01",
                                            "end_at": "2024-01-31"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by yusufatalar93** [comment]
Schedule items do not have properties named start_at and end_at. They only have a property named value_with_tax.
@mrhdias
`{
  "minimum_seller_allowed_price": {
    "title": "Purchasable Offer Minimum Seller Allowed Price",
    "description": "The attribute indicates the Purchasable Offer Minimum Seller Allowed Price of the product",
    "type": "array",
    "minItems": 1,
    "items": {
      "type": "object",
      "required": [],
      "properties": {
        "schedule": {
          "title": "Purchasable Offer Minimum Seller Allowed Price Schedule",
          "description": "The attribute indicates the Purchasable Offer Minimum Seller Allowed Price Schedule of the product",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": [],
            "properties": {
              "value_with_tax": {
                "title": "Minimum Seller Alllowed Price",
                "description": "Provide the minimum seller allowed price",
                "editable": true,
                "hidden": false,
                "examples": [
                  "259.99"
                ],
                "type": "number"
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    }
  }
}
`

**Comment by LysakVitaliy** [comment]
Yes, it doesn't have. 
In my case when I applied **start_at** and **end_at** Amazon API deleted min/max prices without any issues or warnings.

**Comment by matteosala2301-boop** [comment]
I have tried the solution provided by mrhdias with the start_at and end_at trick but the minimum and maximum value it actually clears for about 10 minutes and then goes back to the ones that are passed during the patch operation...do you have some tips please?
