### ISSUE TITLE
A flat file containing Japanese characters becomes garbled. (in SP-API Report)

### ISSUE THREAD

**Issue by sugaular** [amzn/selling-partner-api-models#545]
I am parsing GET_MERCHANT_LISTINGS_ALL_DATA.
Japanese characters are garbled.
XML files (e.g. GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL) were fine.
Please tell me what to do.

**Comment by supoman-service** [comment]
Garbled Japanese characters need to be converted to
Encoding.GetEncoding("Shift_JIS") to try, but I have not encountered this
situation so far. After the revision, almost all of them are UTF-8 encoded.

sugaular ***@***.***> 于2024年5月9日周四 18:26写道：

**Comment by sugaular** [comment]
I tried shift_jis, cp932, and UTF-8, but all the characters were garbled.I'm also concerned that an error will occur if I don't use encode and decode.
### Source excerpt
    report_document_id = get_report_response.report_document_id
    if report_document_id != None:
        get_report_document_response = reports_api.get_report_document(report_document_id=report_document_id)
        url = get_report_document_response.url

        import requests
        import codecs
        res = requests.get(url)

        report_text = res.text
        #report_bytes = report_text.encode('UTF-8', "ignore")
        #report_text = report_bytes.decode('UTF-8', "ignore")

        #report_bytes = report_text.encode('cp932', "ignore")
        #report_text = report_bytes.decode('cp932', "ignore")

        report_bytes = report_text.encode('shift_jis', "ignore")
        report_text = report_bytes.decode('shift_jis', "ignore")

        #s.encode('cp932', "ignore")
        #f = open('../data/orders_xml.txt', 'w', encoding='UTF-8')
        #f = open('../data/orders_xml.txt', 'w', encoding='cp932')
        f = open('../data/orders_xml.txt', 'w', encoding='shift_jis')
        f.write(report_text)
        f.close()
