### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 setPackingInformation NOT working

### ISSUE THREAD

**Issue by nafberger** [amzn/selling-partner-api-models#552]
when calling the set packing information it always retuns this error

ERROR: Package group pgxxxxx0ea41 did not contain expected items and/or quantities

**Comment by ssamran15** [comment]
Hi @nafberger, were you able to find a solution to the error? or anyone here were able to submit the Packing information using setPackingInformation API call?

**Comment by nafberger** [comment]
post me please your payload, it worjs by me. post me the error response too, and i will try to help

**Comment by Ironkyy** [comment]
I still have the same problem now. Can this function be used normally?

**Comment by puppsupr** [comment]
Hi Team,
We understand the frustration here. Fix got deployed and the API should be working as expected. If you still face issues, can you please provide full request and response along with the inbound plan ID to did more ?

**Comment by amistry007** [comment]
@puppsupr please see my error as commented here with full request and responses https://github.com/amzn/selling-partner-api-models/issues/551#issuecomment-2211047023

**Comment by amistry007** [comment]
@puppsupr any update on progress of this bug?

**Comment by amistry007** [comment]
@puppsupr can we have an acknowledgement that someone is actually looking into this?

**Comment by shantikolli** [comment]
+1


Same issue. It has been not resolved until now. Please provide a date when this is going to be fixed?

**Comment by puppsupr** [comment]
Hi All,
Our team has identified the bug and working to resolve it ASAP. Will provide an update once resolved.

**Comment by sheikhdanish** [comment]
Has the issue been resolved? Please provide an update when possible.

**Comment by amistry007** [comment]
@puppsupr  you updated this ticket 2 weeks ago and still we have no further update. Please can you keep us informed on progress on this and when we can expect this to be fixed. Not sure how you expect your users to plan their workload when you provide such bad communication.

**Comment by puppsupr** [comment]
Hi All,
The issue have been fixed and deployed. Can you please check and let us know if the issue still occurs.

**Comment by amistry007** [comment]
@puppsupr still same issue see my comment here: https://github.com/amzn/selling-partner-api-models/issues/3951#issuecomment-2257690392

**Comment by puppsupr** [comment]
https://github.com/amzn/selling-partner-api-models/issues/3951 Please track the related thread for updates.
