### ISSUE TITLE
I want to process the Amazon order refund on a third-party platform, and put the third-party platform’s RMA information is synchronized to the Amazon platform, which API should I use?

### ISSUE THREAD

**Issue by elcnu986** [amzn/selling-partner-api-models#553]
I want to process the Amazon order refund on a third-party platform, and put the third-party platform’s
RMA information is synchronized to the Amazon platform, which API should I use?

**Comment by supoman-service** [comment]
There seems to be no such interface

elcnu ***@***.***> 于2024年5月9日周四 18:27写道：

**Comment by leonardonakagawa** [comment]
Hi @supoman-service, 

Could you please provide us details of what is the API product you are looking for and any type of Data on how this would benefit you?

We would love to hear and bring new Ideas to our Product Team.

Best,
Leonardo
