### ISSUE TITLE
Fulfillment Inbound API v2024-03-20 setPackingInformation has a bug

### ISSUE THREAD

**Issue by daiqi77777** [amzn/selling-partner-api-models#554]
ERROR: Package group pgxxxxxxxx did not contain expected items and/or quantities
I hava two SKU ,and every sku ship 10 units; offer four box, and every box has a sku and 5 units,
this is my params when I setPackingInformation ; 

'packageGroupings' => [
            [
                'boxes' => [
                    [
                        'boxId' => 'box_000001',
                        'templateName' => 'box_000001',
                        'contentInformationSource' => 'BOX_CONTENT_PROVIDED',
                        'quantity' => 1,
                        'dimensions' => ['unitOfMeasurement' => 'IN', 'length' => 9, 'width' => 8, 'height' => 7],
                        'weight' => ['unit' => 'LB', 'value' => 3],
                        'contents' => [
                            [
                                'labelOwner' => 'SELLER',
                                'prepOwner' => 'SELLER',
                                'msku' => 'SKU1',
                                'quantityInBox' => 5,
                            ],
                        ],

                    ],
                    [
                        'boxId' => 'box_000002',
                        'templateName' => 'box_000002',
                        'contentInformationSource' => 'BOX_CONTENT_PROVIDED',
                        'quantity' => 1,
                        'dimensions' => ['unitOfMeasurement' => 'IN', 'length' => 10, 'width' => 9, 'height' => 7],
                        'weight' => ['unit' => 'LB', 'value' => 3],
                        'contents' => [
                            [
                                'labelOwner' => 'SELLER',
                                'prepOwner' => 'SELLER',
                                'msku' => 'SKU1',
                                'quantityInBox' => 5,
                            ]
                        ],

                    ],

                    [
                        'boxId' => 'box_000003',
                        'templateName' => 'box_000003',
                        'contentInformationSource' => 'BOX_CONTENT_PROVIDED',
                        'quantity' => 1,
                        'dimensions' => ['unitOfMeasurement' => 'IN', 'length' => 11, 'width' => 10, 'height' => 9],
                        'weight' => ['unit' => 'LB', 'value' => 4],
                        'contents' => [
                            [
                                'labelOwner' => 'SELLER',
                                'prepOwner' => 'SELLER',
                                'msku' => 'SKU2',
                                'quantityInBox' => 5,
                            ]
                        ],

                    ],
                    [
                        'boxId' => 'box_000004',
                        'templateName' => 'box_000004',
                        'contentInformationSource' => 'BOX_CONTENT_PROVIDED',
                        'quantity' => 1,
                        'dimensions' => ['unitOfMeasurement' => 'IN', 'length' => 11, 'width' => 11, 'height' => 9],
                        'weight' => ['unit' => 'LB', 'value' => 4],
                        'contents' => [
                            [
                                'labelOwner' => 'SELLER',
                                'prepOwner' => 'SELLER',
                                'msku' => 'SKU2',
                                'quantityInBox' => 5,
                            ]
                        ],

                    ],

                ],
                'packingGroupId' => 'pgxxxxxxxxxx',
            ],
        ];

**Comment by harguph** [comment]
@MeenaAmz

**Comment by MeenaAmz** [comment]
This should be resolved now. Please review and let us know if you still see issues

**Comment by emakunin** [comment]
@MeenaAmz I still face the same issue. It's not solved. Potentially recent release broke it. See https://developer-docs.amazon.com/sp-api/changelog/update-fulfillment-outbound-api-v2020-07-01-adds-deliveryoffers-and-updates-getfulfillmentorder-and-createfulfillmentorder

**Comment by MeenaAmz** [comment]
@emakunin This is a release for fulfillment outbound API which will not impact the fulfillment inbound API operations. Can you please provide details on what issues you are seeing with request and response.

**Comment by emakunin** [comment]
My bad. It is a wrong link. I meant: https://developer-docs.amazon.com/sp-api/changelog/general-availability-of-fulfillment-inbound-api-v2024-03-20 that was released on June 27th.

The issue seems to be a duplicate of https://github.com/amzn/selling-partner-api-models/issues/3951#issuecomment-2203529254
