### ISSUE TITLE
[QUESTION] [SP-API] Fulfillment Inbound v2024-03-20 API getShipments and getShipmentItems deprecated

### ISSUE THREAD

**Issue by luigel** [amzn/selling-partner-api-models#555]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: Question
</code></pre>

## SP-API Name and Version or Report/Feed Type
Fulfillment Inbound v2024-03-20 API getShipments and getShipmentItems deprecated. What is the same implementation in v2024-03-20 for these operations?

**Comment by jamesquinton** [comment]
We are also running into this issue - currently we collect a list of active Inbound Shipments using `getShipments` and then collect the shipment items using `getShipmentItemsByShipmentId`. In the updated API version, there does not seem to be any equivalent endpoints.

Additional confusion is now being caused;

On this page it is saying they WILL NOT be deprecated: https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference.
On this page it is saying they WILL be deprecated: https://developer-docs.amazon.com/sp-api/docs/sp-api-deprecations.

Is it possible to get some clarity on exactly what will be deprecated and what our migration options are with the new versions?
