### ISSUE TITLE
[BUG] [SP-API] [Regression] Fulfillment Inbound v2024-03-20 API provides 0 methods to retrieve inbounded items

### ISSUE THREAD

**Issue by emakunin** [amzn/selling-partner-api-models#558]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

According to the anounce (https://developer-docs.amazon.com/sp-api/changelog/get-early-access-to-new-fulfillment-inbound-api-v2024-03-20) V0 inbound API will stop working soon. However it contains crucial methods (getshipmentitems, getshipmentitemsbyshipmentid) that provide `QuantityShipped` and `QuantityReceived` information. New `Fulfillment Inbound v2024-03-20 API` does not provide any means to retrive such data.

The fields are important as quite often during inbound process FBA recieves less items than was shipped. But the shipments will be still closed with less items than shipped. It brakes automation tools and will force our application customers to manually check the information on SellerCentral.

Inventory API [getinventorysummaries](https://spapi.cyou/en/references/fbainventory-api-v1-reference.html#getinventorysummaries) seems to have a limitation that will not allow checking inventor inbound process as well
>  If specified, all inventory summaries that have changed since then are returned. You must specify a date and time that is no earlier than 18 months prior to the date and time when you call the API. Note: Changes in inboundWorkingQuantity, inboundShippedQuantity and inboundReceivingQuantity are not detected

## SP-API Name and Version or Report/Feed Type
* Fulfillment Inbound v2024-03-20 API 
* Fulfillment Inbound API v0

## Expected Behavior

Inbound API should provide means to obtain shipped VS inbound items quantities. Ideally defective/rejected/etc. Alternatively access to [getShipmentItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitems) and/or [getShipmentItemsByShipmentId](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitemsbyshipmentid) should remain untouched post-deprecation. Similarly to `getLabels` and  `getBillOfLading` that will remain operational according to [FAQ](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-faq#which-operations-in-the-fulfillment-inbound-v0-api-are-deprecated)

## Current Behavior

Currently customers can obtain inbound quantities by using [getShipments](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipments) and then [getShipmentItems](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitems) or [getShipmentItemsByShipmentId](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#getshipmentitemsbyshipmentid)

The methods return [InboundShipmentItem](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#inboundshipmentitem) struct that contains `QuantityShipped` and `QuantityReceived` fields.

## Context/Screenshots

Our integration needs to validate shipped VS inbound quanties once an inbound shipment is closed as they may differ. Without an API we have to rely on SellerCentral UI to check notifications or shipments dashboards manully. 

The only alternative to receive this info seems to be [FBA inbound-performance report](https://developer-docs.amazon.com/sp-api/docs/report-type-values-fba#fba-inbound-performance-report) that is much less convenient for automation and will reuire migration. **Also this report contains completely wrong data** I requested a couple of them and they do not report problematic shipments. Or return the ones that are marked ad CLOSED with no errors in Seller central

Related issues:
1. https://github.com/amzn/selling-partner-api-models/issues/555

## Your Environment

We host an selling-partner application that tracks inbound shipments. The application uses  "Fulfillment Inbound API v0" currently.

**Comment by emakunin** [comment]
The issue is still valid.

**Comment by SuperFlyingCow** [comment]
Have you all able to get received and shipped quantity through the latest API?

**Comment by emakunin** [comment]
Noop, you'll have to use V0 API. Note that it return inconsistent data. Even after shipments are "CLOSED" Amazon still keeps updating quantities

**Comment by vgarciasouza** [comment]
Is this issue solved? I need to get QuaantityReceived, and can't find it on Fulfillment Inbound API v2024-03-20 Reference

**Comment by PhilJeffcock** [comment]
Bump.
