### ISSUE TITLE
[BUG] [SP-API] [Issue] Data Kiosk SKU Economics dataset query authorization issues (403)

### ISSUE THREAD

**Issue by hexrw** [amzn/selling-partner-api-models#567]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type

Data Kiosk 2023-11-15 createQuery
`POST /dataKiosk/2023-11-15/queries`

## Expected Behavior

Query gets created and report document will start generating

## Current Behavior

Returns 403 unauthorized even though the very same data is accessible and retrievable from other Selling Partner APIs including the old Reports API thus this response makes no sense.

## Context/Screenshots

I'm just trying to retrieve the report. Every single one of the other APIs and even all other Data Kiosk dataset queries work as expected.

**Request:**

```json
{
    "query": "query SalesBase{analytics_economics_2024_03_15{economics(endDate:\"2024-04-29\" marketplaceIds:[\"A1PA6795UKMFR9\"]aggregateBy:{date:DAY,productId:MSKU}startDate:\"2024-02-29\"){childAsin netProceeds{perUnit{amount currencyCode}total{amount currencyCode}}parentAsin startDate endDate marketplaceId msku sales{unitsRefunded unitsOrdered refundedProductSales{amount}orderedProductSales{amount}netUnitsSold netProductSales{amount}averageSellingPrice{amount}}fees{feeTypeName charge{aggregatedDetail{quantity amount{amount}amountPerUnit{amount}promotionAmount{amount}taxAmount{amount}totalAmount{amount}}components{name aggregatedDetail{taxAmount{amount}amount{amount}amountPerUnit{amount}promotionAmount{amount}quantity totalAmount{amount}}}}}}}}"
}
```

**Response:**
```json
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Unauthorized to access requested fields.",
      "details": "Unauthorized to access: [analytics_economics_2024_03_15.economics.endDate, analytics_economics_2024_03_15.economics.netProceeds.total.currencyCode, analytics_economics_2024_03_15.economics.sales.unitsRefunded, analytics_economics_2024_03_15.economics.sales.averageSellingPrice.amount, analytics_economics_2024_03_15.economics.sales.refundedProductSales.amount, analytics_economics_2024_03_15.economics.fees.charge.components.aggregatedDetail.quantity, analytics_economics_2024_03_15.economics.sales.netUnitsSold, analytics_economics_2024_03_15.economics.marketplaceId, analytics_economics_2024_03_15.economics.fees.charge.components.aggregatedDetail.totalAmount.amount, analytics_economics_2024_03_15.economics.fees.charge.aggregatedDetail.totalAmount.amount, analytics_economics_2024_03_15.economics.fees.feeTypeName, analytics_economics_2024_03_15.economics.fees.charge.components.aggregatedDetail.amountPerUnit.amount, analytics_economics_2024_03_15.economics.fees.charge.aggregatedDetail.promotionAmount.amount, analytics_economics_2024_03_15.economics.sales.orderedProductSales.amount, analytics_economics_2024_03_15.economics.fees.charge.aggregatedDetail.taxAmount.amount, analytics_economics_2024_03_15.economics.fees.charge.components.name, analytics_economics_2024_03_15.economics.fees.charge.components.aggregatedDetail.amount.amount, analytics_economics_2024_03_15.economics.netProceeds.perUnit.amount, analytics_economics_2024_03_15.economics.fees.charge.components.aggregatedDetail.taxAmount.amount, analytics_economics_2024_03_15.economics.childAsin, analytics_economics_2024_03_15.economics.sales.unitsOrdered, analytics_economics_2024_03_15.economics.startDate, analytics_economics_2024_03_15.economics.netProceeds.perUnit.currencyCode, analytics_economics_2024_03_15.economics.msku, analytics_economics_2024_03_15.economics.fees.charge.aggregatedDetail.amount.amount, analytics_economics_2024_03_15.economics.sales.netProductSales.amount, analytics_economics_2024_03_15.economics.fees.charge.aggregatedDetail.quantity, analytics_economics_2024_03_15.economics.fees.charge.aggregatedDetail.amountPerUnit.amount, analytics_economics_2024_03_15.economics.fees.charge.components.aggregatedDetail.promotionAmount.amount, analytics_economics_2024_03_15.economics.netProceeds.total.amount, analytics_economics_2024_03_15.economics.parentAsin]"
    }
  ]
}
```

## Your Environment

Happens in all environments
- Ubuntu 22.04 LTS - Node 20.12 LTS
- Postman (in-browser)
- Mac OS Sonoma 14.3 - Node 20.12 LTS

**Comment by leonardonakagawa** [comment]
Hi @hexrw,

Thanks for letting us know about this issue.

The SKU Economics report is still going to be released, and it was posted by mistake in the Schema Explorer, that is the reason you received the 403 error.

Make sure you are subscribed to our [RSS feeds updates](http://developer-docs.amazon.com/sp-api/changelog.rss) to know when the new dataset launches.

Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support

**Comment by hexrw** [comment]
In that case it should not be part of the documentation...

I understand Data Kiosk is currently in beta. However, you are openly encouraging it's use and even marking the Reports API as to-be-deprecated. You also said we are to be on the watch out for new datasets. Please hide the Economics dataset or at least mark it as unreleased.

![Screenshot 2024-05-15 at 19 31 23](https://github.com/amzn/selling-partner-api-models/assets/72889112/4c723c58-f525-4fb0-a385-79daca554af6)

**Comment by hexrw** [comment]
@leonardonakagawa, I would kindly request **more information** on this matter.

I understand the development process, still, could you tell us - are we talking about a **couple** more **days** before **release**? **Couple weeks**? **Couple months**? We would like to **use this** dataset for **our application** and we are **halting** the development of alternatives for now in the hope of this dataset being accessible **soon**.

Thank you for your time.

**Comment by ayies128** [comment]
@leonardonakagawa 
The new release was officially launched recently, but I am still encountering the same error.
https://developer-docs.amazon.com/sp-api/changelog/data-kiosk-reports-experience-general-availability-launch
Is everyone experiencing the same error, or is it just me?
I do not encounter any errors with the salesAndTraffic request.

**Comment by jakobhaugk** [comment]
I encountered the same error for the economics report.

Request:
POST https://sellingpartnerapi-eu.amazon.com/dataKiosk/2023-11-15/queries
```
  {
    "query": "{  analytics_economics_2024_03_15 {    economics(startDate: \"2025-05-21\", endDate: \"2025-05-21\", marketplaceIds: [\"A1PA6795UKMFR9\"])      { startDate }  }}"
  }
````

Response:
```
{
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Unauthorized to access requested fields.",
      "details": "Unauthorized to access: [analytics_economics_2024_03_15.economics.startDate]"
    }
  ]
}
````

Creating a query for the `analytics_salesAndTraffic_2024_04_24` report works without any issues.

Please provide a solution for this problem as soon as possible

**Comment by leonardonakagawa** [comment]
Hi all! 

Thanks for sharing this out.

Economics dataset are under Selling Partner Insights role, so can you please ensure if you have it attached to your developer profile and app? We released [this](https://developer-docs.amazon.com/sp-api/changelog/correction-data-kiosk-role-requirements) announcement about it last year.



Thanks,
Leonardo Nakagawa
Solutions Architect, Selling Partner API Developer Support
