### ISSUE TITLE
[FEATURE] Get customizable product info

### ISSUE THREAD

**Issue by krystian-rzepa** [amzn/selling-partner-api-models#571]
I checked all types of "Inventory" reports (https://developer-docs.amazon.com/sp-api/docs/report-type-values-inventory) and none of them return information about whether the product is configurable or not. I really need to be able to check if product is set as configurable or not. Can I get this product information in another way?

**Comment by harguph** [comment]
Hello @krystian-rzepa ,

- What does "the product is configurable" mean? 
- Can you provide examples of configurable products?
- Also, can you give an example of this (probably some ASIN's from the marketplace) ?

**Comment by krystian-rzepa** [comment]
Hi @harguph,
Thanks for reply.
By "the product is configurable" I mean products, you can customize (https://www.amazon.de/-/en/gp/help/customer/display.html?nodeId=201983050).
For example this: https://www.amazon.de/-/pl/dp/B09J55L67S?th=1

**Comment by harguph** [comment]
Hello @krystian-rzepa ,

There is no specific field that confirms this currently.

Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with queries related to SP API.
