### ISSUE TITLE
How can i generate C# classes and method using swagger and models

### ISSUE THREAD

**Issue by testniaccunt** [amzn/selling-partner-api-models#58]
How can i generate C# classes and method using swagger and models?
I am able to create one class at a time via editor.swagger but i am am recieving double class files because i need to make the same for every model. Can someone help me, please

**Comment by coder771** [comment]
@testniaccunt  were you able to find this?

**Comment by jadanah** [comment]
Here's a link to my repo which has all the amazon selling partner api client's with some usage samples built via nswag using httpclient vs. amazon's restsharp implementation.

https://github.com/jadanah/amazon-selling-partner-api-csharp-samples

**Comment by DawidWawrzyniak** [comment]
You can use swagger codegen from the command line.

`D:\tools>java -jar .\swagger-codegen-cli-2.4.17.jar generate -i 'D:\tools\selling-partner-api-models-main\models\vendor-direct-fulfillment-orders-api-model\vendorDirectFulfillmentOrdersV1.json' -o D:\tools\AmazonSpApi -l csharp -DpackageName='AmazonVendor.IO.Swagger' -t 'D:\tools\selling-partner-api-models-main\models\template\' --api-package ApiDirectFulfillmentOrders

D:\tools> java -jar .\swagger-codegen-cli-2.4.17.jar generate -i 'D:\tools\selling-partner-api-models-main\models\vendor-orders-api-model\vendorOrders.json' -o D:\tools\AmazonSpApi -l csharp -D'packageName=AmazonVendor.IO.Swagger' -t 'D:\tools\selling-partner-api-models-main\models\template\' --api-package ApiOrders
`

**Comment by puppsupr** [comment]
Hi @testniaccunt,

You can refer to this blog for steps on generating C# SDK : https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-the-c-sdk

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
