### ISSUE TITLE
Fetching product reviews

### ISSUE THREAD

**Issue by glureau-betclic** [amzn/selling-partner-api-models#62]
Can I use an API to fetch ebook authors, ebooks and product reviews?

Not sure I'm at the right place, bug thanks if you can guide me!

**Comment by vikingcodes** [comment]
@glureau-betclic You can get authors but not product reviews. Check this attributes of product catalogItems API

https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItemsV0.md#attributesetlist
