### ISSUE TITLE
v2024-03-20 API SetPackingInformation and GeneratePlacementOptions have 10-20 minutes processing time and randomly fail...

### ISSUE THREAD

**Issue by alexartisans** [amzn/selling-partner-api-models#637]
v2024-03-20 API SetPackingInformation and GeneratePlacementOptions have 10-20 minutes processing time and randomly fail... Is that an expected behavior where a plan creation will take hours if not days ?

Thank you

**Comment by mynamevincent** [comment]
我的经验也是这样的, 需要那么久,

你有遇到返回运输方式 没有空运小包的问题吗?

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up. Please create a developer support case so that we can better help you via calls etc.
