### ISSUE TITLE
[BUG] [SP-API] [Issue]  fulfillment-inbound-api-v2024-03-20: listtransportationoptions Lack of the airlift package option I need [AIR_SMALL_PARCEL or AIR_SMALL_PARCEL_EXPRESS]

### ISSUE THREAD

**Issue by mynamevincent** [amzn/selling-partner-api-models#638]
https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#listtransportationoptions

GET  /inbound/fba/2024-03-20/inboundPlans/wf18eabeed-b264-4452-8b0c-755be48bb6bc/transportationOptions

{"query":{"pageSize":"20","shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca"}

requestid : 5010eb6d-2fc4-4b01-9cdb-ac0e730c0e6e

request-date : 20240510T111441Z

caseid: 15255232711

Return results ：{"transportationOptions":[{"carrier":{"name":"Other"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to13f04994-aef3-48d7-b328-f0dbd8620889","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"Forest

Shipping New York

Inc","alphaCode":"FSNH"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to16f2ef9b-bd5b-4e80-8e94-4a4877a0606d","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"Forest

Shipping New York

Inc","alphaCode":"FSNH"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to1abec271-7787-4f63-9504-620186958757","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"ABF

FREIGHT SYSTEM

INC","alphaCode":"ABFS"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to1ef89e4b-cc5a-472c-8dcb-f2664afec9a4","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"Jiufang","alphaCode":"SZJD"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to2a516bd5-3c15-4572-8ddf-124269d1a2b9","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"United

States Postal

Service","alphaCode":"USPS"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to2b92681e-4030-42a2-b3ca-6f30c10e753c","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"SANDTORM

SHIPPING

LTD","alphaCode":"SDRP"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to3d7882ee-8a94-4d59-91e7-f1b16dedf943","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"WILSPILEN

TANKERS

INC","alphaCode":"WITK"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to4328030a-4bfa-4386-8ec3-47cd61f5c68e","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"SANDTORM

SHIPPING

LTD","alphaCode":"SDRP"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to6689e529-8f18-42de-a388-702da1873209","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"UNITED

PARCEL SERVICE

INC","alphaCode":"UPSN"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to71df26e9-ccae-4f8a-b5e0-60e67f891e8d","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"FEDERAL

EXPRESS

CORP","alphaCode":"FDE"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to7c3abb8a-3e28-485a-9891-88b9a4b4f50d","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"SMITH

& SONS FUEL & HEATING OIL

CO","alphaCode":"SQSF"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to83a920bb-f3c2-493e-88d0-8b666300fd6f","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"DHL

EXPRESS (USA)

INC","alphaCode":"DHLW"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"to9ed46c35-fd4a-4326-9248-f27a61465950","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"SMITH

& SONS FUEL & HEATING OIL

CO","alphaCode":"SQSF"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"toa12af2e4-f2d5-4428-885b-a78a4782cd7d","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"AMASS

INTERNATIONAL GROUP

INC","alphaCode":"AMIG"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"toaf8cfaab-128c-44c2-b311-d73be602e36a","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"UPS

FREIGHT","alphaCode":"UPGF"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"tob7daee10-56cc-46f2-b1b2-c279f75b241f","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"AMASS

INTERNATIONAL GROUP

INC","alphaCode":"AMIG"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"toca13b50f-577d-4674-9f00-62079a3e90d0","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"LES

INDUSTRIES HARNOIS

INC","alphaCode":"LINP"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"tocb9bac04-6b51-452a-9efc-32a16a33d130","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"WILSPILEN

TANKERS

INC","alphaCode":"WITK"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"tod7016435-2357-4588-9280-88825eea632a","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"Jiufang","alphaCode":"SZJD"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"tod87ca6df-9d75-462d-a943-6230208675ae","shippingSolution":"USE_YOUR_OWN_CARRIER"}],"pagination":{"nextToken":"d843ef03-b06e-40ee-bc0a-fc1135bf2164"}} and {"transportationOptions":[{"carrier":{"name":"Other"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"todb735b9e-6931-48ea-91b8-a2a9294c2c97","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"LES
INDUSTRIES HARNOIS
INC","alphaCode":"LINP"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"todc791158-a022-4886-bc5d-2bf912e3045a","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"BURLINGTON
NORTHERN SANTA FE RAILWAY
COMPANY","alphaCode":"BNSF"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"FREIGHT_LTL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"toeb912033-b273-4609-983b-2589218e5f49","shippingSolution":"USE_YOUR_OWN_CARRIER"},{"carrier":{"name":"FEDEX
GROUND
(CORPORATE)","alphaCode":"FDEG"},"shipmentId":"shde9ee8bd-211d-443e-8473-661085ca20ca","inboundPlanId":"wf18eabeed-b264-4452-8b0c-755be48bb6bc","shippingMode":"GROUND_SMALL_PARCEL","placementOptionId":"ple0f04d98-d1b5-4002-894e-b4dd174f00da","transportationOptionId":"tofb01ddae-470d-42ae-9bdb-9976484ed90c","shippingSolution":"USE_YOUR_OWN_CARRIER"}],"pagination":[]}

**Comment by harguph** [comment]
Hello @mynamevincent ,

Closing this ticket as you have opened a developer support case.

Regards
