### ISSUE TITLE
[BUG] [SP-API] [Issue] Fulfillment Inbound API v2024-03-20 Operation: trackingDetails  return operationStatus : FAILED operationProblems is empty

### ISSUE THREAD

**Issue by mynamevincent** [amzn/selling-partner-api-models#639]
调用提供追踪信息接口，返回操作ID : 27feac96-df8c-44cd-8329-542807352efb，查询状态结果返回 operationStatus : FAILED，而且没有返回任何原因，请问是什么原因，要怎么排查

1.提供跟踪号信息接口参数和返回:
RequestId : 18ab7343-03c5-4ef9-8549-2354c3b9883f

Timestamp : 20240510T110554Z

api : /inbound/fba/2024-03-20/inboundPlans/wf19edcae3-15a7-405f-9746-b37b3c7bdeb2/shipments/sh3ac3d6bf-ae41-47d1-933e-b981694b86b9/trackingDetails

request :
{"trackingDetails":{"spdTrackingDetail":{"spdTrackingItems":[{"boxId":"FBA180DW5332U000001","trackingId":"1ZE267590313996850"},{"boxId":"FBA180DW5332U000002","trackingId":"1ZE267590311363466"},{"boxId":"FBA180DW5332U000003","trackingId":"1ZE267590316682479"}]}}

response:
{"operationId":"27feac96-df8c-44cd-8329-542807352efb"}

2.查询第一点的接口的操作ID结果
RequestId : 30d4ea93-9bfe-4897-8f48-a5781cd33ecb

Timestamp : 20240510T111148Z

api : /inbound/fba/2024-03-20/operations/27feac96-df8c-44cd-8329-542807352efb

request :
{"trackingDetails":{"spdTrackingDetail":{"spdTrackingItems":[{"boxId":"FBA180DW5332U000001","trackingId":"1ZE267590313996850"},{"boxId":"FBA180DW5332U000002","trackingId":"1ZE267590311363466"},{"boxId":"FBA180DW5332U000003","trackingId":"1ZE267590316682479"}]}}

response:
{"operationStatus":"FAILED","operationId":"b09773b8-7e09-4391-a0d8-12908a622b99","operation":"updateShipmentTrackingDetails","operationProblems":[]}

**Comment by mynamevincent** [comment]
case id : 15255382851

**Comment by liangfeng520** [comment]
兄弟 解决了么    我也遇到同样的问题

**Comment by shreeharsh-a** [comment]
Please reach out to [developer support](https://developer.amazonservices.com/support) so that we can better help you with issues related to SP API.

`Note: SP API or docs related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
