### ISSUE TITLE
Getting the actual buyer email 

### ISSUE THREAD

**Issue by tswapnil** [amzn/selling-partner-api-models#64]
How do I get the actual buyer email ? 
I am able to get the email such as ***************@marketplace.amazon.in . I am unable to send an email to this address . Is that intentional ?

**Comment by vikingcodes** [comment]
@tswapnil amazon never show you real email id of buyer. Because it can create privacy issue. I think you can send email id for ***************@marketplace.amazon.in customer . I think many customer feedback management software send mail to encrypted email id.
