### ISSUE TITLE
clients/sellingpartner-api-aa-java/pom.xml using very old okhttp dependency that conflicts with Amazon Ads API dependencies 

### ISSUE THREAD

**Issue by csimoes1** [amzn/selling-partner-api-models#645]
clients/sellingpartner-api-aa-java/pom.xml has:
 ```
       <dependency>
            <groupId>com.squareup.okhttp</groupId>
            <artifactId>okhttp</artifactId>
            <version>2.7.5</version>
        </dependency>
```

Many other parts of my project are using okhttp3, something like:
 ```
      <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.12.0</version>
        </dependency>
```

Converting this is relatively straightforward.  It seems you just need to update the "LWAAuthorizationSigner" and "LWAClient" classes to use okhttp3 instead of okhttp, particularly for the Request object.  Reporting this just to bring it to your attention.  I was running my project in a servlet container, and the class path loading was causing a runtime crash due to okhttp having a class called ByteStream that was not resolving properly.

**Comment by harguph** [comment]
Thank you for bringing this up.

We are currently working on this.

**Comment by wienczny** [comment]
For the Java client please consider the following:
- replace the hard dependency with an optional one for okhttp
- move the RateLimitInterceptor from ApiClient to the sellingpartner-api-aa-java library
- have LWAAuthorizationSigner just calculate the header value
- add interceptors for okhttp2 / okhttp3 / or any other client library that add the header using LWAAuthorizationSigner.
- have a classes with a static methods to augment the client for every supported client library like:
        // Example for okhttp
        public static void extendApiClient(ApiClient apiClient, LWAInterceptor lwaInterceptor, RateLimitInterceptor rateLimiterInterceptor) {
        	if (lwaInterceptor != null) {
        		apiClient.getHttpClient().interceptors().add(lwaInterceptor);
        	}
        	if (rateLimiterInceptor != null) {
        		apiClient.getHttpClient().interceptors().add(rateLimiterInterceptor);
        	}
        }

This way an APIClient without custom templates would be possible. Easier to build with default configuration and less problems during updates. Alternative HTTP client libraries can be implemented.

**Comment by harguph** [comment]
Thank you for sharing the details.

**Comment by harguph** [comment]
Hello @csimoes1 , the changes in pom.xml have been deployed : https://github.com/amzn/selling-partner-api-models/blob/main/clients/sellingpartner-api-aa-java/pom.xml
