### ISSUE TITLE
Unauthorized error when getting FBA inventory quantity with FbaInventoryApi

### ISSUE THREAD

**Issue by sugaular** [amzn/selling-partner-api-models#646]
Currently, I am getting the FBA inventory count with FbaInventoryApi. I can obtain some inventory information. However, halfway through, it stops with an Unauthorized error. Why.

### Error message
swagger_client.rest.ApiException: (403)
Reason:
HTTP response headers: HTTPHeaderDict({'Server': 'Server', 'Date': 'Mon, 06 May 2024 02:41:11 GMT', 'Content-Type': 'application/json', 'Content-Length': '185', 'Connection': 'keep-alive', 'x-amz-rid': '9SAQP1T7NJQF5V7CDNQP', 'x-amzn-RequestId': '31198f34-1439-41bf-8093-eb37e0ddbee1', 'x-amz-apigw-id': 'OPF31198f341439', 'X-Amzn-Trace-Id': 'Root=1-66384347-31198f34143941bf', 'x-amzn-ErrorType': 'AccessDeniedException', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload'})
HTTP response body: {
"errors": [
{
"code": "Unauthorized",
"message": "Access to requested resource is denied.",
"details": "The access token you provided has expired."
}
]
}

**Comment by sugaular** [comment]
I didn't pay attention to Rate (requests per second), so I'll review it. excuse me.

**Comment by sugaular** [comment]
No, I added a 2 second wait time to 1 SKU.

**Comment by harguph** [comment]
Hello @sugaular ,

The error indicates the Access token is expired. Please ensure using an active token and make the request. Additionally, please ensure meeting the request-rate limit accordingly.

Please feel free to open a [developer support case](https://developer.amazonservices.com/support) sharing the full request and response if the issue persists.

**Comment by sugaular** [comment]
I got it to work by re-authenticating repeatedly.
thank you.

**Comment by harguph** [comment]
Thank you for confirming the same. Closing the ticket now.
