### ISSUE TITLE
Update Order statuses

### ISSUE THREAD

**Issue by tswapnil** [amzn/selling-partner-api-models#65]
What is the API to change order statuses ? hard to find it from the reference.

**Comment by BlinglingGirl** [comment]
feeds-api
do you know how to access the listings in my seller account ?

**Comment by vikingcodes** [comment]
@tswapnil Create a Order feeds and set order status.

Check these

https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feeds_2020-09-04.md

https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedType_string_array_values.md#order-feeds
