### ISSUE TITLE
During ListPlacementOptions it is returning Null - Fulfillment Inbound V2024-03-20 API

### ISSUE THREAD

**Issue by shantikolli** [amzn/selling-partner-api-models#655]
During ListPlacementOptions API Call,  it is returning Null . Attaching screenshot. Please look into this issue

![generateplacement](https://github.com/amzn/selling-partner-api-models/assets/170322609/ff78bb4d-189e-4ac4-9a70-cd44091dc8ea)

**Comment by harguph** [comment]
Hello @shantikolli ,

Per the documentation on [ListPlacementOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#get-inboundfba2024-03-20inboundplansinboundplanidplacementoptions) : Placement options must first be generated by the corresponding endpoint before becoming available.

Please ensure to invoke [generatePlacementOptions](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#post-inboundfba2024-03-20inboundplansinboundplanidplacementoptions) before invoking the ListPlacementOptions endpoint.

Please open a [developer support case](https://developer.amazonservices.com/support) sharing the full request and response if the issue persists.

Regards

**Comment by zaki-siddiqui** [comment]
When you run "GeneratePlacementOptions" operation it returns "operationId" so first you should run "GetInboundOperationStatus" with returned "operationId(which is returned by GeneratePlacementOptions)" and when it returns "Success" then call your "ListPlacementOptions" API.

**Comment by shantikolli** [comment]
@zaki-siddiqui 

Thank you !! It is no where mentioned in the Amazon documentation to check inbound operation and then make the next call. So after every operation we need to run the GetInboundOperationStatus or only specific to this call.

https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-use-case-guide#step-4-generate-and-view-options-for-destination-fulfillment-centers

**Comment by shantikolli** [comment]
@harguph 

I followed the same earlier. I executed the generatePlacementOptions before invoking the ListPlacementOptions endpoint.

**Comment by shantikolli** [comment]
@zaki-siddiqui 

thank you!!The operation id results in success status. However, I still have the same issue and the listplacementoptions is returning null.

**Comment by shantikolli** [comment]
any help would be appreciated..
