### ISSUE TITLE
how to access the listings in my seller account ?

### ISSUE THREAD

**Issue by BlinglingGirl** [amzn/selling-partner-api-models#66]
how to access the listings in my seller account ?

**Comment by vikingcodes** [comment]
@BlinglingGirl You can check your inventory via Inventory Report API.

Check these two articles.

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reports_2020-09-04.md
https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reportType_string_array_values.md#inventory-reports
