### ISSUE TITLE
fulfillment-inbound-api-v2024-03-20 (Broken)

### ISSUE THREAD

**Issue by stesmyth** [amzn/selling-partner-api-models#661]
We're still having the same issues... Can't get it to work regardless of what's posted on github.
And the feedback from the API itself is nonsense...

packingOptionId is always '0000'
supportedShippingConfigurations is always empty
contentInformationSource Barcode / Content Provided gives the same issue

"errors": [
{
"code": "InternalFailure",
"message": "We encountered an internal error. Please try again.",
"details": ""
}
]

Occurs on SetPackingInformation... every time

22/05/2024 15:33:47 | Status (createInboundPlan) [7898e7fb-38e1-4c75-a6bc-11cd87713137]
22/05/2024 15:33:52 | Status (IN_PROGRESS) [7898e7fb-38e1-4c75-a6bc-11cd87713137]
... ... ...
22/05/2024 15:34:00 | Status (SUCCESS) [7898e7fb-38e1-4c75-a6bc-11cd87713137]

22/05/2024 15:34:06 | Status (generatePackingOptions) [da6e77a6-2bcb-416e-b532-f0d426645119]
22/05/2024 15:34:11 | Status (IN_PROGRESS) [da6e77a6-2bcb-416e-b532-f0d426645119]
... ... ...
22/05/2024 15:34:13 | Status (SUCCESS) [da6e77a6-2bcb-416e-b532-f0d426645119]

"packingOptions": [
{
"packingGroups": [
"pg0ff66378-6c99-4280-a3b5-b89f66e78b82"
],
"fees": [],
"discounts": [],
"packingOptionId": "po00000000-0000-0000-0000-000000000000",
"supportedShippingConfigurations": [],
"inboundPlanId": "wf0cf8caec-7f52-4153-9b5e-c3e5da97913b",
"status": "ACCEPTED"
}
]

Note: generatePackingOptions Response status is always 'ACCEPTED' even before 'confirmPackingOption' is called.

Calling createInboundPlan and then picking up in the SendToAmazon GUI works fine, but generatePackingOptions via API doesn't. (UK Marketplace)

**Comment by shreeharsh-a** [comment]
Hi @stesmyth,
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
