### ISSUE TITLE
Fulfillment Inbound V2024-03-20 API createInboundPlan "FAILED" [cannot be more than 1 packline]

### ISSUE THREAD

**Issue by shadowJourney** [amzn/selling-partner-api-models#664]
createInboundPlan  In the use of some special scenarios, the error message is not very clear, can not accurately locate where the problem is

Scene 1:

![2](https://github.com/amzn/selling-partner-api-models/assets/112471375/d15107fa-ae23-4bb8-b85b-01af67ab1ce1)
![5](https://github.com/amzn/selling-partner-api-models/assets/112471375/83f37578-dcd7-4f65-a3e8-6af9c09124a2)

{
    "operationId": "92f1d6d1-9962-40a9-941b-1a2bf43bb28c",
    "inboundPlanId": "wf42874d50-989a-47e4-b6b3-93718decfc42"
}

When we submit goods in the range of 250-500, the error "ERROR: There cannot be more than 1 packline of individual unit of the same merchant SKUs while saving sku boxes" will appear, so we So we need to know what the limitations are. We need to know what the constraints are, such as pre-processing, size, packaging, specification and other criteria to distinguish
And in the process of waiting for the results, packaging line error waiting time is very long, whether it can be optimised, and reporting errors can be precise problem

Scene 2:

![3](https://github.com/amzn/selling-partner-api-models/assets/112471375/c0face6f-a6f6-408a-996b-13d30b0b78c4)
![4](https://github.com/amzn/selling-partner-api-models/assets/112471375/e11eced0-189b-488f-aab2-41d3e3e5de32)

{
    "operationId": "2c667e92-3bb8-4808-8bfc-98a7a05336e0",
    "inboundPlanId": "wfbc88f810-ad08-4c33-bca0-d5df697bd758"
}
When we submit more than 500 products, it will directly return "FAILED", there is no way to identify the specific cause of this error. But Fulfillment Inbound V2024-03-20 API document announced that the new interface allows 1500 sku.
I hope that in this kind of also reported the specific cause of the error to give us tips, as well as the formula of 1500 sku conditions and thresholds!

**Comment by shreeharsh-a** [comment]
Hi @shadowJourney,
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
