### ISSUE TITLE
Require more information on The `ShipFromSupplySourceId` attribute update on Order feeds:

### ISSUE THREAD

**Issue by charan1221** [amzn/selling-partner-api-models#669]
ShipFromSupplySourceId field has been added to the feed of post_order_fulfillment_data 

However, the xsd of the feed is not updated with the field, and the response of the API feed call is throwing a warning whenever the field is not populated.

**Comment by shreeharsh-a** [comment]
Thank you for bringing this up for us.

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`
