### ISSUE TITLE
Work with Sandbox

### ISSUE THREAD

**Issue by Andru4o** [amzn/selling-partner-api-models#694]
Hello.
Is there a user interface for sandboxing? To create orders, replenish the catalog and more. And then work with this through the API

**Comment by northerncodemky** [comment]
So 5 years after SP-API launched, and the team were aware of the need for a functionally useful sandbox, sellers still do not have that feature? Could someone from Amazon please describe how exactly they expect developers to adequately test their integrations using SP-API without testing in production? As a 2 trillion dollar company this is not an unreasonable expectation for developers to have of Amazon, surely?
