### ISSUE TITLE
Shipping address is incomplete in /orders/v0/orders/{orderId}/address

### ISSUE THREAD

**Issue by rogersv** [amzn/selling-partner-api-models#732]
I made a call to `/orders/v0/orders/{orderId}/address` to our own seller account to get a real order.
I got the order information but the shipping information was incomplete.

The response I got is below and the `xx...` contained correct data
```
{
    "payload": {
        "AmazonOrderId": "xxx-xxxxxxx-xxxxxxx",
        "ShippingAddress": {
            "PostalCode": "xxxxx",
            "City": "xxxxx",
            "CountryCode": "xx",
            "Name": ""
        }
    }
}
```
The "Name" should not be empty and a lot of other information is missing.

**EDIT**: Is this because of the app is in draft-state and the rest of the information is personal information?

Note:
The app is in draft-state and I have used self-auth to get the refresh-token.
(I used https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json as reference.)

**Comment by montagnamarco** [comment]
Is there any update on this? My company tried to apply for PII access, but sincerly, it's a terrible and overcomplicated process, it lasts months of wait with a very little percentage of success. Now our customer wants the connector but we can't finish it because of this.
