### ISSUE TITLE
Is x-amzn-RateLimit-Limit response header working?

### ISSUE THREAD

**Issue by Amrac** [amzn/selling-partner-api-models#746]
Hello,
I'm currently building my software with respect to Selling Partner API's usage plans,  and I do not get the x-amzn-RateLimit-Limit in the headers. 

Could you confirm that this feature is currently working and that I should get this x-amzn-RateLimit-Limit header?

`array(1) {
  [0]=>
  string(265) "HTTP/1.1 429 
Date: Sat, 31 Oct 2020 09:44:43 GMT
Content-Type: application/json
Content-Length: 134
Connection: keep-alive
x-amzn-RequestId: 08994608-0658-4072-b813-88a208b8e506
x-amzn-ErrorType: TooManyRequestsException
x-amz-apigw-id: VRTB2HecDoEF2yA=

"
}`

`array(1) {
  [0]=>
  string(134) "{
  "errors": [
    {
      "message": "You exceeded your quota for the requested resource.",
     "code": "QuotaExceeded"
    }
  ]
}"
}`

**Comment by johnkw** [comment]
This ticket should not be closed @shreeharsh-a

**Comment by shreeharsh-a** [comment]
Please reach out to developer support so that we can better help you with issues related to SP API.

`Note: SP API related issues / troubleshooting support is managed by a different team. We can help if the issue is related to the content published on this repo.`

**Comment by johnkw** [comment]
It would be helpful to leave the bug open until it's fixed, so people know where to look for information on this bug.
