### ISSUE TITLE
Best practice to receive Fees, Sales Prices and Product Data for many listings

### ISSUE THREAD

**Issue by stefnats** [amzn/selling-partner-api-models#75]
Hello,

our use case is that we sometimes need to retrieve all fees, sales prices and product data of all of a seller's listings.
With the old MWS API, this was possible with getting multiple listings at once, however we had always encountered rate throttling which we accepted. With the new API it's only possible to retrieve only one SKU/ASIN at a time. This means much more API Calls and much more time to retrieve. I believe this is not the best interest for Amazon.
I noticed that these fees are in no reports and the sales prices are also in no reports.

So what would be the best practice to receive Fees, Product Data and Sales Prices for all listings?
To be more exact

- Fees = All available fees like Referral Fee, Promotions, FBA Fees, etc. based on a price input
- Product Data = ASIN, Title, Images, Attributes, Sales Ranks, Variations, etc.
- Sales Prices = Current online price and - if it exists - a strikethrough price

What are the best practices for retrieving data for lots of listings (>100k)?

Thanks in advance!

**Comment by DawidWawrzyniak** [comment]
You can use report API and report: GET_MERCHANT_LISTINGS_ALL_DATA

**Comment by happy-bear-x** [comment]
> You can use report API and report: GET_MERCHANT_LISTINGS_ALL_DATA

Hello, I get this report, but no sale price. Can you get sale price?
