### ISSUE TITLE
Create shipments - Invalid input

### ISSUE THREAD

**Issue by rusanpas** [amzn/selling-partner-api-models#78]
I am trying to make a call to Merchanfullfillment - create shipment (POST /mfn/v0/shipments ), but it returns the error 

```
{
    "errors": [
        {
            "code": "InvalidInput",
            "message": "Invalid Input",
            "details": ""
        }
    ]
}
```
I have tried in the sandbox and the call is successful. You can tell me that it may be wrong ...I think the json is correct.

This is what is being sent without personal data :
```
{
   "ShipmentRequestDetails":{
      "AmazonOrderId":"...",
      "ItemList":[
         {
            "OrderItemId":"3183...459",
            "Quantity":1
         }
      ],
      "ShipFromAddress":{
         "Name":"...",
         "AddressLine1":"..",
         "Email":"...",
         "City":"...",
         "PostalCode":"...",
         "CountryCode":"ES",
         "Phone":"..."
      },
      "PackageDimensions":{
         "Length":17.6,
         "Width":13.7,
         "Height":11.2,
         "Unit":"inches"
      },
      "Weight":{
         "Value":202.1,
         "Unit":"oz"
      },
      "ShippingServiceOptions":{
         "DeliveryExperience":"DeliveryConfirmationWithoutSignature",
         "CarrierWillPickup":false
      }
   },
   "ShippingServiceId":"SEUR_ES_MFN_24",
   "ShippingServiceOfferId":"....."
}
```

Case ID : #6880732102

Thanks

**Comment by poeily** [comment]
Hello, have you solved your problem. I have the same problem as you, on the createreport method

**Comment by franciscocha** [comment]
@rusanpas You are missing the StateOrProvinceCode property in your Address

**Comment by franciscocha** [comment]
@poeily if you post your request I might be able to help you troubleshoot.

**Comment by rodrifed** [comment]
Hello @rusanpas ,

In order to correctly resolve this issue, please [open a support case](https://developer.amazonservices.com/support) so we can pursue the investigation as additional details are required from your end.

Thanks,
Federico
Selling Partner API Developer Support
