### ISSUE TITLE
How can I POST new product?

### ISSUE THREAD

**Issue by GrelaM100** [amzn/selling-partner-api-models#811]
Hi,
I am trying to POST product using SP-API. As far as I understand I should create feed using createFeed method from feeds-api with feedType = " POST_PRODUCT_DATA". However I don't know what feedOptions should I set. In use case guide I found request example for an Easy Ship order. Where can I find information about specific values of feedOptions parameter for every feedType?

**Comment by mtkumar82** [comment]
Hello Everyone,

I am getting below warning when trying to submit feed with feed type: "POST_PRODUCT_DATA". Below link saying 

Feed types that will be sunset on March 31, 2025:

    POST_PRODUCT_DATA
    POST_INVENTORY_AVAILABILITY_DATA
    POST_PRODUCT_OVERRIDES_DATA
    POST_PRODUCT_PRICING_DATA
    POST_PRODUCT_IMAGE_DATA
    POST_PRODUCT_RELATIONSHIP_DATA
    POST_FLAT_FILE_INVLOADER_DATA
    POST_FLAT_FILE_LISTINGS_DATA
    POST_FLAT_FILE_BOOKLOADER_DATA
    POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA
    POST_FLAT_FILE_LISTINGS_DATA
    POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA
    POST_UIEE_BOOKLOADER_DATA



The feed type used for this submission via the Selling Partner Feeds API will be sunset on March 31, 2025. To continue submitting listings data through APIs (including pricing and inventory updates), you will need to migrate to the Selling Partner Listings Items APIs or the JSON_LISTINGS_FEED feed type submitted via the Selling Partner Feeds API. If you have received this message through a third-party solution, please contact your solution provider. If you are using the Selling Partner Feeds API directly, more details on migrating can be found on the Selling Partner API developer documentation website here : https://developer-docs.amazon.com/sp-api/changelog/deprecation-of-feeds-api-support-for-xml-and-flat-file-listings-feeds.



Anybody can please help me how I can use  JSON_LISTINGS_FEED  for      POST_PRODUCT_DATA
    POST_INVENTORY_AVAILABILITY_DATA
    POST_PRODUCT_OVERRIDES_DATA
    POST_PRODUCT_PRICING_DATA

feed types, I am able to find proper documenttation how to use these feed type with JSON_LISTINGS_FEED ?

Waiting for your valuable support
