### ISSUE TITLE
GET /fba/inbound/v0/shipments, Operation: getShipments, NextToken not work

### ISSUE THREAD

**Issue by FexusZ** [amzn/selling-partner-api-models#822]
Hello,
When I call the getShipments method, I get the first list with the 50 shipments, but when I try to get the next 50 shipments via the NextToken parameter, I get exactly the same list.

Is the NextToken parameter implemented?

first request : 
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments
?LastUpdatedAfter=2020-11-01T10:21:20+00:00
&LastUpdatedBefore=2020-12-01T10:21:20+00:00
&MarketplaceId=A13V1IB3VIYZZH
&QueryType=DATE_RANGE
&ShipmentStatusList=WORKING,SHIPPED,RECEIVING,CANCELLED,DELETED,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN

second request : 
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments
?LastUpdatedAfter=2020-11-01T10:23:07+00:00
&LastUpdatedBefore=2020-12-01T10:23:07+00:00
&MarketplaceId=A13V1IB3VIYZZH
&NextToken= {TOKEN}
&QueryType=NEXT_TOKEN
&ShipmentStatusList=WORKING,SHIPPED,RECEIVING,CANCELLED,DELETED,CLOSED,ERROR,IN_TRANSIT,DELIVERED,CHECKED_IN

**Comment by emakunin** [comment]
Still doesn't work.

https://github.com/amzn/selling-partner-api-models/issues/4205
