### ISSUE TITLE
No access to tax related information

### ISSUE THREAD

**Issue by fernlop** [amzn/selling-partner-api-models#843]
I can't access any information related to taxes. 
I should have access to everything. I checked every role in the developer profile and got accepted.

**Examples:**
Get VAT ID for business orders in **/orders/v0/orders** or **/orders/v0/orders/{orderId}** API:
In the old MWS API, there was an object called **TaxRegistrationDetails** which contained the registration id and country. 
The new SP API doesn't return this object even with business orders that have a registered tax id. 

I'm not able to upload tax invoices through a feed type **UPLOAD_VAT_INVOICE**:
I can create and upload other feeds but when trying to upload the invoices i get an unauthorized error:
`{"code":"Unauthorized","message":"Access to the resource is forbidden","details":""}`

I can't get financial events through **/finances/v0/financialEventGroups** or **/finances/v0/financialEvents** API:
When i try to get financial event i receive an unauthorized error.:
`{"message":"Access to requested resource is denied.","code":"Unauthorized","details":""}`
I have access the financial events for an order with **/finances/v0/orders/{orderId}/financialEvents**, but everything else will result in an error.

It seems like this is all related to restrictions to tax related information. I double checked my access requested in the developer profile and even re-submitted the form and used a new generated refresh token. 

**Contact with MWS Support:**
I opened a case (6546747312) with MWS Support and they told me they are not responsible for "the review or appeal of Developer Registration and Assessment forms" and have forwarded this to the Developer Registration Team, but they never replied me. 

> Hello from Amazon Selling Partner Support,
> 
> We understand that you have questions about MWS PII access.
> 
> The Amazon MWS Support team is not involved in the review or appeal of Developer Registration and Assessment forms, so we are not able to assist you directly. However, we have informed the Developer Registration Team and they will contact you in the following 3 business days in order to help you with the Registration Process.
> 

Then i opened a new case (6573616692) with the Team that should be responsible for this but still got no response too. 

I want to make clear, i don't have general problems to access the SP API, just with this specific tax related endpoints!

**Comment by benjiam-gh** [comment]
> Has someone found a solution? I can not get the buyer-tax-registration-id for FBA orders. The report GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL only returns buyer-tax-registration-country and buyer-tax-registration-type and the /orders/v0/orders/{orderId} returns NULL for TaxRegistrationDetails.

I'm still having the same problem. Has anyone found a solution to retrieve VAT numbers for AFN orders without having Amazon VAT Calculation Service active?
