### ISSUE TITLE
Can't make requests to regions other than North America with a self-authorized app

### ISSUE THREAD

**Issue by jlevers** [amzn/selling-partner-api-models#854]
I'm working with a client to try to expand their Selling Partner API application to the European and Far East markets, but for some reason I can't make requests to the EU and FE endpoints with their credentials. They've created support tickets related to this issue and been told that their credentials should work globally, so their application for developer credentials in Europe has been denied.

However, when I try to make a request to one of the non-NA endpoints, I get this infamous error:
```json
{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
```

When I try the exact same request, using the LWA and AWS info for another app I'm working on that was created from the `Develop Apps` page of the EU Seller Central dashboard (in a different Seller Central account), everything works fine. This implies to me that this is not an issue with the STS URL I'm using, or the region I'm specifying, because the code behaves as expected when I use credentials from an app created on the `Develop Apps` page of my EU dashboard.

This issue crops up both when I use authentication code that I personally wrote, and when using the pre-written Java SDK that provides the authentication logic. I've tried using my personal SP API credentials as well, and those also fail when I try to use the EU or NA endpoints.

Could someone from Amazon please provide some insight into what might be going on here? Thank you :)

**Comment by AhmadHumayun** [comment]
@jlevers in self authorize only NAM region appearing as my seller account and developer account are within that, no option for EU region, is there is way or am i missing something to have multi region tokens, or we still need to create multiple applications
