### ISSUE TITLE
[BUG] Documentation FulFillment-Inbound getShipmentItemsByShipmentId Bug and inconsistent workflow in endpoint

### ISSUE THREAD

**Issue by JacksonJeans** [amzn/selling-partner-api-models#870]
**Describe the bug**
The error affects the documentation itself and the domain logic of the `getShipmentItemsByShipmentID` operation.

I only ever get the same response from this operation from the second request using `NextToken`.

In my opinion, the API should only set `NextToken` as required instead of `MarketplaceId` and `shipmentId` in combination with the `NextToken`.

If I omit the MarketplaceId and shipmentId in the second call and only specify the NextToken, my call is invalid.

**URL of the content on GitHub**
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getShipmentItemsByShipmentId](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#getShipmentItemsByShipmentId)

[https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#GetShipmentItemsResult](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#GetShipmentItemsResult)

**Description of what the documentation currently says**

Currently, the operation is based on the assumption that no `NextToken` can be specified and that the entire list of items sent with the shipment can be found in ItemData in one call.

getShipmentItemsByShipmentId Operation:
Type | Name | Description | Schema
-- | -- | -- | --
Path | shipmentId  required | A shipment identifier used for selecting items in a specific inbound shipment. | string
Query | MarketplaceId  required | A marketplace identifier. Specifies the marketplace where the product would be stored. | string

GetShipmentItemsResult:
Name | Description | Schema
| ---- | ---- | ---- |
|   ItemData   |   A list of item information for an inbound shipment.   |   InboundShipmentItemList   |
|   NextToken   |   When present and not empty, pass this string token in the next request to return the next response page.   |    string  |

**Description of what the documentation should say**
The documentation should state, already in the operation, whether a NextToken can be specified as a parameter and whether MarketplaceId and shipmentId must also be specified in the second call.

Currently, the documentation regarding the operation does not indicate that a NextToken is expected or can be specified. Unlike the documentation for, for example, the Order, Feeds and Report API.

**Additional context**
In addition, the inbound interface does not work consistently against the orders, reports, and feeds endpoints. 
The query string in the URI must not be preceded by "/", which is necessary in the other requests. This also applies to the calculation and creation of the signature for the canonical request. 

For example:
My URI for orders: 
getOrder:
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/408-9433449-0649117/
is valid.

and here with query string:
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders/?LastUpdatedAfter=2020-12-15T23%3A00%3A00&MarketplaceIds=A1805IZSGTT6HS&MarketplaceIds=A1PA6795UKMFR9&MaxResultsPerPage=100
is valid.

In the InboundAPI, however:

getTransportDetails:
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/transport
is valid.

https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/transport/ 
will be invalid.

and here with query string:
getShipmentItemsByShipmentId
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/items?MarketplaceId=A1PA6795UKMFR9&shipmentId=FBA15DDQDL4V

is valid.

https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15DDQDL4V/items/?MarketplaceId=A1PA6795UKMFR9&shipmentId=FBA15DDQDL4V

will be invalid.

Finding that out first was very hard.

**Comment by kpconnell** [comment]
This was never resolved and is a major issue in the documentation.

**Comment by emakunin** [comment]
still relevant

**Comment by emakunin** [comment]
UPD
``
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15GRY6VTR/items?QueryType=NEXT_TOKEN&NextToken=AAAAAAAAAQBgs%2FmNHCJa9L4yvNjDU1Y6VQEAAAAAAAB1u1QZJsamgmfFrIP82PrznoS9whhTuRa0CQ2tWnXdP1Frq1uIiqBAmmn87p%2FN2HEw7VdFDDE3TPo%2FDzi%2Fvupnmr3KB9fFOkMoovqySAUXp%2BWt0wjLnC%2FvK8hpK0Dr%2Fx%2BEmlxVu7mjb81XzMqr7TzFrtyO0V2Hv%2BJ73wFKQ1W6iiFwGNxy%2BG1H5nP%2FdWw%2FJyjt%2FQ8XyPNTT%2B0eHfaWlILVSLL2Pk0ETJ6YEgPi07v%2FCAWz0t6NyefexGOQZ%2FWB%2FJ24LM9ozbWs4kKxs6LPAS9enfbz6YMloCM1uO02cfKalmMN2zHbZIY35JoeX1AiLKuYHxKMUxsLKaV8GQBoVsKBIDrx9d37j1hBifLcv%2FKwcXYDMLs1d4GUX%2FyCYnarfUU9NiXd9LDRR4tHraDOAOKdPXcnsqzNb2dfQx3pvX%2BKZ%2FV%2BVbj15b1gatp8VccOqz%2BBzwd%2FVA%3D%3D
``

The request is encoded, I don't see any issues. The token is retrieved with a previous call
```
https://sellingpartnerapi-eu.amazon.com/fba/inbound/v0/shipments/FBA15GRY6VTR/items?QueryType=SHIPMENT
```

I tried to follow the nextToken, and all next calls return same results (4 items in my case) with nextToken present.

**Comment by monkeyking123g** [comment]
To use getShipmentItemsByShipmentId, the next token is not needed; it goes into an infinite loop, which is a bug. I checked and it already returns all the data for that shipmentId. I hope this helps someone. 
Examples:
```javascript
   const response = await sellingPartner.callAPI({
            operation: 'getShipmentItemsByShipmentId',
            endpoint: 'fulfillmentInbound',
            path: {
              shipmentId: input.ShipmentId,
            },
            query: {
              MarketplaceId: 'APJ6JRA9NG5V4',
            },
          });
```

**Comment by mafge** [comment]
Hi @emakunin and everyone else,
thanks for pinging me on this one!
We are currently working on moving everyone to the v2024-03-20 API, so honestly we won't do any fixes on the v0 API anymore and put all effort into the new API. Sorry for that!

**Comment by emakunin** [comment]
Hi @monkeyking123g,
> returns all the data for that shipmentId. I hope this helps someone.

Did you try it with shipments containing more than 200 items? The page size is 200

**Comment by mafge** [comment]
@emakunin Can you please tell me which api/data you are looking for and is currently missing compared to v0? There are some operations like getLabel which are used from v0, however the new API should cover all other aspects. Thanks!

**Comment by emakunin** [comment]
Amm... 

Offtop:
With all the respect. Nothing personal.
Does Amazon actually analyze the complaints and customer feedbacks you receive in the repo? Many people mention bugs/missed fields/etc here. I personally reported 2-3 tickets like that. You are effectively asking your customers to compile a TODO list for you.
As a minimum it is frustrating to see that all previous reports, details and explanations provided are just ignored or lost?. How can I be sure that if I spend my time it won't be wasted again? 

Constructive part:
As a rule of thumb I'd mention all not deprecated apis in v0 that exist there cause there's no equivalent in the new api.
```
getLabels
getBillOfLading
getPrepInstructions
getShipments
getShipmentItemsByShipmentId
getShipmentItems 
```
Issues I can remember (you can find them in the tickets)
1. There's no way to understand preparation/packing details in a reliable way. 
2. Closed shipments are getting updated even after being closed
3. Once you print labels via API the inbound plan is not marked as "ready to ship in SC"
4. There are no dates in the shipments (neither api params, neither returned entities have them). After I recive a shipment I cannot relate it to a specific date/report. I have to go to SC and check manually. (it's valid for new API version as well btw)

Should we write a PRFAQ and BRD ? I'd demand an invite to OP1 meeting planning in this case :)

**Comment by monkeyking123g** [comment]
Hi @emakunin , I haven't tried, but maybe in that case NextToken is needed ?

**Comment by mafge** [comment]
@emakunin,
Sorry for the misunderstanding, I actually meant what is missing for this specific issue. I know that there is currently a lot of problems with the existing Fulfilment Inbound API and the communication from Amazon, but be assured that we are working on improving the API as well as the communication with devs. Please be also assured that we are listening to your feedback and consider all the information you are providing. Thanks for providing your input!
