### ISSUE TITLE
[BUG] POST /uploads/2020-11-01/uploadDestinations/{resource} not working!

### ISSUE THREAD

**Issue by fengmiq** [amzn/selling-partner-api-models#900]
**If you need help troubleshooting a problem with Selling Partner APIs, please [open a support case](https://developer.amazonservices.com/support). Issues are for reporting documentation bugs and enhancements only.**

**Describe the bug**
what is the url?pls look the photo

**URL of the content on GitHub**
[https://github.com/amzn/selling-partner-api-docs/blob/main/references/uploads-api/uploads_2020-11-01.md#createuploaddestinationforresource](url)

**Description of what the documentation currently says**
the url is "2020-11-01"?v1?
**Description of what the documentation should say**

**Screenshots**
![error](https://user-images.githubusercontent.com/43661323/103329917-0852df80-4a9a-11eb-8d0f-57ea592cf330.png)

**Additional context**
return error:403 Forbidden,message:Access to requested resource is denied,other api is ok, I need help，can you support one demo about uploads-api and messaging-api

**Comment by sheep110** [comment]
> Hello [@ShivikaK](https://github.com/ShivikaK),  你好 ， We have not received any updated here or on support regarding this issue, we are try to upload the file through the cURL operation and we receive a 204 response, instead of an expected 200 response. Please let us know what needs to be done differently.我们尚未收到任何关于此问题的更新或支持信息。我们尝试通过 cURL 操作上传文件，但收到了 204 响应，而不是预期的 200 响应。请告知我们您需要采取哪些不同的措施。
> 
> Here is the case ID : 7070359842, and a screenshot of the url and curl response,这是案例 ID：7070359842，以及 url 和 curl 响应的屏幕截图， ![image](https://user-images.githubusercontent.com/3126895/124978251-2869e980-e04f-11eb-8d79-94942494966d.png)
> 
> Thanks  谢谢

Hello, 
how do you  send this url  to get  204,  but  my  send  it  get  403 ： access  denied

**Comment by sheep110** [comment]
> Hello [@ShivikaK](https://github.com/ShivikaK),  你好 ， We have not received any updated here or on support regarding this issue, we are try to upload the file through the cURL operation and we receive a 204 response, instead of an expected 200 response. Please let us know what needs to be done differently.我们尚未收到任何关于此问题的更新或支持信息。我们尝试通过 cURL 操作上传文件，但收到了 204 响应，而不是预期的 200 响应。请告知我们您需要采取哪些不同的措施。
> 
> Here is the case ID : 7070359842, and a screenshot of the url and curl response,这是案例 ID：7070359842，以及 url 和 curl 响应的屏幕截图， ![image](https://user-images.githubusercontent.com/3126895/124978251-2869e980-e04f-11eb-8d79-94942494966d.png)
> 
> Thanks  谢谢

Hi @pramohs :
how  do you send  url  and  return  204,  and I  still get  400:  Conflicting query string parameters: acl, policy, Can you help  me, Thanks

**Comment by arpitmantri7501** [comment]
I am also facing the same issue
Request ID: d635821e-0eef-424e-816b-7e0acdea6393
Timestamp: 2026-01-18T07:32:08 GMT
Error: "403 Unauthorized - Access to requested resource is denied"
Endpoint: /uploads/2020-11-01/uploadDestinations/aplus/2020-11-01/contentDocuments
Purpose: "Uploading images for A+ Content API"
