### ISSUE TITLE
{"error_description":"The request has an invalid grant parameter : refresh_token","error":"invalid_grant"}

### ISSUE THREAD

**Issue by B627336** [amzn/selling-partner-api-models#921]
Hi, anyone came across this error? When I try to exchange the refresh token for an access token, I get this error message. However, this is only the case when using the refresh token generate with authorization workflow. When I use the refresh token from self-authorization, the access token issuance works fine.

**Comment by ericblade** [comment]
exchanging it within milliseconds still provides this error.  
Strongly suspecting that i'm being given invalid oauth codes.
