### ISSUE TITLE
Feature Request: Api to download invoices generated by Amazon on our behalf

### ISSUE THREAD

**Issue by florianbepunkt** [amzn/selling-partner-api-models#922]
We are not enrolled in the VCS (Vat calculation service), but due to changes in UK tax law, Amazon is generating invoices on our behalf. 

Currently we have no way of downloading these invoices and/or the invoice numbers. This makes bookkeeping a nightmare since we need to download all these invoices manually through seller central.

Please provide an endpoint for getting information about these invoices like invoice number and a possibility to download the PDF

**Comment by quangmata2707** [comment]
![test](https://github.com/amzn/selling-partner-api-models/assets/67143940/59da08a4-735a-431c-90e8-1b6058b08e7b)
![test2](https://github.com/amzn/selling-partner-api-models/assets/67143940/8d4e5836-c3b8-42a8-b5ef-dc3191c23d98)
