### ISSUE TITLE
Unauthorized, Access to requested resource is denied

### ISSUE THREAD

**Issue by cdragon1116** [amzn/selling-partner-api-models#943]
I have been trying to use Amazon SP-API recently but somehow I am getting Unauthorized message.

Confirmed that 
- my AWS IAM role has access policy for `execute-api` 
- I'm able to get the `x-amz-access-token` from token endpoint 
- Able to generate `id/secret/session_token` from `assumeRole` and attach as `x-amz-security-token`

I tried on the postman using `AWS Signature` Auth and still getting same error:
```
{
    "errors": [
        {
            "message": "Access to requested resource is denied.",
            "code": "Unauthorized",
            "details": ""
        }
    ]
}
```

**Comment by QasimMughal05** [comment]
I think credentials Issue
