### ISSUE TITLE
/mfn/v0/shipments The Amazon Terms and Conditions were not accepted

### ISSUE THREAD

**Issue by lifu521** [amzn/selling-partner-api-models#962]
The Amazon Terms and Conditions were not accepted
I want to create logistics information, but the above prompt appears, how do I solve it

**Comment by jason-huboo** [comment]
> > The Amazon Terms and Conditions were not accepted I want to create logistics information, but the above prompt appears, how do I solve it
> 
> 你的问题有解决了吗？我也遇到一些merchantFulfillment类的问题，能否一起探讨一下，我的微信号jsonluo

I had the same issue. Caused by not accepting the terms here:
**https://sellercentral.amazon.co.uk/orders-st/terms-and-conditions**
