### ISSUE TITLE
Documentation getOrders function and getOrderItems Missing field Who knows why

### ISSUE THREAD

**Issue by qingwuit** [amzn/selling-partner-api-models#980]
I don't know if I didn't get the complete information because of `version = beta`

#### For example:
`OrderList`  =>  `orderTotal`
`OrderItemList`  =>  `itemPrice`

#### The data information I got:
```json
{
      "ASIN":"B08PFxxx",
      "OrderItemId":"5830xxxx6330",
      "SellerSKU":"2R-YQMU-xxx",
      "Title":"USB C Female to USB Male Adapter .........",
      "QuantityOrdered":1,
      "QuantityShipped":0,
      "ProductInfo":{
          "NumberOfItems":"1"
      },
      "PromotionIds":[
          "US Core Free Shipping xxx",
          "VPxxxxpon"
      ],
      "IsGift":"false",
      "IsTransparency":false
  }
```

**Comment by wolendranh** [comment]
Hi! @qingwuit Is there an official documentation stating that while order is in `Pending` state, or other non `Shipped` state, `orderTotal `, `itemPrice` are empty?
