### ISSUE TITLE
Merchant Fulfillment - getEligibileShipmentServices - Invalid Input

### ISSUE THREAD

**Issue by ghost** [amzn/selling-partner-api-models#996]
I am using the POST /mfn/v0/eligibleShippingServices endpoint but if I include the _ShipmentRequestDetails > MustArriveByDate_ or _ShipmentRequestDetails > ShipDate_, I get the error Invalid Input back.

I am formatting the date as yyyy-MM-ddTHH:mm:ssZ which to my understanding is correct for the ISO 8601 datetime format. Can anyone advise if they have had this problem and if so, how they resolved it?

**Comment by franciscocha** [comment]
> This is the body I requested:
> 
> { "shipmentRequestDetails": { "amazonOrderId": "XXXXX", "itemList": [ { "orderItemId": "XXXX", "quantity": 1 } ], "packageDimensions": { "height": 30.65, "length": 100.03, "unit": "CENTIMETERS", "width": 50.25 }, "sellerOrderId": "1733935466552OO6iXRRu", "shipFromAddress": { "addressLine1": "XXXXXX", "city": "STAMFORD", "countryCode": "US", "email": "XXXXX", "name": "XXXXX", "phone": "+1 xxx-xxx-xxx ext. 55307", "postalCode": "06907-1412", "stateOrProvinceCode": "CT" }, "shippingServiceOptions": { "carrierWillPickUp": false, "declaredValue": { "amount": 678.88, "currencyCode": "USD" }, "deliveryExperience": "DELIVERYCONFIRMATIONWITHOUTSIGNATURE" }, "weight": { "unit": "G", "value": 860.3 } } }
> 
> Always return:apiClient error :{ "errors": [ { "code": "InvalidInput", "message": "Invalid Input", "details": "" } ] }
> 
> I hope I can get some help

Your request is using amazonOrderId instead of AmazonOrderId. (All of the other properties in your request also have this issue) The property names are case sensitive. Make sure to check the model documentation. https://github.com/amzn/selling-partner-api-models/blob/main/models/merchant-fulfillment-api-model/merchantFulfillmentV0.json#L68-L99

`{
    "ShipmentRequestDetails": {
        "AmazonOrderId": "903-5563053-5647845",
        "ItemList": [
            {
                "OrderItemId": "52986411826454",
                "Quantity": 1
            }
        ],
        "PackageDimensions": {
            "Height": 10.25,
            "Length": 10.25,
            "Unit": "inches",
            "Width": 10.25
        },
        "ShipFromAddress": {
            "AddressLine1": "300 Turnbull Ave",
            "City": "Detroit",
            "CountryCode": "US",
            "Email": "jdoeasdfllkj@yahoo.com",
            "Name": "John Doe",
            "Phone": "7132341234",
            "PostalCode": "48123",
            "StateOrProvinceCode": "MI"
        },
        "ShippingServiceOptions": {
            "CarrierWillPickUp": false,
            "CarrierWillPickUpOption": "ShipperWillDropOff",
            "DeliveryExperience": "NoTracking"
        },
        "Weight": {
            "Unit": "oz",
            "Value": 10.25
        }
    }
}`

**Comment by hj2xx2hj-888** [comment]
Thank you very much for your answer to the previous question. According to your answer, I have corrected the case problem of the request parameter. The request parameter body is now as follows:


{
    "ShipmentRequestDetails": {
        "AmazonOrderId": "000-00000-0000000",
        "SellerOrderId": "fdsafdsfdf",
        "ItemList": [
            {
                "OrderItemId": "117125951263561",
                "Quantity": 1
            }
        ],
        "ShipFromAddress": {
            "Name": "xxx",
            "AddressLine1": "xxx",
            "Email": "00000000@marketplace.amazon.com",
            "City": "STAMFORD",
            "StateOrProvinceCode": "CT",
            "PostalCode": "06907-1412",
            "CountryCode": "US",
            "Phone": "+1 000-00-0000 ext. 55307"
        },
        "PackageDimensions": {
            "Length": 100.03,
            "Width": 50.25,
            "Height": 30.65,
            "Unit": "centimeters"
        },
        "Weight": {
            "Value": 860.3,
            "Unit": "g"
        },
        "ShippingServiceOptions": {
            "DeliveryExperience": "DeliveryConfirmationWithoutSignature",
            "DeclaredValue": {
                "CurrencyCode": "USD",
                "Amount": 526.41
            },
            "CarrierWillPickUp": false
        }
    }
}

But still return the same error, apiClient error :{
"errors": [
{
"code": "InvalidInput",
"message": "Invalid Input",
"details": ""
}
]
}   waiting for your answer again .

**Comment by franciscocha** [comment]
> Thank you very much for your answer to the previous question. According to your answer, I have corrected the case problem of the request parameter. The request parameter body is now as follows:
> 
> { "ShipmentRequestDetails": { "AmazonOrderId": "000-00000-0000000", "SellerOrderId": "fdsafdsfdf", "ItemList": [ { "OrderItemId": "117125951263561", "Quantity": 1 } ], "ShipFromAddress": { "Name": "xxx", "AddressLine1": "xxx", "Email": "[00000000@marketplace.amazon.com](mailto:00000000@marketplace.amazon.com)", "City": "STAMFORD", "StateOrProvinceCode": "CT", "PostalCode": "06907-1412", "CountryCode": "US", "Phone": "+1 000-00-0000 ext. 55307" }, "PackageDimensions": { "Length": 100.03, "Width": 50.25, "Height": 30.65, "Unit": "centimeters" }, "Weight": { "Value": 860.3, "Unit": "g" }, "ShippingServiceOptions": { "DeliveryExperience": "DeliveryConfirmationWithoutSignature", "DeclaredValue": { "CurrencyCode": "USD", "Amount": 526.41 }, "CarrierWillPickUp": false } } }
> 
> But still return the same error, apiClient error :{ "errors": [ { "code": "InvalidInput", "message": "Invalid Input", "details": "" } ] } waiting for your answer again .

I would try it without the declared value.
